### ISSUE TITLE
opening any nvm file results in... fatal: not a git repositroy (or any of the parent directories): .git

### ISSUE THREAD

**Issue by Abh15h3k** [nvim-telescope/telescope.nvim#1002]
i just installed nvm ( node vresion manager NVM_DIR=~/.config/nvm ). 

If i open any file in the nvm directory from outsite the nvm directory ( i.e. pwd != ~/.config/nvm ). the buffer gets flooded with the `fatal: not a git repositroy (or any of the parent directories): .git`

![Screenshot from 2021-07-16 14-41-52](https://user-images.githubusercontent.com/40197742/125923986-9d46e07d-95ef-4b96-bc6c-de57197b68c0.png)
![Screenshot from 2021-07-16 14-42-33](https://user-images.githubusercontent.com/40197742/125923994-b318461b-3368-4238-ae73-f7c742293c88.png)

if i cd into `~/.config/nvm` this does not happen.

**Comment by l-kershaw** [comment]
I'm not sure how telescope could have caused this problem.
If disabling telescope fixes this problem, then we will need more information on your setup to figure out what is causing it.
If so, could you provide the details requested in the [bug report template](https://github.com/nvim-telescope/telescope.nvim/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by Abh15h3k** [comment]
ok. so i actually figured it out a few hours ago.

turns out the git repository was "checked-out" to a branch. (showed `Not currently on any branch` with `git status`).
after doing `git checkout master` the issue went away.

but normally errors should show in the command section ( bottom of the window ). why did this "hijack" my buffer?

**Comment by l-kershaw** [comment]
I can't find a way to reproduce this error, so it is difficult to diagnose why it happened.
Could you share some reproduction steps?

**Comment by Abh15h3k** [comment]
### for exact reproduction steps:

1. install nvm using curl one liner.
`curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | sh`
2. open any file in the installed nvm directory while not sitting in that directory (i.e pwd != <nvm_directory>)
```
cd ~
nvim ~/.config/nvm/nvm.sh
```
for me nvm installed in ~/.config/nvm.

### closest reproduction without nvm:
1. create empty git
  ```
  mkdir dummygit
  cd dummygit
  git init
  ```
2. open `.git/HEAD` and delete its content.
3. on saving that message ("fatal: not a git repositroy (or any of the parent directories): .git") should start flooding the buffer should start coming.

**Comment by Abh15h3k** [comment]
Here's a gif show the exact issue i face start to finish.

![buffer-error](https://user-images.githubusercontent.com/40197742/125987207-99a7aec2-36ba-4f11-90fd-bbbb5a5dcc67.gif)

**Comment by l-kershaw** [comment]
That's really weird.

I'm on Windows so I can't install nvm to follow your first set of reproduction steps.
Your second set of reproduction steps don't produce any unusual behavior for me.

**Comment by Abh15h3k** [comment]
ok. so i opened a issue on the nvm repo. someone replied that the install script checks out to a release tag. which is why the local repo is not actually on a valid branch.
so i took a deep dive into the install script and manually ran all git commands. so maybe you could try this.

obviously change `abhishek` to your username.
```
command git clone "https://github.com/nvm-sh/nvm.git" --depth=1 "/home/abhishek/Downloads/nvm"
command git --git-dir="/home/abhishek/Downloads/nvm"/.git --work-tree="/home/abhishek/Downloads/nvm" fetch origin tag "v0.38.0" --depth=1
command git --git-dir="/home/abhishek/Downloads/nvm"/.git --work-tree="/home/abhishek/Downloads/nvm" fetch origin "v0.38.0" --depth=1
command git -c advice.detachedHead=false --git-dir="/home/abhishek/Downloads/nvm"/.git --work-tree="/home/abhishek/Downloads/nvm" checkout -f --quiet FETCH_HEAD
command git --git-dir="$INSTALL_DIR"/.git --work-tree="$INSTALL_DIR" branch --quiet -D master >/dev/null 2>&1
command git --git-dir="/home/abhishek/Downloads/nvm"/.git --work-tree="/home/abhishek/Downloads/nvm" branch --quiet 2>/dev/null
command git --git-dir="/home/abhishek/Downloads/nvm"/.git --work-tree="/home/abhishek/Downloads/nvm" reflog expire --expire=now --all
command git --git-dir="/home/abhishek/Downloads/nvm"/.git --work-tree="/home/abhishek/Downloads/nvm" gc --auto --aggressive --prune=now
```

after all that.

```
cd
nvim Downloads/nvm/nvm.sh
```

and "hopefully" you should get the issue.

**Comment by Abh15h3k** [comment]
OK.
I owe you a HUGE apology. this is not telescopes issue.
its a statusline i use (galaxyline) thats producing those errrors.

I am truly sorry for wasting your time.
Really SORRY!!!

**Comment by l-kershaw** [comment]
No worries, glad you figured it out 🙂
