### ISSUE TITLE
Prefer filename matches when doing search

### ISSUE THREAD

**Issue by non25** [nvim-telescope/telescope.nvim#1015]
Hi! Telescope is amazing. Thanks a lot. Now I'm just going to fill the form. :grin: 

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I type exact name of a file, like SomeInterestingName, and it will print paths containing parts of this filename first:

```
DifferentPath/WhichContains/WhatImLookingFor/SomeInterestingName.tsx
SomeInteresting/Name/SomethingCompletelyUnrelatedAgain.tsx
SomeInterestingName/SomethingCompletelyUnrelated.tsx
SomeInterestingName/SomethingCompletelyUnrelatedAgain.tsx
```

**Describe the solution you'd like**
I would like it to give filename matches more priority.

```
SomeInteresting/Name/SomethingCompletelyUnrelatedAgain.tsx
SomeInterestingName/SomethingCompletelyUnrelated.tsx
SomeInterestingName/SomethingCompletelyUnrelatedAgain.tsx
DifferentPath/WhichContains/WhatImLookingFor/SomeInterestingName.tsx
```

**Describe alternatives you've considered**
Not doing anything, replacing fuzzy finding engine in Telescope somehow?

**Additional context**
If that is not enough to get point accross I'll add more.

**Comment by fdschmidt93** [comment]
I think this is something for a potential `break_ties` option to our pickers.

I'm happy to guide if you are willing to contribute on this comparably straightforward project. Please see #1190 and "custom tiebreak".

**Comment by fdschmidt93** [comment]
This should now be achievable via `tiebreak`, see `:h telescope.defaults.tiebreak` or probably better with an optimized sorter https://github.com/natecraddock/telescope-zf-native.nvim .

In any case, closing as `wontfix` from `telescope.nvim` side.
