### ISSUE TITLE
using initial_mode = "normal" search results are not displaying property (small bug)

### ISSUE THREAD

**Issue by Adomas-beep-boop-maggots** [nvim-telescope/telescope.nvim#1018]
### Description

Using "initial_mode" option with builtin.buffers function causes telescope to
not refresh and therefore leaving empty "results" display

**Expected Behavior**

Expected "results" display when using "initial_mode" option in builtin.buffers
function exactly when new telescope search buffer lists window spawns, my
reason is because my buffer list is usually rather short, so id rather use hjkl
keys to navigate without pressing escape

**Actual Behavior**

*you're lol.
When telescope search buffer list spawns the results are empty, but when i go
to insert mode (press i) results of buffer list appear

### Details

<details><summary>Reproduce</summary>
i use "<leader>fb" keybind to call ":Telescope buffers" 
and have a initial_mode = "normal", option in buffers section 
(I'm not sure how to describe it programmatically sorry)
(don't worry I'll link my short telescope.rc.vim below)

</details>

<details><summary>Environment</summary>
I'm note sure what to write there...

- nvim --version output: 
- NVIM v0.5.0

- Operating system: 
- Arch linux
no. Arch GNU/linux lol

- Telescope commit: 
1. https://pastebin.com/eUrDF6GR ~/.config/nvim/after/plugin/telescope.rc.vim
2. :Telescope live_grep
3. https://i.imgur.com/tcaKrQD.png 
(it just hangs like that, but refreshes when in insert mode)
4.  https://i.imgur.com/lQbfgot.png

</details>

<details><summary>https://pastebin.com/eUrDF6GR</summary>
<p>

```viml
https://pastebin.com/eUrDF6GR
```

**Comment by Adomas-beep-boop-maggots** [comment]
really sorry for formatting here this my first issue post.
placing things in brackets is hard

**Comment by Adomas-beep-boop-maggots** [comment]
updated the imigur picture links. i copied the wrong ones at first...

**Comment by JoseConseco** [comment]
I can confirm. Using  config option   :  initial_mode='normal'  -  wont initialize results list.   Only going into insert mode will populate the result list.   This issue is visible in eg: grep_string

**Comment by Conni2461** [comment]
This bug will be fixed in #987 You can try if that works for you
