### ISSUE TITLE
Add 'follow' opt to builtin.live_grep

### ISSUE THREAD

**Issue by vicecaycedo** [nvim-telescope/telescope.nvim#1020]
To mirror `builtin.find_files`, `builtin.live_grep` should have a `follow` opt. 

Similar to #530.

**Comment by Conni2461** [comment]
Not sure about that you can just edit your `vimgrep_arguments` and append `-L`

**Comment by vicecaycedo** [comment]
Yes, I can edit the command arguments, but the same could be said for find_files.

In my opinion, the interfaces should be kept as similar as possible. As a user, if find_files has a follow opt, I would expect live_grep to have one as well.

**Comment by clason** [comment]
But `live_grep` is quite different, because it sends the text to an external command for filtering rather than filtering a full list returned from an external command. (In this sense, `grep_string` is the natural companion to `find_files`, not `live_grep`.)

**Comment by vicecaycedo** [comment]
I see. I wasn't aware of the implementation details. 

Since this feature is possible by modifying the command, I'm fine with closing this FR then.

Thanks for the help, everyone!
