### ISSUE TITLE
Error when using help-tags

### ISSUE THREAD

**Issue by macthecadillac** [nvim-telescope/telescope.nvim#1030]
### Description

`:Telescope help-tags` gives an error message `Error executing vim.schedule lua callback: .../opt/plenary/filetype.lua:114: attempt to index local 'filepath' (a nil value)`. This only happens when the window size is large enough that telescope is showing the preview.

**Expected Behavior**

Invoking telescope help-tags should not give an error.

**Actual Behavior**

`:Telescope help-tags` gives an error message `Error executing vim.schedule lua callback: .../opt/plenary/filetype.lua:114: attempt to index local 'filepath' (a nil value)`. This only happens when the window size is large enough that telescope is showing the preview.

### Details

<details><summary>Reproduction</summary>

1. Open a terminal with the window size big enough to trigger the previewer (120 columns?)

2. `nvim -nu test.vim`

3. `:Telescope help_tags`

4. `Error executing vim.schedule lua callback: /tmp/plugged/plenary.nvim/lua/plenary/filetype.lua:114: attempt to index local 'filepath' (a nil value)`

</details>

<details><summary>Environment</summary>

- `nvim --version` output:
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/mac/build-src/neovim/build/config -I/home/mac/build-src/neovim/src -I/home/mac/build-src/neovim/.deps/usr/include -I/usr/include -I/home/mac/build-src/neovim/build/src/nvim/auto -I/home/mac/build-src/neovim/build/include
Compiled by mac@debian-desktop

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/mac/.local/share/nvim"

Run :checkhealth for more info
```
- Operating system:
```
$ uname -a
Linux debian-desktop 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux
```
- Telescope commit: `8c3f2b630be0241fe10709e61ee9dab473518f32`

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua require('telescope').setup()
```

**Comment by Conni2461** [comment]
Cant reproduce. So on what help tag (selected value) does this happen.

**Comment by macthecadillac** [comment]
It spits out an error on invocation, so as soon as I call `: Telescope
help_tags` it shows an error message. The window has to be large enough for
the previewer to be triggered for it to error out though and it doesn't
show an error if the previewer is disabled.

**Comment by Conni2461** [comment]
Is this issue still happening? I still can't reproduce

**Comment by macthecadillac** [comment]
I fixed it. Turns out it was an old help tag file that was causing the problem. The problem went away once I removed the tag file.
