### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by jalberto** [nvim-telescope/telescope.nvim#1031]
### Description

When I run any `Telescope` command I get this error:

```
Error executing vim.schedule lua callback: .../start/telescope.nvim/lua/telescope/previewers/utils.lua:67: Vim(syntax):E484: Can't open file syntax/shell.vim
```

I discard it (using esc) and telescope works as expected, but getting this every time is annoying.

**Expected Behavior**

Do not get any error msg

**Actual Behavior**

I get an error msg

### Details
<details><summary>Environment</summary>

1. nvim -nu test.vim
2. :Telescope find_files
3. error shows up

</details>

<details><summary>Environment</summary>

- nvim --version output: 

```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.5.0/x86_64-redhat-linux-gnu/config -I/builddir/build/BUILD/neovim-0.5.0/src -I/usr/include -I/usr/include/lua-5.1 -I/builddir/build/BUILD/neovim-0.5.0/x86_64-redhat-linux-gnu/src/nvim/auto -I/builddir/build/BUILD/neovim-0.5.0/x86_64-redhat-linux-gnu/include
Compiled by mockbuild@koj
```

- Operating system:  Fedora 34
- Telescope commit:  46e03a9

</details>

**Comment by fdschmidt93** [comment]
Not a telescope issue as clearly stated by the error: `Can't open file syntax/shell.vim` Please recompile neovim fully such that runtime files are accessible (and check file access rights, maybe).

**Comment by jalberto** [comment]
that's the interesting part, is neovim installed via package manager, and every file is accessible, and this error only happens in telescope

**Comment by Conni2461** [comment]
the question is why does ft detect return `shell` as filetype, because it should return `sh`.

What file is selected when this error appears. Does this happen with the minimal rc from the current issue template?

**Comment by fdschmidt93** [comment]
Apologies, I closed this a bit too preemptively and should have added to reopen the issue if it still persisted (as we now essentially require repro with `minimal_init.lua`.

**Comment by Conni2461** [comment]
Missing information and stale for quite some time. Closing
