### ISSUE TITLE
Exclude flag for fd makes find_command displays nothing

### ISSUE THREAD

**Issue by ybbond** [nvim-telescope/telescope.nvim#1032]
### Description
Using [`fd`](https://github.com/sharkdp/fd) with flag `--exclude` for `:Telescope find_files` makes empty result even without search query.

For example, I use `Telescope find_files find_command=fd,-E=.git,--hidden,--no-ignore`, which `fd` command will work in terminal.

With Telescope, that configuration will not work. Removing the `-E=.git` part makes Telescope works.

**Expected Behavior**
Telescope will still show result when the `--exclude -E` flag is used with `fd`.

**Actual Behavior**
Telescope will not show any result when the `--exclude -E` flag is used with `fd`.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :Telescope find_files find_command=fd,-E=.git,--hidden,--no-ignore
3. no result
4. try input some search query
5. still no result
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-97973-1wtbty6/neovim-0.5.0/build/config -I/tmp/neovim-20210702-97973-1wtbty6/neovim-0.5.0/src -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210702-97973-1wtbty6/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-97973-1wtbty6/neovim-0.5.0/build/include
Compiled by brew@HMBRW-A-001-M1-005.local
```
- Operating system: macOS 11.4
- Telescope commit: https://github.com/nvim-telescope/telescope.nvim/commit/46e03a935f1d080a9bd856d5a8acfcc093cd1461

</details>

**Comment by Conni2461** [comment]
Please use the lua interface for that. We are dynamically dispatching vim commands to lua commands and `-E=` is confusing the dispatcher.

```
lua require("telescope.builtin").find_files{ find_command= { "fd", "-E=.git", "--hidden", "--no-ignore" }}
```

**Comment by ybbond** [comment]
Actually, that works perfectly. Thanks @Conni2461 !

I just need to get used to the lua alternative to calling a command, and try that before consider any plugin's feature buggy.
