### ISSUE TITLE
Prompt on top on horizontal

### ISSUE THREAD

**Issue by ChrisTsou** [nvim-telescope/telescope.nvim#1036]
add option in the horizontal view for the positions of prompt and results to be exchanged, something like:
```
horizontal = {
    mirror_horizontal = true/false,  -- change Preview position left/right
    mirror_vertical = true/false        -- change prompt/Results top/down
}
```

**Comment by l-kershaw** [comment]
If I understand what you are asking for correctly, this is already possible!
You can use the `prompt_position` key of `layout_config` and set it to "top" (see `:help layout_strategies.horizontal()` for more info).

Depending on your personal preferences, you may also want to change the `sorting_strategy` to "ascending" (note that this is not a part of `layout_config`).

Changing both of these settings will move the prompt to the top of the layout, and have the "best" results nearest the top.

**Comment by philip1987** [comment]
I used to be able to change the prompt position through an ex command such as :Telescope find_files prompt_position=top.
Is there a new way to invoke the same behaviour with an ex command? This would be helpful when creating and testing custom Telescope pickers.

**Comment by l-kershaw** [comment]
Unfortunately, it is not currently possible to configure layouts using the vimscript commands, as our command parser is not set up to handle vimscript dictionaries (although this is something I'm planning on looking at).

If you want to configure layouts for one call of a picker, then you need to use the lua api, for example:
```
:lua require('telescope.builtin').find_files({layout_config={prompt_position='top'}})
```

**Comment by ChrisTsou** [comment]
That is exactly what i wanted! Sorry missed the option. Maybe added to the readme?
