### ISSUE TITLE
Previous location is not appended to the jump list when using lsp_references.

### ISSUE THREAD

**Issue by kcivkulis** [nvim-telescope/telescope.nvim#1038]
### Description

When jumping to a reference in the same file using `:Telescope lsp_references` the previous location is not appended to jump list, therefore ctrl-o doesn't work as expected.

**Expected Behavior**

Previous location is appended to jump list.

**Actual Behavior**

Jump list is not changed.

### Details

<details><summary>Reproduce</summary>

1. Move to some symbol
2. :clearjumps
3. :Telescope lsp_references
4. Select any reference in the same file
5. Observe that jump list is still empty
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.6.0-dev+48-g5377b2b00
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto
-DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/kristaps/neovim/build/config -I/home/kristaps/neovim/src -I/home/kristaps/neovim/.deps/usr/include -I/usr/include -I/home/kristaps/neovim/build/src/nvim/auto -I/home/kristaps/neovim/build/include
Compiled by kristaps

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- Operating system: 
Arch linux
- Telescope commit: 
6646900

</details>

**Comment by kcivkulis** [comment]
This _could_ be fixed by adding `vim.cmd "normal! m'"` to `action_set.edit` function, although this is definitely a hack.

Also (this is only slightly related), there is no issue when using `:Telescope live_grep` and jumping to the same file because in that case `filename` contains a redundant `/./` and doesn't exactly match the return value of [`vim.api.nvim_buf_get_name(0)`](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/actions/set.lua#L132) , therefore the if condition is true.

**Comment by fdschmidt93** [comment]
I'm happy to help guide you towards a PR to fix the issue. Otherwise, an issue at this is quite niche and difficult to fix for just _anyone_.

cc @caojoshua as the original creator of the jumplist picker (maybe you are willing to help)

**Comment by caojoshua** [comment]
The change is simple enough so I just went ahead and created a PR. Please review if you have the time.

> This could be fixed by adding vim.cmd "normal! m'" to action_set.edit function, although this is definitely a hack.

I don't consider this a hack. Builtin LSP does this. See the PR description for more details.

**Comment by Massolari** [comment]
This is also needed for document_symbols()
