### ISSUE TITLE
Is it possible to show the branch graph when viewing git_commits?

### ISSUE THREAD

**Issue by lynndylanhurley** [nvim-telescope/telescope.nvim#1041]
I'm coming from fzf where the commit list shows the branch graph (see attached). Is it possible to configure telescope to show this?

<img width="1406" alt="Screen Shot 2021-07-23 at 1 40 17 PM" src="https://user-images.githubusercontent.com/468037/126827337-6e2a4d0a-eedb-4737-8a6c-5cf6be51c4c0.png">

**Comment by l-kershaw** [comment]
This is not something that is currently possible within telescope.
I'm also not really sure how to implement such a thing in the current framework, but if you are interested in writing a PR, I'd be happy to give pointers 🙂

**Comment by lynndylanhurley** [comment]
Ok thanks @l-kershaw. Closing this out then
