### ISSUE TITLE
Search for file then method/line

### ISSUE THREAD

**Issue by johans** [nvim-telescope/telescope.nvim#1042]
First, thanks for this awsome project! I only miss this one feature described below.

Sublime Text and recently also VS Code has this really nice feature which lets you go directly to a function/method or line number via the quick open meny using the search patterns:
- "partOfFileName@function" and 
- "partOfFileName:linenumber"

What's also nice is that it supports previewing as you type which is really useful if you just want to look something up really quick. 

Is something like this possible to implement in Telescope?  Currently I first search and open the file then use `lsp_document_symbols({prompt_prefix=' ', default_text=' :method: '})` to filter on methods. This works but would be so cool if it could be improved into one action.

Attached a small video showing the feature:

![sublime](https://user-images.githubusercontent.com/1887/74606417-83084b80-50d0-11ea-9bf1-f02bc442f66d.gif)

**Comment by fdschmidt93** [comment]
I'll admit its buried deep in `telescope/pickers.lua` but something like this is possible with a few workarounds.

```lua
local actions = require "telescope.actions"

file_and_symbol = function()
  require("telescope.builtin").find_files {
    attach_mappings = function(prompt_bufnr, _)
      actions.select_default:enhance {
        post = function()
          require("telescope.builtin").lsp_document_symbols()
          -- not sure why this is needed,
          -- but lsp_document_symbols otherwise doesn't properly start in insert mode ;)
          vim.cmd [[normal! A]]
        end,
      }
      return true
    end,
    -- on_input_filter_cb is ran before finding/sorting, so any char "should" be safe
    on_input_filter_cb = function(prompt)
      -- this hack is required since actions cannot be run from within here
      if prompt:sub(#prompt) == "@" then
        local key = vim.api.nvim_replace_termcodes("<CR>", true, false, true)
        vim.api.nvim_feedkeys(key, "i", false)
      end
    end,
  }
end
```

You can play around with it and see if you get a nicer solution with `on_input_filter_cb`, but the coroutine always complained when I wanted to call `actions` within `on_input_filter_cb`

**Comment by johans** [comment]
@fdschmidt93 Amazing, it works really well! Thank you so much for this!

**Comment by fdschmidt93** [comment]
@johans 

This came up again in gitter.

You can amend the above solution with something like this in your telescope- find_files picker setup to preview and goto line

```lua
local actions = require "telescope.actions"
local action_state = require "telescope.action.state"

require"telescope".setup{
  pickers =
    find_files = {
      on_input_filter_cb = function(prompt)
        local find_colon = string.find(prompt, ":")
        if find_colon then
          local ret = string.sub(prompt, 1, find_colon - 1)
          vim.schedule(function()
            local prompt_bufnr = vim.api.nvim_get_current_buf()
            local picker = action_state.get_current_picker(prompt_bufnr)
            local lnum = tonumber(prompt:sub(find_colon + 1))
            if type(lnum) == "number" then
              local win = picker.previewer.state.winid
              local bufnr = picker.previewer.state.bufnr
              local line_count = vim.api.nvim_buf_line_count(bufnr)
              vim.api.nvim_win_set_cursor(win, { math.max(1, math.min(lnum, line_count)), 0 })
            end
          end)
          return { prompt = ret }
        end
      end,
      attach_mappings = function()
        actions.select_default:enhance {
          post = function()
            -- if we found something, go to line
            local prompt = action_state.get_current_line()
            local find_colon = string.find(prompt, ":")
            if find_colon then
              local lnum = tonumber(prompt:sub(find_colon + 1))
              vim.api.nvim_win_set_cursor(0, { lnum, 0 })
            end
          end,
        }
        return true
      end,
    },
  }
}
```

Further, you could use extmarks/highlighting to show line numbers and / or highlight the respective line.. I'd leave that to you though :)
