### ISSUE TITLE
Add option to show hidden files for the file browser

### ISSUE THREAD

**Issue by maxheyer** [nvim-telescope/telescope.nvim#1050]
**Is your feature request related to a problem? Please describe.**
I want to move to telescope for browsing files, but I can not find a solution to show hidden files or set custom search commands for the file_browser.

**Describe the solution you'd like**
I would like to whether set a custom search command or to set no-hidden parameters to show hidden files.

**Additional context**
For my search I use the rg command to find all Files: 

`      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--hidden',
      '--no-ignore',
      '--smart-case'`

**Comment by l-kershaw** [comment]
I think that this has already been implemented (although it isn't in the docs). 
You should be able to use the `hidden` flag, e.g.:
```
:Telescope file_browser hidden=true
```
or
```
:lua require('telescope.builtin').file_browser({hidden=true})
```

**Comment by elianiva** [comment]
If you don't mind, you could also help me testing https://github.com/nvim-telescope/telescope.nvim/pull/613 which can toggle hidden files on or off.

**Comment by Conni2461** [comment]
We have a option, its documented now and i'll review #613 but thats another issue point. I think this question was answered.

> Additional context
For my search I use the rg command to find all Files:
>
> 'rg', '--color=never', '--no-heading', '--with-filename', '--line-number', '--column', '--hidden', '--no-ignore', '--smart-case'

We dont use any extenal process for `file_browser` we use libuv. So no ripgrep, fd or any other program

**Comment by molleweide** [comment]
I am also trying to achieve displaying hidden files but i don't quite understand how to set this option. 
I provide my config below and if I understand correctly the hidden flag should be set in the topmost find_command table:

<details>
```lua
-- https://github.com/nvim-telescope/telescope.nvim#telescope-defaults
return function()
  local telescope = require("telescope")
  -- Required to close with ESC in insert mode
  local actions = require("telescope.actions")

  telescope.setup({
    defaults = {
      find_command = {
        "rg",
        "--no-heading",
        "--with-filename",
        "--line-number",
        "--column",
        "--smart-case",
        "--hidden",
      },
      initial_mode = "insert",
      selection_strategy = "reset",
      sorting_strategy = "descending",
      layout_strategy = "horizontal",
      prompt_prefix = "   ",
      selection_caret = " ",
      layout_config = {
        width = 0.75,
        preview_cutoff = 120,
        prompt_position = "bottom",
        vertical = { mirror = false },
        horizontal = {
          mirror = false,
          preview_width = 0.6,
        },
      },
      file_sorter = require("telescope.sorters").get_fuzzy_file,
      file_ignore_patterns = { ".git", "node_modules", "__pycache__" },
      generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter,
      winblend = 0,
      scroll_strategy = "cycle",
      border = {},
      borderchars = {
        "─",
        "│",
        "─",
        "│",
        "╭",
        "╮",
        "╯",
        "╰",
      },
      color_devicons = true,
      use_less = true,
      set_env = { ["COLORTERM"] = "truecolor" }, -- default = nil,
      file_previewer = require("telescope.previewers").vim_buffer_cat.new,
      grep_previewer = require("telescope.previewers").vim_buffer_vimgrep.new,
      qflist_previewer = require("telescope.previewers").vim_buffer_qflist.new,

      -- Developer configurations: Not meant for general override
      buffer_previewer_maker = require("telescope.previewers").buffer_previewer_maker,
      mappings = {
        i = {
          ["<C-j>"] = actions.move_selection_next,
          ["<C-k>"] = actions.move_selection_previous,
          ["<C-q>"] = actions.smart_send_to_qflist + actions.open_qflist,
          ["<Leader>f"] = actions.close, -- works like a toggle, sometimes can be buggy
          ["<CR>"] = actions.select_default + actions.center,
        },
        n = {
          ["<C-j>"] = actions.move_selection_next,
          ["<C-k>"] = actions.move_selection_previous,
          ["<C-q>"] = actions.smart_send_to_qflist + actions.open_qflist,
        },
      },
    },
  })

  -- Load mapper extension
  telescope.load_extension("mapper")
end
```
</details>

**Comment by Conni2461** [comment]
Sorry but please read the thread before you ask the same question.

> We dont use any extenal process for file_browser we use libuv. So no ripgrep, fd or any other program

```
:Telescope file_browser hidden=true
```

or

```
:lua require('telescope.builtin').file_browser({hidden=true})
```

or permanent with configuration as described here https://github.com/nvim-telescope/telescope.nvim#customize-default-builtin-behavior

```lua
require("telescope").setup {
  defaults = {
    -- Your defaults config goes in here
  },
  pickers = {
    -- Your special builtin config goes in here
    file_browser = {
      hidden = true
    }
  },
  extensions = {
    -- Your extension config goes in here
  }
}
```

**Comment by ThSGM** [comment]
@Conni2461 and @l-kershaw 

Is there a reason why the following command issues an error on "der": 

`nnoremap <leader>fn <cmd>lua require('telescope.builtin').file_browser({hidden = true})<cr>
`

Return "Not an editor command: dde"
