### ISSUE TITLE
How to make  files ignored by live_grep only and still searchable in normal find_files command

### ISSUE THREAD

**Issue by fans3210** [nvim-telescope/telescope.nvim#1052]
### Description

I have a react project. When search a string using live_grep, it would give me results of strings inside image binary files, especially the svg files. I tried to ignore them in "file_ignore_patterns", but it not only ignore those svg files from live_grep, but also from normal search.
**Expected Behavior**

I would like to only ignore those svg files when doing live_grep search
**Actual Behavior**

### Details

<details><summary>Reproduce</summary>

</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- Telescope commit: 

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua require('telescope').setup()
```

**Comment by fdschmidt93** [comment]
`file_ignore_patterns` should then be rather passed individually to your picker in question as opposed to defined at telescope setup, e.g.

`:lua require"telescope.builtin".find_files{file_ignore_patterns={"%.lua"}}`

**Comment by fans3210** [comment]
Noted with thanks @fdschmidt93
