### ISSUE TITLE
`git_bcommits()` erroneously displays an empty list

### ISSUE THREAD

**Issue by mroavi** [nvim-telescope/telescope.nvim#1055]
### Description

I configured `git_bcommits()` such that the command affects the repo containing the currently displayed buffer. I do so using the `cwd` option:

```lua
function M.git_bcommits()
	require("telescope.builtin").git_bcommits{
		cwd = vim.fn.expand("%:p:h"),
		layout_config = {
			prompt_position = "top",
		},
		sorting_strategy = "ascending",
	}
end
```

The problem is that if nvim's current working directory is not in the repo containing the current buffer, then this command displays an empty list of commits. If, however, the nvim's current working directory is inside the repo contain the current buffer, then the commits are displayed properly. This gif illustrates this:

![Peek 2021-07-28 12-59_bcommits_empty_list](https://user-images.githubusercontent.com/19517248/127311658-30824c5e-6e5d-4b84-be99-2d6b87b054b1.gif)

**Expected Behavior**

`git_bcommits()` should display the list of commits for the current buffer regardless of neovim's current working directory.

**Actual Behavior**

`git_bcommits()` displays an empty list when invoked outside of the repo containing the currently displayed buffer.

### Details

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az242-526
```

- Operating system:
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

- Telescope commit: 69adcbc

</details>

**Comment by caojoshua** [comment]
I was able to repro. Provided an explanation and fix in the linked PR.

**Comment by mroavi** [comment]
I tested your PR successfully: it solves the reported problem as far as I can tell.
