### ISSUE TITLE
undo file broken 

### ISSUE THREAD

**Issue by ayoubelmhamdi** [nvim-telescope/telescope.nvim#1056]
### my workflow is pushed to github.com/ayoubelmhamdi/nvim-lua : 
-    use 'nvim-telescope/telescope.nvim'
-    use 'akinsho/flutter-tools.nvim' ...

if i'm using telescop to find flutter file as `.dart` ,i got this error : 
```
E5108: Error executing lua ...acker/start/telescope.nvim/lua/telescope/actions/set.lua:134: Vim(e
dit):E823: Not an undo file: /root/.local/vim/undodir/%projects%flutter%app3%lib%quote.dart
```
- i have lot of plugin , perhapes this errore from another plugin but ,now i want to pushed this essue , than if this error not commun , i can't find solution with my self

**Comment by latesh** [comment]
It seems like you updated neovim and your old undo file is incompatible with the new version. Delete the file(s) from `/root/.local/vim/undodir/` and it should fix the issue.
