### ISSUE TITLE
Show keymaps for current picker

### ISSUE THREAD

**Issue by AllenDang** [nvim-telescope/telescope.nvim#1062]
**Is your feature request related to a problem? Please describe.**
I need to read manual or code directly to know the keymaps for a specify picker. It will be very helpful if there is a common way (like C-?) to show keymaps in the Previewer for current pick.

**Describe the solution you'd like**
After `Telescope find_files`, press `C-?` could display keymaps of builtin.find_files picker in Previewer.

**Comment by fdschmidt93** [comment]
If you anyone is happy to come up with a PR, here are a few pointers to get started on something like this at least for builtin-actions to display the action name:

The mappings are stored in `__TelescopeKeymapStore[prompt_bufnr]`, in which you'll find the `key_func` number that corresponds to a respective action.

Analogously, the `rhs` in `vim.api.nvim_buf_keymap(prompt_bufnr, "i")` gives you the mapped functions `require ("telescope.mappings").execute_keymap(`prompt_bufnr`, `key_func`)`.

Of course, maybe `telescope/mappings.lua` can be amended to more suitably  show `actions` and their keybind for the respective mode.
