### ISSUE TITLE
Actions.insert doesn't behave as expected

### ISSUE THREAD

**Issue by clason** [nvim-telescope/telescope.nvim#1072]
I am playing around with `Telescope symbols` and noticed the following unexpected behavior when using it in insert mode (which is the most common use, I'd say):

1. `:inoremap <c-s> <cmd>Telescope symbols<cr>`
2. type `foobar`
3. place the cursor between `foo` and `bar`
4. trigger `<c-s>` and insert any symbol, say, `X`

**Expected**: `fooX|bar` in insert mode

**Actual**: `foob[X]ar` in normal mode

(Also, wouldn't a better place for sources be in `.local/share/nvim/telescope/symbols` rather than under `.config`? I feel there could be a general "data cleanup" for `telescope_history` and `file_frecency.sqlite3` as well...)

**Comment by Conni2461** [comment]
1. We currently always leave insert mode when closing telescope. That actually is a issue with `inoremap`.
2. We insert with `nvim_put` and after is set to true, so `P` which is not optimal.
3. We agreed that files have to be placed at `vim.api.nvim_get_runtime_file("data/telescope-sources/*.json", true)` so we can distribute them easily with a extension, but we could also allow files at `.local/share/nvim/telescope/*.json` or make the path configurable. So you can curl the files from the repo and dont have to install it as extension.

**Comment by clason** [comment]
1. That is a major deal-breaker for this function, then ;)
2. That at least sounds fixable...
3. How about looking in both places? Then extensions can put it in runtime path, while users can use data path (which I'd propose to put in `nvim/telescope/symbols/*.json` -- there's a lot of telescope files, and more coming, so getting structure in early would pay off ;))

**Comment by Conni2461** [comment]
for 1 and 2
```diff
diff --git a/lua/telescope/actions/init.lua b/lua/telescope/actions/init.lua
index 4ee6134..9a7acd5 100644
--- a/lua/telescope/actions/init.lua
+++ b/lua/telescope/actions/init.lua
@@ -375,8 +375,8 @@ end
 
 actions.insert_symbol = function(prompt_bufnr)
   local selection = action_state.get_selected_entry()
-  actions.close(prompt_bufnr)
-  vim.api.nvim_put({ selection.value[1] }, "", true, true)
+  actions._close(prompt_bufnr, true)
+  vim.api.nvim_put({ selection.value[1] }, "", false, true)
 end
 
 -- TODO: Think about how to do this.
```

3. Yeah I meant that we could look in both places. We can say `.local/share/nvim/telescope/symbols/*.json` fixed and opts.symbol_path to override it

**Comment by clason** [comment]
That fixes 2 only -- I still end up in normal mode? 

3. sounds good!

**Comment by clason** [comment]
Hmm, no, that doesn't work consistently (for 2) -- sometimes it puts the cursor _before_ the inserted symbol. For example, if you are at the end of the line.

**Comment by clason** [comment]
Specifically, if at the end of a line you trigger `Telescope symbols` (using an `inoremap`), the symbol gets inserted after_ the cursor. This does not happen if I map `vim.api.nvim_put('X')` directly, so something with the prompt (or other) buffer(s) interferes with the `put`.

**Comment by Conni2461** [comment]
This feels super hacky
```diff
diff --git a/lua/telescope/actions/init.lua b/lua/telescope/actions/init.lua
index 4ee6134..3867fdf 100644
--- a/lua/telescope/actions/init.lua
+++ b/lua/telescope/actions/init.lua
@@ -375,8 +375,10 @@ end
 
 actions.insert_symbol = function(prompt_bufnr)
   local selection = action_state.get_selected_entry()
-  actions.close(prompt_bufnr)
-  vim.api.nvim_put({ selection.value[1] }, "", true, true)
+  actions._close(prompt_bufnr, true)
+  local cursor = vim.api.nvim_win_get_cursor(0)
+  vim.api.nvim_buf_set_text(0, cursor[1] - 1, cursor[2], cursor[1] - 1, cursor[2], { selection.value[1] })
+  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<esc>la", true, true, true), "n", true)
 end
 
 -- TODO: Think about how to do this.
```

**Comment by clason** [comment]
It does -- but it does work ;)

**Comment by clason** [comment]
And `insert_symbol` is probably niche enough not to worry too much about it, at least for now?

**Comment by Conni2461** [comment]
FYI I still have this on my todo list, i'll do it today or tomorrow :) will ping you on a PR
