### ISSUE TITLE
Allow splitting file from file browser and finder

### ISSUE THREAD

**Issue by eric-hansen** [nvim-telescope/telescope.nvim#1078]
**Is your feature request related to a problem? Please describe.**
It can be annoying to constantly have to choose a file, then create a split manually and then have to switch to another buffer in the split manually.  I.e.: from the file finder I choose a source file, then I have to split (i.e.: `:vs`) and then open the file finder browser in the new split to open up the associated test file.

**Describe the solution you'd like**
`<C-x>` already does a horizontal split from the file finder and browser, not sure how difficult it would be to support `<C-s>` or something mappable to do other splits.

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim#mappings

`<c-v>` to do vertical splits. Doesn't that work for you?

**Comment by eric-hansen** [comment]
> https://github.com/nvim-telescope/telescope.nvim#mappings
> 
> `<c-v>` to do vertical splits. Doesn't that work for you?

Yeah that works.  Windows Terminal has `<C-v>` mapped to paste which gave unexpected results so I had to unmap that.  Thanks!
