### ISSUE TITLE
Remap <CR> for builtin functions

### ISSUE THREAD

**Issue by philip1987** [nvim-telescope/telescope.nvim#1079]
I'd like to (re)map a few keybindings for some built-in functions. For example <CR> should open in a vertical split for help_tags, but still retain the default behaviour in other builtin functions (such as find_files). Is this possible?

I tried the following in my config which didn't work (it opens the help page in a horizontal split, which I think is vim's default way of opening help pages):

```
M.help = function()
    require("telescope.builtin").help_tags({
        mappings = {
            i = { ["<CR>"] = require("telescope.actions").select_vertical, },
        }
    })
end
```

Could some point me in the right direction?

**Comment by philip1987** [comment]
Beautiful, it worked as intended. Thank you for clarifying how to override mapped actions. I am still new to both nvim and programming and I am so grateful for the wonderful neovim community aka people like you. Dankeschön ;-)

**Comment by l-kershaw** [comment]
@philip1987 another option for this is to set the mapping directly in your config setup, e.g.:
```lua
require("telescope").setup({
  -- other config   
  pickers = {
    help_tags = {
      mappings = {
        i = {
          ["<CR>"] = "select_vertical",
        },
        n = {
          ["<CR>"] = "select_vertical",
        },
      },
    },
  },
  -- other config
})
```

This has the effect that whenever you call `help_tags` you will have these mappings, so you don't have to call a specific lua function to get your wanted configuration. For example, with this `:Telescope help_tags` will still have your mappings, as will opening `help_tags` from within the `:Telescope` builtin picker.

This may or may not be something you want, as it means you would have to override it back to get the original selection behaviour.

Up to you what you think best suits your workflow 🙂

**Comment by philip1987** [comment]
@l-kershaw Thank you Lukas for your suggestion! In my opinion your suggestion is a cleaner way  and as you mentioned does not mess with the behaviour of the built in function. Very useful for other pickers too!
