### ISSUE TITLE
current_buffer_fuzzy_find - options 

### ISSUE THREAD

**Issue by adrianstaniec** [nvim-telescope/telescope.nvim#1080]
I've switched to telescope, and I am liking the plugin,
but there is one behavior I am missing.

Can somebody help me configure `current_buffer_fuzzy_find` 
such that:
- it displays the results in order according to line number
- it only shows lines, where all chars typed are found in consecutive order

I have trying to figure it out, but no luck. TIA

**Comment by fdschmidt93** [comment]
> it only shows lines, where all chars typed are found in consecutive order

Are you referring to exact match? If so, please see my answer as per #1083

> it displays the results in order according to line number

Generally, results are displayed in order of their sorting score. AFAIK, without really deep changes, something akin to this could only be solved right now after finding & sorting have been completed.

If you'd like to take a crack at this yourself, I'd have a look at `telescope/pickers.lua` and more specifically `Picker:_on_complete` in which you'd essentially re-fill `results_bufnr` according to score for which now ties are broken by preference to lower line number (I might be wrong though :laughing:  ). I'm happy to have a look at what you are doing then :)

**Comment by TC72** [comment]
Came here from #1341 which is a dupe I opened. I'll definitely have a look at how this can be done.

**Comment by fdschmidt93** [comment]
Again, it's very cool that you did your research, but I'm a bit puzzled that you seem to be ignoring my comments :sweat_smile: 

Following the links from my original comment from #1340 would have led you [here](https://github.com/nvim-telescope/telescope.nvim/pull/987#discussion_r686623272) which is pretty much what you're proposing?

**Comment by TC72** [comment]
Honestly not ignoring your comments, I just got a bit lost and I'm happy doing this to have a better understanding of the code.
I'll jump over to #987, I think it was mainly the title of that one that put me off reading it as didn't see how it was connected.

**Comment by TC72** [comment]
I've just added a pr for this #1401

**Comment by Conni2461** [comment]
#1401 is merged. Is this resolved?

**Comment by TC72** [comment]
yes

**Comment by Sleepful** [comment]
@TC72 thank you so much, this makes the search so much better!

```lua
require("telescope.builtin").current_buffer_fuzzy_find({
        -- function from
        -- https://github.com/nvim-telescope/telescope.nvim/pull/1401#issuecomment-957234973
        tiebreak = function(entry1, entry2, prompt)
          local start_pos1, _ = entry1.ordinal:find(prompt)
          if start_pos1 then
            local start_pos2, _ = entry2.ordinal:find(prompt)
            if start_pos2 then
              return start_pos1 < start_pos2
            end
          end
          return false
        end,
        additional_args = { "--ignore-case", "--pcre2" },
      })
```
