### ISSUE TITLE
Ruby singleton methods are not shown when using the treesitter picker

### ISSUE THREAD

**Issue by YorickPeterse** [nvim-telescope/telescope.nvim#1085]
### Description

When using `Telescope treesitter`, singleton methods in Ruby aren't displayed. This in spite of tree-sitter-ruby parsing them just fine.

![Screenshot from 2021-08-05 15-59-54](https://user-images.githubusercontent.com/86065/128362884-a0cba255-d5fd-44c4-bfcf-41843e29b2e3.png)

**Expected Behavior**

Class/singleton methods are displayed in the output of the `treesitter` picker.

**Actual Behavior**

They are not included.

### Details

<details><summary>Reproduce</summary>

Create the following Ruby script:

```ruby
module Foo
  def self.bar
    10
  end
end
```

Then run `Telescope treesitter`, and observe the lack of the `bar` method in the list. The Treesitter parse tree is as follows:

```
module [0, 0] - [4, 3]
  name: constant [0, 7] - [0, 10]
  singleton_method [1, 2] - [3, 5]
    object: self [1, 6] - [1, 10]
    name: identifier [1, 11] - [1, 14]
    integer [2, 4] - [2, 6]
```

</details>

<details><summary>Environment</summary>

- nvim --version output: `NVIM v0.6.0-dev+106-g545e05d2f`
- Operating system: Arch Linux
- Telescope commit: `b742c50`

</details>

**Comment by Conni2461** [comment]
This is most likely not a telescope bug. We are asking nvim-treesitter for all definitions https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/locals.lua#L36-L48 and it seems like that the `singleton_method` is missing in the locals https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/ruby/locals.scm#L39 file. Try to add it there and open a PR for nvim-treesitter if it works :)

**Comment by YorickPeterse** [comment]
It looks like this may be an issue with nvim-treesitter. Say I simplify the file to this:

```ruby
def self.foo
  10
end
```

Then run this:

```lua
lua print(vim.inspect(require('nvim-treesitter.locals').get_definitions(vim.api.nvim_get_current_buf())))
```

The output is an empty table.

**Comment by YorickPeterse** [comment]
@Conni2461 Seems you beat me to it. I'll submit a PR to nvim-treesitter. Thanks for the pointer!
