### ISSUE TITLE
Highlight files and directories on file_browser

### ISSUE THREAD

**Issue by henriquehbr** [nvim-telescope/telescope.nvim#1086]
I've read the documentation a couple of times, but still couldn't find a specific section taking about how to highlight files displayed by the `file_browser` builtin

Is there any option that allows to change the parameters of a command in order to manipulate how the entries are displayed (like a `ls` or a `find` command)?

In my case, i needed to highlight both files and directories (the first one based on it's extension) and display the latter (directories) at the top

**Comment by fdschmidt93** [comment]
This might be very interesting once #613 is merged. At the same time, this is a great issue for anyone who wants to start contributing to telescope. Happy to help guiding anyone who's trying to attempt this, contributor's welcome :)

As a pointer: I think one would have to start [here](https://github.com/nvim-telescope/telescope.nvim/blob/2c573b9d12f421cec74a215f79b25591fe083352/lua/telescope/builtin/files.lua#L314). You'd essentially have to amend `maker` to fill in entries to the results buffer adequately displayed and highlighted. 

As a reference, `lua/telescope/make_entry` has a lot of ideas you can borrow from to achieve this.

**Comment by henriquehbr** [comment]
I'm afraid i can't be of much help, mainly because i'm still learning lua, started studying it no more than a few weeks ago, and the codebase seems a bit too challenging for my current knowledge

I've been thinkering with telescope for quite some time, and it's by far one of the most amazing plugins i've used on neovim so faar, having this feature on it would easily allow me (and maybe others) to fully migrate from fzf

**Comment by TheLeoP** [comment]
I want to try to do this :3.

So, I have been reading the Telescope code for some hours (I had troubles understanding how the highlighting was being made but I think I understand it now) and now I'm thinking about how to expose the hightlight options to a normal user. I have this two ideas for now:
- Expose to the user two highlights groups: one for the directories and one for the files, but that wouldn't allow a different highlight for each filetype. 
- Add an option to extend the highlight of the icon of each filetype to the whole entry and tell users to change each color throught devicons.


About displaying, I haven't look up how the entries are ordered yet (I guess it isn't related with `maker`, or is it?). I would appreciate if someone could point me in the right direction (I guess I may have to do a new sorter (?)).

**Comment by fdschmidt93** [comment]
It's probably outside of the scope of that PR, but I've started revamping the file browser in #1257. So something on this here would preferably only be merged afterwards.

> Expose to the user two highlights groups: one for the directories and one for the files, but that wouldn't allow a different highlight for each filetype.
Add an option to extend the highlight of the icon of each filetype to the whole entry and tell users to change each color throught devicons.

Yeah, this really warrants more discussion; I'll have to think about this more, but yeah, opt-in FG highlighting of devicon sounds reasonable to me.
 
> About displaying, I haven't look up how the entries are ordered yet (I guess it isn't related with maker, or is it?). I would appreciate if someone could point me in the right direction (I guess I may have to do a new sorter (?)).

This would then happen somewhere here if/when the PR gets merged: https://github.com/nvim-telescope/telescope.nvim/blob/6d61afeed602edeb3dc0a943cd64aab8cf7296bf/lua/telescope/make_entry.lua#L237-L285

**Comment by Conni2461** [comment]
file_browser was moved out of telescope core. Closing

If you are still interested in this please open a issue here https://github.com/nvim-telescope/telescope-file-browser.nvim
