### ISSUE TITLE
ctrl-e not working in find_files

### ISSUE THREAD

**Issue by oliverdain** [nvim-telescope/telescope.nvim#1087]
### Description
If I try to use the `<c-e>` key binding in `find_files` to create a new file it doesn't work.

**Expected Behavior**
Hitting Ctrl-e after typing the name of a non-existent file should create that file and open it in a buffer.

**Actual Behavior**
Nothing happens at all. The keystroke is simply ignored.

### Details

`:Telescope find_files`
type the name of a non-existent file like `foo.txt` and hit Ctrl-e.

Nothing happens at all. The `find_files` picker is still opened and the keystroke is ignored.

```
$ nvim --version
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az242-526

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

OS is Debian Linux (11.0).

Telescope commit: b742c50bf119d7c442a553cc52e8afde0086ae02

**Comment by fdschmidt93** [comment]
This is only expected behavior in the `bultin.file_browser`. See `:h builtin.file_brower()` for more info.

**Comment by oliverdain** [comment]
Sorry! I was reading the help pages but, apparently, reading `file_browser` as `find_files`. My bad.
