### ISSUE TITLE
API improvement to `finders.new_table` to support passing a list of tables

### ISSUE THREAD

**Issue by smackesey** [nvim-telescope/telescope.nvim#1090]
Creating custom pickers using a "static" finder (i.e. from `finders.new_table`) requires unnecessary boilerplate and silently fails if it is not provided.

The issue is that for `finders.new_table`, if no `entry_maker` is provided, then it assumes you passed a list of strings and attempts to generate an entry using `make_entry.gen_from_string`. If you passed a list of tables, then this will cause a silent failure. You have to pass an identity function as `entry_maker` to get a list of tables to work.

Seems to me that `finders.new_table` should support simply passing a list of entries (i.e. tables) that don't need any additional massaging by an `entry_maker` function. The solution is to check the type of the first entry in the passed list. If it's a table, then ~~just skip using an `entry_maker` entirely if none was provided~~ use an identity function as the default `entry_maker`.

**Comment by fdschmidt93** [comment]
> `new_table` silently fails if it is not provided

I agree, we should include that after #987 .

Your proposed solution unfortunately is not universal. An `entry_maker` is required since the sorter scores on the `entry.ordinal` which is created automatically in the table of strings case. Otherwise, it's ambiguous from what to create the ordinal from, unless it's explicitly passed. In contrast, the current behavior is quite well defined (apart from silently failing ;).

Consequently, I rather think having a personal wrapper for your use cases, i.e. the particular entry maker for passing a list of tables is a more principled solution to define what should be displayed, what should be sorted on, where to jump on selection etc. (which still needs better documentation, contributors welcome ;). To get a a better idea, have a look at `lua/telescope/make_entry.lua`.

I hope that reasons well enough as to why we the default behaves as it does.

**Comment by smackesey** [comment]
Hmm not sure I see the problem. Why does the fact that the default entry maker function adds `ordinal` matter? You're implying that Telescope needs to add `ordinal`, but I don't see why that's the case. You can already pass an arbitrary entry maker function, and I don't think `ordinal` is automatically added to the result of that (user is expected to provide it). So it's not like `ordinal` is part of a private API-- users already need to know about it if they are passing a custom `entry_maker`.

All I'm suggesting is that, if a table of tables is passed, the step in which they are mapped by an `entry_maker` function is skipped. So they are treated just like the output of a custom `entry_maker`.

**Comment by fdschmidt93** [comment]
> You're implying that Telescope needs to add ordinal, but I don't see why that's the case.

See [here](https://github.com/nvim-telescope/telescope.nvim/blob/f67d3e883d7afafa93428a27cb1ba1c4144d9d4c/lua/telescope/sorters.lua#L117). Without an ordinal, you are effectively not

> You can already pass an arbitrary entry maker function, and I don't think ordinal is automatically added to the result of that (user is expected to provide it).

That's why we have the default to generate the entry from string, which also makes sure there is an ordinal, display, and value, for instance.

> All I'm suggesting is that, if a table of tables is passed, the step in which they are mapped by an entry_maker function is skipped. So they are treated just like the output of a custom entry_maker.

I hope it is more clear as to why there is ambiguity. Besides the ordinal you'll typically see `display`, `lnum`, etc.; again, please take a look at `lua/telescope/make_entry.lua` with what I've been referring to here in mind -- there information there passed is required for a lot of the downstream functionality. Without explicit information, not all too much happens. Exchange `a` and `b` as `entry_makers` in the below code too see what I'm referring to in action:

```lua
local finders = require "telescope.finders"
local pickers = require "telescope.pickers"
local conf = require("telescope.config").values
local data = {{'this'}, {'is'}, {'a'}, {'test'}}
local a = function(e) return {ordinal = e[1], display=e[1], value=e[1]} end
local b = function(e) return e end

pickers.new({}, {
  prompt_title = "Test",
  finder = finders.new_table {
    results = data,
    entry_maker = a,
  },
  sorter = conf.generic_sorter({}),
  previewer = false,
}):find()
```

**Comment by smackesey** [comment]
@fdschmidt93 Thanks for engaging on this.

I am already familiar with `lua/telescope/make_entry.lua`. I understand that entries need to express a particular interface (`ordinal`/`display`/`value`) to work correctly.

What I *don't* understand (or perhaps I'm missing something) is why there isn't a simple option to pass a list of table entries to a picker that *already* express this interface. Passing a list of strings is supported first-class, but not a list of entry tables. From your example above, it looks like you think I'm talking about passing a list of tables where the element tables contain strings. I'm not, I'm talking about this:

```lua
local data = {
  { ordinal = 'a', display = 'a', value = 'a' },
  { ordinal = 'b', display = 'b', value = 'b' },
}

-- fails but IMO should work
finders.new_table(data)

-- works via unnecessarily complex interface with silly identity function boilerplate
finders.new_table{
  results = data,
  entry_maker = function (x) return x end,
}
```

This is useful whenever you have a custom picker generating entries from some arbitrary lua code that is not an external program. That way you can construct your entries in one place. With the current interface, you have to either pass an identity function or split up the entry-generating logic (putting parts adding `telescope`-specific fields in an entry maker).

Am I missing something?

**Comment by Conni2461** [comment]
This is currently not possible and i think we should keep it that way. This splitting into `entry_maker` allows us to reuse these functions across `new_table` and `new_job` depending on the use case. And for example in the future we can replace the lsp stuff that we currently have, which uses `new_table` with a finder that lets us stream in new items using `vim.lsp.buf_request` over `vim.lsp.buf_request_sync`.

What makes a possible implementation for `new_table` hard is that we have some picker they pass in a table of tables which are not in the entry format yet. Like `builtin.buffers` which passes in a table `{ bufnr = bufnr, flag = flag, info = info }`. For a possible implementation we would need to figure out if we actually have now a table of already entry or if its just a table of tables. Doing this figuring out would just add bloat to it and potentially add bugs. For your idea might require a lot of changes for the builtin pickers and for a lot of extensions and is probably not worth it.

I think your best bet right now is `entry_maker = function (x) return x end` (which gets probably compiled away by luajit anyways) or writing your own finder for your extension. I think we do not need to have a interface in telescope core for every usecase. But thats just my opinion

**Comment by fdschmidt93** [comment]
Thanks for your examples @smackesey !

> From your example above, it looks like you think I'm talking about passing a list of tables where the element tables contain strings.

In fact, I was actually trying not making any assumptions (see `builtin.buffers` examples as referred to above). And, while you seem very knowledgeable , other users might not be and we have new problems on our hands.

> This is currently not possible and i think we should keep it that way. 

As argued, I agree. As the original problem is to straightforwardly solved almost no overhead (dedicated finder -- see `telescope/finders/async_static_finders.lua` or `entry_maker`), I'd shy away from trying to make this work from within telescope.

I'll leave it to you to close the issue if there's more you want to discuss here.

**Comment by smackesey** [comment]
Thanks and sorry to belabor the point, but the responses here suggest something is being lost in translation. Nothing about what I'm recommending requires changes to any existing functionality. All I am suggesting is that sensible defaults be implemented for inputs that currently cause Telescope to **silently fail**. As a user/writer of custom pickers, I found this silent failure quite frustrating, and reasonable defaults seem like a strict improvement.

@Conni2461:

>This splitting into entry_maker allows us to reuse these functions across new_table and new_job depending on the use case. 

I am not suggesting removing entry makers. I am suggesting implementing default behavior for when one is not provided.

>What makes a possible implementation for new_table hard is that we have some picker they pass in a table of tables which are not in the entry format yet.

Nothing about this needs to change. These pickers already pass an entry maker.

>For a possible implementation we would need to figure out if we actually have now a table of already entry or if its just a table of tables.

Not necessary, all you need to do is check if the first entry is a string or a table. Here is one way to implement the suggested change in three lines of code.

```lua
-- lua/telescope/finders/async_static_finder.lua

local default_entry_maker = type(input_results[1]) == 'table' and
  function (x) return x end or
  make_entry.gem_from_string()

entry_maker = opts.entry_maker or default_entry_maker
```

AFAICT, this changes no existing functionality at all. It replaces a bug/uncovered input case with a sensible default.
