### ISSUE TITLE
Add "space" in fuzzy finding queries to search multiple words

### ISSUE THREAD

**Issue by w-cantin** [nvim-telescope/telescope.nvim#1091]
**Is your feature request related to a problem? Please describe.**

Sorry if this feature already exists but I could not find it. One of the best features of FZF or VSCode's `Ctrl+P`  search in my opinion is that it is possible to search for multiple words using spaces to refine the search and jump quickly to the solution. Those words do not have to be in order for the search to work. Spaces kinda act like an `and` operator of sorts (search for something that matches this word `and` this word).

Here is an example. I know that I am looking for a .py file so I type "py" first. Then to refine my search I can add another word to my search to select what I want. 

![vscodeEx](https://user-images.githubusercontent.com/43618947/128553500-9b265db9-9f03-4e9b-bfc7-fc4ddf2d9f79.gif)

As far as I know I cannot do this type of search in telescope, every letter I type have to be in order. For example if I was searching between two files in Telescope "/test/textobject" and "/bob/textobject" and I started typing "textobject" I would be stuck there between the 2 files unable to refine my search further by searching "textobject bob". For 2 files this is not an issue because you can use the arrow keys and select it easily. But when you need to choose between dozens of them it can become a problem.

Using spaces to search multiple words would make this more intuitive.

Thank you by the way for this wonderful piece of software.

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope-fzf-native.nvim implements fzf sorting behavior with search syntax

**Comment by w-cantin** [comment]
Thank you @Conni2461 that works
