### ISSUE TITLE
Whether parameter query is supported ？

### ISSUE THREAD

**Issue by liuxian1990** [nvim-telescope/telescope.nvim#1095]
For example：

:Telescope find_files search_text='hello'

results：

![img](https://raw.githubusercontent.com/liuxian1990/webimages/2a36d7716169c7e71e9852cea8b93b9e60ee0d85/2021-08-09_20-04.png)

**Comment by fdschmidt93** [comment]
Does `:Telescope find_files default_text=hello` work as intended for you?

**Comment by liuxian1990** [comment]
> Does `:Telescope find_files default_text=hello` work as intended for you?
> 
> 如何: Telescope find _ files default _ text = hello work as intended for you？

Yes, thank you

**Comment by liuxian1990** [comment]
I implemented a simple function

![](https://raw.githubusercontent.com/liuxian1990/webimages/master/Peek%202021-08-10%2010-22.gif)
