### ISSUE TITLE
<cr> in insert mode doesn't select the item

### ISSUE THREAD

**Issue by mellery451** [nvim-telescope/telescope.nvim#1100]
**Is your feature request related to a problem? Please describe.**
Preface: This is very possibly pilot error.

 I'm using a mostly default configuration...which I'll include below. I'm in insert mode when I launch tele, start typing, fuzzy find starts working and when the highlighted item looks right to me, I'd like to just press <cr> and have it open. Instead I have to press <esc> and then <cr>. <cr> in insert mode seems to just clear the insert window..or maybe it's just inserting a newline character and causing my previous entry to scrolloff. In any event, I'm perplexed and sometimes annoyed by this behavior ;)

**Describe the solution you'd like**
I'd like to just press <cr> in insert mode to open the highlighted item

**Describe alternatives you've considered**
I've tried explicitly mapping <cr> for insert mode in the default mappings, but still no change.

**Additional context**
my config

```
    require('telescope').load_extension('fzy_native')
    if vim.g._try_lsp == 0 then
        require('telescope').load_extension('coc')
    end
    local actions = require('telescope.actions')
    require('telescope').setup{
        defaults = {
            file_ignore_patterns = {"bazel-*/*", "*.so", ".git/*"},
            vimgrep_arguments = {
                'rg',
                '--color=never',
                '--no-heading',
                '--with-filename',
                '--line-number',
                '--column',
                '--hidden',
                '--follow',
                '--smart-case',
            },
            -- mappings = {
            --     i = {
            --         ["<cr>"] = actions.select_default,
            --     },
            -- },
        },
        pickers = {
            buffers = {
                show_all_buffers = true,
                sort_lastused = true,
                -- theme = "dropdown",
                scroll_strategy = "cycle",
                previewer = false,
                mappings = {
                    i = {
                        ["<c-d>"] = require("telescope.actions").delete_buffer,
                    },
                    n = {
                        ["<c-d>"] = require("telescope.actions").delete_buffer,
                    }
                }
            }
        },
    }
```
I'm on neovim 0.5 release. I do have quite a few other plugins installed, so if you think there might be some sort of conflict, I'm happy to try to diagnose more, with advice about how to do that.

thanks for creating telescope!

**Comment by elianiva** [comment]
what's the output of `:verbose imap <CR>`?

**Comment by mellery451** [comment]
```
i  <CR>         @<Plug>(PearTreeExpand)
        Last set from ~/.config/nvim/bundle/pear-tree/plugin/pear-tree.vim line 179
```
(which seems to be https://github.com/tmsvg/pear-tree).

removing that plugin makes it work as expected. thanks @elianiva !
