### ISSUE TITLE
Telescope cannot display text properly

### ISSUE THREAD

**Issue by c4dr01d** [nvim-telescope/telescope.nvim#1107]
### Description

Details in https://github.com/navarasu/onedark.nvim/issues/13

**Expected Behavior**

Open telescope, show the text and icons

**Actual Behavior**

Just show icons, text disppear

### Details

<details><summary>Reproduce</summary>

1. nvim
2. `:Telescope find_files`
</details>

<details><summary>Environment</summary>

- nvim --version output: nvim v0.5.0
- Operating system: Arch Linux
- Telescope commit: d4a52de

</details>

<details><summary>Configuration</summary>
<p>

``` lua
require("telescope").setup {
    defaults = {
        vimgrep_arguments = {
            "rg",
            "--color=never",
            "--no-heading",
            "--with-filename",
            "--line-number",
            "--column",
            "--smart-case"
        },
        prompt_prefix = ">",
        initial_mode = "insert",
        selection_strategy = "reset",
        sorting_strategy = "descending",
        layout_strategy = "horizontal",
        layout_config = {
            width = 0.75,
            preview_cutoff = 120,
            prompt_position = "bottom"
        },
        file_sorter = require("telescope.sorters").get_fuzzy_file,
        file_ignore_patterns = {},
        generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter,
        path_display = true,
        winblend = 0,
        color_devicons = true,
        use_less = true,
        set_env = {
            ["COLORTERM"] = "truecolor"
        },
        file_previewer = require("telescope.previewers").cat.new,
        grep_previewer = require("telescope.previewers").vimgrep.new,
        qflist_previewer = require("telescope.previewers").qflist.new,
        buffer_previewer_maker = require("telescope.previewers").buffer_previewer_maker
    }
}
```

**Comment by l-kershaw** [comment]
I think this is caused by you setting `path_display=true`, which is not a valid setting.
This should be a (possibly empty) list of options, see `:help telescope.defaults.path_display` for more details.

**Comment by c4dr01d** [comment]
I modified to path_display to "shorten", nothing happen, still display icons only

**Comment by c4dr01d** [comment]
@l-kershaw I just find out why, I deleted path_display option, everything is back to the normal

**Comment by l-kershaw** [comment]
@c4dr01d I'm glad you have fixed your issue 🙂

For future reference, if you want to enable some of the `path_display` options, you need to put them in a list.
For example: `path_display = {"absolute","shorten"}` or `path_display = {"tail"}`
