### ISSUE TITLE
Telescope exit autocommand

### ISSUE THREAD

**Issue by oponkork** [nvim-telescope/telescope.nvim#1108]
**Is your feature request related to a problem? Please describe.**
I want to toggle autocompletion off (on)  when I enter (leave) telescope window. I tried the following autocommand
```vim
augroup mucompleteTelescope
    autocmd!
    autocmd User TelescopeFindPre MUcompleteAutoOff
    autocmd WinLeave,FileType TelescopePrompt MUcompleteAutoOn
augroup end
```
If I remove the second autocommand, I am able to disable the autocompletion.

The second autocommand however executes when I am in the telescope prompt and not when I leave it. I have also tried BufLeave instead of WinLeave.

**Comment by fdschmidt93** [comment]
Happy to hear that :) Closing this then.
