### ISSUE TITLE
Popup list of keymaps for current picker

### ISSUE THREAD

**Issue by fedoranvar** [nvim-telescope/telescope.nvim#1114]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by clason** [comment]
The template is there for a reason... (Don't make me turn this into a form, too!)

**Comment by clason** [comment]
I suspect that this is a duplicate of https://github.com/nvim-telescope/telescope.nvim/pull/1084 anyway. If it's not, please edit the issue to describe in detail what you want.

**Comment by fedoranvar** [comment]
sorry for bad searching
