### ISSUE TITLE
lsp_range_code_actions is broken

### ISSUE THREAD

**Issue by jan-xyz** [nvim-telescope/telescope.nvim#1119]
### Description

a workaround is to use the native function again https://github.com/neovim/neovim/pull/12962

### Neovim version

0.5.0

### Operating system and version

MacOS 11.5.2

### Steps to reproduce

1. install any language server with range support (e.g. gopls)
2. open a supported (Go) file
3. select multiple lines
4. execute `:Telescope lsp_range_code_actions`

### Expected behavior

a dialog opening to select the code action from

### Actual behavior

 The code action fails with `Error: no range allowed`

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
Thanks for reporting! I think upstream might have changed from the original range code actions PR? Unfortunately, I'm not using code actions in the languages I'm writing in myself, but happy to review a PR from anyone (maybe you @jan-xyz ? :) who takes a crack at it.

In general, a PR would likely have to reconcile `neovim/runtime/lua/vim/lsp/buf.lua` and `telescope/builtin/lsp.lua` with the respective code actions method. Should be straightforward so long as one can test it.

**Comment by jan-xyz** [comment]
Thanks for the pointer! I'll give it a shot in the next days.

**Comment by fdschmidt93** [comment]
Cool! You are very happy to reach out on our [Gitter](https://gitter.im/nvim-telescope/community) for ad-hoc questions. Typically, a (albeit small) group of people can actively help you :)
