### ISSUE TITLE
restrict find_file matches to respect the order in which characters are typed

### ISSUE THREAD

**Issue by kmeissner** [nvim-telescope/telescope.nvim#1121]
**Is your feature request related to a problem? Please describe.**
The find_file matcher matches on permutations of the characters in the search term, returning too many matches on directories with a lot of files.  for example
ortengine
was matched by the path
src/lib/engine/compute/primitive/embed.cpp

the characters are of the search term are in the result path, but occur in a different order.

**Describe the solution you'd like**
Enforce that the order in which characters appear in the search term must occur in the same order in the matching result string

So a search of 
ortengine
would be matched by 
src/code/ort/engine/embed.cpp
and would not be matched by paths like
...
src/lib/engine/compute/primitive/embed.cpp
src/engine/ort/embed.cpp
....

**Describe alternatives you've considered**
I have read the documentation looking for a flag to change the match rules but did not see find it in the documents. 

**Additional context**

**Comment by fdschmidt93** [comment]
To make sure, in other words, you'd like an _exact_ match of your query?

This can be achieved with [telescope-fzf-native](https://github.com/nvim-telescope/telescope-fzf-native.nvim) (just do `require('telescope').load_extension('fzf')` after your `telescope.setup` and for the moment ignore the remainder of the recommended setup, there's an inconsistency).

with `telescope-fzf-native` you can achieve an exact match by prefixing your query with `'` like so `'query`, which I think solves your issue.

**Comment by kmeissner** [comment]
ok thank you
