### ISSUE TITLE
I get an error with find_files.

### ISSUE THREAD

**Issue by nabezokodaikon** [nvim-telescope/telescope.nvim#1125]
### Description

I get an error with find_files.

### Neovim version

v0.6.0-dev+140-gc6ef95606

### Operating system and version

Mac 11.5.2

### Steps to reproduce

1. `nvim`
2. `:Telescope find_files find_command=rg,--ignore,--hidden,--files`

### Expected behavior

find_files succeeds.

### Actual behavior

`E5108: Error executing lua ...daikon/ws/issue/telescope.nvim/lua/telescope/command.lua:100: [string "return rg,--ignore
,--hidden,--files"]:1: unexpected symbol near '<eof>'`

### Minimal config

```Lua
[vimrc]
nnoremap <silent> <Leader>f :<C-u> Telescope find_files find_command=rg,--ignore,--hidden,--files<CR>

[init.lua]
require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_prefix = "> ",
    selection_caret = "> ",
    entry_prefix = "  ",
    initial_mode = "insert",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_config = {
      horizontal = {
        mirror = false,
      },
      vertical = {
        mirror = false,
      },
    },
    file_sorter =  require'telescope.sorters'.get_fuzzy_file,
    file_ignore_patterns = {},
    generic_sorter =  require'telescope.sorters'.get_generic_fuzzy_sorter,
    winblend = 0,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
    color_devicons = true,
    use_less = true,
    path_display = {},
    set_env = { ['COLORTERM'] = 'truecolor' }, -- default = nil,
    file_previewer = require'telescope.previewers'.vim_buffer_cat.new,
    grep_previewer = require'telescope.previewers'.vim_buffer_vimgrep.new,
    qflist_previewer = require'telescope.previewers'.vim_buffer_qflist.new,

    -- Developer configurations: Not meant for general override
    buffer_previewer_maker = require'telescope.previewers'.buffer_previewer_maker
  }
}
```

**Comment by fdschmidt93** [comment]
Thanks for reporting, this is a known issue and will be fixed here, hopefully by end of day: https://github.com/nvim-telescope/telescope.nvim/pull/1124

Alternatively, checkout f1a27baf279976845eb43c65e99a71d7f0f92d02 for the time being until the above PR gets merged.

**Comment by nabezokodaikon** [comment]
Thank you for your reply! I am waiting.

**Comment by l-kershaw** [comment]
@nabezokodaikon (and/or @fdschmidt93) if you could test the PR that would be very helpful.
If it solves the problem for you (and doesn't break anything else in your workflow), I'm happy to merge it as soon as I get back to my computer.

**Comment by nabezokodaikon** [comment]
After checking the operation of PR, `find_files` seems to be working properly.

**Comment by nabezokodaikon** [comment]
I confirmed that it works normally. Thank you for your support.
