### ISSUE TITLE
grep_string with empty string argument hangs telescope

### ISSUE THREAD

**Issue by tllilleh** [nvim-telescope/telescope.nvim#1130]
### Description

If I run the following on a large project and exit the results window telescope hangs:
:lua require('telescope.builtin').grep_string({search = ""})                                                                                                                          

I can see a process has been spawned and still running in the background.

While it is still running any other telescope operations don't show any results.  
e.g.:
:lua require('telescope.builtin').find_files()

Even after the process is done, all future Telescope operations seem much slower, restarting neovim seems to be the only solution.

### Neovim version

NVIM v0.5.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include Compiled by runner@fv-az242-526  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: " /home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"  Run :checkhealth for more info

### Operating system and version

Linux TENGD-6531 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. run command: :lua require('telescope.builtin').grep_string({search = ""})                                                                                                                          

### Expected behavior

I would expect when I close the results page (hit escape) all sub-processes would be killed and take up system resources

### Actual behavior

hang, slow behavior

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by tllilleh** [comment]
Note, I don't intentionally run grep_string with an empty search, I use the following mapping:

nnoremap <Space>g <cmd>lua require('telescope.builtin').grep_string({search = vim.fn.input("Grep For > ")})<cr>

and sometimes accidentally hit enter before typing in my query

**Comment by fdschmidt93** [comment]
This issue is expected to be addressed by #987, which will hopefully get merged soon.

Ideally, you check out the PR and give your detailed feedback over there in case it does not solve your problem.

**Comment by tllilleh** [comment]
It looks like that pull request (which was recently merged) solves part of my problem. 

That is, if I run grep_string({search =""}), other telescope features like find_files() will now work.  But I can see a load of ripgrep processes still running in the background (taking up quite a bit of my CPU time as well).  Furthermore, a subsequent grep_string() call is still slowed down until the first one finishes.  That is, if I run: grep_string({search = "foo"}) immediately after exiting the empty string search I still need to wait quite a long time to get any results.

But overall things are much better than before.

**Comment by tjdevries** [comment]
Does this fix the problem of leaving jobs hanging around? https://github.com/nvim-telescope/telescope.nvim/pull/1140

I think it should hopefully do that. Let me know if it does for you and I'll merge

**Comment by tllilleh** [comment]
Yes, PR #1140 resolves the last of my issues.  Thanks.
