### ISSUE TITLE
Command :Telescope errors out since today.

### ISSUE THREAD

**Issue by bushblade** [nvim-telescope/telescope.nvim#1132]
### Description

After updating my plugins today when I run :Telescope I get the error
```
E5107: Error loading lua [string ":lua"]:1:1 unexpected symbol near ')'
```
And Telescope fails to open.
All `:Telescope whatever_finder` commands work.
This was working as expected before I updated today so I suspect has something to do with #1128 or #1123 ?

### Neovim version

v0.5.0

### Operating system and version

Manjaro XFCE

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. :Telescope
![Screenshot_2021-08-20_14-34-25](https://user-images.githubusercontent.com/21976188/130241333-a961c02d-e3c1-4152-a8f9-917a0a449cd0.png)

### Expected behavior

Telescope should open.

### Actual behavior

Telescope fails to open and we get an error.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by G-Rowell** [comment]
Can second, 
I've had this problem too

Thank you regardless for the amazing plugin!!!!

**Comment by l-kershaw** [comment]
Sorry for breaking things! 😅 

[This](https://github.com/nvim-telescope/telescope.nvim/pull/1134) PR should hopefully fix the issue, but it would be helpful if people could test it.

**Comment by bushblade** [comment]
Hi @l-kershaw Lol! No worries, really appreciate such an awesome plugin.
I updated but the error is still there for me sadly.

**Comment by jonathannerat** [comment]
@bushblade The PR hasn't been merged yet. Once it's merged it should be gone. You can test it by changing your plugin definition to point to @/l-kershaw's fork / branch

**Comment by bushblade** [comment]
@jonathannerat Oh lol! That would explain it, I should have read the commits when I ran :PackerUpdate

**Comment by bushblade** [comment]
So I switched to using @l-kershaw 's fork/fix ...
```lua
    use {
      -- "nvim-telescope/telescope.nvim",
      "l-kershaw/telescope.nvim",
      branch = "fix/command_parser_fix_again",
      requires = {{"nvim-lua/popup.nvim"}, {"nvim-lua/plenary.nvim"}}
    }
```
But I still experience the same issue.

**Comment by jonathannerat** [comment]
You're absolutely right, my bad lol

For some reason I thought this had to do with what l-kershaw was fixing  but looks like I was wrong. Don't really know where this is coming from tho. For the time being, you can use `:Telescope builtin`, which works in the minimal config you provided

**Comment by bushblade** [comment]
@jonathannerat Thanks, can confirm `:Telescope builtin` is good for me.

**Comment by G-Rowell** [comment]
@l-kershaw 

Thank you very much for your effort and the amazing plugin!
really appreciate all the work you & the team do!

**Comment by bushblade** [comment]
Thank you, can confirm this is fixed for me now.
