### ISSUE TITLE
Find and set nvim options

### ISSUE THREAD

**Issue by clason** [nvim-telescope/telescope.nvim#114]
... like https://github.com/teto/nvim-palette, but in lua

@sunjon seems to have volunteered on gitter ;)

**Comment by sunjon** [comment]
Thinking of the best format to be able to display `opt_name`, `opt_type`,  `opt_value`.

https://github.com/nvim-lua/telescope.nvim/issues/118#issue-707508467

**Comment by tami5** [comment]
Does #133 closes your feature request ? if not please reopen and add feature request label.
