### ISSUE TITLE
Can't customize mappings of builtin picker

### ISSUE THREAD

**Issue by spindensity** [nvim-telescope/telescope.nvim#1145]
### Description

When customizing mappings of builtin picker, the following error occurred:

```log
E5108: Error executing lua ...k\packer\start\telescope.nvim\lua\telescope\mappings.lua:224: attempt to call local 'key_func' (a table value)
```

### Neovim version

NVIM v0.5.0

### Operating system and version

Windows 10 21H2

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Execute:
```vim
:Telescope buffers
```
3. Press <kbd>Ctrl</kbd> + <kbd>d</kbd>

### Expected behavior

No error occurred.

### Actual behavior

The following error occurred:

```log
E5108: Error executing lua ...k\packer\start\telescope.nvim\lua\telescope\mappings.lua:224: attempt to call local 'key_func' (a table value)
```

### Minimal config

```Lua
local fn = vim.fn
local cmd = vim.cmd

local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0
then
    fn.system({"git", "clone", "https://github.com/wbthomason/packer.nvim", install_path})
    cmd [[ packadd packer.nvim ]]
end

-- Only required if you have packer configured as `opt`
cmd [[ packadd packer.nvim ]]

cmd [[ autocmd BufWritePost plugins.lua source <afile> | PackerCompile ]]

require("packer").startup(function()
    -- Packer can manage itself
    use "wbthomason/packer.nvim"

    use {
        "nvim-telescope/telescope.nvim",
        requires = { { "nvim-lua/plenary.nvim" } }
    }
end)

local actions = require("telescope.actions")

require('telescope').setup{
    pickers = {
        buffers = {
            mappings = {
                i = {
                    ["<c-d>"] = actions.delete_buffer,
                },
                n = {
                    ["<c-d>"] = actions.delete_buffer,
                }
            }
        },
    },
}
```

**Comment by Conni2461** [comment]
Its weird i am also getting this since today. I am currently testing #1120 and it works there but in master, so i am not sure whats going on or what commit introduced this issue.

Can you confirm that #1120 fixes this issue?

**Comment by Conni2461** [comment]
Oh wait it doesn't happen in 1120 because the branch is not yet rebased. I am looking into this bug

**Comment by Conni2461** [comment]
Introduced in https://github.com/nvim-telescope/telescope.nvim/commit/a97af306c4e9c9a6fa7c886c0ffe3079822c5203 :sob: why is it always the biggest PR

**Comment by Conni2461** [comment]
Would be nice if you could try https://github.com/nvim-telescope/telescope.nvim/pull/1147 maybe this fixes your issue :)

**Comment by mattleong** [comment]
@Conni2461 I was experiencing the same issue. Looks like your fix seems to work! Thank you! 💯

**Comment by spindensity** [comment]
> Would be nice if you could try #1147 does this fix your issue :)

#1147 fixed the issue, thanks!

**Comment by dpetka2001** [comment]
After the fix the options in 'telescope.lua' for find_files stopped working. I had the following in my config
`require('telescope').setup{
  defaults = {
    prompt_prefix = "$ ",
    -- prompt_position = "top",
    sorting_strategy = "ascending",
    selection_caret = "> ",
    layout_config = {
      prompt_position = "top",
    }
  },
  pickers = {
    -- Your special builtin config goes in here
    buffers = {
      -- sort_lastused = true,
      -- theme = "dropdown",
      -- previewer = false,
      mappings = {
         i = {
           ["<c-d>"] = require("telescope.actions").delete_buffer,
           -- or right hand side can also be a the name of the action as string
           ["<c-d>"] = "delete_buffer",
           -- ["<c-a>"] = function() vim.cmd ":norm I" end,
           -- ["<c-e>"] = function() vim.cmd ":norm A" end,
           -- ["<c-u>"] = function() vim.cmd ":norm c0" end,
         },
         n = {
           ["<c-d>"] = require("telescope.actions").delete_buffer,
         }
       }
    },
    find_files = {
        find_command = { 'rg', '--hidden', '--files' },
    --   theme = "dropdown"
    },
  },
}
`,
so that find_files would use rg but it stopped working. I now changed the keymap i use in `nnoremap <leader>ff :Telescope find_files find_command=rg,--ignore,--hidden,--files<CR>
` to get the same behaviour as before. Does anyone have any hints as to what might have gone wrong?

**Comment by Conni2461** [comment]
@dpetka2001 should be fixed. Thanks for reporting :)

I wasnt sure if it was 100% correct so i did not merge it immediately. yeah i cant blame tami really because i provided the faulty implementation :rofl:

btw you can also just do but doesnt really matter :rofl: 
```lua
    find_files = {
        hidden = true,
    --   theme = "dropdown"
    },
```
