### ISSUE TITLE
:norm! A mapping for insert mode behaves strangely

### ISSUE THREAD

**Issue by trewjames** [nvim-telescope/telescope.nvim#1148]
### Description

adding a mapping in insert mode to jump to the end of the line causes strange behavior.

Came up as a point of discussion on [reddit](https://www.reddit.com/r/neovim/comments/p8jfo2/question_in_telescope_how_to_use_ca_ce_cu_etc/). Multiple people have expressed that they are experiencing this issue.

### Neovim version

0.5.0

### Operating system and version

Arch - Linux 5.13.10

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. open Telescope find_files
3. begin typing then while in insert mode, press <C-e>

### Expected behavior

The cursor should jump to the end of the currently typed line if not already there. Backspace removes any previously typed characters. (The other custom mappings in minimual.lua seem to work fine, only the `:norm! A` function is acting out).

### Actual behavior

Cursor jumps to the second to last character, and backspace seems to no only work on previously typed characters.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup(
    defaults = {
      mappings = {
        i = {
          ["<c-a>"] = function() vim.cmd ":norm! I" end,
          ["<c-e>"] = function() vim.cmd ":norm! A" end,
          ["<c-u>"] = function() vim.cmd ":norm! c0" end,
        },
      },
    },
)
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by tami5** [comment]
hmmmm, I don't think mapping these keys should be done here. Personally, I have the following in my config

```lua
 map["ic|<C-a>"] = "<Home>"
 map["ic|<C-e>"] = "<End>"
 map["ic|<C-f>"] = "<Right>"
 map["ic|<C-b>"] = "<Left>"
 map["ic|<C-h>"] = "<BS>"
```

Basically, doing `inoremap/cnoremap <C-a> <Home>` 

I can't imagine binding these keys only in telescope buffer, but here's how to set stuff in telescope prompt only:

```vim
autocmd! FileType TelescopePrompt inoremap <buffer><C-a> <Home>
```

I'm still in doubt whether this is a bug or not. Thanks @trewjames for reporting hope the above helps

**Comment by mauroporras** [comment]
@tami5 Working great, thank you. Any ideas on how to get <C-u> to delete up until the beginning of the line?

**Comment by tami5** [comment]
> @tami5 Working great, thank you. Any ideas on how to get `<C-u>` to delete up until the beginning of the line?
> 
> 

I believe this already mapped not sure it inherently works with me.

**Comment by mauroporras** [comment]
@tami5, it works out of the box for me too, except in Telescope. I'll keep researching. Thank you.

**Comment by tami5** [comment]
oh yah c-u is mapped by default to page up. I guess unmapping it would work, maybe set <c-u> to nil or add autocmd `iunmap <c-u>`

**Comment by mauroporras** [comment]
@tami5, unfortunately I'm still too noob to do that on my own. Would you please give some pointers?

These are working:

```vim
" Insert.
inoremap <C-a> <Home>
inoremap <C-b> <Left>
inoremap <C-d> <Del>
inoremap <C-e> <End>
inoremap <C-f> <Right>
```

**Comment by Conni2461** [comment]
Thanks tami for a the autocmd solution. For anyone in the future who is looking for a solution that enables this in the telescope config `:help telescope.defaults.mappings`. Example
```lua
require("telescope").setup {
  defaults = {
    mappings = {
      i = {
        ["<c-u>"] = false,
        ["<c-a>"] = { "<home>", type = "command" },
        ["<c-e>"] = { "<end>", type = "command" },
      },
    }
  },
}
```

does this answer your questions? Can we close this issue?

**Comment by trewjames** [comment]
all good from me as well. thanks everyone.
