### ISSUE TITLE
Searching with :Telescope find_files has strange issues

### ISSUE THREAD

**Issue by devinjameson** [nvim-telescope/telescope.nvim#1161]
### Description

When searching with the popup window using `:Telescope find_files`, two things happen:
-  Completion suggestions appear in another popup
- About half the time, the text typed into the Telescope popup window will be added to the opened file, replacing some of the content on the line and not allowing undo

<img width="662" alt="Screen Shot 2021-08-24 at 3 29 02 PM" src="https://user-images.githubusercontent.com/39350030/130678237-2374f66e-ecf1-4d6a-8ddb-237982383127.png">

### Neovim version

NVIM v0.5.0 Build type: Release LuaJIT 2.1.0-beta3

### Operating system and version

Mac OS 11.4

### Steps to reproduce

Just use `:Telescope find_files` and type something.

### Expected behavior

No completion suggestions appear. Search text does not randomly get added to the opened file.

### Actual behavior

Completion suggestions appear when searching. Sometimes, search text gets added to the opened file.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by clason** [comment]
Sorry, but I have to ask: is this happening with the minimal config provided?

**Comment by devinjameson** [comment]
> Sorry, but I have to ask: is this happening with the minimal config provided? Because that looks to me like interference from a completion plugin.

No sorry necessary. Honestly I'm not totally sure what the minimal config is. I don't have any lua stuff configured, just a vimrc. Would it be helpful to share that?

**Comment by clason** [comment]
No, I suspect that is far from minimal... Vim or Lua makes no difference, you can out your vimscript config in a big
```lua
vim.cmd [[
... your vimscript config here
]]
```
block where the `ADD INIT.LUA SETTINGS` is. (But how do you configure telescope without Lua?)

But it's important to start from the provided config (adding stuff where necessary); otherwise we can't pinpoint what's going wrong.

(Obviously, nobody so far has met with the problem you describe.)

**Comment by adwinwhite** [comment]
In my case, I can confirm that it's _completion-nvim_ conflicting with telescope.
If I trigger and confirm completion when using _live-grep_ , then typed characters  will be appended to where _live-grep_'s result lies.(Note that both completion's confirm key and _live-grep_'s confirm key are _Enter_)

**Comment by adwinwhite** [comment]
@tjdevries I figured out prompt buffer is named _prompt_bufnr_. But how can I specify it? Neovim's pattern matching only speaks to filename.

**Comment by Conni2461** [comment]
This person describes how to disable completion-nvim for the filetype `TelescopePrompt` https://github.com/nvim-telescope/telescope.nvim/issues/94#issuecomment-905314431
