### ISSUE TITLE
command no work on macos 

### ISSUE THREAD

**Issue by findNextStep** [nvim-telescope/telescope.nvim#1162]
### Description

show error E5108:  Error executing lua ...ueqian/.vim/plug/plenary.nvim/lua/plenary/popup/init.lua:208: Invalid key 'noautocmd'

### Neovim version

NVIM v0.5.0-dev+nightly-259-g516551319 Build type: Release LuaJIT 2.1.0-beta3

### Operating system and version

11.5.1 (20G80)

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. ...

### Actual behavior

show error like Description

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by tami5** [comment]
hmmm weird I'm on a mac and I just ran your minimal configuration and no issues. Can you share the steps to reproduce?

**Comment by findNextStep** [comment]
> hmmm weird I'm on a mac and I just ran your minimal configuration and no issues. Can you share the steps to reproduce?

what is your nvim version? I use nvim from homebrew and the minimal.lua in the issue template can be reproduced
![image](https://user-images.githubusercontent.com/26270464/130724554-589ee215-5be0-4772-a12f-d2ca52091548.png)

by the way, when open nvim with min.lua, i receive Error like below 
![image](https://user-images.githubusercontent.com/26270464/130724697-e8d9a59b-c4de-4330-a23f-6a523bc8d3ef.png)

**Comment by Conni2461** [comment]
> NVIM v0.5.0-dev+nightly-259

Is like not even close to a up to date neovim version. We require at neovim version 0.5(release version) or newer.
See also https://github.com/nvim-lua/plenary.nvim/issues/217 https://github.com/nvim-lua/plenary.nvim/issues/219

**Comment by findNextStep** [comment]
I had pin cmake so that nvim not upgrade

after upgrade nvim it work
