### ISSUE TITLE
Files with this kind of title [...title] not opening correctly on find_files

### ISSUE THREAD

**Issue by efierros** [nvim-telescope/telescope.nvim#1171]
### Description

Each time I trigger the command to find files with Telescope, I search for a file with this kind of title

`[...title].js`

And it doesn't open, it shows me a blank file, but the file es full of code

I believe is because it asumes the extension is: `..title].js`, Formatter also has trouble with this files

### Neovim version

0.5.0

### Operating system and version

macOS 11.5.2

### Steps to reproduce

1.- Create a file with the title [...title].js
2.- Try to open it with find_files command, I use this: `<Cmd>Telescope find_files find_command=rg,--ignore,--hidden,--files<CR>`

### Actual behavior

If I open the file from nvimTree, it opens fine
![Captura de Pantalla 2021-08-26 a la(s) 15 02 58](https://user-images.githubusercontent.com/5409160/131028570-66caf3d9-c904-4138-be78-294af89eb5ed.png)

If I search the file it shows me correctly the preview
![Captura de Pantalla 2021-08-26 a la(s) 15 04 04](https://user-images.githubusercontent.com/5409160/131028588-edaac4d7-e860-48f9-b7e9-b1d85cb0aa8a.png)

But once I opened the file is blank, it doesn't overwrite the file, just show it blank
![Captura de Pantalla 2021-08-26 a la(s) 15 04 16](https://user-images.githubusercontent.com/5409160/131028683-e291694a-25a7-4b05-b550-11b57e26402a.png)

### Minimal config

```Lua
This is my telescope config

require('telescope').setup {
    defaults = {
        vimgrep_arguments = {
            'rg',
            '--no-heading',
            '--with-filename',
            '--line-number',
            '--column',
            '--smart-case',
            '-u'
        },
        prompt_prefix = " ",
        selection_caret = " ",
        entry_prefix = "  ",
        initial_mode = "insert",
        selection_strategy = "reset",
        sorting_strategy = "ascending",
        layout_strategy = "vertical",
        layout_config = {
			prompt_position = "top",
			horizontal = {mirror = false}, vertical = {mirror = false},
			--width = 0.75,
			--preview_cutoff = 120,
		},
        file_sorter = require'telescope.sorters'.get_fzy_sorter,
        file_ignore_patterns = {},
        path_display = {
			--'shorten'
		},
        winblend = 0,
        border = {},
        borderchars = {'─', '│', '─', '│', '╭', '╮', '╯', '╰'},
        color_devicons = true,
        use_less = true,
        set_env = {['COLORTERM'] = 'truecolor'}, -- default = nil,
        file_previewer = require'telescope.previewers'.vim_buffer_cat.new,
        grep_previewer = require'telescope.previewers'.vim_buffer_vimgrep.new,
        qflist_previewer = require'telescope.previewers'.vim_buffer_qflist.new,

        -- Developer configurations: Not meant for general override
        buffer_previewer_maker = require'telescope.previewers'.buffer_previewer_maker,
        mappings = {
            i = {
                ["<C-j>"] = actions.move_selection_next,
                ["<C-k>"] = actions.move_selection_previous,
                -- To disable a keymap, put [map] = false
                -- So, to not map "<C-n>", just put
                -- ["<c-x>"] = false,
                ["<esc>"] = actions.close,

                -- Otherwise, just set the mapping to the function that you want it to be.
                -- ["<C-i>"] = actions.select_horizontal,

                -- Add up multiple actions
                ["<CR>"] = actions.select_default + actions.center

                -- You can perform as many actions in a row as you like
                -- ["<CR>"] = actions.select_default + actions.center + my_cool_custom_action,
            },
            n = {
                ["<C-j>"] = actions.move_selection_next,
                ["<C-k>"] = actions.move_selection_previous
                -- ["<C-i>"] = my_cool_custom_action,
            }
        },
        extensions = {
            media_files = {
                filetypes = {"png", "webp", "jpg", "jpeg", "mp4", "pdf"},
                find_cmd = "rg"
            },
            fzy_native = {
                override_generic_sorter = false,
                override_file_sorter = true,
            },
			project = {
				display_type = 'full'
			}
		}
    }
}
```

**Comment by tami5** [comment]
tbh, it's weird use case 😄. I can confirm the bug,  and it's because `[` needs to be escaped with \ for it to be opened via edit command.

https://github.com/nvim-telescope/telescope.nvim/blob/dcee6c81f4cd5f9bc4a4cea782135a0669aa74bd/lua/telescope/actions/set.lua#L132-L135

`Path:new(vim.fn.fnameescape(filename)):normalize(vim.loop.cwd())` should have taken care of that. 

executing `:exe "edit " . fnameescape("[...algo].js")` works without issues. However, 
- original: "/full/path/to/file/[...algo].js"
- after `fnameescape`: "/full/path/to/file/\\[...algo].js" (double escape is wrong)
- after normalize: `"/\\[...algo].js"` (path is gone, left with just name)

So it must be something todo with either normalize path or make_relative

- [lua/plenary/path.lua#L79-L105](https://github.com/nvim-lua/plenary.nvim/blob/15c3cb9e6311dc1a875eacb9fc8df69ca48d7402/lua/plenary/path.lua#L79-L105)

- [lua/plenary/path.lua#L292-L312](https://github.com/nvim-lua/plenary.nvim/blob/15c3cb9e6311dc1a875eacb9fc8df69ca48d7402/lua/plenary/path.lua#L292-L312)

For the life of me, I couldn't spot out what maybe causing this.

**Comment by itmecho** [comment]
So from what I can tell, the problem is coming `plenary.path` where the path is getting normalized to the root directory.

```
:lua print(string.format('edit %s', require('plenary.path'):new(vim.fn.fnameescape('pages/api/auth/[...nextAuth].ts'))))
edit pages/api/auth/\[...nextAuth].ts

-- same thing with the normalize call
:lua print(string.format('edit %s', require('plenary.path'):new(vim.fn.fnameescape('pages/api/auth/[...nextAuth].ts')):normalize(vim.loop.cwd())))
edit /pages/api/auth/\[...nextAuth].ts
```

**Comment by itmecho** [comment]
OK I've found the problem and a possible fix. I'll open a ticket on plenary

**Comment by tami5** [comment]
@itmecho open a pr better

**Comment by itmecho** [comment]
Meant to open it as a draft as I didn't have time to get everything working at work =[ Tidying it up now

**Comment by itmecho** [comment]
@tami5 Hopefully it's better now. The tests pass locally and I tested it with telescope and it now opens the files correctly

**Comment by 4ry1337** [comment]
I am still facing the same problem

trying to save 

![image](https://github.com/nvim-lua/plenary.nvim/assets/52571621/d8183936-7868-4531-8311-e5087a0e7598)

![image](https://github.com/nvim-lua/plenary.nvim/assets/52571621/52e75129-375f-473f-9f44-1a6943e98638)

**Comment by stf9** [comment]
I am also having this issue, did you figure it out?

**Comment by jluquer** [comment]
It happens to me too.

My workaround is to use a custom find_command:

`  
find_command = {
            "rg",
            "--files",
            "--glob",
            "!{.git/*,.svelte-kit/*,target/*,node_modules/*,.vscode/*}",
            "--path-separator",
            "/",
},
`

live_grep also fails. It shows an empty buffer when navigating to a file inside a (folder) but I did not found a workaround yet.
