### ISSUE TITLE
Suggestion for commands builtin copy command to register action

### ISSUE THREAD

**Issue by lbiaggi** [nvim-telescope/telescope.nvim#1177]
**Is your feature request related to a problem? Please describe.**
N/A
**Describe the solution you'd like**

I think the command pickers is awesome to search for something which you don't remember, especially when you are assigning a custom map in your neovim workflow, but I missed the ability to copy and paste it. I was amazed how easily I could make it knowing almost nothing about telescope stuff (just read the developer.md and project extension code) and thought that could be included or at least shared to others use it too.
**Describe alternatives you've considered**
I did this for myself, and thought that could be useful to others
```
custom_command_telescope.lua
local M = {}

local actions = require("telescope.actions")
local transform_mod = require('telescope.actions.mt').transform_mod

M.set_register = function(entry)
    local cmd = ":" .. entry.name
    vim.fn.setreg('+', cmd ,"c")
end

M.copy_to_reg = function(prompt_bufnr)
    local selected_entry = actions.get_selected_entry(prompt_bufnr)
    local value = selected_entry['value']
    M.set_register(value)
    actions.close(prompt_bufnr)
end

return transform_mod(M)
```
telescope command cfg
```
local custom_actions = require('custom_command_telescope')
...
  commands = {
    mappings = {
        n = {
            ["Y"] = custom_actions.copy_to_reg
        },
        i = {
            ["<C-Y>"] = custom_actions.copy_to_reg
        },
    },
...
```

**Additional context**

I think it could be extended to copy event definitions (pure lua bindings)

Regards,
Lucas

**Comment by tami5** [comment]
Interesting 😍 , I like your solution. my lazy solution to the problem was to map `jk` to `<esc>` and then select and copy. Thanks for sharing

**Comment by Conni2461** [comment]
Feel free to post a PR for that. I dont see a reason why we shouldnt ship this action :)

**Comment by lbiaggi** [comment]
Okay, If you don't mind explain,  where I should do? (I'm quite lost), how am I supposed to insert a map to Y and C-Y  [here](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/internal.lua#L278-L291) or isn't this the best place to do it?

**Comment by tami5** [comment]
> Okay, If you don't mind explain, where I should do? (I'm quite lost), how am I supposed to insert a map to Y and C-Y [here](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/internal.lua#L278-L291) or isn't this the best place to do it?

I suggest first trying to insert the custom function in https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/actions/init.lua then in the pr we can further discuss. I think these mapping perhaps better be available in all picker, and for that it would go into defaults. but first the custom function need to placed there

**Comment by lbiaggi** [comment]
@tami5 thanks, done.
