### ISSUE TITLE
Path with filename

### ISSUE THREAD

**Issue by menash134** [nvim-telescope/telescope.nvim#1178]
I have a big project with almost path depths go to 20. The result windows is not enought hence I am looking for smart file paths. My idea would be naive and simple.  Other path show patterns like shorten does not satisfy for our needs.
a) could you just allow me to configure the depths of the file path to be displayed? This would be ideal for my usecase. may be before the depth it could be "hidden/shorten"!!!
b) In the file preview window, you can display the full path of the file which might be also okay

**Comment by l-kershaw** [comment]
No worries, happy to help 🙂
