### ISSUE TITLE
Telescope throws error when trying to open plenary popup

### ISSUE THREAD

**Issue by seand52** [nvim-telescope/telescope.nvim#1180]
### Description

Hi,

2 days ago I upgraded my plugins and neovim to the latest version and I started having an issue with telescope when it tries to create a popup. If I launch any telescope function that creates a popup it throws the following error : 

`Error executing lua ...an/.vim/plugged/telescope.nvim/lua/telescope/pickers.lua:298: attempt to call field 'create' (a nil value)`

I tried adding a print statement in that line and it looks like the `popup` method in plenary does not have a create function :thinking: . 

The versions I'm working with are:
- neovim -> NVIM v0.6.0-dev+192-g32024787b
- telescope -> commit dcee6c81f4cd5f9bc4a4cea782135a0669aa74bd
- plenary -> commit 15c3cb9e6311dc1a875eacb9fc8df69ca48d7402
- lua -> 5.4.3
- OS -> Arch Linux x86_64

I made a minimal neovim config with just the stuff I need and it still throws the error.

### Neovim version

NVIM v0.6.0-dev+192-g32024787b

### Operating system and version

Arch Linux x86_64

### Steps to reproduce

1. nvim -nu minimal.vim
2. try to open any telescope function 

### Expected behavior

Should open the plenary popup

### Actual behavior

Throws the following error 
`E5108: Error executing lua ...an/.vim/plugged/telescope.nvim/lua/telescope/pickers.lua:298: attempt to call field 'create' (a nil value)`

### Minimal config

```Lua
call plug#begin('~/.vim/plugged')
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-lua/plenary.nvim'
call plug#end()


nnoremap <c-p> :Telescope find_files<cr>
nnoremap <leader>rg :Telescope live_grep<cr>
nnoremap <leader>rgs :Telescope grep_string<cr>
nnoremap <leader>b :Telescope buffers<cr>
nnoremap <leader>gb :Telescope git_bcommits<cr>
```

**Comment by clason** [comment]
Duplicate of https://github.com/nvim-telescope/telescope.nvim/issues/1106

**Comment by seand52** [comment]
Thanks! I managed to fix it looking at https://github.com/nvim-telescope/telescope.nvim/issues/1105. It was caused to do a mix of plugin managers.
