### ISSUE TITLE
line number preview

### ISSUE THREAD

**Issue by aspeddro** [nvim-telescope/telescope.nvim#1186]
Is it possible to show the line number? I saw that telescope uses `bat`

**Comment by fdschmidt93** [comment]
Does this work for you?

```lua
vim.cmd "autocmd User TelescopePreviewerLoaded setlocal number"
```

**Comment by aspeddro** [comment]
It works!

**Comment by yanzhang0219** [comment]
Hi, @fdschmidt93 

In my init.vim, I added `autocmd User TelescopePreviewerLoaded setlocal number` aiming to show line number in the preview window. However, when I select an entry, no number in the preview window, and if I select another entry and then select that previous entry again, the numbers appear. 

Is this a bug related to autocmd itself, or telescope? Thank you very much.

**Comment by weeman1337** [comment]
>  when I select an entry, no number in the preview window, and if I select another entry and then select that previous entry again, the numbers appear.

Can confirm that with NeoVim 0.6.1 and latest Telescope release. Will investigate later and open an issue with a minimal config.

**Comment by weeman1337** [comment]
#1661
