### ISSUE TITLE
live_grep doesn't show all files, missing/unimplemented/broken hidden=true option

### ISSUE THREAD

**Issue by Racle** [nvim-telescope/telescope.nvim#1189]
### Description

live_grep doesn't show all files (when editing ex. my [dotfiles](https://github.com/Racle/dotfiles)).

With `:Telescope find_files hidden=true` I can see sub folders (ex. `neovim/.config` on my dotfiles) and it finds files I want it to find, but I cannot replicate this with `:Telescope live_grep`. 

`:Telescope live_grep` shows only two files and searches text from those only. It doesn't see sub folders (ex. `neovim/.config`).

Adding `hidden=true` behaviour to `live_grep` would solve this (if there isn't any other solution to this, which I did not find)

You can find my current telescope config here: https://github.com/Racle/dotfiles/blob/master/neovim/.config/nvim/lua/plug-config/telescope.lua

### Neovim version

NVIM v0.6.0-dev

### Operating system and version

pop_os 21.04

### Steps to reproduce

1. `:Telescope live_grep`

### Expected behavior

See all files which are not in `file_ignore_patterns` like in `:Telescope find_files hidden=true`

### Actual behavior

See only files which are in hidden folders. 

### Minimal config

```Lua
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-telescope/telescope-media-files.nvim'
  
https://github.com/Racle/dotfiles/blob/master/neovim/.config/nvim/lua/plug-config/telescope.lua
```

**Comment by clason** [comment]
That's what the `vimgrep_arguments` option is for.

**Comment by Racle** [comment]
> That's what the `vimgrep_arguments` option is for.

I tried this but used `--glob` with `--hidden` before and it didn't work. 
Now I only added `--hidden` to defaults seems to be working as it should..

Thanks sorry for trouble.

**Comment by phortonssf** [comment]
@Racle Can you share your solution ty.

**Comment by Racle** [comment]
> @Racle Can you share your solution ty.

You can find my current working config here (same link as in my original post): https://github.com/Racle/dotfiles/blob/master/neovim/.config/nvim/lua/plug-config/telescope.lua

Hope that helps :)
