### ISSUE TITLE
Option missmatch between buffer and oldfiles picker options

### ISSUE THREAD

**Issue by thraizz** [nvim-telescope/telescope.nvim#1199]
### Description

The buffer picker accepts `only_cwd` as a restraining option, the oldfiles picker accepts `cwd_only` as an option.
I would submit a quick PR for this, but this will definitely break some configurations.
My main idea was to document this incosistency so I have to be the last one debugging why my buffers are restricted to the cwd but not my oldfiles when setting `only_cwd=true` :smile_cat:  

### Neovim version

NVIM v0.6.0-dev+163-g599af7451                                                                                                                       
Build type: RelWithDebInfo
LuaJIT 2.0.5

### Operating system and version

manjaro on 5.11.4-1-rt11-MANJARO

### Steps to reproduce

1. Configure keymaps for `Telescope buffer only_cwd=true` and `Telescope oldfiles only_cwd=true`
2.  Wonder why just one of the options restricts files to current working directory.

### Expected behavior

`only_cwd` should configure both buffer and oldfiles picker to limit matches to files in the current working directory.

### Actual behavior

`only_cwd` configures the buffer picker, `cwd_only` configures the oldfiles picker.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by thraizz** [comment]
Also neither are listed in the auto complete when running :Telescope oldfiles/buffers <TAB>

**Comment by fdschmidt93** [comment]
Fully agree this needs to be taken care of. Until somebody gets up to the task my take on is the same as in #1197 

>I'm not jumping at this, as once we maybe streamline path/filenames of results entries (eg see #1182) a holistic solution should apply to (almost) all pickers alike (cf. #1168) that'll then be adequately documented. In the meantime, I'm happy to be pragmatic and include it. A PR would be very welcome :)

We can then see how to universally add `only_cwd` or `cwd_only` as a simple flag theoretically passable to any picker.

**Comment by Conni2461** [comment]
happens if 130+ people work on a project :laughing: we can just treat `only_cwd` and `cwd_only` as synonyms and make both valid
