### ISSUE TITLE
Custom Picker Documentation / Example

### ISSUE THREAD

**Issue by aprowe** [nvim-telescope/telescope.nvim#1204]
The documentation on how to create a custom picker is missing some key information for a minimum working example. 
From the readme: 
```lua
function my_custom_picker(results)
  pickers.new(opts, {
    prompt_title = 'Custom Picker',
    finder = finders.new_table(results),
    sorter = sorters.fuzzy_with_index_bias(),
    attach_mappings = function(_, map)
      -- Map "<cr>" in insert mode to the function, actions.set_command_line
      map('i', '<cr>', actions.set_command_line)

      -- If the return value of `attach_mappings` is true, then the other
      -- default mappings are still applies.
      --
      -- Return false if you don't want any other mappings applied.
      --
      -- A return value _must_ be returned. It is an error to not return anything.
      return true
    end,
  }):find()
end
```

It was frustrating not knowing where `pickers`, `finders`, `sorters` are imported from. I had to dig into the telescope files, but 
then I'm looking at a huge file and it's hard to determine what is necessary, what I provide, and what I need to import.
It also was not totally clear from this example how I call this picker, or what `results` are. 
I figured out I just call it like a normal function, but then how do I import it into the list of pickers that Telescope provides?
I know this information is available from digging, but a complete yet minimal example I can copy and paste would go a long way.  I couldn't find a self-contained example of a custom picker.  

I hate to compare, but compare this to vim-clap's example (which has similar API to fzf): 
```lua
let g:clap_provider_quick_open = {
      \ 'source': ['~/.vimrc', '~/.spacevim', '~/.bashrc', '~/.tmux.conf'],
      \ 'sink': 'e',
      \ 'description': 'Quick open some dotfiles',
      \ }
```
It's immediately clear what this does, and I can copy and paste and have an example up and running immediately.

**Comment by Conni2461** [comment]
Working on it https://github.com/nvim-telescope/telescope.nvim/pull/1024

https://github.com/Conni2461/telescope.nvim/blob/docs_rework/developers.md
