### ISSUE TITLE
Strange problem with lazy load

### ISSUE THREAD

**Issue by 1478zhcy** [nvim-telescope/telescope.nvim#1206]
### Description

When I set telescope to lazy loading, There will be a error message when I use neovim to open a file,
but enter dashboard.nvim is safe.
![图片](https://user-images.githubusercontent.com/61115159/132010516-43e7e519-3a0b-4cde-9787-ed7cd52826d6.png)
The strangest thing is that if my terminal is bigger, this error message will not appear.
![图片](https://user-images.githubusercontent.com/61115159/132010475-5c5b234c-c855-4d73-898d-b75b5025da22.png)
Anyway, this does not affect the use.

### Neovim version

NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5

### Operating system and version

Arch Linux

### Steps to reproduce

1.Use packer.nvim set telescope to lazy load after the event 'VimEnter'
2.The terminal size should be the same as the picture
3.Open an existing or create a new file use `nvim <filename>`

### Actual behavior

![图片](https://user-images.githubusercontent.com/61115159/132010516-43e7e519-3a0b-4cde-9787-ed7cd52826d6.png)

### Minimal config

```Lua
local vim = vim
local packer = require'packer'

local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
  vim.cmd 'packadd packer.nvim'
end

vim.cmd([[
  augroup packer_user_config
    autocmd!
    autocmd BufWritePost plugins.lua source <afile> | PackerCompile
  augroup end
]])

return packer.startup(function (use)
  use {
    'nvim-telescope/telescope.nvim',
    config = function () require'config.tools.telescope' end,
    event = 'VimEnter',
    requires = {
      { 'nvim-lua/popup.nvim' },
      { 'nvim-lua/plenary.nvim' },
      { 'nvim-telescope/telescope-project.nvim' },
      { 'nvim-telescope/telescope-hop.nvim' },
      { 'nvim-telescope/telescope-dap.nvim' },
      { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
      { 'nvim-telescope/telescope-frecency.nvim' , require = 'tami5/sql.nvim' },
      { 'nvim-telescope/telescope-media-files.nvim' }
    }
  }
}
```

**Comment by clason** [comment]
Why are you doing that? That just breaks assumptions without any actual benefit (beside tricking the `--startuptime` counter...)

**Comment by clason** [comment]
But more to the point, the error message points to `nvim-treesitter`, not telescope.
