### ISSUE TITLE
Ability to go back to previous searches

### ISSUE THREAD

**Issue by wurosh** [nvim-telescope/telescope.nvim#1208]
**Is your feature request related to a problem? Please describe.**
I often search for something, then need to go back to reading some code, then want to go back to the previous search, but now I need to type it in the exact same way to get the same results (if I can get the same results at all)

**Describe the solution you'd like**
Something like [ivy's resume functionality](https://github.com/abo-abo/swiper/blob/master/ivy.el#L1201) would be really nice. A naive implementation could just save the search inputs and re-run the search, but a more robust one would also save the temporary buffers and restore them (and then modify them if the search changes)

My apologies if this is already implemented

**Comment by Conni2461** [comment]
Take a look at: `:help telescope.defaults.cache_picker` and `:help builtin.resume` and `:help builtin.pickers`.

You can also cycle to previous history entries. See `:help telescope.defaults.history`

**Comment by wurosh** [comment]
Thanks @Conni2461  - that resolves it. I'm still getting used to how help "scoping" works in Vim coming from Emacs so I'm not the best at the RTFM at the moment. Hopefully it gets better with time.

**Comment by fdschmidt93** [comment]
I can recommend the  `help_tags` picker is great for exploring the vim docs, which is accessible either via `:Telescope help_tags` or `lua require 'telescope.builtin'.help_tags` :)
