### ISSUE TITLE
Refresh quickfix list on respective file changes

### ISSUE THREAD

**Issue by samchan0221** [nvim-telescope/telescope.nvim#1209]
Is your feature request related to a problem? Please describe.
Sometimes I want to rename A to B on all the files (which LSP can't handle by refactoring) and I use the quick fix list to quickly work on them one by one. But when the list is too large it would be hard to navigate

Describe the solution you'd like
If I want them to disappear after it no longer match my searching query it would be nice, or if there is a manual function which we can call inside the quickfix buffer to refresh the buffer it would also be good enough! (because sometimes we don't want to refresh it as well)

**Comment by fdschmidt93** [comment]
I'm not sure, you could make a custom action in the `builtin.lsp_workspace_symbols` picker that renames the symbol of the current selection and then refreshes the search.

I'll try to have a look into that next week unless you'd want to take a a crack at that yourself, PRs welcome :)

**Comment by samchan0221** [comment]
> I'm not sure, you could make a custom action in the `builtin.lsp_workspace_symbols` picker that renames the symbol of the current selection and then refreshes the search. Would that do what you are looking for?
> 
> 
> 
> I'll try to have a look into that next week unless you'd want to take a a crack at that yourself, PRs welcome :)

I would definitely try that out. Thank you 😁

**Comment by fdschmidt93** [comment]
You're happy to ping me here in case you have any questions :)

**Comment by fdschmidt93** [comment]
I've also added this to #1190 as it also relates to another context.

**Comment by Conni2461** [comment]
Closing as wont fix

My two cents:

> Refresh quickfix list

We are not going to do this, because we are a fuzzy finder and not a qflist plugin

> custom action in the `builtin.lsp_workspace_symbols`

The lsp spec has a rename request support: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rename So it should be implemented there and in the lsp servers not here. Just saying but `vim.lsp.buf.rename` works great for me
