### ISSUE TITLE
CI tests are broken

### ISSUE THREAD

**Issue by l-kershaw** [nvim-telescope/telescope.nvim#1212]
### Description

The CI tests are currently not working due to there no longer being a "nightly" **release** for [neovim](https://github.com/neovim/neovim/tags).

@Conni2461 you seem to have been most involved in setting up the CI here (and I think in plenary too).
Any ideas for fixing this?

Problem first noticed in a couple of my plenary PRs, but also present in recently updated telescope PRs too.

### Neovim version

N/A

### Operating system and version

N/A

### Steps to reproduce

1. Run CI in any PR e.g. with a new commit.
2. Appimage and X64 Ubuntu tests fail.

### Actual behavior

Tests successfully use latest version of neovim.

### Minimal config

```Lua
N/A
```

**Comment by tami5** [comment]
I had the same issue in another project I'm working on. I'll look into it

**Comment by Conni2461** [comment]
We had this in the past a couple of time (its been a while). But sometimes neovim/neovim CI fails when doing the nightly release leaving us a day without a Release, so a day without CI. But usually 24 hours later its fixed. https://github.com/neovim/neovim/releases

Just reran your jobs and everything seems to work again

**Comment by l-kershaw** [comment]
Ah, wasn't sure if it was a conscious decision in neovim/neovim.
Thanks for explaining @Conni2461

Closing now
