### ISSUE TITLE
Items added to Quickfix window by `actions.smart_send_to_qflist` don't allow `cfdo` commands

### ISSUE THREAD

**Issue by benfrain** [nvim-telescope/telescope.nvim#1218]
### Description

If I grep via Telescope and add the four found files to the Quickfix with `<C-q>` then the quickfix works as expected. I am able to do something like `:cfdo :call append(4, '"status": "not started"')` to add a line to each file. Beautiful!

However, if I find files with Telescope, then select the files (using Tab) I want and run `["<C-q>"] = actions.smart_send_to_qflist + actions.open_qflist,`, which I used on the basis of info here: https://github.com/nvim-telescope/telescope.nvim/issues/634 then the Quickfix window appears but the results don't allow commands like `:cfdo :call append(4, '"status": "not started"')` – they have no effect on them.

### Neovim version

NVIM v0.5.0-dev+1384-gf2906a466
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 11.5.2

### Steps to reproduce

1. Open Telescope
2. Find Files and search for a string
3. From the list, select 2-3 files with Tab
4. Use the `actions.smart_send_to_qflist + actions.open_qflist` (think the default is `<A-q>`)
5. Try and run a cfdo command on those files such as adding a line with `:cfdo :call append(4, '"status": "not started"')`

### Expected behavior

I would expect the Quickfix window here to behave the same way as it works if using Find files and <C-q>.

### Actual behavior

Nothing occurs when running `cfdo` operations.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
For this to work the entry in question must have a `lnum` and (maybe only or?) `col` defined. For `builtin.live_grep` `:cfdo :call append(4, '"status": "not started"')` just works. Analogously, after I added `lnum` and `col` by hand to the selected entry, the command work just as well.

So you could do something like

```lua
require actions = require "telescope.actions"
require action_utils = require "telescope.actions.utils"

function preprocess_selections = function(selection)
 if not selection.lnum then
   selection.lnum = 1
 end
 if not selection.col then
   selection.col = 0
 end
end

function custom_smart_to_qf_list = function(prompt_bufnr)
  action_utils.map_selections(prompt_bufnr, preprocess_selections)
  actions.smart_send_to_qflist(prompt_bufnr)
end
```
I haven't tried it though it should work.

Alternatively, I guess we maybe could add to set these defaults to `send_to_qflist` or amend the `entry_maker` [here](https://github.com/nvim-telescope/telescope.nvim/blob/162cf7b5343eaf97c32c97af6a37452f9a3a9ca1/lua/telescope/make_entry.lua#L102) PRs welcome :)

**Comment by benfrain** [comment]
Thanks for the info @fdschmidt93, are there scenarios where one wouldn't want the `lnum` and `col` passing along by default?

If not, they seem like sensible things to include in the default behaviour.

I'm only familiar enough with Lua that I can sometimes make my `init.lua` work so a PR from me might be optimistic!  ;)
However, are you suggesting it may be as simple as adding your function into that file before the return?
