### ISSUE TITLE
Cursor position outside buffer error when opening from buffer picker and cursor is on the first column

### ISSUE THREAD

**Issue by akinsho** [nvim-telescope/telescope.nvim#1226]
### Description

When opening a buffer in a new tab from the buffer picker using `<c-t>` it seems that if the cursor is on the first column of the line the set cursor command at line 741 of the internal.lua file fails. I can successfully reproduce it inside log buffers, but it's a bit sporadic in other situations.

This relates to #957 which showed a similar error with an associated PR which fixed I think a part of this issue but there could also be another instance of the same bug in the related file below. 
```
E5108: Error executing lua ...er/opt/telescope.nvim/lua/telescope/builtin/internal.lua:741: Cursor position outside buffer
```
cc @Conni2461 (raised it as a separate issue as mentioned in the linked issue)

### Neovim version

:version
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmis
sing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FR
OM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacO
SX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info

### Operating system and version

macOS Big Sur & Ubuntu 20.04

### Steps to reproduce

1. Set buffer picker config to (Optional, maybe)
```lua
      buffers = {
        sort_mru = true,
        sort_lastused = true,
        show_all_buffers = true,
        ignore_current_buffer = true,
        previewer = false,
        theme = 'dropdown',
        mappings = {
          i = { ['<c-x>'] = 'delete_buffer' },
          n = { ['<c-x>'] = 'delete_buffer' },
        },
      },
```
2. open a file and move the cursor to the start of a line
3. move to another file
4. try to open the original file in a new tab using `<c-t>`

### Expected behavior

Should not error

### Actual behavior

Throws the above error

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
In my super quick trials I wasn't able to reproduce this with the steps you've laid out. Not 100% sure, maybe I'm missing something? I have to jump now but I'll look later in this tonight.

You've mentioned you can only reproduce this sporadically. Can you (if possible) please lay out the steps to reproduce this safely? Thanks in advance!

**Comment by akinsho** [comment]
@fdschmidt93 thanks for having a look, yeah I'm able to quite consistently reproduce it in quite a specific situation but I haven't been able to boil it down to quite a general minimal case (or at least the case I suggested isn't consistent)

**Comment by fdschmidt93** [comment]
Could you please try this buffer picker in the case in which an error occurs?


```lua
local action_set = require "telescope.actions.set"
local action_state = require "telescope.actions.state"

require "telescope.builtin".buffers {
  attach_mappings = function()
    action_set.select:enhance {
      pre = function(_)
        -- check lnum and col (col may not be set)
        local entry = action_state.get_selected_entry()
        print(vim.inspect(entry))
      end
    }
    return true
  end
}
```

`lnum` and `col` for some reason must be invalid. Hopefully that gets us closer pinning this down :sweat_smile:

**Comment by akinsho** [comment]
Thanks, will give that a try and report back

**Comment by akinsho** [comment]
@fdschmidt93 just tried this locally and got
```
{
  bufnr = 11,
  display = <function 1>,
  filename = "__FLUTTER_DEV_LOG__",
  index = 4,
  indicator = " a  ",
  lnum = 401,
  ordinal = "11 : __FLUTTER_DEV_LOG__",
  valid = true,
  value = "__FLUTTER_DEV_LOG__"

E5108: Error executing lua ...er/opt/telescope.nvim/lua/telescope/builtin/internal.lua:741: Cursor position outside buffer
```
when trying to open my log buffer in a new tab. The key thing to note it that the `lnum` is being reported as `401` but at the time this buffer had only one line in it.

I'm wondering if the issue could be related to having an old record of the lnum, basically my log buffer gets populated as my app runs but from time to time I restart nvim and the buffer is persisted in my session so nvim opens again but the file isn't being saved to disc or anything so it's empty on restart. It could have been that it had 400 lines in my previous session, except where would the old entry data be coming from. Are entries persisted somewhere outside of the cache picker. I also use the `smart-history` extension but that's for getting old searches back so not sure why it would affect the entry value.
