### ISSUE TITLE
Add an option to control if `lsp_definitions` picker shows a menu or not when there is only one definition to jump to.

### ISSUE THREAD

**Issue by d0u9** [nvim-telescope/telescope.nvim#1227]
**Describe the solution you'd like**
For `builtin.lsp_definitions` picker, when only one definition of the word under the cursor is available, **telescope** will jump to that definition instead of showing a menu.

This makes me cumbersome if what I want is a simple preview other than jumping to. So, I suggest adding an option, e.g. `alway_show_in_telescop`, for `builtin.lsp_definitions` which controls such behavior.

**Comment by fdschmidt93** [comment]
This is already possible with `:Telescope lsp_definitions jump_type=never` or `require("telescope.builtin").lsp_definitions { jump_type = "never" }`.

See also `:h builtin.lsp_definitions` (preferably viewed via `:Telescope help_tags`, of course :)

**Comment by d0u9** [comment]
Thank you, @fdschmidt93. 💯
