### ISSUE TITLE
`E523: Not allowed here` when binding Telescope pickers to key

### ISSUE THREAD

**Issue by babygau** [nvim-telescope/telescope.nvim#1235]
### Description

I got a few pickers bound to a global table `_G.tdt.telescope` such as `find_files`, `live_grep`..., using

`vim.api.nvim_set_keymap("n", "<Leader>;", ("v:lua.tdt.telescope.live_grep()"), {expr = true, noremap = true, nowait = true})` 

resulted in 

![image](https://user-images.githubusercontent.com/1514823/132981473-771a5d6a-6273-4eaf-8ad0-5c9a4f8747e4.png)

However using

`vim.api.nvim_set_keymap("n", "<Leader>;", ("<Cmd>lua tdt.telescope.live_grep()<CR>"), {expr = true, noremap = true, nowait = true})` 

worked.

### Neovim version

NVIM v0.6.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld1

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/nix/store/vz0h2gg4bmb3xaa6r9ga30ylk2zbaj5c-neovim-unwrapped-master/share/nvim"

Run :checkhealth for more info

### Operating system and version

macos 11.5

### Steps to reproduce

1. Press <Leader>; to search `live_grep`
2. Error occured

### Expected behavior

Telescope pickers should worked when binding key using global functions

### Actual behavior

![image](https://user-images.githubusercontent.com/1514823/132981473-771a5d6a-6273-4eaf-8ad0-5c9a4f8747e4.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by l-kershaw** [comment]
You don't appear to have added the relevant configuration to the minimal config you have provided.
Could you please give all of the information regarding this mapping (how have you defined it, when are you trying to map it, etc...) so that your issue can be looked at?
It makes it a lot easier for someone to help if you give the minimum number of steps to reproduce your issue

**Comment by babygau** [comment]
Sorry for that. The reason is my config is written in fennel. FYI, the mapping is defined in `telescope.fnl` which is called from  telescope packer config, as I mentioned above, the custom picker (https://github.com/nvim-telescope/telescope.nvim/issues/938#issuecomment-916688222) seems not working with `v:lua.` but working with `lua ....`. I've looked up `E523`, it is about set `secure` option, but I don't have that one in my config, and the error came from `plenary`. 

I understand it's not a good way to describe my problem, but please bear with me, I'll post my config later when I'm home.

**Comment by babygau** [comment]
@l-kershaw here is my config

```fennel
(import-macros {: nmap! : noremap!} :core.macros)

(local telescope (require :telescope))
(local telescope/utils (require :telescope.utils))
(local telescope/themes (require :telescope.themes))
(local telescope/previewers (require :telescope.previewers))
(local telescope/actions (require :telescope.actions))
(local telescope/builtins (require :telescope.builtin))
(local {: merge! : run!} (require :cljlib))

;; TODO: move telescope settings to global table `tdt.plugins.telescope`
(telescope.setup {:defaults {:cache_picker {:num_pickers 20}
                             :prompt_prefix "❯ "
                             :selection_caret "❯ "
                             :borderchars ["─"
                                           "│"
                                           "─"
                                           "│"
                                           "┌"
                                           "┐"
                                           "┘"
                                           "└"]
                             :path_display ["smart" "absolute"]
                             :disable_devicons true
                             :winblend 0
                             :sorting_strategy :ascending
                             :layout_strategy :flex
                             :layout_config {:prompt_position "top"
                                             :height 0.8}
                             :mappings {:i {:<ESC> telescope/actions.close}}
                             :file_ignore_patterns [:.git/
                                                    :node_modules/.*
                                                    :.neuron/.*
                                                    :alfred2/.*]
                             :file_previewer telescope/previewers.vim_buffer_cat.new
                             :grep_previewer telescope/previewers.vim_buffer_vimgrep.new
                             :qflist_previewer telescope/previewers.vim_buffer_qflist.new}
                  :extensions {:fzf {:fuzzy true
                                     :override_generic_sorter false
                                     :override_file_sorter true
                                     :case_mode :smart_case}}})

;;;; Load extensions
(->> [:fzf :projects]
     (run! telescope.load_extension))

(local picker-opts (telescope/themes.get_ivy {:borderchars ["─"
                                                          "│"
                                                          "─"
                                                          "│"
                                                          "┌"
                                                          "┐"
                                                          "┘"
                                                          "└"]
                                            :disable_devicons true}))
;; https://github.com/nvim-telescope/telescope.nvim/issues/938#issuecomment-916688222
(local pickers
    (setmetatable {}
                  {:__index (fn [_ key]
                              (when (= (. telescope/builtins key) nil)
                                (error "Invalid key, please check :h telescope.builtin")
                                (lua "return "))
                              (fn [opts]
                                (set-forcibly! opts (merge! (or opts {}) picker-opts))
                                ((. telescope/builtins key) opts)))}))

;; https://www.reddit.com/r/neovim/comments/p1xj92/make_telescope_git_files_revert_back_to_find
(fn project-files []
  (let [(_ ret _) (telescope/utils.get_os_command_output [:git :rev-parse :--is-inside-work-tree])]
    (if (= ret 0) (pickers.git_files) (pickers.find_files))))

;; fnlfmt: skip
(->> {:project_files   project-files
      :live_grep       pickers.live_grep
      :grep_string     pickers.grep_string
      :find_files      pickers.find_files
      :git_files       pickers.git_files
      :oldfiles        pickers.oldfiles
      :buffers         pickers.buffers
      :commands        pickers.commands
      :command_history pickers.command_history
      :keymaps         pickers.keymaps
      :pickers         pickers.pickers}
     (set tdt.telescope))

;;;; Telescope keymaps WORKING
;; fnlfmt: skip
(noremap! [n :nowait] "<Leader><Leader>" "<Cmd>lua tdt.telescope.project_files()<CR>")
(noremap! [n :nowait] "<Leader>ht"       "<Cmd>Telescope<CR>")
(noremap! [n :nowait] "<Leader>;"        "<Cmd>lua tdt.telescope.live_grep()<CR>")

;;;; NOT WORKING!
(noremap! [n :nowait] "<Leader><Leader>" "v:lua.tdt.telescope.project_files()")
(noremap! [n :nowait] "<Leader>;"        "v:lua.tdt.telescope.live_grep()<CR>")

**Comment by tjdevries** [comment]
```
vim.api.nvim_set_keymap("n", "<Leader>;", ("<Cmd>lua tdt.telescope.live_grep()<CR>"), {expr = true, noremap = true, nowait = true})
```

This isn't an expression. So don't put `expr = true`

**Comment by babygau** [comment]
@tjdevries, sorry, you're right, it's my bad, actually there was no `expr = true` in that keymap.
But as I mentioned above, using `"<Cmd>lua ....<CR>"` worked for me, but I couldn't use `"v:lua...()"` on the same function as an alternative
`vim.api.nvim_set_keymap("n", "<Leader>;", ("v:lua.tdt.telescope.live_grep()"), {expr = true, noremap = true, nowait = true})`

**Comment by tami5** [comment]
> @tjdevries, sorry, you're right, it's my bad, actually there was no `expr = true` in that keymap.
> 
> But as I mentioned above, using `"<Cmd>lua ....<CR>"` worked for me, but I couldn't use `"v:lua...()"` on the same function as an alternative
> 
> `vim.api.nvim_set_keymap("n", "<Leader>;", ("v:lua.tdt.telescope.live_grep()"), {expr = true, noremap = true, nowait = true})`

if I remember correctly, v:lua needs `:call` in front

**Comment by babygau** [comment]
> if I remember correctly, v:lua needs `:call` in front
@tami5 thank you for your response. We don't need that one in `rhs` of keymap function. I got other keymaps which use the same `v:lua..` syntax and they are all working except for `telescope`. I know it's weird, and it's not a critical bug because I'm still able to use with `lua ...`. In addition, I'm not sure it's related to `telescope` since the error came from `plenary/popup`

**Comment by DanielRivasMD** [comment]
So can you exemplify which the correct form to bind Telescope call is. I have the same problem, but my config is: `map('n', '<C-t>', '<cmd>lua require(\'telescope.builtin\').find_files()<CR>')`

`E523: Not allowed here`

Appreciated your response. Cheers

**Comment by babygau** [comment]
@DanielRivasMD sorry for late response. There's possibly sth wrong with you `map` function, make sure it doesn't have `{expr = true}`. An alternative `<Cmd>Telescope find_files<CR>` should be OK. My issue is about using global function with `v:lua`

**Comment by chenle02** [comment]
Hello everyone,

Has this issue been solved? I am having the same issue here:

```
vim.api.nvim_set_keymap("n", ";s", [[<Cmd>lua require'le.telescope'.grep_dotfiles()<CR>]], { noremap = true, silent = true })
```

Then 

```
E523: Not allowed here
```

**Comment by simonweil** [comment]
I'm getting this `E523: Not allowed here` issue on daily basis :(

**Comment by simonweil** [comment]
For reference, this solution of disabling completion fixed the issue for me: https://github.com/nvim-telescope/telescope.nvim/issues/82#issuecomment-854596669

**Comment by tjdevries** [comment]
Disabling completion should fix the issue. Nothing we can do on our side I don't think.
