### ISSUE TITLE
actions.send_to_qflist with `<c-q>` needs to be pressed twice to close window

### ISSUE THREAD

**Issue by malkomalko** [nvim-telescope/telescope.nvim#1244]
### Description

It seems like I need to hit `<c-q>` to pop open the quick fix list action.  Is this expected behavior?  I expected the action to fire and have it close the telescope gui.

### Neovim version

NVIM v0.6.0-dev+230-gd8339be69
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 11.5.2

### Steps to reproduce

`nvim -nu minimal.lua`

### Expected behavior

I hit `<c-q>` to fire the qfix list action and I see the qfix list with the selection.

### Actual behavior

I have to hit `<c-q>` twice.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
Cannot reproduce, my hunch tells me it's the same as https://github.com/nvim-telescope/telescope.nvim/issues/919 (also macOS). Hopefully that helps :)

**Comment by malkomalko** [comment]
Thank you.  I'll close this out and look on my end.

**Comment by malkomalko** [comment]
Adding this here for reference with a fix incase somebody searches for this same issue in the future: https://github.com/alacritty/alacritty/issues/1359
