### ISSUE TITLE
Display the filename along with the path in file pickers

### ISSUE THREAD

**Issue by chuwy** [nvim-telescope/telescope.nvim#1246]
**Is your feature request related to a problem? Please describe.**
When I work with a project with deeply nested folder structure I find it very hard to navigate to files with `git_files`, `find_files` etc because actual filenames are not fitting into the window, see the screenshot.

<img width="1402" alt="Screenshot 2021-09-15 at 13 53 28" src="https://user-images.githubusercontent.com/681171/133422500-c8886f91-9984-4135-b281-2e0f71e959f7.png">

**Describe the solution you'd like**
I'd like the filename to be displayed separately from the full path, for example at the bottom of preview area. 

**Describe alternatives you've considered**
Another altenative would be to right-alight the filepaths, so that I see the end of the path with filename, but don't see the beginning of the path.

**Additional context**
I was searching mostly for "filename" and "file name" to see if there's already a setting, but couldn't find anything.

**Comment by l-kershaw** [comment]
What you are looking for is the `path_display` option, see `:h telescope.defaults.path_display`.
If you only want to show filenames, you can set `path_display={"tail"}` to achieve this, e.g.:
`:Telescope find_files path_display={"tail"}`
The `shorten` option might work well for you too.

You could also provide a custom function to define how paths are displayed, the example in the docs might be helpful for you there.

---

I will close this issue now, but feel free to reopen it if you need more help 🙂

**Comment by Conni2461** [comment]
Also dup of https://github.com/nvim-telescope/telescope.nvim/issues/1167
