### ISSUE TITLE
Can't delete characters after navigting the search field 

### ISSUE THREAD

**Issue by mkuratczyk** [nvim-telescope/telescope.nvim#1251]
### Description

If I open `:Telescope find_files` (for example), type in a few characters and then try navigating in the search field, for example to fix a typo, I can't really do that. A few ways to trigger the issue:
1. Type in a few characters, press backspace/^H - you can delete what you typed in. Now press left arrow and then right arrow and try deleting a character now - I can no longer do that.
2. Another way - type in a few characters, let's say you made a typo - use left arrow to go back and try to delete a character - I can't
3. Another way - type in a few characters, press ESC, press `a` - again, you can't delete what you typed in before pressing ESC.

This behavior is strangely familiar - I believe that's how the original `vi` behaved (and `vim` in compatibility mode). Perhaps the search field runs in the compatibility mode?

Thank you for the amazing work!

### Neovim version

NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 11.6

### checkhealth telescope

health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

### Steps to reproduce

As described above.

### Expected behavior

Being able to edit the search field after navigating using arrow keys or movements in normal mode.

### Actual behavior

Can't delete characters.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
Upstream prompt buffers bug. See also #852 #829 #692 #567 #261

you can fix this by disabling prompt_prefix

**Comment by mkuratczyk** [comment]
I don't know how I missed these previous issues. Thank you!

**Comment by Conni2461** [comment]
Dont worry :)

Lets keep these upstream issues open

**Comment by elianiva** [comment]
it has been fixed upstream, try using master after this PR https://github.com/neovim/neovim/pull/16421

**Comment by Conni2461** [comment]
tested it. Its fixed upstream. Closing this issue

**Comment by jrafaaael** [comment]
Same error here. The error is present in the version 0.6 and 0.6.1 of neovim. I solved it setting prompt_prefix equals to a empty string in the Telescope config
