### ISSUE TITLE
no syntax highlight in preview window with toml file 

### ISSUE THREAD

**Issue by krisfans** [nvim-telescope/telescope.nvim#1259]
### Description

no syntax highlight in preview window with toml file 
![Snipaste_2021-09-19_14-20-01](https://user-images.githubusercontent.com/57793534/133917591-4b7aca86-cd11-4a05-a108-ab8fe37d99c7.png)

### Neovim version

NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

windows subsystem for linux (wsl) Ubuntu 20.04 LTS

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 11.0.2
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. `nvim -u minimal.vim a.toml`
2. `:Telescope oldfiles`

### Expected behavior

![Snipaste_2021-09-19_14-22-10](https://user-images.githubusercontent.com/57793534/133917662-d16eadc0-bef6-4cf0-bc14-57839b076677.png)

### Actual behavior

![Snipaste_2021-09-19_14-20-01](https://user-images.githubusercontent.com/57793534/133917630-e2c1abb8-575c-4e3c-a515-654abe2028c0.png)

### Minimal config

```Lua
set encoding=utf-8
"dein Scripts-----------------------------
if &compatible
    set nocompatible               " Be iMproved
endif

set runtimepath+=~/.cache/nvim/dein/repos/github.com/Shougo/dein.vim
call dein#begin($HOME . '/.cache/nvim/dein')
call dein#add($HOME . '/.cache/nvim/dein')
call dein#add('nvim-treesitter/nvim-treesitter')
call dein#add('nvim-treesitter/nvim-treesitter-refactor')
call dein#add('kyazdani42/nvim-web-devicons')
call dein#add('nvim-telescope/telescope.nvim')
call dein#add('nvim-lua/plenary.nvim')
call dein#add('cespare/vim-toml')
call dein#end()

call dein#call_hook('source')
call dein#call_hook('post_source')
let g:dein#auto_recache = 1
" Required:
filetype plugin indent on
syntax enable

set background=dark

lua << EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = "all",
    highlight = { enable = true, },
    indent = { enable = true },
    refactor = {
        highlight_definitions = { enable = true },
        highlight_current_scope = { enable = false },
    },
}
EOF
```

**Comment by fdschmidt93** [comment]
The reason for this is our new buffer previewer, which essentially blocks toml as it's not picked up by plenary's filetype detection and thus more an upstream plenary issue. 

Would you mind making a PR that adds toml to https://github.com/nvim-lua/plenary.nvim/blob/master/data/plenary/filetypes/base.lua ? That would resolve the issue :) I tested it with a manual override in the code base and then it works.

**Comment by Conni2461** [comment]
Wrong file. `base.lua` is autogenerated and shouldnt be touched. You can open a PR that adds it to https://github.com/nvim-lua/plenary.nvim/blob/master/data/plenary/filetypes/builtin.lua

That "hail mary" idea is probably not worth it. We are not missing that many file types that its worth it implementing.

**Comment by Conni2461** [comment]
`toml` does already work. At least for me `lua print(require("plenary.filetype").detect("asdf.toml"))` because files with extension = filetype just work.

I forgot i added this to plenary filetype some time ago. (I think i added it for `bib` or so)
