### ISSUE TITLE
Windows 10 backslash escape crash

### ISSUE THREAD

**Issue by ruimgoncalves** [nvim-telescope/telescope.nvim#1263]
### Description

In Windows 10 using Windows Terminal with PowerShell Core, searching for `\` or a binary file that displays the message `Binary cannot be previewed` surround by backslash characters, Neovim crashes.

It seems the problem is when escaping backslashes when using any console windows terminal, being cmd, powershell, cygwin but works fine in nvim-qt.

### Neovim version
```markdown
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-786

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
```

### Operating system and version

Windows 10 21H1

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `fzy_native`
  - INFO: No healthcheck provided
```

### Steps to reproduce

```console
1. nvim .
2. :Telescope find_files
3. \
```

### Actual behavior

Nvim crashes because some escape characters are thrown to the terminal, after the input prompt

![image](https://user-images.githubusercontent.com/1674884/133937836-25f61852-6ec1-40bc-9c08-fd3ec550da18.png)

### Minimal config

```Lua
require('telescope').setup {
  defaults = {
    -- Default configuration for telescope goes here:
    -- config_key = value,
    -- ..
    -- buffer_previewer_maker = new_maker,
    default = {
	COLORTERM = "truecolor"
    }
  },
  pickers = {
    -- Default configuration for builtin pickers goes here:
    -- picker_name = {
    --   picker_config_key = value,
    --   ...
    -- }
    -- Now the picker_config_key will be applied every time you call this
    -- builtin picker
  },
  extensions = {
    fzf = {
      fuzzy = true,                    -- false will only do exact matching
      override_generic_sorter = true,  -- override the generic sorter
      override_file_sorter = true,     -- override the file sorter
      case_mode = "smart_case",        -- or "ignore_case" or "respect_case"
                                       -- the default case_mode is "smart_case"
    }
  }
}
-- To get fzf loaded and working with telescope, you need to call
-- load_extension, somewhere after setup function:
require('telescope').load_extension('fzy_native')
```

**Comment by fdschmidt93** [comment]
Is `file` in your path when using TUI? Does it work if you turn off checking for mime types?

```lua
telescope.setup {
  defaults = {
    preview = {
      check_mime_type = false
    },
  }
}
```

**Comment by ruimgoncalves** [comment]
Disabling `check_mime_type` seems to prevent the issue, thanks!

Are you referencing `file` to be the `$VIM\sysinit.vim`, in this case no, it's not in my path

**Comment by fdschmidt93** [comment]
What does 
 
```lua
lua print(1 == vim.fn.executable "file")
```

return for you?

**Comment by ruimgoncalves** [comment]
```lua
lua print(1 == vim.fn.executable "file")
```
returns `true`

After some digging around, returning before line 217 prevents the error, returning after line 217 produces the error.

```lua
   local output = capture(string.format([[file --mime-type -b "%s"]], filepath)) 
```

Is `capture` leaking some chars into tui?

Here are some permutations that produce the same result

```lua
 local output = capture(string.format([[file --mime-type -b "%s"]], filepath)) 
 local output = capture(string.format([[file --mime-type -b "%s"]], filepath:gsub("\\", "/"))) 
 local ran, output = pcall(capture,string.format([[file --mime-type -b '%s']], filepath:gsub("\\", "/"))) 
```

**Comment by fdschmidt93** [comment]
> Is capture leaking some chars into tui?

I wouldn't know why that would be the case.

> Here are some permutations that produce the same result

To clarify, these variants you mean also produce the leakage? Otherwise asked, is there a version that works? Really just to knock down all possibilities here, I'm assuming file is the correct binary? eg the same one is in linux such that you can use the command to get the mime type?
 
I think the easiest fix for this would be switching to the plenary Job API which should be possible once https://github.com/neovim/neovim/pull/15658 lands, which itself should be hopefully some time soon. Then we'd however have the issue that that wouldn't be a fix for 0.5 users I guess. Ideally is there is one `capture` variant that works :sweat_smile: in your scenario.

We are only using `capture` because we are in vim.loop.fs_* callback which doesn't have access to vim functions on which plenary Job relies (`vim.wait`) to be exact.

**Comment by fdschmidt93** [comment]
@dantearaujo1 could you please share your config? Just making sure you've disabled `check_mime_type` adequately before because it seems to be an outlier compared to other windows users.

As per the general issue, maybe we should default to turning off `check_mime_type` by default for Windows users as there doesn't seem to be a good out-of-the-box solution. Windows users would have to install `file` to have simple tool that is just as convenient as on UNIX systems.

Thoughts?

**Comment by dantearaujo1** [comment]
## NVIM VERSION
NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compilado por runneradmin@fv-az152-633

Features: -acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM\sysinit.vim"
            padrão para $VIM: "C:/Program Files/nvim/share/nvim"
## Terminal
- Windows Terminal running Cmder with TERM set to =xterm-256color
- 
## CHECKHEALTH log

health#telescope#check
========================================================================
Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

Checking external dependencies
  - OK: rg: found ripgrep 12.1.1 (rev 7cb211378a)
  - OK: fd: found fd 8.1.1
===== Installed extensions =====

 Telescope Extension: `dap`
  - INFO: No healthcheck provided
 Telescope Extension: `repo`
  - INFO: No healthcheck provided

health#nvim_treesitter#check
========================================================================
 Installation
  - OK: `tree-sitter` found  0.20.0 (e85a279cf29da1b08648e27214dda20a841e57c8) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.13.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { "clang", "gcc" }
    Version: clang version 12.0.1
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

 Parser/Features H L F I J
  - vim            ✓ ✓ . . ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ . ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - json5          ✓ . . . ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

health#lspconfig#check
========================================================================
 Checking language server protocol configuration
  - INFO: html: configuration checked.
  - INFO: omnisharp: configuration checked.
  - INFO: intelephense: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: cmake: configuration checked.
  - INFO: clangd: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: pyright: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: solargraph: configuration checked.
  - INFO: sqlls: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: jdtls: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: tsserver: configuration checked.

health#mkdp#check
========================================================================
  - INFO: Platform: win
  - INFO: Nvim Version: NVIM v0.5.1
  - INFO: Node version: v14.13.0

  - INFO: Script: D:\Code\Configurations\nvim\nvim-data\site\pack\packer\start\markdown-preview.nvim/app/server.js
  - INFO: Script exists: 1
  - OK: Using node

health#nvim#check
========================================================================
 Configuration
  - OK: no issues found

 Performance
  - OK: Build type: RelWithDebInfo

 Remote Plugins
  - OK: Up to date

 terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
 Clipboard (optional)
  - OK: Clipboard tool found: win32yank

 Python 2 provider (optional)
  - INFO: Disabled (g:loaded_python_provider=0).

 Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "D:\Code\Languages\Python\Python38\python"
  - INFO: Executable: D:\Code\Languages\Python\Python38\python.EXE
  - INFO: Python version: 3.8.6
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.
 Python virtualenv
  - OK: no $VIRTUAL_ENV

 Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
  - INFO: Host: D:\Code\Languages\Ruby\Ruby27-x64\bin\neovim-ruby-host.bat
  - OK: Latest "neovim" gem is installed: 0.9.0

 Node.js provider (optional)
  - INFO: Node.js: v14.13.0
  - INFO: Nvim node.js host: D:\Code\NodeJS\node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.0

 Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

health#treesitter#check
========================================================================
Checking treesitter configuration
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for cmake: ABI version 13
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for c_sharp: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json5: ABI version 13
  - OK: Loaded parser for jsonc: ABI version 13
  - OK: Loaded parser for latex: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for php: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for vim: ABI version 13
  - OK: Loaded parser for vue: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for cmake: ABI version 13
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for c_sharp: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json5: ABI version 13
  - OK: Loaded parser for jsonc: ABI version 13
  - OK: Loaded parser for latex: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for php: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for vim: ABI version 13
  - OK: Loaded parser for vue: ABI version 13
  
## Telescope Configurations
`
local telescope = require'telescope'
local util = require'utils'

telescope.setup {
	defaults = {
		mappings = {
			i = {
				["<C-j>"] = "move_selection_next",
				["<C-k>"] = "move_selection_previous",
				["<C-n>"] = false,
				["<C-p>"] = false,
			},
			n = {

			},
		}
	},
	extensions = {
		fzf = {
			fuzzy = true,                    -- false will only do exact matching
			override_generic_sorter = false, -- override the generic sorter
			override_file_sorter = true,     -- override the file sorter
			case_mode = "smart_case",        -- or "ignore_case" or "respect_case"
		},
	},
  preview = {
    check_mime_type = false
  },
}
    -- To get fzf loaded and working with telescope, you need to call
    -- load_extension, somewhere after setup function:

-- require('telescope').load_extension('fzf')
require('telescope').load_extension('repo')
require('telescope').load_extension('dap')

local M = {

}
M.search_dotfiles = function()
  local system_name = util.getOS()
  if system_name == "Windows" then
    require("telescope.builtin").find_files({
      prompt_title = "< NVIM RC - DANTE >",
      cwd = "~/nvim"
    })
  elseif system_name == "Linux" then
    require("telescope.builtin").find_files({
      prompt_title = "< NVIM RC - DANTE >",
      cwd = "~/.config/nvim"
    })
  end
end

return M
`

**Comment by fdschmidt93** [comment]
Ideally, you can test-drive #1413 on Windows and give feedback whether that branch fixes the issues with an out-of-the-box telescope configuration, as I unfortunately have no Neovim Windows setup.

Thanks in advance :)

**Comment by JSchrtke** [comment]
I just gave this a try for 5 minutes, without the "disable mime type check" bandaid fix, no issues so far.
I'll stay on #1413 on my work machine until it is merged, I will let you know if I find any further issues.

**Comment by fdschmidt93** [comment]
It's virtually the same solution, just built into telescope :sweat_smile: Eyeing helix, I've come across https://github.com/sharkdp/content_inspector which maybe can be easily ported to luajit for plenary? Its approach looks super simple and then we'd have a pretty much pareto-efficient approach. Just a suggestion, if a Windows user wants to take a crack at it :)

**Comment by JSchrtke** [comment]
Hm, I've just started learning rust, don't really know lua all that well, nor what goes on in plenary. So you mean to implement the solution used in 'content_inspection' in a function/set of functions directly in plenary?
I mean, code is code after all, I might give it a shot this weekend and see what I can do.

**Comment by fdschmidt93** [comment]
> So you mean to implement the solution used in 'content_inspection' in a function/set of functions directly in plenary?

Exactly. The heuristic seems to be relatively simple and depends pretty much only on reading out the first 1024 bytes, but of course may or may not be easily ported to Lua.

https://github.com/sharkdp/content_inspector/blob/master/src/lib.rs explains in mere text how it works.

**Comment by Conni2461** [comment]
I think this was fixed by https://github.com/nvim-telescope/telescope.nvim/commit/2097f11305598bd88f799a76f5549da57f852a58 closing.

Feel free to reopen if i am wrong
