### ISSUE TITLE
live_grep  by passing cwd and file regex map

### ISSUE THREAD

**Issue by yueyingjuesha** [nvim-telescope/telescope.nvim#1266]
**Is your feature request related to a problem? Please describe.**
I am wondering if someone has the configuration example for passing a cwd/search directories and file name regex matching to live_grep so the live_grep can search under certain directories and file name

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fdschmidt93** [comment]
Uninitiated thought, I think https://github.com/nvim-telescope/telescope-live-grep-raw.nvim can do the job. Please close if that's the case.

**Comment by Conni2461** [comment]
I am not 100% understanding what is requested here. You should look into `live-grep-raw` and or read `:help telescope.builtin.live_grep`. Because you can do `:Telescope live_grep cwd=asdf glob_pattern=*.lua` or similar things
