### ISSUE TITLE
Error after updating plugin

### ISSUE THREAD

**Issue by abrausch** [nvim-telescope/telescope.nvim#1268]
### Description

After updating to the latest version I get the following error:

E5108: Error executing lua ...ig/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:307: attempt to call field 'create' (a nil value)

### Neovim version

NVIM v0.6.0-dev+313-g490e09c6d
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by abrausch@dante

Features: +acl +iconv +tui

### Operating system and version

macOS 11.4

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. Start vim
2. Type :Telescope

### Actual behavior

E5108: Error executing lua ...ig/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:307: attempt to call field 'create' (a nil value)
is shown

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
Dup of https://github.com/nvim-telescope/telescope.nvim/issues/1105

Make sure you have a up to date plenary version and only one plenary version in your rtp

**Comment by Conni2461** [comment]
CC @clason Maybe checkhealth can run `git log -1 --format=%h` in plenary directory and print that as version. Just an idea

**Comment by abrausch** [comment]
Thanks a lot. The link to #1105 helped.
