### ISSUE TITLE
Allow default / backup search_dirs

### ISSUE THREAD

**Issue by danjenson** [nvim-telescope/telescope.nvim#1276]
Is it possible to create a default `search_dirs` option? For instance, I would like all the current functionality to remain the same, i.e. starting the current directory or w/e, but after that, populate a file list from a custom directory, i.e. `/data`. In other words, I would like `/data` to always be searched after the current directory.

I could only get this to partially work with commands like `:Telescope find_files search_dirs=/data`, but then it seems to ignore the current directory, and `:Telescope find_files search_dirs=. /data` fails, and similarly when the directories are quotes, i.e. `:Telescope find_files search_dirs=". /data"`.

thanks!

**Comment by Conni2461** [comment]
`help telescope.command` explains how to do arrays with the `:Telescope` shorthand.

The lua version is `:lua require("telescope.builtin").find_files({ search_dirs = { ".", "/data" } })`

**Comment by danjenson** [comment]
Thank you! However, I am wondering if we could elevate that to a config-level option, as opposed to creating keybindings for each of these lua calls for every command I want to do this for in telescope. `fzf.vim` for instance allows you to specify the dirs

**Comment by siduck76** [comment]
> Thank you! However, I am wondering if we could elevate that to a config-level option, as opposed to creating keybindings for each of these lua calls for every command I want to do this for in telescope. `fzf.vim` for instance allows you to specify the dirs. It also seems like this method doesn't trigger packer to load the package, while `:Telescope` does:
> 
> ![image](https://user-images.githubusercontent.com/4793438/134401896-cd734eea-dcd8-4c20-8f25-ebdce9ddd4a8.png)

thats because we lazy loaded Telescope on (cmd = "Telescope") , so commands starting with "Telescope" will load telescope , i dont thing ":lua require.." work ._.

**Comment by danjenson** [comment]
I can't seem to get this to work with arrays, and the docs just say to use a vim array, which these are:

```
   map('n', '<C-f>', ':Telescope find_files search_dirs=[".", "/data/repos"] <CR>')
   map('n', '<C-s>', ':Telescope live_grep search_dirs=[".", "/data/repos"] <CR>')

```

**Comment by l-kershaw** [comment]
@danjenson The docs in `:h telescope.command` specify that you can't have spaces in any of the options. You have spaces in your option `search_dirs` (after the comma). This should work for you:
```
map('n', '<C-f>', ':Telescope find_files search_dirs=[".","/data/repos"] <CR>')
map('n', '<C-s>', ':Telescope live_grep search_dirs=[".","/data/repos"] <CR>')
```

---

Regarding adding an option for a default value for `search_dirs`, I'm not against an option being added, but it's not a high priority feature, so I don't think any of the core team will work on this. Since this is a relatively small feature to add, I'm labelling as "good first issue".
