### ISSUE TITLE
Cannot clear search text after Esc

### ISSUE THREAD

**Issue by igbanam** [nvim-telescope/telescope.nvim#1282]
### Description

When fuzzy-searching, if you switch to normal mode, and switch back, you cannot backspace away the text that was previously there before the mode-toggle.

### Neovim version

NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-97973-1wtbty6/neovim-0.5.0/build/config -I/tmp/neovim-20210702-97973-1wtbty6/neovim-0.5.0/src -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210702-97973-1wtbty6/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-97973-1wtbty6/neovim-0.5.0/build/include
Compiled by brew@HMBRW-A-001-M1-005.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.5.0/share/nvim"

### Operating system and version

macOS Big Sur

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. open any project
2. `:Telescope find_files`
3. Begin fuzzy searching for a file — assume your file is called `MyFile.java`, type `My`
4. Press `Esc` to switch back to normal mode in Telescope
    a. Press `i` to switch back to Insert mode and continue searching — cannot backspace to clear all text
    b. Use `ciw` to clear the text and re-search — cannot backspace to clear all text

### Expected behavior

I should be able to clear the text in the buffer when I reenter Insert mode. 

#### The former text cannot be `Backspace`d

The text in the buffer when you reach step 4 in the steps to reproduce remains in the buffer. Ideally, I should be able to delete these text with backspace, but I can't. The way I work around this is to get back into normal mode, and use a delete sequence.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
Upstream prompt buffers bug. See also #1251 #852 #829 #692 #567 #261

you can fix this by disabling prompt_prefix.

`Telescope find_files prompt_prefix=`

see also `:help telescope.defaults.prompt_prefix` it can also be disabled in `telescope.setup { }`

**Comment by tjdevries** [comment]
Let's close these as duplicates maybe?

**Comment by igbanam** [comment]
It's fine to close as a duplicate. The workaround works for me for now.

Thank you.

**Comment by igbanam** [comment]
Closing as duplicate
