### ISSUE TITLE
Add option to customize the character used in the background of the "buffer_previewer" in function "set_timeout_message"

### ISSUE THREAD

**Issue by saviocmc** [nvim-telescope/telescope.nvim#1288]
___First of all, thank you all very much for the great work, this plugin is awesome!___ 🔭🚀

**Is your feature request related to a problem? Please describe.**
The is no problem whatsoever. I just want more options for customization.

**Describe the solution you'd like**
I would like to have an option in the function ```require('telescope').setup()``` to customize the character used to make the pattern of the preview background when the function [```set_timeout_message```](https://github.com/nvim-telescope/telescope.nvim/blob/4816a27d7680feed293d21a945c476947af20d29/lua/telescope/previewers/buffer_previewer.lua#L59) is called. Currently the character is hardcoded as "/" [right here](https://github.com/nvim-telescope/telescope.nvim/blob/4816a27d7680feed293d21a945c476947af20d29/lua/telescope/previewers/buffer_previewer.lua#L67).

**Describe alternatives you've considered**
For now, I'm using my fork with a personal branch, where I hardcoded the character to a more pleasant one (in my opinion): "·".

**Additional context**
I'm only opening this here because I was not sure about what would be the best place to put such option in order to submit a PR.

___Again, thanks everyone for the great work on this plugin.___

**Comment by fdschmidt93** [comment]
I've addressed this in #1273, which would also supersede your PR to avoid conflicts and I've made slight changes to improve efficiency and allow to separately highlight the background.

Apologies, I should not have jumped the gub. I'm happy to merge your PR instead with the corresponding changes if you agree :)
