### ISSUE TITLE
Commit a97af306c4e9c9a6fa7c886c0ffe3079822c5203 breaks find_files and live_grep for me

### ISSUE THREAD

**Issue by VlkrS** [nvim-telescope/telescope.nvim#1292]
### Description

With any version after commit a97af306c4e9c9a6fa7c886c0ffe3079822c5203, find_files and live_grep yield only empty results.

### Neovim version

NVIM v0.5.0
Build type: Release
Lua 5.1

### Operating system and version

OpenBSD -current

### checkhealth telescope

```markdown
checkhealth was implemented in a later commit (I'm now running d6d28dbe324de9826a579155076873888169ba0f). 

I have rg and do *not* have fd installed.
```

### Steps to reproduce

With a97af306c4e9c9a6fa7c886c0ffe3079822c5203 or later

:Telescope find_files

or 

:Telescope live_grep

### Expected behavior

A list of files and a preview of the selected file

### Actual behavior

Both the file list and accordingly the preview are empty

### Minimal config

```Lua
lua << EOF
require('telescope').setup{
defaults = {
  }
}
EOF
```

**Comment by fdschmidt93** [comment]
https://github.com/nvim-telescope/telescope.nvim/issues/1174 might be the same issue?

**Comment by VlkrS** [comment]
Yes, #1174 is apparently the same issue. Sorry for opening a duplicate here ...

**Comment by fdschmidt93** [comment]
No worries :) closing as duplicate.
