### ISSUE TITLE
option for wrap file path 

### ISSUE THREAD

**Issue by grimgort** [nvim-telescope/telescope.nvim#1296]
Hello,
In general, it is not possible to display the absolute path of the files because they overflow the window. Is it possible to add an option to wrap the paths? 
![image](https://user-images.githubusercontent.com/44238325/135284984-418075aa-7cff-4f96-99ae-653498775f6f.png)

**Comment by tami5** [comment]
you can do that by `telescope.defaults {    path_display = { truncate = 2 } | "truncate" } `

**Comment by grimgort** [comment]
Ho yes, sorry. 
However I had tried to modify this variable to "truncate" but without success. I must have made a mistake... sorry for the inconvenience...

**Comment by Conni2461** [comment]
wrapping was just implemented in #1735
