### ISSUE TITLE
[question] how do i scroll inside the preview buffer using the telescope api

### ISSUE THREAD

**Issue by alexzanderr** [nvim-telescope/telescope.nvim#1324]
i know that there is a control + u or control + d to scroll the previewer, but i dont like this

and i found this
![image](https://user-images.githubusercontent.com/54772464/136660259-50f55c4d-e357-432b-8ebe-0ce4063c9021.png)

but how do i use this?

i've read all the documentation from `help telescope.nvim`, the entire 2777 lines of docs, but it doesnt tell me how to use that function.

i just want to make a mapping like this
```lua
        mappings = {
            i = {
				["<C-up>"] = -- scroll up using api,
				["<C-down>"] = -- scroll down using api
            }
        }
```

**Comment by alexzanderr** [comment]
and please, guys, make an `issue template for questions`. because there will be even more questions from me in the future about this topic (telescope) and i dont want to spam in the feature requests, nor asking on random websites.

**Comment by alexzanderr** [comment]
i asked there. now answer me!

**Comment by Conni2461** [comment]
Wow. pretty rude to demand a answer with "now answer me!".

Sorry to say this but no one is obligated to answer you. We do this as hobby, in our freetime and provide a free and open source software.

**Comment by alexzanderr** [comment]
> Because you asked so "nice". Here is how its done for the default mappings.
> 
> https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/mappings.lua#L25-L26
> 
> the rest is explained in `help telescope.defaults.mappings`

and, omg, it works. thanks a lot for support.

**Comment by arcin** [comment]
@alexzanderr 
> i asked there. *now answer me!*
> ...
> dude. i was joking around with the `now answer me!`; *calm down*, it wasnt *intended* to be rude.


1. You tell someone to answer you (in a rude way).
2. Then you claim it was a joke, and tell them to calm down (in a rude way). 

The way you ask for help and express gratitude makes it hard to want to help.

> dude. i was joking around with the `now answer me!`; calm down, it wasn't intended to be rude.
This sentence comes off as either gaslighting/invalidating. There was absolutely no way to know you were joking and it looks like you're just saying that after the fact. Which makes the initial offense worse.

> and, omg, it works. thanks a lot for support.
This sentence comes off a sarcastic/ungrateful.

Not sure if you're intentionally or unintentionally using abrasive language, but I just wanted to point it out in case you didn't know. Its something you can work on, if you want. How we communicate plays a huge role in the quality of our lives.

Emojis might be helpful 👍  (And to be clear, this post is just my attempt at being helpful 🤠)
