### ISSUE TITLE
[Mapping feature] results_scrolling_up and results_scrolling_down hooks

### ISSUE THREAD

**Issue by bluz71** [nvim-telescope/telescope.nvim#1326]
Hello Telescope crew,

Excellent work with regards to the recent merge of #1232 (results scrolling, up to 1,000). Many thanks for that.

With that foundation in place, I would like to be able to page up/down the results list quickly via custom mappings, similar to the existing `results_scrolling_up` and `results_scrolling_down` hooks listed in [mappings.lua](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/mappings.lua#L25). But for the results list.

I could not seem to find an existing request for this, hence this new issue (apologies if I am mistaken).

Currently, I only see `<Up>` and `<Down>` single line results scrolling. Like preview scrolling, ideally I would like half page result scrolling hooks.

Possible?
Or already available?

Cheers.

**Comment by mattleong** [comment]
I do know that `G` and `gg` were added as default mappings in one of the last commits. Maybe helpful for ya

**Comment by bluz71** [comment]
No, not helpful.

Up and down arrows already navigate the list ends. G and gg are not applicable to this feature request.

**Comment by bluz71** [comment]
Yes, that works perfect. Personally, I don't see any jump problems. I got it working just like my old fzf setup.

Note however, one also needs to do the following for the above to work:

```lua
local state = require('telescope.state')
local action_set = require "telescope.actions.set"
```

That solves the issue for me.
I do think other people will find this useful.

Would the Telescope powers-that-be see fit to abstract this into the existing mappings with a nicer API?

**Comment by bluz71** [comment]
Thank you, the new API works great.
