### ISSUE TITLE
builtin.lsp_code_actions handler not working in development neovim

### ISSUE THREAD

**Issue by klausweiss** [nvim-telescope/telescope.nvim#1332]
### Description

For a few days now telescope LSP handler doesn't work for `textDocument/codeAction` in the latest development version of neovim.
I'm using neovim nightly on Fedora from this repository https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/ (as advised on neovim wiki https://github.com/neovim/neovim/wiki/Installing-Neovim#fedora).
I've tested this against multiple versions and tracked down the breaking change happened after this (daily) merge: https://github.com/agriffis/neovim/commit/b4bb7340a2bcf9bb80fd7533d7890f64110fa773
The following squashed PR was included and is related, so I suspect it's the reason behind the failure: https://github.com/neovim/neovim/pull/15818/files

By _doesn't work_ I simply mean telescope doesn't show and the default handler is used instead, see below:
![image](https://user-images.githubusercontent.com/11031002/136823480-9a6232e9-acaa-41c1-9fe9-51812888ab86.png)

Tested against purescript-language-server, hls and elmls.

### Neovim version

NVIM v0.6.0-dev+449-gf4359b5db
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Fedora 34

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. Get a recent neovim build (make sure it's not earlier than this commit: https://github.com/neovim/neovim/pull/15818/files#diff-fb2b7119cd068ae643697e57d3dc10e758737dc763b97b91e5c17736f17b8da8R2402)
2. Configure neovim to handle codeActions with telescope
3. Try invoking codeActions

For example with elm and provided `minimal.lua`:
1. Install elm https://guide.elm-lang.org/install/elm.html
2. Install elm-language-server https://github.com/elm-tooling/elm-language-server
3. Create an elm project
 a. `mkdir /tmp/neovim-lsp-telescope-codeaction-bug`
 b. `cd /tmp/neovim-lsp-telescope-codeaction-bug && elm init`
 c. proceed with the defaults
4. Launch neovim with the minimal config provided:
  `nvim -u minimal.lua /tmp/neovim-lsp-telescope-codeaction-bug/src/Main.elm`
5. In `Main.elm` place some code which should cause some actions to be available, e.g.:
 ```elm
 main = 123
 ```
6. Start the lsp server:
 `:LspStart`
7. Trigger the code actions handler
 `:lua vim.lsp.buf.code_action()`

### Expected behavior

Telescope to be shown, like on the screenshot from an older development neovim version:
```
NVIM v0.6.0-dev+344-gb3b02eb52
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
![image](https://user-images.githubusercontent.com/11031002/136830231-de860d09-b170-4f72-8d2d-a6ceb87944f4.png)

### Actual behavior

Telescope not shown
![image](https://user-images.githubusercontent.com/11031002/136830398-84b2006e-8778-4da9-90ee-646fc0323b1d.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
			'neovim/nvim-lspconfig',
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
	
	require'lspconfig'.elmls.setup{}
  
  local telescope_builtin = require'telescope.builtin'
  vim.lsp.handlers['textDocument/codeAction'] = telescope_builtin.lsp_code_actions
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
Was `builtin.lsp_code_actions` ever meant to override the LSP handler? Just glancing at the function signature of the original handler and [telescope's implementation](https://github.com/nvim-telescope/telescope.nvim/blob/3f45d64e9c47ad9eef273ddab65790a84cced30b/lua/telescope/builtin/lsp.lua#L149-L328) I actually think it just worked, because telescope was called correctly unintentionally. AFAIK, `:Telescope lsp_code_actions` or `:lua require "telescope.builtin".lsp_code_actions()` always were the intended usage.

In any case, the [Neovim commit](https://github.com/neovim/neovim/pull/15818/files#diff-fb2b7119cd068ae643697e57d3dc10e758737dc763b97b91e5c17736f17b8da8R2402) you are referencing removes the handler you are setting, so your minimal init lua just doesn't have an effect.

Does simply `:Telescope lsp_code_actions` work for you as expected? Sumneko is the one LSP where I could (but don't) use code actions and there it seems to work for me as expected.
