### ISSUE TITLE
allow delete/rename in file_browser picker

### ISSUE THREAD

**Issue by willt** [nvim-telescope/telescope.nvim#1337]
Would be nice if file_browser supported delete/rename for files/dirs.

**Comment by fdschmidt93** [comment]
Update: As a beacon of hope https://github.com/nvim-lua/plenary.nvim/pull/241 now only needs to undergo (most likely) Conni's review. Then I can clean up #1257 which should hopefully be more straightforward given that the branch is rather advanced.

**Comment by fdschmidt93** [comment]
Closing as https://github.com/nvim-telescope/telescope-file-browser.nvim was now released as an extension. (Please consider it beta though for the time being.)
