### ISSUE TITLE
git_files with fallback to find_files when not in git repo picker

### ISSUE THREAD

**Issue by marekdedic** [nvim-telescope/telescope.nvim#1338]
**Is your feature request related to a problem? Please describe.**
Hi, I would like to use git_files for most of my work. However, I am not always running vim inside a git repo

**Describe the solution you'd like**
I'd like to see a picker that behaves like `git_files` when I'm inside a git repo and like `find_files` otherwise

**Comment by fdschmidt93** [comment]
I don't see what a dedicated picker would over the recipe apart from technical debt. _Maybe_ telescope build in a fallback option into `builtin.git_files` but that's a kind of precedent I'd want to avoid. 

What would a dedicated picker really offer here?

**Comment by fdschmidt93** [comment]
I agree that customization is something we should further try to improve. However, I'd close this for the time being for tidyness as `wontfix` as I'm presuming any core member would make a PR for that. Any team member would be free to reopen this though :)

You'd be welcome to make a PR to include this in `builtin.git_files` here:

https://github.com/nvim-telescope/telescope.nvim/blob/b5c63c6329cff8dd8e23047eecd1f581379f1587/lua/telescope/builtin/git.lua#L16-L43

Then we can revisit as to whether to include such a fallback. I'd be OK with as I guess it wouldn't increase the maintenance burden.
