### ISSUE TITLE
Add an option to path_display to use devicon colors for filenames and paths in results

### ISSUE THREAD

**Issue by TC72** [nvim-telescope/telescope.nvim#1343]
It'd be nice to have the option to have paths and filenames colored in the same way as color_devicons.
This could be another option in path_display along with the choice of using it for the full path or just the filename.

I do something similar in my tab extension, this shows the section of the path below the current working directory being colored:

![CleanShot 2021-10-14 at 12 27 29](https://user-images.githubusercontent.com/402357/137310079-58c0429b-814e-4873-84a7-f3cd12e7a927.png)

**Comment by l-kershaw** [comment]
I don't think that this adds much value to Telescope compared to the added complexity that it would cause.
Currently the `path_display` handling in `utils.transform_path` simply returns the transformed path as a string, whereas this feature would require returning a string and a list of highlights.
This would then have to be handled anywhere that paths are displayed, which adds a lot of complexity to the codebase.

Unless someone comes up with a way of handling this with very little added code complexity, this doesn't seem worth it to add.
I am closing this for the moment as a `wontfix`.

**Comment by TC72** [comment]
Hey @l-kershaw thanks for having a look at this.

I'm coming at this from a different direction. I've been working on code to handle the highlighting we get back from tools like ripgrep which show us matches. The issue I had while writing that code was adding highlights based on a string including a full length path and then having path_display shorten that path. i then have to run through all the highlights and adjust them based on where they are and how much the path has been shortened by.

It would be great if there was a system that did attach the highlights to individual parts of the display string which could then take care of these changes themselves.

Then at the very end you'd combine the strings with their highlights. For things like shortening paths you have to understand which block of text is a path anyway.

I'm not pushing for this, it'd be nice to have but I think changes which could allow this would help in adding colors we get from other tools. Definitely not a little change to achieve this.
