### ISSUE TITLE
Fuzzy Find / Search in all open buffers

### ISSUE THREAD

**Issue by zoomido** [nvim-telescope/telescope.nvim#1357]
**What I am missing:**
In https://github.com/junegunn/fzf.vim there is a command:
`:Lines [QUERY] 	Lines in loaded buffers`
This is a fuzzy finder for all lines in all open buffers.

**Solution**
A similar alternative in telescope.

**Describe alternatives you've considered**
Currently I'm doing `:bufdo vimgrepadd pattern %` to populate the quickfix list with a pattern. Unfortunately this is not a fuzzy search.

**Comment by ssh352** [comment]
> Well after some testing is seems that this is indeed the same as live_grep and not a fuzzy search.
> Is there a way to have the same functionality as `current buffer fuzzy find` but for all open buffers?

I have same question.

**Comment by Conni2461** [comment]
Can someone test  this PR https://github.com/nvim-telescope/telescope.nvim/pull/2039

For fuzzy find for word under cursor for all open files `:Telescope grep_string grep_open_files=true` 
Or fuzzy find over all open files `:Telescope grep_string grep_open_files=true search=`
