### ISSUE TITLE
Integrate with vista

### ISSUE THREAD

**Issue by tjdevries** [nvim-telescope/telescope.nvim#138]
We could probably integrate w/ https://github.com/liuchengxu/vista.vim which would be cool.

**Comment by sunjon** [comment]
Couldn't the Tree-sitter finder be improved to obtain similar results?

At the moment the TS results aren't as accurate as Vista's; Functions get misidentified as vars and similar, but I think that's down to the finder itself not taking into account different permutations of function/function_definition, etc. Other than that, TS identifies more objects in my tests (see screenshot).

![vista](https://raw.githubusercontent.com/sunjon/images/master/vista_vs_ts.png)
Group labels are a;ready on the TS finder, a sorter could be made to sort by object_type -> alphanumeric.

I'm not sure how represnting nested objects would work with the finder.

**Comment by tami5** [comment]
Added to wishlist
