### ISSUE TITLE
E5108: Error executing lua ...fig/nvim/plugged/plenary.nvim/lua/plenary/popup/init.lua:240: Invalid key 'zindex'

### ISSUE THREAD

**Issue by MarcelRobitaille** [nvim-telescope/telescope.nvim#1394]
### Description

I just installed telescope and I am getting this error when I do `<leader>f` after setting up this mapping:
```vim
nnoremap <leader>f <cmd>Telescope find_files<cr>
```

I installed plenary and telescope with plug and ran `:PlugUpdate`, so both are up to date

### Neovim version

NVIM v0.5.0-dev+1262-g63b64ebab
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/marcel/.cache/yay/neovim-git/src/build/config -I/home/marcel/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/marcel/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/marcel/.cache/yay/neovim-git/src/build/include
Compiled by marcel@Zeus

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

Arch Linux

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. Install the package
1. Setup this mapping:
    ```vim
    nnoremap <leader>f <cmd>Telescope find_files<cr>
    ```
1. Press `<leader>f`

### Expected behavior

List of files and fuzzy search

### Actual behavior

The message `E5108: Error executing lua ...fig/nvim/plugged/plenary.nvim/lua/plenary/popup/init.lua:240: Invalid key 'zindex'`.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
-- This minimal config is giving its own error: [packer.nvim] [ERROR 15:01:23] async.lua:20: Error in coroutine: /tmp/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:710: Vim:E492: Not an editor command: -- Automatically generated packer.nvim plu
gin loader code
```

**Comment by Conni2461** [comment]
Your neovim version is pre 0.5.0 release. Its from 04/17/2021. The release was in july. We dont support this and i dont even think i will make the minimum requirement to 0.5.1 or newer (because there is a segfault in 0.5.0)

**Comment by MarcelRobitaille** [comment]
My bad. I switched from `neovim` to `neovim-git` a while back to test something and forgot to switch back. Thank you @Conni2461
