### ISSUE TITLE
ANSI escape codes in git_bcommits

### ISSUE THREAD

**Issue by YanikCeulemans** [nvim-telescope/telescope.nvim#1397]
### Description

I switched my workflow yesterday to the following setup:
* Alacritty 0.9.0 (came from iTerm2, but I have the same problem in iTerm2)
* tmux 3.2a
* `echo $TERM` in alacritty: `alacritty-direct`
* `echo $TERM` in tmux: `tmux-256color`
* Telescope, installed yesterday 2021-10-31, last commit: `d7f09f5`

Whenever I open Telescope for git_bcommits of git_status, Telescope shows the ANSI escape codes used to color text instead of actually colouring the text. This is most likely a problem with my configuration considering I've searched for this issue with very few results. I also have the same issue when using the `neogit` plugin showing the git status.

The unmodified minimal.lua file is enough to reproduce the issue.

### Neovim version

NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/build/config -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/build/include
Compiled by brew@BigSur

### Operating system and version

macOS 11.6

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. navigate to a git directory
2. run `nvim -nu minimal.lua`
3. open a file with some git history
4. run `:lua require'telescope.builtin'.git_bcommits()`

### Expected behavior

The picker list to select commits does not contain ANSI escape codes and the diff preview shows the diff for the currently selected commit.

### Actual behavior

The picker list to select commits shows ANSI escape codes and the diff preview window is empty. When scrolling through the picker list, the diff preview window remains empty.

![image](https://user-images.githubusercontent.com/4895411/139577457-5913494d-ada4-4292-97df-b3e9d3723ce3.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
What does your gitconfig says about colors?

You should set it to `auto` not to `always`. We dont have ansi colors implemented yet. Neither do we interpret them nor do we remove them

**Comment by YanikCeulemans** [comment]
Thank you for your fast response. My `.gitconfig` contained the following entries for [color]:
```
[color]
	ui = always
[color "diff-highlight"]
	oldNormal = red bold
	oldHighlight = red bold 52
	newNormal = green bold
	newHighlight = green bold 22
```
I have deleted those entries and it is now working as intended.

Thank you very much for your help.
