### ISSUE TITLE
ignore pattern: `".git"` ignores all names with `git` substring with one exception.

### ISSUE THREAD

**Issue by molleweide** [nvim-telescope/telescope.nvim#1402]
### Description

With the ignore pattern ".git" in telescope config it seems that telescope ignores all dir and file names containing
a substring = `git` UNLESS the file/dir is located in the same path where I initiated nvim.

### Neovim version

- **OS**: Darwin
- **Neovim version**: 0.6.0 (dev)
- **Doom Nvim information**:
- **version**: 3.2.0-beta2
- **`doom_root` variable**: `/Users/hjalmarjakobsson/.config/doom-nvim`
- **`doom_configs_root` variable**: `/Users/hjalmarjakobsson/.config/doom-nvim`

### Operating system and version

macOS 10.15.7

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `cheat`
  - INFO: No healthcheck provided

## Telescope Extension: `mapper`
  - INFO: No healthcheck provided

## Telescope Extension: `project`
  - INFO: No healthcheck provided

## Telescope Extension: `repo`
  - INFO: No healthcheck provided

## Telescope Extension: `z`
  - INFO: No healthcheck provided
```

### Steps to reproduce

Start vim in a dir and create files and dirs containing substring `git`.

Only if a file starts with string `git` and is located in the same path where you started nvim it shows up in results for me.
And similar with dirs. I don't know if this pattern is the whole problem but this
what I have been able to deduce until now.

`git` and `gitrooooot` will show but not `fooogit` shows for me.

### Expected behavior

I expect strings like "git" that aren't preceded by a period to show up in results.

### Actual behavior

Only names in same path as where I started vim show

### Minimal config

```Lua
I don't know how to do this step yet, BUT I am using `doom-nvim`.
I have to learn more about nvim configs so that I can do this step.
```

**Comment by fdschmidt93** [comment]
Without any research, IIRC you should ignore `%.git` rather than `.git`. Let me know whether that works for you.

**Comment by molleweide** [comment]
I believe that did the trick! Thank you very much!
