### ISSUE TITLE
Opening files with Telescope are messing up buffer IDs

### ISSUE THREAD

**Issue by rod-stuchi** [nvim-telescope/telescope.nvim#1414]
### Description

Files opened with Telescope are get buffer ID not sequential, high numbers, I think this is related with buffer preview.

![image](https://user-images.githubusercontent.com/19471811/140246100-5d3a9e17-3afc-4cbc-a9b3-f4ee904642f8.png)

![image](https://user-images.githubusercontent.com/19471811/140246628-a2087fb2-eac9-4945-8e69-975453ebab29.png)

### Neovim version

```
NVIM v0.6.0-dev+550-g29cec32f4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch 5.14.15-arch1-1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. Open some with `:edit` or `nvim-tree`, check the buffer ids
2. Open more files (but before, you should do some navigation on the file list (ctrl+p, ctrl+n), then open a file
3. Check buffers ID with `:ls` 

### Expected behavior

Keep the buffers IDs sequential, to facilitate navigability `:b1, b2, b3, ...` etc

### Actual behavior

https://user-images.githubusercontent.com/19471811/140247703-3f609e23-2876-423d-ad38-acd2968e0841.mp4

**Comment by Conni2461** [comment]
Basically not fixable.

Telescope opens a bunch of floating windows (with new buffers). 1 buffer for prompt, 1 for results and x for previewers. You can cut it down by disabling previewers: `:Telescope find_files previewer=false`.

If you dont like that we are opening buffers you should look for an alternative. `fzf.vim` isnt that bad with buffers. I think it only opens 1 at the time.
