### ISSUE TITLE
Faster way to select file from filelist

### ISSUE THREAD

**Issue by Nico-Guyon** [nvim-telescope/telescope.nvim#1417]
Is there a way to add a faster way of selecting files than using up / down to navigate ?

For example if I type maybe 4 letters of the file I'm searching and the remaining selection is 40 possible items, the file I want is just in the 3/4 of the list.
I can either type 5 more letters to narrow down the possible candidate or move down 10 times to select the actual file.

Since I'm seeing the file I want inside the list, it could be great to select it directly by using numbers for example or labels like plugins such as easymotion and hop do.

Is there a way to fast select an item on the file list without having to type more letters or to use up / down selection keys ?

I know I could go to normal mode and then use numbers + movement keys like inside vim which would be <ESC>30k in my example but it still account for 4 keystroke and since the line numbers are not displayed I can't be sure if it's 30k or not 29k or 31k.

I use hop intensively in my workflow so I'm used to jumping around with minimal keystroke, it would be so great to have the same ability in telescope.

(By the way thanks for this great plugin and all your hard work, like hop it really improved my workflow a lot !)

**Comment by l-kershaw** [comment]
There was a discussion of a "hop-like" movement in #965, which resulted in [telescope-hop.nvim](https://github.com/nvim-telescope/telescope-hop.nvim). I don't use it, so not really sure how it works, but I'm guessing that this is the sort of thing that you are looking for?

**Comment by fdschmidt93** [comment]
An extension I wrote some time ago to play around with the extmark API does just that.

https://github.com/nvim-telescope/telescope-hop.nvim

Closing this as we won't be having this in telescope.

**Comment by Nico-Guyon** [comment]
That's exactly what I was looking for !
Many thanks !

**Comment by matu3ba** [comment]
@fdschmidt93 I was so free to add it to the wiki [here](https://github.com/nvim-telescope/telescope.nvim/wiki/Extensions#different-plugins-with-telescope-integration). I hope the description is sufficiently accurate and short.

**Comment by fdschmidt93** [comment]
It's great, thanks a lot :) I should have added it earlier
