### ISSUE TITLE
Telescope crashes nvim after commit 3b9ac8e

### ISSUE THREAD

**Issue by PanagiotisS** [nvim-telescope/telescope.nvim#1420]
### Description

Teleport is crashing nvim as described below.

As seen from the minimal config the commit that causes the crash is https://github.com/nvim-telescope/telescope.nvim/commit/3b9ac8edba8c1b4053c7f6ac8a4e78969cec66dd

If I use the latest commit https://github.com/nvim-telescope/telescope.nvim/commit/97842abb038798ee51dd1f6bceb2f928f04a4c31 and revert that commit then Telescope is working without problems

File: `lua/telescope/pickers/highlights.lua`

```lua
 74   a.nvim_buf_add_highlight(results_bufnr, ns_telescope_selection, "TelescopeSelection", row, #caret, -1)
 75   -- a.nvim_buf_set_extmark(
 76   --   results_bufnr,
 77   --   ns_telescope_selection,
 78   --   row,
 79   --   #caret,
 80   --   { end_line = row + 1, hl_eol = conf.hl_result_eol, hl_group = "TelescopeSelection" }
 81   -- )
```

EDIT: I just noticed the commit message. It also works if I set `hl_result_eol` to false,

```lua
lua << EOF
require("telescope").setup{
    defaults = {
        hl_result_eol = false,
    },
}
EOF
```

### Neovim version

:version
NVIM v0.6.0-dev+3-gd791274a9
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-786

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
Press ENTER or type command to continue

### Operating system and version

Windows 10, Build: 19042.1288

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. Open nvim
2. Open telescope and try to run a command. For example `:Telescope find_files` 
3. Type a string, select a file, type Enter
4. Crash (see screenshot)

This happens always with `find_files`, most of the times with `live_grep`. Did not try more as I though it was enough.

It will also crash most of the times if I press `ctrl-c`

1. Open nvim
2. :Telescope find_files
3. Type a string
4. Press `ctrl-c`
5. Crash

### Expected behavior

To work.

### Actual behavior

Crashes

![image](https://user-images.githubusercontent.com/11048776/140523234-bd7369b8-01d3-4bd4-bffc-c23b0ba79a91.png)

### Minimal config

" With `x` are the commits which are not working.
" With `v` are the commits that work.

```vim
set encoding=utf-8
scriptencoding utf-8

let &runtimepath .= ',' . expand(stdpath('data') . '/dein/repos/github.com/Shougo/dein.vim/')
let s:path = expand(stdpath('data') . '/dein')

if dein#load_state(s:path)

    call dein#begin(s:path, [expand('<sfile>')])

    call dein#add('Shougo\dein.vim')

    call dein#add('nvim-lua/plenary.nvim') " {'rev': 96e821e}
    call dein#add('nvim-telescope/telescope.nvim') " {'rev': 97842a}       x : fix: revert buffers previewer (#1400) 
    " call dein#add('nvim-telescope/telescope.nvim', {'rev': '6a8fbb4'}) " x : breaking: bump nvim version requirement to 0.5.1 (#1406) 
    " call dein#add('nvim-telescope/telescope.nvim', {'rev': '587a10d'}) " x : chore: remove a lot of deprecated stuff (#1399) 
    " call dein#add('nvim-telescope/telescope.nvim', {'rev': 'c08f958'}) " x : fix: check if caret is present before removal (#1390) 
    " call dein#add('nvim-telescope/telescope.nvim', {'rev': '3b9ac8'})  " x : break: changed the results window highlight to always be full width (#1312)
    " call dein#add('nvim-telescope/telescope.nvim', {'rev': '02a02f7'}) " v : fix: set preview titlehighlight when re-enabling preview (#1384) 
    " call dein#add('nvim-telescope/telescope.nvim', {'rev': 'f31ef36'}) " v : fix: opts.git_command for files, commits, bcommits (#1374) 
    " call dein#add('nvim-telescope/telescope.nvim', {'rev': 'f562227'}) " v : fix: always remove previous caret when change selection (#1364)


    call dein#end()
    call dein#save_state()
endif
" }}}
filetype plugin indent on
syntax enable

set number

nnoremap <silent><leader>gr <cmd>lua require'telescope.builtin'.live_grep{}<cr>
nnoremap <silent><leader>r <cmd>lua require'telescope.builtin'.find_files{}<cr>
```

**Comment by PanagiotisS** [comment]
After downloading the latest Neovim version https://github.com/neovim/neovim/commit/3ba800f1538e083f8172655c6bab096cd604a0b5 and testing again it is running without problems.

```
:version
NVIM v0.6.0-dev+558-g3ba800f15
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-482

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
Press ENTER or type command to continue
```

Therefore, since Telescope commit https://github.com/nvim-telescope/telescope.nvim/commit/3b9ac8edba8c1b4053c7f6ac8a4e78969cec66dd we need either nvim 0.5.1 or nvim 0.6 after a specific commit.

**Comment by Conni2461** [comment]
We bumped telescope to 0.5.1: https://github.com/nvim-telescope/telescope.nvim/commit/6a8fbb53e01f9c523a68fb1eb06a346e43db720d

and the readme states 0.5.1 or newer: https://github.com/nvim-telescope/telescope.nvim#getting-started

everything else isnt supported

**Comment by PanagiotisS** [comment]
Indeed. But readme states 0.5.1 or newer and therefore one assumes 0.6 > 0.5.1.  Which apparently is not the case here.
So specifying in the readme which commit is needed for 0.6 would be very helpful and easy to do :)

**Comment by Conni2461** [comment]
you cant assume that. 0.6 is a dev version. And the version you ran is literally the 3 commit after the 0.5.0 release from back in July.

I changed it, its now 0.5.1 or the LATEST nightly commit. You shouldnt run any nightly commit that is older than a couple of days. Or just run the official release.

Its unreasonable to support all 558 commits since the last neovim minor release.

Also its unreasonable for us to say you need min commit sha xyz because the commit after that could just introduce a regression to some feature. And we need to bump the sha again ?!?!?

**Comment by PanagiotisS** [comment]
Well, specifying latest commit it is very useful indeed! At least I know to check that. I do not know how neovim dev runs with numbering and stuff, but if I see latest commit I will now that I might have an old nvim version. And tbh I do not know how old the dev commit I run is. I just run whatever choco installs. From my point of view a commit from July is fairly new! Anyway, thank you and sorry to have bothered you!

Cheers
