### ISSUE TITLE
segmentation fault when using `find_files`

### ISSUE THREAD

**Issue by ZwodahS** [nvim-telescope/telescope.nvim#1424]
### Description

Encounter a segfault when I am using the `find_files`

Command in question
`Telescope find_files previewer=false theme=get_dropdown`

Did a bisect and manage to find the commit that caused the error
`6652d4d55571db0ebd6cb636c523cb8a87785c27`

Am using vim-plug, so I attached a minimal config that isn't working. If needed, I can set up a minimum config using the template provided.

### Neovim version

NVIM v0.6.0-dev+43-g02bf251bb
Build type: Debug
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 11.6

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities
```

### Steps to reproduce

press <C-P> to open the search or run `:Telescope find_files previewer=false theme=get_dropdown` to search. 
Select any file and press enter and seg fault occurs.

### Actual behavior

`Segmentation fault: 11`

### Minimal config

```Lua
call plug#begin('~/.vim/installed_plugins")
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()
lua << EOF
require("telescope").setup {
  defaults = {
    hl_result_eol = true,
  },
  pickers = {
    buffers = {
        sort_lastused = true,
        theme = "cursor",
        previewer = false,
        mappings = {
            i = {
                ["<C-d>"] = require("telescope.actions").delete_buffer,
            },
            n = {
                ["d"] = require("telescope.actions").delete_buffer,
            }
        }
    },
    find_files = {
        sorting_strategy = "descending",
        follow = true
    },
    file_browser = {
        sorting_strategy = "descending",
    },
    live_grep = {
        sorting_strategy = "descending",
    }
  },
}
EOF
nnoremap <C-P> <cmd>Telescope find_files previewer=false theme=get_dropdown<CR>
```

**Comment by Conni2461** [comment]
Dup of https://github.com/nvim-telescope/telescope.nvim/issues/1391

We bumped the minimum required version and your neovim is no longer supported. Either LATEST (within last week) nightly build (which yours isnt, its too old) or 0.5.1

**Comment by typesAreSpaces** [comment]
I might be confused, but @ZwodahS is using 0.6 and he is still getting that issue. I'm in the same situation. At this point, I'm thinking maybe I'm not using the correct version?

**Comment by l-kershaw** [comment]
It depends on how old a version of 0.6 you are using, the version code in the original issue denotes an old nightly version of 0.6 (from relatively soon after 0.5 was released), and was not the latest version at the time the issue was raised.

@typesAreSpaces are you using the release version of 0.6, or the latest nightly version of 0.7? If yes, and you are still getting this issue, then we can reopen this issue.

**Comment by typesAreSpaces** [comment]
@l-kershaw Thanks for your quick reply! Yes, I think I had an old 0.6 installed. I uninstalled/installed nvim again and it's working just fine. Thanks for your help!
