### ISSUE TITLE
Check output of `fd -V` to make sure it's fdfind not fdclone (debian/ubuntu's /usr/bin/fd)?

### ISSUE THREAD

**Issue by erwin** [nvim-telescope/telescope.nvim#1425]
### Description

Just a minor issue to bring to your attention...

Each time I tried to run `checkhealth telescope` I would get a strange UI and nvim would become unresponsive. I created a minimal nvim config, and the problem persisted.

Turns out there is a package on Ubuntu called `FDclone` (File & Directory Tool) by T.Shirai that I had installed...

It could be useful to check the output of `/usr/bin/fd` (or whichever `fd` is in the path) to make sure it's the fd-find that works work telescope (sharkdp/fd), and not the `fdclone` that's a package in Ubuntu/Debian.

 
![image](https://user-images.githubusercontent.com/11534217/140641746-cb5005f1-967e-4166-9700-4cd31fb449e0.png)

![image](https://user-images.githubusercontent.com/11534217/140641758-2f15c41a-c0b9-4341-97fc-e7e3d4ee19a7.png)

In my case, I hadn't used `fdclone` or `sharkdp/fd` before, so when I kept getting this erroneous window while trying to use `:checkhealth telescope` (and during other telescope operations) it was very confusing.

### Neovim version

```
~/Reinstall  v --version
NVIM v0.6.0-dev+498-gd0f10a7ad
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az139-646

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Kubuntu 21.10 x86_64

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. `apt install fdclone`
2. open nvim
3. `:checkhealth telescope`

### Expected behavior

Expected the `:checkhealth telescope` to give normal output

### Actual behavior

nvim locks up, replaced by fdclone running, which user may not have directly installed and thus not recognize - could have been installed as a dependency 

### Minimal config

```Lua
" auto-install vim-plug
if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.config/nvim/autoload/plugged')

"=====[ install plugins ]=======================================================
call plug#begin()
Plug 'kyazdani42/nvim-web-devicons' " for icons in telescope
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}  
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
" c extension for telescope for faster FZF
"Plug 'nvim-telescope/telescope-fzf-native.nvim', { 'do': 'make' }
call plug#end()

"=====[ Conditional Configuration ]=============================================
if exists('$COLORTERM') && $COLORTERM == 'truecolor'
	set termguicolors
endif
if $TERM == 'xterm-kitty'
	let &t_ut=''
endif
```

**Comment by Conni2461** [comment]
We already check for `fdfind` but maybe in the wrong order.

Can you try switch the order here: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/health.lua#L28

If it works. PR welcome :)
