### ISSUE TITLE
`Telescope.file_browser` does not honour the `cwd = require("telescope.utils").buffer_dir()` 

### ISSUE THREAD

**Issue by horta** [nvim-telescope/telescope.nvim#1440]
### Description

`Telescope.file_browser` does not honour the `cwd = require("telescope.utils").buffer_dir()` configuration. It works at the first time when opening the file/buffer from terminal and then ignore whatever buffer's location you are working on.

A solution perhaps would be a callback: `cwd = require("telescope.utils").buffer_dir`?

### Neovim version

NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/build/config -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/src -I/opt/homebrew/include -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20211103-7276-u4ywwo/neovim-0.5.1/build/include
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.5.1_1/share/nvim"

Run :checkhealth for more info

### Operating system and version

macOS 12.0.1

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 
 
## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1
 
## ===== Installed extensions =====
 
## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. `touch file0`
2. `mkdir dir`
3. `touch dir/file1`
4. `touch dir/file2`
5. `nvim -nu minimal.lua file0`
6. `:Telescope file_browser`
7. It correctly lists the directory pertaining to `file0`.
8. Open `dir/file1` (via file_browser)
9. `:Telescope file_browser`
10. It **INCORRECTLY** lists the directory pertaining to `file0`, instead of the one belonging to `dir/file1`.

### Expected behavior

To honour the `cwd = require("telescope.utils").buffer_dir()` configuration.

### Actual behavior

It will open the initial buffer_dir() from `file0`, instead of the current buffer's folder.

https://asciinema.org/a/1TiGHzCxydN1ia38iBJP8I9gG

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"nvim-telescope/telescope.nvim",
				requires = {
					"nvim-lua/plenary.nvim",
					{ "nvim-telescope/telescope-fzf-native.nvim", run = "make" },
				},
			},
			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
_G.load_config = function()
	require("telescope").setup({
		pickers = {
			file_browser = require("telescope.themes").get_dropdown({
				cwd = require("telescope.utils").buffer_dir(),
				previewer = false,
			}),
		},
	})
	require("telescope").load_extension("fzf")
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing Telescope and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

**Comment by fdschmidt93** [comment]
Recapping to avoid ambiguity, your minimal init lua cannot work, since the `require "telescope.utils".buffer_dir()` is only evaluated once during startup. Hence, you'd want the `builtin.file_browser` to evaluate `cwd` as a `function`.

Why not:
```lua
require "telescope.builtin".file_browser { cwd = vim.fn.expand("%:p:h") }
```

which seems to be working for me as intended? Admittedly, I haven't gotten it to work in vimscript as `:Telescope file_browser cwd=expand("%:p:h")` does not seem to work because `expand` is not evaluated properly, though I'm sure that's possible somehow.

While I'd agree that `opts.cwd` ideally always can be either a `function` to be evaluated or a `string` to the `cwd` and defaulting `vim.loop.cwd` otherwise, the main problem would be that we'd have to change all `opts.cwd` of existing pickers. I guess if another member agrees, I'd be happy to review a PR.

**Comment by horta** [comment]
Changing `cwd = require("telescope.utils").buffer_dir(),` to `cwd = vim.fn.expand("%:p:h")` does not change its behaviour.

**Comment by horta** [comment]
Just to make it more clear, using the following `minimal.lua`

```
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"nvim-telescope/telescope.nvim",
				requires = {
					"nvim-lua/plenary.nvim",
					{ "nvim-telescope/telescope-fzf-native.nvim", run = "make" },
				},
			},
			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
_G.load_config = function()
	require("telescope").setup({
		pickers = {
			file_browser = {
				cwd = vim.fn.expand("%:p:h"),
			},
		},
	})
	require("telescope").load_extension("fzf")
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing Telescope and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

still present the same problem.

**Comment by fdschmidt93** [comment]
`require "telescope.builtin".file_browser { cwd = vim.fn.expand("%:p:h") }` is supposed to be the mapping you bind the file browser to as opposed to having this in your `telescope.setup`, because as mentioned above, otherwise `cwd` in setup essentially defaults to your working directory as it is evaluated at neovim startup.

**Comment by horta** [comment]
I guess I figured it out then. Just use `cwd = "%:p:h"`. I will PR a documentation change on that.

**Comment by fdschmidt93** [comment]
Ah yeah, I now see that the `builtin.files` function actually expand on the passed `opts.cwd`. I wasn't aware of that myself. Good catch :)

**Comment by fdschmidt93** [comment]
With regards to the file browser, I'll incorporate the document change into the soon-to-be released extension (see https://github.com/nvim-telescope/telescope.nvim/pull/1453).

**Comment by Conni2461** [comment]
file_browser is no longer part of telescope
