### ISSUE TITLE
Possibility of adding versioning to the project

### ISSUE THREAD

**Issue by thornycrackers** [nvim-telescope/telescope.nvim#1443]
Thanks for building this plugin, it's been extremely useful. Recently I ran `:PackerSync` and started receiving notifications about the recent requirement bump to neovim 0.5.1. I noticed there is no versioning around the project so I had to manually pin to an old commit in my packer config to:
```
use {
    'nvim-telescope/telescope.nvim',
    commit = "3b9ac8e",
```
So that the error would go away. I couldn't find any version or CHANGELOG information on the change and had to jump through the issues to find the commit I could pin to. This would probably be a frustrating experience for some users, have there been talks of adding more information around releases so that breaking changes can be mitigated? The messaging around:
```
Telescope.nvim requires at least nvim-0.5.1. Please update or uninstall
```
Could be a little more explicit on what versions require the update?

**Comment by l-kershaw** [comment]
I've made [this PR](https://github.com/nvim-telescope/telescope.nvim/pull/1444) to explain this to users who encounter the error.

Does this changelog give sufficient information for you?

**Comment by thornycrackers** [comment]
Oh that is so cool. I think that's great! I didn't see the changelog in the docs folder. Thanks for being so fast.
