### ISSUE TITLE
Certain pickers close Telescope and enter insert mode

### ISSUE THREAD

**Issue by polak-jan** [nvim-telescope/telescope.nvim#1457]
### Description

As discussed in #1446, the issue I am facing is that some pickers close the Telescope window and put the focused buffer into insert mode.

My config is still written in Vim script, but I am able to repro the issue even with just what is listed as the minimal config at the bottom. Meaning just Telescope and lspconfig.

### Neovim version

```markdown
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu 18.04.2 LTS in WSL

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. Open neovim with the config provided bellow
2. `:Telescope`
3: Select either of these two pickers: `symbols`, `lsp_document_symbols` (possibly more, haven't tested them all)

### Actual behavior

Selecting the mentioned pickers closes the Telescope window and puts the focused buffer into insert mode.

### Minimal config

```Lua
call plug#begin()

Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }

call plug#end()

lua << EOF

require'lspconfig'.gopls.setup{}
require'lspconfig'.tsserver.setup{}
require'telescope'.setup{}
EOF
```
```

**Comment by polak-jan** [comment]
Just noticed that I forgot to update the checkhealth after adding treesitter. It doesn't really matter as the behaviour is the same both with and without it.

**Comment by l-kershaw** [comment]
How old a version of nightly do you have?
The latest output of the `:version` command is:
```
NVIM v0.6.0-dev+582-g87a053f12
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

Your provided `:version` doesn't have the extra info at the end

**Comment by polak-jan** [comment]
It was updated from the official PPM just before producing the repro.

**Comment by l-kershaw** [comment]
Is the `:version` info above (without the extra info) what you are getting?
If so, that's very confusing, as it should be there

**Comment by polak-jan** [comment]
Yes it's exactly what I am getting. The only thing I can think of is that I am somehow running nightly by accident, because I do have both the stable and unstable PPMs on my system, and the fact that the version number includes a commit hash from 3 days ago would support that.
```
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-r6Lw8y/neovim-0.6.0~ubuntu1+git202111151248-8f984dc1f-adeb5640f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -D
NVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -
fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-r6Lw8y/neovim-0.6.0~ubuntu1+git202111151248-8f984dc1f-adeb5640f/build/c
onfig -I/build/neovim-r6Lw8y/neovim-0.6.0~ubuntu1+git202111151248-8f984dc1f-adeb5640f/src -I/build/neovim-r6Lw8y/neovim-0.6.0~ubuntu1+git202111151248-8f984dc1f-adeb5640f/.deps/usr/include -I/usr/include -I/build/neovim-r6Lw8y/neo
vim-0.6.0~ubuntu1+git202111151248-8f984dc1f-adeb5640f/build/src/nvim/auto -I/build/neovim-r6Lw8y/neovim-0.6.0~ubuntu1+git202111151248-8f984dc1f-adeb5640f/build/include
Compiled by buildd@lgw01-amd64-002

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

And this is what `dpkg -s neovim` gets me:
```
Package: neovim
Status: install ok installed
Priority: optional
Section: editors
Installed-Size: 24706
Maintainer: Florian Walch <florian+launchpad@fwalch.com>
Architecture: amd64
Version: 0.6.0~ubuntu1+git202111151248-8f984dc1f-adeb5640f-72bbdecee~ubuntu18.04.1
Replaces: neovim-runtime
Provides: editor, vim
Depends: libc6 (>= 2.14), libluajit-5.1-2 (>= 2.0.4+dfsg)
Breaks: neovim-runtime
Description: Fork of Vim aiming to improve user experience, plugins, and GUIs.
Homepage: http://neovim.io
```

**Comment by l-kershaw** [comment]
Okay, then reasonable to assume that this isn't a problem from not being up to date on `nightly`

Do you get anything in `:messages` after trying to use either `:Telescope symbols` or `:Telescope lsp_document_symbols`?

**Comment by polak-jan** [comment]
Infact, I do. And this is also the first time I have tried running it directly like this instead of using the main `:Telescope` command, and doing it this way result in it failing even before the window is opened and **not going into INSERT mode**. And the following is printed, this time visible as the insert mode label used to be on top of it.
```
No sources found! Check out https://github.com/nvim-telescope/telescope-symbols.nvim for some prebuild symbols or how to create you own symbol source.
```

**Comment by polak-jan** [comment]
So I have done some investigating on my own.

There basically are two parts to this issue. One is documentation/me missing something. And one is Telescope not handling an error correctly.

The common thing for all the pickers, is that they exit prematurely, after printing a message. This isn't handled by Telescope and causes it to close immediately and shift focus back to the the split it was in before. But because it closes unexpectedly, the INSERT mode forced inside the Telescope searchbar stays on even after the focus changes, which hides the error message, leaving the user clueless.

Now for why the pickers fail:
 - symbols -- This is the one where some of the blame falls on me, because of the same word being used I assumed this picker belonged together with the other `symbols` pickers which isn't the case, and as the picker relies on manually provided data, which I don't have, it naturally fails.
 - lsp_workspace_symbols (lsp_document_symbols seems to be working now) -- This one is actually also simple, it's the same thing as #964 and #568

**Comment by Conni2461** [comment]
> The common thing for all the pickers, is that they exit prematurely, after printing a message.

Can you show these claims, with a video for example. Because right now the code is like this
```lua
local symbols = getSymbols()
if not symbols then
  print "err"
  return
end

openPicker()
```

this applies to `symbols`, `lsp_workspace_symbols` and many more. I know why `symbols` is failing. It says so in the printed message. We could use `log.error` for that or `vim.notify` to make it more obvious but i dont see how people miss this message.

 And for `lsp_workspace_symbols` there should also be a printed message for why its failing. We cant do anything if the lsp doesnt return things. So we probably should close #964 as well. We have dynamic_workspace_symbol to fix that for these lsps

**Comment by polak-jan** [comment]
Yes, as far as I can tell the behaviour is as expected, with the only thing here being an issue is that the insert mode persists and hides the message, confusing the user. So to solve this either a more noticable error message should be used or the insert mode issue be fixed to make sure the existing one is shown.

`lsp_workspace_symbols` prints this message:
![image](https://user-images.githubusercontent.com/11616898/142732272-bb9f1d45-f025-4b7f-b482-ae3a2cfd7fd5.png)

**Comment by Conni2461** [comment]
Please record a video with obs and upload it. 
We never go into insert mode until we actually run telescope. Which doesn't happen if we don't get any queries back from the lsp server.

**Comment by polak-jan** [comment]
Oh, right, my bad with a poor explanation. It happens when you just type `:Telescope` and then select the picker from the list there. Using a command to access the picker directly doesn't do this.

Interestringly, today I am getting a different behaviour for `symbols` compared to yesterday, while `lsp_workspace_symbols` still does the same thing.

https://user-images.githubusercontent.com/11616898/142733675-f3eec027-4684-405e-b272-8a96d212b13c.mp4

**Comment by Conni2461** [comment]
Oh its an issue when going over `:Telescope`. I was assuming you do `:Telescope lsp_workspace_symbols`.

Hmmm this one is tricky to fix.

**Comment by ulisses-cruz** [comment]
I'm having this issue too.

**Comment by CKolkey** [comment]
I've been experiencing this recently as well - I think a reasonable solution would be to add `vim.cmd.stopinsert()` here: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/actions/set.lua#L188

**Comment by Townk** [comment]
I started having the "insert mode" problem after I updated Vim to 0.10 nightly. I do have a map on the telescope that, when in insert mode, if I press `<esc>` it closes the Telescope.

I have a feeling that vim is sharing the current mode across buffers. If I'm on a standard buffer, put the editor in "insert mode", and use my mouse to "select" a different buffer on my tabline, the next buffer in focus is also in insert mode.

**Comment by jamestrew** [comment]
I've also started experiencing this issue. More people chiming in recently on this other issues as well #2027 

I've repost what I said there
> This is a pretty weird bug.
I experience this on nightly 801ac2acc but rolling back to 339011f59 seemed to have solved the issue for me. But even when I was experiencing this issue, it was not consistent so I couldn't even really do a git bisect. Even if I could, clearly people have been experiencing this as early as 0.7.

**Comment by rockyzhang24** [comment]
Also experiencing this issue after installing `nvim-treesitter-context`. Totally weird.

**Comment by koopa1338** [comment]
I also have this behavior recently. For me, it only appears the first time I use telescope (all my keymaps are using the `Telescope` command). It doesn't matter which finder I am using. After I opened a file through telescope, the bug disappears. The bug does not appear if I open nvim directly with a file passed. I use `alpha` as a starting buffer, could it somehow be caused by that? Is there anything else I could test to narrow down the bug?
```
NVIM v0.10.0-dev-117+g9033d5ecc-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by Shougo** [comment]
You should create the minimal configuration...

**Comment by rockyzhang24** [comment]
Confirmed that it caused by this commit neovim/neovim@d52cc66

**Comment by jamestrew** [comment]
I believe this is fix as of https://github.com/neovim/neovim/commit/b46f61ac050e6eb530ceb4d4b510b612596427c5
