### ISSUE TITLE
Ex mode in telescope

### ISSUE THREAD

**Issue by zim0369** [nvim-telescope/telescope.nvim#1464]
Ex-mode if I'm not wrong or basically the mode in which you enter commands by pressing `:` in neovim/vim has these problems:
- Use arrow keys to move through history
- Suggested commands window is not very intuitive
- Use arrow keys to move through suggested commands
- Use arrow keys to move through command being edited
- Can't use macros like `cw` for quickly editing commands
- Editing regexes in default ex mode is a pain in the arse
- Have to keep looking at the bottom  of screen for long commands

Fuzzy suggestions for the commands being entered would be also very useful.

I like the normal mode in telescope and ex mode would be nice to have especially for those long regexes and fuzzy suggestions.

**Comment by tjdevries** [comment]
I don't think this lines up with telescopes goals. Perhaps something
