### ISSUE TITLE
Quicklist - from grep string <c-q> generates list with incorrect paths

### ISSUE THREAD

**Issue by JoseConseco** [nvim-telescope/telescope.nvim#1466]
### Description

using grep_string, and then generating quick list from it - gives invalid paths like so: 
![image](https://user-images.githubusercontent.com/13521338/142597438-2236651d-1f1a-4915-b861-63df75a27b7a.png)
When I'm working in folder with spaces in directory path. 
If I enter into quickfix result - empty buffer is opened with incorrect path visible above .
Similar issue for live_grep.  But current_buffer_fuzzy_find works ok. 

### Neovim version

```markdown
NVIM v0.6.0-dev+594-g36538417f
Build type: Debug
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `media_files`
  - INFO: No healthcheck provided

## Telescope Extension: `sessions`
  - INFO: No healthcheck provided

## Telescope Extension: `vim_bookmarks`
  - INFO: No healthcheck provided
```

### Steps to reproduce
0. cwd into folder that has space in name. 
1. Telescope grep_string on any file that in in above directory
2. ctrl+q

### Expected behavior

tele generates quick fix with correct paths in results

### Actual behavior

Bad path in quick fix results

### Minimal config

```Lua
Maybe anyone can confirm this ?
```

**Comment by JoseConseco** [comment]
generated quick fix works though ok for project in other folder.... maybe issue is related to path format (spaces ? ) will test som more.

**Comment by Conni2461** [comment]
Pretty sure this is a dup and we already have a pr open for that. Dont have the numbers at hand

**Comment by Conni2461** [comment]
I think this is fixed by https://github.com/nvim-telescope/telescope.nvim/commit/b501d9ecb7d8181e2238620c919740025e8b2096

If not feel free to reopen

**Comment by JoseConseco** [comment]
yes, it is fixed now. Thx
