### ISSUE TITLE
scrollbind seems to confuse telescope

### ISSUE THREAD

**Issue by emmanueltouzery** [nvim-telescope/telescope.nvim#1468]
### Description

if scrollbind is active in the buffer that telescope is activated from, telescope doesn't display search results and flickers (and displays the results briefly) when the up or down arrows are pressed.

### Neovim version

```markdown
NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.5.1/x86_64-redhat-linux-gnu/config -I/builddir/build/BUILD/neovim-0.5.1/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.5.1/x86_64-redhat-linux-gnu/src/nvim/auto -I/builddir/build/BUILD/neovim-0.5.1/x86_64-redhat-linux-gnu/include
Compiled by mockbuild@koji

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

fedora 34

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `live_grep_raw`
  - INFO: No healthcheck provided

## Telescope Extension: `mapper`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:set scrollbind`
3. `:lua require('telescope.builtin').live_grep()`
4. `type "te" the live grep entry, there should be matches`
5. try to scroll among the matches

### Expected behavior

same behavior whether scrollbind is set or not: search matches are displayed, and you can use arrows to view/select them

### Actual behavior

when scrollbind is active, results appear and disappear when you scroll them using arrows, rendering is broken at times

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
thanks for reporting :)

can you test https://github.com/nvim-telescope/telescope.nvim/pull/1496

**Comment by emmanueltouzery** [comment]
sorry, I've tried to redirect to your repo instead of the normal telescope repo, but all I succeeded in doing was botching my config :/ trying to recover it now. So it's going to be hard for me to test it. but I gave that repro when reporting the bug, with the minimal config, and if that's fixed, it should be fine.
One thing is that I think you disable scrollbind, it would be nice to re-enable it when telescope closes if it was enabled, but then i guess who knows what action will telescope trigger, so presumably it's not that easy. Disabling it is definitely way better than nothing.

**Comment by Conni2461** [comment]
It should only affect the local telescope window. So nothing else. And i think thats the correct behavior, not scrolling other windows while we currently scroll inside telescope.

It fixed it for me but i kinda like asking the person who reported if it actually fixed the bug :)

**Comment by emmanueltouzery** [comment]
Great that it's only the telescope window. Yes, I think you can assume it's fixed, when it gets merged to master I'll test again but as it is, testing the patch is just beyond my mastery of nvim at this point :(

**Comment by Conni2461** [comment]
you could just go to the telescope.nvim repo and pull the pr with: `git fetch origin pull/1496/head:pr-1496`. After that you could checkout the new branch `pr-1496`.

There is also a way to do it with the github cli client
