### ISSUE TITLE
Can't create a cursor themed custom picker

### ISSUE THREAD

**Issue by Matsuuu** [nvim-telescope/telescope.nvim#1472]
### Description

I'm trying to create a custom picker as instructed [here](https://github.com/mfussenegger/nvim-jdtls/wiki/UI-Extensions) but I would want it themed with the `cursor` theme. It doesn't seem to apply however.

![image](https://user-images.githubusercontent.com/16068444/142677164-37aeecf0-be5e-44a3-af0b-385b83eab1f2.png)

### Neovim version

```markdown
NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5
```

### Operating system and version

Linux

### checkhealth telescope

```markdown
1
    1 health#telescope#check
    2 ========================================================================
    3 ## Checking for required plugins
    4   - OK: plenary installed.
    5   - OK: nvim-treesitter installed.
    6
    7 ## Checking external dependencies
    8   - OK: rg: found ripgrep 13.0.0
    9   - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities
   10
   11 ## ===== Installed extensions =====
   12
~
```

### Steps to reproduce

Add config like in https://github.com/mfussenegger/nvim-jdtls/wiki/UI-Extensions , and try to run jdtls code action through it

### Expected behavior

Get a cursor themed code action

### Actual behavior

Get a regular themed code action

### Minimal config

```Lua
-
```

**Comment by fdschmidt93** [comment]
Themes essentially constitute a bunch of options you can pass onto the picker as a collection, primarily affecting of course the layout. The `theme` shorthand is only a convenience layer for eg telescope setup. 

Therefore, you'd have to define opts as follows: `local opts = require "telescope.themes".get_cursor { your_other_picker_opts }`. 

which does the following (straight up copied):

```lua
function themes.get_cursor(opts)
  opts = opts or {}

  local theme_opts = {
    theme = "cursor",

    sorting_strategy = "ascending",
    results_title = false,
    layout_strategy = "cursor",
    layout_config = {
      width = 80,
      height = 9,
    },
    borderchars = {
      prompt = { "─", "│", " ", "│", "╭", "╮", "│", "│" },
      results = { "─", "│", "─", "│", "├", "┤", "╯", "╰" },
      preview = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
    },
  }

  return vim.tbl_deep_extend("force", theme_opts, opts)
end
```

I'd close this because I think the question is answered; if you need more help, let me know and I see what I can do :)

**Comment by Matsuuu** [comment]
Thanks so much @fdschmidt93 ! That did the trick! I tried close to everything else than that.
