### ISSUE TITLE
`current_buffer_fuzzy_find` no longer navigates to selected results

### ISSUE THREAD

**Issue by mystilleef** [nvim-telescope/telescope.nvim#1482]
### Description

`current_buffer_fuzzy_find` no longer navigates to selected results.

### Neovim version

```markdown
NVIM v0.6.0-dev+619-gcfa5d0680
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Fedora Linux 35 (Workstation Edition)

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1
```

### Steps to reproduce

1. Open a file in Neovim.
2. Launch the fuzzy buffer search picker with `:Telescope current_buffer_fuzzy_find`.
3. Search for a token.

### Expected behavior

I expect that when I select and activate the result of a search query, it navigates to the location of the query in the buffer.

### Actual behavior

When I select and activate the result of a search query, it does not navigate to the location of the query in the buffer. The video attached shows the issue.

https://user-images.githubusercontent.com/273399/143009275-8f1dbcef-f806-475b-8ad3-15359eca3cc9.mp4

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
        },
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by xsteadfastx** [comment]
same for me here...

**Comment by flleonx** [comment]
I have the same issue.

**Comment by weeman1337** [comment]
Can confirm. The last commit breaks it https://github.com/nvim-telescope/telescope.nvim/commit/6daf35c88c07dd4b220468968a742cda04889cd3 If rolling back before that one it is working.

**Comment by Conni2461** [comment]
Can someone test if #1480 this issue fixed.

I think the current telescope shutdown process does stuff that breaks stuff. :laughing: 
Personally i can't reproduce it with #1480

**Comment by weeman1337** [comment]
> Can someone test if #1480 this issue fixed.

Works for me

**Comment by fdschmidt93** [comment]
Yep, me too :)

**Comment by flleonx** [comment]
I am still having this problem :(

**Comment by Conni2461** [comment]
branch wasnt even rebased. sigh. will be a long night ...  looking into it

**Comment by flleonx** [comment]
Now it works perfect. Thank you :)
