### ISSUE TITLE
help_tags does not list all man pages

### ISSUE THREAD

**Issue by reverseila** [nvim-telescope/telescope.nvim#1489]
### Description

I issued `:helptags ALL` and that didn't help. If I invoke `:Man <manpage>`, it will bring the man page up (tab-completion will work too). Am I missing something?

One thing I've noticed is that the man pages that I was looking for and telescope couldn't find them, were compressed files (output of `file <manpage>`: ` gzip compressed data, max compression, from Unix, original size modulo 2^32 48364`) files.

Note that,

- The man page database is fully updated (with `sudo mandb`)
- I also experienced this behavior in FZF's `:Helptags` command.

### Neovim version

```markdown
NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5
```

### Operating system and version

Artixlinux ( x86_64 GNU/Linux )

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

nvim

### Expected behavior

List all the man pages on the system (those that the program `man` itself has access to).

### Actual behavior

`:Telescope help_tags` only list a portion of all the man page on the system

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
`:Telescope help_tags` will list vim help tags not man pages. You are looking for `:Telescope man_pages` to list all pages in (1).

To list more than (1) or other pages try `:Telescope man_pages section=2,3` (to list 2 and 3) or `:Telescope man_pages sections=ALL` to list all. More information `:help builtin.man_pages`

Btw the same applies to fzfs `:Helptags` it just doesnt list man pages

**Comment by reverseila** [comment]
I don't know why I thought `help_tags` supposed to list man pages. I actually tested the `:Telescope man_pages` command and just wasn't aware of its options. I should've consulted the help. Anyway, Sorry for the noise.

**Comment by reverseila** [comment]
Yes, Unfortunately, those `help_tags` were a mistake! I meant `man_pages`.

I tested those command and still that didn't help!

**Comment by Conni2461** [comment]
the setup call isnt 100% correct for `man_pages`. I left a comment where i changed it slightly
```lua
telescope.setup {
  defaults = {
    theme = "dropdown",
    border = {},
    vimgrep_arguments = {
      "rg", "--color=never", "--no-heading", "--with-filename", "--line-number",
      "--column", "--smart-case", "--hidden"
    },
    prompt_prefix = "❯ ",
    selection_caret = "❯ ",
    sorting_strategy = "ascending",
    color_devicons = true,
    layout_config = {
      prompt_position = "top",
      horizontal = {
        width_padding = 0.04,
        height_padding = 0.1,
        preview_width = 0.6
      },
      vertical = {
        width_padding = 0.05,
        height_padding = 1,
        preview_height = 0.5
      }
    },
    mappings = {
      i = {
        ["<C-j>"] = actions.move_selection_next,
        ["<C-k>"] = actions.move_selection_previous
        -- ["<Esc>"] = actions.close
      },
      n = {["q"] = actions.close, ["<Esc>"] = actions.close}
    },
  },
  pickers = { -- it needs to go in another table called pickers. Not in the defaults table.
    man_pages = { sections = { "2", "3" } }
  }
}
```

![image](https://user-images.githubusercontent.com/15233006/143242654-38bd5a0f-fa5c-44f7-801f-410bcd14222a.png)

**Comment by reverseila** [comment]
I am really sorry, I am officially blind. That did it. Thanks for help man!
BTW, why the command `:Telescope man_pages section=2,3` didn't work?

**Comment by Conni2461** [comment]
my bad i mistyped. should have been `sections=4, 5` but the `ALL` example didnt contain a typo as well as the `:help builtin.man_pages`

**Comment by reverseila** [comment]
I learned a lot. Thanks man!
