### ISSUE TITLE
current_buffer_fuzzy_find messes up highlighting in preview and buffer

### ISSUE THREAD

**Issue by tibimunteanu** [nvim-telescope/telescope.nvim#1504]
### Description

Calling current_buffer_fuzzy_find messes up highlighting in preview and buffer.
I should mention that I first started seeing this bug after I added treesitter and all the telescope finders would behave like this.
I added treesitter = false in defaults -> preview, and it fixed the issue for all telescope finders, EXCEPT for the current_buffer_fuzzy_find.

### Neovim version

```markdown
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 10

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 11.0.2
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `coc`
  - INFO: No healthcheck provided

## Telescope Extension: `fzy_native`
  - INFO: No healthcheck provided

## Telescope Extension: `git_worktree`
  - INFO: No healthcheck provided

## Telescope Extension: `session-lens`
  - INFO: No healthcheck provided
```

### Steps to reproduce

nvim -nu minimal.lua

### Expected behavior

opening telescope current_buffer_fuzzy_find DOES NOT change highlighting

### Actual behavior

opening telescope current_buffer_fuzzy_find DOES change highlighting

### Minimal config

```Lua
require('telescope').setup {
    defaults = {
        file_sorter = require('telescope.sorters').get_fzy_sorter,
        file_previewer   = require('telescope.previewers').vim_buffer_cat.new,
        grep_previewer   = require('telescope.previewers').vim_buffer_vimgrep.new,
        qflist_previewer = require('telescope.previewers').vim_buffer_qflist.new,
        preview = {
          treesitter = false
        }
    },
    extensions = {
        fzy_native = {
            override_generic_sorter = false,
            override_file_sorter = true,
        }
    }
}

require('telescope').load_extension('fzy_native')
require('telescope').load_extension('coc')
EOF

nnoremap <silent> <leader>fa :lua require('telescope.builtin').find_files({ hidden = true })<CR>
nnoremap <silent> <leader>ff :lua require('telescope.builtin').git_files()<CR>
nnoremap <silent> <leader>fo :lua require('telescope.builtin').buffers()<CR>
nnoremap <silent> <leader>fh :lua require('telescope.builtin').help_tags()<CR>
nnoremap <silent> <leader>ft :lua require('telescope.builtin').file_browser()<CR>
nnoremap <silent> <leader>f: :lua require('telescope.builtin').commands()<CR>

nnoremap <silent> <leader>fs :lua require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ")})<CR>
nnoremap <silent> <leader>fw :lua require('telescope.builtin').grep_string { search = vim.fn.expand("<cword>") }<CR>
nnoremap <silent> <leader>fg :lua require('telescope.builtin').live_grep()<CR>
nnoremap <silent> <leader>fz :lua require('telescope.builtin').current_buffer_fuzzy_find(require('telescope.themes').get_ivy())<CR>
```

**Comment by Conni2461** [comment]
Can you provide steps to reproduce? Can you a full minimal config, for example with the treesitter config (thats the important things when you say it happened after you added it). And maybe provide a short clip.

Otherwise i cant help you because i can t reproduce it.

**Comment by tibimunteanu** [comment]
[init.zip](https://github.com/nvim-telescope/telescope.nvim/files/7621533/init.zip

https://user-images.githubusercontent.com/1462924/143952548-2c01b4dd-9714-413f-a2bf-3cd9a7f320ec.mp4

I attached a minimal init.vim and a short clip to show that when I open find_files the colors don't change, but when I open current_buffer_fuzzy_find, the colors in the buffer and the preview change.

**Comment by Conni2461** [comment]
I dont download zip. But you video was helpful because i saw your config in the bag. https://github.com/nvim-telescope/telescope.nvim/pull/1524 should fix your issue.

The problem is that highlighting is disabled but parsers are installed. So we use those parsers to highlight the code in the results window in current_buffer_fuzzy_find and for some reason they are applied to the original buffer when parsing it. So we just no longer calculate the colors.

The alternative would be to use `get_string_parser` rather than buffer. But they have some limitations when it comes to injections: https://github.com/neovim/neovim/blob/7229afcd60b6a3ad2f0b58ca270f11936f4a7d1b/runtime/lua/vim/treesitter/languagetree.lua#L263-L265
