### ISSUE TITLE
Add highlight group for Results window

### ISSUE THREAD

**Issue by siduck** [nvim-telescope/telescope.nvim#1507]
would it be possible to add a highlight group for the results window , something like TelescopeResultstNormal?

**Comment by max397574** [comment]
![telescope_highlights_wanted](https://user-images.githubusercontent.com/81827001/143845191-4d7a3d57-4691-4149-aada-86fb2f0f6bbd.jpg)

basically we want to be able to do this

this is done with photoshop

**Comment by max397574** [comment]
this could be done by creating TelescopePromptNormal and TelescopeResultsNormal or just one of them and for the other normal is used (I'd prefer the first).

Another problem is that TelescopeNormal isn't used when you aren't in insert mode
![Screenshot 2021-11-29 at 10 47 47](https://user-images.githubusercontent.com/81827001/143846172-ea2b6f7e-bfe7-43af-ac3d-160e1b4a82d4.png)
![Screenshot 2021-11-29 at 10 47 54](https://user-images.githubusercontent.com/81827001/143846176-a0095287-b512-47e0-a5ed-84abdd99d6ea.png)

**Comment by l-kershaw** [comment]
Happy to review a PR to add this feature if someone is interested in writing one.

I _think_ that this should only require changes in `plugin/telescope.vim` (adding links to predefined highlights) and `lua/telescope/pickers.lua` (changing the settings for the relevant popups).

**Comment by max397574** [comment]
I'll try

**Comment by max397574** [comment]
where would that be
> lua/telescope/pickers.lua (changing the settings for the relevant popups).

this file is 1.4k lines and I have no clue where to search

**Comment by l-kershaw** [comment]
You need to search for `TelescopeNormal` which is the current highlight name

**Comment by max397574** [comment]
imo it makes sense to link them to `TelescopeNormal` what do you think?

**Comment by max397574** [comment]
will be closed with https://github.com/nvim-telescope/telescope.nvim/pull/1514
