### ISSUE TITLE
when Preview NTUSER.DAT, nvim crash

### ISSUE THREAD

**Issue by zgpio** [nvim-telescope/telescope.nvim#1519]
### Description

https://user-images.githubusercontent.com/19503791/144073650-c77e0eb0-1eba-41f4-8cdc-bd62d824a001.mp4

### Neovim version

```markdown
NVIM v0.6.0-dev+518-g1dbbaf89b
```

### Operating system and version

windows 10

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

ref to video

### Actual behavior

nvim crash

### Minimal config

```Lua
default config
```

**Comment by fdschmidt93** [comment]
See also: https://github.com/nvim-telescope/telescope.nvim/issues/1263

Please make sure telescope is updated. Please check whether this happens with all dat or just `NTUSER.dat`. Please repro with minimal init lua.

**Comment by Conni2461** [comment]
Closing as stale
