### ISSUE TITLE
Bug in code example: Configuration Recipes: Customize buffers display to look like LeaderF

### ISSUE THREAD

**Issue by jeetsukumaran** [nvim-telescope/telescope.nvim#1527]
### Description

As given in https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#customize-buffers-display-to-look-like-leaderf , instead of:

```lua
require('telescope.builtin').buffers({
  -- ...
  entry_maker = require'vimrc.telescope.my_make_entry'.gen_from_buffer_like_leaderf(),
})
```

it should be:

```lua
require('telescope.builtin').buffers({
  -- ...
  entry_maker = require'rc.telescope.my_make_entry'.gen_from_buffer_like_leaderf(),
})
```

### Neovim version

```markdown
n/a
```

### Operating system and version

n/a

### checkhealth telescope

```markdown
n/a
```

### Steps to reproduce

n/a

### Expected behavior

n/a

### Actual behavior

n/a

### Minimal config

```Lua
n/a
```

**Comment by Conni2461** [comment]
Wiki is community maintained. You can just edit the Page and apply your findings.
