### ISSUE TITLE
Deleting buffer from the builtin buffers picker with`"row"` as `selection_strategy` is broken

### ISSUE THREAD

**Issue by mroavi** [nvim-telescope/telescope.nvim#1539]
### Description

Deleting a buffer from the builtin buffers picker with `"row"` as `selection_strategy` is broken.
This used to work when [this](https://github.com/nvim-telescope/telescope.nvim/pull/828) PR was merged as shown in the video here: https://github.com/nvim-telescope/telescope.nvim/pull/828#issue-881876741

I traced the bug back to this commit: https://github.com/nvim-telescope/telescope.nvim/commit/dea927d0eb22255632dd82d2efff1a68d621c871

### Neovim version

```markdown
NVIM v0.6.0-dev+558-g3ba800f15
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Manjaro Linux x86_64 -  Kernel: 5.10.79-1-MANJARO

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Load several buffers.
3. `:telescope buffers`
4. select an entry in the middle of the picker and press "x"

### Expected behavior

See video above.

### Actual behavior

The selection resets to the first row of the picker.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  local actions = require 'telescope.actions'
  require('telescope').setup({
    defaults = {
      selection_strategy = "row",
      mappings = {
        i = { ["x"] = actions.delete_buffer },
      },
    },
  })
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by stephane-klein** [comment]
@mroavi I'm interested in this feature 🙂

Have you made any progress in its implementation?

**Comment by stephane-klein** [comment]
I found this https://old.reddit.com/r/neovim/comments/qspemc/close_buffers_with_telescope/

Tested with success 🙂

**Comment by mroavi** [comment]
@Conni2461 solved this in [this](https://github.com/nvim-telescope/telescope.nvim/pull/1559) pr. There is only one corner case I found that still doesn't work as I mentioned there.

**Comment by Conni2461** [comment]
PR didn't close the issue :(

Fixed by https://github.com/nvim-telescope/telescope.nvim/commit/2532b98d6747230bb8e55753aa992bea267540a1
