### ISSUE TITLE
highlight group for results counter in prompt

### ISSUE THREAD

**Issue by fedoranvar** [nvim-telescope/telescope.nvim#1540]
**Is your feature request related to a problem? Please describe.**
Results counter in prompt hardcoded to `NonText` highlight group

https://github.com/nvim-telescope/telescope.nvim/blob/ef245548a858690fa8f2db1f1a0eaf41b93a6ef6/lua/telescope/pickers.lua#L1097-L1099

 trouble begins when some colorscheme linked NonText  to some highlight group/
 
for example spaceindentations in colorscheme:
![image](https://user-images.githubusercontent.com/52028706/144537113-63f8722f-7e5f-4359-b942-9720cafae14b.png)

**Describe the solution you'd like**
To be able to tweak dedicated highlight group

**Describe alternatives you've considered**
editing `NonText` highlight group

**Additional context**
Thank you!

**Comment by gegoune** [comment]
@fedoranvar That's very pretty, do you mind sharing your configuration, please?

**Comment by fedoranvar** [comment]
@Conni2461 
Thank you!

@gegoune 
Sure, here you go:

```lua
{
    initial_mode = "insert",
    selection_strategy = "reset",
    prompt_prefix = "  +  ",
    selection_caret = " >  ",
    entry_prefix    = "    ",
    sorting_strategy = "ascending",
    borderchars = {
        -- prompt = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
        -- results = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
        -- preview = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
        prompt  = { " ", " ", " ", " ", " ", " ", " ", " " },
        results = { " ", " ", " ", " ", " ", " ", " ", " " },
        preview = { " ", " ", " ", " ", " ", " ", " ", " " },
    },
    layout_strategy = "vertical",
   preview = {
       hide_on_startup = true,
   },
    layout_config = {
        preview_cutoff = 1, -- Preview should always show (unless previewer = false)

        prompt_position = "top",
        vertical = {
            width = 0.99,
            height = 0.9,
            preview_height = 0.5,
            mirror = true,
        },
    },
}
```
