### ISSUE TITLE
Make buffer_delete default to force=false

### ISSUE THREAD

**Issue by the42** [nvim-telescope/telescope.nvim#1541]
**Is your feature request related to a problem? Please describe.**
The delete_buffer action forcefully deletes a buffer. This is a nonsensical default

**Describe the solution you'd like**
Hint that a dirty buffer is going to be deleted or simply fail with the default nvim mechanisms.

**Additional context**
The buffer picker doesn't make it clear that a buffer contains unsaved content.

Related to #689

**Comment by Conni2461** [comment]
Also not a enhancement. But i let this one slide. Thanks for reporting. Should be fixed
