### ISSUE TITLE
Uniform behaviour of path separators between windows and unix

### ISSUE THREAD

**Issue by the42** [nvim-telescope/telescope.nvim#1542]
**Is your feature request related to a problem? Please describe.**
File preview only understands unix path separators

**Describe the solution you'd like**
Buffer preview is insensitive to windows vs. unix path separators.

When I browse the `:Telescope buffers` and my terminal is wide enough I get a helpful buffer preview. This however only works for buffers pointing to files which have been opened using slash-separated paths. On Windows, nvim happily opens both forward and backward separated paths. This happens eg. when using `:e <filespec><Tab>` which defaults to separating paths with  `\`. For such buffers no preview is available.

**Additional context**
**Even more so, if I open a buffer for which I get no preview from `buffers` with <CR>, neovim will open a second buffer pointing to the same file which I can edit completely independently from the first file, leading to a potential data loss**

**Comment by Conni2461** [comment]
this is not an enhancement. Its a bug. So please open a bug report and fill out the template
