### ISSUE TITLE
Live_grep not working. Issue with make_entry.lua? 

### ISSUE THREAD

**Issue by itstheandre** [nvim-telescope/telescope.nvim#1547]
### Description

I am trying to run Telescope live_grep and i keepgetting the same error. I have tried reinstalling the plugin and still not working.

Just running the live_grep command works, but the moment I input any char it breaks with the same errror

### Neovim version

```markdown
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.6.0/share/nvim"
```

### Operating system and version

macOs 12.0.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====
```

### Steps to reproduce

I dont really know how to explain. I can pass my neovim config [here](https://github.com/itstheandre/config/tree/master/nvim/.config/nvim).

### Actual behavior

[WARN  Fri Dec  3 17:33:45 2021] ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:444: Finder failed with msg:  ...packer/start/telescope.nvim/lua/telescope/make_entry.lua:127: bad argument #1
       │  to 'find' (string expected, got nil)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
My bad https://github.com/nvim-telescope/telescope.nvim/pull/1548

**Comment by Conni2461** [comment]
Thanks for reporting tho :)

**Comment by itstheandre** [comment]
Ah so you know what this might be @Conni2461 ?

**Comment by Conni2461** [comment]
already have the fix. Waiting for pipeline to finish. Just stumbled across this myself. I merged a PR earlier that had a typo.

**Comment by itstheandre** [comment]
Ah cool cool. after it is merged should I jsut run another `:PackerSync` and that should work?

**Comment by Conni2461** [comment]
Yes. i think so

**Comment by itstheandre** [comment]
Working @Conni2461  👍  
Thanks!
Thats probably the quickest bug I have ever seen fixed in my entire life. Not even in my projects 💪
