### ISSUE TITLE
Left side border characters from telescope window preview does not work

### ISSUE THREAD

**Issue by mateusfdl** [nvim-telescope/telescope.nvim#1575]
### Description

The characters on the left window border do not render even though the settings are default

### Neovim version

```markdown
NVIM v0.6.0-dev+107-g3d1835967
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOs Monterey 12.0.1

### checkhealth telescope

```markdown
========================================================================
## Checking for required plugins
    - OK: plenary installed.
    - OK: nvim-treesitter installed.
## Checking external dependencies
    - OK: rg: found ripgrep 13.0.0
    - OK: fd: found fd 8.2.1
## ===== Installed extensions =====
```

### Steps to reproduce

1. open Nvim
2. `:lua require('telescope.builtin').find_files()`

### Actual behavior

![image](https://user-images.githubusercontent.com/41559036/145242002-52c5dcb2-74b2-4347-b352-91c2e3063433.png)

### Minimal config

```Lua
local M = {}
local options = vim.opt
local cmd = vim.cmd

function M.vim_auto_cmds()
  cmd("filetype plugin indent on")
  cmd("highlight ColorColumn ctermbg=red")
  cmd("colorscheme dracula")
  cmd("syntax on")
  cmd("syntax enable")
end

function M.lua_auto_cmds()
  options.mouse                     ="nv"
  options.colorcolumn		    ='80'
  options.encoding		    ='utf-8'
  options.number		    =true
  options.relativenumber	    =true
  options.autoindent		    =true
  options.autoread		    =true 
  options.ruler			    =true
  options.showcmd		    =true
  options.smartcase 		    =true
  options.termguicolors             =true
  options.cursorline		    =true
  options.autoread		    =true
  options.ruler 		    =true
  options.laststatus		    =2
  options.scrolloff		    =3
  options.shiftwidth		    =2
  options.backspace		    ='2'
  options.softtabstop		    =2                                     
  options.tabstop		    =8
  options.incsearch		    =true
  options.hlsearch		    =true
  options.ignorecase		    =true
  options.smartcase		    =true
end

function M.setup()
  M.vim_auto_cmds()
  M.lua_auto_cmds()
end

return M
```

**Comment by l-kershaw** [comment]
I can't reproduce this using the config you have given.
I would suggest either bisecting your options to see which (if any) affect this; e.g. I doubt `hlsearch` would cause this sort of issue.
This will make the config provided actually minimal, and thus make it easier for maintainers to diagnose your issue.

Also, you haven't included anything related to telescope in your config, so we can't tell if you have correctly set up even the default behaviour.

**Comment by mateusfdl** [comment]
Thank you very much, it was indeed hlsearch. I will close the issue because the problem has already been fixed.

**Comment by acro5piano** [comment]
In my case, removing the following line from `init.vim` solved the issue.

```
set ambiwidth=double
```
