### ISSUE TITLE
C-W stopped working in the prompt

### ISSUE THREAD

**Issue by Gelio** [nvim-telescope/telescope.nvim#1579]
### Description

`<C-W>` in insert mode is often used to remove the current word. It used to work in the Telescope picker. I recently noticed it stopped working and instead it seems to work as-if it was not in Insert mode (invoking the regular `<C-W>` from normal mode).

### Neovim version

```markdown
NVIM v0.7.0-dev+697-g6063e07a0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az32-430
```

### Operating system and version

Ubuntu 20.04 LTS

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 7.4.0
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:Telescope live_grep`
3. Type in any text in the prompt (e.g. `pack`)
4. Press C-W in insert mode

### Expected behavior

The word is removed and the picker is empty. Neovim remains in insert mode.

### Actual behavior

The cursor changes to a block. The word is not removed. It looks as if `<C-W>` from normal mode was executed (the window manipulation prefix).

![image](https://user-images.githubusercontent.com/889383/145386637-59b1fcd3-6fc3-450b-8994-bbb01bc151b9.png)

https://user-images.githubusercontent.com/889383/145386657-f009b171-ad67-4d6e-83be-a893bc75203b.mp4

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
Same question essentially came up on Neovim gitter [here](https://gitter.im/neovim/neovim?at=61b0936ccd3f06175df810e0).

Copying reply b/c too lazy:

Sean Dewar @seandewar:matrix.org [m] Dez. 08 12:33
its expected as C-W works for window commands while in insert mode in the prompt buffer now
like vim

elianiva @elianiva:matrix.org [m] Dez. 08 12:33
ok, thanks

Sean Dewar @seandewar:matrix.org [m] Dez. 08 12:37
that said it looks like ctrl-shift-w should work according to the docs

with Sean being responsible to have contributed merging the corresponding Vim patch into Neovim.

**Comment by elianiva** [comment]
FWIW you can still remap `<C-W>` to `<C-S-W>` if you want the old behaviour. That's what I do in my config.

**Comment by fdschmidt93** [comment]
> FWIW you can still remap <C-W> to <C-S-W> if you want the old behaviour. That's what I do in my config.

I'm personally not a 100% sure what that means :sweat_smile: but I also was too lazy too read everything.

Another workaround, which seems to work as expected is something like

```lua
require "telescope".setup {
  defaults = {
    mappings = {
      i = {
        ["<C-w>"] = function()
          vim.cmd [[normal! bcw]]
        end,
      },
    },
  }
}
```

**Comment by Gelio** [comment]
Thanks for the explanation and the suggested solutions, they make sense :+1: I'm surprised that `<C-W>` is now used for window management in insert mode in prompt buffers, but who am I to suggest deviating from vim's default behavior :smile: 

Coincidentally, `<C-S-W>` is [a kitty shortcut for closing the window](https://sw.kovidgoyal.net/kitty/overview/#windows). Adding `map ctrl+shift+w no_op` to kitty's config file disables that behavior and allows using `<C-S-W>` in neovim

**Comment by fdschmidt93** [comment]
> Coincidentally, <C-S-W> is a kitty shortcut for closing the window. Adding map ctrl+shift+w no_op to kitty's config file disables that behavior and allows using <C-S-W> in neovim

yeah, I ran into the same thing. That's why I cooked up the remap as above.

**Comment by tjdevries** [comment]
```lua
        ["<C-w>"] = function()
          vim.api.nvim_input "<c-s-w>"
        end,
```

Maybe we should put this as a default mapping?

**Comment by williamboman** [comment]
`<C-w>` is a very well established keybind to delete the word before the cursor in Unix programs. The same for `<C-u>`. Both are very useful in a prompt input, I think it makes sense to make it default behavior :+1:!

**Comment by tjdevries** [comment]
If someone makes PR and tags me, we can probably merge that. It is easy to disable and is basically "backwards compatible" IMO

**Comment by davegallant** [comment]
Also stumbled upon this issue after expecting `<C-w>` to work.
