### ISSUE TITLE
Stop using lsp deprecated functions

### ISSUE THREAD

**Issue by bellini666** [nvim-telescope/telescope.nvim#1581]
### Description

There are some lsp functions that were deprecated. [this commit](https://github.com/neovim/neovim/pull/16536/files) added warnings to those which spams deprecation warnings everytime those are used.

### Neovim version

```markdown
NVIM v0.7.0-dev+698-g2fe60905f
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by bellini@behemoth

Features: +acl +iconv +tui
```

### Operating system and version

Debian Unstable

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

`:lua require('telescope.builtin').lsp_document_diagnostics()` will display the warning that even needs to be dismissed

(there are probably other functions. that one is an example where the problem happens)

### Expected behavior

No warning

### Actual behavior

vim.lsp.diagnostic.get is deprecated. See :h deprecated

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
happens this tomorrow: https://github.com/nvim-telescope/telescope.nvim/pull/1553

we cant switch over to using 0.6 stuff until we require minimum 0.6: this happens tomorrow: https://github.com/nvim-telescope/telescope.nvim/issues/1470#issuecomment-985772540

**Comment by bellini666** [comment]
Hey @Conni2461 ,

Oh, nice, so tomorrow this will be fixed :). Thanks for the heads up!

**Comment by Conni2461** [comment]
Yeah but we will do a rename of the functions. `lsp_document_diagnostics` will be deprecated (with a message) and the new name will be `diagnostics_document ` because the new picker no longer have things to do with lsp. Like `vim.diagnostics`
Same applies for `lsp_workspace_diagnostics` -> `diagnostics_workspace`. But that should only be a naming change for you.

I'll merge later. Still need to clean up some minor things

**Comment by Conni2461** [comment]
My previous comment is no longer correct. Its now
- Telescope lsp_document_diagnostics -> Telescope diagnostics bufnr=0
- Telescope lsp_workspace_diagnostics -> Telescope diagnostics

For more informations see `:help telescope.changelog-1553` and `:help builtin.diagnostics`
