### ISSUE TITLE
Syntax Highlighting in preview for ejs files? 

### ISSUE THREAD

**Issue by Rz-Rz** [nvim-telescope/telescope.nvim#1585]
**Is your feature request related to a problem? Please describe.**
No syntax highlighting for .ejs files (basically html file with javascript mixed in it)

**Describe the solution you'd like**
Syntax highlighting of .ejs files.

**Describe alternatives you've considered**
applying at least HTML and maybe JS rules to highlight.

**Comment by Conni2461** [comment]
Whats the vim filetype?

**Comment by Conni2461** [comment]
I can't help you if you can't provide me the expected filetype and i honestly don't wanna go looking for it so closing.

You can basically also add the filetype yourself. Read the section here: https://github.com/nvim-telescope/telescope.nvim#previewers
