### ISSUE TITLE
Pipe output from one picker into a new configuration

### ISSUE THREAD

**Issue by Conni2461** [nvim-telescope/telescope.nvim#1590]
Example would be live_grep -> fuzzy, or `lsp_dynamic_workspace_symbols`

The interface i had in my was something like this
```lua
attach_mappings = function(map) 
  map("i", "<c-f>", function(prompt_bufnr)
    local line = action_state.get_current_line()
    require("telescope.actions.generate").pipe(prompt_bufnr, {
      prompt_title = "Find Word (" .. line .. ")" 
      sorter = conf.generic_sorter(opts),
    })
  end)
  return true
end
```
It should allow us to take all items that were already gather from `live_grep` (for example) and put them back into a `new_table` with a fuzzy sorter. We should probably only refresh the picker rather than closing and reopening it. If we pass in a sorter we need to make sure that its correctly setup. This includes calling the `init` function of the sorter. Otherwise fzf sorter wouldnt work.

CC @kylo252 If you would be interested in doing this, I would assign you otherwise i flag it with `good first issue`

**Comment by danielo515** [comment]
Ins't this similar to #793 , which is attempt to be done in #1115 ?

**Comment by Conni2461** [comment]
forgot that #793 existed. I looked at #1115 a long time ago and it looks promising.

Some time ago we had a not so great proposal and then i wrote down what i was expecting from something like that (interface wise). The task shouldn't be that difficult and if i find the time i'll write the implementation (probably based on #1115) prior to 0.1 (#1938)

**Comment by Conni2461** [comment]
A somewhat basic interface is provided (we can add additional config options on demand) and we provide implementations refine implementation for `live_grep` and `lsp_dynamic_workspace_symbols` to go from live to fuzzy with the default key being `<c-space>` and it can be configured  to custom keys, see https://github.com/nvim-telescope/telescope.nvim/pull/2034
