### ISSUE TITLE
Directory names with hyphen aren't respected by file_ignore_patterns

### ISSUE THREAD

**Issue by Melkster** [nvim-telescope/telescope.nvim#1591]
### Description

I noticed that directories with a hyphen (`-`) in the name aren't ignored by `file_ignore_patterns`.

### Neovim version

```markdown
NVIM v0.7.0-dev+660-gd3585e0ec
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Manjaro Linux x86_64

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. `> mkdir test-dir && touch test-dir/testfile`
2. Run neovim with above config
3. Press `<C-p>` and notice that `test-dir/testfile` shows up
4. Try renaming `test-dir/` to `test_dir/` in `file_ignore_patterns` in the above config, as well as in your filesystem
5. Run neovim with new config and press `<C-p>`
6. Notice that now `test_dir/` doesn't show up

### Expected behavior

If a directory name in `file_ignore_patterns` contains a hyphen it should be ignored just like any other directory name.

### Actual behavior

`test-dir/testfile` shows up as a file, even though it is ignored by `file_ignore_patterns`

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  require('telescope').setup {
    defaults = {
      file_ignore_patterns = { 'test_dir/' }
    }
  }

  vim.api.nvim_set_keymap('n', '<C-p>', '<cmd>lua require("telescope.builtin").find_files()<CR>', {})
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by gegoune** [comment]
https://www.lua.org/manual/5.1/manual.html#5.4.1

>Character Class:
>
>A character class is used to represent a set of characters. The following combinations are allowed in describing a character class:
>
>x: (where x is not one of the magic characters ^$()%.[]*+-?) represents the character x itself.

You need to scape it.

**Comment by Melkster** [comment]
Thanks, you're right. I did try escaping the hyphen using backslash before posting this issue but that didn't work. However, using double hyphens solved it:

```lua
file_ignore_patterns = { 'test--dir/' }
```

**Comment by Conni2461** [comment]
For future reference this would be the correctly escaped example
```lua
file_ignore_patterns = { "test%-dir/" }
```
