### ISSUE TITLE
Opening Telescope results in Lua errors

### ISSUE THREAD

**Issue by Leandros** [nvim-telescope/telescope.nvim#1593]
### Description

Opening, for example, `.find_files()` results in a lua error:

![image](https://user-images.githubusercontent.com/396475/145896680-b19b061c-5625-4534-b66c-cd7d504d6dde.png)

### Neovim version

```markdown
NVIM v0.7.0-dev+715-g1f3c0593e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-791

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info


---

NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-703

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Windows 11 21H2 22000.348

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Call: `:lua require('telescope.builtin').find_files()`

### Expected behavior

No Lua errors

### Actual behavior

Getting lua errors

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim'
        },
        
      },
      'thirtythreeforty/lessspace.vim', -- THIS IS THE CULPRIT
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
To double check, that happens with minimal init lua? Screenshot seems to indicate otherwise and, just trried, I cannot reproduce on latest neovim master with up-to-date telescope.

**Comment by Leandros** [comment]
Yes, @fdschmidt93, I can reproduce the issue with the minimal config.

**Comment by l-kershaw** [comment]
Just to clarify @Leandros, I'm guessing you mean that you can reproduce with the minimal config you provided (including `lessspace.vim`) not with the default minimal config, right?

If so, this definitely seems like a LessSpace issue, rather than a Telescope issue, since we don't have `insert_top` (from the error) anywhere in our codebase, and it features in LessSpace [here](https://github.com/thirtythreeforty/lessspace.vim/blob/master/autoload/lessspace.vim).

**Comment by Leandros** [comment]
> Just to clarify @Leandros, I'm guessing you mean that you can reproduce with the minimal config you provided (including `lessspace.vim`) not with the default minimal config, right?

Yes, correct. Fair enough. Let's close it.
