### ISSUE TITLE
Previewer not show

### ISSUE THREAD

**Issue by gary-ruizhang** [nvim-telescope/telescope.nvim#1594]
### Description

Previewer not show by default and some related config not work. 
`["<M-p>"] = action_layout.toggle_preview` will show 
`E5108: Error executing lua [string ":lua"]:8: attempt to index global 'action_layout' (a nil value)
stack traceback:
        [string ":lua"]:8: in main chunk
`

### Neovim version

```markdown
NVIM v0.7.0-dev+717-gf37c5f180
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.0.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:Telescope find_files`

### Actual behavior

![image](https://user-images.githubusercontent.com/32344731/145967498-88fec1f7-9a32-44c1-9342-40963f7aa0fc.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
There's two issues here.

1. Minimal init lua does not show a preview for you? That's weird. I've just tried the minimal init lua provided and preview shows.
2. The way it reads: Did you just copy `["<M-p>"] = action_layout.toggle_preview`? You have to require `local action_layout = require "telescope.actions.layout" at the top of the file beforehand.

**Comment by gary-ruizhang** [comment]
@fdschmidt93 yes, the issue 2 is my mistake.

**Comment by l-kershaw** [comment]
The minimal init not showing preview by default is likely due to the default `preview_cutoff` value of 120 columns. It looks like your terminal is smaller than 120 columns.

If you want the preview to appear by default you should have something like the following in your telescope config:
```lua
require("telescope").setup({
  defaults = {
    layout_config = {
      horizontal = {
        preview_cutoff = 0,
      },
    },
  },
})
```

**Comment by gary-ruizhang** [comment]
> The minimal init not showing preview by default is likely due to the default `preview_cutoff` value of 120 columns. It looks like your terminal is smaller than 120 columns.
> 
> If you want the preview to appear by default you should have something like the following in your telescope config:
> 
> ```lua
> require("telescope").setup({
>   defaults = {
>     layout_config = {
>       horizontal = {
>         preview_cutoff = 0,
>       },
>     },
>   },
> })
> ```

yes, I have a rather large font size config of my terminal. Thanks.

**Comment by tarikwaleed** [comment]
> The minimal init not showing preview by default is likely due to the default `preview_cutoff` value of 120 columns. It looks like your terminal is smaller than 120 columns.
> 
> If you want the preview to appear by default you should have something like the following in your telescope config:
> 
> ```lua
> require("telescope").setup({
>   defaults = {
>     layout_config = {
>       horizontal = {
>         preview_cutoff = 0,
>       },
>     },
>   },
> })
> ```

after trying too many things, this is what worked for me , thanks @l-kershaw

**Comment by zach-is-my-name** [comment]
That drove me a bit mad.  Maybe there's a more sensible default settings that won't block previewers with default settings if the user likes their terminal font a bit larger than average?

**Comment by TheRustifyer** [comment]
> That drove me a bit mad. Maybe there's a more sensible default setting that won't block previewers with default settings if the user likes their terminal font a bit larger than average?

I had the same issue, and also drove me mad. Using telescope to change the colorscheme seems to be a popular option. Maybe it will be nice to add some references into the main README.md, or even having a new recipe making the people aware the possible issues that they can find.

**Comment by mrjackphil** [comment]
Thanks for the answer.
I've spent couple days to try to figure out what's happening.
A little configurable warning (Screen is small, preview were disabled) in UI or in console could help for future people do not stumble across this nuance.
