### ISSUE TITLE
`git_status` icons are not showing up with the entries

### ISSUE THREAD

**Issue by hhn-pham** [nvim-telescope/telescope.nvim#1597]
### Description

Note: I have tried different fonts. But it shouldn't matter, seeing as git_icon_defaults render properly on all fonts. I'm using kitty, so I switched to wezterm. Same issue.

### Neovim version

```markdown
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
```

### Operating system and version

Arch Linux 5.15.7-227-tkg-pds

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `zoxide`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. Run `nvim -nu minimal.lua`
2. `cd` into a git repository and open any file.
3. `Telescope git_status`

### Expected behavior

To see diff icons where the blank areas would be.

### Actual behavior

See no icons instead:

Right terminal shows git status of the same local repo I am doing `Telescope git_status` on.

![2021-12-15_16-13-20](https://user-images.githubusercontent.com/33115327/146223417-197320ba-b04b-4989-87db-6495df84bf1c.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by l-kershaw** [comment]
I can't reproduce this using the default minimal config.

The only thing that I can think of is that your colorscheme is making the icons blend in with the background?
Can you run `:Telescope highlights`, type "TelescopeResultsDiff" and then take a screenshot?

**Comment by hhn-pham** [comment]
> The only thing that I can think of is that your colorscheme is making the icons blend in with the background? Can you run `:Telescope highlights`, type "TelescopeResultsDiff" and then take a screenshot?

I checked that too, it's definitely visible.

![2021-12-15_16-54-18](https://user-images.githubusercontent.com/33115327/146230173-a36eea81-a6e1-450e-b959-74c26f9516db.png)

**Comment by l-kershaw** [comment]
Hmm, I'm unsure then 😕
You haven't changed any of the options at all? Either in the `setup` call or the options passed to the picker?

**Comment by hhn-pham** [comment]
No, I tested with my current config minus any extra calls to telescope, just setup(), I removed lazy loading still the same. I guess if the behaviour is seen with the minimal config then it's a bug of some sort. I've experienced this since I started using Telescope for a few months now, don't think I ever got it to work.

**Comment by l-kershaw** [comment]
Since I can't reproduce when I disable all plugins except Telescope (and plenary), maybe this is somehow caused by one of your other plugins? (No idea how this would happen though) Can you still reproduce this without any other plugins?

Also, how are you calling the `git_status` picker? Are you using a mapping, or straight from command mode? (Might be helpful if you do a screen recording of this, if possible)

**Comment by hhn-pham** [comment]
Both minimal and full configs have this issue. Minimal config as provided, with only Telescope and plenary.

Here is issue shown with full configs (about 50+ plugins, but I can't see what would be conflicting with git calls, I can provide further configs if needed), also `$ git status` at the beginning just to show that it's a fairly standard repo with nothing special. In fact I tried this with many repos and the issue persists, this is my dotfiles repo:

https://user-images.githubusercontent.com/33115327/146273627-8fc99c8f-262d-48c5-adae-798d0b0e7dd9.mp4

This is with minimal configuration provided by the issue template, with the `nvim` data folder located in `/tmp/` so it shouldn't have anything to do with my setup. Using the same dotfiles repo:

https://user-images.githubusercontent.com/33115327/146273859-8f57175f-9c91-4ffa-a02e-dc31b6bf5286.mp4

**Comment by l-kershaw** [comment]
Maybe there is something in your git config that changes the output of the status command in a way that telescope doesn't handle?

What output do you get when you use the following command?
`git status -s -- .`

**Comment by hhn-pham** [comment]
Bingo. Color output was set to `always` for status. Switching to `auto` works. Thank you!
