### ISSUE TITLE
Telescope doesn't see ripgrep and fd

### ISSUE THREAD

**Issue by Nojpg** [nvim-telescope/telescope.nvim#1603]
### Description

Ripgrep and fd installed via cargo. Cargo folder added to $PATH also. Neovim installed via appimage. Idk mb this issue related to nvim more, but only on telescope I use cargo packages so. Appimage moved to /usr/local/bin/. 
Checked on suggested minimal config, same issue.

### Neovim version

```markdown
NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az65-618

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Linux 5.14.21-210.current #1 SMP PREEMPT Sun Dec 5 21:23:09 UTC 2021 x86_64 GNU/Linux Solus OS

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - ERROR: rg: not found. `live-grep` finder will not function without [BurntSushi/ripgrep](https://github.com/BurntSushi/ripgrep) installed.
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. get nvim from appimage
2. cargo install ripgrep --force
3. cargo install fd-find

### Expected behavior

OK for all deps

### Actual behavior

Doesn't see fd and rg

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by l-kershaw** [comment]
I'm assuming by "Telescope doesn't see ripgrep and fd" you mean that:

- you have ripgrep and fd installed
- `:Telescope find_files` doesn't use them

Is that right?

If so, can you check what the output of the following commands are:
`:echo executable("rg")` and `:echo executable("fd")`
These should both return 1 if you have installed things in a way that nvim can access.

**Comment by Nojpg** [comment]
> I'm assuming by "Telescope doesn't see ripgrep and fd" you mean that:
> 
> * you have ripgrep and fd installed
> * `:Telescope find_files` doesn't use them
> 
> Is that right?
> 
> If so, can you check what the output of the following commands are: `:echo executable("rg")` and `:echo executable("fd")` These should both return 1 if you have installed things in a way that nvim can access.

checked 
:echo executable("rg") and :echo executable("fd") both return 0
```:Telescope find_files``` work I think
![image](https://user-images.githubusercontent.com/15429565/146648258-a0aa752c-8ef2-43c2-980d-47c67f7fa53d.png)

Checked also if ripgrep will be installed via system package manages. Now Telescope see it. 
So as I understand neovim from appimage can't see cargo's packages? Or neovim at all can't see it?

**Comment by l-kershaw** [comment]
What do you mean by "see" or "can't see" here?

**Comment by Nojpg** [comment]
> What do you mean by "see" or "can't see" here?

There are packages in .cargo/bin path, but neovim from appimage doesn't resolve that

**Comment by Nojpg** [comment]
I resolved that issue. Problem in ```path```.
if in 
```echo $PATH
/home/user/.cabal/bin:~/.cargo/bin/...
```
i don't know whose fault, neovim or appimage package(I think appimage can't resolve properly) 
but if we change path to 
```echo $PATH
/home/user/.cabal/bin:/home/user/.cargo/bin/...
```
Everything will work.
