### ISSUE TITLE
`Actions.insert_i` exits insert mode after insertion

### ISSUE THREAD

**Issue by clason** [nvim-telescope/telescope.nvim#1608]
### Description

After https://github.com/neovim/neovim/commit/28134f4e78819c2bbf0344326b9d44f21eb0d736 (which changes the behavior of prompt buffers, in particular -- quite intentionally -- the following), `actions.insert_i` no longer remains in insert mode.

A possible simple fix is to add a `vim.cmd 'startinsert!'` after https://github.com/nvim-telescope/telescope.nvim/blob/5f37fbfa837dfee7ecd30f388b271f4a71c0a9e0/lua/telescope/actions/init.lua#L371

### Neovim version

```markdown
NVIM v0.7.0-dev+737-g818ae74ea
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

Use `require"telescope.builtin".symbols()` in insert mode.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by kylo252** [comment]
I'm not really sure how to reproduce this. It seems that I can actually call `require"telescope.builtin".symbols()` but it's looking for a hard-coded path, where I had to install https://github.com/nvim-telescope/telescope-symbols.nvim 😅 

Could you please describe the exact workflow? I feel like I'm supposed to trigger that call from insert-mode? otherwise, it's already starting fine for me. And I want to see if #1600 fixes this.
