### ISSUE TITLE
Telescope very slow performance on Neovim 0.6.0

### ISSUE THREAD

**Issue by wilkinson4** [nvim-telescope/telescope.nvim#1616]
### Description

I am having an issue with `git_files`, `live_grep` and `grep_string` telescope commands being terribly slow to load the preview window/files. This issue started happening once I upgraded to Neovim 0.6.0 whereas on Neovim 0.5.1 it works perfectly fine and is super snappy.

### Neovim version

```markdown
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.0.1 Apple Silicon

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. I have Neovim installed/managed via asdf.
2. I brew installed ripgrep via the `arch -arm64 brew install ripgrep` command.
3. When using the `git_files`, `live_grep` or `grep_string` commands in a larger project it is very slow.

### Actual behavior

The preview window opens up fast, but with nothing in it—then a couple seconds later the files will show up in the preview window. When typing in the preview window it takes a couple seconds to catch up with the input being typed.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  local M = {}

-- from telescope wiki
-- use git_files if in git project; fall back to find_files if not
M.project_files = function()
  local ok = pcall(require'telescope.builtin'.git_files, {})
  if not ok then require'telescope.builtin'.find_files({hidden = true}) end
end

local actions = require'telescope.actions'

require'telescope'.setup{
  defaults = {
    file_sorter = require'telescope.sorters'.get_fzy_sorter,
    generic_sorter = require'telescope.sorters'.get_fzy_sorter,
    -- prompt_prefix = '',  -- fixes using rsi in prompt but causes other issues
    mappings = {
      i = {
        ["<esc>"] = actions.close,
        ["<c-f>"] = actions.smart_send_to_qflist + actions.open_qflist,
        ["<a-a>"] = actions.select_all,
      },
    },
  },
}

U.keymap('n', '<leader>f', "<cmd>lua require'config.telescope'.project_files{}<cr>")
U.keymap('n', '<leader>F', "<cmd>lua require'telescope.builtin'.fd{}<cr>")

-- super search
U.keymap('n', '<leader>?', "<cmd>lua require'telescope.builtin'.live_grep{}<cr>") -- can't do regex
U.keymap('n', '<leader>/', "<cmd>lua require'telescope.builtin'.grep_string{ search = vim.fn.input('Rg> '), use_regex = true }<cr>")

-- super search for word under cursor
U.keymap('n', '<leader>*', "<cmd>lua require'telescope.builtin'.grep_string{}<cr>")

U.keymap('n', '<leader>b', "<cmd>lua require'telescope.builtin'.buffers{}<cr>")
U.keymap('n', '<leader>B', "<cmd>lua require'telescope.builtin'.current_buffer_fuzzy_find{}<cr>")

U.keymap('n', '<leader><leader>', "<cmd>lua require'telescope.builtin'.commands{}<cr>")
U.keymap('n', '<leader>K', "<cmd>lua require'telescope.builtin'.help_tags{}<cr>")

require('telescope').load_extension('fzf')

return M
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by l-kershaw** [comment]
I am very surprised that nvim 0.5.1 vs 0.6.0 has a negative performance impact for `telescope`.

Did you update anything else at the same time? e.g. `rg` or `telescope` itself?
If so, it would be helpful if you could bisect the git history of the relevant part to find the point that this negative performance impact happened.

**Comment by fdschmidt93** [comment]
As I understand you description and to clarify, only the preview has materially slowed down for you? If so, could you please try to deactivate treesitter and see how telescope then fares? Some users reported material improvements

```lua
require "telescope".setup {
  defaults = {
    preview = {
      treesitter = false
    }
  }
}
```

**Comment by wilkinson4** [comment]
Disabling treesitter in the preview window made a huge improvement in performance for me. Thank you! I wonder what changed between 0.5.1 and 0.6.0 that would've caused that. Is it trying to utilize treesitter on every file that exists in the preview window instead of just the one that is active maybe?

**Comment by fdschmidt93** [comment]
> Is it trying to utilize treesitter on every file that exists in the preview window instead of just the one that is active maybe?

I'd have to check once more, but IIRC previewing is pretty lazy already. It works by faking loading the file - the entire file is read with plenary and `vim.api.nvim_buf_set_lines` to a new scratch buffer onto which the tree-sitter parser for the filetype is attached. This only occurs once (and is then cached) for the to be previewed file. In other words, files not yet previewed don't have a preview buffer.

The window throughout all of this stays the same and should not have any impact.

I loosely recall some comment somewhere on the repo here that the parsing API of `nvim-treesitter` may have changed or something. Maybe that has anything to do with it? For me, I don't note a difference. I see two angles:

a) For some reason we parse slower than should
b) `nvim-treesitter` has a performance regression

It might very well be a) in case when you open the file in question treesitter parsing is fast.

**Comment by fernandofleury** [comment]
In my case, it gets extremely slow if the project has lots of files. Keeping the preview enabled for a smaller project (like 200 files) is completely fine. But having it in a project with over 4k files turns every keystroke into a 5 seconds wait period

**Comment by wilkinson4** [comment]
> > Is it trying to utilize treesitter on every file that exists in the preview window instead of just the one that is active maybe?
> 
> I'd have to check once more, but IIRC previewing is pretty lazy already. It works by faking loading the file - the entire file is read with plenary and `vim.api.nvim_buf_set_lines` to a new scratch buffer onto which the tree-sitter parser for the filetype is attached. This only occurs once (and is then cached) for the to be previewed file. In other words, files not yet previewed don't have a preview buffer.
> 
> The window throughout all of this stays the same and should not have any impact.
> 
> I loosely recall some comment somewhere on the repo here that the parsing API of `nvim-treesitter` may have changed or something. Maybe that has anything to do with it? For me, I don't note a difference. I see two angles:
> 
> a) For some reason we parse slower than should
> b) `nvim-treesitter` has a performance regression
> 
> It might very well be a) in case when you open the file in question treesitter parsing is fast.

I think it's probably a treesitter performance regression now that I have treesitter disabled when I open a file from the preview it takes a second or two to load it in a buffer.

**Comment by Shatur** [comment]
> In my case, it gets extremely slow if the project has lots of files. Keeping the preview enabled for a smaller project (like 200 files) is completely fine. But having it in a project with over 4k files turns every keystroke into a 5 seconds wait period

I experiencing the same, here is a separate issue about it: #1423

**Comment by felippemr** [comment]
In a project with about 300k files I am experiencing the same.

**Comment by felippemr** [comment]
Disabling treesitter made things way better!

**Comment by fdschmidt93** [comment]
There's some chatter on Gitter that apparently tree-sitter version has been bumped that tremendously improved performance for some users, which seems to have affected macOS users.

You might want to try with tree-sitter re-enabled.

**Comment by wilkinson4** [comment]
I actually ran `PackerUpdate` a few minutes ago and I'm still experiencing the same slowness plus some nodejs version detection issues now. I opened an issue on nvim-treesitter for the performance issues because I think it's probably their problem.
https://github.com/nvim-treesitter/nvim-treesitter/issues/2182

Also, in case anyone experiences the same asdf/nodejs version issues here is that link
https://github.com/nvim-treesitter/nvim-treesitter/issues/2181

**Comment by clason** [comment]
You need to rebuild neovim with the updated tree-sitter library; it's not an issue with any plugins.

**Comment by wilkinson4** [comment]
I'm using asdf to manage neovim's version, and I tried `asdf plugin remove neovim` followed by `asdf plugin add neovim` and `asdf install neovim 0.6.1`. This didn't resolve the issue for me.

**Comment by clason** [comment]
No, as I wrote, you need a nightly build, the performance mitigation didn't make it into 0.6.1.

**Comment by wilkinson4** [comment]
Ah. Thank you!

**Comment by scho7623** [comment]
I'm also working on a project with ~12K files and telescope's find_files is super slow. It takes >10 seconds to search for the file. Before telescope, I used to use FZF, and it finds files nearly instantly. Is there away to leverage FZF for telescope's find_files?

**Comment by fernandofleury** [comment]
@scho7623 I've disabled the treeviewer for the telescope preview, that ""fixed"" the issue
