### ISSUE TITLE
get_dropdown() with preview_width yields "Unsupported layout_config key" error

### ISSUE THREAD

**Issue by Melkster** [nvim-telescope/telescope.nvim#1623]
### Description

When calling `get_dropdown()` with `layout_config = { preview_width = *value*}` in the `defaults` table in `setup()` I get the error "Unsupported layout_config key for the center strategy: preview_width".

### Neovim version

```markdown
NVIM v0.7.0-dev+660-gd3585e0ec
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Manjaro Linux x86_64

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Press `<leader>f`

### Expected behavior

`find_files` dropdown menu appears

### Actual behavior

Error mentioned above (and then the menu appears)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  vim.api.nvim_set_keymap('n', '<leader>f', '<cmd>lua require"telescope.builtin".find_files(require("telescope.themes").get_dropdown())<CR>', {})
  require('telescope').setup {
    defaults = {
      layout_config = { preview_width = 80 },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
`preview_width` is a unique option that is only implemented for horizontal right now. It doesnt makes sense to implement it for dropdown because previewer width is handled by the actual width.

So this is not a bug, the error message just says that you have configured something wrong
```lua
require('telescope').setup {
    defaults = {
      layout_config = {
        horizontal = {
          preview_width = 80
        }
      },
    },
  }
```

You should read `:help telescope.defaults.layout_config` and `:help telescope.layout`

**Comment by Melkster** [comment]
I see. Yes, your suggested config solved the problem, thank you!

But why does putting `layout_config` directly under `defaults` like in the snippet below work with other layout strategies like horizonal?

```lua
require('telescope').setup {
  default = {
    layout_config = {
      preview_width = 80
    }
  }
}
```

It affects horizontal's preview width the same way as when I do it the way that you suggest:

```lua
require('telescope').setup {
  default = {
    layout_config = {
      horizontal = {
        preview_width = 80
      }
    }
  }
}
```

Is that a bug or intended behaviour?

**Comment by craigmac** [comment]
> So this is not a bug, the error message just says that you have configured something wrong. You are only allowed to put shared options at the top level of the layout_config table. 

Just got bitten by this when I tried:

```lua
require('telescope').setup({
  defaults = {
    layout_strategy = 'flex',
    layout_config = {
        height = 0.95,
        sorting_strategy = "ascending",
    },
  },
})
})
```

Which result in: 

```
Unsupported layout_config key for the flex strategy: sorting_strategy
```

@Conni2461 Nowhere in `:h telescope.defaults.layout` or `:h telescope.defaults.layout_config` does it mention that what I and OP did isn't allowed. Could you please add that to the docs somewhere in there, it would save others a lot of headaches trying to figure this out.
