### ISSUE TITLE
Change view of "Binary not found" in preview 

### ISSUE THREAD

**Issue by qubisc** [nvim-telescope/telescope.nvim#1626]
I have sensitive eyes and preview like seen in telescope when a file cannot be previewed are pain.
![image](https://user-images.githubusercontent.com/93098117/147465580-bf428ce2-f943-45ab-8ba3-20dd014cecf8.png)

Is there a way to disable the view?

**Comment by Conni2461** [comment]
I personally have this set set, to make it less noisy 

```lua
require("telescope").setup {
  defaults = {
    preview = {
      msg_bg_fillchar = " ",
    },
  }
}
```

**Comment by Conni2461** [comment]
`:help telescope.defaults.preview`

**Comment by qubisc** [comment]
@Conni2461 Hey, this worked very well. Thank you very much!:)
