### ISSUE TITLE
Frecency and Neoclip broke with commit 3dafcb4

### ISSUE THREAD

**Issue by yigothu** [nvim-telescope/telescope.nvim#1632]
### Description

Commit `3dafcb4` yesterday stopped all the “third-party” telescope extensions from running. 

Eg `:Telescope frecency` returns nothing. 

Reverting to the previous commit lets them run again. 

### Neovim version

```markdown
Nightly
```

### Operating system and version

Debian

### checkhealth telescope

```markdown
No problems found.
```

### Steps to reproduce

Can reproduce with just telescope, plenary and frecency loaded. 

### Actual behavior

Commit `3dafcb4` yesterday stopped all the “third-party” telescope extensions from running. 

Eg `:Telescope frecency` returns nothing. 

Reverting to the previous commit lets them run again. 

### Minimal config

```Lua
minimal.lua
```

**Comment by queensferryme** [comment]
+1 for this issue, config for reproduction:

```lua
require("telescope").setup {
    defaults = {
        layout_config = {
            scroll_speed = 2,
        },
    },
    pickers = {
        lsp_definitions = { theme = "dropdown" },
        lsp_implementations = { theme = "dropdown" },
        lsp_references = { theme = "dropdown" },
        lsp_document_symbols = { theme = "dropdown" },
    },
    extensions = {
        frecency = {
            show_unindexed = false,
        },
    },
}
require("telescope").load_extension("frecency")
require("telescope").load_extension("projects")
```

**Comment by GreatestOfAllTimee** [comment]
Yes, this issue has been discussed on PR [#1601](https://github.com/nvim-telescope/telescope.nvim/pull/1601#issuecomment-1001662342). 80% or more plugins that rely on [Telescope](https://github.com/nvim-telescope/telescope.nvim) experience the same problem.

**Comment by clason** [comment]
Note that this affects only the `:Telescope` user commands -- the Lua API, e.g., `require"telescope".extensions.frecency.frecency()`, still work fine.

**Comment by GreatestOfAllTimee** [comment]
> +1 for this issue, config for reproduction:
> 
This configuration should be done on the dev side.

**Comment by yigothu** [comment]
I confirm it works again now. Thanks!
