### ISSUE TITLE
setup.pickers options do not work

### ISSUE THREAD

**Issue by pedro757** [nvim-telescope/telescope.nvim#1635]
### Description

This does not set the `hidden` option
```lua
require('telescope').setup{
  pickers = {
    find_files = {
      find_command = { "fd", "--type", "f", "--strip-cwd-prefix" },
      hidden = true,
    },
  },
}
```
This works
```lua
require('telescope').setup{
  pickers = {
    find_files = {
      find_command = { "fd", "--type", "f", "--strip-cwd-prefix", "--hidden" },
    },
  },
}
```
But the docs says that there's a `hidden` option we can set

https://github.com/nvim-telescope/telescope.nvim/blob/9d0034df79506af0ee0f102f1f5c6eec59e20e90/doc/telescope.txt#L745-L767

`:lua require"telescope.builtin".find_files()`

### Neovim version

```markdown
NVIM v0.7.0-dev+761-g0d7a97224
```

### Operating system and version

Arch linux

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `git_worktree`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided
```

### Steps to reproduce

.

### Expected behavior

I expect with the `hidden` option shows the hidden files if true

### Actual behavior

The `hidden` option does not work.
The `find_command` option works

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by pedro757** [comment]
The problem is when I try to set the `find_command` option along with other options

**Comment by fdschmidt93** [comment]
If you pass `find_command`, then you should use `--hidden` or `-H` with `fd` in `find_command`. See `man fd`. Otherwise, `find_command` pretty much overrides `hidden`.

Cf. implementation here 

https://github.com/nvim-telescope/telescope.nvim/blob/9d0034df79506af0ee0f102f1f5c6eec59e20e90/lua/telescope/builtin/files.lua#L163-L180

Closing this as `wontfix`. While it maybe could be handled (it would have to work across `builtin.files` commands), I neither think any maintainer would work on this kind of refactoring nor is it an all too worthy undertaking since I'm sure there's edges all around.

**Comment by fdschmidt93** [comment]
Correcting myself: we keep this open as the docs could reflect this.
