### ISSUE TITLE
Telescope find_files freezes nvim when select big binary file(use previewer)

### ISSUE THREAD

**Issue by fcying** [nvim-telescope/telescope.nvim#1637]
### Description

when I use `Telescope find_files` select a big binary file(test file: unzip [ccls](https://github.com/fcying/tools/releases/download/tools/ccls_linux_amd64.zip), about 38M), nvim be freezes, nvim cpu 90+%.
wait several seconds, display `Binary cannot be previewed`

if disable previers`Telescope find_files previewer=false`, work fine, select  binary file not freeze nvim.

telescope version: master latest: 9d0034d

### Neovim version

```markdown
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az32-74
```

### Operating system and version

debian 11

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1 (rev 7cb211378a)
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. nvim -u init.lua
2. Telescope find_files
3. select ccls(freezes nvim, cpu 90+%)  
4. wait and quit nvim
5. nvim -u init.lua
6. Telescope find_files previewer=false
7. select ccls(work fine)

### Expected behavior

if select binary file, only display `Binary cannot be previewed`, not freeze nvim

### Actual behavior

freeze nvim

### Minimal config
init.lua
```Lua
local fn, cmd = vim.fn, vim.cmd
local root_dir = fn.fnamemodify(fn.resolve(fn.expand('<sfile>:p')), ':h')

cmd('set packpath=' .. root_dir .. '/plugged')
cmd('set runtimepath^=' .. root_dir .. '/plugged')
local install_path = root_dir .. '/plugged/pack/packer/opt/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
    Bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

cmd([[
    set mouse=n
    packadd packer.nvim
    nnoremap <space>pu :PackerSync<CR>
    nnoremap <space>pc :PackerCompile<CR>

    nnoremap <silent> ff :Telescope find_files previewer=false<CR>
    nnoremap <silent> fp :Telescope find_files<CR>
    set cmdheight=3
]])

local packer = require('packer')
local use = packer.use
packer.init({
    package_root = root_dir .. '/plugged/pack',
    compile_path  = root_dir .. '/plugged/plugin/packer_compiled.lua',
})

use {'wbthomason/packer.nvim', opt = true}
use 'nvim-lua/plenary.nvim'
use 'nvim-telescope/telescope.nvim'

if Bootstrap then
    packer.sync()
end


```
```

**Comment by Conni2461** [comment]
For me it spends 20 seconds in filetype detect (so a plenary issue). Because it reads the head (first line) of the file and looks for a shebang

**Comment by Conni2461** [comment]
fixed by https://github.com/nvim-lua/plenary.nvim/commit/cbaeb9fffc14e7e5687715987a94b4f410084560
