### ISSUE TITLE
Add Syntax highlighting to current_buffer_fuzzy_find() items

### ISSUE THREAD

**Issue by tami5** [nvim-telescope/telescope.nvim#164]
Hi there, is it possible to have syntax highlighting on result items?  I think it would be an awesome feature. 
Thanks

**Comment by dekelyi** [comment]
The docs says to have `bat` installed, which is a `cat` with syntax highlighting

**Comment by tami5** [comment]
Hey @dekelyi, I don't mean the preview facility, am referring to highlighting the search results items itself.

**Comment by OkanEsen** [comment]
Just set the highlight:

``` vim
highlight link TelescopeMatching ...
```

**Comment by tami5** [comment]
@OkanEsen not what I mean but thanks for your comment. filetype specific syntax highlighting

**Comment by OkanEsen** [comment]
Oh, my bad! That's currently not possible though.

**Comment by tjdevries** [comment]
There is a way you could do this:

1. If your current buffer uses treesitter, you can get the parser
2. You can find out which lines are displayed and get the highlights that the parser WOULD have done on those lines
3. Then, with those, you can apply them with nvim_buf_add_highlight

I don't have time to do this, but it should be possible for that situation. I don't have any guarantees though.

**Comment by Conni2461** [comment]
tj did this in https://github.com/nvim-telescope/telescope.nvim/commit/0b2c801978e9cfc9b6351fc9f037ff2ba93805bd but it requires treesitter.

Closing
