### ISSUE TITLE
Show cwd information in some pickers

### ISSUE THREAD

**Issue by SimonMandlik** [nvim-telescope/telescope.nvim#1647]
**Is your feature request related to a problem? Please describe.**

I think it could be helpful to display cwd for e.g. `find_files` and `live_grep` pickers. I tend to forget where I'm at when switchich between projects in tmux and it would be nice to have a remainder (my workflow almost always starts with invoking either telescope or nvim-tree)

**Describe the solution you'd like**

One of the easiest solutions seems to change the `Find Files` title to `Find Files (~/Projects/...)`

**Comment by Conni2461** [comment]
You can just do

```
lua require("telescope.builtin").find_files({ prompt_title = string.format("Find Files (%s)", vim.loop.cwd()) })

lua require("telescope.builtin").live_grep({ prompt_title = string.format("Live Grep (%s)", vim.loop.cwd()) })
```

**Comment by SimonMandlik** [comment]
Thank you for your help. Is it possible to shorten the path in case it is too long / the window is too short? By calling a similar procedure which shortens path e.g. in find_files

**Comment by Conni2461** [comment]
```
lua require("telescope.builtin").find_files({ prompt_title = string.format("Find Files (%s)", require("plenary.path"):new(vim.loop.cwd()):shorten()) })
```

**Comment by petobens** [comment]
@Conni2461 how can I make your snippet work with `cwd`? I tried:
```lua
lua require("telescope.builtin").find_files({ cwd = "..", prompt_title = string.format("Find Files (%s)", vim.loop.cwd())})
```
But the prompt title shows the child rather than the parent dir.. Thanks in advance!
