### ISSUE TITLE
normal mode keymap for move left move right

### ISSUE THREAD

**Issue by yueyingjuesha** [nvim-telescope/telescope.nvim#1659]
**Is your feature request related to a problem? Please describe.**
Sometimes the file name/function signature is very long that we can't see the entire entry

**Describe the solution you'd like**
add key l, h for moving to the entry left / right

**Describe alternatives you've considered**

**Additional context**

**Comment by fdschmidt93** [comment]
I think that would be extremely complicated (string vs float width, incrementing / decrementing) with likely subpar UX, where simple solutions probably suffice and fare better.
Something lik

```lua
local action_state = require "telescope.actions.state"

local print_display = function(prompt_bufnr)
  local entry = action_state.get_selected_entry()
  local str = type(entry.display) == "function" and entry:display() or entry.display
  print(str)
end
```

should do. Please let me know whether that works for you.

I'm closing this as `wontfix` as I don't see any maintainers working on this (as per usual, any maintainer is happy to reopen etc). I don't think my function warrants a dedicated `telescope.action` but if there's something cool, I'm very happy to review a PR.
