### ISSUE TITLE
previewer autocmd TelescopePreviewerLoaded line number only works after second action

### ISSUE THREAD

**Issue by weeman1337** [nvim-telescope/telescope.nvim#1661]
### Description

I want to display line numbers in the preview. To achieve that I've added that to my config

```
vim.cmd "autocmd User TelescopePreviewerLoaded setlocal number"
```

Unfortunately the numbers are not displayed initially for each file in the previewer.  
They appear if I select the file a second time in the previewer.

The example below uses `live_grep` but also applies to all other pickers.

### Neovim version

```markdown
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu 20.04.3 LTS

### checkhealth telescope

```markdown
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1 (rev 7cb211378a)
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. `nvim -u minimal.lua minimal.lua`
2. `:Telescope live_grep`
3. type `p`

### Expected behavior

- match displayed in previewer
- including line numbers

### Actual behavior

- match displayed
- no line numbers

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
vim.cmd "autocmd User TelescopePreviewerLoaded setlocal number"
```

**Comment by Conni2461** [comment]
can someone try https://github.com/nvim-telescope/telescope.nvim/pull/2005

Thanks :)

**Comment by akinsho** [comment]
Just gave it a try @Conni2461 and seems to work consistently now 👍🏿

**Comment by Conni2461** [comment]
Thanks for testing

**Comment by akinsho** [comment]
@Conni2461 now that this works consistently I've only now noticed that it will apply to all telescope windows (unsurprisingly) but I'm wondering if there's some way to distinguish the picker we are in at that point so I can essentially turn this behaviour on only for file related pickers an not for things like git status, commits etc.?
