### ISSUE TITLE
Inconvenient buffer name when path contains spaces.

### ISSUE THREAD

**Issue by SimonMandlik** [nvim-telescope/telescope.nvim#1662]
In the following scenario

```
❯ tree ~/With\ Space/
/Users/simon.mandlik/With\ Space/
└── test.txt

0 directories, 1 file
```

I `cd` into `With Space`, run `:Telescope find_files` and press `<CR>` on `./test.txt`. Then, `:echo expand('%')` returns `/Users/simon.mandlik//With space/./test.txt`. Then I run into problems like here: https://github.com/nvim-lualine/lualine.nvim/issues/533

In the same scenario where the name of the directory doesn't contain space it works fine as well as when I open the file with `:e` or e.g. [fzf-lua](https://github.com/ibhagwan/fzf-lua).

Is this a telescope problem or should I dig deeper? Thanks!

**Comment by Conni2461** [comment]
I know why. There is a bug in plenary.path with normalizing paths.

Btw this should be a BUG report! Not a "feature request" (like what)

**Comment by SimonMandlik** [comment]
Thank you. Should I report an issue in plenary then? I only found this https://github.com/nvim-lua/plenary.nvim/issues/250

**Comment by Neelfrost** [comment]
For me, it is not limited to paths with spaces, it also seems to be happening in paths containing $HOME.

**Comment by Conni2461** [comment]
> Should I report an issue in plenary then

Not really the active maintainers basically overlap

**Comment by Conni2461** [comment]
Just fixed in https://github.com/nvim-lua/plenary.nvim/commit/c54f77d409f476d457d1e1ba7615139c63937321

Closing for now. Feel free to open a bug report in the plenary repo if this still happens again. Thanks for your patients :)
