### ISSUE TITLE
Pressing arrow keys in insert mode temporarily disables other keys

### ISSUE THREAD

**Issue by SimonMandlik** [nvim-telescope/telescope.nvim#1665]
### Description

As the title says

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

### Operating system and version

macOS 12.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended        capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. Open e.g. `:Telescope find_files`
2. Write `"queery"`
3. Use the left arrow key to delete the extra `e`
4. Delete key (backspace) stopped working
5. `<C-w>` doesn't work either
6. Write any key
7. Everything works again 

### Expected behavior

I would expect insert mode in telescope to work as close as possible to the original neovim insert mode.

### Actual behavior

Described above

### Minimal config

```Lua
return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use { 'nvim-telescope/telescope.nvim',
    requires = 'nvim-lua/plenary.nvim',
    config = function()
      actions = require "telescope.actions"
      require('telescope').setup{
        defaults = { mappings = { i = {
          ["<Tab>"] = actions.toggle_selection + actions.move_selection_worse,
          ["<S-Tab>"] = actions.toggle_selection + actions.move_selection_better,
          ["<A-a>"] = actions.toggle_all
        }}}}
    end
  }
end)
```
```

**Comment by Conni2461** [comment]
This is a upstream bug that is fixed in the latest nightly.

A workaround for this is to disable prompt buffer type like this: `Telescope find_files prompt_prefix=`

Duplicated bug reports: https://github.com/nvim-telescope/telescope.nvim/issues?q=label%3Aupstream

Closing
