### ISSUE TITLE
Apply similar options like path_display to live_grep

### ISSUE THREAD

**Issue by SimonMandlik** [nvim-telescope/telescope.nvim#1666]
**Is your feature request related to a problem? Please describe.**
When using `live_grep` majority of result lines overflow (they contain both the file path and the line)

**Describe the solution you'd like**
Judging from the docs, `display_path` only works for `find_files` picker. It would be great to have something similar

**Comment by AbdullahDiaa** [comment]
You can just `path_display` option instead:

```
lua require('telescope.builtin').find_files({path_display = {"smart"}})
lua require('telescope.builtin').live_grep({path_display = {"shroten"}})
```

**Comment by Conni2461** [comment]
yep already works for live_grep

![image](https://user-images.githubusercontent.com/15233006/148683319-f2da94d2-5a8f-4e6e-b9f9-dffa2bcc7361.png)

See `:help telescope.defaults.path_display`

Note that there is a typo in the post above `path_display = {"shroten"}` should be `shorten`

Closing.
