### ISSUE TITLE
Cannot open files due to error in InsertLeave Autocommand

### ISSUE THREAD

**Issue by samr** [nvim-telescope/telescope.nvim#1672]
### Description

When I execute `find_files()` and then try to open a file to edit, I get an error message stating `Error detected while processing InsertLeave Autocommand: for '*':` followed by `E5107: Error loading lua [string ':lua']:]: invalid escape sequence near '*site'`.

I believe this was introduced in PR #1643 as I can fix it by reverting the way files are opened for edit in `telescope\actions\set.lua` on approximately line 135. Basically using the old way of `pcall(vim.cmd, string.format("%s %s", command, filename))` instead of the one with the InsertLeave autocommand.

Perhaps there is something specific to my configuration that I can change to make this work, but I'm not sure what it is.

### Neovim version

```markdown
NVIM v0.6.1, and latest nightly
NVIM v0.7.0-dev+858-gc7ffe406b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-430
```

### Operating system and version

Windows 10

### checkhealth telescope

```markdown
telescope: 
========================================================================
  - ERROR: No healthcheck found for "telescope" plugin.
```

### Steps to reproduce

1. pull up telescope to find a file
2. choose a file to edit
3. see the error (and the file does not open for edit)

### Expected behavior

1. pull up telescope to find a file
2. choose a file to edit
3. edit the file in the buffer

### Actual behavior

![image](https://user-images.githubusercontent.com/432659/148697934-fb2a2b53-6bda-436b-a956-fe7147623124.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]

-- This is very much a Linux favoring minimal.lua script. I am having issues getting this working on Windows. Packer does not seem to want to work with the non-existent packpath, even after I change it to something like 'C:/Temp' and when I point it at my existing packpath, I get a ton of errors.
```

**Comment by GreatestOfAllTimee** [comment]
I have the same issue https://github.com/nvim-telescope/telescope.nvim/pull/1643#issuecomment-1008350492.

https://user-images.githubusercontent.com/73665622/148699012-2139ba0e-7d96-4e70-9def-fd84f6c31bc9.mp4

**Comment by Conni2461** [comment]
I reverted it https://github.com/nvim-telescope/telescope.nvim/commit/c54fc1733e440ebe730f68a838c54c7c7e70e6fd
