### ISSUE TITLE
The preview update while typing in `Telescope help_tags` stop work 

### ISSUE THREAD

**Issue by anuvyklack** [nvim-telescope/telescope.nvim#1692]
### Description

After 2bfc0eb while searching help tag with `Telescope help_tags` the preview is not updated while typing. Only when going up or down in the list.

### Neovim version

```markdown
NVIM v0.7.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

pop-os 21.10

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided
```

### Steps to reproduce

type `:Telescope help_tags` and start searching anything.

### Actual behavior

The preview window is not updated.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by l-kershaw** [comment]
Do you get any messages when this problem occurs (i.e. is there any output from `:messages`)?

**Comment by anuvyklack** [comment]
No. Nothing.

**Comment by l-kershaw** [comment]
I've been able to reproduce this problem using pickers other than `help_tags` too, and I think this should be fixed by #1693.
If anyone experiencing this issue could test that PR, then that would be great 🙂

**Comment by koengommers** [comment]
I also have this issue, for all pickers. Would love to test the pull request, but how do I go about letting Packer check it out?

**Comment by jamestrew** [comment]
I also started experiencing this behavior. Not exclusive to `help_tags`. Also get it in `git_files` and `treesitter_symbols` maybe others but not sure.
I get this warning after typing two characters (weird?) into the `help_tags`search and nowhere else:
`[telescope] [WARN  21:16:42] ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1007: no line found at row -1048 in buffer 40`

@l-kershaw I checkout #1693 and that looks to have cleared everything up. 

@koengommers if you have the github CLI, you can try the PR by running `gh pr checkout 1693` where telescope is installed (by default I think it's `~/.local/share/nvim/pack/packer/start/telescope.nvim`, replace `start` with `opt` if it's lazy loaded). If you don't have gh CLI you gotta follow this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
