### ISSUE TITLE
'git_create_branch' not functional

### ISSUE THREAD

**Issue by barrett-ruth** [nvim-telescope/telescope.nvim#1699]
### Description

telescope action 'git_create_branch' does not allow user to enter branchname when prompted

### Neovim version

```markdown
NVIM v0.7.0-dev+850-ge92b81633
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 11.5

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `fzy_native`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. Be in git repo
2. nvim -nu minimal.lua
3. :lua require 'telescope.builtin'.git_branches()
4. \<esc> to go into normal mode
5. press \<c-a>, the default git_create_branch binding
6. Unable to type branch

### Expected behavior

Prompt pops up and one can actually type branch into the prompt

### Actual behavior

Prompt with "Please enter the name of the new branch to create" pops up.
Unable to enter branch name or type at all -- as if nothing was pressed
![image](https://user-images.githubusercontent.com/62671086/149875866-f36d47e7-1b31-4173-af81-f797d4d73807.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by l-kershaw** [comment]
From your screenshot, it looks like your Telescope prompt is entry, so there is no name to give the newly created branch.

**Comment by barrett-ruth** [comment]
Thanks!
I didn't understand the workflow for creating a branch would first be to type the name in *and then* press \<c-a>, rather than press \<c-a> and be prompted for entry on the cmdline.
My mistake.
