### ISSUE TITLE
Clear preview window when no results are available

### ISSUE THREAD

**Issue by simonmandlik** [nvim-telescope/telescope.nvim#1702]
In `telescope.nvim` repo:

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/16707112/150175565-ef1bd9db-8724-46b5-9384-26ee2acf8040.png">

Wouldn't it be nice if the preview window got cleared?

**Comment by Conni2461** [comment]
Implemented here: https://github.com/nvim-telescope/telescope.nvim/pull/2004

Could someone test it?

**Comment by Conni2461** [comment]
Merged in current `dev` branch. See #1938 for more information when it will be applied to master
