### ISSUE TITLE
List source files from compile databases for C/C++ projects

### ISSUE THREAD

**Issue by shrkamat** [nvim-telescope/telescope.nvim#1711]
**Is your feature request related to a problem? Please describe.**
Firstly thanks for the plugin, it's become integral part of my workflow. Especially `lsp_references` is greatly improving my dev experience.

I majorly work on large C/C++ code bases (of the order of 10GB source files) any solution to find files in such large codebases will be slow. However most modern build systems support generation of [compile database](https://clang.llvm.org/docs/JSONCompilationDatabase.html) this database (json) file   

**Describe the solution you'd like**
A simple json query like `jq '.[].file' build/compile_commands.json` should list all project files. 

I know there is already solution for `git_files` but again in by case atleast file are split into multiple git repos then brohgt together with [git-repo](https://gerrit.googlesource.com/git-repo/) tool (similar to git submodules) 

Would it need a newer command similar to `find_files` say `project_files` to run [jq](https://stedolan.github.io/jq/). ? Or can I customize find_files ? 

P.S. I have never customized Telescope.

**Describe alternatives you've considered**
NA

**Additional context**
`jq` results on [qtbase](https://github.com/qt/qtbase) (one of the smaller sub project)
![jq vs rg](https://i.imgur.com/0TkBc2S.png)

Above command is run on less than 5% of code base that I work on. Results are much better for larger code bases.

There are subtle differences though, 
| rg | jq |
| :---: | :---: |
| list all files (even if file is not used in project)** | lists only project enabled files (compiled files) |
|output is only string| output is quoted string|
|output is prefixed with current dir| output is relative path from curent dir </br>OR <br> it can be configured to provide absolute path to files | 
|header and source files are both listed| only source files are listed##|
|files are listed as per directory listing | files are listed as per compilation order |

** This is most often the case in compiled languages 
\#\# This is a disadvantage, but for the performance gain I can live with this LSP provides mechanism to [jump to header file from source](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/clangd.lua#L53)

**Comment by Conni2461** [comment]
Yeah we would not ship custom solutions. But you can either write yourself a small picker yourself or this should work
```
lua require("telescope.builtin").find_files({ find_command = { "jq", "-r", ".[].\"file\"", "build/compile_commands.json" } })
```
