### ISSUE TITLE
Pickers do not use their own settings when invoked through `builtin.builtin` picker.

### ISSUE THREAD

**Issue by sonata-chen** [nvim-telescope/telescope.nvim#1714]
### Description

https://github.com/nvim-telescope/telescope.nvim/blob/0011b1148d3975600f5a9f0be8058cdaac4e30d9/lua/telescope/builtin/internal.lua#L92-L100

Because `opts` is passed to the function, the selected picker will use the same setting as `builtin.builtin` picker's. 
Maybe we can change these two lines to 

``` lua
 require("telescope").extensions[ext][func]() 
 -- skip
 require("telescope.builtin")[selection.text]() 
``` 

so the selected picker will behave as if it is invoked manually. ( through `:Telescope help_tags`)
Or maybe it is not a bug. Is there any reasons you decide to pass `opts` to the selected picker?

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
```

### Operating system and version

Arch linux 5.16.2-zen1-1-zen

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. `nvim -u minimal.lua`
2. `:Telescope builtin`
3. select a picker (help_tags)
4. `:Telescope help_tags`

### Actual behavior

skip

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup(
    {
      -- use different theme for builtin picker
      pickers = {
        builtin = {
          theme = 'dropdown',
          previewer = false,
        },
      },
    }
  )
  require('telescope').load_extension('fzf')
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by NXTaar** [comment]
+1. I can't assign options to specific picker, it just skips it inside the pickers.lua file
https://github.com/nvim-telescope/telescope.nvim/blob/f262e7d56d37625613c5de0df5a933cccacf13c5/lua/telescope/pickers.lua#L76

just because of
https://github.com/nvim-telescope/telescope.nvim/blob/f262e7d56d37625613c5de0df5a933cccacf13c5/lua/telescope/config.lua#L9 https://github.com/nvim-telescope/telescope.nvim/blob/f262e7d56d37625613c5de0df5a933cccacf13c5/lua/telescope/config.lua#L67

`_TelescopeConfigurationValues` value is never assigned and is always empty object

so this code in the config doesn't work
```lua
    setup{
        pickers = {
            buffers = {
                previewer = false,
                theme = 'ivy',
                mappings = {
                    i = {
                        ["<C-d>"] = actions.delete_buffer + actions.move_to_top,
                    },
                    n = {
                        ["d"] = actions.delete_buffer + actions.move_to_top,
                    }
                }
            }
        }
    }
```

**Comment by sonata-chen** [comment]
> so this code in the config doesn't work

I'm not sure why it doesn't work for you. Maybe you have something wrong in your config files.
Pickers do use their own settings as long as they are not invoked through `builtin.builtin` picker.

---
```
pickers = {
    buffers = {
        previewer = false,
        theme = 'ivy'
    }
}
```
![image](https://user-images.githubusercontent.com/59016625/153862542-69b89720-3421-42ca-9476-62aa509eddef.png)

---
```
pickers = {
    buffers = {       
        theme = 'ivy'
    }
}
```

![image](https://user-images.githubusercontent.com/59016625/153862820-d41e984d-ec26-425b-aa27-ff47280eb763.png)

**Comment by Conni2461** [comment]
This is a deliberate decision that pickers will prefer the options that were passed to `builtin.builtin` so that there isn't a theme change.

@NXTaar s issue is completely unrelated and shouldn't be here. Please open a separate issue.
