### ISSUE TITLE
Add `tv` as a csv previewer

### ISSUE THREAD

**Issue by alexhallam** [nvim-telescope/telescope.nvim#1716]
**Is your feature request related to a problem? Please describe.**
I am frustrated when csv files use `cat` or `bat`

**Describe the solution you'd like**
I wrote `tv` in Rust. I would like help make this an option as a previewer for csv file types. Just point me in the right direction.

**Describe alternatives you've considered**
`tv` has become a popular cli for csv file previewing. I think it could be a good fit here.

**Additional context**
See examples on my readme. I compare `cat` and `column` vs `tv` in a number of different situations.  https://github.com/alexhallam/tv

**Comment by fdschmidt93** [comment]
There's two options here:

1) `:h telescope.defaults.preview` and then see hooks, in your case, filetype_hooks. You'd capture and potentially parse the output of `tv` and then put it into the buffer via a function.

```lua

require "telescope".setup {
  defaults = {
    preview = {
      filetype_hook = function(filepath, bufnr, opts)
      ... -- see example in docs
      end
    }
  }
}
```

2) Have a joint buffer and terminal previewer, similar to what I'm doing in this PR https://github.com/nvim-telescope/telescope-file-browser.nvim/pull/74, typically with the advantage of having output automatically highlighted as you want to. I'll work on that PR tonight, maybe this can be generalized a bit (clean up & switch to terminal previewer condition) and then put into the wiki.

Buffer and terminal previewers are two separate things, primarily by how they are created and how some of the actions (eg scrolling) work.

**Comment by Conni2461** [comment]
Closing because we will not gonna add such a previewer, even though the tool is written in rust and looks cool and i probably gonna use it outside of telescope myself, but this can be done with configurations.

Thanks for sharing tho :)
