### ISSUE TITLE
See file name on search

### ISSUE THREAD

**Issue by imalexlab** [nvim-telescope/telescope.nvim#1720]
When I'm searching for a file, the path may be long and is hiding the file name.

I would like to be able to see the name (maybe on top of the preview?) of the file under cursor who is previewed.

**Comment by fdschmidt93** [comment]
See `:h telescope.defaults.dynamic_preview_title`

so

```lua

require "telescope".setup { defaults = { dynamic_preview_title = true } }

```

should do the trick.

**Comment by imalexlab** [comment]
Thanks! I also had to change `path_display = {"truncate"}` as the preview title is the long path, not the filename unfortunately so it can be hidden when the path is too long

**Comment by fdschmidt93** [comment]
Glad it works! I guess we can close this? Let me know otherwise in case there's more to discuss here.
