### ISSUE TITLE
Open file error after updated to recent 

### ISSUE THREAD

**Issue by rickywu** [nvim-telescope/telescope.nvim#1724]
### Description

Open file or quit after select cause E5108

### Neovim version

```markdown
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Win 10

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====

## Telescope Extension: `frecency`
  - INFO: No healthcheck provided

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `project`
  - INFO: No healthcheck provided

## Telescope Extension: `zoxide`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. open find_files
2. select for press ESC

### Expected behavior

open file

### Actual behavior

E5108: Error executing lua ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:458: We couldn't mkdir: E:\Download\d:
stack traceback:
	[C]: in function 'error'
	...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:458: in function 'mkdir'
	...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:591: in function 'touch'
	...ker\opt\telescope.nvim/lua/telescope/actions/history.lua:170: in function 'init'
	...ker\opt\telescope.nvim/lua/telescope/actions/history.lua:76: in function 'handler'
	...acker\opt\telescope.nvim/lua/telescope/actions/state.lua:47: in function 'get_current_history'
	...packer\opt\telescope.nvim/lua/telescope/actions/init.lua:184: in function <...packer\opt\telescope.nvim/lua/telescope/actions/init.lua:183>
	...k\packer\opt\telescope.nvim/lua/telescope/actions/mt.lua:23: in function 'key_func'
	...ack\packer\opt\telescope.nvim/lua/telescope/mappings.lua:236: in function 'execute_keymap'
	[string ":lua"]:1: in main chunk

### Minimal config

```Lua
  defaults = {
    -- Default configuration for telescope goes here:
    -- config_key = value,
    mappings = {
      i = {
        -- map actions.which_key to <C-h> (default: <C-/>)
        -- actions.which_key shows the mappings for your picker,
        -- e.g. git_{create, delete, ...}_branch for the git_branches picker
        ["<C-h>"] = "which_key"
      }
    }
  },
  pickers = {
    -- Default configuration for builtin pickers goes here:
    -- picker_name = {
    --   picker_config_key = value,
    --   ...
    -- }
    -- Now the picker_config_key will be applied every time you call this
    -- builtin picker
  },
  extensions = {
    -- Your extension configuration goes here:
    -- extension_name = {
    --   extension_config_key = value,
    -- }
    -- please take a look at the readme of the extension you want to configure
  }
}
```

**Comment by l-kershaw** [comment]
I can't reproduce this on my Windows 10 machine.

Could bisect your "minimal config" to see what (if any) of your configuration options or extensions cause this?
For example, I doubt the `prompt_prefix` or the `selection_caret` is causing this sort of problem, so removing it from the "minimal config" might make it easier to find where the problem is.

**Comment by rickywu** [comment]
> I can't reproduce this on my Windows 10 machine.

I changed to 
```
function config.telescope()
        if not packer_plugins["sqlite.lua"].loaded then
        vim.cmd [[
            let g:sqlite_clib_path = 'D:/DevTools/sqlite/sqlite3.dll'
            packadd sqlite.lua
        ]]
        end

        if not packer_plugins["telescope-fzf-native.nvim"].loaded then
                vim.cmd([[packadd telescope-fzf-native.nvim]])
        end

        if not packer_plugins["telescope-project.nvim"].loaded then
                vim.cmd([[packadd telescope-project.nvim]])
        end

        if not packer_plugins["telescope-frecency.nvim"].loaded then
                vim.cmd([[packadd telescope-frecency.nvim]])
        end

        if not packer_plugins["telescope-zoxide"].loaded then
                vim.cmd([[packadd telescope-zoxide]])
        end

require('telescope').setup{
  defaults = {
    -- Default configuration for telescope goes here:
    -- config_key = value,
    mappings = {
      i = {
        -- map actions.which_key to <C-h> (default: <C-/>)
        -- actions.which_key shows the mappings for your picker,
        -- e.g. git_{create, delete, ...}_branch for the git_branches picker
        ["<C-h>"] = "which_key"
      }
    }
  },
  pickers = {
    -- Default configuration for builtin pickers goes here:
    -- picker_name = {
    --   picker_config_key = value,
    --   ...
    -- }
    -- Now the picker_config_key will be applied every time you call this
    -- builtin picker
  },
  extensions = {
    -- Your extension configuration goes here:
    -- extension_name = {
    --   extension_config_key = value,
    -- }
    -- please take a look at the readme of the extension you want to configure
  }
}

end
```

Not resolved, but the same config can't reproduce in my WSL

**Comment by rickywu** [comment]
I just tried with default conf with only one plugin, packer is in nvim-data\site\pack\packer\start\packer.nvim

config/nvim/lua/plugins.lua:
```
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function()
use {
  'nvim-telescope/telescope.nvim',
  requires = { {'nvim-lua/plenary.nvim'} }
}
end) 
```

init.lua:
```
require('plugins')
```

**Comment by Conni2461** [comment]
This is probably happening because of history.
See `:help telescope.defaults.history`. The default path is `stdpath("data")/telescope_history`

To what did you set `XDG_DATA_HOME`?

**Comment by rickywu** [comment]
XDG_DATA_HOME set as D:\Neovim, nvim-data is D:\Neovim\nvim-data
XDG_CONFIG_HOME also set as D:\Neovim, nvim is in D:\Neovim\nvim

**Comment by fdschmidt93** [comment]
Closing this as stale; should the issue persist, please reopen with fully reproducible steps on a _minimal_ init lua (preferably ours).

**Comment by Conni2461** [comment]
I dont think this should have been closed as stale because it was stale from my side. Its a valid issue i just didn't have anything new to add at the time being.

I just merged a PR in plenary https://github.com/nvim-lua/plenary.nvim/pull/324 (its a plenary issue) that might improve on this issue. I dont have a windows machine so i can't test this. So i have to ask you if you can retest with the newest plenary version. (Make sure you update it).

Thanks :)

**Comment by rickywu** [comment]
I think it's because of env var XDG_DATA_HOME, because I just remove it then works well
I'll test and feedback

**Comment by Conni2461** [comment]
Did you have time testing it `XDG_DATA_HOME` set to `D:\ ...`

**Comment by Conni2461** [comment]
Now its time to close it as stale. I just have to assume the merged plenary PR fixed the issue, or no longer have intentions on setting this env var like that.
