### ISSUE TITLE
more select options

### ISSUE THREAD

**Issue by ZhiyuanLck** [nvim-telescope/telescope.nvim#1725]
There are only `select_default`, `select_horizontal`, `select_vertical`, `select_tab`, but sometime I want to specify the position more precisely, such as open left, right, or other way using vim commands `abo, bel, to, bo` etc.

So can we add more options to support these commands or an option to support custom open commands?

**Comment by ZhiyuanLck** [comment]
Well, I patch it by myself by adding extra actions. It is better if the map [here](https://github.com/nvim-telescope/telescope.nvim/blob/f285599440fcdbf97a7f44d120d403c80316f576/lua/telescope/actions/set.lua#L67-L72) can add more items:

- open on the top: `topleft split`
- open on the bottom: `botright split`
- open on the left: `vert topleft split`
- open on the right: `vert botright split`

**Comment by l-kershaw** [comment]
There is already an option for passing custom commands here, using `action_set.edit` (which is what the actions you mentioned are defined using).
For example, the following mapping always opens a full-height vertical split:
```lua
require'telescope'.setup({
  defaults = {
    mappings = {
      n = {
        ["<M-v>"] = function(prompt_bufnr)
          return require'telescope.actions.set'.edit(prompt_bufnr,"to vnew")
        end,
      },
      i = {
        ["<M-v>"] = function(prompt_bufnr)
          return require'telescope.actions.set'.edit(prompt_bufnr,"to vnew")
        end,
      },
    },
  },
})
```

**Comment by igrep** [comment]
I found the mapping doesn't work with `builtin.buffers`. Hitting `<C-h>` etc when opening `Telescope buffers`, I get the error `There was no associated buffer command`, [raised here](https://github.com/nvim-telescope/telescope.nvim/blob/6258d50b09f9ae087317e392efe7c05a7323492d/lua/telescope/actions/set.lua#L81):

![image](https://user-images.githubusercontent.com/227057/231029848-76af7737-9cf1-4e5e-a3f9-277ab7398328.png)

Here is my configuration of telescope:

```lua
local hjkl_mappings = {
  ["<C-h>"] = function(prompt_bufnr)
    return require'telescope.actions.set'.edit(prompt_bufnr,"leftabove vnew")
  end,
  ["<C-j>"] = function(prompt_bufnr)
    return require'telescope.actions.set'.edit(prompt_bufnr,"rightbelow new")
  end,
  ["<C-k>"] = function(prompt_bufnr)
    return require'telescope.actions.set'.edit(prompt_bufnr,"leftabove new")
  end,
  ["<C-l>"] = function(prompt_bufnr)
    return require'telescope.actions.set'.edit(prompt_bufnr,"rightbelow vnew")
  end,
}
require('telescope').setup{
  defaults = {
    -- Default configuration for telescope goes here:
    -- config_key = value,
    mappings = {
      n = hjkl_mappings,
      i = hjkl_mappings,
    }
  },
  pickers = {
    -- Default configuration for builtin pickers goes here:
    -- picker_name = {
    --   picker_config_key = value,
    --   ...
    -- }
    -- Now the picker_config_key will be applied every time you call this
    -- builtin picker
  },
  extensions = {
    -- Your extension configuration goes here:
    -- extension_name = {
    --   extension_config_key = value,
    -- }
    -- please take a look at the readme of the extension you want to configure
  }
}
```
