### ISSUE TITLE
fuzzy find line of current file

### ISSUE THREAD

**Issue by ZhiyuanLck** [nvim-telescope/telescope.nvim#1726]
How can I write a picker to fuzzy filter the lines of current file or all opened file?

**Comment by Conni2461** [comment]
`:Telescope current_buffer_fuzzy_find`

Also this is not a place to ask questions. Please use gitter or matrix. Or consult the documentation. This is a good place to start for developers: https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md
