### ISSUE TITLE
Picker autocommands throws error `cursor position outside buffer`

### ISSUE THREAD

**Issue by daangoossens22** [nvim-telescope/telescope.nvim#1727]
### Description

When changing previewers for the autocommands picker, it sometimes will throw the error `Error executing vim.schedule lua callback: ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:933: Cursor position outside buffer`. Looking at the source code this error is thrown when setting the cursor position in the previewer window.

Observations:
- It usually happens when changing the contents of the previewer
- Mostly happens when changing to a previewer with a lot of lines in it and immediately selecting the lines further at the bottom of the previewer. (e.g. augroup filetypedetect)
- When a previewer of an augroup has already been shown before, it doesn't happen as often (e.g. selecting the first line of augroup filetypedetect and then selecting the last line of filetypedetect doesn't throw an error while selecting the last line immediately does throw it)

Maybe related to: #957

### Neovim version

```markdown
NVIM v0.7.0-dev+963-g082ff2190
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az32-759

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

5.16.3-arch1-1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. type `:Telescope autocommands`
3. type `<C-n>` to go to the next entry (I've also been able to reproduce it by fuzzy finding for `'lua`)

### Expected behavior

Throws no error and have the previewer scrolled to the selected line from the results pane

### Actual behavior

Throws error and doesn't scroll the previewer (if it wasn't already in the correct spot)
![bug](https://user-images.githubusercontent.com/62295482/151669573-ce5cf5f2-b122-4351-9c4c-26b2447f61a5.gif)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by asmodeus812** [comment]
I also experience the same issue with telescope + lsp for example buf.outgoing_calls()

**Comment by Conni2461** [comment]
@asmodeus812 can you please open a new issue. thanks
