### ISSUE TITLE
Client-side code actions

### ISSUE THREAD

**Issue by nanotee** [nvim-telescope/telescope.nvim#1728]
**Is your feature request related to a problem? Please describe.**
https://github.com/neovim/neovim/pull/14115 and https://github.com/neovim/neovim/pull/16101 added the ability to define client-side commands for the built-in LSP client. However, from what I understand, `:Telescope lsp_code_actions` does not take `client.commands` and `vim.lsp.commands` into account

**Describe the solution you'd like**
I'd like Telescope to match the behavior `vim.lsp.buf.code_action()` and execute client-side code actions

**Describe alternatives you've considered**

**Additional context**

**Comment by Conni2461** [comment]
I suggest using `vim.lsp.buf.code_action()` and using something like https://github.com/nvim-telescope/telescope-ui-select.nvim to get the telescope ui for it.

I already fantasized with removing `lsp_code_actions` because its just a worse duplication of `vim.lsp.buf.code_action()`

**Comment by nanotee** [comment]
Thank you for the quick reply. I agree that using `vim.lsp.buf.code_action()` directly is probably the best solution here. I do that myself but someone encountered this issue while using one of my plugins so I thought I'd report it here

**Comment by Conni2461** [comment]
code_actions where removed from telescope in https://github.com/nvim-telescope/telescope.nvim/pull/1866

See `:help telescope.changelog-1866` for more information
