### ISSUE TITLE
Setting previewer option doesn't work with lsp_document_symbols

### ISSUE THREAD

**Issue by krkhan** [nvim-telescope/telescope.nvim#173]
Trying this but it's not working; still getting the vim-buffer as previewer for `lsp_document_symbols`.

```
local previewers = require('telescope.previewers')
local telescope = require('telescope')
telescope.setup {
  defaults = {
    use_less = false,
    previewer = previewers.bat_maker,
    mappings = {
...
      },
    },
  }
}
```

**Comment by tjdevries** [comment]
Oh, it won't work here -- you need to do it to where you are calling the builtin.

You can't specify a "default previewer" for everything -- that doesn't make sense. Different things need to be displayed differently.

`require('telescope.builtin').find_files { previewer = <put something here> }`

**Comment by krkhan** [comment]
that works, thanks!

**Comment by krkhan** [comment]
actually that doesn't for lsp_document_symbols, with the following I'm still getting vim buffer for preview

```
nmap <C-K> <cmd>lua require('telescope.builtin').lsp_document_symbols{ previewer = require('telescope.previewers').bat_maker }<CR>
```

**Comment by Conni2461** [comment]
Okay previewer got completely rewritten but even back in the day, `bat_maker` wasn't a previewer but just a function to determine `bat` options.
We now can define previewers on a setup level and documentation exists. That are the defaults and valid previewers can be found [here](https://github.com/nvim-telescope/telescope.nvim#previewers)
```lua
require('telescope').setup{
  defaults = {
    file_previewer = require'telescope.previewers'.cat.new, 
    grep_previewer = require'telescope.previewers'.vimgrep.new,
    qflist_previewer = require'telescope.previewers'.qflist.new, 
  }
}
```

You can also define previewers on a function level with an actual previewer: `:lua require('telescope.builtin').lsp_document_symbols{ previewer = require'telescope.previewers'.vimgrep.new({}) }`

So closing. Feel free to reopen if this is not what you are looking for
