### ISSUE TITLE
Slow file preview for csharp files

### ISSUE THREAD

**Issue by Anakael** [nvim-telescope/telescope.nvim#1733]
### Description

Scrolling through csharp files works slowly.
It freezes only with first scroll through file (so if scroll up and after down it will be fine).
For other files (like lua) works fine

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
```

### Operating system and version

ArchLinux

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `file_browser`
  - INFO: No healthcheck provided
```

### Steps to reproduce

0. Enable preview
1. Open C# project
2. Open file_browser (or live_grep)
3. Scroll through .cs files

### Expected behavior

Not freezing

### Actual behavior

Freezing when scroll through C# files.

### Minimal config

```Lua
use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'
use { 'nvim-telescope/telescope.nvim', requires = {'nvim-lua/plenary.nvim'}}
use {'nvim-telescope/telescope-fzf-native.nvim', run = 'make' }
use { "nvim-telescope/telescope-file-browser.nvim" }

require('telescope').setup()
require('telescope').load_extension('file_browser')
```

**Comment by tami5** [comment]
This isn't really a but with telescope but rather with the tree sitter . I had similar issue with swift tree sitter, it indeed freezed everything. Maybe something can be done to avoid this but I don't think it's worth because it relates to special cases like swift and c#.

**Comment by Conni2461** [comment]
You can disable treesitter highlighting in telescope preview, or only enable it for a specific set of filetypes. See `:help telescope.defaults.preview`

**Comment by Anakael** [comment]
Ok, I'll try.

**Comment by Anakael** [comment]
I've disabled treesitter highlighting and now its works fine. I'll open issue in treesitter.

**Comment by Conni2461** [comment]
FYI treesitter performance of nightly is way better than on 0.6.1
