### ISSUE TITLE
Unignore the ignored with a noignore anti-ignore pattern in .noignore

### ISSUE THREAD

**Issue by xbc5** [nvim-telescope/telescope.nvim#1734]
**Is your feature request related to a problem? Please describe.**
I am unable to find_files that are `.gitignored` without using `noignore`. There are times when I need frequent access to such files, but don't want to search the entire tree of other heavy directories (node_modules).

One such example is a repo I am creating to prototype HTML, CSS, and JS. I have script to set up a scratch directory that I work in. This scratch directory should not be tracked, but I cannot use Telescope on it without `noignore`.

**Describe the solution you'd like**
A whitelist:
1. a `.telescope` in the project root, with a `noignore` option: a list of glob or Regex patterns; or simply a `.noignore`;
2. a whitelist global configuration option that accepts a list of glob or Regex patterns;

**Describe alternatives you've considered**
Using `noignore`; :e , notepad.

**Comment by Conni2461** [comment]
You can set `file_ignore_patterns` to always ignore `node_modules` then you can use `Telescope find_files no_ignore=true` again.

see `:help telescope.defaults.file_ignore_patterns`

We can't do a global `passlist` because `fd` or `rg` are already ignoring on default

**Comment by Conni2461** [comment]
I take that thumbs up as accepted answer and would close this issue. Feel free to reopen

**Comment by marcelarie** [comment]
This will be really useful if possible.
