### ISSUE TITLE
Show tracked files in find_files and live_grep

### ISSUE THREAD

**Issue by timsofteng** [nvim-telescope/telescope.nvim#1738]
### Description

I've init git repo for dotfiles as Drew described.
All files in .gitignore.

*

Then add files to git with `git add -f path/to/file`

https://drewdevault.com/2019/12/30/dotfiles.html

How can I see my staged files with find_files and live_grep in Telescope?

BTW `nvim-tree` show files correctly.
![image](https://user-images.githubusercontent.com/51912173/153236158-bfc682e3-d7a3-4256-8d94-3df4060df1be.png)

### Neovim version

```markdown
0.6.1
```

### Operating system and version

Void Linux

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====
```

### Steps to reproduce

1. Added all files to gitignore.
2. Start to track some files with `git add -f some.file`

### Expected behavior

Want to see tracked files in pickers

### Actual behavior

Picker doesn't display any files.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by l-kershaw** [comment]
I don't think there is a way to do this for `find_files` and `live_grep`, as I can't see any options for `ripgrep` to only show tracked files. The closest option I can see is the `--no-ignore` option which is used in `find_files` as `no_ignore`.

Since this doesn't seem to be something that telescope can directly solve, I am closing this issue. If you disagree and can think of a way to implement it, then we can reopen.
