### ISSUE TITLE
Telescope should make use of the quickfix list stack

### ISSUE THREAD

**Issue by cgsheeh** [nvim-telescope/telescope.nvim#1739]
**Is your feature request related to a problem? Please describe.**
Sometimes I make a search for A and send it to the quickfix list. Then I work a little more, and make another search for B, which I also send to the quickfix list. After that, I realize I need to see the results of my search for A again. Since I searched for B already, the quickfix list is overwritten and I need to re-open Telescope, search for A and re-send to the quickfix list.

I looked online for some extension that might solve this issue for me, but as it turns out this is already a feature of the quickfix list in Vim/Neovim! See [this page](https://neovim.io/doc/user/quickfix.html) and search for "Using more than one list of errors" (sorry, I can't figure out how to permalink the exact section). Neovim supports a stack of up to 10 quickfix lists, which can be moved between using `:colder`, `:cnewer` in a similar fashion to `:cnext` and `:cprev`.

**Describe the solution you'd like**
So the feature request (bug?) is that Telescope should be sending results to new quickfix lists instead of replacing all entries in the current quickfix list.

**Describe alternatives you've considered**
Alternatively we could create a new mapping that specifically sends results to a new quickfix list, keeping "overwrite all existing entries in the current list" as the default.

**Additional context**
I'm a relative newbie to Neovim and its rapidly evolving ecosystem, so it's possible there is a better solution that I haven't considered. I've never actually used the quickfix stack before so I might also be wrong about it's usefulness here. If I'm way off the mark here or there's a much better workflow I haven't been made aware of, please point me in the right direction!

I took a brief look at the code and it seems when Telescope calls [`setqflist`](https://neovim.io/doc/user/builtin.html#setqflist()) it always passes `'r'` as the mode on "send to qf list", when it should probably pass `''` to create a new list. I'd be interested in taking this on as a contribution if it would be accepted into the codebase.

**Comment by cgsheeh** [comment]
The first PR which enables Telescope using the quickfix list stack has landed. Nice!

I'm going to keep this open as I plan to hack on this a little more. As I mentioned previously I think having a picker for the quickfix list stack would be a nice feature. We may also be able to leverage the `what` dict passed to `setqflist` to add the Telescope query as the title of the quickfix list in the stack, which would make search much easier.

**Comment by Conni2461** [comment]
we are currently not looking for new pickers. See https://github.com/nvim-telescope/telescope.nvim/issues/1228

We can expose the local function `send_selected_to_qf ` in the `actions/init.lua`?

**Comment by cgsheeh** [comment]
> we are currently not looking for new pickers. See #1228

Ah okay, I won't bother adding it then. `:chistory` has been sufficient for me anyways. :)

Thanks for all your work on Telescope, it's great!
