### ISSUE TITLE
I really like telescope+ts file explorer combo, it would be nice if can run outside of nvim

### ISSUE THREAD

**Issue by ForteDexe** [nvim-telescope/telescope.nvim#1750]
I would love to see this extension become an app, to use without nvim. Like a CLI file explorer.

**Comment by Vedant36** [comment]
Both telescope and telescope-file-explorer are based on the neovim api, so you can only use them inside neovim.

However, there are much better terminal apps(imo) that were made for this very purpose. Refer to [here](https://github.com/agarrharr/awesome-cli-apps#file-managers) for more options. I currently use ranger and am thinking of trying out nnn

**Comment by fdschmidt93** [comment]
Sufficiently answered, thanks! Closing.
