### ISSUE TITLE
builtin.autocommands previewer throws: Cursor position outside buffer

### ISSUE THREAD

**Issue by Vedant36** [nvim-telescope/telescope.nvim#1754]
### Description

Context: I've only started converting my init.vim to init.lua since day before yesterday and got this problem while checking if a specific autocommand was set(it was)

The bug seems to be in the following lines(lua/telescope/previewers/buffer_previewer.lua:935-937):
```
vim.schedule(function()
  vim.api.nvim_win_set_cursor(status.preview_win, { selected_row, 0 })
end)
```
Error disappears when the lines are removed but I don't know what their purpose is
No error when letters typed slower than 0.5s apart so the error showing that `Cursor position outside buffer` seems confusing
I don't understand `vim.schedule` well but this seems to suggest that the error is caused when another callback starts before the previous one finishes but I'm probably wrong

Note: the error margin is actually 0.45s(always error) - 0.46s(never error) (multiple tests) but I doubt the time accuracy of sleep at that scale

Telescope commit: df0b35c

Related but fixed Issues:
#957 fixed by #1157
#1727 fixed by #1732

### Neovim version

```markdown
NVIM v0.7.0-dev+1109-gfaeff49cb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.16.10-zen1-1-zen

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:Telescope autocommands`
3. type something fast(less than 0.4s between letters, tested with xdotool). i could get a consistent error by typing `asd` fast

### Expected behavior

No error is thrown

### Actual behavior

Error thrown:
```
Error executing vim.schedule lua callback: ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:936: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:936: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:935>
```

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
lets just add a `pcall`

**Comment by Vedant36** [comment]
Do those lines even have a purpose or they're just a safe measure?
In the latter case just removing them should be better considering this is the 3rd issue caused by it

**Comment by Conni2461** [comment]
No they do have a purpose. These lines scroll the window.

But the other `set_cursor` in this file dont error because i `pcall`ed them a long time ago https://github.com/nvim-telescope/telescope.nvim/blob/df0b35c8bc0944164828ccba8ea17941423c6725/lua/telescope/previewers/buffer_previewer.lua#L439

we should do this here as well.
