### ISSUE TITLE
nvim 'wrap_result' option make the first line of 'oldfiles picker' hidden

### ISSUE THREAD

**Issue by ForteDexe** [nvim-telescope/telescope.nvim#1757]
### Description

This happens when you have a long file path in the 'oldfiles picker' list.

### Neovim version

```markdown
Lastest stable
```

### Operating system and version

Arch Manjaro KDE

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `coc`
  - INFO: No healthcheck provided

## Telescope Extension: `file_browser`
  - INFO: No healthcheck provided
```

### Steps to reproduce

wrap_result = 1

### Actual behavior

![Peek 2022-02-22 08-18](https://user-images.githubusercontent.com/57673412/155052874-7267dc2c-1a31-4b3d-9131-7fbf3cef5f4a.gif)

### Minimal config

```Lua
None
```

**Comment by edementyev** [comment]
Having the same issue actually on any picker, setting wrap_result to true seems to offset first selected line (where the cursor lands when the window opens) if there are any results that are wrapped in the list

**Comment by Conni2461** [comment]
The calculated selection line is no longer correct. For example with the default `selection_strategy` `reset` we set the selection to `max_results  - 1` which is no longer correct depending on how many lines are wrapped and that is kinda hard to figure out. You could calculate the `max_width` a result can have and then get the len of each display but thats a lot of work and only adds support for one strategy. Which makes the code blow up in the end ...
You probably wont see any Problems if you use `sorting_strategy = ascending` (see `:help telescope.defaults.sorting_strategy`). Would be nice if someone could test this

CC @sultanahamer i knew it wasnt that easy. Maybe that is not a feature we wanna have

**Comment by sultanahamer** [comment]
Wrapping doesn't create more lines is my understanding and navigating to line number with :<linenumber> works with wrap files in general. Let me see this computation part and see if its using something else to do the selection.

**Comment by sultanahamer** [comment]
The behavior I see is that selection is happening but is not in the visible view. We have to do ctrl +p and ctrl + n to see the actual selection. So, selection is happening alright but the scroll part is not.

**Comment by Conni2461** [comment]
sure the row seems to be correct but its still borked.

**Comment by sultanahamer** [comment]
If this happens only when users chooses the option wrap_results = true then, we can let it be a known issue while myself and others work on the fix.

Since this option is disabled by default, it shouldn't affect many users.

**Comment by Conni2461** [comment]
We can leave it like this for now, i wont remove it. Only if the maintenance overhead is greater than the benefit of having it

**Comment by sultanahamer** [comment]
This is not reproducible if users types the search string slowly or type the entire search term except last letter and then press the last letter after half a sec.

Like if I have to search in git_files "main" then I can type "mai" with normal speed, give it a second to get results then press n and the picker is alright, scrolled till end of results, showing the selection as well.

Not sure if there is any computation involved here to fix.
