### ISSUE TITLE
Addition of --pcre2 to additional_args of live_grep doesn't allow negative lookahead

### ISSUE THREAD

**Issue by keabarnes** [nvim-telescope/telescope.nvim#1759]
### Description

CLI ripgrep supports negative lookahead when the `--pcre2` flag is added, eg:
```bash
rg --pcre2 "class \w+ extends (?\!Component)"
```
* had results

but adding it to the `live_grep` `additional_args` doesn't seem to allow it:
```vim
nnoremap <leader>fg :lua require('telescope.builtin').live_grep({ additional_args = function(opts) return { "--pcre2" } end })<cr>
```
<img width="568" alt="image" src="https://user-images.githubusercontent.com/6176760/155095623-a5390d18-6fd7-4480-a8d7-773224c8c53f.png">

### Neovim version

```markdown
NVIM v0.6.0-dev+572-g5d653a134
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 11.5.2

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1
  - OK: fd: found fd 8.3.2
```

### Steps to reproduce

```vim
nnoremap <leader>fg :lua require('telescope.builtin').live_grep({ additional_args = function(opts) return { "--pcre2" } end })<cr>
```
<img width="568" alt="image" src="https://user-images.githubusercontent.com/6176760/155095623-a5390d18-6fd7-4480-a8d7-773224c8c53f.png">

### Expected behavior

Matching results to be shown

### Actual behavior

No results are shown

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jinleileiking** [comment]
`nnoremap <leader>fg :lua require('telescope.builtin').live_grep({ additional_args = function(opts) return { "" } end })<cr>` not work
`nnoremap <leader>fg :lua require('telescope.builtin').live_grep()<cr>` work

**Comment by jinleileiking** [comment]
relate to this ? https://github.com/nvim-telescope/telescope.nvim/pull/1217

**Comment by Conni2461** [comment]
You also have to escape it for telescope, is that the problem here?

**Comment by Conni2461** [comment]
> nnoremap <leader>fg :lua require('telescope.builtin').live_grep({ additional_args = function(opts) return { "" } end })<cr> not work

This is just invalid because you enter a empty string into the arguments list which you shouldn't do

**Comment by Conni2461** [comment]
Closing as stale
