### ISSUE TITLE
Ctrl+u to clear input

### ISSUE THREAD

**Issue by bno1** [nvim-telescope/telescope.nvim#1762]
**Is your feature request related to a problem? Please describe.**
Many linux programs, including vim, use the ctrl+u keybind to clear the focused text input. Telescope,nvim does not and I find it annoying that I have to clear it manually.

**Describe the solution you'd like**
Either add this keybind to telescope or allow control of user input line via actions. Right now I can't find any action that allow me modify or clear the input.

**Describe alternatives you've considered**
I can't find anything to help me clear the input line quickly.

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#mapping-c-u-to-clear-prompt

**Comment by bno1** [comment]
Thank you so much!
