### ISSUE TITLE
`rg -g '!*~'` not work

### ISSUE THREAD

**Issue by jinleileiking** [nvim-telescope/telescope.nvim#1769]
### Description

`rg -g '!*~'` not work
I want to ignore vim temp files  xxxx~

but not work.
tried many ways.

 
![image](https://user-images.githubusercontent.com/93968/156524508-b6470792-71ae-4dc6-b2c2-393b21c676ad.png)

or in vim_arguments.

### Neovim version

```markdown
⌁51% 7d [jinleileiking:~/temp] master(+12/-16)* ± nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

mac 

### checkhealth telescope

```markdown
-  2 telescope: require("telescope.health").check()¬
│  3 ========================================================================¬
│  4 ## Checking for required plugins¬
│- 5   - OK: plenary installed.¬
││ 6   - OK: nvim-treesitter installed.¬
││ 7 ¬
│  8 ## Checking external dependencies¬
│- 9   - OK: rg: found ripgrep 13.0.0¬
││10   - OK: fd: found fd 8.3.2¬
││11 ¬
│ 12 ## ===== Installed extensions =====¬
```

### Steps to reproduce

just like the pic

### Actual behavior

can igonore  *~ files

### Minimal config

```Lua
see pic
```

**Comment by Conni2461** [comment]
I have a temp file `xxxx~` in my directory with the content `Hello World`. Using normal `live_grep`
![image](https://user-images.githubusercontent.com/15233006/157841571-915ec8b7-2824-45af-90cd-478ebb2a0d8c.png)

Using `:lua require('telescope.builtin').live_grep({ additional_args = function(opts) return { "-g", "!*~" } end })` no results, as expected

![image](https://user-images.githubusercontent.com/15233006/157841641-f5817427-a222-4487-99c6-ef08826c740b.png)

Closing

**Comment by jinleileiking** [comment]
change `"'!*~'"` to `"!*~"`,  works well
