### ISSUE TITLE
Telescope sends results to quickfix incorrectly when there are spaces in the path.

### ISSUE THREAD

**Issue by lucypero** [nvim-telescope/telescope.nvim#1775]
### Description

When there are spaces in the file's path, Telescope sends the results to the quickfix incorrectly. It seems to escape the spaces with `\`. I think that's the reason why the files don't open when you try to open them from the quickfix list. It just opens an empty buffer.

### Neovim version

```markdown
NVIM v0.7.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu 20.04.3 LTS on Windows 10 x86_64

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 11.0.2
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. Go to a directory with spaces
2. Select some files on telescope
3. Send them to quickfix :   `require("telescope.actions").smart_send_to_qflist(prompt_bufnr)`
4. Try to open one of the files from quickfix

### Expected behavior

It should open the correct file on vim.

### Actual behavior

It opens a new empty buffer.

### Minimal config

```Lua
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
```

**Comment by eruizc-dev** [comment]
I managed to reproduce this in native linux as well:

![image](https://user-images.githubusercontent.com/58179604/156932607-f5079d82-325f-4cba-bca0-e72b58c7a31a.png)

The file `test dir/file.json` is sent to the quickfixlist as `test\ dir/file.json` with unnecessary escaping thus opening the wrong file afterwards.

There is no special configuration required for this to happen, it's the default behavior

**Comment by Conni2461** [comment]
Dup of #1700

**Comment by Conni2461** [comment]
fixed by https://github.com/nvim-telescope/telescope.nvim/commit/b501d9ecb7d8181e2238620c919740025e8b2096
