### ISSUE TITLE
builtin.man_pages() not respecting $MANPATH

### ISSUE THREAD

**Issue by grezp** [nvim-telescope/telescope.nvim#1777]
### Description

`builtin.man_pages()` can only find man pages located in `/usr/share/man`.

I install packages on my home path in `$HOME/local`. In there is `$HOME/local/share/man` where I have several man files from installed packages. How can I tell telescope to look in different paths. It seems to ignore `$MANPATH`.

### Neovim version

```markdown
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

CentOS 7.2

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev 468c69162a)
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. move man page near home directory
2. export man page to $MANPATH
3. call builtin.man_pages()

### Expected behavior

Ability to view man pages in different path locations.

### Actual behavior

builtin.man_pages() only shows "default" man pages

### Minimal config

```Lua
n/a
```

**Comment by Conni2461** [comment]
Merged without confirmation, If it still isn't fixed feel free to reopen

**Comment by grezp** [comment]
@Conni2461,
I just pulled from the master branch. It seems that the issue is still there.

**Comment by Conni2461** [comment]
Hmm that weird you should've been able to reopen.

Something that comes to mind why it isn't working is because we run `apropos ""` to get all manpages. but i think `apropos` only know about the manpages part of the db that `mandb` creates.

> The database searched by apropos is updated by the mandb program.

So can you check if these manpages are visible by just running `apropos ""` in command line

**Comment by grezp** [comment]
@Conni2461,
There's been a misunderstanding on my part on how man pages work.

I've added the additional man pages by updating with:
mandb -u

Thank you for your help.
