### ISSUE TITLE
Telescope's treesitter builtin isn't working with Lua.

### ISSUE THREAD

**Issue by pagankeymaster** [nvim-telescope/telescope.nvim#1778]
### Description

The title says it all. Only additional notes are that it works fine with other languages that I use, such as Java and Python.
This may be a treesitter parser related issue, or an user-error. Please, let me know if I messed up lmao.

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch Linux x86_64

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====
```

### Steps to reproduce

Steps:
1. Clone `plenary.nvim`, `nvim-treesitter` and `telescope.nvim` into `~/.local/share/nvim/site/pack`.
2. Create a Lua file called `minimal.lua`. The location of the file does not matter, but, for simplicity we create it in `~/Documents`
3. Open your favorite terminal emulator and type `nvim -nu path/to/minimal.lua path/to/sample.lua`.
4. Switch to command mode `:` then type `Telescope treesitter` and then press enter.

### Expected behavior

A floating window open up, showing scope information and type names.

### Gif example [Python]

![working](https://user-images.githubusercontent.com/80379926/157074344-18a5377a-cfa7-42a4-b45c-44679d86c141.gif)

## Throws a error.

```log
E5108: Error executing lua ...acker/opt/telescope.nvim/lua/telescope/builtin/files.lua:255: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
        [C]: in function 'pairs'
        ...acker/opt/telescope.nvim/lua/telescope/builtin/files.lua:255: in function 'prepare_match'
        ...acker/opt/telescope.nvim/lua/telescope/builtin/files.lua:256: in function 'prepare_match'
        ...acker/opt/telescope.nvim/lua/telescope/builtin/files.lua:256: in function 'prepare_match'
        ...acker/opt/telescope.nvim/lua/telescope/builtin/files.lua:282: in function 'v'
        ...acker/opt/telescope.nvim/lua/telescope/builtin/files.lua:455: in function 'v'
        ...packer/opt/telescope.nvim/lua/telescope/builtin/init.lua:474: in function <...packer/opt/telescope.nvim/lua/telescope/builtin/init.lua:443>
        ...pack/packer/opt/telescope.nvim/lua/telescope/command.lua:179: in function 'run_command'
        ...pack/packer/opt/telescope.nvim/lua/telescope/command.lua:244: in function '
```

## Possible clues(?)

Firstly note that for Java and Python files the extension works perfectly fine!
Now, notice this function `prepare_match` in `.../files.lua` ?

Navigate to that file and edit the following snippet in the beginning of `prepare_match` function:
```lua
if type(entry) == "string" then vim.notify(entry)
else vim.notify(vim.inspect(entry)) end
```

### The result is somewhat like this:
Tested in and screenshots for Lua and Python files:

#### Python
![screenshot-1646660141](https://user-images.githubusercontent.com/80379926/157069587-54701d0f-c3bc-4f3b-8e1f-94187c437424.png)

#### Lua
![screenshot-1646659319](https://user-images.githubusercontent.com/80379926/157069482-e48342cb-a6a7-463f-b229-d2c3cd545d5a.png)

From what I gather... the function requires a `.node` key in order to terminate the recursion(?).
But, I don't see `.node` being returned for lua files.

### Gif Demo [Lua]

![errors](https://user-images.githubusercontent.com/80379926/157074306-2165173d-d24a-4e92-a5b0-0fb701808ac6.gif)

### Minimal config

```Lua
-- NOTE: Put this in `minimal.lua` file.
vim.cmd[[packadd plenary.nvim | packadd telescope.nvim | packadd nvim-treesitter]]
require("telescope").setup()
require("nvim-treesitter.configs").setup({ ensure_installed = { "lua", "python" } })
```

**Comment by Conni2461** [comment]
Could you test this: https://github.com/nvim-telescope/telescope.nvim/pull/1779 ?

I dont use nvim-treesitters lua so i havent tested it yet :grimacing: but i am pretty sure that should fix the issue.

Thanks for reporting the bug :)

**Comment by pagankeymaster** [comment]
Wow... that was quite fast. That fixed it by the way. Thank you.
I'll subscribe to the pull request.
Closing...

**Comment by Conni2461** [comment]
FYI never close an issue before the PR is merge. The PR usually takes care of it.

**Comment by pagankeymaster** [comment]
I see! I'll keep that in mind (for next time :smile:).
