### ISSUE TITLE
Sort buffers by fricensy of use

### ISSUE THREAD

**Issue by Stanislav-Lapata** [nvim-telescope/telescope.nvim#179]
Hi, thanks for a wonderful project.

Can you add sort for `require'telescope.builtin'.buffers`?
When I use buffers. I would like to see the last files used at the bottom of the list.
![981866b5182e84ddfbdd10a1e6d196be](https://user-images.githubusercontent.com/12072329/96386525-497a6980-11a4-11eb-9659-339d1b98010a.jpg)
I open Gemfile and then Procfile, but they find at the top of the list.

**Comment by tjdevries** [comment]
So highest buffer number in the bottom or actually the last buffer you were in?

**Comment by Stanislav-Lapata** [comment]
Actually the last buffer I was in.

**Comment by sunjon** [comment]
I'd wanted this feature too. I'm not sure about how FZF ordered the buffers, because I don't want to be navigating with cursor keys in a fuzzy finder.. what _was_ useful, was the "%" buffer being pinned to the top.

Then if I have `<leader><CR>` mapped to telescope buffers, I can hit `<leader><cr><cr>` to toggle back and forth between two buffers.

**Comment by tjdevries** [comment]
But that's builtin, you can use `<C-^>`, right?

**Comment by tjdevries** [comment]
To neovim I mean.

**Comment by sunjon** [comment]
> But that's builtin, you can use <C-^>, right?

Sure, I could. But I find that an inconvenient shortcut that seem chosen. For me it's about least resistance and keeping my hands on the homerow.

I map `<Leader>(space)+<CR>`  to present the buffer list
The keys to interact with the window are `<esc>` (caps-lock)[homerow], `<C-j>/<C-k>`[homerow], and <CR> which my finger is already on. The choice of four or five buffers are available from a couple of key presses beneath keys my fingers are already on, without be having to even begin an actual fuzzy search.
It becomes a zero-thought process.

It does feel like I'm reasoning on Junegunn' behalf though, as it's nothing more than a request for the same feature as FZF, and that feature was undoubtedly a design choice.
In fact not only does FZF bump the previous buffer to the top of the list for this convenience, it also shows `%` / `^` /etc marks preceeding the buffer name.

**Comment by Conni2461** [comment]
I would take a closer look at this in the next few days, if it is okay for all involved.

**Comment by cseelus** [comment]
@Stanislav-Lapata Did you ever get this to work with #208? Also which theme are you using? Looks really decent 👍

**Comment by creativecreature** [comment]
This section of the README described how to achieve this: https://github.com/nvim-telescope/telescope.nvim#customize-default-builtin-behavior

This is the configuration you would need:
```lua
local actions = require('telescope.actions')require('telescope').setup{
  pickers = {
    buffers = {
      sort_lastused = true
    }
  }
}
```

**Comment by Herz3h** [comment]
This is not shown anymore in the README, it talks about sorters, but no example on how to override the default one..
