### ISSUE TITLE
Slow buffer list population

### ISSUE THREAD

**Issue by m-novikov** [nvim-telescope/telescope.nvim#1794]
### Description

Population of the results list when using LSP server is slow.
In my particular case it's `pyright`. But there is report https://github.com/nvim-telescope/telescope.nvim/issues/477 of 
For me most problematic part is `:Telescope buffers` command listing couple of open buffers could take seconds.

I am not sure how to debug this. My guess lsp hogging evenloop for some reason.

### Neovim version

```markdown
NVIM v0.7.0-dev+1259-g9a9b93c48
Build type: Debug
LuaJIT 2.1.0-beta3
```

### Operating system and version

Fedora 34

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. Configure LSP (pyright, rls)
2. Open couple of sufficiently complex files
3. Try to open `:Telescope buffers`

### Expected behavior

Rendering of telescope windows with it's contents is almost instant.

### Actual behavior

Windows is rendered, but contents only populated after delay.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
I'm curious about your hardware and cpu/mem usage during this. And you're saying it's especially bad when doing `:Telescope buffers`, even with only a couple (2) python files open? 

I use pyright nearly everyday and have not experienced any major slowdowns with telescope.

**Comment by Conni2461** [comment]
Can not reproduce this.

Also I'd like to see jamestrew questions answered otherwise i can't really help you

**Comment by Conni2461** [comment]
closing as stale. Feel free to reopen if this is still happening.
