### ISSUE TITLE
problems opening telescope from visual mode

### ISSUE THREAD

**Issue by przepompownia** [nvim-telescope/telescope.nvim#1802]
### Description

In my real environment I tried to use lua keymaps to run live_grep extension but I noticed that the initial query is not inserted to the prompt buffer and is not used as the initial query. 

I reduced the example to the original `live_grep` - it seems to be easy to reproduce on some minimal environment.

### Neovim version

```markdown
NVIM v0.7.0-dev+1290-ge7391191e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Debian sid

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

Given two visual mode mappings
```lua
local keymap = require('vim.keymap')

keymap.set('v', ',w', function()
  local query = 'test'
  require('telescope.builtin').live_grep({
    default_text = query,
  })
end)
vim.cmd([[
  vnoremap ,a :<c-u>lua require('telescope.builtin').live_grep({ default_text = 'test' })<cr>
]])
```
use it and see the effect.

### Expected behavior

The prompt query is the valoe of `default_text` at the start

### Actual behavior

The prompt query is empty
![image](https://user-images.githubusercontent.com/11404453/159196630-4c336c37-4f67-4bda-9cbd-caea866dc520.png)
For comparison, the prompt buffer behaves as expected when using vim mapping:
![image](https://user-images.githubusercontent.com/11404453/159196690-65b5fcad-fcc8-42d5-907a-e67a54a6aeb6.png)
Please notice that modes differ. 

### Minimal config

I included it in https://github.com/przepompownia/telescope-test

**Comment by Conni2461** [comment]
`default_text` is currently borked on latest nightly because of the prompt buffer patches that were merged.

Possible fix in https://github.com/nvim-telescope/telescope.nvim/pull/1600

**Comment by przepompownia** [comment]
Thanks @Conni2461 It works better but still has issues to describe there.

**Comment by Conni2461** [comment]
fixed by https://github.com/nvim-telescope/telescope.nvim/commit/cc1a3440f9ba6f28a8ca0bfff867f60c2d80c353

If not feel free to reopen, thanks :)

**Comment by przepompownia** [comment]
Thank you too, also for linking the partial solution :)
