### ISSUE TITLE
mapping configuration for each picker

### ISSUE THREAD

**Issue by tristone13th** [nvim-telescope/telescope.nvim#1808]
**Is your feature request related to a problem? Please describe.**
I want to set up key mappings for each individual picker.

**Describe the solution you'd like**
Add a mapping field for each picker in setup.

**Comment by l-kershaw** [comment]
This is already possible, for example:
```lua
require('telescope').setup({
  pickers = {
    buffers = {
      mappings = {
        i = {
          ["<C-x>"] = "delete_buffer",
        },
      },
    },
  },
})
```
will add a mapping for deleting buffers in the `buffers` picker.

**Comment by tristone13th** [comment]
> This is already possible, for example:
> 
> ```lua
> require('telescope').setup({
>   pickers = {
>     buffers = {
>       mappings = {
>         i = {
>           ["<C-x>"] = "delete_buffer",
>         },
>       },
>     },
>   },
> })
> ```
> 
> will add a mapping for deleting buffers in the `buffers` picker.

Thanks, what about mapping for extensions?

**Comment by l-kershaw** [comment]
It depends on the extension; they need to create a way of handling this option in their setup function.
For example, `telescope-file-browser` allows this (see [here](https://github.com/nvim-telescope/telescope-file-browser.nvim#remappings)), but others may not.
