### ISSUE TITLE
Ability to include untracked files in git_files

### ISSUE THREAD

**Issue by WesVleuten** [nvim-telescope/telescope.nvim#181]
I think a great addition would be the ability to find untracked files in `git_files`.

When working on a project, I often find myself adding new files. With the current configuration, I would need to first `git add` the file to find it in `git_files`

**Comment by rockerBOO** [comment]
Maybe check out `find_files` with the [`fd`](https://github.com/sharkdp/fd) program installed. This will ignore files in your `.gitignore` as well as search all files in the directory.

**Comment by tjdevries** [comment]
We can maybe add an option to git files to allow untracked.

**Comment by WesVleuten** [comment]
> Maybe check out `find_files` with the [`fd`](https://github.com/sharkdp/fd) program installed. This will ignore files in your `.gitignore` as well as search all files in the directory.

As far as I see, this isn't documented anywhere, but I'd love to have this as an option within telescope so it could work without a dependency.

**Comment by Conni2461** [comment]
`git_files` has show untracked since idk, i think its even enabled on default. `Telescope git_files show_untracked=true` / `false` to enable disable it. Closing for now
