### ISSUE TITLE
Treesitter picker not working properly

### ISSUE THREAD

**Issue by FractalWire** [nvim-telescope/telescope.nvim#1811]
### Description

After updating all of my plugin yesterday, I noticed a change in how Telescope handled treesitter picker.

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.16.16-arch1-1 GNU/Linux

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====
```

### Steps to reproduce

1. Install a treesitter language if not already done. `:TSInstall python`. Replace `python` by the language that is in the file you are testing
2. `:Telescope treesitter`
3. Check the third column

### Actual behavior

In the third column, instead of indicating the symbol type (function, var, type, etc.) we only see a `1` as chown on the screenshot below

![ss-290322-165924](https://user-images.githubusercontent.com/16882885/160779104-b5cddc2d-4a18-40d6-83e7-ad350617e1f6.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      'nvim-treesitter/nvim-treesitter'
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by FractalWire** [comment]
Original post on Reddit: https://www.reddit.com/r/neovim/comments/tr3160/telescope_and_treesitter_not_working_as_expected/

Comment of interest: https://www.reddit.com/r/neovim/comments/tr3160/telescope_and_treesitter_not_working_as_expected/i2ndvjo/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by Conni2461** [comment]
Thanks for brining this to github :) Should be fixed
