### ISSUE TITLE
Ignore TelescopeMultiSelection hg

### ISSUE THREAD

**Issue by SimonMandlik** [nvim-telescope/telescope.nvim#1815]
**Is your feature request related to a problem? Please describe.**
My simplistic telescope setup currently looks like this 

<img width="545" alt="image" src="https://user-images.githubusercontent.com/16707112/161015157-7fceab04-5535-4244-818d-d71e9f030c11.png">

I am using `Visual` hg for `TelescopeSelection`. I would like multi-selection to be only marked with the icon before all entries, not by any additional highlight group. I cannot use `TelescopeNormal` because that overrides the "visual" style when the focus is on the given result

<img width="545" alt="image" src="https://user-images.githubusercontent.com/16707112/161016090-24f0e531-6868-4e81-8e71-b952c3aa2ec6.png">

And similarly, I can't use `TelescopeSelected` because then it is hard to tell where the focus actually is

<img width="545" alt="image" src="https://user-images.githubusercontent.com/16707112/161016335-a2b8a388-33dd-4a3c-929d-6666cadb8a3b.png">

**Describe the solution you'd like**
Would it be possible to somehow ignore `TelescopeMultiSelection` and use `TelescopeNormal` / `TelescopeSelected` depending on the focus?

**Additional context**
I am using the following setting for all highlight groups:

```
highlight! link TelescopeBorder FloatBorder
highlight! link TelescopePromptBorder TelescopeBorder
highlight! link TelescopeTitle        TelescopeBorder
highlight! link TelescopePromptTitle  TelescopeTitle
highlight! link TelescopeResultsTitle TelescopeTitle
highlight! link TelescopePreviewTitle TelescopeTitle

highlight! link TelescopeMultiIcon CursorLineNr
highlight! link TelescopeMultiSelection TelescopeNormal
highlight! link TelescopeMatching Bold

highlight! link TelescopeSelection    Visual
highlight! link TelescopeNormal       Normal
highlight! link TelescopePromptNormal TelescopeNormal
highlight! link TelescopePromptPrefix Identifier
```

**Comment by l-kershaw** [comment]
If I understand what it is that you want correctly, then this should be possible by simply clearing the `TelescopeMultiSelection` highlight group.
There might be a better way to do this, but the following seemed to work for me:
```vim
highlight! link TelescopeMultiSelection NONE
```

Does this solve your issue?

**Comment by SimonMandlik** [comment]
Great, thanks!
