### ISSUE TITLE
Improve live_grep

### ISSUE THREAD

**Issue by otavioschwanck** [nvim-telescope/telescope.nvim#1818]
Recently i migrated from emacs to vim, im loving the performance, etc.

But i missing something crucial:  The project text finder is a little weak and too poluted.

Here is a comparassion:

Searching `stableCoin` on project and filtering for filename that contains `sol` (you can divide the search with `#`)

Emacs: 
![image](https://user-images.githubusercontent.com/9551316/161599052-50c3f21e-5d6e-4e87-9262-74696efa50e0.png)

Neovim:
![image](https://user-images.githubusercontent.com/9551316/161599582-7221df34-0054-4b48-8534-5ccccaadb944.png)

On telescope, it repeats the file a lot of times., make it poluted.
On telescope i cannot filter by filename (i have to use grep_string with search=)

Emacs:  Doom Emacs default search

**Comment by dm19** [comment]
It seems like string_grep and live_grep have the two halves to what we want; they're just not put together. String_grep greps for an initial term and the results can be filtered by typing additional terms in the telescope prompt, but string_grep takes only the word under cursor for the initial term; you can't enter it on command line or in Telescope prompt. live_grep lets you enter the initial term but you can't narrow the results by typing in additional terms.  

The way it works on Emacs (at least with consult-ripgrep, which is what I used), is that you can type in the initial term in the prompt, then the command seamlessly accepts any additional terms as filters on the initial results.

**Comment by tapayne88** [comment]
I wanted something like this, so I use the [telescope-rg](https://github.com/nvim-telescope/telescope-rg.nvim) extension which gives you access to `rg`.

Now to search for `stableCoin` and filtering for filename that contains `sol` I'd do
```
stableCoin -t sol
```
or perhaps
```
stableCoin -g *.sol
```

You can get pretty advanced with the glob matching so you can exclude tests with `-g !**/tests/**` etc. Everything you can do with ripgrep.

Another example searching in my dotfiles
<img width="1920" alt="Screenshot 2022-04-06 at 12 42 02" src="https://user-images.githubusercontent.com/991180/161967217-f8e3a901-9555-4dbd-8d5d-e1c4831ca1ce.png">

**Comment by otavioschwanck** [comment]
> I wanted something like this, so I use the [telescope-rg](https://github.com/nvim-telescope/telescope-rg.nvim) extension which gives you access to `rg`.
> 
> Now to search for `stableCoin` and filtering for filename that contains `sol` I'd do
> 
> ```
> stableCoin -t sol
> ```
> 
> or perhaps
> 
> ```
> stableCoin -g *.sol
> ```
> 
> You can get pretty advanced with the glob matching so you can exclude tests with `-g !**/tests/**` etc. Everything you can do with ripgrep.
> 
> Another example searching in my dotfiles <img alt="Screenshot 2022-04-06 at 12 42 02" width="1920" src="https://user-images.githubusercontent.com/991180/161967217-f8e3a901-9555-4dbd-8d5d-e1c4831ca1ce.png">

Telescope rg is OK, but still not good enough.  

1- I can`t separate the search with space unless i put 'my search'
2 - I have to remember the `*file*sol` exactly to works
3 - I have to put the search in order, if i want to find: 'senior token', on emacs e can put 'token senior' and it will get it, that easy.

**Comment by Conni2461** [comment]
You can now refine your live grep search and move to a fuzzy environment with `<c-space>`. Can be configured see https://github.com/nvim-telescope/telescope.nvim/pull/2034

**Comment by rsdenijs** [comment]
@Conni2461 That is awesome. I think this feature should be advertised more prominently!
