### ISSUE TITLE
How to change tags picker's file path width?

### ISSUE THREAD

**Issue by crusj** [nvim-telescope/telescope.nvim#1820]
### Description

I can not find the way by docs

### Neovim version

```markdown
0.6.1
```

### Operating system and version

macos 12.0.1

### checkhealth telescope

```markdown
-- This file can be loaded by calling `lua require('plugins')` from your init.vim

-- Only required if you have packer configured as `opt`
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function()
  -- Packer can manage itself
	use 'wbthomason/packer.nvim'
  	use 'neovim/nvim-lspconfig' -- Collection of configurations for the built-in LSP client
	use 'kyazdani42/nvim-web-devicons'
	use 'overcache/NeoSolarized'
	use {'neoclide/coc.nvim', branch = 'release'}
	use 'gfanto/fzf-lsp.nvim'
	use 'nvim-treesitter/nvim-treesitter'
	use {
  		'nvim-lualine/lualine.nvim',
  		requires = { 'kyazdani42/nvim-web-devicons', opt = true }
	}
	use {
    	'kyazdani42/nvim-tree.lua',
   	 	requires = {
      		'kyazdani42/nvim-web-devicons', -- optional, for file icon
    	},
    	config = function() require'nvim-tree'.setup {} end
	}
	use 'bagrat/vim-buffet'
	use 'voldikss/vim-floaterm'
	use 'nvim-lua/plenary.nvim'
	use 'hoschi/yode-nvim'
	use {
  		'nvim-telescope/telescope.nvim',
  		requires = { {'nvim-lua/plenary.nvim'}
	},
	use {
		'nvim-telescope/telescope-fzf-native.nvim',
		run = 'make' 
	}
}
end)
```

### Steps to reproduce

:Telescope tags

### Actual behavior

<img width="1372" alt="图片" src="https://user-images.githubusercontent.com/20185895/161920215-0560e565-3ecf-4fd4-a106-426983f42f97.png">

### Minimal config

```Lua
-- This file can be loaded by calling `lua require('plugins')` from your init.vim

-- Only required if you have packer configured as `opt`
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function()
  -- Packer can manage itself
	use 'wbthomason/packer.nvim'
  	use 'neovim/nvim-lspconfig' -- Collection of configurations for the built-in LSP client
	use 'kyazdani42/nvim-web-devicons'
	use 'overcache/NeoSolarized'
	use {'neoclide/coc.nvim', branch = 'release'}
	use 'gfanto/fzf-lsp.nvim'
	use 'nvim-treesitter/nvim-treesitter'
	use {
  		'nvim-lualine/lualine.nvim',
  		requires = { 'kyazdani42/nvim-web-devicons', opt = true }
	}
	use {
    	'kyazdani42/nvim-tree.lua',
   	 	requires = {
      		'kyazdani42/nvim-web-devicons', -- optional, for file icon
    	},
    	config = function() require'nvim-tree'.setup {} end
	}
	use 'bagrat/vim-buffet'
	use 'voldikss/vim-floaterm'
	use 'nvim-lua/plenary.nvim'
	use 'hoschi/yode-nvim'
	use {
  		'nvim-telescope/telescope.nvim',
  		requires = { {'nvim-lua/plenary.nvim'}
	},
	use {
		'nvim-telescope/telescope-fzf-native.nvim',
		run = 'make' 
	}
}
end)
```

**Comment by Conni2461** [comment]
currently hardcoded. https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/make_entry.lua#L921

Good first issue could be an additional options that you can access from opts.

**Comment by ankush** [comment]
Sort of related. Separator placement seems to be incorrect in some cases. IDK about the root cause, but feels relevant to the usage of tabs for indentation (and tswidth) 

<img width="1352" alt="Screenshot 2022-04-10 at 12 35 34 PM" src="https://user-images.githubusercontent.com/9079960/162606597-0b092221-f61a-4b0d-ba9f-edd45e6fed97.png">

**Comment by crusj** [comment]
> currently hardcoded. https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/make_entry.lua#L921
> 
> Good first issue could be an additional options that you can access from opts.

IThanks, I adjusted it manually

**Comment by KiLLeRRaT** [comment]
I know this is old, but I've just created a quick custom function which will set my `fname_width` based on my current tmux pane width, so I can always have `fname_width` as a proportion of my current pane width.  

Thought it could be useful to someone.

```lua
M.lsp_references = function()
	-- get pane width from tmux and use half the width for the fname_width
	local fname_width = math.floor(vim.fn.system("tmux display -p '#{pane_width}'") / 2)
	-- Maybe running outside of tmux
	if fname_width == 0 then
		fname_width = 30
	end
	require('telescope.builtin').lsp_references({fname_width = fname_width })
end

```

**Comment by jamestrew** [comment]
we just recently merged into master a change to remove the `fname_width` option from many pickers due to how clumsy having `<file path> | <line text>` looked. This led to `fname_width` never being great. Always cutting out the path or taking too much space and leaving a bunch of whitespace. Going forward, the file path and the text are shown as one concatenated string like so
![image](https://github.com/nvim-telescope/telescope.nvim/assets/66286082/ddc803fa-3550-4940-86b1-ab0422e292d0)

https://github.com/nvim-telescope/telescope.nvim/pull/2842

**Comment by KiLLeRRaT** [comment]
> we just recently merged into master a change to remove the `fname_width` option from many pickers due to how clumsy having `<file path> | <line text>` looked. This led to `fname_width` never being great. Always cutting out the path or taking too much space and leaving a bunch of whitespace. Going forward, the file path and the text are shown as one concatenated string like so ![image](https://private-user-images.githubusercontent.com/66286082/295403571-ddc803fa-3550-4940-86b1-ab0422e292d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTE5OTcsIm5iZiI6MTcwNDkxMTY5NywicGF0aCI6Ii82NjI4NjA4Mi8yOTU0MDM1NzEtZGRjODAzZmEtMzU1MC00OTQwLTg2YjEtYWIwNDIyZTI5MmQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE4MzQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkY2E0YmUxYTcxZmI3M2U5MTY4MDRlOTIyN2ZkMzgzMDI3YjY2YTMyNDljOWE2ODk2MDBhNWU3NDg0NDQ3NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bu0conpCi4h0JfUgX6CQDD0yL6RTre0lo_LRlm6NREg)
> 
> #2842

Hi @jamestrew that looks nice! And eliminates the whole problem.  I'm looking forward to using that in the future :)

Cheers,
