### ISSUE TITLE
[Feature] Add an option to also include current line when looking for references

### ISSUE THREAD

**Issue by pidgeon777** [nvim-telescope/telescope.nvim#1821]
This is the actual code for `Telescope lsp_references`:

```lua
...
    local locations = {}
    if result then
      local results = vim.lsp.util.locations_to_items(result, vim.lsp.get_client_by_id(ctx.client_id).offset_encoding)
      locations = vim.tbl_filter(function(v)
        -- Remove current line from result
        return not (v.filename == filepath and v.lnum == lnum)
      end, results or {})
    end
...
```

it would be great to add an option to allow the inclusion of the current line when looking for references.

**Comment by Conni2461** [comment]
`Telescope lsp_references include_current_line=true` should is now implemented.

Another bad report btw

**Comment by entropitor** [comment]
Isn't `include_current_line` reversed? It seems to filter out if it's true and vice versa

**Comment by Conni2461** [comment]
yep seems like i made a mistake and its reversed. Interested in opening a PR which fixes this?

**Comment by pidgeon777** [comment]
I wonder if this has been fixed?

**Comment by Conni2461** [comment]
we merged a fixed a couple of days ago https://github.com/nvim-telescope/telescope.nvim/commit/4a43d13c953596503ff37fbc0cc80e68099c5c5c

so yeah its fixed
