### ISSUE TITLE
Selected from builtin will switch to normal mode.

### ISSUE THREAD

**Issue by singlexyz** [nvim-telescope/telescope.nvim#1824]
After directly opening Telescope's pickers, it will automatically jump to insert mode.

But if execute `:Telescope` first, and then select like `colorscheme` to open, it will enter normal mode.

Can the picker opened in this way also automatically enter insert mode?

https://user-images.githubusercontent.com/4456413/162052599-36f09954-c5ee-4cb3-940b-0eb9d28497ce.mov

**Comment by Conni2461** [comment]
Dup of #1599 

Also not a features request. Please open your bug reports as bug reports in the future!
