### ISSUE TITLE
Option to allow the right hand side of path/buffer/etc to be always visible

### ISSUE THREAD

**Issue by muhmud** [nvim-telescope/telescope.nvim#1826]
**Is your feature request related to a problem? Please describe.**
When the path to a file is long, I'm unable to see the filename part of the path, which I think it more important that the front of the path

![image](https://user-images.githubusercontent.com/7550982/162258663-0a8a9658-cf6b-4932-aa0d-1f5d0da5621e.png)

**Describe the solution you'd like**
I'd like an option, or a shortcut, to shift the path part so that I can see the right hand side of it. I think an option that always does this would be good.

**Describe alternatives you've considered**
I thought about using a different layout, but I like the default one. I've also looked at increasing the width, but I don't think this will work in all circumstances.

**Comment by l-kershaw** [comment]
I think the `path_display` option "truncate", is what you are looking for.
See `:h telescope.defaults.path_display` for more information.

**Comment by muhmud** [comment]
Thanks for the tip :+1: 

This does what I want, though I might do a variation that includes the project name on the front:

```lua
(function(max)
  return function(opts, path)
    local length = string.len(path)
    if (length > max) then
      path = "..." .. string.sub(path, length - max + 3 + 1)
    end
    return path
  end
end)(35)
```
