### ISSUE TITLE
find_files with a non-empty cwd returns a weird filepath

### ISSUE THREAD

**Issue by nguyenvukhang** [nvim-telescope/telescope.nvim#1828]
### Description

If a `cwd` parameter to telescope's builtin `find_files` function, the file that opens after using `select_default` has its path incorrectly shown.

### Neovim version

```markdown
NVIM v0.6.1
```

### Operating system and version

macOS 12.3

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====
```

### Steps to reproduce

Given this file structure:
```
~
├── scope
│  └── foo
└── tele
   └── bar
```

and this `init.lua`:
```
vim.cmd("call plug#begin()")
vim.cmd("Plug 'nvim-lua/plenary.nvim'")
vim.cmd("Plug 'nvim-telescope/telescope.nvim'")
vim.cmd("call plug#end()")
vim.api.nvim_set_keymap('n', '<C-p>', ":lua require('telescope.builtin').find_files({ cwd = '$HOME/scope' })<CR>", {})
```

After installing the plugins, do these steps:
```
cd $HOME/tele
nvim bar
```
Press `<C-p>` (there should be only one result: `foo`) and press enter.
Your statusline should now show the weird filename. I personally got `~//scope/./foo`

### Expected behavior

Expected value is `~/scope/foo`, achievable by the following commands:

```
cd $HOME/tele
nvim bar
:e ~/scope/foo
```

### Actual behavior

https://user-images.githubusercontent.com/10664455/162477086-6cc645ac-330a-4f16-ad9b-c307f0caec0e.mov

### Minimal config

```Lua
vim.cmd("call plug#begin()")
vim.cmd("Plug 'nvim-lua/plenary.nvim'")
vim.cmd("Plug 'nvim-telescope/telescope.nvim'")
vim.cmd("call plug#end()")
vim.api.nvim_set_keymap('n', '<C-p>', ":lua require('telescope.builtin').find_files({ cwd = '$HOME/scope' })<CR>", {})
```

**Comment by Conni2461** [comment]
plenary bug https://github.com/nvim-lua/plenary.nvim/issues/330

**Comment by Conni2461** [comment]
Fixed by https://github.com/nvim-lua/plenary.nvim/commit/c54f77d409f476d457d1e1ba7615139c63937321
