### ISSUE TITLE
tag/lsp reference picker separator placement doesn't work with tabs

### ISSUE THREAD

**Issue by ankush** [nvim-telescope/telescope.nvim#1834]
### Description

with `ts=4`

<img width="1352" alt="Screenshot 2022-04-10 at 12 35 34 PM" src="https://user-images.githubusercontent.com/9079960/162606597-0b092221-f61a-4b0d-ba9f-edd45e6fed97.png">

with `ts=1`

<img width="1352" alt="Screenshot 2022-04-10 at 12 42 26 PM" src="https://user-images.githubusercontent.com/9079960/162606828-600e0b1e-8816-4515-b100-7c39914f9295.png">

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-001.local

Features: +acl +iconv +tui
```

### Operating system and version

Mac OS 11.6.x

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. Use tabs for indentation in code
2. Set ts to > 1
3. use lsp_references. Separator placement considers tabs as single character. 

### Expected behavior

`ts` value should be respected

### Actual behavior

`ts` value isn't considered

**Comment by Conni2461** [comment]
does https://github.com/nvim-telescope/telescope.nvim/pull/1845 help?

**Comment by ankush** [comment]
@Conni2461 yep, tested locally 👍
