### ISSUE TITLE
Telescope find_files slow

### ISSUE THREAD

**Issue by kirill-martynov** [nvim-telescope/telescope.nvim#1837]
### Description

Telescope find_files too slow on a project with 3479 files
 I found that option  path_display = { "smart" } makes it slow

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.3

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

```
require('telescope').setup{
  pickers = {
    find_files = {
      path_display = { "smart" }
    }
  }
}

require('telescope').load_extension('fzf')
```

### Actual behavior

https://user-images.githubusercontent.com/70448489/163059325-a17920f5-1ca8-45db-ba86-9e4314ad1816.mov

### Minimal config

```Lua
require('telescope').setup{
  pickers = {
    find_files = {
      path_display = { "smart" }
    }
  }
}

require('telescope').load_extension('fzf')
```

**Comment by Conni2461** [comment]
`path_smart` is a lua only algorithm that takes all files into consideration. Its an algorithm that was proposed by someone and probably can't be optimized.

Ref https://github.com/nvim-telescope/telescope.nvim/pull/914

We should add a disclaimer to our documentation about the performance impact.

**Comment by AlxHnr** [comment]
`find_files` is very slow, even when not setting the smart option. I have 126.000 files in my homedir. Searching for `telereadme` causes Telescope to hang for 7 seconds before it suggests `.config/nvim/pack/plugin/start/telescope.nvim/README.md`. Installing telescope's fzf sorter extension gets this down to 5 seconds, but this is still unusable. [Fzf.vim](https://github.com/junegunn/fzf.vim) can do this instantaneously as I type `telereadme`.

When I start typing immediately after running `:Telescope find_files`, it will swallow the first few characters I'm typing :( This doesn't occur with fzf.vim.

**Comment by Conni2461** [comment]
I added a negative performance warning for `smart_path`.

@AlxHnr your report is cover by this issue: #1423 Our UI is currently slow in updating. We are working on this here #1491

If Telescope doesnt work for you just stick with fzf, its an awesome tool

**Comment by jneidel** [comment]
Using `find_files` in my home directory is also unbearably slow, so I just use fzf there and telescope everywhere else:

```lua
  if vim.fn.getcwd() == os.getenv("HOME") then
    -- redefine fzf call: vim.cmd( "let $FZF_DEFAULT_COMMAND ...
    vim.cmd( "command! -bang -nargs=? -complete=dir Files call fzf#vim#files(<q-args>, {'options': []}, <bang>0)" )

    vim.keymap.set("n", "<A-f>", ":Files<CR>", {});
  else
    -- redefine find_files: function custom_find_files() ...

    vim.keymap.set("n", "<A-f>", custom_find_files, {});
  end
```
