### ISSUE TITLE
Can't use telescope anymore, always showing no file name

### ISSUE THREAD

**Issue by BitInByte** [nvim-telescope/telescope.nvim#1839]
### Description

Every time that I try to run telescope and select files to preview or open a file I receive an error which doesn't allow me to open the file.

### Neovim version

```markdown
VIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.3.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====
```

### Steps to reproduce

trying to find a file it should show the error

### Actual behavior

![Error](https://user-images.githubusercontent.com/64453275/163556667-3c9edb9d-3803-4143-8ed0-5f0dbabdd0e6.png)

### Minimal config

```Lua
-- local actions = require('telescope.actions')
-- Global remapping
------------------------------
require("telescope").setup {
  defaults = {
    vimgrep_arguments = {
      "rg",
      "--color=never",
      "--no-heading",
      "--with-filename",
      "--line-number",
      "--column",
      "--smart-case"
    },
    prompt_prefix = "> ",
    color_devicons = true,
    file_previewer = require("telescope.previewers").vim_buffer_cat.new,
    grep_previewer = require "telescope.previewers".vim_buffer_vimgrep.new,
    file_ignore_patterns = {"node_modules"},
    buffer_previewer_maker = require "telescope.previewers".buffer_previewer_maker,
    mappings = {
      i = {},
      n = {}
    },
    extensions = {
      fzy_native = {
        override_generic_sorter = false,
        override_file_sorter = true
      }
    }
  }
}

--require('telescope').load_extension('fzy_native')
```

**Comment by l-kershaw** [comment]
I can't reproduce this problem on my machine.
Are you using the latest version of both `plenary` and `telescope`?

**Comment by BitInByte** [comment]
Found the issue but now I don't know how to solve it.

The problem is derived by this piece of code in my config:
```lua
vim.cmd [[
augroup remember_folds
  autocmd!
  autocmd BufWinLeave * mkview
  autocmd BufWinEnter * silent! loadview
augroup END
]]
```
It basically allow it to save my folds.

**Comment by Conni2461** [comment]
We have filetypes for `TelescopePrompt`, `TelescopeResults`. So you can only do `mkview` if its neither of those two file types. I think that should help.

**Comment by fdschmidt93** [comment]
I think we can close this as `wontfix` from telescope side. Should that not be the case, please open a new issue. Thanks

**Comment by sutyum** [comment]
Facing the same issue, any hints on how to fix this?

**Comment by justinmakes** [comment]
Same here, is there another way to save folds while using telescope?

**Comment by jamestrew** [comment]
Just exclude the telescope file types listed above in your autocommands i.e. don't use `*`.

**Comment by finnurthorisson** [comment]
```vim
augroup remember_folds
	autocmd!
	autocmd BufWinLeave * if &filetype !=# 'TelescopePrompt' && &filetype !=# 'TelescopeResults' && bufname('%') != '' | mkview
	autocmd BufWinEnter * if &filetype !=# 'TelescopePrompt' && &filetype !=# 'TelescopeResults' && bufname('%') != '' | silent! loadview
augroup END
```
