### ISSUE TITLE
color_devicons setting is 

### ISSUE THREAD

**Issue by exten** [nvim-telescope/telescope.nvim#1843]
### Description

`color_devicons = false` Invalid setting，
![image](https://user-images.githubusercontent.com/3364033/163707926-2981b7f3-1bac-4b6c-97fe-7baca28d47f6.png)

### Neovim version

```markdown
NVIM 7.0
```

### Operating system and version

macOS 10.15

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - ERROR: rg: not found. `live-grep` finder will not function without [BurntSushi/ripgrep](https://github.com/BurntSushi/ripgrep) installed.
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====
```

### Steps to reproduce

    theme = "dropdown", -- dropdown\ivy
    sorting_strategy = "ascending",
    layout_strategy = "bottom_pane",
    border = true,
    color_devicons = false,
    borderchars = {
      prompt = {"─", "│", "─", "│", "+", "+", "+", "+"},
      results = {"─", "│", "─", "│", "+", "+", "+", "+"},
      preview = {"─", "│", "─", "│", "+", "+", "+", "+"}
    },
    prompt_prefix = "> ",
    selection_caret = "> ",
    path_display = {"smart"},

### Expected behavior

close icon icon，Because it is not installed `devicons `, so i set `color_devicons = false` 

### Actual behavior

Font icon display cannot be turned off

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
`color_devicons` is for disabling highlighting for devicons. Not for turning of icons! See `help telescope.defaults.color_devicons`

If `kyazdani42/nvim-web-devicons` is not loaded/installed we dont load devicons. Works perfectly fine for me.
![image](https://user-images.githubusercontent.com/15233006/163714444-54db4822-c3c1-4ef3-80a3-72756af4f98c.png)

And to disable devicons with an optional use `Telescope find_files disable_devicons=true`. Also works for me.

It currently can't be used globally and is not documented. See #1222 

I would close this Issue as dup of #1222. If thats okay for you and this this post answers your questions.

**Comment by exten** [comment]
thanks ：）
