### ISSUE TITLE
fzy sorter is slow with large code base

### ISSUE THREAD

**Issue by smartding** [nvim-telescope/telescope.nvim#185]
I have 2 golang repos [kubernetes](https://github.com/kubernetes/kubernetes) with 20k+ files and [kubeedge](https://github.com/kubeedge/kubeedge) with 7k+ files.

 `git_files` and `find_files` becomes quite slow once I set the sorters to fzy,  search result starts to show after I type 7,8 letters :

```lua
require('telescope').setup{
  defaults = {
    generic_sorter = require'telescope.sorters'.get_fzy_sorter,
    file_sorter = require'telescope.sorters'.get_fzy_sorter,
  }
}
```

**Comment by FL3SH** [comment]
Do we have any update here? I can add more details if needed, just let me know what is necessary.

**Comment by OkanEsen** [comment]
Yeah, there is ongoing work in #215.

**Comment by tjdevries** [comment]
You can try this instead: https://github.com/nvim-telescope/telescope-fzy-native.nvim :) I hope it works for you!

**Comment by smartding** [comment]
> You can try this instead: https://github.com/nvim-telescope/telescope-fzy-native.nvim :) I hope it works for you!

it works, even with 20k files in the git repo!
