### ISSUE TITLE
Find words don't work

### ISSUE THREAD

**Issue by Shrimp22** [nvim-telescope/telescope.nvim#1861]
I have a problem with find words. Every time when I try search I got this message
![Screenshot from 2022-04-20 22-51-49](https://user-images.githubusercontent.com/86841678/164321384-b09f5f45-4b85-4f72-acb0-b304623baae9.png)

**Comment by Conni2461** [comment]
make sure you have the dependencies https://github.com/nvim-telescope/telescope.nvim#suggested-dependencies
