### ISSUE TITLE
Let live grep search in path and file simultaneously

### ISSUE THREAD

**Issue by ngerritsen** [nvim-telescope/telescope.nvim#1862]
**Is your feature request related to a problem? Please describe.**
The only reason that I'm still using fzf.vim is the fact that I can very easily search for specific strings in the context of a certain filepath. So for instance when I have the string `Run` and I want to search for it in all files ending with `Test.js`, in fzf.vim I just run `:Rg` for ripgrep and type `Run Test.js` and it will give me the results I want. In `:Telescope live_grep` I get nothing.

**Describe the solution you'd like**
I would like the live_grep in Telescope to behave the same way as in fzf.vim, fuzzy searching in the path and file contents simultaneously.

**Describe alternatives you've considered**
I have Googled a bit on this and asked this in the Gitter chat of Telescope. I did not find any working solutions.

**Additional context**
FZF Rg:
![Screenshot 2022-04-21 at 12 46 38](https://user-images.githubusercontent.com/6407496/164442287-4bdb250c-9a12-4988-8bc8-70f4e0cc8cd1.png)

Telescope live_grep:
![Screenshot 2022-04-21 at 12 46 51](https://user-images.githubusercontent.com/6407496/164442292-0f2029b7-16e8-45d5-b00d-b958882565e8.png)

**Comment by SoryEscobar** [comment]
Try the **grep_string** picker, I think that one behaves the way you expect this to work

**Comment by fdschmidt93** [comment]
`live_grep` immediately launches. IIRC `fzf.vim` `Rg` essentially fetches all the lines and then `fzf` over them, this, as said above is comparable to `grep_string` picker.

I don't think there's anything to do here from `telescope` side, so closing. Please note if you feel otherwise.
