### ISSUE TITLE
improve lsp_[range_]code_actions

### ISSUE THREAD

**Issue by rebelot** [nvim-telescope/telescope.nvim#1863]
**Is your feature request related to a problem? Please describe.**
normalize telescope code action behavior with default `vim.lsp.buf.[range_]code_action`

**Describe the solution you'd like**

1) telescope builtin `range_code_actions` should not override column position when calling `vim.lsp.util.make_given_range_params` as this nullifies code actions for LSPs that support refactoring

2) if code action triggers a server command, check `client.commands[action.command.command]` or `vim.lsp.commands[action.command.command]` for a provider and lastly fall back to `vim.lsp.buf.execute_command`
as in https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/buf.lua#L513
this will consolidate a consistent strategy for extending LSP capabilities by only defining functions called on specific server commands instead of needing to override `textDocument/executeCommand` handler to make code actions work with telescope

**Comment by rebelot** [comment]
Temporary fix: 

Telescope config
```lua
local function on_execute_action(action, offset_encoding)
    local getfn = function(command)
        if vim.lsp.commands[command] then
            return vim.lsp.commands[command]
        end
        for _, client in ipairs(vim.lsp.buf_get_clients(0)) do
            if client.commands[command] then
                return client.commands[command]
            end
        end
    end

    if action.edit then
        vim.lsp.util.apply_workspace_edit(action.edit, offset_encoding)
    end
    if action.command then
        local command = type(action.command) == "table" and action.command or action
        local fn = getfn(command.command)
        if fn then
            fn(command, {})
        else
            vim.lsp.buf.execute_command(command)
        end
    end

require("telescope").setup({
    ...
    pickers = {
        ...
        lsp_code_actions = themes.get_cursor({
            execute_action = on_execute_action,
        }),
    }
}
```

mappings:
```lua
vim.keymap.set(
    "n",
    "<leader>la",
    require("telescope.builtin").lsp_code_actions,
    { unpack(opts), desc = "List LSP Code Actions" }
)
vim.keymap.set(
    "x",
    "<leader>la",
    function()
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<esc>", true, false, true), "n", false)
        local params = vim.lsp.util.make_given_range_params()
        require("telescope.builtin").lsp_code_actions({ params = params })
    end,
    { unpack(opts), desc = "List LSP Code Actions for selected range" }
)
```

(btw, lua is all nice and evarything, but man I never thought I'd miss `:<C-U>call`)

**Comment by Conni2461** [comment]
id rather remove it. We have `vim.lsp.buf.[range_]code_action` with `vim.ui.select`. So you can still have a telescope ui with https://github.com/nvim-telescope/telescope-ui-select.nvim

At this point its just a duplication of work and there were so many fixes over the past couple of months and even more issues. I just havent had the guts to pull the trigger.

Ref #1728 #1760

**Comment by gegoune** [comment]
I would say remove it if there is better (there is) alternative. It makes it easier for users to pick solution they use.

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/1866

**Comment by Conni2461** [comment]
code_actions where removed from telescope in https://github.com/nvim-telescope/telescope.nvim/pull/1866

See `:help telescope.changelog-1866` for more information
