### ISSUE TITLE
Mappings do not appear on which key

### ISSUE THREAD

**Issue by danielo515** [nvim-telescope/telescope.nvim#1869]
**Is your feature request related to a problem? Please describe.**
I am using the telescope extension of harpoon, and despite the extension registers some custom mappings for its picker, those mappings do not appear when I trigger which key inside the popup of the picker. Take a look at the additional context section for links and screenshots

**Describe the solution you'd like**
I heavily rely on the inline help that which-key provides, so I would love to this to actually work for all the mappings

**Describe alternatives you've considered**
None other than having a cheatsheet.

**Additional context**
Here is the code of the extension that registers the mappings:
https://github.com/ThePrimeagen/harpoon/blob/master/lua/telescope/_extensions/marks.lua#L102-L115

Here you can see an screenshot with which key open, where the mappings created do not exist
![image](https://user-images.githubusercontent.com/2270425/164646712-f48d0fca-726c-47ca-a757-aab723dc171e.png)

**Comment by fdschmidt93** [comment]
Have you read the code I've sent in Matrix and my follow-up comment to your reply?

Registering is something like this

```lua
local builtin = require("telescope.builtin")
local actions = require("telescope.actions")
local action_state = require("telescope.actions.state")
local transform_mod = require("telescope.actions.mt").transform_mod

local mod = {}
mod.print_value = function(prompt_bufnr)
  print(action_state.get_selected_entry().value)
end
mod = transform_mod(mod)

builtin.find_files({
  attach_mappings = function(_, map)
    map("n", "P", mod.print_value)
    return true
  end,
})
```

and not just mapping a function in attach_mappings. It has to be a module, primarily such that the table key corresponds to the function name.

Please put more effort into understanding documentation and help.

**Comment by danielo515** [comment]
> Please put more effort into understanding documentation and help.

I put all the effort I was able before opening an issue. Yes, I read your comment, so please point me when, in any of your comments you mention the module requirement:

> existing mappings should appear, registering mappings can be done like so
-- Piece of code here
> Yes, because as elaborated beforehand, mappings need to be appropriate registered akin to the code snippet I've posted above. You're free to make a PR to Harpoon and then you'd seen them popup.

` appropriate registered` may mean something to you, to the telescope team or to people already familiar with the inners of how this works, but has no meaning for anyone else. I had not much experience with lua, nor with telescope, so for me there is no obvious difference between passing a variable containing a function and a module property containing a function. If there is any technical limitation in the language that allows you to do reflection on modules and not on variables I don't know of.
Also, as you pointed that this is obvious also in docs and I was not able to deduce it by reading the docs, could you point me to the place where this very particular and implicit requirement is explained?

**Comment by Conni2461** [comment]
the table/the object contains the name of the function that we can get from the module (when you do `transform_mod`). If you just do `module.fn` you only get the function pointer. The best we can do in this case is show that there is a anonymous function with this diff

```diff
diff --git a/lua/telescope/actions/init.lua b/lua/telescope/actions/init.lua
index 96eb525..8425f83 100644
--- a/lua/telescope/actions/init.lua
+++ b/lua/telescope/actions/init.lua
@@ -1125,6 +1125,10 @@ actions.which_key = function(prompt_bufnr, opts)
           table.insert(mappings, { mode = v.mode, keybind = v.keybind, name = name })
         end
       end
+    elseif type(v.func) == "function" then
+      if not opts.only_show_current_mode or mode == v.mode then
+        table.insert(mappings, { mode = v.mode, keybind = v.keybind, name = "<anonymous function>" })
+      end
     end
   end
 
```

**Comment by fdschmidt93** [comment]
> I put all the effort I was able before opening an issue. Yes, I read your comment, so please point me when, in any of your comments you mention the module requirement:

I'd have made the case that the difference between harpoon mapping and the code snippet is sufficiently clear when knowing a little bit of lua.

> appropriate registered may mean something to you, to the telescope team or to people already familiar with the inners of how this works, but has no meaning for anyone else. I had not much experience with lua, nor with telescope, so for me there is no obvious difference between passing a variable containing a function and a module property containing a function.

That's fair, but I hope you understand as to why I'm wondering that you didn't follow up on matrix asking me to clarify but instead open a new issue. That sort of left me with the impression you didn't appropriately consider what I was trying to get across. I didn't mean to attack you personally or anything, it's more that there's maybe 2-4 contributors periodically replying to questions from a lot of people, so my replies will mostly be what I hope is minimally sufficient.

Anyways, it's all good from my end.

> Also, as you pointed that this is obvious also in docs and I was not able to deduce it by reading the docs, could you point me to the place where this very particular and implicit requirement is explained?

`:h telescope.actions` mentions that functions can be transformed into `actions`, though in fairness, it's not yet perfectly clear that `which_key` only shows actions. There used to be some information straight on the README. I'll make a PR to clarify it both in `telescope.actions` and `actions.which_key`.

I'll see if we can use the `debug` module to maybe also extract the name of the actual function.

**Comment by Conni2461** [comment]
> I'll see if we can use the `debug` module to maybe also extract the name of the actual function.

Do we really want to fetch the function name from file information (source and linedefined) from `debug.getinfo`. It just gets worse when someone does this: 
```lua
map("n", "asdf", function()
end)
```

**Comment by fdschmidt93** [comment]
> Do we really want to fetch the function name from file information (source and linedefined) from debug.getinfo. It just gets worse when someone does this:

Ah, only assignments could have names, would have been easily checked for.

```lua
function _get_anon_function_name(func_ref)
  local Path = require "plenary.path"
  local info = debug.getinfo(func_ref)
  local fname
  for i, line in ipairs(Path:new(info.short_src):readlines()) do
    if i == info.linedefined then
      fname = line
      break
    end
  end
  -- (1) remove function/local, (2) whitespace and equal and (3) anything in parenthesis incl. parentheses themselves
  if fname:match("=") == nil then
    return "<anonymous>"
  else
    fname = fname:gsub("function", ""):gsub("local", ""):gsub("[%s=]", ""):gsub("%((.+)%)", ""):gsub("(.+)%.", "")
    return fname
  end
end
```

But yeah

> we should make sure that we have this everything inside telescope.nvim, and that we dont have callbacks anywhere

Not sure I 100% follow what you mean here.

**Comment by Conni2461** [comment]
> Not sure I 100% follow what you mean here.

We should make sure all our mapped functions are actual actions. So the first party support is good. Did a quick grep and havent found any thought so nvm

We can do it, if you already have a working code :laughing:
