### ISSUE TITLE
Empty Grep String causes vim to lock up

### ISSUE THREAD

**Issue by ThePrimeagen** [nvim-telescope/telescope.nvim#187]
Here is my remap

```vimL
nnoremap <leader>ps :lua require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For >")})<CR>
```

If I simply hit "enter", then the lua telescope menu pops up, then I hit escape.  Locks the UI with continuous stream of errors.

nvim: 
NVIM v0.5.0-766-g77dc891bf
Build type: Release
LuaJIT 2.1.0-beta3

latest telescope.

**Comment by elianiva** [comment]
This is no longer the case, I think. I couldn't reproduce the issue. Can you confirm this @ThePrimeagen ?

**Comment by ThePrimeagen** [comment]
you are correct.  Just tried it.

Well done with whom fixed it!

**Comment by kdnk** [comment]
It's not the case when I hit `enter` but It still seems to be in the case when I hit `escape` instead of `enter`.
