### ISSUE TITLE
actions.git_rebase_branch should support `--interactive`

### ISSUE THREAD

**Issue by tom-anders** [nvim-telescope/telescope.nvim#1870]
**Is your feature request related to a problem? Please describe.**
actions.git_rebase_branch always does a non-interactive rebase

**Describe the solution you'd like**
Add an optional bool parameter `interactive` or even a table `flags` that are passed to `git rebase`

**Comment by Conni2461** [comment]
I dont 100% get what you want to happen when interactive is passed to the command. How do you want to do set command for specific commits?

We are primary a fuzzy finder (not a git plugin) we provide some basic pickers and actions but that does not have to cover every use case. You can easily write your own action if you want to set interactive.

**Comment by tom-anders** [comment]
Right, I just thought it would be useful for many people, but of course I can write it myself
