### ISSUE TITLE
remove last free form template

### ISSUE THREAD

**Issue by Conni2461** [nvim-telescope/telescope.nvim#1874]
I've been thinking about this for quite a while. It sucks that if we remove it we (team) can no longer have the possibility to do post like this. Just write a free form text about anything, which should be possible from time to time.

But we are getting more and more bug reports as free form features requests. The last one was #1861 

Maybe the solution is have free form allowed (with default tag discussion) but add a description that if a bug/feature request is opened as free form, we close and lock it, no support for it. That allows people to still make discussions and no one can be mad for just getting their issue closed.   

Unrelated: We should add telescope commit sha/version to the bug template

**Comment by Conni2461** [comment]
Like here

![image](https://user-images.githubusercontent.com/15233006/164760876-408480ca-24f2-4315-bfdc-26b53bd34cb4.png)

Another point "Discussion" with the subtext: "Meant for discussions. Opened Bug/Feature requests as Discussions will get ANY support"

CC @tjdevries @fdschmidt93 @clason @l-kershaw

**Comment by clason** [comment]
Which on is the last one?

**Comment by Conni2461** [comment]
Feature request is still a free form markdown template, i want to make it a form, similar to bug report. With just 4 text boxes that have to be filled out.
- Is your feature request related to a problem? Please describe.
- Describe the solution you'd like
- Describe alternatives you've considered
- Additional context

**Comment by gegoune** [comment]
Or enable discussions?

**Comment by Conni2461** [comment]
We've tried them and i did not like them. 90% were bug reports and there weren't really discussions happening

**Comment by clason** [comment]
Ah, Feature Request. I would leave it as is (I personally find the "describe alternatives" just a pointless exercise to make people jump through hoops -- much better to just close and ask them to expand on poor requests.)

Really, the only thing to do is to be _very_ aggressive in insta-closing bug reports (don't even read them!) that don't use the template. Use a canned response to reduce the effort for it (and drive the point home).

**Comment by Conni2461** [comment]
Maybe you are right and i am overthinking this because i am actively maintaining/reading issues again :laughing:

**Comment by clason** [comment]
I feel you... ;) Unfortunately, this can't be fully automated and requires the human touch (or slap, in this case).

**Comment by Conni2461** [comment]
yeah i know. I've seen your work in nvim-treesitter.

I think you are right here and we can close this issue. Thanks for your insight :)
