### ISSUE TITLE
Picker for multiple quickfix lists

### ISSUE THREAD

**Issue by timsofteng** [nvim-telescope/telescope.nvim#1877]
**Is your feature request related to a problem? Please describe.**
I've found quickfix lists in (neo)vim is very powerful solution. Especially it shines with `cdo`. If I get correctly cdo works on current qflist. With `cdo undo` it is very flexible feature. Would be nice to pick some previous qflist to do something on that items or make undo.

**Describe the solution you'd like*
Just plain telescope picker which will contain all quickfix lists per session with their names and items in preview window and pick opens one.

**Describe alternatives you've considered**
Now I type `:cold` and `cnew` but it's slightly annoying.

**Additional context**
Nothing

**Comment by timsofteng** [comment]
@fdschmidt93 thanks for pr!
Just one note. Is it possible to restore list into the native quickfix list? Not into telescope picker.
Like second option

**Comment by fdschmidt93** [comment]
You are very free to write your own custom actions for this picker. Please consider _contributing_ as opposed to requesting features that are very individual to your workflow.

That said,

```lua
-- in telescope setup
    quickfixhistory = {
      mappings = {
        i = {
          ["<C-s>"] = function(prompt_buf)
            local entry = action_state.get_selected_entry()
            actions.close(prompt_buf)
            vim.cmd(string.format("%schistory | copen", entry.nr))
          end
        }
      }
```

seems to do the job.
