### ISSUE TITLE
Show files which was force added despite of gitignore

### ISSUE THREAD

**Issue by timsofteng** [nvim-telescope/telescope.nvim#1888]
**Is your feature request related to a problem? Please describe.**
I'm trying to organize my dotfiles and I've found Drew's method most elegant.
https://drewdevault.com/2019/12/30/dotfiles.html

It means user inits git repo in home and all files to gitignore.
Than force add files which should be tracked.
The problem is `find_files` picker doesn't  show force added files. I don't know how to configure it to respect this files in terms of global gitignore.
Here is command which I use:
`find_files find_command=rg,--hidden,--files`

**Describe the solution you'd like**
Somehow show force added files to git.

**Additional context**
`nvim-tree` show it well.
![image](https://user-images.githubusercontent.com/51912173/165631605-91cf5987-91b1-4a57-af51-5ee509d6d8a3.png)

**Comment by fdschmidt93** [comment]
This is not a telescope but `rg` or `fd` (whatever you're using for `telescope.builtin.find_files`) issue.

Check their documentation on how to configure the command s.t. they list files that are ignored but force-added.

Nothing we can do or should be doing here AFAIK. Closing as `wontfix`.

**Comment by Conni2461** [comment]
`rg` and `fd` dont work like that. They look at the gitignore and the directory and ignore everything that is in the config. They dont ask git.

If you need something like that you HAVE to go immediately to git. We have `Telescope git_files` for that which uses `git ls-files` under the hood.

To support this we would actually need to look inside the `.git` folder and thats just a waste of time
