### ISSUE TITLE
Failed to call `nvim_create_user_command` because it's a nil value

### ISSUE THREAD

**Issue by ominusliticus** [nvim-telescope/telescope.nvim#1890]
### Description

I just ran the command `:PlugUpdate` on my init.vim file, and the next nvim session gave this error message
![image](https://user-images.githubusercontent.com/44349307/165646956-2ab47154-79c1-4621-90fb-25c8841daac4.png)

### Neovim version

```markdown
NVIM v0.7.0-dev
Build Type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

WSL 0.2.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary install.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 11.0.2
  - OK: fd: found fd 7.4.0

## ===== Installed extensions =====

## Telescope Extension: 'fzf'
  - INFO: No healthcheck provided
```

### Steps to reproduce

In the `init.vim` file
```lua
    Plug 'nvim-lua/plenary.nvim'
    Plug 'nvim-telescope/telescope.nvim'
```

then run `nvim` command in terminal

### Expected behavior

No error messages 

### Actual behavior

![image](https://user-images.githubusercontent.com/44349307/165646956-2ab47154-79c1-4621-90fb-25c8841daac4.png)

### Minimal config

```Lua
call plug#begin('~/.config/nvim/plugged')
    Plug 'nvim-lua/plenary.nvim'
    Plug 'nvim-telescope/telescope.nvim'
call plug#end()

-- call configure files

**Comment by fdschmidt93** [comment]
Please update to latest neovim stable to fix this issue.

Dup of #1880
