### ISSUE TITLE
Telescope won't open in neovim update

### ISSUE THREAD

**Issue by data-stepper** [nvim-telescope/telescope.nvim#1893]
### Description

I just updated my system (including neovim), all packages from vim-plug, and am now getting an error every time I open neovim. Also no telescope commands work anymore (as if the plugin was not installed). The exact error I am getting is:
```
Error detected while processing /home/bent/.local/share/nvim/plugged/telescope.nvim/plugin/telescope.lua:
E5113: Error while calling lua chunk: ...l/share/nvim/plugged/telescope.nvim/plugin/telescope.lua:108: attempt to call field 'nvim_create_user_command' (a nil value)
stack traceback:
        ...l/share/nvim/plugged/telescope.nvim/plugin/telescope.lua:108: in main chunk
```

My config ( and also the minimal config I tried ) is still an init.vim as I didn't fully switch to lua yet.
In the minimal init.vim I didn't load the nvim_treesitter module but I suspect that this is not an issue since the bug still persists. Also the checkhealth output comes from my complete init.vim configuration.

### Neovim version

```markdown
NVIM v0.7.0-dev+1328-gfb5587d2b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az121-717
```

### Operating system and version

Arch Linux with kernel 5.17.4-arch1-1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities
```

### Steps to reproduce

1. Update neovim ( from neovim-nightly-bin in the AUR )
2. Start neovim

### Actual behavior

Telescope doesn't work anymore completely.

### Minimal config

```Lua
set nocompatible
filetype off

call plug#begin()
" Now using telescope
" Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

" Neovim telescope setup
map <leader>t :Telescope<CR>
map <C-t> :Telescope<CR>
map <F3> :Telescope<CR>

" Some more specific telescope mappings
map <C-f> :Telescope find_files<CR> 
map <C-b> :Telescope buffers<CR> 
map <C-r> :Telescope oldfiles<CR>
```

**Comment by data-stepper** [comment]
Updating to 0.8 fixed my issue, sorry that I didn't read that earlier closing this now.

**Comment by anrie** [comment]
@data-stepper I noticed the same problem after updating telescope to the latest version. 

But all I found were references to a minimum requirement of Neovim 0.7 which is what I am using. Pinning packer to the `nvim-0.6`-Tag solves the issue. 

Could you point me to where 0.8 (nightly) is explicitly mentioned? Thanks!

**Comment by data-stepper** [comment]
So as I mentioned I am using vim-plug not packer as my package Manager so I don't know what you mean by that nvim-0.6 tag.

All I did to solve the issue was update the neovim-nightly-bin package in the AUR using yay. When asked I also chose to clean build the package.

That solved the issue for me but I am sure the issue still persists in nvim 0.7 as I have seen in a similar GitHub issue.

**Comment by fdschmidt93** [comment]
> Could you eventually point me to where 0.8 (nightly) is explicitly mentioned as a requirement for the latest telescope master? Thanks!

Latest `neovim`-`stable` (0.7 was released 2 weeks ago) is a requirement as opposed to _any_ 0.7 version.

> But all I found were references to https://github.com/nvim-telescope/telescope.nvim/issues/1470#issuecomment-1104415773 which is what I am using.

You are most likely on an outdated 0.7-`dev` version as opposed to the stable release.

I'll refine the wording of that breaking change post.

**Comment by Conni2461** [comment]
> Telescope requires now Neovim release 0.7.0 or a more recent nightly. 
If you are running Neovim nightly, you need to make sure that you are on the
LATEST version. Every other commit is not supported. So make sure you build
the newest nightly before reporting issues.

From the changelog that is linked the the comment. If you are running nightly its your responsibility to keep it up to date.

The minimum version is also mentioned in the readme

**Comment by anrie** [comment]
Hey! Thanks for the feedback.

Correct me if I am wrong, but I was under the impression that this points to the latest stable version?: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage At least it currently points to https://github.com/neovim/neovim/releases/tag/v0.7.0 and I downloaded the image after the official release.

Also `:version` doesn't mention dev or nightly:
```:version 
NVIM v0.7.0                                                                                                                                                                                                                  
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
I see if using a more recent release changes the situation.

**Comment by fdschmidt93** [comment]
Then please open a new issue with minimal reproduction steps, because with extremely high certainty, you do not get 

`attempt to call field 'nvim_create_user_command'`

as an error that prevents you from opening telescope, but something else.

`:lua print(vim.api.nvim_create_user_command)` must print a function reference with the linked appimage (I just confirmed).

**Comment by anrie** [comment]
@fdschmidt93 Thanks for the explanation and the hints!

I really had no intend to hijack this issue and will open an new issue if needed. 
It's just that I found the issue in the tracker and simply wanted to verify that I didn't miss/misunderstood some announcement.
