### ISSUE TITLE
Error while jumping to error if the file is not saved

### ISSUE THREAD

**Issue by singalhimanshu** [nvim-telescope/telescope.nvim#19]
There's an error when trying to jump to an error and that line is not written on the file.
```
|| E5108: Error executing lua ...hu/.vim/plugged/telescope.nvim/lua/telescope/actions.lua:65: Vim(edit):E37: No write since last change (add ! to override)
```

**Comment by tjdevries** [comment]
I think you need `set hidden`? This happens any time you try and leave a file that is not saved, right?

**Comment by himansingh241** [comment]
> I think you need `set hidden`? This happens any time you try and leave a file that is not saved, right?

I do have `set hidden` in my config

**Comment by tjdevries** [comment]
Does this still happen?

**Comment by the-codingguy** [comment]
Yup it does.

**Comment by tami5** [comment]
@tjdevries I'm getting similar issue, If I have unwritten edits and I want to jump to a section of the file with lsp document symbols or even with fd it prompts me to save changes to the current file. 

```
Save changes to "/home/tami/.local/share/nvim/site/pack/packer/opt/telescope.nvim/lua/telescope/finders.lua"?
[Y]es, (N)o, (C)ancel:

```
I think this is related to an option I have: `set confirm`

BTW: this doesn't happen with buffer fuzzy

**Comment by tjdevries** [comment]
Anyone still having this?

**Comment by singalhimanshu** [comment]
> Anyone still having this?

Nope

**Comment by tami5** [comment]
Still happens to me sometimes @tjdevries

**Comment by Conni2461** [comment]
I remember ober and me fixing this issue some time ago. Closing for now
