### ISSUE TITLE
Telescope vertical layout preview order

### ISSUE THREAD

**Issue by axieax** [nvim-telescope/telescope.nvim#1903]
**Is your feature request related to a problem? Please describe.**

I usually use the `horizontal` layout, but it's frustrating when the previewer doesn't display on smaller screens (I'm currently using a `preview_width` of 0.6 which looks great on larger screen sizes), especially since there is no option to set a minimum or maximum width. As such, I've played around with the `vertical` layout which seems to meet my needs of fitting the previewer on the screen, but it's inconvenient that I cannot customise the prompt to appear at the top of the stack, which is what I'm used to with `horizontal` with `prompt_position` top.

**Describe the solution you'd like**

I would like the ability to move preview to the bottom of the stack. There is an option for `prompt_position`, which places it in between Preview and Result.

Desired behaviour:

```
┌──────────────────────────────────────────────────┐
│                                                  │
│    ┌────────────────────────────────────────┐    │
│    |                 Prompt                 |    │
│    └────────────────────────────────────────┘    │
│    ┌────────────────────────────────────────┐    │
│    |                 Result                 |    │
│    |                 Result                 |    │
│    └────────────────────────────────────────┘    │
│    ┌────────────────────────────────────────┐    │
│    |                 Preview                |    │
│    |                 Preview                |    │
│    |                 Preview                |    │
│    └────────────────────────────────────────┘    │
│                                                  │
└──────────────────────────────────────────────────┘
```

Diagram adapted from [default](https://github.com/nvim-telescope/telescope.nvim/blob/57bd8a500213c274558f253478a11fd77e4c9fcb/lua/telescope/pickers/layout_strategies.lua#L638-L660).

**Describe alternatives you've considered**

I've tried playing around with `layout_config`, but it seems like there's limited customizability offered.

**Additional context**

**Comment by Conni2461** [comment]
```lua
    layout_config = {
      vertical = {
        prompt_position = "top",
        mirror = true,
      },
    }
```

also see `help telescope.layout.vertical()`. Does this work for you?

**Comment by axieax** [comment]
Omg can't believe I missed the `mirror` option. Thank you so much!

**Comment by Tony-Sol** [comment]
I guess, `mirror = true` is aslo invert results list, which is kinda awkward

**Comment by unlimitedsola** [comment]
> ```lua
>     layout_config = {
>       vertical = {
>         prompt_position = "top",
>         mirror = true,
>       },
>     }
> ```
> 
> also see `help telescope.layout.vertical()`. Does this work for you?

This is very helpful! Do you know how to reverse the listing direction so it fills from top to bottom instead?
