### ISSUE TITLE
Ability to set a maximum and minimum width/height for layout

### ISSUE THREAD

**Issue by axieax** [nvim-telescope/telescope.nvim#1904]
**Is your feature request related to a problem? Please describe.**

Configuring a general layout to fit all screen sizes is extremely difficult with the customisation options. For example, I want to set a maximum width to ensure a percentage width doesn't extend too far for larger screen sizes; I want to set a minimum width to ensure there is adequate space for the previewer in smaller screen sizes.

**Describe the solution you'd like**

Instead of just passing a value for `width` and `height` under `layout_config`, it would be nice to also pass these minimum and maximum values in a table, e.g.

```lua
center = {
  width = { 0.5, max = 70 },
}
```

**Describe alternatives you've considered**

I've tried all the layout options with customisations (found #1903 when trying to find an alternative to this), but none which work for a general layout regardless of screen size.

**Additional context**

**Comment by Conni2461** [comment]
Currently `width` and `height` can be a function as well. Can you try if this is what you requested? If yes i'll implement a user friendly interface for it and open a PR

```lua
        width = function(_, max_columns)
          local percentage = 0.5
          local max = 70
          return math.min(math.floor(percentage * max_columns), max)
        end,
        height = function(_, _, max_lines)
          local percentage = 0.5
          local min = 70
          return math.max(math.floor(percentage * max_lines), min)
        end
```

**Comment by axieax** [comment]
Perfect! Thanks again :D

**Comment by Conni2461** [comment]
i think i still implement a simplified interface later

**Comment by Conni2461** [comment]
Can you test https://github.com/nvim-telescope/telescope.nvim/pull/2002

`width = { 0.5, max = 70, min = 123 }` is implemented on that branch. First val must be 0 <= val < 1 and only `min` or `max` is set as a fixed number.

Also described here: `telescope.resolve.resolve_width` and `telescope.resolve.resolve_height`

**Comment by Conni2461** [comment]
merged in current dev branch, will hit master soon

**Comment by unphased** [comment]
How can I make use of this to override the minimum height/width? I'm using code actions with the telescope picker via https://github.com/nvim-telescope/telescope-ui-select.nvim and i'm configuring without borders to minimize wasted space. 

Notice how there remains huge amounts of wasted space. 

<img width="889" alt="image" src="https://github.com/nvim-telescope/telescope.nvim/assets/1542910/23f23ecc-7429-49d3-b9f1-b848b25d1d9e">
