### ISSUE TITLE
live_grep on word under cursor stopped working

### ISSUE THREAD

**Issue by KiLLeRRaT** [nvim-telescope/telescope.nvim#1911]
### Description

I have had this mapping for quite some time, and use it quite a lot.  This mapping will open Telescope, and prefill what's under my cursor. E.g. doing a file search with what's under my cursor.

```
nnoremap <expr> <leader>fF ':Telescope find_files<cr>' . "'" . expand('<cword>')
```

Recently it stopped working, and I'm not sure exactly why.  I've updated all my plugins and Neovim very recently, so thought it is related to that.

I have figured out that it breaks on the following commit of Telescope: 

```
cc1a344 fix: fix keep insert when going from telescope window to telescope window (#1600)
```
It may be because of this line that was added: https://github.com/nvim-telescope/telescope.nvim/commit/cc1a3440f9ba6f28a8ca0bfff867f60c2d80c353#diff-9ac2063a221b713185ddb6df3157cf01edf3b12894c2ae984e14250bf16ebd89R444

I'm not 100% sure though.

### Neovim version

```markdown
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az320-113
```

### Operating system and version

Windows 10 Pro 21H2, 19044.1645

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====

## Telescope Extension: `hop`
  - INFO: No healthcheck provided
```

### Steps to reproduce

Open a file, and hit my keymap as above, `<leader>fF` it should open Telescope, and prefil what was under my cursor.

### Actual behavior

Telescope opens, but nothing is prefilled.

I have simplied things to see if it's related to cword or something, but even the following doesn't prefill anything:

```
nnoremap <expr> <leader>fG ':Telescope live_grep<cr>hello'
```

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
This was never an interface

The real way of doing that would have been and still is `:Telescope find_files default_text=asdf` or `:Telescope live_grep default_text=asdf`, etc ...

**Comment by Conni2461** [comment]
That it no longer works is a dup of #1898 i think

**Comment by KiLLeRRaT** [comment]
Hi @Conni2461 thanks for getting back to me.

I must have stumbled upon some weird glitch that allowed that to work in the past.  I've since updated my mappings to the following and they work beautifully!

```
nnoremap <leader>fF :execute 'Telescope find_files default_text=' . "'" . expand('<cword>')<cr>
nnoremap <leader>fG :execute 'Telescope live_grep default_text=' . expand('<cword>')<cr>
```

Not sure if that's the 100% correct way, but seems to work :)

Cheers and thanks for your time!

**Comment by gaving** [comment]
It appears there is `builtin.grep_string` for this very thing, e.g.

`:Telescope grep_string`

<img width="711" alt="image" src="https://user-images.githubusercontent.com/43741/177027326-975b2b90-8fb5-4593-949c-6f1fdc5ead06.png">

**Comment by space-blaster** [comment]
> It appears there is `builtin.grep_string` for this very thing, e.g.
> 
> `:Telescope grep_string`
> 
> <img alt="image" width="711" src="https://user-images.githubusercontent.com/43741/177027326-975b2b90-8fb5-4593-949c-6f1fdc5ead06.png">

this is great. finally find this solution, pretty neat. thanks.

**Comment by Innei** [comment]
> It appears there is `builtin.grep_string` for this very thing, e.g.
> 
> `:Telescope grep_string`
> 
> <img alt="image" width="711" src="https://user-images.githubusercontent.com/43741/177027326-975b2b90-8fb5-4593-949c-6f1fdc5ead06.png">

How to disable this feature?
