### ISSUE TITLE
segfault when previewing markdown files

### ISSUE THREAD

**Issue by max397574** [nvim-telescope/telescope.nvim#1916]
### Description

I get segfaults when previewing markdown files (not randomly but every time)
I tested this with live-grep and find-files

I can prevent it with this code snippet from the wiki:
```lua
local _bad = { ".*%.md" } -- Put all filetypes that slow you down in this array
local bad_files = function(filepath)
  for _, v in ipairs(_bad) do
    if filepath:match(v) then
      return false
    end
  end

  return true
end

local new_maker = function(filepath, bufnr, opts)
  opts = opts or {}
  if opts.use_ft_detect == nil then opts.use_ft_detect = true end
  opts.use_ft_detect = opts.use_ft_detect == false and false or bad_files(filepath)
  previewers.buffer_previewer_maker(filepath, bufnr, opts)
end

require("telescope").setup {
  defaults = {
    buffer_previewer_maker = new_maker,
  }
}
```

### Neovim version

```markdown
NVIM v0.8.0-dev+nightly-1774-g815b65d77
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 11.4

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

not possible with minimal config

### Expected behavior

No errors

### Actual behavior

Segfault

### Minimal config

```Lua
I can't reproduce this with a minimal config
here is my config where it happens: https://github.com/max397574/NeovimConfig/tree/c599e7031c49cfce5e7f703c0fcd545b33baeb4d
```

**Comment by Conni2461** [comment]
If you get segfaults you kinda have to provide a coredump. At least the stacktrace that you get from doing. (no idea how to do this on mac thought)

But i kinda know what it is. Can you uninstall the markdown tree-sitter parser? And try to reproduce again. That parser is known for segfaulting neovim and i would advice against using it.

**Comment by max397574** [comment]
no it's not a problem with markdown treesitter, already tried this
atm it looks like it has something to do with neorg but I have to look into this

**Comment by clason** [comment]
>  That parser is known for segfaulting neovim and i would advice against using it.

I don't think that's (as) true anymore -- the parser we currently use has performance issues (especially with many injections), but I'm not aware of recent reports of segfaulting.

You can try with the latest master, though; I just bumped LuaJIT to a commit that claims to have fixed a segfault people have been sporadically reporting.

Otherwise I have to agree with @Conni2461 : If you can't provide a minimal reproducible example _without_ other plugins, there's nothing we can do here. (You can't expect people to sift through and test your full config.)

**Comment by Conni2461** [comment]
> I'm not aware of recent reports of segfaulting

My bad havent tried that parser in months :laughing: 

> If you can't provide a minimal reproducible example without other plugins, there's nothing we can do here

Or provide at least a coredump, just anything more than "it segfaults when previewing markdown"

**Comment by max397574** [comment]
my neovim is like 10 minutes old atm
and I managed to get a kinda minimal config which uses neorg but it doesn't work for anyone.
So I think I can move this issue over to neorg
