### ISSUE TITLE
Telescope lsp_code_action  is no longer available

### ISSUE THREAD

**Issue by NikosEfthias** [nvim-telescope/telescope.nvim#1919]
### Description

after recent update Telescope lsp_code_action no longer an available option

### Neovim version

```markdown
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"
```

### Operating system and version

macOS 12.3.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====
```

### Steps to reproduce

1. :Telescope lsp_code_action

### Expected behavior

code action popup

### Actual behavior

an run error popup indicating no such command exists any more

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by iwfan** [comment]
Hi @NikosEfthias,  You should check the  [Notice of Breaking Changes](https://github.com/nvim-telescope/telescope.nvim/issues/1470#issuecomment-1106707726) first.

`lsp_code_action` and `lsp_range_code_action` has been removed in #1866 

For Now, You can use  the Neovim built-in code action as alternative.
```
vim.api.nvim_buf_set_keymap(bufnr, 'n', '<space>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
```

**Comment by NikosEfthias** [comment]
builtin one works fine but doesnt have fuzy search or no search at all :) thanks for the info tho

**Comment by Conni2461** [comment]
`vim.lsp.buf.code_action()` is not an alternative it is the way to go from now on. Plugins should not decide to try and reimplement code_actions anymore. Neovim has a perfectly working working builtin and you can switch the underlying ui with whatever you need. Even telescope and that is also explained in `help telescope.changelog-1866`

You can have fuzzy finding if you set telescope as ui for `vim.ui.select`. The idea behind that is that people can just feed data into that function and the user can decide the underlying ui to be telescope, fzf, ... So all these plugins dont have to implement the same set of functions that feed the data into the engines. This only happens at one place.

So i suggest using https://github.com/nvim-telescope/telescope-ui-select.nvim to get code_actions back as they where before. I made sure that the displaying mimics the builtin version before removing those builtins. I only forget to put in a proper removal message on calling `:Telescope lsp_code_actions` that was my bad and i apologize for the inconvenience

**Comment by undg** [comment]
@Conni2461 thanks for the explanation, that has perfect sense now for me.
@knpwrs with your commit as a reference it's even more transparent what's going on.
