### ISSUE TITLE
the doc does not find how to configure the find file, the configuration method is to start from the project root directory

### ISSUE THREAD

**Issue by 505384662** [nvim-telescope/telescope.nvim#1921]
在doc中没有找到怎么配置 find file的时候是从项目根目录开始查找的配置方法
![image](https://user-images.githubusercontent.com/31720616/166884388-0927d7a3-fa72-4789-80b9-fd5809aef1e2.png)
比如现在目录是在config/nvim/lua/core 下
现在想从config路径下搜索，找了半天 doc中并没有配置方法

**Comment by Shougo** [comment]
Please open the issue in English.

**Comment by 505384662** [comment]
Okay~~
the doc does not find how to configure the find file, the configuration method is to start from the project root directory，
![image](https://user-images.githubusercontent.com/31720616/166885585-43b03b7f-fe6a-4041-8b81-4b9a82e1fd01.png)

For example, the current directory is  ‘config / nvim / Lua / core‘

Now I want to search from the ~/.config path. I've been searching for a long time. There is no configuration method in doc

**Comment by Shougo** [comment]
Please fix the title in English.

**Comment by 505384662** [comment]
ok~

**Comment by Shougo** [comment]
Please see the issue.

https://github.com/nvim-telescope/telescope.nvim/issues/592

The feature seems already supported.

**Comment by fdschmidt93** [comment]
Thanks @Shougo ! If I correctly follow the issue, it can be closed.

Please let us know otherwise (ideally in English).
