### ISSUE TITLE
how to search with selected text in visual mode ? 

### ISSUE THREAD

**Issue by ifnk** [nvim-telescope/telescope.nvim#1923]
like this 

![dudu](https://user-images.githubusercontent.com/39295458/167047589-37203963-67ee-4816-b972-8fb2fae7b120.gif)

**Comment by adoyle-h** [comment]
```lua
function vim.getVisualSelection()
	vim.cmd('noau normal! "vy"')
	local text = vim.fn.getreg('v')
	vim.fn.setreg('v', {})

	text = string.gsub(text, "\n", "")
	if #text > 0 then
		return text
	else
		return ''
	end
end


local keymap = vim.keymap.set
local tb = require('telescope.builtin')
local opts = { noremap = true, silent = true }

keymap('n', '<space>g', ':Telescope current_buffer_fuzzy_find<cr>', opts)
keymap('v', '<space>g', function()
	local text = vim.getVisualSelection()
	tb.current_buffer_fuzzy_find({ default_text = text })
end, opts)

keymap('n', '<space>G', ':Telescope live_grep<cr>', opts)
keymap('v', '<space>G', function()
	local text = vim.getVisualSelection()
	tb.live_grep({ default_text = text })
end, opts)
```

**Comment by fdschmidt93** [comment]
Many thanks! That's exactly one of the ways to go about it.

Eventually, neovim will probably have an `get_visual_selection` function (there's a PR somewhere, the output of which then can be passed to any picker via `default_text`.

So I think we can close this.

**Comment by ifnk** [comment]
> ```lua
> function vim.getVisualSelection()
> 	vim.cmd('noau normal! "vy"')
> 	local text = vim.fn.getreg('v')
> 	vim.fn.setreg('v', {})
> 
> 	text = string.gsub(text, "\n", "")
> 	if #text > 0 then
> 		return text
> 	else
> 		return ''
> 	end
> end
> 
> 
> local keymap = vim.keymap.set
> local tb = require('telescope.builtin')
> local opts = { noremap = true, silent = true }
> 
> keymap('n', '<space>g', ':Telescope current_buffer_fuzzy_find<cr>', opts)
> keymap('v', '<space>g', function()
> 	local text = vim.getVisualSelection()
> 	tb.current_buffer_fuzzy_find({ default_text = text })
> end, opts)
> 
> keymap('n', '<space>G', ':Telescope live_grep<cr>', opts)
> keymap('v', '<space>G', function()
> 	local text = vim.getVisualSelection()
> 	tb.live_grep({ default_text = text })
> end, opts)
> ```

thanks !

**Comment by gegoune** [comment]
I am trying to pair it up with `cword` search like:

```lua
local getVisualSelection = function()
  vim.cmd 'noau normal! ""'
  local text = vim.fn.getreg 'v'
  vim.fn.setreg('v', {})

  text = string.gsub(text, '\n', '') -- text is always "" for v mode
  if #text > 0 then
    return text
  else
    return vim.fn.expand '<cword>' or ''
  end
end

vim.keymap.set({ 'n', 'v' }, '|', function()
  local text = getVisualSelection()
  require('telescope').extensions.live_grep_raw.live_grep_raw { default_text = text }
end, opts)
```

but it doesn't work as expected for visual mode - always returns `cword`. Any idea why?
Thanks!

**Comment by theZetrax** [comment]
> I got this error triggered by "noau normal! 'vy'"
> 
> ```
> E20: Mark not set
> ```

@towry it's `"vy"` that's for copying to a register

**Comment by ronandalton** [comment]
One small improvement to @adoyle-h's solution:

Replacing
`tb.live_grep({ default_text = text })`
with
`tb.grep_string({ search = text })`
will make it so that you don't need to go through manually and escape regex characters if your search string contains them. This will allow searches for selections like `.length()` to work as expected.

**Comment by the-main-thing** [comment]
Updated working version where the clipboards's value is not getting overwritten by the selected text:
```lua

function vim.getVisualSelection()
	local current_clipboard_content = vim.fn.getreg('"')

	vim.cmd('noau normal! "vy"')
	local text = vim.fn.getreg('v')
	vim.fn.setreg('v', {})

	vim.fn.setreg('"', current_clipboard_content)

	text = string.gsub(text, "\n", "")
	if #text > 0 then
		return text
	else
		return ''
	end
end

local keymap = vim.keymap.set
local tb = require('telescope.builtin')
local opts = { noremap = true, silent = true }

keymap('n', '<space>g', ':Telescope current_buffer_fuzzy_find<cr>', opts)
keymap('v', '<space>g', function()
	local text = vim.getVisualSelection()
	bt.current_buffer_fuzzy_find({ default_text = text })
end, opts)

keymap('n', '<space>G', ':Telescope live_grep<cr>', opts)
keymap('v', '<space>G', function()
	local text = vim.getVisualSelection()
	bt.grep_string({ search = text })
end, opts)


```

**Comment by Geremia** [comment]
@the-main-thing What keys do I press to execute this? (I'm new to NeoVim.)

**Comment by the-main-thing** [comment]
@Geremia sorry I am answering three months later. When you see a string like `"<space>G"` or `"<leader>G"` this means that this is the key combination. For `"<space>G"` you press the space and then the "G" key. One after another. There is timeout after hitting "space". Usually about 1 second. So pressing "space" + waiting for a second will do nothing (or move cursor).

The `<leader>` thing refers to the key that has been set up as a "leader" key. For example I have this lua code in one of my config files:
```lua
vim.g.mapleader = " "
```
This means that now the "leader" key is the space key. And all the settings with something like `"<leader>G"` are equivalent for `"<space>G"`
