### ISSUE TITLE
Provide an option for find_files: search on filenames only

### ISSUE THREAD

**Issue by kjgfcdb** [nvim-telescope/telescope.nvim#1928]
Hello, I'm facing a problem that when I use the `find_files` command and type in some words, the fuzzy search engine always give me the results based on the **full path** of each file. For example, I have a folder like that:
![barfoo](https://user-images.githubusercontent.com/15307944/167290074-72d8b9fd-8c73-46b0-85eb-a42620c11102.jpg)

If I call the `find_files` command and type in `foo`, I got the following results
![foobar](https://user-images.githubusercontent.com/15307944/167290233-cb1025cb-b2b9-4a3d-b235-c0dbcfaa69ad.jpg)

Obviously, pattern `foo` matches `./foo/bar` and `./foo/foo`. Is it possible to add an option to let the fuzzy search engine only use the **basename** of each file so that in the example above, we can keep `./foo/foo` only and get rid of `./foo/bar`?

Thank you!

**Comment by Conni2461** [comment]
Take a look at this extension https://github.com/natecraddock/telescope-zf-native.nvim

**Comment by kjgfcdb** [comment]
@Conni2461 Thanks! It works!
