### ISSUE TITLE
Can't change the background of Borders

### ISSUE THREAD

**Issue by felipesere** [nvim-telescope/telescope.nvim#1936]
### Description

I'm trying to use a lighter background across all Float windows to make them stand out better.
To achieve that I use
```lua
vim.api.nvim_set_hl(0, "FloatBorder", {bg="#3B4252", fg="#5E81AC"})
vim.api.nvim_set_hl(0, "NormalFloat", {bg="#3B4252"})
vim.api.nvim_set_hl(0, "TelescopeNormal", {bg="#3B4252"})
vim.api.nvim_set_hl(0, "TelescopeBorder", {bg="#3B4252"})
```

But the `TelescopeBorder` line has no effect at all.
<img width="1244" alt="Screenshot 2022-05-14 at 22 51 41" src="https://user-images.githubusercontent.com/1850188/168461781-2482cdca-d9d9-429c-8714-d7b90fd60c27.png">

### Neovim version

```markdown
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS 12.3.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:Telescope find_files`

Check the background color of the borders.

### Expected behavior

The background (bg) of the borders to match the background of the float window

### Actual behavior

The background of the borders retains its default color.

### Minimal config

```Lua
vim.opt.termguicolors = true
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      'shaunsingh/nord.nvim',
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE

  -- The color scheme I use
  vim.cmd[[colorscheme nord]]

  -- slightly brighter background to make the float pop more
  vim.api.nvim_set_hl(0, "FloatBorder", {bg="#3B4252", fg="#5E81AC"}) 
  vim.api.nvim_set_hl(0, "NormalFloat", {bg="#3B4252"})
  vim.api.nvim_set_hl(0, "TelescopeNormal", {bg="#3B4252"})
  vim.api.nvim_set_hl(0, "TelescopeBorder", {bg="#3B4252"})
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
I'm pretty sure that's because those are not the relevant highlight groups, which you can find here (`Telescope{Prompt, Results, Preview}Border`): https://github.com/nvim-telescope/telescope.nvim/blob/39b12d84e86f5054e2ed98829b367598ae53ab41/plugin/telescope.lua#L11-L91

**Comment by Conni2461** [comment]
`TelescopeBorder` should work and effect all borders at the same time. It also does for me. I just think you are using it wrong and should reread `nvim_set_hl` and `synIDattr` docs. Also interesting `highlight-ctermbg` and `termguicolors`

If you dont have `set termguicolors` then you have to use `{ctermbg=210}`

![image](https://user-images.githubusercontent.com/15233006/168463746-4ca95b10-8e3a-49a9-b6bb-0bd6e902630b.png)

**Comment by felipesere** [comment]
I have `vim.opt.termguicolors = true` (updated the minimal config) set in my `init.lua`.

I also tried your last line with and without `termguicolors`, being well aware that it should work when `vim.opt.termguicolors = false`.
Not quite sure what else to read from nvim_set_hl?

**Comment by Conni2461** [comment]
Sorry i can legit not reproduce. I assumed you only missed `termguicolors` because that was missing

![image](https://user-images.githubusercontent.com/15233006/168488111-390741e5-11d9-4eed-9546-42e804e41e55.png)

you should check with `hi TelescopeBorder` if the color is actually set

**Comment by felipesere** [comment]
The below screenshot is from the minimal.lua.

The highlights are set to the right value but not used.

![Screenshot 2022-05-15 at 21 32 11](https://user-images.githubusercontent.com/1850188/168492691-2313105b-7599-44f6-ab4e-30ff722aabf2.png)

BUT (!) if I set `TelescopePreviewBorder` then the the preview window looks right!

**Comment by Conni2461** [comment]
> BUT (!)

I love this. Why `!` ...

Never mind i found your issue. And we are not the issue its nord.nvim:

https://github.com/shaunsingh/nord.nvim/blob/e0f536da5716288021bb53d6167a36434b11ba79/lua/nord/theme.lua#L426-L428

They unlink the default links that we set here

https://github.com/nvim-telescope/telescope.nvim/blob/39b12d84e86f5054e2ed98829b367598ae53ab41/plugin/telescope.lua#L27-L30

So `TelescopePromptBorder` does no longer link to `TelescopeBorder`, same is true for the other two. (`TelescopeBorder` is only a shorthand on which the others link, Its not actually used). So you have to set all 3 values or you open an issue at nord.nvim.

Next time. Check without a custom colorscheme plugin ... This is resolved for me

**Comment by felipesere** [comment]
Awesome. Brilliant! Sorry for the extra work!

**Comment by Conni2461** [comment]
Thank you very much for the sponsor, i really appreciate it :)
