### ISSUE TITLE
telescope 0.1 release announcement

### ISSUE THREAD

**Issue by Conni2461** [nvim-telescope/telescope.nvim#1938]
Hey,

we(tj, @fdschmidt93 and me) had our first telescope maintainer meeting a couple of days ago, and we discussed the first release, which is only a couple of weeks away. We plan to release telescope 0.1 on July 12, the second birthday of telescope.
 
Foremost, I have to thank a tone of people. Thanks to all 220 people who contributed to telescope, thanks to everyone that opened issues and discussed problems and improvements. We almost have 1000 commits on the main branch, most of them squashed. It's insane what the community achieved in the past two years. We are really grateful for your support.

Coming back to the release. We discussed a couple of things, including features we want to have included in the first release and some breaking changes/cleanup we want to do prior to the release. To make these breaking changes easier for end users, we decided we merge them into a separate [dev](https://github.com/nvim-telescope/telescope.nvim/tree/dev) branch and write a changelog for every breaking change before everything will then be merged in master.
The general timeline will be a feature freeze in around 4 weeks, 1/2 weeks later we merge the [dev](https://github.com/nvim-telescope/telescope.nvim/tree/dev) branch into master and release a first release candidate. Following by the 0.1 release 2/3 weeks later. We suggest not running the [dev](https://github.com/nvim-telescope/telescope.nvim/tree/dev) branch, though we appreciate everyone who is willing to testing it :) The master branch will for the time being only receiving necessary fixes.

You can follow the current development state here: https://github.com/nvim-telescope/telescope.nvim/projects/2 and I will go over all open issues and PRs in the next couple of days and check what could be done.

I'll leave this issue open for discussion, but I kindly ask you to open new issues for features you want to see in this release (or comment under the issue, if one already exists).

Edit: The dev PR can be tracked here: https://github.com/nvim-telescope/telescope.nvim/pull/1945

Edit 2:

> **Note**
> dev branch will receive regular rebases and force pushes. Only run it if you know what you do :)

Edit 3: Updated time schedule, see comment below (after a bunch of mentions)

**Comment by Conni2461** [comment]
took us a long time, a lot of work but here it is https://github.com/nvim-telescope/telescope.nvim/releases/tag/0.1.0

**Comment by mehalter** [comment]
Hey @Conni2461 regarding these tagged releases, is there a reason you are avoiding including features in the 0.1.x releases? I believe you are doing it because of the semantic versioning specification summary saying:

> PATCH version when you make backward compatible bug fixes

But that is not a fully valid statement in the specification. The fully valid statement is:

> Patch version Z (x.y.Z | x > 0) MUST be incremented if only backward compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.

So before v1.0.0 basically things shift downard. 0.x.0 release imply breaking changes and 0.1.x releases imply features and backwards compatible bug fixes.

Would we be able to get a 0.1.X release with all of the features of the past 2 years without breaking changes?
