### ISSUE TITLE
Make delete_buffer force deletion for terminal windows

### ISSUE THREAD

**Issue by TheMeaningfulEngineer** [nvim-telescope/telescope.nvim#1940]
**Is your feature request related to a problem? Please describe.**

The delete_buffer isn't handling the edge cases for the moment. 

**Describe the solution you'd like**

## Acceptance criteria:

- [x] Force buffer deletion for terminal
- [x] If the non-terminal buffer can't be deleted (because of unsaved changes)
    -  Print a human friendly error message
    -  Don't remove the item from the selection
- [ ] Add debug logs which would allow for deeper diagnostic if needed (if that exists as a mechanism)

**Comment by fdschmidt93** [comment]
If I understand it correctly, a PR for this seems very straightforward and would be very welcome :)

**Comment by TheMeaningfulEngineer** [comment]
Yup, planning to make a PR from this, looks like a nice first issue :)

**Comment by Conni2461** [comment]
#1943 was merged in the dev branch.
