### ISSUE TITLE
How to adjust window size

### ISSUE THREAD

**Issue by ray-x** [nvim-telescope/telescope.nvim#195]
It more breaks down to two questions. How to adjust flowing options:

1) In horizontal layout, the default preview window with
2) In vertical layout, dropdown theme, how to increase preview heigh.

I did something like:
```lua
lua require'telescope.builtin'.lsp_references(require('telescope.themes').get_dropdown({results_height = 20;width = 0.7;height=0.8}))

lua require'telescope.builtin'.lsp_references({preview_width = 0.6})
```
Seem does not working for me.

**Comment by tami5** [comment]
Me neither :D, I gave up on changing the size of the whole float window with preview option, for drop-down I manged to change the size with following  configuration simple

```lua
local dropdown = require('telescope.themes').get_dropdown({
  -- thanks to @pwntester
  winblend = 10;
  width = 0.5;
  prompt = '';
  results_height = 20;
  previewer = false;})

function tele.fd()
  local opts = vim.deepcopy(dropdown)
  opts.prompt_prefix = 'Files>'
  require'telescope.builtin'.fd(opts)
end

```

**Comment by ray-x** [comment]
I think, for horizontal layout, the preview window size was fixed as below:

```lua
  if self.previewer then
    preview.width = resolve.resolve_width(layout_config.preview_width or function(_, cols)
      if not self.previewer or cols < self.preview_cutoff then
        return 0
      elseif cols < 150 then
        return math.floor(cols * 0.4)
      elseif cols < 200 then
        return 80
      else
        return 120
      end
    end)(self, picker_width, max_lines)
  else
    preview.width = 0
  end
```

My monitor width is 365 when I run `echo winwidth(0)`, that makes the preview width (120) much less than result window because maxim size is fixed to 120 for preview.

I think if hard coded, maybe make it like this:
```lua
  if self.previewer then
    preview.width = resolve.resolve_width(layout_config.preview_width or function(_, cols)
      if not self.previewer or cols < self.preview_cutoff then
        return 0
      elseif cols < 150 then
        return math.floor(cols * 0.4)
      else
        return math.floor(cols * 0.6)
      end
    end)(self, picker_width, max_lines)
  else
    preview.width = 0
  end
```
For vertical, preview size was fixed here:
```lua
  prompt.line = (lines / 2) - ((max_results + (bs * 2)) / 2)
  results.line = prompt.line + 1 + (bs)

  preview.line = 1
  preview.height = math.floor(prompt.line - (2 + bs))
```

Would be great to have a ratio setup, so it more like
```
preview.height = math.floor(ratio*prompt.line - (2 + bs))
```

**Comment by tjdevries** [comment]
It is already supported, but I'm a bit behind on the documentation because I'm not 100% sure I'll keep it exactly this way.

For now, you need to put configuration for the layout in `layout_config` when running a builtin.

For example:

```lua
  require('telescope.builtin').find_files { 
    prompt_title = "~ dotfiles ~",                                                   
    shorten_path = false,     
    cwd = "~/.config/nvim",     
    height = 10,     
     
    layout_strategy = 'horizontal',     
    layout_config = {     
      preview_width = 0.65,     
    },     
  }  
```

`preview_width` can be:
1. a percentage
2. an exact number
3. a function, that can return the width you desire.

**Comment by tjdevries** [comment]
I will try and firmly decide & then document these this month :)

**Comment by ray-x** [comment]
Thanks @tjdevries 
Yes, it works. I think I did try this option before. The reason it failed is that I need to specify both `layout_strategy -> horizontal` and `preview_width`

Also, keen to know option to adjust the height in vertical/center layout.

**Comment by tami5** [comment]
@tjdevries adjusting the ration of the preview window to the list works great, but how to change the whole window size, I basically want half the default size.

Here's what won't work for me 

```lua
local withpreview = {
  width = 0.5;
  height = 0.5;
  }
```

**Comment by elianiva** [comment]
@tami5 I think what you want to change is `width_padding` and `height_padding`. It's the padding of the main neovim window and telescope window. If you make the padding bigger, the telescope window gets smaller.

You need to play around with the value though, I've tried to change it *slightly* (like, adding 0.05) and it changed quite a lot visually, it's probably because of my smol screen resolution :p

**Comment by Conni2461** [comment]
We just reworked how layout configuration worked to make configuration more consistent. See `help telescope.changelog` for the breaking changes and `help telescope.layout` for how to configure it.

Closing for now. Feel free to reopen

**Comment by Myzel394** [comment]
For anyone who wants to quickly copy and paste the config, here's how I did it with a 65% preview width:

```lua
require("telescope").setup({
    defaults = {
        layout_strategy = "horizontal",
        layout_config = {
            preview_width = 0.65
        },
    }
})
```
