### ISSUE TITLE
The results of lsp_definitions are different.

### ISSUE THREAD

**Issue by ryoppippi** [nvim-telescope/telescope.nvim#1953]
### Description

The results are different

![スクリーンショット 2022-05-21 14 34 01](https://user-images.githubusercontent.com/1560508/169654113-38390b98-8ee7-461d-ba21-f8747eb099a1.png)

![スクリーンショット 2022-05-21 14 34 26](https://user-images.githubusercontent.com/1560508/169654115-14961c0b-2538-4732-b718-12c83a32211e.png)

### Neovim version

```markdown
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS 12.3.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `changes`
  - INFO: No healthcheck provided

## Telescope Extension: `file_browser`
  - INFO: No healthcheck provided

## Telescope Extension: `frecency`
  - INFO: No healthcheck provided

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `heading`
  - INFO: No healthcheck provided

## Telescope Extension: `media_files`
  - INFO: No healthcheck provided

## Telescope Extension: `notify`
  - INFO: No healthcheck provided

## Telescope Extension: `ui-select`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. clone this repository https://github.com/ryoppippi/telescope_type_definitions_bug
2. execute `yarn`
3. open src/main.ts
4. move cursor to the word `message` at 6:32
5. execute `:lua vim.lsp.buf.lsp_type_definition()` and `:Telescope lsp_type_definition` on  `message`

### Expected behavior

Should be the same results

### Actual behavior

The results are different

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      'neovim/nvim-lspconfig',
      'williamboman/nvim-lsp-installer'
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
Its not reproducible with your config and i even know why.

consider removing `node_modules` from `file_ignore_patterns` in your config

https://github.com/ryoppippi/dotfiles/blob/29adaf0e87a593c2e06dbf040b29790afb36d127/.config/nvim/lua/plugin/config/telescope.lua#L33-L36

It applies to all pickers that have any file association, you basically say you never wanna see any results from these files. We should update the docs for `:help telescope.defaults.file_ignore_patterns` to better reflect this behavior.

If you only wanna ignore these files for find_files, live_grep and grep_string i suggest adding `node_modules` to `.gitignore` (which you already have) and then using `fd` and `ripgrep` (which you also already have set, write it down for completion) because both programs already dont give you results containing gitignored files (on default)

**Comment by ryoppippi** [comment]
@Conni2461 
Thank you for your reply, and yes! after deleting the `file_ignore_patterns` it works fine.
Thank you so much!
