### ISSUE TITLE
full path

### ISSUE THREAD

**Issue by lauccode** [nvim-telescope/telescope.nvim#1958]
**Is your feature request related to a problem? Please describe.**
Not possible to see the full path and file name selected.
It can be needed to select same file name in different long path.

**Describe the solution you'd like**
Put somewhere "full path+file name" to be sure of the file selected.

**Describe alternatives you've considered**
I try to play with setting "defaut.path_display" but don't find solution.

**Comment by fdschmidt93** [comment]
If I understand your request correctly, this should work.

```lua
local builtin = require("telescope.builtin")

builtin.find_files({
	find_command = { "fd", "-t=f", "-a" },
	path_display = { "absolute" },
})
```

It's about combining `find_command` with `path_display = { "absolute" }` appropriately, of course, depending on what your preferred `find_command` is.

**Comment by fdschmidt93** [comment]
```lua
builtin.find_files({
        -- use fd to "find files" and return absolute paths
	find_command = { "fd", "-t=f", "-a" },
	path_display = { "absolute" },
        wrap_results = true
})
```

is what you are looking for.

**Comment by lauccode** [comment]
Thanks a lot.
This is working with :

```lua
lvim.builtin.telescope.defaults={
  -- use fd to "find files" and return absolute paths
	find_command = { "fd", "-t=f", "-a" },
	path_display = { "absolute" },
        wrap_results = true
}
```
It could be avoided to set this option with "full path+file name" for the file selected. To be checked with user, I think it could be a useful default improvement.
