### ISSUE TITLE
Add ability to sort *grep_string* results by folder names

### ISSUE THREAD

**Issue by Tej12345** [nvim-telescope/telescope.nvim#1960]
**Telescope grep_string** is missing the feature when you could find a grep pattern in particular folders.

I want to see something like:
1.  ```Telescope grep_string```
2.  Write into input box e.g.: ```define --folder "*playground*```
3. Get results of **define** keyword in under everyfolder which has **playground** keyword.

It's really annoying to do this by going to:
1) Move results to quickfix window (Pressing C-q)
2) Filtering results with ```:Cfilter playgound```

Please, this nvim plugin is really great so far, but this feature I MISS so much...
Thank you, Nikita

**Comment by fdschmidt93** [comment]
If you use [telescope-fzf-native](https://github.com/nvim-telescope/telescope-fzf-native.nvim), then `!playground` should do the trick, as the path becomes part of the `ordinal` (the attribute sorted by).

If you don't need fuzzy matching (which people typically don't need, it's very popular, albeit people actually 99% of time search for exact matches with multiple terms), then you can tailor https://github.com/nvim-telescope/telescope-rg.nvim to achieve them same outcome as well.

**Comment by fdschmidt93** [comment]
Apologies, I cannot, since I'm not a user of that extension. Please ask in `telescope-rg.nvim`. Closing as this is not relevant any longer for `telescope.nvim`.
