### ISSUE TITLE
Colorscheme live switching

### ISSUE THREAD

**Issue by miversen33** [nvim-telescope/telescope.nvim#1961]
**Is your feature request related to a problem? Please describe.**
When using `builtin.colorscheme`, it would be pretty cool to have Telescope temporarily change your color scheme to whatever you have entry you are currently viewing. 

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
NA

**Additional context**
This is a placeholder, this evening I am planning on forking and attempting a PR for this.

**Comment by miversen33** [comment]
Looking at the documentation, it appears that this is actually already a feature, however it requires an option to be provided to enable it.
https://github.com/nvim-telescope/telescope.nvim/blob/master/doc/telescope.txt#L1320-L1328
```
builtin.colorscheme({opts})                  *telescope.builtin.colorscheme()*
    Lists available colorschemes and applies them on `<cr>`


    Parameters: ~
        {opts} (table)  options to pass to the picker

    Options: ~
        {enable_preview} (boolean)  if true, will preview the selected color
```

So would it make sense to have this option enabled by default as opposed to an opt in?
My specific use case (for what its worth), I open this from the general `builtin` command which opens all available commands. From there I can open the colorschemes but they don't auto preview as I would expect. Effectively I would look to change the option `enable_preview` to `disable_preview` (to make it an opt out instead of opt in).

I can of course just "fix" this on my own config, thoughts?

**Comment by fdschmidt93** [comment]
> So would it make sense to have this option enabled by default as opposed to an opt in?

I'd agree.

> Edit: It looks like enable_preview is not used anywhere else, just here. It seems a bit odd that this would be an opt in. Am I missing something? Can I set this in my global config and not have to worry about it?

Sure. This should always be fine

```lua
require "telescope".setup {
  pickers = {
    colorscheme = {
      enable_preview = true
    }
  }
}
```

(I hope I wrote this correctly as it is untested, but the pattern should work).

**Comment by miversen33** [comment]
> I disagree for a simple reason. The default for this option should continue to be false. Some colorschemes dont reload nicely which breaks things. So default should be the more stable option without auto switching

That does make sense

> Another way to think about it is that no other picker performs an action on just select.
That is untrue, the whole point of `preview` is to perform an action when the user places their cursor over an item in the dropdown. The idea (and exactly how its implemented) is to temporarily change the theme to whatever theme you are currently looking at in the colorscheme picker. If no choice is made, the theme reverts back to what it was before. A temporary change. However @Conni2461 raises a very good point that I had not considered.

@Conni2461, if a colorscheme "breaks things", would a revert back to the previous colorscheme "unbreak" things? Do you have a colorscheme I can test against with this?

**Comment by fdschmidt93** [comment]
I've actually tested it after the concerns raised and for me indeed breaks the colorscheme in a way that aborting the picker doesn't fully revert the original state.

I think it's not something we can _practically_ fix, because of user customization of themes. You'd have to resource all the relevant files I suppose in correct order. I'm using the standard gruvbox with some [personal customization](https://github.com/fdschmidt93/dotfiles/blob/master/nvim/.config/nvim/lua/fds/highlights/init.lua).

**Comment by miversen33** [comment]
Rip. I suppose we close this issue out then. It doesn't make sense to break stuff by default, especially if reverting doesn't fix it.

**Comment by airtonix** [comment]
never say never.


you could provide a function that is run on cancel: 

`plugins/mytheme.lua`
```lua

local M = {}

M.chosen = magicallyParseChosenThemeFromDiskOnlyOnceOnStartup()

function M.save = function(colorscheme)
  -- magically persist chosen color scheme
  M.chosen = colorscheme
  magicalFSLibraryThatSavesToDiskMaybeNVimDoesThisIDunnoLoL(colorscheme)
end

--- @param colorscheme string
function M.setup = function (colorscheme)
  -- magically setup magical colorscheme in magically correct magical order

  chosen = colorscheme or M.chosen

  if (chosen == 'some-special-colorscheme-name') then
    -- do even more magical colorscheme things to magically magic magic magic.
    -- some more wonderfully complicated steps
  end

  -- otherwise be boring peasant like me.
end


return M
```


`plugins/plugin-where-i-configure-telescope.lua`
```lua
return {
  'nvim-telescope/telescope.nvim',
  config = function() {
    require("telescope").setup({
      pickers = {
        colorscheme = {
          enable_preview = true,
          on_cancel = function () {
            local mytheme = require('plugins.mytheme')
            -- runs theme setup logic for M.chosen
            mytheme.setup()
            -- or
            -- mytheme.setup(mytheme.chosen)
          },
          on_hover = function (colorscheme) {
            require('plugins.mytheme').setup(colorscheme)
          },
          on_change = function (colorscheme) {
            require('plugins.mytheme').save(colorscheme)
          }
        }
      }
    })
  }
}
```

Dunno, I'm just a filthy frontend developer peasant. forgive me if i've commited some kind of heresy.

**Comment by miversen33** [comment]
@airtonix 

The bigger issue (as pointed out by the Telescope devs) is related to "undoing" the changes that were made. Whether we call a function or simply write the logic into an anon function, the issue is not _what to do_, but _how to do_.

Colorschemes seem to affect specific parts of Vim core that are hard to "undo". Its actually a thing I have spent a bit of time digging into in another plugin I work on, there just doesn't seem so to be a solid way to "undo" the changes a colorscheme makes as there is no great way of knowing _what_ changes a colorscheme made during its initialization. Its all very nonstandard which leads to things "breaking" (half reverted colorschemes and such).

**Comment by fdschmidt93** [comment]
For anyone that really wants to have this feature, maybe colorschemes changes could be handled appropriately

https://github.com/neovim/neovim/pull/13457#issuecomment-739312212

That is, bfredl's snippet appropriately preserves the highlight groups and users correctly define custom highlight groups per theme (not 100% sure how, possibly `Colorscheme` autocmd, but I'm reasonably sure it's an issue).

Not sure we'd have it in telescope core though.
