### ISSUE TITLE
make live_grep take a list of files in addition to the list of folders

### ISSUE THREAD

**Issue by danielo515** [nvim-telescope/telescope.nvim#1962]
**Is your feature request related to a problem? Please describe.**
I am always frustrated with how hard is for me to refine searches while doing live_grep. Many times I get a set of files that I want to re-search on, limiting the search to those files.
This is something this picker kind-of already does, but limited to open buffers.

**Describe the solution you'd like**
I propose to add another option to live_grep to limit the search to a set of files. This way I will able to chain other searches to refine them in a new live_grep picker.

**Describe alternatives you've considered**
Right now I should create clone of live_grep in my user space and use that picker instead

**Additional context**
This will empower the users to easily create workflows like the described in #793 (or similar to)

**Comment by Conni2461** [comment]
`search_dirs` option is not only limited to dirs. (its a bad name) but its basically the [PATH...] part from `rg [OPTIONS] PATTERN [PATH...]`

so this `lua require("telescope.builtin").live_grep({ search_dirs = { "file_b", "file_a" } })`

**Comment by danielo515** [comment]
> `search_dirs` option is not only limited to dirs. (its a bad name) but its basically the [PATH...] part from `rg [OPTIONS] PATTERN [PATH...]`
> 
> so this `lua require("telescope.builtin").live_grep({ search_dirs = { "file_b", "file_a" } })`

That's what I thought,  but I tried and I didn't got any results. Maybe I did some additional mistake. Have you verified that such thing works?

**Comment by Conni2461** [comment]
yes tried it before posting that snippet

**Comment by danielo515** [comment]
> yes tried it before posting that snippet, first on cli after that with telescope

You're right, it works. It is just that live_grep does not show anything until you start typing, so it is easy to get confused by that.

Can an annotation be added to the docs so this feature is not overlooked by other devs and it is nor deleted by the core team?

**Comment by Conni2461** [comment]
clarified the docs in the current dev branch: https://github.com/nvim-telescope/telescope.nvim/pull/1945/commits/314404c7831fe9706910c6d0a2cac989032ea134
