### ISSUE TITLE
Invalid error level message

### ISSUE THREAD

**Issue by asmodeus812** [nvim-telescope/telescope.nvim#1965]
### Description

Hi, trying to use git_branches functionality and the git_switch_branch action i accidentally discovered that there is a small typo which breaks (in my case using nvim notify) nvim. Here in the file init.lua in the actions on line 601
```Lua
utils.notify("actions.git_switch_branch", {
      msg = string.format(
        "Error when switching to: %s. Git returned: '%s'",
        selection.value,
        table.concat(stderr, " ")
      ),
      level = "ERORR",
```

### Neovim version

```markdown
NVIM 7
```

### Operating system and version

WSL

### checkhealth telescope

```markdown
Not relevant
```

### Steps to reproduce

Install nvim notify
Open git branches builtin
Press c-s to trigger git branch switch action
Observe the error

### Expected behavior

No error

### Actual behavior

Notify throws an error that no such error level exists. (due to the typo)

### Minimal config

```Lua
Using defaults.
```

**Comment by fdschmidt93** [comment]
Thanks for reporting, should be fixed now :)
