### ISSUE TITLE
Using multi search key words delimited by space

### ISSUE THREAD

**Issue by OliverChao** [nvim-telescope/telescope.nvim#1968]
I am not sure if telescope has this feature just like fzf does. 
In one search action, I can use several items delimited by space, and telescope returns the most matched results.
Fzf support this feature.

![image](https://user-images.githubusercontent.com/39361033/170297761-8f49bb5f-a6a8-4c35-b4a1-9b8308b2bfe0.png)

But, I fail in telescope.
![image](https://user-images.githubusercontent.com/39361033/170298267-c085889f-1235-4c89-8ba5-5308d466e45a.png)

![image](https://user-images.githubusercontent.com/39361033/170298314-6fadc943-037b-4d0e-8c5a-68414d48fe46.png)

**Comment by fdschmidt93** [comment]
This depends on the sorter you are using; [telescope-fzf-native](https://github.com/nvim-telescope/telescope-fzf-native.nvim) is a sorter that 1:1 mimics fzf (apart from a few edge cases) and enables the functionality you are looking for.

**Comment by OliverChao** [comment]
> This depends on the sorter you are using; [telescope-fzf-native](https://github.com/nvim-telescope/telescope-fzf-native.nvim) is a sorter that 1:1 mimics fzf (apart from a few edge cases) and enables the functionality you are looking for.

Yep, I got it. Thanks. This plugin works just as I want. Thank you @fdschmidt93

**Comment by CrazyHulk** [comment]
Find_files works fine, but live_grep doesn't, do you have the same problem?

**Comment by Conni2461** [comment]
`live_grep` is not fuzzy. Every input "word" goes directly to ripgrep. If you want a `:Rg` equivalent you can do `:Telescope grep_string search=`

but `live_grep` does offer regex support which can be useful and then you can do `<c-space>` to pipe the results in a fuzzy environment.

Hope that answers your question

**Comment by CrazyHulk** [comment]
> `live_grep` is not fuzzy. Every input "word" goes directly to ripgrep. If you want a `:Rg` equivalent you can do `:Telescope grep_string search=`
> 
> but `live_grep` does offer regex support which can be useful and then you can do `<c-space>` to pipe the results in a fuzzy environment.
> 
> Hope that answers your question

Thanks, really helpful.
