### ISSUE TITLE
Unsure of how we got this failure

### ISSUE THREAD

**Issue by fgheng** [nvim-telescope/telescope.nvim#1975]
### Description

Hello, there are some errors with [copilot.vim](https://github.com/github/copilot.vim), "Unsure of how we got this failure".

![image](https://user-images.githubusercontent.com/50551377/170731378-1637f588-d888-45bf-a533-f217e39ef1a5.png)

### Neovim version

```markdown
NVIM v0.8.0-dev+313-g7b952793d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az220-948

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

arch linux

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. (I have also configed `copilot.vim`, so skip this step )
3. `:Telescope`
4. enter \<esc\> to quit the telescope window
5. press 'o' to create new row
6. input any character and press tab after the character quickly, error will occured

### Expected behavior

no error message

### Actual behavior

![telescope](https://user-images.githubusercontent.com/50551377/170733283-e2d84117-2a0d-4e6f-8d5b-d5bb665861db.gif)

### Minimal config

```Lua
vim.g.do_filetype_lua = 1
vim.g.did_load_filetypes = 0

local fn = vim.fn
local cmd = vim.cmd

local packer_boot_strap = false
local install_path = fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
    packer_boot_strap = fn.system({ 'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path })
    if packer_boot_strap then
        cmd [[packadd packer.nvim]]
    else
        return
    end
end

require('packer').startup({ function(use)
    use { 'wbthomason/packer.nvim' }

    use { 'github/copilot.vim',
       event = 'InsertEnter',
        config = function()                                                                                                                                                
            vim.cmd[[                                                                                                                                                      
                let g:copilot_filetypes = {                                                                                                                                
                      \ 'TelescopeResults': v:false,                                                                                                                       
                      \ 'TelescopePrompt': v:false,                                                                                                                        
                      \ }                                                                                                                                                  
            ]]                                                                                                                                                             
        end  
    }

     use { 'nvim-telescope/telescope.nvim',
         config = function()
             require('telescope').setup()
         end,
         requires = {
             { 'nvim-lua/plenary.nvim' },
         },
         cmd = { 'Telescope' },
     }

    -- packer auto install if packer is installed for the first time
    if packer_boot_strap then
        require('packer').sync()
    end
end,
config = { -- packer using float window
    display = {
        open_fn = function()
            return require('packer.util').float({ border = 'single' })
        end
    }
}
})
```

**Comment by Conni2461** [comment]
Did you try to disable all of Telescopes filetypes for copilot? `TelescopePrompt` and `TelescopeResults`?

https://github.com/github/copilot.vim/blob/ad102c7a58356414f18680f60c2298246e41ccea/doc/copilot.txt#L43-L59

Or even better only enable copilot for filetypes you need. Maybe that helps, if not i would install copilot and try it out myself

**Comment by fgheng** [comment]
Yes, the problem  still exists.
I have changed the minimal config with 'g:copilot_filetypes'.

**Comment by Conni2461** [comment]
Hmm okay i can reproduce. Its weird, i dont know why you can trigger a telescope mapping even thought we already closed that buffer. My only assumption right now is that these mappings are not yet cleaned fully cleaned up. I can remove that error message, but that only gonna "eat" the `<Tab>` keypress. Calling `:mapclear <buffer>` prior to deleting the buffer also didn't help

I need to investigate more, on what going wrong here.

**Comment by Genius1512** [comment]
I'm getting the exact same error message, but I'm using coc instead of copilot

**Comment by ruanyouxing** [comment]
i found out that <Tab> keymap was overrided by this
![tab](https://user-images.githubusercontent.com/87190231/177830835-53a82119-e509-46ae-b43a-dc298149d381.png)

**Comment by xgugeng** [comment]
I don't know why but resolved this issue by removing `event = "InsertEnter`. Then the key binding for `<Tab>` seems ok
![image](https://user-images.githubusercontent.com/5053603/211546892-7571af6d-56d4-43ef-9252-970a7dd2ab52.png)

**Comment by fgheng** [comment]
my solution is using [copilot.lua](https://github.com/zbirenbaum/copilot.lua)

**Comment by paulochoi** [comment]
I'm also getting this error. Tried installing copilot.lua but also having the same error.

For the time being, I have just remapped tab to behave as usual.

**Comment by mskelton** [comment]
@paulochoi If you are using Lazy.nvim for your package manager, this may help.

https://github.com/mskelton/dotfiles/commit/6cebc2d8b8d13eb622ba4054df49d9b05ae57ecf

The issue for me was that I was loading copilot after Telescope which caused issues with the mappings. Using `VimEnter` as the event for copilot ensured that it would load before Telescope with my config and then everything worked as normal.

Hope that helps!

**Comment by paulochoi** [comment]
Thanks for that, you are right. Looks like copilot is loading after telescope here. I typically launch neovim with telescope find_files as a command and looks like when I do that, telescope is the first thing that loads and it is causing the problem.

**Comment by Conni2461** [comment]
Can someone retest this. we actually might have fixed this issue, because we rewrote our mappings (latest master) and it might have fixed that issue because we no longer have a couple of hacks for mappings and the "Unsure of how we got this failure" code also no longer exists.

**Comment by paulochoi** [comment]
I have reverted my workaround and can confirm that the error no longer occurs. Thanks @Conni2461 and team!

**Comment by Conni2461** [comment]
Thanks for retesting. If this issues comes back, feel free to reopen

**Comment by marcellmueller** [comment]
This is fixed for me as well, thanks so much I really appreciate it!
