### ISSUE TITLE
spell_suggest changes the next section of text when on the final character of a word

### ISSUE THREAD

**Issue by Louis-dM** [nvim-telescope/telescope.nvim#1977]
### Description

When on the final character of a word, using `spell_suggest` to change the word changes the text following the current word.

### Neovim version

```markdown
NVIM v0.8.0-dev+317-ge2940d3c7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Fedora Linux 35 (Workstation Edition)

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

Say I have the following text, which happens to be in my init.lua:
```
vim.keymap.set("n", "<leader>s", function()
	require("telescope.builtin").spell_suggest(require('telescope.themes').get_cursor({}))
end)
```
If I move the cursor to the `d` in the word `end` on the last line and type `<leader>s<CR>`, the final line is changed to `endand`.

### Expected behavior

The final line should be changed to `and)`. Doing the same thing but using Vim's built-in spell checker (i.e. typing `z=1<CR>` instead of `<leader>s<CR>`)) gives the expected result.

### Actual behavior

The final line is changed to `endand`.

**Other observations**

- If there is a space between two words, the space will be replaced with the suggestion.
- For example, if the cursor is on the final `,` of the first line and the command is run, the space is replaced with the text `Function`.  (If the text under the cursor isn't an actual word, it seems to act as if the cursor is in the following word.) Doing the same but with `z=` replaces the text `function` with the text `Function`, as expected.

### Minimal config

The only lines I have added to this is the remap mentioned in the `steps to reproduce` section, purely because I'm new to both Neovim and Telescope and don't know how to activate the function without the remap. I doubt it's necessary.

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  vim.keymap.set("n", "<leader>s", function()
	require("telescope.builtin").spell_suggest(require('telescope.themes').get_cursor({}))
  end)
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by joeveiga** [comment]
The `+ 1` in the cursor column here seems to be the issue (removing it fixes the problem for me), but I'm not too familiar with the code yet and not sure why it was added in the first place. (/cc @Conni2461 @fdschmidt93)
https://github.com/nvim-telescope/telescope.nvim/blob/e2a77a54a35642dd95310effe2bf4e36fff3af26/lua/telescope/actions/init.lua#L355

Found this comment that looks also related: https://github.com/nvim-telescope/telescope.nvim/commit/b4c45e8c610c8dc60483b49936dee8a4d0b9c532#commitcomment-74837390
