### ISSUE TITLE
clarify what hidden entries may be provided to the callback of map_entries util

### ISSUE THREAD

**Issue by danielo515** [nvim-telescope/telescope.nvim#1980]
**Is your feature request related to a problem? Please describe.**
Reading the documentation of telescope I came to the conclusion that there is no way to get a list of all the visible items (meaning, not filtered out) in a picker.
However, my experience suggest me that this is not true. The reason of my confusion comes from this help line from `:h telescope.actions.utils`

``` 
utils.map_entries({prompt_bufnr}, {f}) *telescope.actions.utils.map_entries()*
    Apply `f` to the entries of the current picker.
    - Notes:
      - Mapped entries may include results not visible in the results popup.
      - Indices are 1-indexed, whereas rows are 0-indexed.
    - Warning: `map_entries` has no return value.
``` 
 Specifically `Mapped entries may include results not visible in the results popup.` If I want to map over visible entries, or at least entries that match the current filter this confuses me. Maybe the wording can be more clear by adding additional context? I know it will not be as concise, but it will be easier to understand

**Describe the solution you'd like**
Adding some extra information like:

```
Maps over entries that fulfils the current filter, which may include results not visible in the results popup.
```

Also, probably as a separate issue, adding a table with the mapped items as a return value will be beneficial. By definition, mapping functions return a new list of values, and this does not adhere to that interface for a reason that is not clear. If you want to keep it as it is, it should be renamed to `for_each_entry` or something like that, which is more close to what it actually does and add a new implementation for map_entries.

**Describe alternatives you've considered**
Taking my own notes and try to remember 😄 

**Additional context**
I am using this to pipe the current list of filtered items to other pickers

**Comment by danielo515** [comment]
> PR welcome

Are my suppositions about the behaviour correct? Do you like my proposed alternative sentence?

**Comment by Conni2461** [comment]
Its not possible to iterate over only visible entries. Its possible to iterate over selected or filtered entries.

You can propose a PR to clarify the documentation.

I don't want to change the name `map_entries` to something else. We can iterate over the interface post 0.1 and maybe use `plenary.iterator` which should give us more flexibility.

**Comment by danielo515** [comment]
> Its not possible to iterate over only visible entries. Its possible to iterate over selected or filtered entries.

Thanks for the clarification, I'll try to open a PR to make this more obvious in the docs.

**Comment by Conni2461** [comment]
clarified the docs in the current dev branch: https://github.com/nvim-telescope/telescope.nvim/pull/1945/commits/314404c7831fe9706910c6d0a2cac989032ea134
