### ISSUE TITLE
Telescope error: "We couldn't mkdir: C:\C:"

### ISSUE THREAD

**Issue by dartacao** [nvim-telescope/telescope.nvim#1990]
### Description

Cannot close, edit or interact with pickers other than select (tab) items. Upon selecting or pressing CR, the following error message is shown:

```
E5108: Error executing lua ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:488: We couldn't mkdir: C:\C:
stack traceback:
        [C]: in function 'error'
        ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:488: in function 'mkdir'
        ...site\pack\packer\start\plenary.nvim/lua/plenary/path.lua:621: in function 'touch'
        ...ker\opt\telescope.nvim/lua/telescope/actions/history.lua:173: in function 'init'
        ...ker\opt\telescope.nvim/lua/telescope/actions/history.lua:79: in function 'handler'
        ...acker\opt\telescope.nvim/lua/telescope/actions/state.lua:48: in function 'get_current_history'
        ...packer\opt\telescope.nvim/lua/telescope/actions/init.lua:245: in function <...packer\opt\telescope.nvim/lua/telescope/actions/init.lua:244>
        ...k\packer\opt\telescope.nvim/lua/telescope/actions/mt.lua:58: in function 'key_func'
        ...ack\packer\opt\telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
```

This occurs with or without any configurations applied. The same exact configuration, commit and version are fully functional on my other windows 10 machine, with a `git clone'd` set of dotfiles (see my dotfiles [here](https://github.com/dartacao/dots)).

### Neovim version

```markdown
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az320-113
```

### Operating system and version

Windows 10

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.4.0

## ===== Installed extensions =====
```

### Steps to reproduce

1. nvim -u NONE
2. :packadd telescope.nvim

### Actual behavior

Cannot close, <CR> or otherwise exit from picker.

### Minimal config

```Lua
-- nothing
```

**Comment by dartacao** [comment]
I believe I have found one of the issues at least. The problem is the history functionality, which I've never used and disabled with `defaults = {history = false}`. If anyone has this issue, try this. I'm not sure why history is bugging out telescope so hard, but at least it's working well now.

**Comment by dartacao** [comment]
> This issue is similar to #1724
> 
> I just merged a fix into plenary that might improve or even fix this issue [nvim-lua/plenary.nvim#324](https://github.com/nvim-lua/plenary.nvim/pull/324). Can you retest? Thanks :)

Hi! Thanks for your PR, I believe this fixes it. Thank you very much for your help, problem solved! :)

**Comment by xarthurx** [comment]
I got this error today again:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/1921878/89cedebf-e782-463c-8fa4-29ddc86f0dfc)

**Comment by jamestrew** [comment]
@xarthurx what were you trying to do when you got this error? nothing in the stack trace indicates this is related to telescope specifically (granted it looks similar to the root issue of this issue).

**Comment by xarthurx** [comment]
> @xarthurx what were you trying to do when you got this error? nothing in the stack trace indicates this is related to telescope specifically (granted it looks similar to the root issue of this issue).

file history files.
I assume this might be the path processer issue on Windows?

**Comment by bjjblackbelt** [comment]
This solved the issue I was seeing on Windows:

[Same issue on Windows: "We couldn't mkdir: C:\project\repo\C:/Users/User/AppData/Local/Temp/nvim ". Occurs when using completion with nvim-cmp.](https://github.com/nvim-lua/plenary.nvim/pull/551)
