### ISSUE TITLE
Add option to hide process exit code for previewers.new_termopen_previewer

### ISSUE THREAD

**Issue by Zane-** [nvim-telescope/telescope.nvim#1991]
**Is your feature request related to a problem? Please describe.**
More of an inconvenience; if the previewer command provided to `finders.new_oneshot_job` exits instead of remaining open like `bat` or `less`, telescope displays the process exit code like so:

![image](https://user-images.githubusercontent.com/6345012/172449817-5b27aa13-e6c3-40b5-8336-cb65b059230f.png)

**Describe the solution you'd like**
Either hide this by default (it's hideous), or add an option to the `new_termopen_previewer` previewer to hide it.

**Describe alternatives you've considered**
Piping the output to a pager such as `bat`, but this doesn't work because it only runs the one command, i.e.:

```lua
previewer  = previewers.new_termopen_previewer({
  get_command = function(entry)
    return vim.tbl_flatten({ 'ls', '-a', '|', 'bat'})
)}.
```

This would actually be the preferred solution (being able to pipe commands), as it would enable paging on any output by piping it to `bat`.

**Comment by Conni2461** [comment]
It utilizes `:help termopen` which also doesnt support `|` and shows the process exit code. (try it yourself: `lua vim.fn.termopen({ 'ls', '-a', '|', 'bat'})`)

You need a sell interpreter to have pipe support. Try: `lua vim.fn.termopen({ 'bash', '-c', 'ls -la | bat' })`

**Comment by Zane-** [comment]
Ooh, thanks, using `bash -c` works, didn't think of that!
