### ISSUE TITLE
Add picker to list git staged/unstaged hunks(lines) and jump to one of them on selection

### ISSUE THREAD

**Issue by Tej12345** [nvim-telescope/telescope.nvim#1992]
It would be great to have a git picker that would return a list of all unstaged/staged hunks.
That way a person that making a feature would jump to it really quick if for example:
1. Line in file **helloworld.c** and **432** line there has been changed by User.
2. User move to **helloword.h** and changed there something too.
3. User remember the word of the last line that he changed and want to come back to it.
4. Opens telescope layout writes a word that was part of the line that he made change in **helloworld.c:432** and ends up there.
5. Come backs to **helloworld.c:432**.

!!! This is an oposite to remembering filename and fileline where change was made.

Please tell me if it's already possible, if not consider to implement.

**Comment by fdschmidt93** [comment]
I think [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) makes hunks accessible (at least exportable to the quickfixlist).

You are happy to write your own picker on top of that.

**Comment by radyz** [comment]
I stumbled this thread looking for the same thing and so I built an extension for it in case you want to give it a try:

https://github.com/radyz/telescope-gitsigns.

Any feedback is welcomed
