### ISSUE TITLE
full path preview

### ISSUE THREAD

**Issue by ftaiolivista** [nvim-telescope/telescope.nvim#2019]
**Is your feature request related to a problem? Please describe.**
With long path file name is not visible

**Describe the solution you'd like**
While cycling over results  I can see the current item full path wrapped in a box (like the file preview, but for path not file content).
![image](https://user-images.githubusercontent.com/150721/174775056-ed101316-a070-4be9-9eb2-a0e36619f1b3.png)

**Comment by Conni2461** [comment]
I am not sure what you want but maybe take a look at the option `:help telescope.defaults.dynamic_preview_title`

full file path is shown as border title
![image](https://user-images.githubusercontent.com/15233006/175807403-c5f73194-172f-49ee-b4a1-b6e16c324702.png)

**Comment by ftaiolivista** [comment]
Thank you for the suggestion @Conni2461. Tried it but the path keep to be partially hided. See screenshot. Any way to see the full path?
![image](https://user-images.githubusercontent.com/150721/175877967-e9a72210-7746-4e0d-aac3-97f1596011df.png)

**Comment by Shougo** [comment]
I think it has not enough space to display the full path.

**Comment by ftaiolivista** [comment]
> I think it has not enough space to display the full path.

Yes, thats sure. I'm searcing for an option or a way to show the full path "wrapped" on more lines. So to always see it full, even when the space is not enough

**Comment by Shougo** [comment]
Hm...  The feature seems not implemented though.

**Comment by Shougo** [comment]
Please see this.  It is plenary.nvim's feature.

https://github.com/nvim-lua/plenary.nvim/blob/563d9f6d083f0514548f2ac4ad1888326d0a1c66/lua/plenary/window/border.lua#L24

**Comment by Conni2461** [comment]
we are not going to wrap the paths anywhere in the previewer. There are enough options available to get the important parts of the path, see `:help telescope.defaults.path_display`

We could even do a truncate on left for the dynamic border title.
But not what you've proposed.

Closing for now.

**Comment by yyy33** [comment]
> we are not going to wrap the paths anywhere in the previewer. There are enough options available to get the important parts of the path, see `:help telescope.defaults.path_display`
> 
> We could even do a truncate on left for the dynamic border title. But not what you've proposed.
> 
> Closing for now.

I use this configuration, but it is not very intuitive in practice, especially if you are not familiar with the path.
```
      path_display = {
          shorten = {
              len = 3, exclude = {1, -1}
          },
          truncate = true,
      },

```

**Comment by tommdq** [comment]
path_display works perfect for me, but when using telescope.builtin.lsp_reference the path is always shown as absolute. I've checked :help telescope.builtin.lsp_references but found nothing regarding the preview path display.
