### ISSUE TITLE
Add: Picker for tagstack

### ISSUE THREAD

**Issue by DevonMorris** [nvim-telescope/telescope.nvim#202]
Hey TJ thanks for a great plugin! I'm an absolute n00b at lua so this may be super easy and I've missed a simple way to do this.

It looks like you can get the tagstack with `vim.fn.gettagstack()`. I'd like to be able to set up a picker to go through the stack and pop off/push on the corresponding number of tags. Additionally it'd be nice if the cursor started at the current position in the tagstack as well.

Probably wouldn't want any sorting logic here since it would mess up the tag stack.

Let me know what you think!

**Comment by DevonMorris** [comment]
```lua
M.tagstack = function(opts)
  opts = opts or {}
  local tagstack = vim.fn.gettagstack()
  if vim.tbl_isempty(tagstack.items) then
    return
  end

  for i, value in pairs(tagstack.items) do
    value.text = value.tagname
    value.lnum = value.from[2]
    value.filename = vim.fn.bufname(value.from[1])
  end

  -- reverse the list
  tags = {}
  for i=#tagstack.items, 1, -1 do
    tags[#tags+1] = tagstack.items[i]
  end

  pickers.new(opts, {
      prompt_title = 'TagStack',
      finder = finders.new_table {
        results = tags,
        entry_maker = make_entry.gen_from_quickfix(opts),
      },
      previewer = previewers.qflist.new(opts),
      sorter = conf.generic_sorter(opts),
    }):find()
end
```

Took another stab at this, this gets me most of the way there, but it doesn't put the selection at the current position in the tag stack and doesn't modify the tag stack.

Is there a way to change the default selection when calling the picker? I didn't seem able to do that. Also, I assume that popping/pushing the stack should be done through the `attach_mappings`

Also feel free to tear this up since I've never _really_ used lua before. I'm happy to fork and submit a PR if we want as well.

**Comment by tjdevries** [comment]
It looks cool! If you want to submit a PR, I can send feedback about it. that would probably be a lot easier than just messaging in the comments here!

**Comment by tami5** [comment]
@DevonMorris please open a PR for further collaboration to be done. Thanks
