### ISSUE TITLE
Missing Documentation for Extension Development (Bundling)

### ISSUE THREAD

**Issue by nico-bellante** [nvim-telescope/telescope.nvim#2021]
### Description

I see in the docs, there's "later we'll bundle this as an extension" (https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md#guide-to-your-first-picker). However, I do not see the section this is referring to where we can see examples for how to bundle an extension.

It would be awesome if these examples could be added and linked to from this spot.

### Neovim version

```markdown
N/A
```

### Operating system and version

N/A

### checkhealth telescope

```markdown
N/A
```

### Steps to reproduce

N/A

### Expected behavior

The documentation should cover the last step in creating a telescope extension.

### Actual behavior

I am left with a lua file that does exactly what I want when I do `:luafile %` but don't know how to take this file and actually make it an extension.

### Minimal config

```Lua
N/A
```

**Comment by nico-bellante** [comment]
ah, pretty sure what i was looking for was https://github.com/nvim-telescope/telescope.nvim/wiki/Extensions#extension-folder-structure

and `register_extension`

**Comment by Conni2461** [comment]
I think we can still improve it a little bit. I will add a section in the next couple of days. Thanks for reporting :)
