### ISSUE TITLE
Remember last query

### ISSUE THREAD

**Issue by Lilja** [nvim-telescope/telescope.nvim#2024]
**Is your feature request related to a problem? Please describe.**
Sometimes i type a filter into telescope only to realize that I need to close the popup to check something in a buffer. When I do that, I lose the state where I am. I then need to re-type what I just typed. 
VScode has this feature if you search for something, it will remain until you delete that query.

**Describe the solution you'd like**
After a couple of characters/seconds typed into the "buffer"/filter-view, it's saved to some disk. Whenever a new telescope popup is opened, it's opening that file and enters the content of that file.

**Comment by azjgard** [comment]
I was recently searching for the same feature, and by looking through some related issues in this repository I was pleasantly surprised to find that a basic version of this is straightforward to implement.

In case it's helpful, here's what I'm currently doing:
```lua
local telescope = require('telescope.builtin')
local telescope_state = require('telescope.state')

local last_search = nil

function search_with_cache() 
  if last_search == nil then
    telescope.live_grep()

    local cached_pickers = telescope_state.get_global_key "cached_pickers" or {}
    last_search = cached_pickers[1]
  else
    telescope.resume({ picker = last_search }) 
  end
end

vim.keymap.set('n', '<leader>f', search_with_cache)
```

**Comment by Conni2461** [comment]
We have a history module that store the successful (on hitting `<cr>`/`<c-v>`, ...) input. See `:help telescope.defaults.history` and `:help telescope.actions.history`

You can also rerun old finders with`:Telescope resume` see `:help telescope.builtin.resume` and `:help telescope.defaults.cache_picker` for the configuration of it.

Closing as dup, in favor of #1701

**Comment by noamso1** [comment]
simplest solution:

```
local telescope = require('telescope.builtin')
local telescope_last = 0
function telescope_resume()
  if telescope_last == 0 then
    telescope_last = 1
    telescope.live_grep()
  else
    telescope.resume()
  end
end
vim.keymap.set("n", " f", telescope_resume)

```

**Comment by Hecatoncheir** [comment]
How can I resume only commands picker?

**Comment by jamestrew** [comment]
You should be able to achieve this by setting `cache_picker = false` for all the pickers you want to disable caching for.
eg.
```lua
require("telescope").setup({
  defaults = {
    -- ...
  },
  pickers = {
    find_files = {
      cache_picker = false, -- for each picker you want to disable and use
    },
    -- and so on
  },
})


-- for alternatively can do through keymap
vim.keymap.set("n", "<leader>fw", function()
  require("telescope.builtin").live_grep({ cache_picker = false })
end)
```

**Comment by Hecatoncheir** [comment]
> You should be able to achieve this by setting `cache_picker = false` for all the pickers you want to disable caching for. eg.
> 
> ```lua
> require("telescope").setup({
>   defaults = {
>     -- ...
>   },
>   pickers = {
>     find_files = {
>       cache_picker = false, -- for each picker you want to disable and use
>     },
>     -- and so on
>   },
> })
> 
> 
> -- for alternatively can do through keymap
> vim.keymap.set("n", "<leader>fw", function()
>   require("telescope.builtin").live_grep({ cache_picker = false })
> end)
> ```

I try do it like that:
```lua
-- Commands
local commandsPicker = nil
local ToggleCommands = function()
  local telescope = require("telescope.builtin")
  local telescope_state = require("telescope.state")
  if commandsPicker == nil then
    telescope.commands()
    local cached_pickers = telescope_state.get_global_key("cached_pickers") or {}
    commandsPicker = cached_pickers[1]
  else
    telescope.resume({ picker = commandsPicker })
  end
end
vim.api.nvim_create_user_command("ToggleCommands", ToggleCommands, { desc = "Toggle commands" })

-- Files
local filesPicker = nil
local ToggleFiles = function()
  local telescope = require("telescope.builtin")
  local telescope_state = require("telescope.state")
  if filesPicker == nil then
    telescope.find_files()
    local cached_pickers = telescope_state.get_global_key("cached_pickers") or {}
    filesPicker = cached_pickers[1]
  else
    telescope.resume({ picker = filesPicker })
  end
end
vim.api.nvim_create_user_command("ToggleFiles", ToggleFiles, { desc = "Toggle files" })
```

I need always resume any picker. How can I do that?
