### ISSUE TITLE
selected file opens in insert mode directly

### ISSUE THREAD

**Issue by abdellatif-temsamani** [nvim-telescope/telescope.nvim#2027]
### Description

i selected the file that i want, the selected file opens in insert mode directly

### Neovim version

```markdown
NVIM v0.8.0-dev+503-g274609a109
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

arch linux

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.4.0

## ===== Installed extensions =====
```

### Steps to reproduce

1. `nvim`
2. `:Telescope find_files`
3. select a file 

### Expected behavior

- the file should be opened in normal mode

### Actual behavior

- the file will be opened in insert mode

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
    require('packer').startup {
        {
            'wbthomason/packer.nvim',
            {
                'nvim-telescope/telescope.nvim',
                requires = {
                    'nvim-lua/plenary.nvim',
                    { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
                },
            },
            -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
        },
        config = {
            package_root = package_root,
            compile_path = install_path .. '/plugin/packer_compiled.lua',
            display = { non_interactive = true },
        },
    }
end

_G.load_config = function()
    local actions = require("telescope.actions")

    require("telescope").setup({
        defaults = {
            prompt_prefix = " ",
            color_devicons = true,
            selection_strategy = "closest",

            file_previewer = require("telescope.previewers").vim_buffer_cat.new,
            grep_previewer = require("telescope.previewers").vim_buffer_vimgrep.new,
            qflist_previewer = require("telescope.previewers").vim_buffer_qflist.new,


            mappings = {
                i = {
                    ["<C-x>"] = false,
                    ["<C-q>"] = actions.send_to_qflist,
                    ["<C-h>"] = "which_key",
                },
            },
        },

        extensions = {

            fzf = {
                fuzzy = true, -- false will only do exact matching
                override_generic_sorter = true, -- override the generic sorter
                override_file_sorter = true, -- override the file sorter
                case_mode = "smart_case", -- or "ignore_case" or "respect_case"
                -- the default case_mode is "smart_case"
            },
            project = {
                base_dirs = {
                    "~/programming",
                },
                hidden_files = false,
            },
        },
    })


    require('telescope').load_extension('fzf')
    -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
    print("Installing Telescope and dependencies.")
    vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fedreg-bn** [comment]
Seeing the same on 
- nvim v0.7.0 release
- MacOS 12.3.1

**Comment by abdellatif-temsamani** [comment]
> I encounter the same problem currently

i think if downgrade to `NVIM v0.7.2` it should be fixed

**Comment by fedreg-bn** [comment]
@abdellatif-temsamani I'm running v 0.7.0 and had it, but seems like just deleting the plugin and reinstalling it has fixed it for me 🤷 

if the issue pops back up I'll debug a bit more but unable to reproduce at the moment

**Comment by abdellatif-temsamani** [comment]
@fedreg-bn i just reinstalled and it seems to be be working, thanks

**Comment by Conni2461** [comment]
Weird we haven't changed anything. Hopefully no one else runs into this issue again :grimacing:

**Comment by fedreg-bn** [comment]
@Conni2461 this issue popped back up for me again this morning.    It happened right after I updated Telescope.

As you said, no changes in recent commits that would cause anything like this from what I could see..  could it be something not getting fully updated??

nvim 0.7.0
using `vim-plug`
Still using full vimscript init
only Telescope related configs are a few keybindings to call a few Telescope functions...  nothing fancy.

Takes 2 seconds to reinstall so no big deal at all but just sharing in case anyone else mentions and it's helpful.   

If you want any specific info, I can look if/when it happens again.  Unfortunately it was at an inopportune time this morning so couldn't look into it at all.

Thanks for the great work on Telescope!!

**Comment by PopBogdan97** [comment]
The same problem just popped up for me after I updated the plugins. I tried to reinstall Telescope, but it did not work for me. Any other hints on what it could be?

**Comment by theoribeiro** [comment]
Exact same issue happening with me @PopBogdan97 . 
Can confirm that Telescope maintains the mode it is currently on when you open the buffer.

**Comment by PopBogdan97** [comment]
@theoribeiro Unfortunately I did not found any workaround for it at that moment, it just started to behave correctly after a while. I don't know yet why it was not working nor why it is working now...

**Comment by theoribeiro** [comment]
Thanks for the update. No idea what's causing it either, I'll try reinstalling but it's pretty annoying to be honest, lol. It breaks my flow as I end up always editing the file by mistake after I open it.

**Comment by tobealive** [comment]
Yep that's a bit mind mind boggling. It's hard to track to what is actually causing it.

Also, calling `"stopinsert"` doesn't seem to work, even when scheduling it. So a not optional but at least consistent quickfix for now to use with the latest nvim version. 
```lua
nx.au({ -- Prevent entering buffers in insert mode.
	"WinLeave",
	callback = function()
		if vim.bo.ft == "TelescopePrompt" and vim.fn.mode() == "i" then
			vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc>", true, false, true), "i", false)
		end
	end,
})
```

**Comment by medwatt** [comment]
Has there been a fix for this issue?

**Comment by jamestrew** [comment]
This is a pretty weird bug. 
I experience this on nightly `801ac2acc` but rolling back to `339011f59` seemed to have solved the issue for me. But even when I was experiencing this issue, it was not consistent so I couldn't even really do a git bisect. Even if I could, clearly people have been experiencing this as early as 0.7.

**Comment by theoribeiro** [comment]
In my case, the behavior only happened when I had the Codium plugin enabled. I ended up finding out it was a call to a redraw of the status line that for some reason interfered with the mode after leaving Telepresence. Disabling the redraw line solved it but I'm afraid this is just a symptom of some other problem with Telepresence.

**Comment by tobealive** [comment]
@theoribeiro you mean Codeium?
When so, is your observation, that it was a call to redraw the status line that codeium made or telescope?

**Comment by theoribeiro** [comment]
@tobealive yes, sorry I misspelled it, I meant Codeium.

Codeium was making a call to redraw the status line, which caused files opened with Telescope to be opened in Insert mode for me. As soon as I commented that line in Codeium it started working properly again. 

See https://github.com/Exafunction/codeium.vim/issues/80

**Comment by rockyzhang24** [comment]
Confirmed that this issue happened after I installed `nvim-treesitter-context`. That's weird.

**Comment by mudox** [comment]
The neovim nightly-build has this issue, I changed back to 0.9.0 release, the issue gone!

**Comment by mehalter** [comment]
I can confirm I'm also experiencing this in Telescope as well. It appears the mode is always reflected in the buffer I open as my previous mode in Telescope. So if I have the prompt in `insert` mode and select a file, I end up in insert mode. If I go to `normal` mode in the prompt and select a file, I end up in normal mode. Using the autocommand described above is working great for now, but definitely hoping this gets fixed upstream!

**Comment by rockyzhang24** [comment]
@mehalter @catgoose 
I can confirm the issue caused by that commit as well. Not sure it should be fixed on neovim, or telescope.

**Comment by catgoose** [comment]
> @mehalter @catgoose I can confirm the issue caused by that commit as well. Not sure it should be fixed on neovim, or telescope.

Yeah, I'm not sure either.  Do we flip a coin?

**Comment by rockyzhang24** [comment]
Lol. At least this issue should be reopened.

**Comment by Shougo** [comment]
So it should be reported in upstream.

**Comment by Shougo** [comment]
I have reported the change is to fix other plugins issues.
The fix is conflicted...

**Comment by Shougo** [comment]
Please see my comment.

https://github.com/nvim-telescope/telescope.nvim/issues/2501#issuecomment-1541009573

**Comment by Zeioth** [comment]
Currently hapens to me in neovim-git. neovim from arch repos doesn't have the issue.

**Comment by Shougo** [comment]
Because the behavior is changed in recent commit.  Please see my comment.

**Comment by Conni2461** [comment]
i'll keep this closed in favor of https://github.com/nvim-telescope/telescope.nvim/issues/2501, no need to have two issues open, so please report/subscribe to that issue instead. I am going to look into if, we (telescope) can work around that until there is a solution upstream, or maybe that now intended behavior ...
