### ISSUE TITLE
Allow setting default `fname_width` value

### ISSUE THREAD

**Issue by melkster** [nvim-telescope/telescope.nvim#2041]
**Is your feature request related to a problem? Please describe.**
Many builtins allow passing `fname_width` as an option, for instance `builtin.lsp_references()`, and it has the value 30 by default. I think this is too low and so I would like to change it for every builtin. Therefore, I think it would be nice if I could set a default `fname_width` to use, instead of having to pass it to every keymap.

**Describe the solution you'd like**
An `fname_width` field that I can pass to the `setup()` table with the default value of 30. If `fname_width` is passed to a builtin, it should override the default `fname_width` passed to `setup()`.

**Describe alternatives you've considered**
Setting `fname_width` for every single builtin.

**Comment by melkster** [comment]
@Conni2461 Ok I see, thank you!

Another thing: I tried to completely hide the part that's not the file name section by setting the `fname_width` to something huge like 1000, but it seems to always show at least the two first characters of that second part. Is it possible to completely hide that and only show the file filename section?

**Comment by Conni2461** [comment]
for what picker? `lsp_references`? `Telescope lsp_references show_line=false`.

I wanted to point you to the docs for that builtin. But apparently this option doc is missing, ill add that

**Comment by melkster** [comment]
Yes that's what I was looking for! I remember reading about it in the docs and not being sure what it did and then I kinda forgot about it. Thanks for the help!

**Comment by BarretRen** [comment]
@Conni2461 
can we set the "fname_width" for all pickers at the same time? There are so many pickers, it is not smart to set the "fname_width" one by one.

**Comment by lijinglin3** [comment]
> @Conni2461 can we set the "fname_width" for all pickers at the same time? There are so many pickers, it is not smart to set the "fname_width" one by one.

+1

**Comment by Conni2461** [comment]
I am not a fan of introducing a global setting which isn't respected from ALL builtins, as well as extensions. Like currently most global config values we have apply to telescope not to single builtins, exception are vimgrep_arguments but this is a relic that exists since the beginning of the project.

`fname_width` is provided by 15 builtins, and we currently ship over 50 builtins. So i rather wanna move away from that structured table like formatting to a formatting more like the grep builtins.

But you can also do a couple of things.

Because lua is an actual programming language you could do the following:

```lua
local builtins = require("telescope.builtins")

local picker_config = { }
for b, _ in pairs(builtins) do
  picker_config[b] = { fname_width = 30 }
end

require('telescope').setup{
  -- defaults = { },
  pickers = vim.tbl_extend("force", picker_config, {
    lsp_references { fname_width = 40 },
  })
}
```

**Comment by BarretRen** [comment]
@Conni2461 Yeah, that's perfect. Thanks a  lot.
