### ISSUE TITLE
path_display as a function not working due to hidden validation

### ISSUE THREAD

**Issue by cmoscofian** [nvim-telescope/telescope.nvim#2042]
### Description

On some builtins (quickfix, lsp_implementations, lsp_references) _Results_ are being displayed without the formatting provided by the `path_display` function, instead it fallsback as if `path_display` have been set to `hidden`.

I have set on my defaults:
```lua
            path_display = function(_, path)
                local tail = require("telescope.utils").path_tail(path)
                return string.format("%s (%s)", tail, path)
            end
```

but when I call `:Telescope lsp_references` instead os seeing something like:

```
file_name (path/to/file_name)       | XXX
file_name_1 (path/to/file_name_1)   | XXX_1
```

I only see
```
XXX
XXX_1
```

The problem seems to be that the helper [is_path_hidden](https://github.com/nvim-telescope/telescope.nvim/blob/6ea106329ab772328a32f79c79f8004093817b4f/lua/telescope/utils.lua#L202-L210) function is not validating that the path_display could also be a function as stated in the docs.
So whenever it's used to [create an entry](https://github.com/nvim-telescope/telescope.nvim/blob/6ea106329ab772328a32f79c79f8004093817b4f/lua/telescope/make_entry.lua#L410) it evaluates as hidden.

Before opening a pull request, I would like to confirm if this is actually a bug or if supposed to be like this by design.

### Neovim version

```markdown
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.4

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. Open a file with the minimal configuration: `nvim -nu minimal.lua file`
2. Add items to the quickfixlist `vimgrep /pattern/ %`
3. Try to access it using telescope: `:Telescope quickfix`

### Expected behavior

See the `Results` with the path format from the `path_display` function.

### Actual behavior

It assumes that `path_display` is set to `hidden`.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
    require('packer').startup {
        {
            'wbthomason/packer.nvim',
            {
                'nvim-telescope/telescope.nvim',
                requires = {
                    'nvim-lua/plenary.nvim',
                    { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
                },
            },
        },
        config = {
            package_root = package_root,
            compile_path = install_path .. '/plugin/packer_compiled.lua',
            display = { non_interactive = true },
        },
    }
end

_G.load_config = function()
    require('telescope').setup {
        defaults = {
            path_display = function(_, path)
                local tail = require("telescope.utils").path_tail(path)
                return string.format("%s (%s)", tail, path)
            end,
        },
    }
    require('telescope').load_extension('fzf')
    -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end

if vim.fn.isdirectory(install_path) == 0 then
    print("Installing Telescope and dependencies.")
    vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end

load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
Its a bug. Thanks for reporting. PR welcome :)
