### ISSUE TITLE
Wrap lines or scroll horizontally in preview pane

### ISSUE THREAD

**Issue by sassanh** [nvim-telescope/telescope.nvim#2044]
**Is your feature request related to a problem? Please describe.**
Currently I can't see complete lines in the preview pane, no wrapping nor scrolling mechanism is provided as far as I know.

**Describe the solution you'd like**
Either an option to enable line wrapping or a mechanism to scroll horizontally (keymaps), preferably both.

Currently I patched telescope like this:
```diff
diff --git a/lua/telescope/previewers/buffer_previewer.lua b/lua/telescope/previewers/buffer_previewer.lua
index f9e77d2..e0dc140 100644
--- a/lua/telescope/previewers/buffer_previewer.lua
+++ b/lua/telescope/previewers/buffer_previewer.lua
@@ -70,6 +70,7 @@ local function split(s, sep, plain, opts)
   end
   return t
 end
+
 local bytes_to_megabytes = math.pow(1024, 2)
 
 local color_hash = {
@@ -372,7 +373,7 @@ previewers.new_buffer_previewer = function(opts)
       vim.api.nvim_win_set_option(status.preview_win, "winhl", "Normal:TelescopePreviewNormal")
       vim.api.nvim_win_set_option(status.preview_win, "signcolumn", "no")
       vim.api.nvim_win_set_option(status.preview_win, "foldlevel", 100)
-      vim.api.nvim_win_set_option(status.preview_win, "wrap", false)
+      vim.api.nvim_win_set_option(status.preview_win, "wrap", true)
       vim.api.nvim_win_set_option(status.preview_win, "scrollbind", false)
 
       self.state.winid = status.preview_win
```

**Comment by Conni2461** [comment]
Readme contains the answer to your problem: https://github.com/nvim-telescope/telescope.nvim#previewers

```vim
autocmd User TelescopePreviewerLoaded setlocal wrap
```

**Comment by sassanh** [comment]
Thanks! Now I see we already have a solution for wrapping, so should we keep this issue open for horizontal scrolling? (personally I prefer wrapping and the case is closed for me)

**Comment by Conni2461** [comment]
I dont think horizontal scrolling is that beneficial
