### ISSUE TITLE
`from_entry.path` validation fails with escaped path

### ISSUE THREAD

**Issue by habeebweeb** [nvim-telescope/telescope.nvim#2053]
### Description

1aa74b231c6f93152c4ac51549a0563dca9b4453 fixed the check for `filereadable`'s output but `filereadable` fails when checking a path escaped with `fnameescape`.

Failing validation most notably results in some picker preview windows being empty for file paths that contain spaces. Other pickers preview windows work because `entry.path` is `nil` and is never escaped and passes validation.

It seems that validating with `filereadable` and `isdirectory` first then escaping the path afterwards works as intended.

### Neovim version

```markdown
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Arch Linux and MacOS 12.4

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.4.0

## ===== Installed extensions =====

## Telescope Extension: `zf-native`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. `$ echo hello world > hello_world`
2. `$ echo bye world > bye\ world`
3. `$ nvim -nu minimal.lua`
4. `:Telescope live_grep default_text=world`
5. Navigate results

### Expected behavior

The contents of both `hello_world` and `bye world` should show up in the preview.

### Actual behavior

The contents of `hello_world` is shown in the preview but not `bye world`

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by habeebweeb** [comment]
I also noticed that `path` is only ever escaped when `entry.path` is not `nil`.

I think the original intent was to find a path from the `entry`, then escape it, then validate it as was mentioned in  https://github.com/nvim-telescope/telescope.nvim/pull/453#issuecomment-765234852.

Fixing this issue would require changing calls to `from_entry.path` in some places, like `dyn_title`, to prevent unnecessary escaping.

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/2058 should fix the issue
