### ISSUE TITLE
add option for configure the default action for open a selected file ?

### ISSUE THREAD

**Issue by 3Xpl0it3r** [nvim-telescope/telescope.nvim#2056]
should add some optionto config the default action for open a selected file?

like vim-floaterm let g:floaterm_opene=split?

**Comment by Conni2461** [comment]
```lua
require('telescope').setup{
  defaults = {
    mappings = {
      i = {
        ["<cr>"] = require("telescope.actions").select_horizontal,
      },
    }
  },
}
```

for default split. You should read `:help telescope.setup` and `:help telescope.defaults.mappings` and `:help telescope.actions` for the available actions to map.
