### ISSUE TITLE
Prompt history for live_grep picker contains query from fuzzy environment

### ISSUE THREAD

**Issue by ramonbakker** [nvim-telescope/telescope.nvim#2073]
### Description

When I use the live_grep picker together with the new `<C-Space>` fuzzy search functionality, I am unable to search with my initial search query again using the prompt history.

### Neovim version

```markdown
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS Montery 12.4

### Telescope version / branch / rev

telescope 0.1.0

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `fzy_native`
  - INFO: No healthcheck provided

## Telescope Extension: `media_files`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. Open Telescope with `:Telescope live_grep`.
2. Enter a search query.
3. Use `<C-Space>` and enter a fuzzy/second search query.
4. Select a result.
5. Open Telescope with the live_grep picker again and use `actions.cycle_history_prev`.

### Expected behavior

I expect that the prompt history contains my initial search query and that I can get the fuzzy search query from the history again, but after getting the initial search query from the prompt history.

### Actual behavior

The prompt history contains the fuzzy search query instead of the initial search query. The results are only based on the fuzzy search query and therefore not the same as before.

### Minimal config

```Lua
lua <<EOF
local actions = require('telescope.actions')
local action_layout = require('telescope.actions.layout')

require('telescope').setup {
    defaults = {
        mappings = {
            i = {
                ['<C-j>'] = actions.cycle_history_next,
                ['<C-k>'] = actions.cycle_history_prev
            }
        }
    }
}
EOF
```

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/2074 should fix your issue

**Comment by ramonbakker** [comment]
Ok, thanks!
