### ISSUE TITLE
autocomplete <C-l> not working for lsp_dynamic_workspace_symbols

### ISSUE THREAD

**Issue by jrwrigh** [nvim-telescope/telescope.nvim#2089]
### Description

In trying to use the `telescope.builtin.lsp_dynamic_workspace_symbols` picker, the documentation states that I can use `<C-l>` to get an auto complete menu to pre-filter the results by type of symbol. This works correctly for  `telescope.builtin.lsp_workspace_symbols`, but not for `telescope.builtin.lsp_dynamic_workspace_symbols`. When I try to use `<C-l>` for `telescope.builtin.lsp_dynamic_workspace_symbols`, I get the following error:

```
[telescope.actions.complete_tag]: No tag pre-filtering set for this picker
```

### Neovim version

```markdown
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Manjaro Linux

### Telescope version / branch / rev

`main`, 6a33ece

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.4.0

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `refactoring`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. Open `telescope.builtin.lsp_dynamic_workspace_symbols`
2. Do `<C-l>`

### Expected behavior

It to have a completion menu of the LSP symbol types

### Actual behavior

The above error message.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by smit2909** [comment]
Is this going to be worked on anytime soon?

**Comment by ten3roberts** [comment]
I am also having this issue. Typin `:class:` does not work either as no results are shown

**Comment by pogopaule** [comment]
For reference. This seems to have worked somewhen https://github.com/nvim-telescope/telescope.nvim/pull/1336/files

**Comment by jamestrew** [comment]
> For reference. This seems to have worked somewhen https://github.com/nvim-telescope/telescope.nvim/pull/1336/files
> 
> @fdschmidt93 can you confirm that your PR added this behavior and now it is broken?

This seems unrelated.
I'm taking a look into this issue now. I'll see what I can do.

**Comment by jamestrew** [comment]
Ok so I gotta admit, I've never used `lsp_dynamic_workspace_symbols` nor `lsp_workspace_symbols` so it took me a minute to notice this but based on the lsp request they make, the seem identical.

For a telescope perspective, it appears like `dynamic_workspace_symbols` is NOT a fuzzy finder and finds exact matches against the prompt. The finder used for it isn't conducive to filtering via symbols and I believe this picker never supported this and the fact that the documentation says you can is a documentation error.

Sorry to disappoint but I think the fix here is actually to remove the line about the filter key map from the documentation of `lsp_dynamic_workspace_symbols`. Getting `lsp_dynamic_workspace_symbols` to support symbol type filtering would require something hacky or some architectural changes. Not sure if it's worth the effort when the regular `lsp_workspace_symbols` exists and that already supports the symbol filtering.
