### ISSUE TITLE
Change extension's layout

### ISSUE THREAD

**Issue by anuvyklack** [nvim-telescope/telescope.nvim#2106]
### Description

I installed [yanky.nvim](https://github.com/gbprod/yanky.nvim) plugin. which provides Telescope extension. I try to change its layout with next code, but have no effect.

```lua
local telescope = require('telescope')

telescope.setup({
   ...
   extensions = {
      yank_history = {
         layout_strategy = 'vertical',
         layout_config = {
            vertical = {
               ...
            }
         }
      }
   }
})

telescope.load_extension('yank_history')
```

### Neovim version

```markdown
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Fedora 36

### Telescope version / branch / rev

master

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.2.1
```

### Steps to reproduce

-

### Expected behavior

Extensions layout is changed

### Actual behavior

not changed

### Minimal config

```Lua
-
```

**Comment by fdschmidt93** [comment]
This is a problem of `yanky.nvim` with how they merge explicit picker and user configuration. From what I can tell, there is now resolution of `telescope.setup.extensions` configuration and therefore it has no effect.

You should open a feature request over at `yanky.nvim` or maybe they have a different mechanism to resolve configs.

Anyways, closing, not a `telescope.nvim` core issue.
