### ISSUE TITLE
Add inprogress indiactor

### ISSUE THREAD

**Issue by ofirgall** [nvim-telescope/telescope.nvim#2107]
**Is your feature request related to a problem? Please describe.**
I don't know when my picker has finished to collect all the results.
E.g: live grep something in a big repo and you aren't sure the live grep has finished with no results or still running.

**Describe the solution you'd like**
An indicator next to the amount of results that lets you know if the picker is still running or not.

**Comment by Conni2461** [comment]
duplication of https://github.com/nvim-telescope/telescope.nvim/issues/1713 closing in favor

Thats the current status: https://github.com/nvim-telescope/telescope.nvim/issues/1713#issuecomment-1039291766
