### ISSUE TITLE
Autocmd after selecting/jumping

### ISSUE THREAD

**Issue by ofirgall** [nvim-telescope/telescope.nvim#2115]
**Is your feature request related to a problem? Please describe.**
I like to recenter the screen after jumping, I use telescope for lsp's goto's and its annoying that I need to recenter manually each time I jump, an autocmd post jumping will help me solve this issue

**Describe the solution you'd like**
Autocmd after telescope jumped

**Comment by l-kershaw** [comment]
The prompt buffer has its own filetype (`TelescopePrompt`), which you should be able to use for your own autocommand.
The `BufLeave` event would probably be my first choice to use, but there might be another that works better for you.

Closing for now, but feel free to reopen if you're still having issues

**Comment by ofirgall** [comment]
It doesn't fully work for me, not all telescope jumps are done after `TelescopePrompt`, `builtin.lsp_definitions` for example.

When a prompt was exist it works tho.
```lua
-- Auto recenter after TelescopePrompt
api.nvim_create_autocmd('BufLeave', {
	group = config_autocmds,
	pattern = '*',
	callback = function(events)
		local ft = api.nvim_buf_get_option(events.buf, 'filetype')
		if ft == 'TelescopePrompt' then
			api.nvim_feedkeys('zz', 'n', false)
		end
	end
})
```

**Comment by ofirgall** [comment]
This method triggers when telescope is aborted too, in my case I don't want to do anything after aborting a jump.

**Comment by Conni2461** [comment]
This could be solved with mappings
```lua
require('telescope').setup{
  defaults = {
    mappings = {
      i = {
        ["<CR>"] = require("telescope.actions").select_default + require("telescope.actions").center,
        ["<C-x>"] = require("telescope.actions").select_horizontal + require("telescope.actions").center,
        ["<C-v>"] = require("telescope.actions").select_vertical + require("telescope.actions").center,
        ["<C-t>"] = require("telescope.actions").select_tab + require("telescope.actions").center,
      },
      n = {
        ["<CR>"] = require("telescope.actions").select_default + require("telescope.actions").center,
        ["<C-x>"] = require("telescope.actions").select_horizontal + require("telescope.actions").center,
        ["<C-v>"] = require("telescope.actions").select_vertical + require("telescope.actions").center,
        ["<C-t>"] = require("telescope.actions").select_tab + require("telescope.actions").center,
      }
    }
  }
}
```

**Comment by ofirgall** [comment]
Thanks @Conni2461! I had no idea I can chain actions.
But It still doesn't solve the case of jumping without telescope prompt :(
