### ISSUE TITLE
Add option to sorter not to match on filename/path

### ISSUE THREAD

**Issue by clason** [nvim-telescope/telescope.nvim#212]
This would be useful for grep, where I usually want to search the file contents, not the file names. See

<img width="519" alt="Screenshot 2020-11-02 at 17 23 17" src="https://user-images.githubusercontent.com/2361214/97892271-19989d80-1d30-11eb-809f-cbe43a8eb963.png">

where the "best" match is a nuisance. (An alternative would be to bias towards the end of the string, but I think just ignoring the filepath would be cleaner.)

**Comment by yujinyuz** [comment]
I was about to file an issue regarding this.

Would this be available in the near future?

**Comment by Conni2461** [comment]
`grep_string` supports `opts.only_sort_text` since https://github.com/nvim-telescope/telescope.nvim/pull/419. I just think we forgot to close this issue. So closing it now
