### ISSUE TITLE
Results Columns options

### ISSUE THREAD

**Issue by Fabyao** [nvim-telescope/telescope.nvim#2121]
I am using the built in LSP references picker. By default the "Results" section is showing 2 columns. The filename/path and the "Mini preview" (I am not sure what the correct term is).

Having gone through the documentation, its not obvious how one would remove the "Mini preview" in red below:
![image](https://user-images.githubusercontent.com/5112982/183768450-85030be3-801b-42b0-a507-72cb8282c46b.png)

The rational behind my request is that the filename/path in my opinion should be prominent and take the entire width. The "mini preview" columns feels redundant specially when the full preview is showing above. Its kind of showing the same information twice.

Forgive me if this has been requested or documented already. If so I would appreciate some pointers

**Comment by Conni2461** [comment]
`:help telescope.builtin.lsp_references` you can pass in the option show_line=false to hide it.

I also dont like currently how we handle columns in some pickers. And i think we should move to the way we do live_grep / grep_string for some of them. I am pretty sure there is an issue for it (i think for diagnostics), Contributions are welcome :)

**Comment by Fabyao** [comment]
@Conni2461 Thank you. I will familiarise myself with the differences between live_grep and references regarding columns. If not already done, I will happily contribute. 

Apologies for not paying a closer attention to the docs. I will close this ticket

**Comment by Fabyao** [comment]
@Conni2461 I am trying to hide the text result column for live_grep. With the built in LSP, its done with `show_line=false` . However for live_grep/grep_string, as you suggested above, it is handled differently. 

Looking at the documentation with `help help telescope.builtin.live_grep` the only option I see that could achieve it is `additional_args`. By luck I stumbled on `vimgrep_arguments` in the doc which I assume to be the possible arguments as follows:
```
Default: {
          "rg",
          "--color=never",
          "--no-heading",
          "--with-filename",
          "--line-number",
          "--column",
          "--smart-case"
        }
```
With the above I tried :

```
defaults = {
		vimgrep_arguments = {
			"rg",
			"--color=never",
			"--no-heading",
			"--with-filename",
			"--line-number",
			"--column",
			"--smart-case",
                       "--show-line=false", <-- 
		},
}
```
Of course its not working. Any pointers?

**Comment by CoinCheung** [comment]
Hi, Can we set this option for live_grep and grep_string now ?
