### ISSUE TITLE
find_files 'Results' pane has extra characters in filename

### ISSUE THREAD

**Issue by brymon68** [nvim-telescope/telescope.nvim#2128]
### Description

I performed an update on plugins today and post update, when running 

```
:Telescope find_files
```

The output of the file names includes characters like: 

```
../user/autocommands.lua^[[0m
../user/plugins.lua^[[0m 
../user/colorizer.lua^[[0m
../settings/yamlls.lua^[[0m
```
Which appears to be terminal prompt characters though I am not certain. Furtheremore, I cant open the files since these characters seem to be appended to the filename. 

Screenshot attached. 

![Screen Shot 2022-08-11 at 2 59 38 PM](https://user-images.githubusercontent.com/8397405/184241305-f779a251-32b9-47df-a79d-58fb474f2143.png)

### Neovim version

```markdown
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/brycesec/neovim/build/cmake.config -I/Users/brycesec/neovim/src
```

### Operating system and version

macOS 12.5 - M1 Pro

### Telescope version / branch / rev

telescope 0.1.0

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.4.0

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. nvim
2. ```:Telescope find_files```

### Expected behavior

File names listed without special characters

### Actual behavior

See attached screenshot

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
uff can u try to run: `lua require("telescope.builtin").find_files { find_command = { "rg", "--color=never", "--files" }, }`

**Comment by brymon68** [comment]
@Conni2461  - That worked. Is that the path forward or?

**Comment by Conni2461** [comment]
no, we should force color=never for all commands that have a --color option, so people dont run into this. Its a simple fix. PR welcome :) I can also help if you are not familiar with lua and point you where you want to update it

**Comment by brymon68** [comment]
If you can point me to the fix, I'm happy to submit a PR. Whats the best way to coordinate?

**Comment by Conni2461** [comment]
needs to be added here https://github.com/nvim-telescope/telescope.nvim/blob/8746347ac4065f5795e7bd33c7912ab1152cca4b/lua/telescope/builtin/__files.lua#L183-L192 

- `fd` and `fdfind` is the same command
- `which` is for windows and can be ignored

check the options in the man page

**Comment by brymon68** [comment]
PR submitted. Wasn't able to test on windows since I dont have a windows machine, apologies.
https://github.com/nvim-telescope/telescope.nvim/pull/2130
