### ISSUE TITLE
`C-/` and `C--` not mappable to actions

### ISSUE THREAD

**Issue by primeapple** [nvim-telescope/telescope.nvim#2135]
### Description

I want to map `<C-/>` to split vertical and `<C-->` to split horizontal, but I'm unable to do so.

### Neovim version

```markdown
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Übersetzt von builduser

Features: +acl +iconv +tui
```

### Operating system and version

Arch Linux

### Telescope version / branch / rev

telescope 0.1.0

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.4.0

## ===== Installed extensions =====

## Telescope Extension: `dap`
  - INFO: No healthcheck provided

## Telescope Extension: `zf-native`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. Run telescope find files `Telescope find_files`
2. Search for something
3. Press `<C-/>` or `<C-->` in insert or normal mode

### Expected behavior

`<C-/>` opens file in vertical split
`<C-/>` opens file in horizontal split

### Actual behavior

`<C-/>` opens help menu in Insert mode, no action in normal mode
`<C-->` enters `-` in insert mode, no action in normal mode

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup({
  telescope.setup({
    defaults = {
        mappings = {
            i = {
                ['<C-->'] = 'select_horizontal',
                ['<C-/>'] = 'select_vertical',
            },
            n = {
                ['<C-->'] = 'select_horizontal',
                ['<C-/>'] = 'select_vertical',
            }
        }
    }
  })
  require('telescope').load_extension('fzf')
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
not a telescope issue, thats just how terminals work. Open a empty vim buffer and press `<C-v>` and then the key you want to map e.g. `<C-/>` and you get what the terminal interprets. So for `<C-/>` its `<C-_>`, so map that.

for `<C-->` is sadly only yields `?` so you can either map `?` or you can't map it. We cant do anything about this. Same btw applies to neovim.

**Comment by primeapple** [comment]
@Conni2461 , just so that you know: with certain terminals (I'm using kitty) it certainly is sending the right keys?

0. Use Kitty as Terminal Emulator
1. Open empty buffer, e.g. `nvim`
2. Press `:` `C-v` `C-/`
It shows `<C-/>`
3. The same with `C--`

It seems Neovim is handling the term codes a bit buggy :O
https://github.com/kovidgoyal/kitty/discussions/5342
