### ISSUE TITLE
Allow `actions.open_qflist` to utilize split modifiers like `:botright`, `:rightbelow`, etc

### ISSUE THREAD

**Issue by cptchuckles** [nvim-telescope/telescope.nvim#2142]
**Is your feature request related to a problem? Please describe.**
I use [simrat39/symbols-outline](https://github.com/simrat39/symbols-outline.nvim) and noticed that when I have a three-column window layout going on, invoking `telescope.acitons.open_qflist` will open the quickfix list in a split window under the last opened vertical window, which (in my use-case) means that it's inconveniently squished in the lower-right corner, under my symbol outliner [(fig. 1)](https://i.imgur.com/y0Am5wy.png)

Compare this to how the quickfix list opens when invoking `:lua vim.diagnostic.setqflist({open=true})` [(fig.2)](https://i.imgur.com/rZT6w9F.png)

I found out that `vim.diagnostic.setqflist` invokes `:botright copen`, whereas `telescope.actions.open_qflist` invokes just `:copen`.  Using `:botright` causes the next command to open a window that spans the whole neovim window, which in my opinion is vastly preferable in this case, since quickfix items tend to be long, and I can't read them when they end up in the corner.  Unfortunately there is no way to cause Telescope to use `:botright copen`, or any other kind of split modifier like `:rightbelow`, `:topleft`, etc.

**Describe the solution you'd like**
I would like `actions.open_qflist` to accept an opts table with a property that tells it whether to use a split-modifying command or not, and which one.

**Describe alternatives you've considered**
I could just keep moving the window that opens but that gets annoying.

**Additional context**
fig.1: quickfix list opened in the lower-right corner after invoking `actions.open_qflist`:
![fig.1: quickfix list opened in the lower-right corner](https://i.imgur.com/y0Am5wy.png)
*(note: in the above example, the center window was the last to have been focused before opening telescope)*

fig.2: quickfix list opened across the bottom of Neovim, since it was opened via `:botright copen`:
![quickfix list opened across the bottom of neovim via `:botright copen`](https://i.imgur.com/rZT6w9F.png)

**Comment by DasOhmoff** [comment]
I think so too. Also it should be an easy fix maybe

**Comment by juhaku** [comment]
This behavior can be achieved with really easy workaround with your own telescope configs.
```lua
local function send_to_quickfix(promtbufnr)
   telescope_actions.smart_send_to_qflist(promtbufnr)
   vim.cmd([[botright copen]])
end

telescope.setup({
  defaults = {
    mappings = {
      ["n"] = {
        ["<C-q>"] = send_to_quickfix,
      },
       ["i"] = {
         ["<C-q>"] = send_to_quickfix,
       },
     },
  },
})
```

**Comment by Myzel394** [comment]
@juhaku this doesn't seem to be working anymore :/
