### ISSUE TITLE
find_files and live_grep fail on Raspberry Pi 4 running Ubuntu 22.04

### ISSUE THREAD

**Issue by MrOnak** [nvim-telescope/telescope.nvim#2158]
### Description

There might be an issue with Telescope on ARM.

`:Telescope buffers` and other functions work just fine, but `fd`, `find_files` and `live_grep` do not. 

My actual minimal config is on github: https://github.com/MrOnak/neovim_cfg/tree/rpiminimal

The checkhealth output provided below was with your minimal.lua. Since that adds fzf it adds additional errors, see in actual behaviour.

This is on a Raspberry Pi 4 running Ubuntu 22.04, i3wm. 

- Lua 5.1 is installed, LuaJIT is `LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/`
- ripgrep is installed and in my PATH `ripgrep 13.0.0 -SIMD -AVX (compiled)`
- fd is installed and in my PATH  `fd 8.3.1`

Note that I have FZF installed and working on my command-line (zsh). I'm using fd as finder for FZF so FZF in general works on the architecture, just not in neovim.

### Neovim version

```markdown
NVIM v0.7.2
Build type: Release
Lua 5.1
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Ubuntu 22.04 server ARM

### Telescope version / branch / rev

latest

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:Telescope find_files`
3. type a known filename

### Expected behavior

`find_files`, `live_grep` etc should return results.

### Actual behavior

When opening `:Telescope find_files` the popup does open and allows me to type my query, but nothing happens.
After that, `:messages` contains this line once for every key pressed in the find_files popup:

```
[telescope] [WARN  17:47:05] (tail call):-1: Finder failed with msg:  attempt to yield across metamethod/C-call boundary
```

This behaviour is the same with your `minimal.lua` and mine on github that doesn't contain the fzf plugin.

The same error is thrown for `:Telescope find_files`, `:Telescope live_grep` and `:Telescope fd`.

With your `minimal.lua`, when opening nvim there's an additional error regarding fzf extension not being found. This obviously goes away when the fzf-native plugin isn't installed. The above warning is thrown no matter if fzf is included or not.
```
Error executing vim.schedule lua callback: Vim(lua):E5108: Error executing lua ...rt/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'fzf' extension doesn't exist or isn't installed: er
ror loading module 'ffi' from file '/usr/lib/aarch64-linux-gnu/lua/5.1/ffi.so':
        /usr/lib/aarch64-linux-gnu/lua/5.1/ffi.so: undefined symbol: luaopen_ffi
stack traceback:
        [C]: in function 'error'
        ...rt/telescope.nvim/lua/telescope/_extensions/init.lua:10: in function 'load_extension'
        ...rt/telescope.nvim/lua/telescope/_extensions/init.lua:62: in function <...rt/telescope.nvim/lua/telescope/_extensions/init.lua:61>
        (tail call): ?
        ...ome/dominique/.config/nvim/lua/dominique/minimal.lua:27: in function 'load_config'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_exec'
        ?: in function 'cmd'
        ...im/site/pack/packer/start/packer.nvim/lua/packer.lua:359: in function '?'
        ?: in function <?:256>
stack traceback:
        [C]: in function 'nvim_exec'
        ?: in function 'cmd'
        ...im/site/pack/packer/start/packer.nvim/lua/packer.lua:359: in function '?'
        ?: in function <?:256>
```

Furthermore, on launching nvim Packer throws the same error twice:
```
[packer.nvim] [ERROR 17:51:06] (tail call):-1: LuaJIT is required for Luarocks functionality!
```

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by nullchilly** [comment]
This issue https://github.com/nvim-telescope/telescope.nvim/issues/1174 might be related?

**Comment by MrOnak** [comment]
My bad, I should have searched for the warning after you pointed me to where to find it.

I do some coding but I'm a Lua noob. I have no clue what the metamethod warning is trying to tell me but yes I'd say the issue is related. 

Would you suggest I attempt to compile neovim by hand instead of relying on the PPA?

**Comment by nullchilly** [comment]
No don't compile neovim by hand, there are a lot of breaking changes on master branch

If the appimage works for you simply link it to /usr/bin/nvim

**Comment by MrOnak** [comment]
Just saw your edit, the appimage won't run on ARM64:

`zsh: exec format error: ./nvim.appimage`

**Comment by nullchilly** [comment]
Ah yeah you are running it on raspberry pi, sorry for the ignorance!

**Comment by MrOnak** [comment]
No worries :)

One question to maybe simplify the situation further. What's the expected behaviour without fzf, should `find_files` do anything at all? From what I understand it should fall back to system-level `find` and won't be fuzzy anymore?

The drastic error message about FFI only shows up when fzf is installed as per minimal.lua, the warning about the metamethod is the same in both cases.

**Comment by nullchilly** [comment]
fzf add more options for example you can write "!.mp4" to see files that do not end with .mp4

**Comment by MrOnak** [comment]
Sure, but find_files should do plain-old matches without fzf, correct?

BTW the flatpak version seems to exist for ARM64, installing atm.

Checking the fzf link you edited...

**Comment by MrOnak** [comment]
Re: fzf-instructions:

Well I'm in a make environment and my minimal config (the actual one) does have the `...run = 'make'` bit, so I'd say yes. 
The CMake instructions seem more involved but for make this seems to be all?

**Comment by nullchilly** [comment]
In any case just checkout this commit https://github.com/neovim/neovim/commit/e8ee6733926db83ef216497a1d660a173184ff39 and built from "master"

**Comment by MrOnak** [comment]
I've started the flatpak version: 
`flatpak run io.neovim.nvim -nu ~/.config/nvim/lua/dominique/minimal.lua`

No errors on launch and `:Telescope find_files` seems to work. 

`:Telescope live_grep` throws a whole bunch of warnings:

```
[telescope] [WARN  18:34:59] ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:489: Finder failed with msg:  ...ite/pack/packer/start/telescope.nvim/lua/telescope/_.lua:297: rg: Exe
cutable not found
[telescope] stack traceback:
[telescope] ^I...ite/pack/packer/start/telescope.nvim/lua/telescope/_.lua:297: in function 'convert_opts'
[telescope] ^I...ite/pack/packer/start/telescope.nvim/lua/telescope/_.lua:17: in function 'new'
[telescope] ^I...ite/pack/packer/start/telescope.nvim/lua/telescope/_.lua:63: in function 'spawn'
[telescope] ^I...elescope.nvim/lua/telescope/finders/async_job_finder.lua:49: in function 'finder'
[telescope] ^I...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:485: in function <...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:484>
[telescope] ^I[C]: in function 'pcall'
[telescope] ^I...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:484: in function <...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:450>
```

I'll attempt to build the commit you linked and get back to you

**Comment by MrOnak** [comment]
Alright, build complete. The binary works with `-nu minimal.lua` and both `:Telescope find_files` and `:Telescope live_grep` seem to work.

I have only built it, didn't install - at the moment I'm running neovim from build/bin inside the sources folder.

I'll do some tests with my actual configuration before I do anything else with the binary and I'll get back to you.

If in the meantime you have anything specific you want me to try do let me know.

**Comment by MrOnak** [comment]
Update: Not installing the binary yields all sorts of issues but I've gone ahead and installed everything to `$HOME/.local/bin/nvim`

Everything seems to work. I've done a checkout of my actual nvim configuration and it seems fine.

Now, the two million dollar questions:
1. I'm 'stuck' on a commit tag at the moment, what would you recommend for the future to build from, stable tags?
2. what can I do to help debug the actual issue?

Thanks for getting me here, how can I give back?

**Comment by nullchilly** [comment]
Yeah git tag should work, building from source once every 6 months should be too bad right?

> Thanks for getting me here, how can I give back?
Tomorrow is monday, get some rest :)

**Comment by MrOnak** [comment]
Ha :D Thanks a ton for the help

If you decide you want to dig into this further do let me know. Take care

**Comment by Conni2461** [comment]
This is a duplication of https://github.com/nvim-telescope/telescope.nvim/issues/1174 and can be seen here

> Neovim version
> NVIM v0.7.2
> Build type: Release
> Lua 5.1
> Compiled by team+vim@tracker.debian.org

The lua version that was used on compiling is Lua 5.1 and not luajit. We currently have issues with Lua 5.1 and thoes are documented in #1174.  Thats also why a rebuild from source fixes the issue for you, because `nvim --version` will probably now show luajit 2.1.0-beta3

So the ubuntu arm package maintainers decided to build against lua5.1, probably because of compatibility reasons and this broke things.

Glad to hear you got it working, thanks to @nullchilly for helping out :)

 Closing this as duplicate and resolved

**Comment by samrocksc** [comment]
well, glad i missed out on the compiling :P
