### ISSUE TITLE
random "key not present in dictionary rhs" error when opening telescope

### ISSUE THREAD

**Issue by brunobmello25** [nvim-telescope/telescope.nvim#2162]
### Description

Sometimes this error show up when trying to opening telescope.

![image](https://user-images.githubusercontent.com/29875060/188720778-e748f6ca-f014-4890-b03b-fc2c54ee67e7.png)

After I press enter telescope menu appears and I can enter insert mode and start typing normally, but nothing shows up.

![image](https://user-images.githubusercontent.com/29875060/188720900-ebfadd69-269e-430b-b9e1-31c31506ac0b.png)
![image](https://user-images.githubusercontent.com/29875060/188720926-5c42a665-3889-4ce4-b00a-3311c9c6f646.png)

I also can't close telescope without exiting neovim. After I restart neovim it works normally.

I still didn't figure out if there is a pattern to this crashes. I can update the issue as soon as I figure something out. I believe it has something to do with manipulating files with netrw, but it seems inconsistent

----- Update -----

I just tried to create a new file in netrw, and this error happened:

![image](https://user-images.githubusercontent.com/29875060/188729065-366b1070-dbef-489b-9dd6-2673daecba5c.png)

and right after that, I tried to open telescope find_files, and the error happened again:

![image](https://user-images.githubusercontent.com/29875060/188729146-8808bbbe-4202-4ad2-87ab-74b151a30630.png)

which means this might indeed be related to netrw

### Neovim version

```markdown
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

### Operating system and version

arch linux with kernel 5.19.7-arch1-1

### Telescope version / branch / rev

telescope 0.1.0

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.4.0
```

### Steps to reproduce

1. open neovim
2. launch telescope with `lua require('telescope.builtin').find_files({ hidden = true })`
3. try to reproduce the bug? maybe editing/deleting/renaming some files and then opening telescope

### Actual behavior

telescope crashes with the error shown in the first screenshot and requires a nvim restart to work again

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by brunobmello25** [comment]
I just edited the post with additional steps

**Comment by Conni2461** [comment]
Why did you close this issue? Did you resolve it? Do you mind sharing how you've done that?
