### ISSUE TITLE
Can we have a stand-alone variant of this tool? (an executable not a plug-in)

### ISSUE THREAD

**Issue by thisismygitrepo** [nvim-telescope/telescope.nvim#2166]
I'd like to have this tool outside vim, simply in the terminal. I came close to having an equivalent using `ugrep.exe`, `fzf.exe` and `bat.exe` but nothing really as good as this.

In particular, `ugrep` with `-Q` flag starts an interactive grep session but search results are slapped out to the terminal (file name along with its contents) as opposed to having the nice window separation between file names and contents. 

Additionally, `fzf` with `bat` give a similar experience, except that search is limited to filenames, not grepping.

Alternatively, if anyone managed to generate equivalent experience using exisiting tools please share. Thanks.

**Comment by Conni2461** [comment]
Its on the roadmap and mentioned [here](https://github.com/nvim-telescope/telescope.nvim/releases/tag/0.1.0) in the `Future Outlook` section, but we have not started development of a cli app.

But you can search file content with fzf on cli: https://github.com/junegunn/fzf/wiki/Examples#searching-file-contents just look through the Examples wiki page and search for the stuff you need

**Comment by thisismygitrepo** [comment]
Thanks. I've done more searching and found `fzf` integration with `ripgrep`. I even found [Powershell Bindings](https://github.com/kelleyma49/PSFzf)

All good, but would still wait for your off the self product.
