### ISSUE TITLE
Add a `..` to `find_files` to search in the parent directory of `cwd`

### ISSUE THREAD

**Issue by chrisgrieser** [nvim-telescope/telescope.nvim#2179]
**Is your feature request related to a problem? Please describe.**
When using `find_files`, the search is restricted to the `cwd`. Sometimes, I notice that the file I am looking for is actually in the parent directory of the `cwd`. In that case, I have to quit telescope, change the `cwd`, and trigger telescope again, which is quite cumbersome.

**Describe the solution you'd like**
Add an `..` item which on selection triggers `find_files` on the *parent* directory of the `cwd`. (Probably as an option for `find_files`.) That is the solution used by the [Open plugin](https://packagecontrol.io/packages/Open) for Sublime, and I find it to be very elegant solution to the problem.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/73286100/192736717-2b069965-279c-40c5-9f71-1759a0b9f1f7.png">

**Describe alternatives you've considered**
Best alternative I could come up with is have a keybinding to search the parent directory, e.g. `find_files{cwd='%:p:h:h'}`. It's quicker than changing the `cwd` manually, but still requires you to cancel the current telescope prompt, and trigger telescope again.

**Comment by microo8** [comment]
I would also love this functionality. Coming from CtrlP I've been used to opening the file list in the directory relative to the opened file (this can be done with `find_files{cwd=vim.fn.expand('%:p:h')}`), and when needed going to the parent directory with `..`

**Comment by danielo515** [comment]
Maybe provide an API to update the current view params? So if you provide a filter function, when it sees `..` it can reconfigure the current view to point to a different folder.
This will open the possibility to do other things omni-bar like, so for example searching for symbols if you prefix with `@` or search for tags when you prefix with `#` etc.

**Comment by nagy135** [comment]
I am too looking for this feature, but i noticed this ...maybe it can be used instead of find_files. It does much more but allows moving around dirs so maybe its good enough https://github.com/nvim-telescope/telescope-file-browser.nvim

**Comment by chrisgrieser** [comment]
I actually figured out a solution for this a while ago. This adds a small mapping that moves to the parent dir. :)

```lua
pickers = {
	find_files = {
		mappings = {
			i = {
				["<C-up>"] = function(prompt_bufnr)
					local current_picker =
						require("telescope.actions.state").get_current_picker(prompt_bufnr)
					-- cwd is only set if passed as telescope option
					local cwd = current_picker.cwd and tostring(current_picker.cwd)
						or vim.loop.cwd()
					local parent_dir = vim.fs.dirname(cwd)

					require("telescope.actions").close(prompt_bufnr)
					require("telescope.builtin").find_files {
						prompt_title = vim.fs.basename(parent_dir),
						cwd = parent_dir,
					}
				end,
			},
		},
	},
},
```

**Comment by nagy135** [comment]
cool, telescope-file-browser does something similair but maybe even better using that refresh method instead of closing and opening new picker ?
```lua
fb_actions.goto_home_dir = function(prompt_bufnr)
  local current_picker = action_state.get_current_picker(prompt_bufnr)
  local finder = current_picker.finder
  finder.path = vim.loop.os_homedir()

  fb_utils.redraw_border_title(current_picker)
  current_picker:refresh(
    finder,
    { new_prefix = fb_utils.relative_path_prefix(finder), reset_prompt = true, multi = current_picker._multi }
  )
end
```
