### ISSUE TITLE
Consider using DiagnosticSign... highlight groups for diagnostics picker or make them configurable

### ISSUE THREAD

**Issue by nghialm269** [nvim-telescope/telescope.nvim#2182]
**Is your feature request related to a problem? Please describe.**

I frequently use `telescope.builtin.diagnostics` to browse document/workspace diagnostics. But the colorscheme that I'm using (`gruvbox-material`) [does not add foreground color to the Diagnostic... groups](https://github.com/sainnhe/gruvbox-material/blob/66504cee3c4036b75a276abf52460c71ad5672a3/colors/gruvbox-material.vim#L412-L422), it's really hard to differentiate between different severity levels in the picker.

**Describe the solution you'd like**

Since telescope is extracting the diagnostic signs from `DiagnosticSign...`, I think it's better to also use `DiagnosticSign...` highlight groups.

**Describe alternatives you've considered**

Alternatives are to use `DiagnosticVirtualText...` highlight groups, or make the highlight groups configurable.

**Additional context**

Current behavior, using `Diagnostic...` highlight groups (`gruvbox-material` adds underline, not foreground color):

![image](https://user-images.githubusercontent.com/13317164/193412505-68630ac6-21cc-4f15-8dcb-00d3110a3310.png)

Wanted behavior, using `DiagnosticSign...` highlight groups:

![image](https://user-images.githubusercontent.com/13317164/193412801-bf35084c-47da-410c-afbb-cccaa0ae4bdc.png)

**Comment by Conni2461** [comment]
yeah, seems like a good idea (i prefer not to make them configurable here. We need a little bit opinionated stuff). PR welcome.

Needs to be changed in this function: `make_entry.gen_from_diagnostics`

**Comment by nghialm269** [comment]
@Conni2461 I suggested making them configurable because I'm worried this might break others' configuration. But if you're okay with that, here is the PR: #2194
