### ISSUE TITLE
Orderless match

### ISSUE THREAD

**Issue by otavioschwanck** [nvim-telescope/telescope.nvim#2185]
Emacs orderless is awesome as hell, is the think i most miss on emacs.

Would be nice to have on telescope:

```
This package provides an orderless completion style that divides the pattern into space-separated components, and matches candidates that match all of the components in any order. Each component can match in any one of several ways: literally, as a regexp, as an initialism, in the flex style, or as multiple word prefixes. By default, regexp and literal matches are enabled.
```

https://github.com/oantolin/orderless

**Comment by Conni2461** [comment]
Idk what exactly you want here. space separated components is already possible with https://github.com/nvim-telescope/telescope-fzf-native.nvim

With support for fuzzy, exact, prefix, suffix and invert

I have no idea what
- initialism, 
- flex style
is. regexp might be harder to implement.

We have a template that could have been filled out with a little bit more context.

I dont wanna do the research here before i am even sold on a feature!?

Does `orderless` keep the original order or so

**Comment by otavioschwanck** [comment]
> Idk what exactly you want here. space separated components is already possible with https://github.com/nvim-telescope/telescope-fzf-native.nvim
> 
> With support for fuzzy, exact, prefix, suffix and invert
> 
> I have no idea what
> 
> * initialism,
> * flex style
>   is. regexp might be harder to implement.
> 
> We have a template that could have been filled out with a little bit more context.
> 
> I dont wanna do the research here before i am even sold on a feature!?
> 
> Does `orderless` keep the original order or so

could you install doom emacs ?  i think the best way is you see for yourself.  In doom, just press SPC SPC to open the find_files

**Comment by Shougo** [comment]
If you request the feature, you should describe why the feature is really needed.
To recommend install Emacs, it is omitting crucial steps

**Comment by otavioschwanck** [comment]
> If you request the feature, you should describe why the feature is really needed. To recommend install Emacs, it is omitting crucial steps

@Shougo 

About the feature:

Is an alternative way to fuzzy find.  

While on telescope defaults i got:
<img width="813" alt="image" src="https://user-images.githubusercontent.com/9551316/195152492-43e2be0e-c6ce-401a-a433-6ef9467120c9.png">

With orderless, i got:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/9551316/195152612-6b1b48a5-e392-4a91-b3d8-bf2a7b785db4.png">

i can pass multiple words, separated by space, and somehow, it find, not depending on the order.  Here is other example:

On NVim (Telescope):
<img width="609" alt="image" src="https://user-images.githubusercontent.com/9551316/195153124-63d0db22-9094-43d0-9f23-c2e9f4499c66.png">


On Emacs (orderless):
<img width="374" alt="image" src="https://user-images.githubusercontent.com/9551316/195152914-2fcd4db2-6163-4110-85b3-2d5b0ee5d418.png">

**Comment by Conni2461** [comment]
> space separated components is already possible with https://github.com/nvim-telescope/telescope-fzf-native.nvim

Again install https://github.com/nvim-telescope/telescope-fzf-native.nvim. It has support for that kind of stuff.

Here are the examples

![image](https://user-images.githubusercontent.com/15233006/195164247-e97c16a6-4fc4-4e3b-99d8-68c660ad46cc.png)

![image](https://user-images.githubusercontent.com/15233006/195164274-601e9180-ef16-45c7-af64-6772ad1fa859.png)

it doesnt highlight the separate components differently, but it works !

**Comment by otavioschwanck** [comment]
> > space separated components is already possible with https://github.com/nvim-telescope/telescope-fzf-native.nvim
> 
> Like i already said. Does https://github.com/nvim-telescope/telescope-fzf-native.nvim support everything you need. Because it has support for that kind of stuff you mentioned. Install it and try it out.
> 
> Here are the examples
> 
> ![image](https://user-images.githubusercontent.com/15233006/195164247-e97c16a6-4fc4-4e3b-99d8-68c660ad46cc.png)
> 
> ![image](https://user-images.githubusercontent.com/15233006/195164274-601e9180-ef16-45c7-af64-6772ad1fa859.png)
> 
> it doesnt highlight the separate components differently, but it works

i will try, thanks!
