### ISSUE TITLE
Find and reuse window with previously opened file

### ISSUE THREAD

**Issue by michaelfranzl** [nvim-telescope/telescope.nvim#2188]
**Is your feature request related to a problem? Please describe.**

When I work, I have files systematically arranged in tabs and windows (using horizontal and vertical splits). When I use telescope to pick a file, it replaces the view on the buffer in the currently focused window with a view on the buffer of the picked file. Over time, this destroys the systematic arrangement of files. (One effect is that more and more windows are created with views on the same buffers.)

**Describe the solution you'd like**

When I pick a file using telescope, it should first search all buffers to decide if that file is already open. If yes, it should search all windows for that buffer. If there is one, it should focus that window (switching tabs if needed). If there are several windows with identical buffers (i.e. the same file), it is OK to simply focus the first occurrence. If the file is not currently open, the default behavior can apply (open the file in the currently focused window).

**Describe alternatives you've considered**

I tried https://github.com/vim-scripts/bufexplorer.zip . It also does not seem to do a window search. It can open a buffer in another tab, but this may also overwrite existing window views.

**Additional context**

The following vim command implements the desired behavior, but has the limitations to be confined to the currently focused tab, and that the filename is a `file-pattern` and not a fuzzy match.

```vimscript
:call win_gotoid(bufwinid('filename'))
```

**Comment by MaksRus** [comment]
Not sure this is related but I was about to ask this question :
When I select a file with Telescope, I would like it to **simply switch** to the corresponding already open buffer if it exists OR open the file in the current buffer.

I know this behaviour can be achieved natively with the **:drop** command and I was expecting Telescope to act this way, especially when using the "find_buffers" action since I find little use in duplicating buffers.... (it totally ruins my workflow and tab layout)

Is this issue coming from my configuration or is it something I'm missing here ?

**Comment by huyz** [comment]
That sounds like fzf's `g:fzf_buffers_jump = 1` option. And yes, I'm looking for that too. I wanna jump around the existing viewable buffers

**Comment by huyz** [comment]
Didn't know about the `:drop` command. What a funny name for it

**Comment by huyz** [comment]
Actually CtrlP's default option `let g:ctrlp_switch_buffer = 'Et'` is the most sensible of 
https://github.com/kien/ctrlp.vim/blob/564176f01d7f3f7f8ab452ff4e1f5314de7b0981/doc/ctrlp.txt#L145-L155

**Comment by hinell** [comment]
Thuming this up. I'm surprise that this feature isn't a default one.

**Comment by hinell** [comment]
@michaelfranzl @huyz @MaksRus @henrik I've opened a PR fixing this issue. Please thumb it up!

**Comment by leisurelicht** [comment]
I'm look for that too. When I go to lsp definition, I want to jump to a existing window. not open a new window or change current window. I think this should be a option.

**Comment by hinell** [comment]
@leisurelicht I think we need to tweak default `<CR>` action...

**Comment by leisurelicht** [comment]
@hinell sure, I think it is a good idea. I'm trying to read default select action code.

**Comment by hinell** [comment]
@leisurelicht Keep us updated on the progress!

**Comment by RsrnlWysxr** [comment]
I think we just need to add a new `jump_type`

**Comment by hinell** [comment]
It turns out you can actually configure it. In order to jump to an existing file in already opened `tab` or `window` from all file pickers, use the following:

```lua

local actions = require("telescope.actions")
require("telescope").setup({
		pickers = {
		buffers = {
			mappings = {
				i = { ["<CR>"] = actions.select_tab_drop }
		},
		find_files = {
			mappings = {
				i = { ["<CR>"] = actions.select_tab_drop }
			}
		},
		git_files = {
			mappings = {
				i = { ["<CR>"] = actions.select_tab_drop }
			}
		},
		old_files = {
			mappings = {
				i = { ["<CR>"] = actions.select_tab_drop }
			}
		},
	},
})
```

**Comment by kackerx** [comment]
> ```lua
> select_tab_drop
> ```

Why am I prompting key dose not exist for select _ tab _ drop,, version problem?

**Comment by jamestrew** [comment]
These are only currently available of the master branch: https://github.com/nvim-telescope/telescope.nvim/pull/2143
We'll be including these newer actions as part of telescope 0.2 that we'll try to release in the coming weeks.
I'll close this as all we need to do is to release the feature.
