### ISSUE TITLE
[feat] lsp_implementations option

### ISSUE THREAD

**Issue by kaiphat** [nvim-telescope/telescope.nvim#2189]
Add new option to lsp_implementations. When i open telescope with lsp_implementations picker, and telescope found only one reference, telescope closes and opens file, with this reference. It will be more comfortable for me.

**Comment by gutyina70** [comment]
With `lsp_implementations`, it jumps you to the implementation when there is only 1 (with the default options). You can add `jump_type = 'never'` to see the picker with 1 result.

I assume you're talking about `lsp_references`, which doesn't have this option, and it prompts you when there is only 1 reference found.
