### ISSUE TITLE
live grep the files in a quickfix list

### ISSUE THREAD

**Issue by l-bowman** [nvim-telescope/telescope.nvim#2190]
**Is your feature request related to a problem? Please describe.**
I have a problem narrowing down a list of files to fit an exact pattern. For example, I often want to find files which contain String A, String B, and String C. If I could also invert grep on the list, that would be a huge bonus!

**Describe the solution you'd like**
I would like an option to live grep just the files in a Quickfix list--the goal being to then generate another Quickfix list with the results, etc.

**Describe alternatives you've considered**
I have scoured for plugins that might fit the bill and also tried to understand custom pickers, but no solution so far.

**Comment by n0ks** [comment]
You may need to write a custom function for that.

I've made a simple function to search on qflists just by messing around in Lua and neovim apis. I hope that it helps

```lua 
M.live_grep_qflist = function()
        local qflist = vim.fn.getqflist()
	local filetable = {}
	local hashlist = {}

	for i, value in pairs(qflist) do
		local name = vim.api.nvim_buf_get_name(qflist[i].bufnr)

		if not hashlist[name] then
			hashlist[name] = true
			table.insert(filetable, name)
		end
	end

	builtin.live_grep({ search_dirs = filetable })
end
```

**Comment by l-bowman** [comment]
> You may need to write a custom function for that.
> 
> I've made a simple function to search on qflists just by messing around in Lua and neovim apis. I hope that it helps
> 
> ```lua
> local builtin = require("telescope.builtin")
> 
> M.live_grep_qflist = function()
>         local qflist = vim.fn.getqflist()
> 	local filetable = {}
> 	local hashlist = {}
> 
> 	for _, value in pairs(qflist) do
> 		local name = vim.api.nvim_buf_get_name(value.bufnr)
> 
> 		if not hashlist[name] then
> 			hashlist[name] = true
> 			table.insert(filetable, name)
> 		end
> 	end
> 
> 	builtin.live_grep({ search_dirs = filetable })
> end
> ```

Wow, thank you! I am using this to good effect. It is so useful. I think it should be a default option in the plugin. Is there any way that I can also do a reverse grep on a quickfix list? In other words, how can I exclude files that contain a search string? Thanks again!

**Comment by n0ks** [comment]
> > You may need to write a custom function for that.
> > I've made a simple function to search on qflists just by messing around in Lua and neovim apis. I hope that it helps
> > ```lua
> > local builtin = require("telescope.builtin")
> > 
> > M.live_grep_qflist = function()
> >         local qflist = vim.fn.getqflist()
> > 	local filetable = {}
> > 	local hashlist = {}
> > 
> > 	for _, value in pairs(qflist) do
> > 		local name = vim.api.nvim_buf_get_name(value.bufnr)
> > 
> > 		if not hashlist[name] then
> > 			hashlist[name] = true
> > 			table.insert(filetable, name)
> > 		end
> > 	end
> > 
> > 	builtin.live_grep({ search_dirs = filetable })
> > end
> > ```
> 
> Wow, thank you! I am using this to good effect. It is so useful. I think it should be a default option in the plugin. Is there any way that I can also do an invert grep on a quickfix list? In other words, how can I exclude files that contain a search string? Thanks again!
> 
> **Update**: I opened another issue for invert live grep.

i don't think another issue is needed, if u want to invert the search for items that do not include a match you should use `nvim-telescope/telescope-fzf-native.nvim`

**Comment by l-bowman** [comment]
> > > You may need to write a custom function for that.
> > > I've made a simple function to search on qflists just by messing around in Lua and neovim apis. I hope that it helps
> > > ```lua
> > > local builtin = require("telescope.builtin")
> > > 
> > > M.live_grep_qflist = function()
> > >         local qflist = vim.fn.getqflist()
> > > 	local filetable = {}
> > > 	local hashlist = {}
> > > 
> > > 	for _, value in pairs(qflist) do
> > > 		local name = vim.api.nvim_buf_get_name(value.bufnr)
> > > 
> > > 		if not hashlist[name] then
> > > 			hashlist[name] = true
> > > 			table.insert(filetable, name)
> > > 		end
> > > 	end
> > > 
> > > 	builtin.live_grep({ search_dirs = filetable })
> > > end
> > > ```
> > 
> > 
> > Wow, thank you! I am using this to good effect. It is so useful. I think it should be a default option in the plugin. Is there any way that I can also do an invert grep on a quickfix list? In other words, how can I exclude files that contain a search string? Thanks again!
> > **Update**: I opened another issue for invert live grep.
> 
> i don't think another issue is needed, if u want to invert the search for items that do not include a match you should use `nvim-telescope/telescope-fzf-native.nvim`

I don't think it's possible to inverse live grep with that version, but please let me know if I am wrong about that. I do see how an inverse pattern can be used to search for files. That is useful, but really I want to inverse grep within files.

**Comment by n0ks** [comment]
yeah i was messing around with it today and live grep doesn't work when trying to inverse with` ! `, but with grep_string it's fine as you can see here

<a href="https://asciinema.org/a/H55t0gDTidVnmqkUNLPP6i5ua" target="_blank"><img src="https://asciinema.org/a/H55t0gDTidVnmqkUNLPP6i5ua.svg" width="300" /></a>


```lua
-- same code as before but call grep_string
	builtin.grep_string({
		search = "",
		search_dirs = filetable,
	})

```

it filters the file name as well, but you can disable it with another parameter as you can see in the [docs](https://github.com/nvim-telescope/telescope.nvim/blob/master/doc/telescope.txt#L827)

**Comment by l-bowman** [comment]
> yeah i was messing around with it today and live grep doesn't work when trying to inverse with`!`, but with grep_string it's fine as you can see here
> 
> [<img alt="" width="300" src="https://camo.githubusercontent.com/0e00e197c29b0b0301fb789c27bdac117c11173adc32a17b49e06f5290dd0557/68747470733a2f2f61736369696e656d612e6f72672f612f48353574306744546964566e6d716b554e4c505036693575612e737667">](https://asciinema.org/a/H55t0gDTidVnmqkUNLPP6i5ua)
> 
> ```lua
> -- same code as before but call grep_string
> 	builtin.grep_string({
> 		search = "",
> 		search_dirs = filetable,
> 	})
> ```
> 
> it filters the file name as well, but you can disable it with another parameter as you can see in the [docs](https://github.com/nvim-telescope/telescope.nvim/blob/master/doc/telescope.txt#L827)

Thank you for sharing this! I may need to mess around with the options more, but I haven't quite found the setup that works for me. The ideal would be something that works like live_grep but allows for more complex searching. I want to get able to add arguments such as `!filetable` or `| filetable` immediately after a search term. A search with an excluded term should filter out all of the files which contain that string. If a search starts with something like `!filetable`, I want to just see a list of all files that do not contain that term.

**Comment by strboul** [comment]
Telescope has a builtin mapping `<M-q>` (namely <kbd>Alt</kbd><kbd>q</kbd>) to send the selected to the quickfix. I have the following solution that sends grep to quickfix, see here: https://github.com/strboul/dotfiles/blob/38d71dee4d415aa305a330ca1a8eef5fd0eeb6c5/files/nvim/lua/user/plugin/telescope.lua#L38-L44

**Comment by jamestrew** [comment]
There is an option `get_selection_window`
```
    Function that takes function(picker, entry) and returns a window id.
    The window ID will be used to decide what window the chosen file will
    be opened in and the cursor placed in upon leaving the picker.

    Default: `function() return 0 end`
```
that you can pass to `builtin.live_grep({...})` but I think it'll be a little awkward to use in this case.
By default, telescope opens the file in the last used window, so if you're coming directly from the quickfix window, then it'll use that.
I would probably just throw in a `vim.cmd("cclose")` before calling `live_grep` so the quickfix window is closed.
If you want access to it again, you can do `:copen`
