### ISSUE TITLE
invert live_grep

### ISSUE THREAD

**Issue by l-bowman** [nvim-telescope/telescope.nvim#2191]
**Is your feature request related to a problem? Please describe.**
I often want to generate a list of all files which do not contain `String A`. Grep has a `-v `option to accomplish this. I think this would be a great feature for Telescope.

**Describe the solution you'd like**
A simple way to perform a live invert grep.

**Describe alternatives you've considered**
I looked over the docs. I do not see an option for invert grep. I'm also unaware of extensions which offer this.

**Comment by Conni2461** [comment]
you can pass additional args to both live_grep and grep_string, but it seems like that `-v` changes the formatting of the rg output, so it no longer works with our parser. I'll fix that bug and then update how you can pass in that argument.

Will be done by this evening

**Comment by l-bowman** [comment]
> you can pass additional args to both live_grep and grep_string, but it seems like that `-v` changes the formatting of the rg output, so it no longer works with our parser. I'll fix that bug and then update how you can pass in that argument.
> 
> Will be done by this evening

That's fantastic! Thank you!

**Comment by l-bowman** [comment]
> you can pass additional args to both live_grep and grep_string, but it seems like that `-v` changes the formatting of the rg output, so it no longer works with our parser. I'll fix that bug and then update how you can pass in that argument.
> 
> Will be done by this evening

Can you provide an example of the syntax for passing this argument please? When I pass the -v flag, I would anticipate that live_grep would still search my current working directory contents, but exclude any files from the results/preview which contain a string matching the search. Is that correct?

**Comment by Conni2461** [comment]
thanks for confirming that its actually broken. i was 90% sure it wouldn't work out of the box.

https://github.com/nvim-telescope/telescope.nvim/pull/2208 should fix parsing for 
`:lua require('telescope.builtin').live_grep({additional_args = {'-lv'}})` and `:lua require('telescope.builtin').live_grep({additional_args = {'-v'}})`

**Comment by l-bowman** [comment]
> thanks for confirming that its actually broken. i was 90% sure it wouldn't work out of the box.
> 
> #2208 should fix parsing for `:lua require('telescope.builtin').live_grep({additional_args = {'-lv'}})` and `:lua require('telescope.builtin').live_grep({additional_args = {'-v'}})`
> 
> Would be awesome if you could test it. after that i would merge the PR. (Probably tomorrow, its already 10:30pm for me)

Cool! Happy to test. I tried to install your branch as a plugin, but Packer couldn't install it. What am I doing wrong?I tried:   

```
-- Telescope
  use({
    "Conni2461/telescope.nvim/tree/fix/rg_invert_matches_arg_parsing",
    requires = { { "nvim-lua/popup.nvim" }, { "nvim-lua/plenary.nvim" } },
  })

```

**Comment by Conni2461** [comment]
i think it should be

```lua
  use({
    "Conni2461/telescope.nvim", branch = "fix/rg_invert_matches_arg_parsing",
    requires = { { "nvim-lua/plenary.nvim" } },
  })
```

**Comment by Conni2461** [comment]
okay we aren't applying the filter, rg gives us the results!? What happens if you do the exact same query in your terminal?

`rg -lv Telescope` (just my assumption)

**Comment by l-bowman** [comment]
> okay we aren't applying the filter, rg gives us the results!? What happens if you do the exact same query in your terminal?
> 
> `rg -lv Telescope` (just my assumption)

Hmm, this doesn't seem to work in the terminal either. I am still seeing `which-key-settings.lua` returned, but it should be excluded for containing the search string. Any idea what is going on?

**Comment by Conni2461** [comment]
https://github.com/BurntSushi/ripgrep/issues/138

this means i had to update the PR, just run PackerSync, after that `lua require('telescope.builtin').live_grep({additional_args = {'--files-without-match'}})` should give you the expected behavior

**Comment by l-bowman** [comment]
> [BurntSushi/ripgrep#138](https://github.com/BurntSushi/ripgrep/issues/138)
> 
> this means i had to update the PR, just run PackerSync, after that `lua require('telescope.builtin').live_grep({additional_args = {'--files-without-match'}})` should give you the expected behavior

The file appears to be correctly excluded now, but the display is strange: 32 / 42 / `42.`
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/100594833/197858969-42c6f348-a697-4600-a9cd-ed62c67a923c.png">

**Comment by Conni2461** [comment]
Thats a problem of live grep in general and not of that issue.

Items selected / Items filtered / Items in list

The last two filtered and in list, are the same because live_grep isn't filtering, because it always gets data directly from rg after each prompt change.

I'll fix this in a different PR and will merge #2208 Ill open a new issue for strange display

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/issues/2210 is the new issue for the displaying issue

**Comment by l-bowman** [comment]
Thanks! @Conni2461

**Comment by brookhong** [comment]
I just implemented such feature in [my telescope extension](https://github.com/brookhong/telescope-pathogen.nvim), please see the [showcase on Youtube](https://www.youtube.com/watch?v=cCeIuBG4vYM).
