### ISSUE TITLE
current_buffer_fuzzy_find incomplete highlighting

### ISSUE THREAD

**Issue by ziontee113** [nvim-telescope/telescope.nvim#2192]
### Description

Hi, today I tried `Telescope current_buffer_fuzzy_find` and it gives me an Error, seems to be related to Treesitter.
```
E5108: Error executing lua: ...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:413: attempt to call method '_get_hl_from_capture' (a nil value)
stack traceback:
        ...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:413: in function 'v'
        ...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:529: in function 'v'
        ...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:514: in function 'current_buffer_fuzzy_find'
        [string ":source (no file)"]:6: in function <[string ":source (no file)"]:3>
```

### Neovim version

```markdown
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Arch Linux

### Telescope version / branch / rev

0.1.0

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.4.0

## ===== Installed extensions =====

~
~
```

### Steps to reproduce

Run `Telescope current_buffer_fuzzy_find`

### Expected behavior

It works, with proper Treesitter highlighting

### Actual behavior

Breaks on Telescope 0.1.0
No highlight on main branch

### Minimal config

```Lua
---
```

**Comment by max397574** [comment]
https://github.com/nvim-telescope/telescope.nvim/issues/2149
duplicate
looks like the fix isn't in Telescope 0.1.0

**Comment by ziontee113** [comment]
And on the main branch there is no treesittter highlighting for search results

**Comment by Conni2461** [comment]
> looks like the fix isn't in Telescope 0.1.0

ofc not, its a fixed tag. Bugfix was backported to the 0.1.x branch and i plan to do a 0.1.1 release soon. 

highlighting is still done with treesitter, otherwise we couldn't even get the positions of the highlights. But it seems like we are missing highlighting groups, which makes our highlighting incomplete.
I'll look into it

**Comment by chenlei0x** [comment]
Hi
This problem still occurs with latest neovim version, is there any plan to merge the fix into release version??
Or any way to work around this??

**Comment by JoseEscobarBendezu** [comment]
Any Update ?

**Comment by lawrence-laz** [comment]
A copy/paste workaround for packer users:
```lua
    use {
        'nvim-telescope/telescope.nvim',
        branch = '0.1.x', -- <<<<<<<<<<<<<
        requires = { { 'nvim-lua/plenary.nvim' } }
    }

```

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/2394 fixes the highlighter and  after that there should be again full treesitter highlighting. can someone confirm this? after that i would merge.

Thanks for your patients :)
