### ISSUE TITLE
attempt to call field 'create' (a nil value)

### ISSUE THREAD

**Issue by caelumable** [nvim-telescope/telescope.nvim#2199]
### Description

There are the message when I typed "Telescope find_files"

Error executing Lua callback: ...ck\packer\start\telescope.nvim/lua/telescope/pickers.lua:327: attempt to call field 'create' (a nil value)                                                                        
stack traceback:
        ...ck\packer\start\telescope.nvim/lua/telescope/pickers.lua:327: in function '_create_window'
        ...ck\packer\start\telescope.nvim/lua/telescope/pickers.lua:378: in function 'find'
        ...r\start\telescope.nvim/lua/telescope/builtin/__files.lua:305: in function 'v'
        ...r\start\telescope.nvim/lua/telescope/builtin/__files.lua:533: in function 'v'
        ...cker\start\telescope.nvim/lua/telescope/builtin/init.lua:510: in function <...cker\start\telescope.nvim/lua/t                                                                                  elescope/builtin/init.lua:479>
        ...ck\packer\start\telescope.nvim/lua/telescope/command.lua:188: in function 'run_command'
        ...ck\packer\start\telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
        ...te\pack\packer\start\telescope.nvim\plugin\telescope.lua:108: in function <...te\pack\packer\start\telescope.                                                                                  nvim\plugin\telescope.lua:107>

### Neovim version

```markdown
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az177-603
```

### Operating system and version

windows10

### Telescope version / branch / rev

telescope 0.1.x

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.4.0

## ===== Installed extensions =====

## Telescope Extension: `env`
  - INFO: No healthcheck provided

## Telescope Extension: `ui-select`
  - INFO: No healthcheck provided
```

### Steps to reproduce

use {
    'nvim-telescope/telescope.nvim', branch = '0.1.x', -- I don't know why, when I installed the 0.1.0 version, it just couldn't checkhealth the telescope.
    requires = { {'nvim-lua/plenary.nvim'} }
    }
    use {'nvim-telescope/telescope-ui-select.nvim' }
    use "nvim-telescope/telescope-live-grep-raw.nvim"
    use "MattesGroeger/vim-bookmarks"
    use "tom-anders/telescope-vim-bookmarks.nvim"
    use "BurntSushi/ripgrep"
    use {'nvim-telescope/telescope-fzf-native.nvim', run = 'make' }
    use "LinArcX/telescope-env.nvim"
    -- treesitter
    use({
      "nvim-treesitter/nvim-treesitter",
      run = ":TSUpdate",
    })
    use("p00f/nvim-ts-rainbow")

note: because of the poor network, I downloaded the latest files from the homepage and extracted the files and pasted them to the nvim-data folder. 

### Actual behavior

Error executing Lua callback: ...ck\packer\start\telescope.nvim/lua/telescope/pickers.lua:327: attempt to call field 'create' (a nil value)                                                                        
stack traceback:
        ...ck\packer\start\telescope.nvim/lua/telescope/pickers.lua:327: in function '_create_window'
        ...ck\packer\start\telescope.nvim/lua/telescope/pickers.lua:378: in function 'find'
        ...r\start\telescope.nvim/lua/telescope/builtin/__files.lua:305: in function 'v'
        ...r\start\telescope.nvim/lua/telescope/builtin/__files.lua:533: in function 'v'
        ...cker\start\telescope.nvim/lua/telescope/builtin/init.lua:510: in function <...cker\start\telescope.nvim/lua/t                                                                                  elescope/builtin/init.lua:479>
        ...ck\packer\start\telescope.nvim/lua/telescope/command.lua:188: in function 'run_command'
        ...ck\packer\start\telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
        ...te\pack\packer\start\telescope.nvim\plugin\telescope.lua:108: in function <...te\pack\packer\start\telescope.                                                                                  nvim\plugin\telescope.lua:107>

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by caelumable** [comment]
eum..it seems my problem. I get plenary from other source and caused this problem, sorry...

**Comment by lishuaijiang** [comment]
I have the same problem. How did you solve it

**Comment by CoderWeiJ** [comment]
> I have the same problem. How did you solve it

I'm going to use the previous tag(telescope and plenary),it is well
