### ISSUE TITLE
Live Grep display no result

### ISSUE THREAD

**Issue by changcui** [nvim-telescope/telescope.nvim#2204]
### Description

I have installed ripgrep and fd.
Both of them are in the PATH environment.
But I can use live grep, it shows no result.

### Neovim version

```markdown
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az395-591

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

linux centos7 based

### Telescope version / branch / rev

latest

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.4.0

## ===== Installed extensions =====
```

### Steps to reproduce

1. vim
2. <leader>fg

### Actual behavior

live grep show no result in the poping window

### Minimal config

```Lua
call plug#begin()
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

let mapleader=","

lua << EOF
require('telescope').setup{}
EOF

nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>
```

**Comment by Conni2461** [comment]
did you start typing? live_grep sends each prompt to `rg` and displayes these results. If there is no prompt, like on startup nothing is sent to `rg`.

If you want something like `:Rg` which indexes all lines and then uses the fuzzy algo you can do `:Telescope grep_string search=` (so a search with an empty input)

**Comment by changcui** [comment]
Yeah, I have. But it still shows nothing.

**Comment by changcui** [comment]
Sometimes it will show a result stars with <stdin>.
It seems rg only search text from stdin instead of the files in the folder.
I have no clue about it.

**Comment by nparthas** [comment]
I'm also seeing this, only difference in setup is neovim 0.8.0. The exact same config is working on an older computer that I use. Could it be some macos permissions issue?

**Comment by nparthas** [comment]
Hmm seemed to figure it out... there's some package that isn't covered in `checkhealth telescope` but is required for some reason. One of `wget`, `node` or `pylint` is required.

**Comment by changcui** [comment]
Thanks for your reply.
I checked and installed wget, node and pylint.
But it seems not working either.
Here is the versions of them.

~ ❯ wget --version

 ***@***.*** 10:43:40
GNU Wget 1.14 built on linux-gnu.

~ ❯ node --version

 ***@***.*** 10:43:38
v16.14.0

~ ❯ pylint --version

 ***@***.*** 10:43:51
pylint 2.13.9
astroid 2.11.7
Python 3.6.8 (default, Apr 19 2021, 17:20:37)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

nparthas ***@***.***> 于2022年11月1日周二 03:30写道：

**Comment by nparthas** [comment]
Not too sure, can you post your output of `:checkhealth` maybe? Also I did do a restart, maybe that helped. I'm on a very new MacOS build so out versions are probably very different.

**Comment by changcui** [comment]
> Not too sure, can you post your output of `:checkhealth` maybe? Also I did do a restart, maybe that helped. I'm on a very new MacOS build so out versions are probably very different.

Reboot does work! Thanks a lot.
