### ISSUE TITLE
Feature: open telescope in current window/split instead of popup window

### ISSUE THREAD

**Issue by maln0ir** [nvim-telescope/telescope.nvim#2212]
**Describe the solution you'd like**

Currently telescope opens in popup window.  I would like to be able to open it in current window instead.  Similar to how `fzf.vim` can do it.

**Describe alternatives you've considered**

fzf.vim.  When configured like this:

``` vim
let g:fzf_layout = { 'window': 'enew' }
```

`fzf` runs in window instead of popup window.

I would like to be able to replicate this behaviour in telescope.

**Comment by l-kershaw** [comment]
Does something like `:Telescope find_files layout_strategy=current_buffer` fit your needs?

**Comment by stellarhoof** [comment]
Here's a simplified version of `current_buffer` that suits my needs of a minimal picker that takes over the current window:
```lua
require("telescope.pickers.layout_strategies").window = function(self, _, _, _)
  local opts = require("telescope.pickers.window").get_initial_window_options(self)
  local width = vim.api.nvim_win_get_width(0)
  local height = vim.api.nvim_win_get_height(0)
  local pos = vim.api.nvim_win_get_position(0)
  local line = pos[1]
  local col = pos[2]
  return {
    preview = false,
    results = vim.tbl_extend("force", opts.results, {
      border = false,
      width = width,
      height = height - 1,
      line = line + 2,
      col = col + 1,
    }),
    prompt = vim.tbl_extend("force", opts.prompt, {
      border = false,
      width = width,
      height = 1,
      line = line + 1,
      col = col + 1,
    }),
  }
end
```

It looks like this

<img width="961" alt="image" src="https://user-images.githubusercontent.com/4336260/210260720-73740f62-4234-4818-9f63-3a0318f1b601.png">

**Comment by maln0ir** [comment]
Sorry for late response.  I wasn't aware this was already implemented, to some extent.

@stellarhoof Your function does almost everything I wanted, thank you!

I think I can close this issue.

**Comment by sarmong** [comment]
@stellarhoof Thanks for the snippet. Do you know if it is possible to not close telescope when switching to another window?
