### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by antosha417** [nvim-telescope/telescope.nvim#2213]
As of the latest neovim release mouse is enabled for all users by default. 
And I see more and more plugins are adding mouse support. 
Right now for me telescope just closes if I click somewhere with a mouse. 

**Should we provide mouse support for telescope?**

**Comment by chinnkarahoi** [comment]
I map some mouse actions in telescope setup, which works well.
```lua
mappings = {
  i = {
    ["<RightMouse>"] = actions.close,
    ["<LeftMouse>"] = actions.select_default,
    ["<ScrollWheelDown>"] = actions.move_selection_next,
    ["<ScrollWheelUp>"] = actions.move_selection_previous,
  }
}
```

**Comment by lchen-p** [comment]
Is 

> I map some mouse actions in telescope setup, which works well.
> 
> ```lua
> mappings = {
>   i = {
>     ["<RightMouse>"] = actions.close,
>     ["<LeftMouse>"] = actions.select_default,
>     ["<ScrollWheelDown>"] = actions.move_selection_next,
>     ["<ScrollWheelUp>"] = actions.move_selection_previous,
>   }
> }
> ```

This is nice. But sometimes my mouse is outside in the area of the telescope popup (like going back from a different screen), left click will also select the default item, which I don't want... Is it possible to check the condition that my mouse is on the selected item?

**Comment by enesaltinkaya** [comment]
>     ["<LeftMouse>"] = actions.select_default,

Instead of default can we just select the item under the cursor please.
