### ISSUE TITLE
lsp_code_actions don't execute selected action

### ISSUE THREAD

**Issue by ChrisAmelia** [nvim-telescope/telescope.nvim#222]
```
NVIM v0.5.0-812-gd17e50879
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**init.vim**
```vim
set runtimepath^=~/.local/share/nvim/plugged/nvim-lspconfig
set runtimepath^=~/.local/share/nvim/plugged/plenary.nvim
set runtimepath^=~/.local/share/nvim/plugged/telescope.nvim
set runtimepath^=~/.local/share/nvim/plugged/popup.nvim

lua << EOF
	local nvim_lsp = require 'nvim_lsp'
	local root_pattern = nvim_lsp.util.root_pattern

	require'nvim_lsp'.jdtls.setup{
		root_dir = root_pattern(".git", "pom.xml"),
	}
EOF
```

**Main.java**
```java
public class Main {

    public static void main(String[] args) {
        ArrayList list = new ArrayList<>(); // ArrayList cannot be resolved to a type
    }

}
```
 
![image](https://user-images.githubusercontent.com/16366403/98224283-96579180-1f53-11eb-97bc-6d07be5b2830.png)

When calling `lsp_code_actions()` with `:lua require'telescope.bulitin'.lsp_code_actions{}`, the popup with the different actions appears as expected. Though upon selecting one action, nothing happens, I would expect the import to be done.

Edit: Seems the bare function `:lua vim.lsp.buf.code_action()` doesn't, for this case, work anymore.

**Comment by tjdevries** [comment]
Hmmm, is this still happening? Does this happen no matter how you call the code action stuff?

**Comment by ChrisAmelia** [comment]
Yes, the issue is still happening (tested with the last appimage), I've opened a thread there https://github.com/neovim/nvim-lspconfig/issues/397

I simply open the java file then execute `:lua vim.lsp.buf.code_action()` then select any available option.

**Comment by ChrisAmelia** [comment]
With https://github.com/neovim/nvim-lspconfig/pull/429/files

`:lua vim.lsp.buf.code_action()` works but not `:lua require'telescope.builtin'.lsp_code_actions()`.

**Comment by tjdevries** [comment]
Hmmm.... when I just tried it with Go, it worked perfectly.

**Comment by ChrisAmelia** [comment]
Effectively, tested with go and it works.

**Comment by ChrisAmelia** [comment]
Doesn't telescope's `code_actions()` rely on nvim's built-in one?
Maybe this explains the issue with telescope? https://github.com/neovim/nvim-lspconfig/pull/429#discussion_r537110059

**Comment by Matsuuu** [comment]
Bump. I've run into this too

**Comment by tjdevries** [comment]
So, it's not possible that we can handle all the combinations of ways that servers send random things I don't think.

I have provided hooks in #735 

Can you try and fix with these hooks?

**Comment by Matsuuu** [comment]
I might have been able to implement a solution for this. Will build upon your PR

**Comment by Matsuuu** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/738/ Created a PR to your PR, which should fix the error for Java users

**Comment by Conni2461** [comment]
should be adressed by this commit https://github.com/nvim-telescope/telescope.nvim/commit/aaffa84ebb0d411eafe2347e2ee0424af1199219

So i am closing this for now. If it isnt fixed feel free to reopen :)
