### ISSUE TITLE
Telescope lsp_workspace_diagnostics

### ISSUE THREAD

**Issue by barrett-ruth** [nvim-telescope/telescope.nvim#2222]
**Is your feature request related to a problem? Please describe.**
Telescope offers the `diagnostics` function to survey diagnostics of open buffers. However, it has no way of detecting diagnostics within unopened files/buffers.

**Describe the solution you'd like**
Similarly to `fzf-lua`, implement a `lsp_workspace_diagnostics` that shows all diagnostics in the workspace, even if the files with the errors haven't been opened.

**Describe alternatives you've considered**

**Additional context**

**Comment by Conni2461** [comment]
We do exactly the same thing as they do

https://github.com/ibhagwan/fzf-lua/blob/5eeacc2f6646a2b51f99cb321c4d1e6c48abf22f/lua/fzf-lua/providers/diagnostic.lua#L111-L112

https://github.com/nvim-telescope/telescope.nvim/blob/4bd4205028d6588cf2e0a1346687a6039b0f0a7c/lua/telescope/builtin/__diagnostics.lua#L74

Just set `bufnr = nil`, like described in `telescope.builtin.diagnostics`

You can also read more on this topic here, on why both plugins do it like this: `help vim.diagnostic.get`

**Comment by barrett-ruth** [comment]
Wow, `sumneko_lua` just takes an exorbidant amount of time to start up so no LSP diagnostics show until a bit. I checked out the code between the two and indeed thought it was identical. Apologies!

**Comment by randomizedthinking** [comment]
The current workspace diagnostics would only show diagnostics for open buffers, but not all files in the project -- that's why it is called workspace diagnostics.
