### ISSUE TITLE
"Telescope registers" throws an exception: Undefined variable pfile

### ISSUE THREAD

**Issue by j-xella** [nvim-telescope/telescope.nvim#2228]
### Description

I am unable to use the "registers" telescope extension. It does not start.

### Neovim version

```markdown
NVIM v0.9.0-dev-181+gd4ca5c22c
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux

### Telescope version / branch / rev

On branch 0.1.x ; commit 4bd4205

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()$
========================================================================$
## Checking for required plugins$
  - OK: plenary installed.$
  - WARNING: nvim-treesitter not found._$

  8 ## Checking external dependencies$
  9   - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)$
 10   - OK: fd: found fd 8.4.0$
 11 $
 12 ## ===== Installed extensions =====$
 13 $
 14 ## Telescope Extension: `fzf`$
 15   - INFO: No healthcheck provided$
```

### Steps to reproduce

```
:Telescope registers
```

### Expected behavior

The normal behaviour

### Actual behavior

All I get is this exception:

```
Error executing Lua callback: Vim:E121: Undefined variable: pfile
stack traceback:
        [C]: in function 'getreg'
        ...packer/start/telescope.nvim/lua/telescope/make_entry.lua:798: in function 'entry_maker'
        ...scope.nvim/lua/telescope/finders/async_static_finder.lua:17: in function 'new_table'
        ...tart/telescope.nvim/lua/telescope/builtin/__internal.lua:1088: in function 'v'
        ...tart/telescope.nvim/lua/telescope/builtin/__internal.lua:1364: in function 'v'
        ...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:510: in function <...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:479>
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:188: in function 'run_command'
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
        ...te/pack/packer/start/telescope.nvim/plugin/telescope.lua:109: in function <...te/pack/packer/start/telescope.nvim/plugin/telescope.lua:108>
```

### Minimal config

```Lua
not sure ...
```

**Comment by jakubgros** [comment]
I experienced the same. I have noticed that the bug occurs only when you start nvim with a folder provided as an argument. When file is provided or nothing, it works:

no error:
nvim
nvim a_file

error:
nvim a_folder

**Comment by Oumar-1** [comment]
I am experiencing the same issue and was wondering if you have found a solution to it?
thanks @jakubgrop for the suggestion.

**Comment by bootleq** [comment]
The error can also be produced with `:lua = vim.fn.getreg('=')`, when start nvim with a folder like @jakubgros said.
It is weird that `"=` has content `pfile` here, seems like an neovim misbehavior.

**Comment by bootleq** [comment]
After some tracing, found the `"=` was set by netrw ([neovim/netrw.vim#L11021](https://github.com/neovim/neovim/blob/fa12b9ca2b1dd5515/runtime/autoload/netrw.vim#L11021)).
With `put =pfile` where `pfile` is not defined, a `getreg('=')` raise this error reasonably.

We can fix it by provide second argument of getreg like `getreg('=', 1)` in make_entry:
https://github.com/nvim-telescope/telescope.nvim/blob/dce1156ca103b8222e4abbfc63f9c6887abf5ec6/lua/telescope/make_entry.lua#L834
