### ISSUE TITLE
Buffers preview: file path is not expanded correctly

### ISSUE THREAD

**Issue by metalelf0** [nvim-telescope/telescope.nvim#226]
Hi, I think there's an issue with how the file path is passed to `bat` for previewing.

This happens when I have a session with buffers open outside the current working directory, so the builtin `buffers{}` lists them as paths relative to my home dir (e.g. `~/Documents/whatever.txt`). This results in a `bat` error, as bat doesn't expand quoted paths (`bat ~/Documents/whatever.txt` works, but `bat '~/Documents/whatever.txt'` or `bat "~/Documents/whatever.txt"` don't). The error message I see in the preview window is exactly: 

```
[bat error]: '~/Documents/whatever.txt': No such file or directory (os error 2)
```

Some considerations:
- `bat` version is `0.16.0`
- `nvim` version is `NVIM v0.5.0-d17e50879 - Build type: Release`
- I'm on macOS `10.15.7` and my `$SHELL` is zsh, but it's not a shell issue, bash behaves exactly the same way
- I frequently update `telescope.nvim` to latest version
- well, obviously, the file exists ;)

Relevant config:

```
" Telescope {{{2
lua <<EOF
-- bat is not expanding '~', so let's try this.
-- UPDATE: no, it's not working
require('telescope').setup {
  defaults = {
    shorten_path = false -- currently the default value is true
  }
}
EOF

nnoremap <Leader>p <cmd>lua require'telescope.builtin'.find_files{}<CR>
nnoremap <Leader>/ <cmd>lua require'telescope.builtin'.live_grep{}<CR>
nnoremap <Leader>K <cmd>lua require'telescope.builtin'.grep_string{ search = cword }<CR>
nnoremap <Leader>B <cmd>lua require'telescope.builtin'.buffers{}<CR>
" }}}
```

Let me know if I can provide any further info.

Thanks a lot!

**Comment by Conni2461** [comment]
Thanks for reporting this. I hijacked another pr that i opened this morning, which fixed a bug i introduced last night, to fix your mentioned issue aswell. Could you try out #225

**Comment by metalelf0** [comment]
@Conni2461 I confirm your PR fixes the bug above! Thanks!

Considering you're working on this, there's another scenario `bat` can't handle, and it's when the provided path is a directory (it returns `[bat error]: '/Users/yourname/yourpath' is a directory.`). Maybe this could be something to take a look into? In this case, it would be great if a `ls`-like previewer could kick-in. Let me know if you want me to open a separate issue.

Thanks again!

**Comment by Conni2461** [comment]
Thanks for the suggestion. PR is updated.
When do you actually encounter directories. `find_files` and `git_files` should not display them if i recall correctly. So these should only be displayed when you have a buffer in which a directory is opened. Am i right?

**Comment by metalelf0** [comment]
Yes, right. I can only see them in the buffer builtin.

**Comment by tjdevries** [comment]
OK, merged. Thanks for all the great work @Conni2461
