### ISSUE TITLE
Line number shows when a telescope window quit

### ISSUE THREAD

**Issue by omegahh** [nvim-telescope/telescope.nvim#2260]
### Description

https://user-images.githubusercontent.com/5026687/205484635-cf9510fe-98d2-41b8-8741-6d60b2138518.mov

### Neovim version

```markdown
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

archlinux

### Telescope version / branch / rev

master

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.5.3

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - OK: lib working as expected
  - OK: file_sorter correctly configured
  - OK: generic_sorter correctly configured
```

### Steps to reproduce

1. :Telescope any_subcommand
2. quit window

### Expected behavior

just quit window, no line number shows

### Actual behavior

show line number when quitting telescope, in dashboard (by glepnir/dashboard.nvim) or filetree (by nvim-tree/nvim-tree.lua).

### Minimal config

```Lua
local actions = require("telescope.actions")

require("telescope").setup {
	defaults = {
		prompt_prefix = "  ",
		selection_caret = " ",
		entry_prefix = "  ",
		scroll_strategy = "limit",
		file_ignore_patterns = {
			"^.git/", ".cache", "%.class", "%.pdf", "%.mkv", "%.mp4", "%.zip", "%.gz",
			"%.jpeg", "%.jpg", "%.png", "%.svg", "%.otf", "%.ttf",
			"__pychace__", "%.ipynb", "%.sqlite3", "%.hdf5", "%.npz"
		},

		layout_config = {
			horizontal = {
				preview_width = 0.5,
			},
		},
		mappings = {
			-- change mapping for move previous/next in insert mode
			i = {
				["<ESC>"] = actions.close,
				["<C-j>"] = actions.move_selection_next,
				["<C-k>"] = actions.move_selection_previous,
			},
			n = {
				["<ESC>"] = actions.close,
			}
		},
	},
	extensions = {
		fzf = {
			fuzzy = true,                   -- false will only do exact matching
			override_generic_sorter = true, -- override the generic sorter
			override_file_sorter = true,    -- override the file sorter
			case_mode = "smart_case",       -- or "ignore_case" or "respect_case"
		},
	},
}
```

**Comment by l-kershaw** [comment]
I can't reproduce this issue for `nvim-tree` using the minimal config that you have provided
(I don't use `dashboard`, so only checked `nvim-tree`)

Does this issue persist on your system with no other plugins installed (so just `telescope`, `nvim-tree` and dependencies), while using the default `nvim-tree` config?

**Comment by omegahh** [comment]
Sorry, finally, I found it's my fault due to an autocmd setting causes this abnormal result. I will close this issue. Thank you for replying and helping!
