### ISSUE TITLE
Async Opening Misses Keypresses

### ISSUE THREAD

**Issue by kevincox** [nvim-telescope/telescope.nvim#2274]
### Description

When opening telescope keypresses can be missed.

This is most notable for slower pickers (such as LSP stuff, especially if you just opened a file/workspace) but can be easily reproduced for all pickers.

### Neovim version

```markdown
% nvim --version
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

NixOS

### Telescope version / branch / rev

cabf991b1d3996fa6f3232327fc649bbdf676496

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. Run `:Telescope lsp_workspace_symbols`
2. Immediately press another letter such as `i`.

### Expected behavior

The search box has an `i` in it.

### Actual behavior

The search box has `A` in it? Or is empty. Or sometimes is in normal mode instead of insert mode.

### Minimal config

```Lua
-- No config required.
```

**Comment by kevincox** [comment]
This can be hard to reproduce if for example you don't have a big LSP project. So some ways to make it easier to reproduce:

```vim
nmap <Space> :Telescope find_files<CR>
```

Then type `<Space>o` quickly.

Or a method that seems to reproduce every time:

```vim
nmap <Space> :Telescope find_files<CR>
nmap <Space><Space> :echo hi<CR>
```

Then type `<Space>o` The second binding ensures that vim doesn't fire the first binding until after it knows that the second doesn't match.

**Comment by kevincox** [comment]
I can confirm that this is fixed for `find_files` but it isn't fixed for `lsp_workspace_symbols`. This appears to be because the [implementation of `lsp_workspace_symbols`](https://github.com/nvim-telescope/telescope.nvim/blob/20a37e43bb43c74c6091f9fea6551af0964ad45a/lua/telescope/builtin/__lsp.lua#L320-L361) doesn't even open the picker until the LSP query returns. So there is nothing to capture keystrokes until the LSP responds. I can edit the active file trying to type in a filter.

I guess I'll open a separate bug for that.

**Comment by dkuettel** [comment]
> I can confirm that this is fixed for `find_files` but it isn't fixed for `lsp_workspace_symbols`. This appears to be because the [implementation of `lsp_workspace_symbols`](https://github.com/nvim-telescope/telescope.nvim/blob/20a37e43bb43c74c6091f9fea6551af0964ad45a/lua/telescope/builtin/__lsp.lua#L320-L361) doesn't even open the picker until the LSP query returns. So there is nothing to capture keystrokes until the LSP responds. I can edit the active file trying to type in a filter.
> 
> I guess I'll open a separate bug for that.

hi, did you ever open a bug for that? I couldnt find anything relevant. It is still an issue and feels very unresponsive with heavy lsps.

In principle it should be easy to make it better, I tried to open the picker at the very beginning (with an empty list) and then later do `picker:refresh(finder)` with the actually filled finder as the lsp replies. but whenever i do it this way the `vim.lsp.buf_request` never seems to call the callback anymore. I dont understand why that could be.

**Comment by kevincox** [comment]
No, I was waiting to see if maintainers would reopen this instead and forgot. Feel free to open one.
