### ISSUE TITLE
how to set a environment variable for bat

### ISSUE THREAD

**Issue by smartding** [nvim-telescope/telescope.nvim#228]
telescope and fzf.vim have the same problem when using bat for previewing: the color in preview looks more saturated than running bat directly in command line.  See [this issue](https://github.com/junegunn/fzf.vim/issues/1065) in fzf.vim repo for  screenshots from many users.

The short term solution (as discussed [here](https://github.com/sharkdp/bat/issues/634#issuecomment-524525661) ) is to set the environment variable `COLORTERM=truecolor` each time we run bat. How can we do this in telescope?

**Comment by smartding** [comment]
I tried setting the `COLORTERM` environment variable as follows in previewers.lua, but no luck.
```lua
    local term_opts = {
      cwd = opts.cwd or vim.fn.getcwd(),
      env = {
        COLORTERM = 'truecolor'
      }
    }

    with_preview_window(status, bufnr, function()
      set_term_id(
        self,
        vim.fn.termopen(opts.get_command(entry, status), term_opts)
      )
    end)
```

**Comment by tjdevries** [comment]
Hmmm, `env` didn't work? That's what my suggested solution would have been.

Make sure you completely reload the plugin in between to ensure that env is getting passed.

**Comment by smartding** [comment]
I restarted neovim several times, so telescope is definitely reloaded.
I'm using the gruvbox theme in neovim and bat, with alacrity terminal (which can handle truecolor)
After setting `COLORTERM` with `env`, here's what it's like in neovim:

![pic-selected-201114-0729-54](https://user-images.githubusercontent.com/16423944/99130552-a22a0e80-264b-11eb-87ed-4f3bed5cb4c2.png)

And here is what it's like in telescope's bat preview, the color is obviously wrong:

![pic-selected-201114-0729-31](https://user-images.githubusercontent.com/16423944/99130623-cf76bc80-264b-11eb-9eb8-9aa4cbcaebbc.png)

And if I run bat in terminal, the color is correct.

**Comment by tami5** [comment]
I can confirm having the same issue with bat, perhaps it is something todo with bat, please check https://github.com/sharkdp/bat/issues/979

**Comment by smartding** [comment]
> I can confirm having the same issue with bat, perhaps it is something todo with bat, please check [sharkdp/bat#979](https://github.com/sharkdp/bat/issues/979)

bat needs external help to decide whether to use truecolor or not.
The current solution is to set the `COLORTERM` env variable, which works for previews in fzf.vim, but for some reason doesn't work with telescope. The bat community is also talking about adding a flag such as `--color-mode=24-bit` to force bat to use true color.

**Comment by ThomasFeher** [comment]
Why is Neovim removing `COLORTERM` from the environment in the first place? I'm
using a patched version that does not remove `COLORTERM`, as suggested by me
[here](https://github.com/neovim/neovim/issues/10836#issuecomment-663539218).
That fixes the issue for fzf and for telescope.nvim and it doesn't seem to break
anything in my case (using Alacritty and Tmux on Linux).

Should I open a PR for that patch?

**Comment by tami5** [comment]
Ohhh thats why, sure @ThomasFeher

**Comment by Conni2461** [comment]
I don't know what the neovim core guys want here so i don't know if you should open a PR.
The underlining issue is that we can set an env with termopen. This is a neovim bug with issue neovim/neovim#11751 and PR neovim/neovim#12937
But i have an idea how to fix this issue here. I would provide you with a config value like `set_env({ 'COLORTERM=truecolor' })`.
But i have a meeting now so i can implement it in like 2 hours or so :)
I will ping you in the PR.

**Comment by tami5** [comment]
@Conni2461 coming to the rescue :laughing:  appreciate you bro

**Comment by Conni2461** [comment]
Please checkout #260 and report back if it is working for you. Thanks :)

**Comment by smartding** [comment]
> Please checkout #260 and report back if it is working for you. Thanks :)

I tested bat preview with builtin `git_files` and `buffer`, it works!
Nice work :)

**Comment by Conni2461** [comment]
@tami5 can we keep issues around until the pr is merged? Maybe someone will have the same issue in the future and only does an open issue search, this way he can't find that this issue is already been worked on and has a working solution :)

**Comment by tami5** [comment]
@Conni2461 ohhh sorry I thought its merged. I can create FAQ entry

**Comment by smartding** [comment]
> @Conni2461 ohhh sorry I thought its merged. I can create FAQ entry

I was waiting for #260 to be merged, suddenly the issue gets closed.... :)

**Comment by tami5** [comment]
@smartding ohhh sorry for shocking you :rofl: . if you want to test it now and assure us it is working okay you can do `git fetch origin pull/260/head:previewer_fixes ` then ` git switch previewer_fixes`

**Comment by smartding** [comment]
> @smartding ohhh sorry for shocking you  . if you want to test it now and assure us it is working okay you can do `git fetch origin pull/260/head:previewer_fixes ` then ` git switch previewer_fixes`

already tested the PR 21 hours ago and it worked, as I mentioned above. 
I was just waiting to test the merged version in case there's any change.

**Comment by tami5** [comment]
Oh so thats why I closed it. :D I was like hmm this issue if fixed for me and for smartding, let me close it, silly me :P

**Comment by smartding** [comment]
neovim is no longer resetting COLORTERM, thanks to the change made by @ThomasFeher.
I did some testing, there's no need to `set_env = { ['COLORTERM'] = 'truecolor' }` in telescope's setup now.
