### ISSUE TITLE
Telescope Git Status not escape file name properly

### ISSUE THREAD

**Issue by RoRep1ay** [nvim-telescope/telescope.nvim#2292]
### Description

Currently, if a file contains a space in it, it will break the file. Also, if a file contains some special character, will break the file as well.

For example, a file name `hello world.txt` -> will output `world.txt"

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/37890287/210060731-0b6edb81-365d-4f7e-89df-971d95f7f4cd.png">

I've debugged the code a bit, the file output is messed up at this [line](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/make_entry.lua#L1345)

Printing the value, it seems like when a file contains space(might be other cases as well), the git file is return with "" surrounding it which breaks the regex matching. 

### Neovim version

```markdown
:!nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS 13.1

### Telescope version / branch / rev

telescope 0.1.0

### checkhealth telescope

```markdown
:!nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```

### Steps to reproduce

1. Create a new file name `hello world.txt`
2. Run `:Telescope git_status`

### Expected behavior

It should outputs `hello world.txt` file

### Actual behavior

Outputs world.txt\"

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by l-kershaw** [comment]
I think this is an edge case that isn't handled by the pattern [here](https://github.com/nvim-telescope/telescope.nvim/blob/a606bd10c79ec5989c76c49cc6f736e88b63f0da/lua/telescope/make_entry.lua#L1345).

I'll have a think about if the pattern can be improved to handle this, but lua patterns aren't my strong suit.

**Comment by smjonas** [comment]
@RoRep1ay could you please test #2296?

**Comment by RoRep1ay** [comment]
Hello @smjonas , I've tested the filename with spaces and it's looking good to me 👍 . However, some other special characters are still not escaped properly, although i'm not sure whether it should be fixed in your PR.

**Comment by smjonas** [comment]
Thanks for testing! Can you tell me which characters those were and what you expected?

**Comment by smjonas** [comment]
Updated, the files should be listed and opening should work as expected now (the previewer does not handle the filenames correctly but that's a different issue)
