### ISSUE TITLE
Deprecated extension still listed

### ISSUE THREAD

**Issue by lsig** [nvim-telescope/telescope.nvim#2293]
https://github.com/nvim-telescope/telescope.nvim/labels/documentation
The extension brandoncc/telescope-harpoon.nvim is still listed in your wiki under extension even though it has been deprecated. Just wanted to let you know😄.
P.S. 
This is my first issue 🥳 .

**Comment by l-kershaw** [comment]
Hi @lsig, congrats on the first issue 🎉
Luckily, this is an easy issue to fix. The wiki for `telescope` can be edited by anyone, so please feel free to remove this from the list.
You can then close this issue when you're done

**Comment by lsig** [comment]
The wiki has been edited and the deprecated extension removed.
