### ISSUE TITLE
Question: how to cycle (wrap) prompt history?

### ISSUE THREAD

**Issue by adrian5** [nvim-telescope/telescope.nvim#2301]
I noticed that cycling the prompt history doesn't wrap around — picking the wrong (presumably `next`) direction prevents any history from showing up. I'm very used to the wrapping behavior from terminals and telescope behaves that way in the Results pane. Is there a way to achieve that currently?

```lua
telescope.setup({
  defaults = {
    mappings = {
      i = {
        ["<C-n>"] = actions.cycle_history_next,
        ["<C-p>"] = actions.cycle_history_prev,
      }
  }
}
```

**Comment by Conni2461** [comment]
no but it should be pretty easy to implement that, do you want to give it a try?

**Comment by adrian5** [comment]
I'm not fluid enough in nvim and Lua to dive into that in reasonable time. I'll leave this open as a feature request then.

**Comment by reidswan** [comment]
@adrian5 @Conni2461 mind if I take a stab at this one?

**Comment by adrian5** [comment]
@reidswan I'd love that, thank you.
