### ISSUE TITLE
Question: Grep matching newlines?

### ISSUE THREAD

**Issue by adrian5** [nvim-telescope/telescope.nvim#2302]
I was trying to live-grep something like this:

```
first
second
```

I.e. `/` + `first\nsecond` in vim.

Is this achievable with telescope pickers? One thing I tried was passing `--multiline` to `rg` but to no avail.

**Comment by mklishevych** [comment]
@adrian5 how exactly did you pass `--multiline` argument? Below works for me.

```lua
require("telescope").setup({
  defaults = {
    "rg",
    "--color=never",
    "--no-heading",
    "--with-filename",
    "--line-number",
    "--column",
    "--smart-case",
    "--hidden",
    "--trim",
    "--multiline",
  },
})
```

![image](https://user-images.githubusercontent.com/2452586/213874727-06a532a9-b3d0-475b-9575-dabe641a9911.png)
![image](https://user-images.githubusercontent.com/2452586/213874746-b300acd6-867f-40ff-80c3-d560055e2380.png)

**Comment by adrian5** [comment]
@mklishevych Thank you, that works (`defaults = { vimgrep_arguments = { "rg", … }}`)! I recall trying to pass `--multiline` to `:Telescope live_grep()` instead of the telescope `setup()` function. Mistake on my part, I'll close the issue.
