### ISSUE TITLE
Error code snippet in dev doc

### ISSUE THREAD

**Issue by woshichuanqilz** [nvim-telescope/telescope.nvim#2318]
### Description

Under this topic
https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md#entry-maker

The code is error I make the comment in the code. 
```lua
    finder = finders.new_table {
      results = {
        { "red", "#ff0000" },
        { "green", "#00ff00" },
        { "blue", "#0000ff" },
      },
      entry_maker = function(entry)
        return {
          value = entry,
          display = entry[1],  -- error here, should be 2
          ordinal = entry[1],  -- error here, should be 2
        }
      end
    },
```

### Neovim version

```markdown
NVIM v0.8.0-1210-gd367ed9b2
```

### Operating system and version

Ubuntu 22

### Telescope version / branch / rev

0.1.0

### checkhealth telescope

```markdown
leave it empty
```

### Steps to reproduce

leave it empty

### Actual behavior

leave it empty

### Minimal config

```Lua
leave it empty
```

**Comment by l-kershaw** [comment]
I don't think that this is an error. It just depends on what you want to create your picker to do.

If you want to search and pick based on hex RGB values, then your suggestion works. If you want to search and pick based on names, then the suggested method works.

Closing this issue now
