### ISSUE TITLE
git_files fails to show unicode file names

### ISSUE THREAD

**Issue by smartding** [nvim-telescope/telescope.nvim#232]
The builtin `git_files` function shows each Chinese character in file names as `\ddd`, where `d` is a digit. 

And if I open a file like this by hitting `<CR>` in `git_files`, I get an error message： `E5108: Error executing lua ...telescope.nvim/lua/telescope/actions.lua:134: Vim(edit):E32: No file name`

But the builtin `find_files` function, with the help of fd command, handles Chinese characters all right.

**Comment by tjdevries** [comment]
Hmmm.... what does `git ls-files` show in y6our terminal compared to `find` or `fd`?

**Comment by smartding** [comment]
> Hmmm.... what does `git ls-files` show in y6our terminal compared to `find` or `fd`?

`git ls-files` shows `\ddd` too......
I turned out that I need to set ` git config --global core.quotepath off` to make git show the Unicode characters according to [this stackoverflow discusstion](https://stackoverflow.com/questions/22827239/how-to-make-git-properly-display-utf-8-encoded-pathnames-in-the-console-window). Not sure if this setting has any side effects.
