### ISSUE TITLE
Files opened from telescope don't follow statusline "f" setting

### ISSUE THREAD

**Issue by digia** [nvim-telescope/telescope.nvim#234]
When using `f` within the `statusline` configuration it shows the _"path to the file in the buffer, as typed or relative to current directory"_ when a file is opened without telescope, however when using telescope to open the file it'll show the full path, similar to the `F` -- _full path to the file in the buffer_ -- options for the `statusline`.

__Examples__
* Unexpected: `~/Code/digia/project-name/src/filename.ts`
* Expected: `src/filename.ts`

__Status Line Configuration__
```vim
set statusline=""
set statusline+=%<%f:%l:%v " filename:col:line/total lines
set statusline+=\ "
set statusline+=%h%m%r " help/modified/readonly
set statusline+=\ "
set statusline+=[%{&ft}] " filetype
set statusline+=%= " alignment group
set statusline+=\ "
```

__Mappings Used__
```vim
map <silent> <expr> <C-p> fugitive#head() != '' ? ':lua require("telescope.builtin").find_files{ find_command = { "rg", "--smart-case", "--files", "--hidden", "--follow", "-g", "!.git/*" } }<CR><CR>' : ':lua require("telescope.builtin").find_files()<CR>'
nnoremap <silent> <leader>p :lua require('telescope.builtin').git_files()<CR>
```

**Comment by elianiva** [comment]
I believe this is no longer an issue? (iirc it was fixed on one of TJ's stream and I don't get this issue either)
ping @digia just to make sure

**Comment by digia** [comment]
Ya, TJ investigated this live on stream. Should be fixed. @elianiva
