### ISSUE TITLE
Error when finding files in large directories

### ISSUE THREAD

**Issue by anihm136** [nvim-telescope/telescope.nvim#236]
When `builtin.find_files()` is run on a large folder (in this case, my home directory), and I leave the search either by closing telescope or by hitting enter to open a file, I get the following error -
```
Error executing luv callback:
...ig/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:452: attempt
to index field 'manager' (a nil value)
```
This is followed by a continuous stream of the following error (making nvim unusable until I restart it)
```
Error executing luv callback:
cannot resume dead coroutine
```

Let me know what other information I can provide

**Comment by elianiva** [comment]
I also got the dead coroutine thingy, but it came up randomly and I couldn't find a way to reproduce it. If I close telescope, wait for 1 or 2 seconds and open it again, the error is gone. It's quite a rare occurance though, it doesn't bother me that much but this might be a useful information.

**Comment by anihm136** [comment]
Hmm. I can reproduce regularly whenever I close telescope while files are still being found. Also the errors keep popping up for me, so I need to restart nvim to get rid of them

**Comment by tjdevries** [comment]
OK, I think I have fixed this. Please try it and let me know if it is good.

**Comment by clason** [comment]
Yep, looks good, can't reproduce anymore! 💯
