### ISSUE TITLE
Add an option to builtin.buffers to only show filenames not full paths

### ISSUE THREAD

**Issue by rosejn** [nvim-telescope/telescope.nvim#2361]
**Is your feature request related to a problem? Please describe.**
reading the full path makes it harder to find the buffer I'm looking for

**Describe the solution you'd like**
A boolean option in builtin.buffers which specifies to only list the filename

**Describe alternatives you've considered**
Some kind of buffer filter or display filter function, but I can't find this mechanism.

**Additional context**
If you can point me at the right place to do this I'd be happy to give it a go and issue a PR.  I just wanted to bring it up to ask for advice before jumping into code.

**Comment by abelfubu** [comment]
Hello @rosejn I was also trying to only show the filenames and found this solution

```lua 
{
    defaults = {
      path_display = function(_, path)
        return path:match("^.+/(.+)$")
      end,
    }
}
```

**Comment by lvhungdev** [comment]
Correct me if I'm wrong but I believe we already have this functionality built-in.
```lua
{
    defaults = {
      path_display = { 'tail' },
    }
}
```

**Comment by jamestrew** [comment]
> Correct me if I'm wrong but I believe we already have this functionality built-in.
> 
> ```lua
> {
>     defaults = {
>       path_display = { 'tail' },
>     }
> }
> ```

Or just for the `buffers` picker
```lua
require('telescope').setup({
    defaults = { ... }, 
    pickers = {
        buffers = {
            path_display = { 'tail' }
        },
    }
})
