### ISSUE TITLE
Can't set keymap for builtin using themes

### ISSUE THREAD

**Issue by vicrdguez** [nvim-telescope/telescope.nvim#2366]
### Description

Hi, 

I'm trying to set up some keymaps that open telescope using the ivy theme. However I get errors trying to configure it.

The code is the following:

```lua
local builtin = require('telescope.builtin')
local themes = require('telescope.themes')


local themeOpts = themes.get_ivy()

vim.keymap.set('n', '<leader>rf', builtin.find_files(themeOpts))
```

### Neovim version

```markdown
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS 12.6.3 21G419 x86_64

### Telescope version / branch / rev

0.1.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.6.0

## ===== Installed extensions =====
```

### Steps to reproduce

1. add the code for the keymap as shown. 
2. `:w`
3. `:so`

```
Error detected while processing :source (no file):
E5108: Error executing lua vim/keymap.lua:0: rhs: expected string|function, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/keymap.lua: in function 'set'
        [string ":source (no file)"]:7: in main chunk
```

Line 7 is specifically the keymap line.

### Expected behavior

I'm able to set the keymap specifying the theme for the builtin 

### Actual behavior

I'm getting the error mentioned above when setting the keymap

### Minimal config

```Lua
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'

  use {
	  'nvim-telescope/telescope.nvim', tag = '0.1.1',
	  -- or                            , branch = '0.1.x',
	  requires = { {'nvim-lua/plenary.nvim'} }
  }
```

**Comment by vicrdguez** [comment]
Doing some further testing I manage to make it work like this:

```lua
local themeOpts = themes.get_ivy()

vim.keymap.set("n", "<leader>rf", function() builtin.find_files(themeOpts) end)
```

but I not always need to use function.  you might be able to tell if this can be an bug or just my mistake, so if you confirm is nothing I will close the issue

**Comment by vicrdguez** [comment]
Closing since it is not an issue with the configuration mentioned above

**Comment by allworldg** [comment]
@vicrdguez  Today I got same problem. It is not a bug. `rhs` in `vim.keymap.set('n',`` '<leader>rf', rhs)` need to be a str or a function to callback. For example, it can be a str like `vim.keymap.set('n', '<leader>rf', '<cmd>w<CR>')` and a function like `vim.keymap.set('n', '<leader>rf', builtin.find_files)`. If you use `builtin.find_files()`, the function is called and return sth(nil).
