### ISSUE TITLE
jump_type of split will open a [No Name] ("new") buffer in addition to splitting window with definition

### ISSUE THREAD

**Issue by yudi-tan** [nvim-telescope/telescope.nvim#2368]
### Description

I was trying to setup my telescope + lsp config and i'd configured it such that my lsp_definitions call has `jump_type` set to `split`. However, when doing so, i realized that while it does open the file with the definition of that function in a new split window buffer, it also opens an additional [No Name] (aka new) buffer. In other words, 2 buffers are opened, and the "new" buffer is very unnecessary. I'm not sure if this is a configuration issue on my end but i dug into the implementation here https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/__lsp.lua#L190 and it does seem like it calls the "new" and "vnew" commands if `jump_type` is set to `split` or `vsplit`. 

I'm quite new to vim so i'm not 100% sure if i understood that logic correctly. Is it intended that every time we go-to-definition in a new split window it should open an additional [No Name] buffer? I could `set nohidden` and that fixes this issue but i don't really wanna set `nohidden`. 

Here's my config:

```
local function lsp_keymaps(bufnr)
  local opts = { noremap = true, silent = true }

  -- Declaration and definition
  vim.api.nvim_buf_set_keymap(bufnr, "n", "gd", "<cmd>lua require('telescope.builtin').lsp_definitions({jump_type='vsplit'})<CR>", opts)
  vim.api.nvim_buf_set_keymap(bufnr, "n", "hd", "<cmd>lua require('telescope.builtin').lsp_definitions({jump_type='split'})<CR>", opts)
end

M.on_attach = function(client, bufnr)
  lsp_keymaps(bufnr)
end
```
where i am passing in this to `null-ls`.

My alternative right now is to `vim.api.nvim_buf_set_keymap(bufnr, "n", "gd", ":vsplit | lua vim.lsp.buf.definition()<CR>", opts)` instead which works but was just wondering why using Telescope's `lsp_definition` with `jump_type='vsplit') will result in a new [No Name] buffer?

### Neovim version

```markdown
nvim --version
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
```

### Operating system and version

macOS 12.6

### Telescope version / branch / rev

master

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.6.0

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - OK: lib working as expected
  - OK: file_sorter correctly configured
  - OK: generic_sorter correctly configured

## Telescope Extension: `ui-select`
  - INFO: No healthcheck provided
```

### Steps to reproduce

Config is here -- https://github.com/yudi-tan/nvim/blob/a06f7e0107a31d8308cc9e955c69c163e0d1a99c/lua/plugins/lsp/handlers.lua#L115

Opening a file and doing `gd` will open that function's definition in a new split window but also an additional [No Name] buffer is opened.

### Expected behavior

It should only open the function's definition is a split window, without opening the additional [No Name] buffer.

### Actual behavior

An additional [No Name] buffer is opened.

### Minimal config

```Lua
https://github.com/yudi-tan/nvim/blob/a06f7e0107a31d8308cc9e955c69c163e0d1a99c/lua/plugins/lsp/handlers.lua#L115
```

**Comment by mebble** [comment]
I have this same problem. This seems like the same problem as https://github.com/nvim-telescope/telescope.nvim/issues/2469

**Comment by jamestrew** [comment]
Can someone provide a minimal config that I can use to reproduce this?
I tried on several occasions but I've never been able to get this to happen.

**Comment by LinoWhy** [comment]
> Can someone provide a minimal config that I can use to reproduce this? I tried on several occasions but I've never been able to get this to happen.

This config can reproduce this issue:
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

local plugins = {
	{
		"nvim-telescope/telescope.nvim",
		branch = "0.1.x",
		dependencies = { "nvim-lua/plenary.nvim" },
	},
	{
		"akinsho/bufferline.nvim",
		dependencies = { "nvim-tree/nvim-web-devicons" },
		opts = {
			options = {
				mode = "buffers", -- set to "tabs" to only show tabpages instead
				numbers = "none", -- can be "none" | "ordinal" | "buffer_id" | "both" | function
			},
		},
	},
	{
		"neovim/nvim-lspconfig",
		dependencies = {
			{ "folke/neodev.nvim", opts = {} }, -- setup neodev before lspconfig
			"williamboman/mason.nvim",
			"williamboman/mason-lspconfig.nvim",
		},
		config = function(_, opts)
			local lspconfig = require("lspconfig")
			lspconfig.lua_ls.setup({})
		end,
	},
}

require("lazy").setup(plugins)
```

with the result show below:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/43626684/dfe2ac65-d58f-4cb3-9590-c7dea41f0805)

my neovim version is:
```
NVIM v0.9.5-dev-10+g26c2c3c86
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794
```

**Comment by jamestrew** [comment]
Thanks I see the issue now. This can be replicated with just telescope (and lsp) but bufferline makes it obvious. I was getting caught up in the technicalities and not seeing the issue before.

It seems to come down to the fact that we call `vim.cmd "new"` inside the callback handler for `vim.lsp.buf_request`. I can replicate this without telescope as well.

```lua
function Demo()
  local params = vim.lsp.util.make_position_params(0)
  vim.lsp.buf_request(0, "textDocument/definition", params, function(err, result, ctx, _)
    vim.cmd "new"
  end)
end
```
Calling this also opens up an additional buffer.
Not sure what interactions are causing this. Using something like `vim.schedule` or `vim.defer_fn` doesn't help.

**Comment by Frederick888** [comment]
Experiencing this issue too. Same thing happens with `jump_type = 'tab'` btw.

```diff
diff --git a/lua/telescope/builtin/__lsp.lua b/lua/telescope/builtin/__lsp.lua
index 01a1991..192998e 100644
--- a/lua/telescope/builtin/__lsp.lua
+++ b/lua/telescope/builtin/__lsp.lua
@@ -194,12 +194,15 @@ local function list_or_jump(action, title, opts)
       local uri = params.textDocument.uri
       if uri ~= flattened_results[1].uri and uri ~= flattened_results[1].targetUri then
         if opts.jump_type == "tab" then
           vim.cmd "tabedit"
+          vim.opt_local.bufhidden = 'wipe'
         elseif opts.jump_type == "split" then
           vim.cmd "new"
+          vim.opt_local.bufhidden = 'wipe'
         elseif opts.jump_type == "vsplit" then
           vim.cmd "vnew"
+          vim.opt_local.bufhidden = 'wipe'
         elseif opts.jump_type == "tab drop" then
           local file_uri = flattened_results[1].uri
           if file_uri == nil then
             file_uri = flattened_results[1].targetUri
```
...seems to be a workaround. Not sure whether this is a proper solution tho.

**Comment by jamestrew** [comment]
Thanks @Frederick888 for the hint! It took me a while to get around to it but I think I was able to fix this issue with the above linked PR.

If people can verify it on their end, that'll be appreciated.
