### ISSUE TITLE
Preview not shown when window height is small

### ISSUE THREAD

**Issue by rieje** [nvim-telescope/telescope.nvim#2369]
### Description

When the window height is small, e.g. `winheight` of 36, preview window is gone and results window takes up the remaining space with the following config.

Ideally, I set the results window at the bottom to a fixed height of 10 lines, a prompt above it, and then the preview window in the remaining space, like [Swiper for Emacs](https://www.youtube.com/watch?v=s3qwiAtKjuA). But it seems there are no settings to allow for this so a workaround is to set preview height to something close to that (is this a valid feature request?).

    layout_config = {
      vertical = {
        height = vim.o.lines, -- Maximally available lines
        width = vim.o.columns, -- Maximally available columns
        prompt_position = "top",
        preview_height = .72
      }
    },

-----------------

P.S. Unrelated question (I've tried gitter but there's way fewer people answering than those asking--I think discussions would be more suitable but it isn't available):

Does Telescope require a preview window? E.g. for some pickers like `Telescope current_buffer_fuzzy_find`, it would make more sense to use the actual buffer as the "preview", just like in that video for Swiper. A preview window for this case IMO results in cognitive overhead because it involves unnecessary overlay for the preview window where at best the user can attempt to set settings to make it appear the same as the existing live buffer. For example, I'm not sure if it can show LSP stuff in the preview and I could not get same text coloring (syntax highlighting?) to work in some cases. Essentially I find Swiper to be more space-efficient and intuitive--prompt and results take up only a small buffer at the bottom and the rest of the live buffer is *replaced* (not an overlay) as the previewer where an exit would return back to where you were. An overlay also requires a visual flicker because window is created whereas "previewing" using the live buffer directly in the case of `Telescope current_buffer_fuzzy_find`where all results are restricted to live buffer would not.

### Neovim version

```markdown
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch Linux

### Telescope version / branch / rev

telescope v0.1.1

### checkhealth telescope

```markdown
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.6.0

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - OK: lib working as expected
  - OK: file_sorter correctly configured
  - OK: generic_sorter correctly configured
```

### Steps to reproduce

layout_config = {
  vertical = {
    height = vim.o.lines, -- Maximally available lines
    width = vim.o.columns, -- Maximally available columns
    prompt_position = "top",
    preview_height = .72
  }
},

### Expected behavior

Preview window still shown based on the value of `preview_height`, i.e. 72% in this case.

### Actual behavior

Preview window is gone with results window taking up remaining space along with the one-line prompt.

### Minimal config

```Lua
require('telescope').setup {
  defaults = {
    wrap_results = true,

    sorting_strategy = "ascending",

    layout_strategy = "vertical",
    layout_config = {
      vertical = {
        height = vim.o.lines, -- Maximally available lines
        width = vim.o.columns, -- Maximally available columns
        prompt_position = "top",
        preview_height = .72
      }
    },

  },

}
```

**Comment by l-kershaw** [comment]
For the `vertical` layout strategy, the preview is disabled when the number of lines available is less than `preview_cutoff` (as explained in the docs for this strategy). The default value for this layout is `40`. If you want different behaviour, you can change this value.

You can also defined `preview_height` as a function (as explained in the docs under `resolver.resolve_height()`, which is referenced in the layout strategy docs). By defining an appropriate function, you can achieve your goal of "always having 10 results lines".

I hope this solves your issue, and am closing it now. If this doesn't solve your issue, feel free to reopen 🙂
