### ISSUE TITLE
live_grep results are not removed by a garbage collector

### ISSUE THREAD

**Issue by dembitskyi** [nvim-telescope/telescope.nvim#2370]
### Description

Neovim does not release `live_grep` results memory. 
An activity monitor (e.g. `htop`) shows that nvim keeps 'live_grep' results forever. Sometimes it releases 50%, but it never goes to 5%. This makes the telescope plugin unusable if you need to work with a project that has a codebase like [android](https://android.googlesource.com/platform/manifest
) or bigger. 

 I tried invoking `lua collectgarbage("collect")` multiple times, but it did not help. 

### Neovim version

```markdown
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Pop!_OS 22.04 LTS

### Telescope version / branch / rev

203bf5609137600d73e8ed82703d6b0e320a5f36

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. `cd $HOME/android`
2. `nvim -nu /tmp/minimal.lua`
3. `Telescope live_grep`
  3.1. type "l" and wait 5 minutes
  3.2. close the `live_grep` window
4. Open `Telescope planets`  and close it - this should release cached pickers
5. repeat "3 - 4  steps" 5 times
6. `lua collectgarbage("collect")`
7. check nvim memory usage

### Expected behavior

Nvim uses ~1GB of RAM or less.

### Actual behavior

Nvim will consume 50GB of RAM after just 10 `live_grep` attempts :( 
Recovery: reopen nvim 

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
```

**Comment by SonTrinhEH** [comment]
I currently face the same issue, I'm able to so the live grep to search things in my project

**Comment by jamestrew** [comment]
I've tried to replicate this with the linux source code, but I don't see a significant increase in memory usage over time.
> Nvim uses ~1GB of RAM or less.

This is pretty much my experience.
This is on arch linux, nightly neovim and telescope.

**Comment by jamestrew** [comment]
Try this out: https://github.com/nvim-telescope/telescope.nvim/issues/2482#issuecomment-1528053505
I think this issue is relate to changes in the default vimgrep args.
I've created a PR for this already https://github.com/nvim-telescope/telescope.nvim/pull/2488
