### ISSUE TITLE
Add live_grep from project's git root to Configuration Recipes

### ISSUE THREAD

**Issue by wesbragagt** [nvim-telescope/telescope.nvim#2378]
**Is your feature request related to a problem? Please describe.**

Hey everyone, I would love to perform live_grep always from the project's git location. I have a configuration for which I believe it would be great to have added to [Configuration Recipes](https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes)

**Describe the solution you'd like**

```lua
function live_grep_from_project_git_root()
	local function is_git_repo()
		vim.fn.system("git rev-parse --is-inside-work-tree")

		return vim.v.shell_error == 0
	end

	local function get_git_root()
		local dot_git_path = vim.fn.finddir(".git", ".;")
		return vim.fn.fnamemodify(dot_git_path, ":h")
	end

	local opts = {}

	if is_git_repo() then
		opts = {
			cwd = get_git_root(),
		}
	end

	require("telescope.builtin").live_grep(opts)
end
```

**Describe alternatives you've considered**
n/a

**Additional context**

I've edited the [Configuration Recipes Wiki](https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#live-grep-from-project-git-root-with-fallback) thinking it would create a pull request, requiring approvals and not simply saving it, so I apologize in advance.

**Comment by has2k1** [comment]
You can simplify the by having git find the root directory. e.g.

```lua
function live_grep_from_project_git_root()
	local function get_git_toplevel()
		local path = vim.fn.system("git rev-parse --show-toplevel")
		if vim.v.shell_error then
			return nil
		end
		return path
	end

	local opts = { cwd = get_git_toplevel() }

	require("telescope.builtin").live_grep(opts)
end
```
