### ISSUE TITLE
previewer is not working at all on st terminal

### ISSUE THREAD

**Issue by Vinni-Cedraz** [nvim-telescope/telescope.nvim#2380]
### Description

telescope preview feature doesn't work on st terminal, why?
Here is what I tried:

1) Reading the documentation: https://github.com/nvim-telescope/telescope.nvim

2) Trying to understand it: apparently the *Previewers Description* section is telling me that there are different previewer things that I could choose from".

Of course, apart from the default ones there are only the deprecated ones so maybe I interpreted it incorrectly, but anyway I tried to change the previewers because maybe a different one would work on st, and that didn't work either.
 
 3) read existing issues, then I found issue *Various previewer fixes #260* and I couldn't understand anything that was going on there.

### Neovim version

```markdown
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch Linux rolling release

### Telescope version / branch / rev

 commit = "76ea9a898d3307244dce3573392dcf2cc38f340f" 

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.6.0

## ===== Installed extensions =====
```

### Steps to reproduce

1 - use this version of st: https://github.com/LukeSmithxyz/st
2 - use this personal version of LunarVim/nvim-basic-ide: https://github.com/Vinni-Cedraz/vinnivim
3 - open telescope with either ff (file finder) or <leader>lg (live grep)
4 - realize there are no previews

### Expected behavior

preview
![image](https://user-images.githubusercontent.com/92558763/218529289-1f7f85b0-4d01-4377-9623-ff50ce9c9596.png)

### Actual behavior

no preview:

![image](https://user-images.githubusercontent.com/92558763/218528847-acd8d4a5-b0d5-465b-94ce-a2abc4aff37c.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment]
The preview should be working. It's most likely that the font size is too big relative to your telescope configuration given the absolute size of the terminal window, such that telescope hides the preview.

In other words, try incrementally reducing the font size of your terminal and quite likely the preview pops up eventually.

**Comment by Vinni-Cedraz** [comment]
That makes a lot of sense, I'll do that, thanks!!

Em seg., 13 de fev. de 2023 16:38, Fabian David Schmidt <
***@***.***> escreveu:

**Comment by Vinni-Cedraz** [comment]
It did work, thank you again.

Em seg., 13 de fev. de 2023 às 16:43, None of your business <
***@***.***> escreveu:

**Comment by fdschmidt93** [comment]
Cool! Closing :)

**Comment by DreamMaoMao** [comment]
Can it prevent it from hiding automatically? The font that needs to pop up the preview box is too small
