### ISSUE TITLE
Allow `file_ignore_patterns` on a per picker basis OR allow `no_ignore` to override global `file_ignore_patterns`

### ISSUE THREAD

**Issue by calebdw** [nvim-telescope/telescope.nvim#2383]
**Is your feature request related to a problem? Please describe.**
I have several folders in my projects that I would like to ignore in my pickers *most of the time, but they still need to be tracked by git.* However, there are occasions where I would like to include them in the picker search results.

Currently, the only way to exclude files is in `gitignore` and in the `default.file_ignore_patterns` table. But both of these solutions are not acceptable because I need them tracked by git and there is no way to re-include the files after they've been globally ignored.

**Describe the solution you'd like**
There are two solutions that would probably work:
1. Allow file ignore patterns to be passed to each picker:
    I have the following mappings to view ignored files

    ```lua
    vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
    vim.keymap.set('n', '<leader>fa', function()
        builtin.find_files({
            no_ignore = true,
            prompt_title = 'All Files',
        })
    end, {})
    ```
    so it wouldn't be too difficult to list the ignored paths like so:
    ```lua
    vim.keymap.set('n', '<leader>ff', function()
        builtin.find_files({
            ignore = {
                'file/path',
            },
        })
    end, {})
    ```
2. Let `no_ignore` override the global `file_ignore_patterns`

**Comment by sid0-0** [comment]
@calebdw currently both as possible

1. find_files and others accept `file_ignore_patterns`
```
builtin.find_files({
	file_ignore_patterns = {
		'file/path',
	},
})
```
2. Kinda hacky but a workaround is to override it the ignore options in a separate function
my setup config is this
```
telescope.setup({
	defaults = {
		file_ignore_patterns = {
			"yarn.lock",
		},
	},
})
```
which allows ignoring `yarn.lock` by default allowing me to map it easily without any specifications as such:
```
vim.keymap.set('n', '<leader>sg', require('telescope.builtin').live_grep, { desc = '[S]earch by [G]rep' })
```
I also have a keymap to search all files in which I override `file_ignore_patterns` which doesn't ignore `yarn.lock`
```
vim.keymap.set('n', '<leader>svg', function ()
  require('telescope.builtin').live_grep {
    no_ignore = true,
    file_ignore_patterns = {}, -- overridden global file ignores
    prompt_title = '[S]earch [V]erbose [F]iles',
  }
end)
```
(I know verbose is incorrect here but I'm used to it now)

**Comment by jamestrew** [comment]
^ this is the way thanks.

`file_ignore_patterns` and other file filtering options on `find_files` like `no_ignore` and `hidden` work at different levels.

`no_ignore`, and `hidden` are options to pass flags to ripgrep or fd, which is what `find_files` is using under the hood (in most cases).

`file_ignore_patterns` is an additional filter done with lua on top of the results from rg/fd. My general recommendation is to rely of the options provided by rg/fd for things like this using their flags or respective config/ignore files. It's faster and generally more flexible.
But if you do use it and want to override it at the picker level, you can by just passing it as an option to the pickers individually.
