### ISSUE TITLE
Preview cutoff works only when corresponding layout is set to default layout

### ISSUE THREAD

**Issue by Bekaboo** [nvim-telescope/telescope.nvim#2397]
### Description

The vertical layout will not show preview buffer despite the value of `preview_cutoff` is set to `0` for `vertial` layout in `layout_config` if the layout_strategy is not explicitly set to `vertical`.

### Minimal telescope config:

```lua
local telescope = require('telescope')

telescope.setup({
  defaults = {
    layout_config = {
      horizontal = {
        prompt_position = 'top',
        width = 0.8,
        height = 0.8,
        preview_width = 0.5,
      },
      vertical = {
        prompt_position = 'top',
        width = 0.8,
        height = 0.8,
        mirror = true,
        preview_cutoff = 0,
      },
    },
  },
})
```

### Screenshots

Vertical layout when `layout_strategy` is not set explicitly:

![image](https://user-images.githubusercontent.com/76579810/220264857-9d14ed49-1551-47a3-84bc-388a3ebf88c8.png)

Vertical layout when `layout_stragtegy` is set to `vertical`:

![image](https://user-images.githubusercontent.com/76579810/220264953-f6b9f0fe-2849-410a-bee0-58b37a4b772e.png)

### Neovim version

```markdown
NVIM v0.9.0-dev-1014+g286777c333
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 6.1.12-arch1-1

### Telescope version / branch / rev

master

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.6.0

===== Installed extensions ===== ~
```

### Steps to reproduce

1. `nvim -u minimal.lua`
2. Make sure the screen width is less than 120 so that the layout fallbacks to vertical
3. `:Telescope find_files`
4. No preview buffer shown

### Expected behavior

Telescope should show preview buffer.

### Actual behavior

Telescope does not show preview buffer.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
        config = function()

          local telescope = require('telescope')

          telescope.setup({
            defaults = {
              layout_strategy = 'vertical',
              layout_config = {
                horizontal = {
                  prompt_position = 'top',
                  width = 0.8,
                  height = 0.8,
                  preview_width = 0.5,
                },
                vertical = {
                  prompt_position = 'top',
                  width = 0.8,
                  height = 0.8,
                  mirror = true,
                  preview_cutoff = 0,
                },
              },
            },
          })

        end
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by MayyarZidane** [comment]
This fix my problem, I have my screen laptop with 1366x768 size but there is no preview. When i config it as you did, it is working now, but what was the problem and why it was not working?

**Comment by Bekaboo** [comment]
> This fix my problem, I have my screen laptop with 1366x768 size but there is no preview. When i config it as you did, it is working now, but what was the problem and why it was not working?

Did you set `layout_strategy` to `vertical`?

**Comment by l-kershaw** [comment]
I don't think that this is a bug. 
The default `layout_strategy` is `horizontal`, which by default disables the preview if there are less than 120 columns to the nvim window. If you want to default to `vertical` then you need to explicitly set that up. You could also use the `flex` layout which tries to pick the better option between `horizontal` and `vertical`.

**Comment by Bekaboo** [comment]
> I don't think that this is a bug. The default `layout_strategy` is `horizontal`, which by default disables the preview if there are less than 120 columns to the nvim window. If you want to default to `vertical` then you need to explicitly set that up. You could also use the `flex` layout which tries to pick the better option between `horizontal` and `vertical`.

Thanks for your reply. How can I achieve this effect: When the number of columns is larger thsn 120, use horizontal layout with preview: when the number of columns is less thsn 120, use vertical layout with preview?

**Comment by Bekaboo** [comment]
Thank you.
