### ISSUE TITLE
How to shorten long paths in frecency? 

### ISSUE THREAD

**Issue by mertnuhoglu** [nvim-telescope/telescope.nvim#2408]
I want to shorten the file paths when using `:Telescope frecency`. 

I have already configured `path_display = {"smart"}` as described in [Truncate or fold file paths if out of bounds · Issue #895 · nvim-telescope/telescope.nvim](https://github.com/nvim-telescope/telescope.nvim/issues/895). This shortens the file paths in `:Telescope find_files` popups but not in `frecency`.

Long file paths occur mostly in Google Drive files. 

![scs20230301_002557](https://user-images.githubusercontent.com/31400/221983952-af671691-b255-409a-835f-6db0b3723560.jpg)

A solution alternative that came to my mind is as follows: Replace the root folder of Google Drive with an alias. For example:

`~/Library/CloudStorage/GoogleDrive-mert.nuhoglu@gmail.com/My Drive` -> `~/gdrive`

**Comment by jamestrew** [comment]
This is most likely an issue with `frecency`. You should open a issue there instead if you haven't already.

**Comment by tjdevries** [comment]
Yeah, that sounds like `frecency` should support it . I'm going to close the issue here but if it turns out something we need to fix in core, i'd be happy to hear more about it.

**Comment by searleser97** [comment]
I think developer should worry about supporting the "display_path" setting, it should just work out of the box

**Comment by delphinus** [comment]
Now frecency supports this: https://github.com/nvim-telescope/telescope.nvim/issues/2712#issuecomment-1730544357
