### ISSUE TITLE
lua/telescope/mappings.lua does not contain all mappings.

### ISSUE THREAD

**Issue by EnacheB** [nvim-telescope/telescope.nvim#2411]
### Description

In the README, we have "To see the full list of mappings, check out lua/telescope/mappings.lua and the default_mappings table", but it does not contain C-space, which triggers fuzzy refining. Links for the lazy:
https://github.com/nvim-telescope/telescope.nvim/issues/1818#issuecomment-1173168485
https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/mappings.lua
https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/__files.lua#L157

Maybe it's because this only applies to certain pickers?

### Neovim version

```markdown
N/A , I'm just looking at the github repo as of March 1st, 2023
```

### Operating system and version

N/A

### Telescope version / branch / rev

master

### checkhealth telescope

```markdown
N/A
```

### Steps to reproduce

1. Try to find all mappings
2. Read the readme
3. Follow direction, fail to find all mappings

### Expected behavior

I would expect the README to point me to a place where I can actually find all the buttons I can press in all situations.

### Actual behavior

N/A

### Minimal config

```Lua
N/A
```

**Comment by jamestrew** [comment]
Yes, it's `<C-space>` to fuzzy refine is only available to the `live_grep` & `lsp_dynamic_workspace_symbols` pickers so it wouldn't exist in the `mappings.lua` file.

You can find all the mappings for each picker using telescope's builtin which-key functionality using `<C-/>`/`<C-_>` in insert mode and `?` in normal mode.

**Comment by EnacheB** [comment]
Hmm, yup that's exactly what I needed, and I see it's mentioned twice in the README. I don't know how I missed it, although I will say that some of the short names you get from C-/ aren't very informative. 

Either way, Thanks!
