### ISSUE TITLE
Live grep can't show non utf-8 content correctly

### ISSUE THREAD

**Issue by brneor** [nvim-telescope/telescope.nvim#2415]
### Description

When the content showed by Telescope has accented characters like in the word `acentuação` and the content is in `latin1` the characters is not displayed correctly.

### Neovim version

```markdown
NVIM v0.9.0-dev-869+g964ae205a-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Fedora 37

### Telescope version / branch / rev

v0.1.1

### checkhealth telescope

```markdown
1 ──────────────────────────────────────────────────────────────────────────────
  2 telescope: require("telescope.health").check()
  3
  4 Checking for required plugins
  5 - OK plenary installed.
  6 - OK nvim-treesitter installed.
  7
  8 Checking external dependencies
  9 - OK rg: found ripgrep 13.0.0
 10 - OK fd: found fd 8.2.1
 11
 12 ===== Installed extensions =====
 13
```

### Steps to reproduce

1. Open a file with some accented characters with latin1 encoding.
2. Run `:Telescope live_grep`
3. Search for a term in this file
4. Preview can't show accented characters correctly

### Expected behavior

Preview should be displayed correctly as it is with uft-8 files:

![image](https://user-images.githubusercontent.com/5962898/223099480-9f08a2a3-1517-4930-9b73-87f24af8ac25.png)

### Actual behavior

Preview is displayed incorrecly.

![image](https://user-images.githubusercontent.com/5962898/223098554-e074fbc0-c8c2-4c46-adae-57eee28f604f.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
I can replicate this as well.

I can add a new option to pickers using `buffer_previewer`, something like `file_encoding`. Then do a `vim.iconv` during the buffer contents processing to convert encodings.
Users can then do `:Telescope live_grep file_encoding=latin1`.

Should probably tweak the `entry_maker` for `live_grep` as well to handle the encoding incompatibility in the results.
I'll look into this as well.
