### ISSUE TITLE
Cannot call current_buffer_fuzzy_find() after enabling highlight from Treesitter

### ISSUE THREAD

**Issue by doganalper** [nvim-telescope/telescope.nvim#2418]
### Description

I have enable highlighting from Treesitter because it does not work properly with `.vue` files if not enabled. But noticed that I cannot call `current_buffer_fuzzy_find()` after enabling highlight.

### Neovim version

```markdown
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOs 13

### Telescope version / branch / rev

telescope 0.1.0

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. Install `nvim-treesitter/nvim-treesitter`
2. Run command `TsBufEnable highlight` 
3. Call `require("telescope.builtin").current_buffer_fuzzy_find()`

### Expected behavior

Should open current buffer fuzzy find as expected.

### Actual behavior

![image](https://user-images.githubusercontent.com/48688801/223666768-5ed54b8b-ce16-4c63-ae67-f3246f61302d.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
> telescope 0.1.0

try bumping telescope to 0.1.1 or use the 0.1.x branch. see https://github.com/nvim-telescope/telescope.nvim#installation

this bug was already fixed a couple of months ago. a internal neovim api we used was removed thats why this feature no longer works in the 0.1.0 version

**Comment by doganalper** [comment]
@Conni2461 Thank you for informing about issue being fixed.
