### ISSUE TITLE
Keep <C-t> for action select_tab

### ISSUE THREAD

**Issue by sbeyer** [nvim-telescope/telescope.nvim#2419]
**Is your feature request related to a problem? Please describe.**
When I use telescope, I usually use C-x, C-v and C-t to open the selected file in a new split, vsplit, and tab respectively. However, C-t is overridden to action `change_cwd`.

**Describe the solution you'd like**
I would like, that C-t is kept as default `select_tab` action.

**Describe alternatives you've considered**
I fixed it via the configuration
```lua
      local actions = require "telescope.actions"
      local fb_actions = require("telescope").extensions.file_browser.actions
      require("telescope").setup {
        extensions = {
          file_browser = {
            mappings = {
              i = {
                ["<C-t>"] = actions.select_tab,
                ["<C-z>"] = fb_actions.change_cwd,
              },
              n = {
                t = actions.select_tab,
                z = fb_actions.change_cwd,
              },
            },
          },
        },
      }
```

**Additional context**
None.

**Comment by jamestrew** [comment]
This is specific to `telescope-file-browser` rather than core telescope but yeah, that's why the mappings are configurable. We will never agree on one correct key mapping.
There's no enhancement to make here.

**Comment by sbeyer** [comment]
I'm so sorry! I thought I would have written this issue for telescope-file-browser. It seems I had both projects open in different tabs and started the issue in the wrong tab. I'm deeply sorry for the disturbance.
