### ISSUE TITLE
Make window title alignment configurable

### ISSUE THREAD

**Issue by sunjon** [nvim-telescope/telescope.nvim#242]
During a moment of misconfiguration, a finder window rendered with the titles aligned to the right.

I'd initially thought it was a nice/interesting design choice (particularly on multi-window dialogs) and was quite disappointed when it was no longer there after further changes to the config file!

An option to select left/center/right title alignment would be appreciated.

**Comment by tjdevries** [comment]
I think actually this would be an issue for plenary, since we just use the title options from plenary. Once that's done, then we could do this pretty easily.
