### ISSUE TITLE
allow preview page to scroll left and right

### ISSUE THREAD

**Issue by sf8193** [nvim-telescope/telescope.nvim#2428]
**Is your feature request related to a problem? Please describe.**
I am usually working on a laptop, and in order to get more context on what i'm picking it'd be nice if i could pan left/right in the preview mode. This can be painful in repos with a high level of indents because a lot of what i'd like to see i can't

**Describe the solution you'd like**
The ability to pan left/right in the preview section

**Describe alternatives you've considered**
I've tried expanding the preview section, but it just makes it hard to know what file i'm picking through the results

**Comment by sankantsu** [comment]
Seems dupulicate of #2211 and #2243, and implemented in #2437.
Now you can try horizontal scrolling of preview by `actions.preview_scrolling_left` and `actions.preview_scrolling_right`!
They also have default key-mappping `<C-f>` and `<C-k>` in insert mode.
