### ISSUE TITLE
Map with expr for insert mode does not work with attach_mappings

### ISSUE THREAD

**Issue by brookhong** [nvim-telescope/telescope.nvim#2431]
### Description

With below script to call out `find_files`,  then press `C-w`, you'll just see `v:null` to be inserted into prompt.

              require("telescope.builtin").find_files {
                attach_mappings = function(_, map)
                  map("i", "<C-w>", function(_prompt_bufnr)
                    if vim.g.UseCW == 1 then
                        return "<C-w>"
                    else
                        return "<C-o>"
                    end
                  end, { expr = true })

                  return true
                end,
              }

It should trigger `C-w` or `C-o`.

### Neovim version

```markdown
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.6.1

### Telescope version / branch / rev

master

### checkhealth telescope

```markdown
telescope: 
========================================================================
  - ERROR: No healthcheck found for "telescope" plugin.
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. press `<space>j`
3. press `<C-w>` on the telescope ui

### Actual behavior

you'll see `v:null` to be inserted into prompt.

### Minimal config

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable",
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    {
        "nvim-telescope/telescope.nvim",
        dependencies = {
            { "nvim-lua/plenary.nvim" },
        },
        config = function()
            vim.keymap.set('n', '<space>j', function()
              require("telescope.builtin").find_files {
                attach_mappings = function(_, map)
                  map("i", "<C-w>", function(_prompt_bufnr)
                    if vim.g.UseCW == 1 then
                        return "<C-w>"
                    else
                        return "<C-o>"
                    end
                  end, { expr = true })

                  return true
                end,
              }
          end)
        end,
    },
})
```

**Comment by Conni2461** [comment]
sorry for the late response. thanks for your patients :) https://github.com/nvim-telescope/telescope.nvim/pull/2458 should fix your issue. would be nice if you can test this branch thanks :)

**Comment by brookhong** [comment]
It does not work, though the actual behavior changed. For the test case in the issue description, `C-w` will still trigger `C-o` when `vim.g.UseCW` was set 1, looks like the target function is not being executed when the key is pressed, instead of that it is executed before the key pressing and the result expression is never changed.

**Comment by Conni2461** [comment]
hmm idk, it seems to work on my side.

i slightly changed the example but if `vim.g.UseCW` is set to 1 the new version will no longer trigger `<C-o>` but `<Tab>` (in my example).

I quickly recorded the behavior in a screen capture.

https://github.com/nvim-telescope/telescope.nvim/assets/15233006/352ccebb-f063-44cb-9329-85f1c4da8367
