### ISSUE TITLE
Use vim.ui.input for confirmation

### ISSUE THREAD

**Issue by kuznetsss** [nvim-telescope/telescope.nvim#2438]
**Is your feature request related to a problem? Please describe.**
Currently if I open git branches picker and use some action, e.g. "delete branch" and then press `Esc` the selected branch will be deleted. I think it is not an expected behaviour for a user.

**Describe the solution you'd like**
Refactoring to use `vim.ui.input()` will solve the problem, because it calls callback with `nil` on input cancelation and current input string on confirmation.

I'm happy to create a PR if the feature would be considered as useful 😉

**Comment by kuznetsss** [comment]
Might be a duplicate of #1479 but it seems #1479 is not about confirmation.

**Comment by Conni2461** [comment]
we only use `vim.fn.input` for confirmations so yeah its a duplicate issues. I am going to close this and feel free to pick it up and provide an implementation by opening  a new PR. I personally dont have anything configured for `vim.ui.input` so i have currently no idea what people use for it but keep in mind that we can never have 2 telescope instances open at any time, so if ppl use telescope for `vim.ui.input` we probably can't use it.

**Comment by kuznetsss** [comment]
Just to make it clear: in the #2674 I fixed the bug about `Esc` in confirmation dialog, but didn't switch to `vim.ui.input()`.
