### ISSUE TITLE
Add support for .ignore file

### ISSUE THREAD

**Issue by tlvenn** [nvim-telescope/telescope.nvim#2448]
**Is your feature request related to a problem? Please describe.**
I need to be able to ignore some files / directories on a per project / root dir, not only globally. Those files are versioned.

**Describe the solution you'd like**
In addition to source the `.gitignore` file, source also `.ignore` file. This is something Helix does for its fuzzy finder
>  https://docs.helix-editor.com/configuration.html?highlight=.ignore#editorfile-picker-section

**Describe alternatives you've considered**
I don't think there is currently any alternative but to do it globally which has its drawbacks.

**Comment by jamestrew** [comment]
If you have `fd` or `rg`, pickers which utilize them (most if not all file related pickers) do respect `.gitignore` and `.ignore` by default.

You can run `:checkhealth telescope` to check for external dependencies.

**Comment by tlvenn** [comment]
Ha awesome, I guess I should have tried but it's good to understand why it actually works.
