### ISSUE TITLE
Telescope shows oldfiles that I didn't search

### ISSUE THREAD

**Issue by Ezaju** [nvim-telescope/telescope.nvim#2449]
### Description

After I opened some files and worked there, in oldfiles (space f o) I see files that I didn't search. 

### Neovim version

```markdown
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.3

### Telescope version / branch / rev

Telescope 0.1.1

### checkhealth telescope

```markdown
Fd 8.7.0
rg 13.0.0
```

### Steps to reproduce

1. Open python file
2. Work there
3. Space f o
4. See files that I didn't search ( As I know they are documents of pyright lsp)

### Expected behavior

'Space f o' must show me files that I search

### Actual behavior

<img width="666" alt="Issue_telescope" src="https://user-images.githubusercontent.com/129344418/228764517-1613c68f-0c13-45cc-b0cf-a03d8fc1589e.png">

### Minimal config

```Lua
--I'm using AstroNvim. No user configuration
return function(_, opts)
​ local telescope = require "telescope"
​ telescope.setup(o­pts)
​ local utils = req­uire "astronvim.util­s"
​ local conditional­_func = utils.condit­ional_func
​ conditional_func(­telescope.load_exten­sion, pcall(require, "notify"), "notify")
​ conditional_func(­telescope.load_exten­sion, pcall(require, "aerial"), "aerial")
​ conditional_func(­telescope.load_exten­sion, utils.is_avail­able "telescope-fzf-­native.nvim", "fzf")
end
​
```

**Comment by jamestrew** [comment]
This is certainly an AstroVim/configuration issue. 
Recommend you open a ticket there as this is not reproduce-able with a telescope minimal config.
