### ISSUE TITLE
`find_files` does **not** respect global `fd` ignore file

### ISSUE THREAD

**Issue by tmillr** [nvim-telescope/telescope.nvim#2466]
## Is your feature request related to a problem? Please describe.

When both `rg` and `fd` are installed, `find_files` does **not** respect the global `fd` ignore file that is picked up and used by `fd` by default (i.e. `$XDG_CONFIG_HOME/fd/ignore` or `$HOME/.config/fd/ignore`).

My particular use case has to do with enabling hidden (dot) files so that they are included in the results. Why? Because I often use this picker to begin editing files instead of `:edit`, and configuration files sometimes need to be edited and they often begin with a `.` (e.g. `.luarc.json`). I may even want to see/edit files inside `.git` as well. What I don't want however, is all the files under something like `.git/objects` polluting the results and/or slowing down the finder program, so I added that to my global `fd` ignore file, and then was wondering why files under `.git/objects` were still getting included in the results in the picker.

## Describe the solution you'd like

After a little bit of investigation, it seems the issue is caused by the fact that `find_files` uses `rg` over `fd` (see code below). Is there a good reason for this? If not, maybe it'd be better for `fd` to be the preferred/default `finder_command` (for the aforementioned reasons)?

For example:

```lua
files.find_files = function(opts)
  local find_command = (function()
    if opts.find_command then
      if type(opts.find_command) == "function" then
        return opts.find_command(opts)
      end
      return opts.find_command
    elseif 1 == vim.fn.executable "fd" then
      return { "fd", "--type", "f", "--color", "never" }
    elseif 1 == vim.fn.executable "rg" then
      return { "rg", "--files", "--color", "never" }
    elseif 1 == vim.fn.executable "fdfind" then
      return { "fdfind", "--type", "f", "--color", "never" }
    elseif 1 == vim.fn.executable "find" and vim.fn.has "win32" == 0 then
      return { "find", ".", "-type", "f" }
    elseif 1 == vim.fn.executable "where" then
      return { "where", "/r", ".", "*" }
    end
  end)()
```

Instead of:

https://github.com/nvim-telescope/telescope.nvim/blob/6258d50b09f9ae087317e392efe7c05a7323492d/lua/telescope/builtin/__files.lua#L235-L253

## Describe alternatives you've considered

Manually configuring/overriding the default find command in user config:

```lua
setup({
    ...
    pickers = {
        ...
        find_files = {
            ...
            hidden = true,
            find_command = { "fd", "--type", "f", "--color", "never" },
        },
```

### Relevant code:

https://github.com/nvim-telescope/telescope.nvim/blob/6258d50b09f9ae087317e392efe7c05a7323492d/lua/telescope/builtin/__files.lua#L235-L253

**Comment by fky2015** [comment]
<img width="884" alt="image" src="https://github.com/nvim-telescope/telescope.nvim/assets/16451516/01132ef2-19fd-4773-9a27-5b2ed2fddf13">

Maybe the performance is the reason.

**Comment by tmillr** [comment]
> <img alt="image" width="884" src="https://user-images.githubusercontent.com/16451516/242333127-01132ef2-19fd-4773-9a27-5b2ed2fddf13.png">
> Maybe the performance is the reason.

Nice find! That must be the reason.
