### ISSUE TITLE
Unable to map <C-CR>

### ISSUE THREAD

**Issue by ansidev** [nvim-telescope/telescope.nvim#2479]
### Description

I cannot create telescope mapping with Ctrl+Enter.

### Neovim version

```markdown
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.3.1

### Telescope version / branch / rev

v0.1.0

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.5.2

===== Installed extensions ===== ~
```

## Prerequisites

1. Use nvim 0.9.
2. Create folder `~/.config/nvim_repro`.
3. Copy the below minimal `init.lua` to nvim_repro.
4. Run `NVIM_APPNAME=nvim_repro nvim`.
5. Waiting for Lazy to install plugins.
6. Exit nvim.
7. Run `NVIM_APPNAME=nvim_repro nvim`.

## Reproduce

1. Run `:Telescope find_files`.
2. Select file A.
3. Press Ctrl + O => File A was opened in tab 1
4. Run `:Telescope find_files`.
5. Select file B.
6. Press Ctrl + O => File B was opened in tab 2
7. Run `:Telescope find_files`.
8. Select file C.
9. Press Ctrl + Enter => File C was opened in tab 2.

### Expected behavior

File C was opened in tab 3.
We will have 3 tabs: `| A | B | C |`.

### Actual behavior

We have 2 tabs: `| A | C |`.

### Minimal config

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    tag = "0.1.1",
    cmd = { "Telescope" },
    dependencies = { "nvim-lua/plenary.nvim" },
    config = function()
      local telescope_actions = require "telescope.actions"
      require "telescope".setup {
        pickers = {
          find_files = {
            mappings = {
              i = {
                ["<C-CR>"] = telescope_actions.select_tab,
                ["<C-o>"] = telescope_actions.select_tab,
              },
            },
          },
        },
      }
    end,
  },
}

require("lazy").setup(plugins)
```

**Comment by jamestrew** [comment]
This isn't actually a telescope issue. Terminals can't (some can with configuration) distinguish Ctrl+Enter from Enter from Ctrl+M.
So I think what's happening is that your `<C-CR>` is eventually being overwritten by the default `<CR>` action.
