### ISSUE TITLE
Search classes/functions.

### ISSUE THREAD

**Issue by karambaq** [nvim-telescope/telescope.nvim#2495]
**Is your feature request related to a problem? Please describe.**
I would like to search classes, for example for python it would be 
`class <class_name>\(`

It's not intuitive to type `\` before `(` every time and I would like to have the option to just pass this as start "format" for telescope live_grep, I think it's already possible but don't know how.

**Describe the solution you'd like**
Pass default "pattern" to start from, and then just type the class name.

**Comment by stounfo** [comment]
I've fixed it by using a custom vimgrep_arguments argument when calling the live_grep function. Example:
```lua
vimgrep_arguments = {
    "rg",
    "--color=never",
    "--no-heading",
    "--with-filename",
    "--line-number",
    "--column",
    "--smart-case",
    "--fixed-strings" -- literal prompt instead of regex
},
require("telescope.builtin").live_grep({
        vimgrep_arguments = vimgrep_arguments,
})
```

**Comment by jamestrew** [comment]
I would recommend the `additional_args` option over `vimgrep_arguments` but the idea is correct.

```lua
require("telescope.builtin").live_grep {
  additional_args = { "--fixed-strings" },
}
```
