### ISSUE TITLE
Previewer panics on invalid files

### ISSUE THREAD

**Issue by rockerBOO** [nvim-telescope/telescope.nvim#250]
```
Error executing vim.schedule lua callback: ...nvim/plugged/telescope.nvim/lua/telescope/previewers.lua:29: ENOENT: n
o such file or directory:
```

https://imgur.com/EIxSYFs

**Comment by Conni2461** [comment]
I'm looking into this. I think i made a mistake a couple of days ago.
On which commit are you? Latest master?
Does your find files also show directories?
