### ISSUE TITLE
after neovim commit: d52cc66, using :Telescope find_files opens file in insert mode

### ISSUE THREAD

**Issue by catgoose** [nvim-telescope/telescope.nvim#2501]
### Description

After https://github.com/neovim/neovim/commit/d52cc668c736ef6ca7ee3655a7eb7fe6475afadc when opening a file, neovim is put into insert mode

Possibly related: https://github.com/nvim-telescope/telescope.nvim/issues/2027

### Neovim version

```markdown
NVIM v0.10.0-dev-302+g7ed4274f6
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu 22.04

### Telescope version / branch / rev

telescope 0.1.x

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.3.1

===== Installed extensions ===== ~

Telescope Extension: `do-the-needful` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `harpoon` ~
- No healthcheck provided

Telescope Extension: `lazy` ~
- No healthcheck provided

Telescope Extension: `ui-select` ~
- No healthcheck provided

Telescope Extension: `workspaces` ~
- No healthcheck provided
```

### Steps to reproduce

1. check out neovim after commit [d52cc66](https://github.com/neovim/neovim/commit/d52cc668c736ef6ca7ee3655a7eb7fe6475afadc)
2. build and install neovim
3. select and open file with `:Telescope find_files`
4. observe that neovim is now in insert mode

### Expected behavior

file should be opened in normal mode

### Actual behavior

file is opened in insert mode

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by apazzolini** [comment]
In case it helps tracking the bug down, I've also noticed this also happens when you use `<c-q>` to send items to the qflist. On the second (and subsequent) times you do that, you'll be left in insert mode in the qflist buffer.

**Comment by Shougo** [comment]
I describe why it does not work well.

https://github.com/neovim/neovim/pull/22984

The change means `the mode is restored when mode is changed in autocmd`.

I think the open is executed asynchronously.  So the mode change may be executed in `autocmd`.
So it is restored.  I think the execution must be synchronous.

The bug is from asynchronously.  So it depends on your config and plugins and it is not 100% reproduce-able.

**Comment by Shougo** [comment]
Why `:redrawstatus` cause this:

I think slow commands like `:redrawstatus` or `:sleep` executes asynchronous routine.  So it executes the mode change.

**Comment by Shougo** [comment]
In `ddu-ui-ff` plugin, it has similar problem.
Because of asynchronous execution.

The problem is fixed after execute the action synchronously.

**Comment by rockyzhang24** [comment]
I can confirm that after installing `nvim-treesitter-context`, the issue will occur. So it means nvim-treesitter-context executes some asynchronous functions that cause this problem, right?

**Comment by Shougo** [comment]
I think...

* telescope execution is asynchronous

* If you install plugins, it may trigger asynchronous functions in autocmd.

* The mode change is restored in autocmd events even it is executed from asynchronous routine.

**Comment by Shougo** [comment]
`nvim-treesitter` calls many autocmd.

https://github.com/nvim-treesitter/nvim-treesitter-context/blob/f1179bde94bcbeed68be33e694079afb71d49cac/lua/treesitter-context.lua#L751

**Comment by rockyzhang24** [comment]
@Shougo Okay it makes sense. Thank you for your investigation.

**Comment by rockyzhang24** [comment]
@Shougo So the bug should be fixed by the plugins themselves and they should change the async autocmd to sync one, right? If so, many plugin should make adjustments. Is it possible to fix it on neovim? Thanks.

**Comment by Shougo** [comment]
> @Shougo So the bug should be fixed by the plugins themselves and they should change the async autocmd to sync one, right? If so, many plugin should make adjustments and probably may sacrifice their performance. Is it possible to fix it on neovim? Thanks.

I don't know.  It depends on Vim/neovim developers decision.
I think `restore mode after autocmd` is reasonable decision.
But it conflicts with current asynchronous plugins implementation.
You should ask developers.

**Comment by rockyzhang24** [comment]
> I think restore mode after autocmd is reasonable decision

Yes, I second this. Thank you.

**Comment by searleser97** [comment]
> > I think restore mode after autocmd is reasonable decision
> 
> Yes, I second this. Thank you.
> 
> Btw, for someone experiencing this issue, so far we could use this workaround [#2027 (comment)](https://github.com/nvim-telescope/telescope.nvim/issues/2027#issuecomment-1510001730) as a quickfix.

Where should we place this code ? Do we need this library ? https://github.com/tenxsoydev/nx.nvim

**Comment by mehalter** [comment]
Just to contribute to the conversation about workarounds, I have had some issues with the current recommended `WinLeave` work around when using a floating window that opens a telescope prompt (like filtering Mason window) where it will close the floating window. Here is a different workaround that also remedies the issue for now (this is heavily reliant on the default mappings, but could be modified to whatever config) Basically I just added the following insert mode mappings to my telescope setup:

```lua
  mappings = {
    i = {
      ["<CR>"] = function()
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc><CR>", true, false, true), "i", false)
      end,
      ["<C-x>"] = function()
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc><C-x>", true, false, true), "i", false)
      end,
      ["<C-v>"] = function()
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc><C-v>", true, false, true), "i", false)
      end,
      ["<C-t>"] = function()
        vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc><C-t>", true, false, true), "i", false)
      end,
    },
  },
```

**Comment by Shougo** [comment]
Yeah.  The mappings should be executed in normal mode.

**Comment by zeertzjq** [comment]
I cannot reproduce this issue.

**Comment by catgoose** [comment]
Are you checking out the above neovim commit and building from source?

**Comment by zeertzjq** [comment]
Yes

**Comment by rockyzhang24** [comment]
Seems this issue is gone with neovim built using the latest commit. I will keep watching it.

**Comment by catgoose** [comment]
> Seems this issue is gone with neovim built using the latest commit. I will keep watching it.

Yep, that's what I see as well.  I'm going to close this issue.

**Comment by mehalter** [comment]
https://github.com/neovim/neovim/commit/b46f61ac050e6eb530ceb4d4b510b612596427c5

is this because of this commit? I'm just curious and think it would be good to confirm the bug fix and document where it happened. I also can confirm I'm not getting the issue with the latest! :D
