### ISSUE TITLE
Preview Scrolling doesn't work

### ISSUE THREAD

**Issue by tami5** [nvim-telescope/telescope.nvim#253]
### Description

Scrolling with `<C-d>` and `<C-u>` doesn't work for me.

**Expected Behavior**

`<C-d> <C-u>` move preview up down without any issues

**Actual Behavior**

`<C-d> <C-u>` doesn't navigate preview window. Additionally with git_commits I
get additional error: `Error executing lua Vim:Can't send data to closed stream`

### Details

<details><summary>Reproduce</summary>

1. nvim -NU test.vim
2. :Telescope live_grep or git_commits 
3. `<C-d>/<C-u>`

</details>

<details><summary>Environment</summary>

- nvim version: v0.5.0-828-g0a95549d6
- Operating system :Archlinux
- Telescope commit: #749c865

</details>

<details><summary>Configuration</summary>
<p>
 

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()
" the command ran, also try Telescope fd
autocmd VimEnter * PlugClean! | PlugUpdate --sync | close | Telescope git_commits
lua << EOF
local actions = require'telescope.actions'
require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "top", --// change
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "ascending", --// change
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_sorter =  require'telescope.sorters'.get_fuzzy_file ,
    generic_sorter =  require'telescope.sorters'.get_generic_fuzzy_sorter,
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```
</p>
</details>

**Comment by tami5** [comment]
@Conni2461 I had this issue for long time because I don't use preview often, but thanks to your new builtin, it brought the issue to the surface :laughing:

**Comment by Conni2461** [comment]
Oh. I have not implemented this in git_commits, because we only run the "git command". Maybe we should pipe it into less for scrolling?! 
One question you have bat installed and use that right?

**Comment by tami5** [comment]
@Conni2461 oh I see, Yes I have it installed. Did you try to reporduce the issue? and preview scrolling works in e.g. live_grep or fd. Thanks

**Comment by Conni2461** [comment]
No i could not reproduce. Works fine in live_grep and fd.

**Comment by tami5** [comment]
Sorry I mean did you do vim -Nu test.vim of the reproduce configuration? @Conni2461

**Comment by Conni2461** [comment]
Yes i did. I could not reproduce it. I'm on nvim version: v0.5.0-839-g1b8867ab3. Arch as well and bat version 0.16.0. So i don't know

**Comment by tami5** [comment]
Just update bat, still same issue, damn is there another factor effecting preview navigation? I guess we will have to wait for tj thoughts on this

**Comment by Conni2461** [comment]
I think i found something. Scrolling does not work if `--pager=less` is not set. I can't imagine an environment without less but do you have less installed and does scrolling work if you open a big enough file with `bat`?

**Comment by tami5** [comment]
Bat scroll fine in terminal. How can I check if --pager is set to less?

**Comment by Conni2461** [comment]
1. Could you try running `:lua require'telescope.builtin'.fd{ maker = function(filename) return { 'less', filename } end }` This will use less as previewer. So can you tell me if scrolling works?
2. Could you run normal fd with bat und put an `print(has_less)` in `lua/telescope/previewers.lua:51`

**Comment by tami5** [comment]
@Conni2461  1. No scrolling , 2. prints true https://asciinema.org/a/RoT9ZUJY4eDol3TjjSfml5eLH

**Comment by eth3lbert** [comment]
@tami5 could you show your `$LESS` option? I also have the scrolling issue previously.

**Comment by tami5** [comment]
@eth3lbert Interesting so there might be hope :D it the output of `$ echo $LESS` = `iFMRSX`

**Comment by eth3lbert** [comment]
@tami5 try keep only `iMRS`.

**Comment by tami5** [comment]
Damnnn that fixed it, wow it was less configuration all along @tjdevries @Conni2461 !!!. Thanks so much @eth3lbert , here's another feature I can start adopting to.
