### ISSUE TITLE
telescope-symbols: insertion of symbols doesn't work anymore

### ISSUE THREAD

**Issue by walialu** [nvim-telescope/telescope.nvim#2534]
### Description

Insertion of symbols doesn't work anymore in `telescope-symbols`.
I don't know if it's an issue with Lazy, the symbols plugin, telescope or nvim.

### Neovim version

```markdown
NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

ArchLinux

### Telescope version / branch / rev

master

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~
```

### Steps to reproduce

1. `nvim -nu minimal.lua test.md`
2. `:Telescope symbols`
3. Pick a symbol and press enter

### Expected behavior

The pickes symbol/emoji has been inserted into the document and we are in insert mode.

### Actual behavior

Telescope picker is closed and we are back in normal mode.

### Minimal config

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- Install Plugins
require('lazy').setup({
  { 'nvim-telescope/telescope.nvim', dependencies = { 'nvim-lua/plenary.nvim' } },
  { 'nvim-telescope/telescope-symbols.nvim', dependencies = { 'nvim-telescope/telescope.nvim' } },
})
```

**Comment by Conni2461** [comment]
pretty sure caused by https://github.com/nvim-telescope/telescope.nvim/commit/3f1b57908b312e7f3bfd919c52c61524a673e622, i am looking into it

**Comment by walialu** [comment]
@Conni2461, yes, you're right, I checked out the previous commit and it's working. So this is somehow breaking the symbols plugin :cry:

**Comment by Conni2461** [comment]
yeah was sure that this PR introduces problems see (me 3 months ago https://github.com/nvim-telescope/telescope.nvim/pull/2336#issuecomment-1435950625)

but https://github.com/nvim-telescope/telescope.nvim/pull/2535 should fix the issue

**Comment by walialu** [comment]
@Conni2461, I checked out your branch and it is working again, thanks so much <3
