### ISSUE TITLE
Actions.close(prompt) now requires 2 ticks for window cursor handling.

### ISSUE THREAD

**Issue by Dotrar** [nvim-telescope/telescope.nvim#2540]
### Description

Hey all

I've been trying to make my first telescope plugin to search for things and input into my current buffer. I was looking at the [developers.md doc](https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md), and have the following code (as per docs):

```lua
        attach_mappings = function(prompt_bufnr, map)
            actions.select_default:replace(function()
                actions.close(prompt_bufnr)
                local selection = action_state.get_selected_entry()
                vim.api.nvim_put({ selection.value},"l", true, true)
              end)
          return true
        end,
```
i've been pulling my hair out on why this doesn't work, and i kept seeing a "flash" of the text i was trying to put - it turns out, the window is still open when you run the `nvim.api.nvim_put()` - so it will put the text in the closing telescope window.

I've had to work around this by putting 2 `vim.schedule()` calls, so that the "current window" is the window after telescope has closed.
```lua
        attach_mappings = function(prompt_bufnr, map)
            actions.select_default:replace(function()
                actions.close(prompt_bufnr)
                local selection = action_state.get_selected_entry()
                vim.schedule(function ()
                vim.schedule(function ()
                    vim.api.nvim_put({ selection.value},"l", true, true)
                end)
                end)
              end)
          return true
        end,
```

This makes the code behave as expected. I have also tried with just one schedule call and still does not work, you need at-least 2.

### Neovim version

```markdown
NVIM v0.10.0-dev-382+gebb10d624
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH
```

**Comment by Conni2461** [comment]
does this still happen for you? i can not reproduce this with nvim-0.9.4 and with latest telescope master or telescope 0.1.4

**Comment by Dotrar** [comment]
HMM, nope, seems to not be the case anymore, with more recent versions.

Thanks for looking into this anyway! Good luck with all you do!
