### ISSUE TITLE
Lastplace plugins not setting going to lastplace when using :Telescope buffers

### ISSUE THREAD

**Issue by ethanholz** [nvim-telescope/telescope.nvim#2542]
### Description

When opening multiple files using `nvim *.txt`, the lastplace gets set correctly for the first file and for when using `:bn` or `:b1`. However, when we attempt to use `:Telescope buffers`, the place holder does not get set correctly on first load. More details can be found here: https://github.com/ethanholz/nvim-lastplace/issues/21. This has been reported with other versions as well.

### Neovim version

```markdown
NVIM v0.10.0-dev-122+g95c6e1b74
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Pop_OS! 22.04

### Telescope version / branch / rev

6d3fbff

### checkhealth telescope

```markdown
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.3.1

===== Installed extensions ===== ~

Telescope Extension: `file_browser` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `harpoon` ~
- No healthcheck provided

Telescope Extension: `luasnip` ~
- No healthcheck provided
```

### Steps to reproduce

0. Be in a directory with lots of text files
1. `nvim -nu minimal.lua *.txt`
2. Move cursor in files to somewhere other than the top
3. `:wq`
4. `nvim -nu minimal.lua *.txt`
5. `:Telescope buffers`
6. Select a new buffer

### Expected behavior

I expect that the last cursor position should be set for *every* buffer.

### Actual behavior

The last cursor position does not get set for any buffer but the first.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      {
          'ethanholz/nvim-lastplace', {
              config = require("ethanholz/nvim-lastplace").setup
          }
      }

      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end#
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
I can replicate this but I'm not sure if it's a telescope bug.
After step 4, if I run `:lua vim.print(vim.fn.getbufinfo())` only the first buffer has `lnum` set to the correct value.
This I can replicate without telescope even installed. And telescope's `buffer` picker is based off of the `getbufinfo()` function.

**Comment by ethanholz** [comment]
Interesting. What I find odd is that if you do something like a `:bn`, the line does get set correctly.

**Comment by jamestrew** [comment]
I haven't looked too closely into `nvim-lastplace` but seeing the events `BufRead` & `BufWinEnter` for autocommands, maybe one or both of those events aren't actually triggered by a `nvim *.txt`.

**Comment by DUOLabs333** [comment]
I use https://github.com/farmergreg/vim-lastplace instead of the Lua rewrite, which does work with multiple files. However, I'm still experiencing this problem with `:Telescope buffers`.

**Comment by DUOLabs333** [comment]
Also, why does lnum matter to Telescope? Shouldn't it just do :edit, without trying to move to the right line (or is there a way to set this behavior)? Maybe lnum is only updated once you actually switch to the buffer, not just when you open it.

**Comment by jamestrew** [comment]
We use lnum for previews. And wherever we have lnum info, we set the cursor to it after `:edit`. I'm not really convinced there's anything wrong with doing this. We're just putting the cursor according to where `getbufinfo()` says to put it.

**Comment by DUOLabs333** [comment]
It seems that since `lastplace` only sets the right cursor position when the buffer is being opened for the first time, there may be a race condition between lastplace and Telescope when it comes to placing the cursor and updating the buffer info.
