### ISSUE TITLE
builtin.grep_string not working in visual mode

### ISSUE THREAD

**Issue by no-more-secrets** [nvim-telescope/telescope.nvim#2547]
### Description

I got the impression from the documentation that calling `builtin.grep_string` when in visual mode will grep for the highlighted text, as opposed to just the token that happens to be over the cursor... have I understood wrong?  If not, it doesn't seem to be working for me -- at least not reliably... is it possible that maybe spaces or other chars need to be escaped when the selected text has them in it?

### Neovim version

```markdown
NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Various Ubuntu-based distros from the last couple years

### Telescope version / branch / rev

0.1.x

### checkhealth telescope

```markdown
1
  1 ──────────────────────────────────────────────────────────────────────────────
  2 telescope: require("telescope.health").check()
  3
  4 Checking for required plugins
  5 - OK plenary installed.
  6 - OK nvim-treesitter installed.
  7
  8 Checking external dependencies
  9 - OK rg: found ripgrep 11.0.2
 10 - OK fd: found fd 7.4.0
 11
 12 ===== Installed extensions =====
 13
 14 Telescope Extension: `fzf`
 15 - OK lib working as expected
 16 - OK file_sorter correctly configured
 17 - OK generic_sorter correctly configured
```

### Steps to reproduce

If you go into visual mode and highlight a single token then `builtin.grep_string` correctly searches for that token.  But when the selected text has e.g. spaces or dots in it then it doesn't seem to work right -- it's almost as if it is taking the identifier under the cursor instead of the visual selection.

### Expected behavior

`builtin.grep_string` should grep for whatever text is visual selected (though I'd forgive it if it ignored newlines).

### Actual behavior

`builtin.grep_string` does not seem to work right when the selected text is not a single identifier, though I can't prove that 100%.

### Minimal config

```Lua
If this is needed I'm happy to provide it, but probably won't really shed light on this.
```

**Comment by jamestrew** [comment]
This is actually taken care of on the master branch https://github.com/nvim-telescope/telescope.nvim/pull/2333
