### ISSUE TITLE
Previewer feat (66b03e7) breaks file-browser 

### ISSUE THREAD

**Issue by geg2102** [nvim-telescope/telescope.nvim#2558]
### Description

Commit 66b03e7 seems to break the file-browser extension. Not sure if I should report it here or there, but on this commit, I get the following when opening file-browser: 

Error executing vim.schedule lua callback: ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:435: Error executing lua: vim/shared.lua:0: s: expected string, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        vim/shared.lua: in function 'split'
        ...m/lazy/telescope.nvim/lua/telescope/previewers/utils.lua:14: in function 'detect_from_shebang'
        ...m/lazy/telescope.nvim/lua/telescope/previewers/utils.lua:44: in function 'filetype_detect'
        ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:441: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:435>
        [C]: in function 'nvim_buf_call'
        ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:435: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:429>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:435: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:429>

This is fixed by reverting to 4226740. 

### Neovim version

```markdown
NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

ubuntu 20.04.6 LTS

### Telescope version / branch / rev

telescope

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 11.0.2
- OK fd: found fd 8.6.0

===== Installed extensions ===== ~

Telescope Extension: `file_browser` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `notify` ~
- No healthcheck provided
```

### Steps to reproduce

:Telescope file_browser

### Expected behavior

Opens file browser 

### Actual behavior

Get above stack trace. 

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      {
          "nvim-telescope/telescope-file-browser.nvim",
          requires = {
              "nvim-telescope/telescope.nvim",
              "nvim-lua/plenary.nvim"
          }
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')

  require('telescope').load_extension('file_browser')
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
I'll look into it. i prefer not to revert

**Comment by gmartsenkov** [comment]
> could you test #2559 ?

This fixes the issue for me 👍

**Comment by Alienover** [comment]
<img width="1284" alt="image" src="https://github.com/nvim-telescope/telescope.nvim/assets/12182069/4217e202-f318-4bf9-ad26-3ffd235a69a4">
I guess this is the bug that caused this issue. It should use `s` to do the splitting and matching when it's not `nil`, right?

**Comment by Conni2461** [comment]
@Alienover also good catch thanks :)

**Comment by jamestrew** [comment]
I caught another similar issue with the `file_maker` when previewing files/directory with a path with a `$` sign. Looks like the $ sign is getting escaped and `Path:expand` fails to handle it. 

```
Error executing vim.schedule lua callback: ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:435: Error executing lua: ....local/share/nvim/lazy/plenary.nvim/lua/plenary/path.lua:339: Path not valid
stack traceback:
        [C]: in function 'error'
        ....local/share/nvim/lazy/plenary.nvim/lua/plenary/path.lua:339: in function 'expand'
        ....local/share/nvim/lazy/plenary.nvim/lua/plenary/path.lua:711: in function 'is_file'
        ...ojects/telescope.nvim/lua/telescope/previewers/utils.lua:46: in function 'filetype_detect'
        ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:441: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:435>
        [C]: in function 'nvim_buf_call'
        ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:435: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:429>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:435: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:429>
```

**Comment by Conni2461** [comment]
Uff i think we should fix that in plenary. I kinda wanna call `is_file` but `:expand()` should never be called because its not cross platform afaik.

**Comment by Conni2461** [comment]
https://github.com/nvim-lua/plenary.nvim/pull/499 should fix the issue, could you retest

**Comment by jamestrew** [comment]
> [nvim-lua/plenary.nvim#499](https://github.com/nvim-lua/plenary.nvim/pull/499) should fix the issue, could you retest

looks good thanks.
