### ISSUE TITLE
filetype detect error when using nvchad theme switcher

### ISSUE THREAD

**Issue by tariks** [nvim-telescope/telescope.nvim#2562]
### Description

Same error as #2558 occurs when using the themes extension in nvchad. The following message is displayed each time a theme is previewed:

Error executing vim.schedule lua callback: ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:424: Error executing lua: vim/shared.lua:0: s: expected string, got nil
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	vim/shared.lua: in function 'gsplit'
	vim/shared.lua: in function 'split'
	...m/lazy/telescope.nvim/lua/telescope/previewers/utils.lua:14: in function 'detect_from_shebang'
	...m/lazy/telescope.nvim/lua/telescope/previewers/utils.lua:44: in function 'filetype_detect'
	...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:430: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:424>
	[C]: in function 'nvim_buf_call'
	...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:424: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:418>
stack traceback:
	[C]: in function 'nvim_buf_call'
	...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:424: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:418

### Neovim version

```markdown
NVIM v0.10.0-dev-346+gd36dd2bae
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.4

### Telescope version / branch / rev

master / 66b03e7

### checkhealth telescope

```markdown
- ERROR No healthcheck found for "telescope" plugin.
```

### Steps to reproduce

unsure how to display minimal config as nvchad configs are complex

### Actual behavior

error message displayed

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Not really familiar with the themes extension in nvchad but this should be fixed in the latest commit https://github.com/nvim-telescope/telescope.nvim/commit/69e8715786d1ee86249eff326f9d6804ee388502

Can you test with this commit?

**Comment by tariks** [comment]
Yes it works. Unsure why I was a commit behind earlier.
