### ISSUE TITLE
Files with unknown extension are treated as "binary" and not previewed

### ISSUE THREAD

**Issue by EtiamNullam** [nvim-telescope/telescope.nvim#2566]
### Description

"Binary cannot be previewed" are displayed in place of the preview for most file types.

This seems to be a recent regression, as it's fine for me on commit `991d5db62451ee7a50944b84aaad4b58c3447b60`.

### Neovim version

```markdown
NVIM v0.10.0-dev-422+g68e2d7229
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 10

### Telescope version / branch / rev

master

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0 (rev af6b6c543b)
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `ui-select` ~
- No healthcheck provided

Telescope Extension: `undo` ~
- No healthcheck provided
```

### Steps to reproduce

1. `mkdir dir` - create isolated directory to run our example in
2. `cd dir` - move to our isolated directory
3. `'hello world' >> text.filewithunknownextension` - create file with uncommon extension but a basic text content
4. `nvim -nu minimal.lua` - start nvim
5. `:cd dir` - move to our isolated directory
6. `:Telescope find_files` - browse file(s) with telescope
7. Notice the content of our file will not be displayed in the preview, instead we will see a message: "Binary cannot be previewed"

### Expected behavior

We should be able to see the file preview no matter the file extension.

I would rather see attempted (and sometimes garbled in case of non-text files) preview of text rather than error like that with no attempt to preview it.

### Actual behavior

"Binary cannot be previewed" is displayed in place of the preview for most file types.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
sure you are on 0.1.2? because we didnt change preview/ftdetect on that branch, because its a breaking change.

I can reproduce on latest master, but not on 0.1.2.

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/2567 should fix your issue

**Comment by EtiamNullam** [comment]
You're right, my bad - I was on `master`, not on `0.1.2`
