### ISSUE TITLE
grep_string ordering

### ISSUE THREAD

**Issue by everdimension** [nvim-telescope/telescope.nvim#2573]
I coming from `:rg` and wishing to improve my flow for searching file contents AND file names

Related to https://github.com/nvim-telescope/telescope.nvim/issues/564

```
:Telescope grep_string search=
```

This looks awesome, but I miss one thing

Say I'm looking for _hello world_ -like results and my search input is `hellwo`

Say I have two files:
One is named `some-file.ts` (an irrelevant name)
```
// some-file.ts
export const HELLO_WORLD = '42';
```

Another file is named `hello.ts` (name matches search)
```
// hello.ts
export const world = '...';
```

Since the search is both for file names and file contents, results include both files

What I want is for the first file to come up _first_, because the match is found in full in its _contents_, and the other file should be sorted _later_, because it is only a match because of _file name + file contents_

Is this possible?

**Comment by jamestrew** [comment]
No I'm afraid something like that isn't currently available. You can do `only_sort_text=true` to only sort text but that'll take filenames completely out. But beyond that I don't think there's any plans to support a sorter like that either.

**Comment by everdimension** [comment]
Ok, thank you for your answer!

I might consider using two searching modes in my workflow in that case, or trying to go back to Rg
