### ISSUE TITLE
UX bug: colorscheme selects the colorscheme on previewing, instead on when pressing ENTER

### ISSUE THREAD

**Issue by Zeioth** [nvim-telescope/telescope.nvim#2574]
### Description

When using the method

   require("telescope.builtin").colorscheme { enable_preview = true }

* The theme is selected when the cursor passed over it.

* Instead, it should only be selected when pressing ENTER.

### Neovim version

```markdown
9.1
```

### Operating system and version

Arch

### Telescope version / branch / rev

main HEAD

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `aerial` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `luasnip` ~
- No healthcheck provided

Telescope Extension: `macroscope` ~
- No healthcheck provided

Telescope Extension: `neoclip` ~
- No healthcheck provided

Telescope Extension: `notify` ~
- No healthcheck provided

Telescope Extension: `projects` ~
- No healthcheck provided

Telescope Extension: `undo` ~
- No healthcheck provided
```

### Steps to reproduce

1. require("telescope.builtin").colorscheme { enable_preview = true }
2. move the menu cursor over an item.
3. press ESC

the theme will be applied even without pressing ENTER.

### Expected behavior

The theme is selected when pressing ENTER

### Actual behavior

The theme is selected when passing the menu cursor over it.

### Minimal config

```Lua
doesn't apply.
```

**Comment by jamestrew** [comment]
Using a min config, I not seeing the colorscheme being applied when closing the picker with `<ESC>`.


https://github.com/nvim-telescope/telescope.nvim/assets/66286082/df079094-00ec-4de4-8935-3d5863ae536f

**Comment by Zeioth** [comment]
@jamestrew  I've tested a bit more

## How to replicate
* Having [tokyonight](https://github.com/folke/tokyonight.nvim) (night) as current theme.
* Call `require("telescope.builtin").colorscheme { enable_preview = true }`
* Move the cursor to trigger the preview, and press ESC

## What hapen
If you are using a variant of your current theme, when you press ESC, your theme will be changed to the main variant of the theme you are using.

**Comment by jamestrew** [comment]
Thanks, I'm able to replicate this using your steps now. I'll investigate this.

**Comment by jamestrew** [comment]
I'm actually thinking this is a tokyonight bug.
If I do `:colorscheme tokyonight-moon` and then immediately do `:colorscheme` the output says `tokyonight` not `tokyonight-moon`.

I've tried this with [catppuccin](https://github.com/catppuccin/nvim) and it's variants but I get the correct colorscheme names back as expected.

Since the `enable_previewer` option for the `colorscheme` picker simply sets the colorscheme back to whatever `:colorscheme` returns initially, if it's not receiving the correct colorscheme, it's not going to work.

**Comment by jamestrew** [comment]
Looks like it was a conscious decision based on catppuccin's original behavior
https://github.com/folke/tokyonight.nvim/issues/300

but since then, catppuccin's changed its behavior
https://github.com/catppuccin/nvim/pull/458
