### ISSUE TITLE
Allow prepopulating the prompt

### ISSUE THREAD

**Issue by itmecho** [nvim-telescope/telescope.nvim#2575]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just a QoL improvement I think!

**Describe the solution you'd like**
I think it would be nice to be able to set the initial prompt input, i.e. prepopulate the search input. This could be an option like `initial_prompt`.

This would enable users to have a visual mode keymap like `y:Telescope help_tags initial_prompt=<c-r>"<cr>` which would open the telescope help_tags picker pre-searched for the selected text.

**Describe alternatives you've considered**
My current solution is to yank the selection, run `Telescope help_tags` and then do `<c-r>"` to paste the selection into the telescope input.

**Additional context**
Can't think of anything to put here.

**Comment by jamestrew** [comment]
There is a `default_text`option for all pickers. It's not well documented but doing something like `:Telescope help_tags default_text=nvim_get_mode` looks to work.

**Comment by itmecho** [comment]
> There is a `default_text` option for all pickers. It's not well documented but doing something like `:Telescope help_tags default_text=nvim_get_mode` looks to work.

Ah amazing, thank you! I looked through the code but obviously not in the right place 😅
