### ISSUE TITLE
Question: In a picker, how can I change the Results title?

### ISSUE THREAD

**Issue by Zeioth** [nvim-telescope/telescope.nvim#2576]
I've read [the docs](/home/zeioth/images/screenshot_2023-06-17_06-09-01_905215532.png) and I don't see how it's done.

I refer to the second title:
![screenshot_2023-06-17_06-09-01_905215532](https://github.com/nvim-telescope/telescope.nvim/assets/3357792/783b5a5f-c1de-4833-8247-6bd3d06664db)

**Comment by jamestrew** [comment]
It's just `results_title`.
Eg. `:Telescope find_files results_title=hello`
