### ISSUE TITLE
Issues using the git buildins

### ISSUE THREAD

**Issue by jim-at-jibba** [nvim-telescope/telescope.nvim#258]
Hey bud,

neovim: v0.5.0-828-g0a95549d6
telescope: git sha e977c92 

Having issues using the git builtins. 

I have added the following to my init.vim
`nnoremap <Leader>g :lua require('telescope.builtin').git_status()<CR>`

but getting the following error:

`E5108: Error executing lua [string ":lua"]:1: attempt to call field 'git_status' (a nil value)`

When tabbing throught `:Telescope` lots of the git builtins are not showing

Thanks

**Comment by clason** [comment]
Where did you get `git_status` from? I only know of `git_files` and `git_commits`.

**Comment by jim-at-jibba** [comment]
From the readme. There are a number of new builtin for `builtin.git_branches`, `builtin.git_status` etc

**Comment by clason** [comment]
Oh, those are (already...) out of date -- the `git` module has been refactored, it should now be `builtin.git.status`.

**Comment by jim-at-jibba** [comment]
Ah nice. Thanks.

**Comment by clason** [comment]
No, sorry, I wrote too soon -- those functions are exported via `builtin`, so your code should work. (And it does for me.) So something else must be going on.

**Comment by jim-at-jibba** [comment]
I added to the above that they dont show as options when tabbing through `:Telescope`

![Screenshot 2020-11-17 at 17 34 31](https://user-images.githubusercontent.com/7897877/99425797-3f5e9e80-28fb-11eb-89d2-e0e2687c9593.png)

**Comment by clason** [comment]
That's unrelated, I think. I don't see them either and `:lua require'telescope.builtin'.git_status()` still works for me. Are you sure that all dependencies (in particular `plenary`) are also up to date?

**Comment by tami5** [comment]
Copy this to nvim -Nu test.vim then do :lua require'telescope.builtin'.git_status() 
```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
````

If its work, maybe you need to update deps

**Comment by jim-at-jibba** [comment]
That did work. Ok so its a dependency issue. Thanks for your help.

**Comment by clason** [comment]
Glad it works now! For the record, if you use telescope, you always need to keep plenary (and popup) updated as well -- they are developed in parallel.

**Comment by tami5** [comment]
@clason sad reality :laughing: hope it gets solved soon

**Comment by jim-at-jibba** [comment]
I am not sure it is plenary or popup as I just updated the lot with Plug. But I am running the latest release of nvim not built from master

**Comment by tami5** [comment]
After updating the issue is solved unless the above snippet didn't work. Also sometimes you might need to reload telescope. Use builtin.reloader
