### ISSUE TITLE
Centering cursor when selecting with current_buffer_fuzzy_find

### ISSUE THREAD

**Issue by lsig** [nvim-telescope/telescope.nvim#2580]
I was wondering if there is some action you can chain or this could maybe be a property, when using current_buffer_fuzzy_find that the cursor gets centered on search. 

This could be a property in the table like so center_on_search = true. 

This how I get the desired functionality now, but I was wondering if there is another way to do this? 

		current_buffer_fuzzy_find = {
			theme = "dropdown",
			previewer = false,
			mappings = {
				i = {
					["<esc>"] = actions.close,
					["<CR>"] = function(prompt_bufnr)
						actions.select_default(prompt_bufnr)
						vim.cmd("normal! zz")
					end,
				},
			},
		}

**Comment by jamestrew** [comment]
I think you're workaround is quite adequate. There is a `center` action which you can use in conjunction with `select_default` like this

```lua
["<CR>"] = actions.select_default + actions.center
```
but all it does is call `vim.cmd ":normal! zz"` as well.
`:h telescope.actions.center()`

**Comment by lsig** [comment]
Thanks for the response! 👍
