### ISSUE TITLE
File browser not focused

### ISSUE THREAD

**Issue by alimtunc** [nvim-telescope/telescope.nvim#2581]
### Description

Hi, I've just updated all my packages, and i've got this issue now. File browser is not focused on startup.. looks like is on conflict with Neovim-tree. When I disabled it, it's working. I've searched on Issues of Telespoce repo's and Tree repo's, couldn't find a solution. 

With Tree : 

https://github.com/nvim-telescope/telescope.nvim/assets/18298759/6f66cb61-2974-4c04-a794-07da51e7c15c

Without Tree :

https://github.com/nvim-telescope/telescope.nvim/assets/18298759/a9a032f1-9ee3-4aa0-b662-0c800516256d

### Neovim version

```markdown
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOs 13.4

### Telescope version / branch / rev

1.0.2:

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `file_browser` ~
- No healthcheck provided
```

### Steps to reproduce

Just add this to telescope setup

telescope.setup {
	extensions = {
		file_browser = {
			initial_mode = "insert",
			-- disables netrw and use telescope-file-browser in its place
			hijack_netrw = true,
		},
	},
}

### Expected behavior

Enter in insertion mode on file browser on startup

### Actual behavior

File browser showing, but not it isn't on insertion mode, need to launch it manually again

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
     {
	'nvim-tree/nvim-tree.lua',
	requires = { 'nvim-tree/nvim-web-devicons' }
     }

      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
I'm not sure why you would want both telescope-file-browser and nvim-tree open at the same time. Since the `hijack_netrw` option for both are trying to do pretty much the exact same thing, them not interacting nicely is no surprise. There's more unintended behaviors when doing `:Ex` or `:e some_directory/`.

I'm sorry but I don't know if this worth investigating much further. My recommendation is to disable `hijack_netwr` on one of them.

**Comment by alimtunc** [comment]
> I'm not sure why you would want both telescope-file-browser and nvim-tree open at the same time. Since the `hijack_netrw` option for both are trying to do pretty much the exact same thing, them not interacting nicely is no surprise. There's more unintended behaviors when doing `:Ex` or `:e some_directory/`.
> 
> I'm sorry but I don't know if this worth investigating much further. My recommendation is to disable `hijack_netwr` on one of them.

Ok, I got it. Sorry, I'm pretty new on Neovim ecosystem. What I want to achieve, is to have the file browser open at startup and have the Tree open when I choosed a file. The thing is, it was working pretty well before the update. That's why, now I'm confused of how things work. 

Do you have any suggestion of how could I toggle NvimTree when I open a file from Telescope? Would appreciate! Thank you

**Comment by jamestrew** [comment]
Yeah no worries, I think what you've described is a fair use case.

I think something like this should work (pretty non-elegant and there's probably a better way but...)
```lua
require("telescope").setup({
  extensions = {
    file_browser = {
      initial_mode = "insert",
      hijack_netrw = true,
      mappings = {
        i = {
          ["<CR>"] = function(prompt_bufnr)
            require("telescope.actions").select_default(prompt_bufnr)
            local entry = require("telescope.actions.state").get_selected_entry()
            if
              entry
              and not entry.Path:is_dir()
              and not require("nvim-tree.api").tree.is_visible()
            then
              vim.cmd(":NvimTreeOpen")
              vim.cmd.e(entry.path)
            end
          end,
        },
      },
    },
  },
})

```
