### ISSUE TITLE
UI animation get stuck when find files on super large project even with fzf-native

### ISSUE THREAD

**Issue by linrongbin16** [nvim-telescope/telescope.nvim#2588]
**Is your feature request related to a problem? Please describe.**

Hi, I am using telescope with fzf-native extension, but in my super large project, that belongs to the company I am working for, it still get stuck on finding files.

The counting number on right side of prompt animation will have a slightly delay, compared with fzf.vim.

A good test case is https://github.com/torvalds/linux.

**Describe the solution you'd like**

Hope there is a way to integrate fzf binary directly into telescope.

**Comment by jamestrew** [comment]
Yeah depending on hardware and the project, telescope might struggle a bit.

> Hope there is a way to integrate fzf binary directly into telescope.

You might want to check out [fzf-lua](https://github.com/ibhagwan/fzf-lua) which does this. There are pros and cons to the way telescope does things but if you're looking for speed, fzf-lua would be hard to beat :rocket:
