### ISSUE TITLE
Chatroom?

### ISSUE THREAD

**Issue by clason** [nvim-telescope/telescope.nvim#259]
We're getting more and more questions about telescope on Gitter; it might be a good idea to have a dedicated chatroom -- either on Gitter or Zulip (or Element?), although I think Gitter is best due to not requiring signup and github integration.

**Comment by tami5** [comment]
Gitter seems to be a great option. I think we should wait on @tjdevries to set it up

**Comment by tjdevries** [comment]
Yeah, I'd say probably gitter or discord -- I don't really need any more chat applications in my life :laughing: 

Gitter probably makes the most sense. I don't know that I have a strong preference though. Anyone interested in chat rooms that has ideas about bridges or something else to connect a few places?

**Comment by clason** [comment]
I vote Gitter, for the stated reasons (and expecting good things from Matrix integration). 

(Neovim itself already has too many...)
