### ISSUE TITLE
Add a feature to builtin branches to compare a file

### ISSUE THREAD

**Issue by rostero1** [nvim-telescope/telescope.nvim#2592]
**Is your feature request related to a problem? Please describe.**
I find it extremely useful to compare a file against an older revision (or branch).  I have a <leader>gf mapped to have fugitive open the file file in a new vertical split at the branch I specified in `input`.

**Describe the solution you'd like**
I want to add this to Telescope, since it has the ability to list (and filter on) all branches.  I would love to see 

```
---   - `<C-s>`: compare a file to the selected branch in a new vertical split.
```

**Describe alternatives you've considered**
Writing my own plugin.  Or keeping the hotkey with `input` instead of listing the branches.

**Comment by jamestrew** [comment]
I don't think this feature belongs telescope but you can do is write a small custom action for the `git_branches` picker that will show the diff between the current branch and the selected branch for the current file.

Maybe something like this
```lua
local diffsplit = function(prompt_bufnr)
  local entry = action_state.get_selected_entry()
  actions.close(prompt_bufnr)
  vim.cmd(string.format(":Gdiffsplit %s", entry.name))
end
```

then bind it as a new keymapping on `git_branches`.

**Comment by rostero1** [comment]
That worked great.  Thanks for the tip.  And I agree. 

I did note that the docs are missing `<C-s>` for `git_branches`.  It seems to be mapped to switch branches.  Also, it would be nice if switch branches (`<cr>` or `<C-s>`) had the ability to be configured with a confirm.
