### ISSUE TITLE
Feature Request: Option to disable check for git cwd

### ISSUE THREAD

**Issue by Subjective** [nvim-telescope/telescope.nvim#2595]
**Is your feature request related to a problem? Please describe.**
Hi. I'm trying to configure a keymap that will allow telescope to search the git commits of a bare repo with a detached working tree (my dotfiles). However, the command I set keeps failing because my current working directory is not a git dir so it fails the check:
```lua
-- telescope.nvim/lua/telescope/builtin/__git.lua

if in_worktree[1] ~= "true" and in_bare[1] ~= "true" then
  error(opts.cwd .. " is not a git directory")
  elseif in_worktree[1] ~= "true" and in_bare[1] == "true" then
    opts.is_bare = true
end
```

Initializing a git repo in my home directory solves this issue, but that is far from ideal and causes other issues.

<details>
<summary>Telescope Command</summary>

```lua
require("telescope.builtin").git_commits {
  cwd = vim.env.HOME,
  git_command = {
    "git",
    "--git-dir",
    vim.env.HOME .. "/.cfg/",
    "--work-tree",
    vim.env.HOME,
    "log",
    "--pretty=oneline",
    "--abbrev-commit",
    "--",
    ".",
  },
}
```

</details>

<details>
<summary>Error Message</summary>

```
E5108: Error executing lua: ...nvim/lazy/telescope.nvim/lua/telescope/builtin/__git.lua:380: /Users/joshua is not a git directory
stack traceback:
[C]: in function 'error'
...nvim/lazy/telescope.nvim/lua/telescope/builtin/__git.lua:380: in function 'set_opts_cwd'
...nvim/lazy/telescope.nvim/lua/telescope/builtin/__git.lua:396: in function 'v'
.../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:533: in function 'git_commits'
.../joshua/.config/astronvim/lua/user/plugins/telescope.lua:58: in function <.../joshua/.config/astronvim/lua/user/plugins/telescope.lua:57>
```
</details>

**Describe the solution you'd like**
Would it be possible to add an option to disable that check? Or perhaps optionally set the work-tree and git directory for the command?

**Describe alternatives you've considered**
Previously, I wrote the following autocmd to help configure git integration for most plugins:

<details>
<summary>Autocmd</summary>

```lua
autocmd({ "BufEnter" }, {
  desc = "Configure git integration when editing dotfiles",
  group = augroup("dotfiles_git", { clear = true }),
  pattern = { "*" },
  callback = function(args)
    local filename = vim.api.nvim_buf_get_name(0)
    if filename == "" or vim.api.nvim_get_option_value("buftype", { buf = args.buf }) == "nofile" then return end

    local home_dir = vim.env.HOME

    if
      utils.cmd({
        "git",
        "--work-tree",
        home_dir,
        "--git-dir",
        home_dir .. "/.cfg",
        "ls-files",
        "--error-unmatch",
        filename,
      }, false)
    then
      vim.env.GIT_DIR = home_dir .. "/.cfg"
      vim.env.GIT_WORK_TREE = home_dir
      utils.if not is_available "gitsigns" then pcall(require, "gitsigns") end
    else
      vim.env.GIT_DIR = nil
      vim.env.GIT_WORK_TREE = nil
    end
  end,
})
```
</details>

But I didn't really like the idea of running a check to set the `GIT_DIR` and `GIT_WORK_TREE` environment variables each time I switch buffers, especially since `gitsigns` (my main usecase) already provides a configuration option to enable git integration for detached worktrees: https://github.com/lewis6991/gitsigns.nvim/pull/600. 

Another potential solution derived from `gitsigns` might be to allow the user to provide a list of detached git worktrees, and set the `--work-tree` and `--git-dir` arguments for the git commands based on whether the file opened in the current buffer is in one of those worktrees.

Example:
```lua
worktrees = {
  {
    toplevel = vim.env.HOME,
    gitdir = vim.env.HOME .. '/projects/dotfiles/.git'
  }
}
```

**Additional context**
A second related issue that occurs when overcoming this one is that the previewer doesn't inherit the same arguments for `--git-dir` and `--work-tree` when running git diffs, which prevents the diffs from being displayed properly even when the commits are shown and searchable.

![Screen Recording 2023-07-06 at 9 45 40 PM](https://github.com/nvim-telescope/telescope.nvim/assets/56745535/f82c1e1a-7673-4832-b338-3484f283d110)

**Comment by jamestrew** [comment]
Hey thanks for the request.
I think doing something akin to what gitsigns does (having a table for worktrees) would be a more appropriate fix over simply having an option to disable the git root check.

This should allow users to use the git related pickers with detached working trees without needed to write a workaround `git_command` for each picker to set `GIT_DIR` and `GIT_WORK_TREE`. It should also help with the previewer not showing contents. This latter issue you're showcasing in the gif I think has a workaround by passing `use_git_root = false` as an option but it's still not ideal since it looks like you're forced into creating a git repo in $HOME.

I'll see what I can do.
