### ISSUE TITLE
[Feature request] Add option to oldfiles to decide what cwd is taken for cwd_only

### ISSUE THREAD

**Issue by towry** [nvim-telescope/telescope.nvim#2598]
**Is your feature request related to a problem? Please describe.**
In monorepo project, I use `project.nvim` plugin to manage the cwd, so in buffer `projectA/bufferA`, the cwd is `${monorepo}/projectA`, in buffer `projectB/bufferB`, the cwd is `${monorepo}/projectB`. This is very convenient if I just want to search inside a project instead of the big monorepo.

But for oldfiles, I'd like to list all rencent files inside the monorepo.

The current telescope oldfiles's cwd_only behavior is that it will only list files that decide by `vim.loop.cwd`, see [this](https://github.com/nvim-telescope/telescope.nvim/blob/276362a8020c6e94c7a76d49aa00d4923b0c02f3/lua/telescope/builtin/__internal.lua#L533C61-L533C61):

```lua
if opts.cwd_only or opts.cwd then
    local cwd = opts.cwd_only and vim.loop.cwd() or opts.cwd
```

My current dirty solution is to override the `vim.loop.cwd` temporarily like this:

```lua
    local vim_cwd_fn = vim.loop.cwd
    if opts.cwd_only and opts.cwd then
      vim.loop.cwd = function()
        return opts.cwd
      end
    end
    pcall(function()
      require('telescope.builtin').oldfiles(opts)
    end)
    vim.loop.cwd = vim_cwd_fn
```

**Describe the solution you'd like**
Add extra option to oldfiles picker let user decide what cwd value is used or to make `cwd_only` option more extensible.

**Describe alternatives you've considered**
no
**Additional context**
no

**Comment by jamestrew** [comment]
I don't think this is necessary as a builtin feature.
You can write a little wrapper to check if your cwd is inside your monorepo and set the `opts.cwd` accordingly.

This is very inelegant but something like this should work
```lua
M.oldfiles = function(opts)
  opts = opts or {}
  local cwd = vim.loop.cwd()
  local my_mono_repo_dir = "/home/user/my_mono_repo_dir"

  if cwd == my_mono_repo_dir then
    opts.cwd = my_mono_repo_dir
  end

  for dir in vim.fs.parents(cwd) do
    if dir == my_mono_repo_dir then
      opts.cwd = my_mono_repo_dir
      break
    end
  end
  require("telescope.builtin").oldfiles(opts)
end
```

And this can be expanded to work with a table of directories as well.

**Comment by towry** [comment]
> I don't think this is necessary as a builtin feature. You can write a little wrapper to check if your cwd is inside your monorepo and set the `opts.cwd` accordingly.
> 
> This is very inelegant but something like this should work
> 
> ```lua
> M.oldfiles = function(opts)
>   opts = opts or {}
>   local cwd = vim.loop.cwd()
>   local my_mono_repo_dir = "/home/user/my_mono_repo_dir"
> 
>   if cwd == my_mono_repo_dir then
>     opts.cwd = my_mono_repo_dir
>   end
> 
>   for dir in vim.fs.parents(cwd) do
>     if dir == my_mono_repo_dir then
>       opts.cwd = my_mono_repo_dir
>       break
>     end
>   end
>   require("telescope.builtin").oldfiles(opts)
> end
> ```
> 
> And this can be expanded to work with a table of directories as well.

This won't work, because it's not about the opts.cwd, it is about oldfiles is using `vim.uv.cwd()`, it won't use opts.cwd.

**Comment by towry** [comment]
The `vim.uv.cwd()` is managed by other plugins and works great, but for oldfiles since it always use `vim.uv.cwd()`, there is no chance to make it use different cwd value other than `vim.uv.cwd()` without change the actual cwd.

**Comment by jamestrew** [comment]
I'm confused.

oldfiles only uses `vim.uv.cwd()` if `opts.cwd_only = true`. If you pass `opts.cwd`, if will use the given cwd.
```lua
 local cwd = opts.cwd_only and vim.loop.cwd() or opts.cwd
```

With my snippet, I can open two windows and set the cwd in each of them using `lcd` to somewhere inside `/home/user/my_mono_repo_dir` (eg. `/home/user/my_mono_repo_dir/projectA` and `/home/user/my_mono_repo_dir/projectB`) and oldfiles will use `/home/user/my_mono_repo_dir` as the cwd and show files in that directory.

This is the behavior you're looking for right or am I missing something?

**Comment by towry** [comment]
@jamestrew You are right, my misread. sorry for the fuss. I can set cwd_only = false and use opts.cwd to archive this.
