### ISSUE TITLE
Put the '<cword>' in the live_grep_args() input and launch a search by default

### ISSUE THREAD

**Issue by weiyshay** [nvim-telescope/telescope.nvim#2600]
**Is your feature request related to a problem? Please describe.**
It is likely to search the 'cword' or related in live_grep_args() by default and it is annoying to input them manually everytime.
Particularily when the word is a long one. It is good to have them in the 'Picker' by default.

**Describe the solution you'd like**
Put the 'cword' to the 'Picker' by default and launch an initial search.

**Describe alternatives you've considered**
N/A

**Additional context**
 I have patched a bit and the function works but the 'cword' is not in the fzf input with the change.

```
diff --git a/lua/telescope/pickers.lua b/lua/telescope/pickers.lua
index 874789f..bff5813 100644
--- a/lua/telescope/pickers.lua
+++ b/lua/telescope/pickers.lua
@@ -338,6 +338,8 @@ end
 --- Opens the given picker for the user to interact with
 ---@note: this is the main function for pickers, as it actually creates the interface for users
 function Picker:find()
+  local prompt = vim.fn.expand("<cword>")
+    print(prompt)
   self:close_existing_pickers()
   self:reset_selection()

@@ -460,11 +462,8 @@ function Picker:find()
     -- https://github.com/neovim/neovim/commit/cbf9199d65325c1167d7eeb02a34c85d243e781c
     self:_reset_prefix_color()

     while true do
-      -- Wait for the next input
-      rx.last()
-      await_schedule()
-
       self:_reset_track()

       if not vim.api.nvim_buf_is_valid(prompt_bufnr) then
@@ -474,7 +473,8 @@ function Picker:find()

       local start_time = vim.loop.hrtime()

-      local prompt = self:_get_next_filtered_prompt()

       -- TODO: Entry manager should have a "bulk" setter. This can prevent a lot of redraws from display
       if self.cache_picker == false or self.cache_picker.is_cached ~= true then
@@ -501,6 +501,9 @@ function Picker:find()
         -- TODO(scroll): This can only happen once, I don't like where it is.
         self:_resume_picker()
       end
+      rx.last()
+      await_schedule()
+      prompt = self:_get_next_filtered_prompt()
     end
   end)

```
cword 'prompt_title':
<img width="1073" alt="图片" src="https://github.com/nvim-telescope/telescope.nvim/assets/99458445/73249f04-95fc-4293-93aa-e137624f1175">

live_grep_args gets the result of 'cword' but not in the input box:
<img width="1915" alt="图片" src="https://github.com/nvim-telescope/telescope.nvim/assets/99458445/19f19154-dac1-45b8-a334-b3be96b9b63c">

**Comment by jamestrew** [comment]
If this request is specific to live-grep-args, you probably want to open an issue there instead.

If you want to grep for cword, you can already do this with the grep_string picker.

If you want a similar feature in live-grep-args, take a look at the grep_word_under_cursor shortcut in their readme.

**Comment by weiyshay** [comment]
Good to know. Thank you very much! James.
