### ISSUE TITLE
Add preview scroll by line option

### ISSUE THREAD

**Issue by fent** [nvim-telescope/telescope.nvim#2602]
**Is your feature request related to a problem? Please describe.**
Hello, I would like to scroll the previewer by a little bit sometimes, as little as one line that I'd like to map to `ctrl-e` and `ctrl-y`

**Describe the solution you'd like**
I would like  `require("telescope.actions").preview_scrolling_down()` and  `require("telescope.actions").preview_scrolling_down()` to take an optional argument with the amount of lines to scroll.

**Describe alternatives you've considered**
I have considered dealing with scrolling half a page

**Comment by jamestrew** [comment]
I'm on my phone so I can't point you to the exact resource right now but I do believe there's something like a `scroll_speed` option, possibly under the layout config if I'm remembering correctly, that might be something close to what you're looking for.

Let me know if you can't find it/get it to work. I can come back here later again when I'm on my desktop.

**Comment by fent** [comment]
thanks! found the setting, but i'd also like to keep the default `ctrl-d`/`ctrl-u` mapping to scroll half the page. i have the following but scrolling by one line is not working 

```lua
          ["<C-d>"] = function(bufnr)
            require("telescope.state").get_status(bufnr).picker.layout_config.scroll_speed = nil
            return require("telescope.actions").preview_scrolling_down(bufnr)
          end,
          ["<C-u>"] = function(bufnr)
            require("telescope.state").get_status(bufnr).picker.layout_config.scroll_speed = nil
            return require("telescope.actions").preview_scrolling_up(bufnr)
          end,
          ["<C-e>"] = function(bufnr)
            require("telescope.state").get_status(bufnr).picker.layout_config.scroll_speed = 1
            return require("telescope.actions").preview_scrolling_down(bufnr)
          end,
          ["<C-y>"] = function(bufnr)
            require("telescope.state").get_status(bufnr).picker.layout_config.scroll_speed = 1
            return require("telescope.actions").preview_scrolling_up(bufnr)
          end,
```

**Comment by jamestrew** [comment]
If you want both scrolling speeds, it might be easier to write your own custom slow scrolling action. Something like this:
```lua
  local state = require("telescope.state")
  local action_state = require("telescope.actions.state")

  local slow_scroll = function(prompt_bufnr, direction)
    local previewer = action_state.get_current_picker(prompt_bufnr).previewer
    local status = state.get_status(prompt_bufnr)

    -- Check if we actually have a previewer and a preview window
    if type(previewer) ~= "table" or previewer.scroll_fn == nil or status.preview_win == nil then
      return
    end

    previewer:scroll_fn(1 * direction)
  end

  require("telescope").setup({
    defaults = {
      mappings = {
        i = {
          ["<C-e>"] = function(bufnr) slow_scroll(bufnr, 1) end,
          ["<C-y>"] = function(bufnr) slow_scroll(bufnr, -1) end,
        },
      },
    },
  })
```

**Comment by fent** [comment]
that works! thanks!

**Comment by fent** [comment]
should this issue be kept open? an easier method to do this may be preferable. what about scrolling by page? by default `<ctr-d>` and `<ctrl-u>` scroll by half a page. but there's no easy way to configure a full page scroll

**Comment by jamestrew** [comment]
I think we can close this.
I don't think there a ton of demand to have various scrolling speeds so while it wouldn't be difficult to add some new action with an option for scroll speeds, I'm not sure if it's necessary. The snippet above should be good enough at least for now.

If you wanted to also scroll by full page, you can do
```lua
  local full_page_scroll = function(prompt_bufnr, direction)
    local previewer = action_state.get_current_picker(prompt_bufnr).previewer
    local status = state.get_status(prompt_bufnr)

    -- Check if we actually have a previewer and a preview window
    if type(previewer) ~= "table" or previewer.scroll_fn == nil or status.preview_win == nil then
      return
    end

    local speed = vim.api.nvim_win_get_height(status.preview_win)
    previewer:scroll_fn(speed * direction)
  end

**Comment by muhfaris** [comment]
> should this issue be kept open? an easier method to do this may be preferable. what about scrolling by page? by default `<ctr-d>` and `<ctrl-u>` scroll by half a page. but there's no easy way to configure a full page scroll

thank you @fent
