### ISSUE TITLE
prompt: can not delete typed text in insert mode (after previously in normal mode)

### ISSUE THREAD

**Issue by doubleloop** [nvim-telescope/telescope.nvim#261]
# Steps to reproduce:

minimal vimrc:
```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-lua/telescope.nvim'
call plug#end()
```
```sh
$ vim -u testrc.vim +"Telescope find_files"
```
type something (ex "foo") in prompt field, press `<esc>` for normal mode  then `a` to insert again. Then try to delete typed text (`backspace` or `c-w`). It does not work. Type further (ex "bar"). Then remove with backspace (without switching to normal mode). You can remove only second part ("foobar" -> "foo") but first part can not be removed (unless you go to normal mode and use some normal mode deletion like `S` or `dbw`)

**Comment by tjdevries** [comment]
Yeah, I believe this is an issue with prompt buffers. I think the bug report should go to neovim/neovim if there isn't one there already. My guess is that we're missing some patches :/ I have experienced the same thing.

**Comment by mah-shee** [comment]
I suppose this issue is related to https://github.com/neovim/neovim/issues/13715  FYI

**Comment by Conni2461** [comment]
This issue is fixed in the latest neovim master: neovim/neovim#16421. Its not part of the 0.6 release
