### ISSUE TITLE
Telescope builtin: prompt in normal mode instead of insert mode

### ISSUE THREAD

**Issue by doubleloop** [nvim-telescope/telescope.nvim#262]
after running `:Telescope builtin` and selecting some picker, prompt is in normal mode instead of being in insert mode

**Comment by tami5** [comment]
Yes, I can confirm I have the same issue

**Comment by gary-ruizhang** [comment]
@tami5 I still have this issue. Is this the default behavior and should I config something?

**Comment by sisrfeng** [comment]
I type a character and brought back to normal mode. SO Annoying

**Comment by fdschmidt93** [comment]
Please don't hijack old closed issues that at most relate to your problem in the outcome. The relevant code has changed tremendously tonight.

We're happy to do our best to help you if you open a new issue with a minimal reproduction config.
