### ISSUE TITLE
lsp references file results' lines/columns cannot be searched

### ISSUE THREAD

**Issue by hongxuchen** [nvim-telescope/telescope.nvim#2621]
### Description

It seems that I cannot use the line/columns results of the candidate files for searching when using `telescope.builtin.lsp_references()`.

For example, the results (`show_line = false`) below all reside in the file `IndexCollector.cpp` and I cannot use any line or column numbers (like `657` or `10`) for matching the expected results.

![image](https://github.com/nvim-telescope/telescope.nvim/assets/843267/5d839a5d-a1be-4ff5-8948-7f94b466f0e8)

### Neovim version

```markdown
NVIM v0.10.0-dev-36941942d
Build type: Release
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

### Operating system and version

Ubuntu 22.10

### Telescope version / branch / rev

0.1.2

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `aerial` ~
- No healthcheck provided

Telescope Extension: `file_browser` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `lazy` ~
- No healthcheck provided

Telescope Extension: `live_grep_args` ~
- No healthcheck provided

Telescope Extension: `ui-select` ~
- No healthcheck provided

Telescope Extension: `zoxide` ~
- No healthcheck provided
```

### Steps to reproduce

In an LSP-enabled buffer, for a specific symbol referenced by others, invoke `telescope.builtin.lsp_references()`.

### Expected behavior

File lines/columns can also be used for search.

### Actual behavior

When searching with numbers, all results are gone.

![image](https://github.com/nvim-telescope/telescope.nvim/assets/843267/eeb87899-0c71-49b4-afb5-9b464a753479)

### Minimal config

```Lua
I believe nothing special is configured except I am using `show_line = false`.
```

**Comment by jamestrew** [comment]
This is actually the intended behavior and sadly at the moment, we don't support an option to include the line/col numbers for matching.

The `lsp_references` picker uses the `gen_from_quickfix` entry maker (the thing that makes each entry in the results). The `ordinal` value is what's match-able while the `display` value is what's actually displayed (`:h telescope.make_entry`).
You could achieve your desired behavior by writing a custom entry maker, borrowing heavily from `gen_from_quickfix` and just adding the line/col numbers to the `ordinal` value.
https://github.com/nvim-telescope/telescope.nvim/blob/776b509f80dd49d8205b9b0d94485568236d1192/lua/telescope/make_entry.lua#L488

Then you can call `require('telescope.builtin').lsp_references({ show_line = false, entry_maker = my_custom_from_quickfix })`.

PR is also welcome.

**Comment by hongxuchen** [comment]
Thank you so much for your explanation! I will read the docs and try to customize `ordinal`.
