### ISSUE TITLE
lsp references with only one candidate should jump directly

### ISSUE THREAD

**Issue by hongxuchen** [nvim-telescope/telescope.nvim#2624]
### Description

`telescope.builtin.lsp_references()` seems always suppose there are >1 candidates when called. However when `include_declaration = false` is set, there might only be 1 candidate, in which scenario the behavior should jump directly to the reference. 

### Neovim version

```markdown
NVIM v0.10.0-dev-36941942d
Build type: Release
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

### Operating system and version

Ubuntu 22.10

### Telescope version / branch / rev

0.1.2

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `aerial` ~
- No healthcheck provided

Telescope Extension: `file_browser` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `lazy` ~
- No healthcheck provided

Telescope Extension: `live_grep_args` ~
- No healthcheck provided

Telescope Extension: `todo-comments` ~
- No healthcheck provided

Telescope Extension: `ui-select` ~
- No healthcheck provided

Telescope Extension: `zoxide` ~
- No healthcheck provided
```

### Steps to reproduce

* Configure with `include_declaration = false`.
* In an LSP-enabled buffer, for a specific symbol who has only one reference other than the declaration/definition itself, invoke `telescope.builtin.lsp_references()`.

### Expected behavior

Jump directly to the reference.

### Actual behavior

Popup the picker window.

### Minimal config

```Lua
Nothing special except `include_declaration = false`.
```

**Comment by jamestrew** [comment]
Can you share an example code snippet where this happens? I've tried to few scenarios but I'm not able to replicate.

**Comment by hongxuchen** [comment]
@jamestrew as the example shown below, `var` is only used only once and applying `telescope.builtin.lsp_references()` on either line 1 or line3 only emits one candidate which is at line 3 since I set `include_declaration = false`.
![image](https://github.com/nvim-telescope/telescope.nvim/assets/843267/59a4f361-2fba-40a0-b9b7-d51a77e46070)

**Comment by jamestrew** [comment]
Thanks, you're right but it looks like this is fixed/implemented on the master branch

**Comment by hongxuchen** [comment]
Oh yes, thanks!

**Comment by ninjarogue** [comment]
@jamestrew LSP Definitions could be improved to jump directly to a definition when there is only one match. Currently, even with a single match, it still opens the Telescope picker, which feels like an unnecessary extra step. It would be better if LSP Definitions skipped the picker and went straight to the definition when there is unambiguously only one result.

**Comment by jamestrew** [comment]
@ninjarogue that's the intended design. If you can replicate this on the master branch then it is a bug, please create an issue showing how to replicate.

**Comment by ninjarogue** [comment]
@jamestrew Sure, I'll try to find some time to replicate it on the master branch. Seems like it's only happening with the React functional components though, not the hooks or regular functions:

<img width="1908" alt="Screen Shot 2024-03-28 at 11 13 21 AM" src="https://github.com/nvim-telescope/telescope.nvim/assets/74705062/de54db8d-7622-40f8-be77-78d7a02e7fe3">

**Comment by dsully** [comment]
This happens in Lua as well.

**Comment by jamestrew** [comment]
@dsully please open a bug report with clear instructions to replicate it

**Comment by ArbitRandomUser** [comment]
can this be made optional ? i would still prefer to not jump to the definition on a single result.

i sometimes need to look at the function in a cursory manner, and the preview suffices.
