### ISSUE TITLE
Telescope buffers input focus is not in insert mode

### ISSUE THREAD

**Issue by shanesaravia** [nvim-telescope/telescope.nvim#2626]
### Description

If you run the command "Telescope buffers", im unable to type. i have to hit a key to put me into insert mode to then start typing. This is unlike the behaviour in any other Telescope windows.

### Neovim version

```markdown
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.5

### Telescope version / branch / rev

Sorry, not sure how to figure this out. im on Lunarvim using Lazy.nvim

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `projects` ~
- No healthcheck provided
```

### Steps to reproduce

I originally found this using which-key with: 
`{ "<cmd>Telescope buffers previewer=false<cr>", "Find"  }`
however if i run the command directly:
`:Telescope buffers`
and then hit enter, it opens the telescope floating window, but im unable to type without hitting an extra key to go into insert mode.

### Expected behavior

Id expect to be able to start typing right away like every other Telescope window behaves

### Actual behavior

Unable to type unless i hit "i" or "a" etc to go into insert mode first

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
I think this is just default config that lunarvim has set for the buffers picker
https://github.com/LunarVim/LunarVim/blob/d663929036e23bd54427cf3e78dedf5b34ab97fc/lua/lvim/core/telescope.lua#L79

I have no knowledge on how to configure lunarvim but from telescope's standpoint, you just set `initial_mode = "insert"`.

**Comment by shanesaravia** [comment]
You're completely right, sorry still new to the nvim world. Thank you for pointing that out. It's working as expected now!
