### ISSUE TITLE
Tag searching has become an order of magnitude slower since release tag 0.1.2

### ISSUE THREAD

**Issue by benstaniford** [nvim-telescope/telescope.nvim#2627]
### Description

I use a 32Mb tag file and recently updated to the very latest telescope commit.  I noticed a huge drop in performance when searching for tags.  After digging around for a bit I noticed that I should be on the release tag 0.1.2. 

In 0.1.2, my tag window loads in 5 seconds and I can start typing.
On commit b6fccfb, my tag window loads in 44 seconds.

Here's some gifs showing 0.1.2 vs latest master

![0 1 2](https://github.com/nvim-telescope/telescope.nvim/assets/1592786/45fc43a7-36c0-4dba-bbca-49f1d94bbbd8)
![master](https://github.com/nvim-telescope/telescope.nvim/assets/1592786/831f91b5-602f-42c3-93f6-5544135a1af0)

### Neovim version

```markdown
NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 10 22H2

### Telescope version / branch / rev

b6fccfb

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 11.0.2 (rev 3de31f7527)
- OK fd: found fd 8.4.0

===== Installed extensions =====
```

### Steps to reproduce

* Load a 32Mb tag file
* Run :Telescope tags
* Time how long for the item counter to finish counting so you can start typing

### Expected behavior

Previously took 5s

### Actual behavior

Now takes 44s

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Thanks for the bug report.
Can you check for me whether this commit is the culprit https://github.com/nvim-telescope/telescope.nvim/commit/6074847b6ee4b725747c8fc540d9b6b128ac8a12 (PR: https://github.com/nvim-telescope/telescope.nvim/pull/2583)?

**Comment by benstaniford** [comment]
@jamestrew Yep, it definitely is.  Performance is fine on 219584a but becomes extremely slow on 6074847.
