### ISSUE TITLE
Make LSP diagnostics sort by severity

### ISSUE THREAD

**Issue by theniceboy** [nvim-telescope/telescope.nvim#2631]
Currently `builtin.diagnostics` shows diagnostic in a somewhat random order. I would really like it to sort the items based on severity first. From [here](https://github.com/nvim-telescope/telescope.nvim/blob/d2e17ba18a6840b7e7079764b282616c3188e0de/lua/telescope/builtin/init.lua#L524) I could only find options to limit items with certain severity levels. Is there a way to show all items and sort them by severity? Thanks!

<img width="1092" alt="Screenshot 2023-08-03 at 8 12 11 PM" src="https://github.com/nvim-telescope/telescope.nvim/assets/8187501/a8a19fef-89b6-4aa1-a996-21efff2e76c0">

### Related issue
#846 was closed by #867 however the issue was not fixed.

**Comment by jamestrew** [comment]
I believe the current behavior is to group by buffer number, order by severity, line number so I think it is working as intended although I can see the desire for it to not group by buffer number and just sort by severity directly.

**Comment by theniceboy** [comment]
Please let me know how #2633 looks
@jamestrew
