### ISSUE TITLE
Better keybindings for scrolling horizontally on Results window

### ISSUE THREAD

**Issue by nnathan** [nvim-telescope/telescope.nvim#2634]
I switched from the 0.1.x branch to master because I would like to use horizontal scrolling of results window. It is unfortunate that the defaults are mapped to `<M-f>` and `<M-k>` for scrolling horizontally as I use a Mac and the meta key doesn't come naturally in my terminal (I feel this is the case for a lot of people though otherwise I wouldn't raise a feature request).

I would like for a reconsideration of those keybindings to use accessible keys and modifiers like the C-mappings.

An alternative that could be considered is using `<C-a>` for scrolling left and `<C-e>` for scrolling right. It may not be the best choice but it appears ergonomic.

Thank you, <3 telescope.nvim.

**Comment by jamestrew** [comment]
You can remapping any of the pre-existing actions to your desire mapping, specifically in this case like this
```lua
require("telescope").setup({
  defaults = {
    -- .. other settings
    mappings = {
      i = {
        ["<C-a>"] = actions.results_scrolling_left,
        ["<C-e>"] = actions.results_scrolling_right,
      }
    }
  }
})
```

**Comment by gitdexgit** [comment]
> You can remapping any of the pre-existing actions to your desire mapping, specifically in this case like this
> 
> require("telescope").setup({
>   defaults = {
>     -- .. other settings
>     mappings = {
>       i = {
>         ["<C-a>"] = actions.results_scrolling_left,
>         ["<C-e>"] = actions.results_scrolling_right,
>       }
>     }
>   }
> })

this key doesn't exist... no such key in telescope


```
Error detected while processing :source buffer=13:
E5108: Error executing lua ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:74: Key does not exist for 'telescope.actions': r
esults_scrolling_left
stack traceback:
        [C]: in function 'error'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:74: in function '__index'
        [string ":source buffer=13"]:76: in main chunk
Press ENTER or type command to continue

```

**Comment by jamestrew** [comment]
@DexGith make sure you're on the master branch

**Comment by gitdexgit** [comment]
@jamestrew I'm new to github I don't know what you are talking about

**Comment by jamestrew** [comment]
@DexGith it's not really a GitHub thing. In your telescope installation config, don't use any "tag" or "branch" value. You'll have to read the documentation for the neovim plugin manager you use.

**Comment by gitdexgit** [comment]
> [@DexGith](https://github.com/DexGith) it's not really a GitHub thing. In your telescope installation config, don't use any "tag" or "branch" value. You'll have to read the documentation for the neovim plugin manager you use.

my bad I had tag 1.x

thanks a lot @jamestrew
