### ISSUE TITLE
Preselect current buffer when launching git_status picker

### ISSUE THREAD

**Issue by mfilej** [nvim-telescope/telescope.nvim#2642]
**Is your feature request related to a problem? Please describe.**
For convenience, I would like the current buffer to be preselected when opening the `git_status` picker (if applicable). This would allow for having a quick way to stage the current file, for example.

**Describe the solution you'd like**
The `file_browser` picker allows specifying the option `select_buffer = true`.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by mfilej** [comment]
Thanks! I'm happy to try this out for a while and see if there are any downsides to having it as the default.

I'm sorry if this should be obvious, but where do I put the above function? I'm assuming it goes under
```lua
      pickers = {
        git_status = {
```
but under which key?

**Comment by jamestrew** [comment]
For personal use, you would do something like this
```lua
local my_git_status = function(opts)
  opts = opts or {}
  local buf_path = vim.api.nvim_buf_get_name(0)
  opts.on_complete = {
    function(self)
      local selection_idx
      for i, entry in ipairs(self.finder.results) do
        if buf_path == entry.path then
          selection_idx = i
          break
        end
      end
      self:set_selection(self:get_row(selection_idx))
    end,
  }
  require("telescope.builtin").git_status(opts)
end
```

Then bind a key to this function.
With this above snippet, I don't know if there's a need to add a new option to achieve this. Open to reconsider if there's more demand for it.

**Comment by mfilej** [comment]
Works like a charm! I agree, I'm happy with a custom function. Thank you very much!
