### ISSUE TITLE
Add an ability to open direct location

### ISSUE THREAD

**Issue by dmtrKovalenko** [nvim-telescope/telescope.nvim#2650]
**Is your feature request related to a problem? Please describe.**
I usually deal with direct location output from the compiler which is a path to the file plus the location marker. e.g.

```
my/directory/file.rs:24:4
```

**Describe the solution you'd like**
I want to be able to paste this directly to the telescope, press enter, and appear in the direct symbol location.

> P.S. This is possible in vs code with no additional setup for example

**Describe alternatives you've considered**
1. Open telescope search
2. Observe nothing found
3. Remove paths 
4. type :24<CR> to go to the line 

**Additional context**
This should be primarily an input feature — strip out everything that looks like location, search, and when open file focus specific symbol. That's why I think it should be a part of the telescope core and not be solved via plugins. 

If you are interested I can open PR for this

**Comment by gegoune** [comment]
There is https://github.com/lewis6991/fileline.nvim

**Comment by dmtrKovalenko** [comment]
It doesn't actually related because there are a lot of reason why it simply won't work. 

1. You have big monorepo and the compiler output is relative to the child directory then `e` simply will never open direct file while telescope will find it easily
2. There could be different subdirectories. E.g. I want to be able to open one of the `mod.rs` in my subdirectory but I want to choose 
3. i

**Comment by Conni2461** [comment]
there is a PR that somewhat implements this: https://github.com/nvim-telescope/telescope.nvim/pull/2312

it needs a rebase and a little bit of cleaning up but its pretty much good to go.

It doesnt implement column only line_number but imo that should be sufficient
