### ISSUE TITLE
Fuzzy search should start when introducing the first character

### ISSUE THREAD

**Issue by Zeioth** [nvim-telescope/telescope.nvim#2653]
**Is your feature request related to a problem? Please describe.**
[compiler.nvim](https://github.com/Zeioth/compiler.nvim) uses a numeric list to select items. But the search doesn't start until the user writes at least two characters in the search bar.

**For example:** Right now the user has to write "3 + space" to start the fuzzy search. But writing "3" should be enough to filter the item number 3.

![screenshot_2023-08-15_18-13-11_242486364](https://github.com/nvim-telescope/telescope.nvim/assets/3357792/d320401e-33c8-41ed-9ce8-d336246a355f)

**Describe the solution you'd like**
Start searching when the first character is written.

**Describe alternatives you've considered**
A config option, if we don't want this behavior by default.

**Comment by jamestrew** [comment]
Try `conf.generic_sorter` from `require('telescope.config').values`.

I think `get_generic_fuzzy_sorter` is pretty much deprecated and unused internally.

**Comment by Zeioth** [comment]
@jamestrew  I've tried with 

```lua
local sorters =  require('telescope.config').

defaults = {
  sorter = conf.generic_sorter({}),
}
```
But I still need to write at least 2 characters to start the search. I also tried with `file_sorter`, but same.

**Comment by jamestrew** [comment]
Try like this?

![image](https://github.com/nvim-telescope/telescope.nvim/assets/66286082/6b8db813-8566-4547-8a0f-18e6372ce218)

**Comment by Zeioth** [comment]
Oh you mean in the plugin!! I was doing it in my local config, sorry for the misunderstanding. You really went the extra mile helping me there. That worked great. Thank you so much @jamestrew
