### ISSUE TITLE
Allow `layout_stategy` to be a function

### ISSUE THREAD

**Issue by martin-braun** [nvim-telescope/telescope.nvim#2657]
**Is your feature request related to a problem? Please describe.**
My terminal window grows and shrinks as I wish and the horizontal layout is great for full screen terminals, but not for narrow sized full-height terminals. I picked the vertical layout, but it feels like a waste of screen estate when going full screen.

**Describe the solution you'd like**
If I could provide a function on `layout_strategy` that will be evaluated whenever telescope opens, I could simply do this:

```lua
layout_strategy = function() return vim.o.columns > 120 and "horizontal" or "vertical" end,
```

**Describe alternatives you've considered**
I'm staying on `vertical` layout for now, it's not a big deal, but the above solution would be superior. I can only think about a work-around in which I detect size changes of my terminal and re-initialize telescope, but this sounds painful and hacky.

**Comment by jamestrew** [comment]
There is a PR in the works to allow for more custom UIs but you can also accomplish what you're looking for today in a slightly hacky way like so https://github.com/nvim-telescope/telescope.nvim/pull/2572#issuecomment-1650289724

**Comment by martin-braun** [comment]
@jamestrew I think the comment you posted shows how to setup an own layout strategy that will be evaluated once when telescope is setup. The thing I am asking for is to evaluate the layout strategy _every time_ I open telescope, so that my terminal can change in size and the next instance of telescope will take its size into consideration.

**Comment by l-kershaw** [comment]
The method outlined in the linked comment should evaluate the function every time that you open telescope.
You can test this by adding a `print` statement in it somewhere and opening telescope multiple times.

If this isn't working on your end let me know, as evaluating each time is the intended behaviour.

**Comment by martin-braun** [comment]
@jamestrew @l-kershaw Sorry for being so skeptical about this. You were totally right, this worked for me:

```lua
local layout_strategies = require("telescope.pickers.layout_strategies")
layout_strategies.dynamic = function(self, max_columns, max_lines, layout_config)
    if vim.o.columns > 120 then
        return layout_strategies.horizontal(self, max_columns, max_lines, layout_config)
    else
        return layout_strategies.vertical(self, max_columns, max_lines, layout_config)
    end
end

-- layout_strategy = "dynamic"
```

It even evaluates when the window resizes while Telescope is open, I love it. Good job! :)
