### ISSUE TITLE
Show full path when listing files with git_status

### ISSUE THREAD

**Issue by mfilej** [nvim-telescope/telescope.nvim#2658]
**Is your feature request related to a problem? Please describe.**
I would like to see the full path for a file in a git repository when using the `git_status` picker.

**Describe the solution you'd like**
I tried passing `path_display = { "absolute" }` directly to the `git_status()` function or directly to the picker options under `pickers.git_status.path_display`.

I'm thinking that maybe this option does not work with `git_status`? The other pickers like `find_files` that I'm using are already showing me the full path without any additional configuration.

I would be also happy with a solution in the form of a custom picker function.

**Comment by jamestrew** [comment]
Sorry this took so long, it was literally just a one line fix.

**Comment by mfilej** [comment]
@jamestrew No need to apologize! Can confirm that it works, much appreciated!
