### ISSUE TITLE
Opening oldfiles changes current working directory

### ISSUE THREAD

**Issue by yizhenAllen** [nvim-telescope/telescope.nvim#2663]
### Description

After I open neovim from `dir A`, in neovim I run
```lua
:lua print(vim.loop.cwd())
```
and it will print out path of `dirA`.

However, every time after I used `telescope.builtin.oldfiles()` to open any recent file, running the command above prints out `~/.config/nvim`, which is the dir that I used a lot recently, although the file I opened is in `dir A` and not in `~/.config/nvim`.

### Neovim version

```markdown
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.6.7

### Telescope version / branch / rev

telescope 0.1.2

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured
```

### Steps to reproduce

Same as description.

### Expected behavior

Do not change working directory after using `telescope.builtin.oldfiles()` to open any recent file.

### Actual behavior

Working directory changes to a particular directory `~/.config/nvim` after using `telescope.builtin.oldfiles()` to open any recent file, although the file is totally not in `~/.config/nvim`.

### Minimal config

```Lua
-- use lazy.nvim

return{
  'nvim-telescope/telescope.nvim',
  branch = '0.1.x',
  dependencies = {
    'nvim-lua/plenary.nvim',
    {
      'nvim-telescope/telescope-fzf-native.nvim',
      build = 'make',
      cond = function()
        return vim.fn.executable 'make' == 1
      end,
    },
  },
  opts = {},
}
```

**Comment by jamestrew** [comment]
I'm not able to reproduce with the provided config

https://github.com/nvim-telescope/telescope.nvim/assets/66286082/0bfffc69-43c1-4591-ad7d-58ce0cce2605

**Comment by yizhenAllen** [comment]
@jamestrew Thanks! I found where the problem is.

Actually the snippet below which I use to keep the fold view of files would cause the problem I said, it is not a bug of telescope.

```lua
-- auto save fold view after exit a file
vim.api.nvim_create_autocmd({ "BufLeave", "BufWinLeave", "InsertLeave" }, {
	group = augroup("remenber_folds"),
	callback = function()
		vim.cmd("silent! mkview")
	end,
	group = general,
	desc = "save fold view",
})

-- auto load fold view after enter a file
vim.api.nvim_create_autocmd({ "BufRead", "BufWinEnter", "BufEnter", "FocusGained" }, {
	group = augroup("remenber_folds"),
	callback = function()
		vim.cmd("silent! loadview")
	end,
	group = general,
	desc = "load fold view",
})

```

**Comment by yizhenAllen** [comment]
Adding `vim.cmd [[set viewoptions-=curdir]]` to my `options.lua` file perfectly solves the problem.
