### ISSUE TITLE
Results are not displayed when filtering

### ISSUE THREAD

**Issue by petobens** [nvim-telescope/telescope.nvim#2667]
### Description

The results pane stopped showing filtered candidates when filtering results. I need to press `<C-p>` to "re-enable" results display.

### Neovim version

```markdown
NVIM v0.10.0-dev-958+gafd0c648a8
```

### Operating system and version

Arch Linux x86_64

### Telescope version / branch / rev

Latests master

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins
- OK plenary installed.
- WARNING nvim-treesitter not found. (Required for `:Telescope treesitter`.)

Checking external dependencies
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions =====
```

### Steps to reproduce

As in the GIF:
1. Open nvim with the minimal lua file provided below.
2. Run `:Telescope find_files`
3. Start typing some characters to filter the results (in my case `tmu`)
4. Note that after 3. the results pane doesn't display any ouput but there are candidates in the pane. By pressing `C-p` (i.e  moving the cursor) the results re-appear.

![telescope](https://github.com/nvim-telescope/telescope.nvim/assets/2583971/04421e6e-b7b6-4e2c-bdac-485d759e60ec)

### Expected behavior

4. Above

### Actual behavior

3. Above

### Minimal config

```Lua
local root = '/tmp/nvim-minimal'

-- Set stdpaths to use root dir
for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
    vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

-- Bootstrap lazy
local lazypath = root .. '/plugins/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        'git',
        'clone',
        '--filter=blob:none',
        '--single-branch',
        'https://github.com/folke/lazy.nvim.git',
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- Install and configure plugins
local plugins = {
    {
        'nvim-telescope/telescope.nvim',
        dependencies = {
            'nvim-lua/plenary.nvim',
            { 'nvim-telescope/telescope-fzf-native.nvim', build = 'make' },
        },
        config = function()
            require('telescope').setup({})
        end,
    },
}
require('lazy').setup(plugins, {
    root = root .. '/plugins',
})
```

**Comment by jamestrew** [comment]
Looks like this is an upstream nvim core issue like you've already identified but I'll keep this open for visibility purposes.

If anybody's curious, they can try out this PR https://github.com/neovim/neovim/pull/24889 and verify it fixes the issue. I haven't tried it myself but apparently it works.

**Comment by petobens** [comment]
@jamestrew Unfortunately the linked PR hasn't fixed the issue. A change seems to be needed from the telescope side as per https://github.com/neovim/neovim/pull/24889#issuecomment-1694620036 : 

> Unfortunately this means that telescope need to be changed somehow, as to not rely on the previous, self-inconsistent behavior.

**Comment by elliotcourant** [comment]
Sorry if I am piling on; but also experiencing this same issue in `NVIM v0.10.0-dev-970+g63802a1db` with the same symptoms. Pressing `<C-p>` or any key that causes the selection list to re-draw seems to resolve it?

**Comment by jamestrew** [comment]
Yeah it looks like telescope is relying on inconsistent/incorrect behavior in neovim core so with this change upstream, there will need to be changes made on telescope's side to address this.

In the meantime, people can stay on `b641fc3` on neovim to avoid this issue.

**Comment by JuanVqz** [comment]
Just to confirm that checking out to `b641fc3` is working again for me, thanks for sharing it @jamestrew

**Comment by delphinus** [comment]
I usually invest such problems by `git bisect`'ing on neovim source.

```sh
git pull origin master
git bisect origin/master ${two_weeks_ago_commit_I_think_it_was_good}
# build & launch nvim & check it
# if it goes bad
git bisect bad
# if it goes good
git bisect good
# and build & check again until bisecting will be done.
```

**Comment by JuanVqz** [comment]
@Michaelpalacce I build it as well, following [the quick start](https://github.com/neovim/neovim/wiki/Building-Neovim#quick-start)
before the third step, run this `git checkout b641fc3` 
> Remember to cover the requirements!

**Comment by semanticart** [comment]
Telescope is still broken w/ the current Neovim nightly (which includes the PR @jamestrew mentioned).

I can confirm that it only seems to happen when the number of results is smaller than the height of the telescope display.

**Comment by gegoune** [comment]
It works fine for me on latest master (`NVIM v0.10.0-dev-993+gbec13cfca-Homebrew`).

**Comment by jamestrew** [comment]
I think this only affects `sorting_strategy = "descending"`.
I'm very limited in time right now (newborn) so any help/patience is appreciated.

**Comment by semanticart** [comment]
I can confirm that setting `defaults = { sorting_strategy = "ascending" }` does fix the issue.

I can also confirm that the fix in #2679 makes things work for `descending`.

**Comment by semanticart** [comment]
Actually, #2679 doesn't appear to work 100% of the time. I can't see any immediate reason.

I'm sticking with `ascending` for now

**Comment by JuanVqz** [comment]
Just to confirm that `sorting_strategy = "ascending"` works in main branch, thanks @jamestrew

**Comment by TwIStOy** [comment]
> Actually, #2679 doesn't appear to work 100% of the time. I can't see any immediate reason.
> 
> 
> 
> I'm sticking with `ascending` for now

I have updated that pr. You can try it again! It works for me!

**Comment by jotamudo** [comment]
> > Actually, #2679 doesn't appear to work 100% of the time. I can't see any immediate reason.
> > I'm sticking with `ascending` for now
> 
> I have updated that pr. You can try it again! It works for me!

I've just compiled from master and can confirm it works too :)

**Comment by SebastienPingal** [comment]
I had this issue and was struggling, then realised the issue is curently being fixed. 
I'm so gratefull for your work guys. Can't wait :heart:

**Comment by jamestrew** [comment]
I think #2679 is in a good place now as a fix.

Can people give it a try (with `sorting_strategy = "descending"`)?

**Comment by petobens** [comment]
Seems to work! Thanks :)

**Comment by tea0112** [comment]
This happens to the nightly version. Use master branch.

**Comment by stormpat** [comment]
Just updated to nvim 0.10, and also facing this issue. For me its working with
    `sorting_strategy = "descending"`
But not with
    `sorting_strategy = "ascending"`

Possibly related issues:

https://github.com/nvim-telescope/telescope.nvim/issues/840
https://github.com/nvim-telescope/telescope.nvim/issues/2490

**Comment by JustMikey** [comment]
I also updated to 0.10, but even changing the `sorting_strategy` does not fix it for me.

**Comment by Dmitrev** [comment]
@stormpat For me updating the latest version of Telescope fixed it
both strategies work:
https://github.com/nvim-telescope/telescope.nvim/releases/tag/0.1.7
