### ISSUE TITLE
Telescope find files not searching the current directory

### ISSUE THREAD

**Issue by razamd784** [nvim-telescope/telescope.nvim#2668]
### Description

Telescope find files not searching the current directory 
it searches my home directory 
and when I do echo getcwd() it show my home directory what should I do?
<img width="1920" alt="Screenshot 2023-08-27 at 1 05 19 PM" src="https://github.com/nvim-telescope/telescope.nvim/assets/29495505/3d5651fc-aa9c-4238-a697-9e8585741452">
<img width="1920" alt="Screenshot 2023-08-27 at 1 04 27 PM" src="https://github.com/nvim-telescope/telescope.nvim/assets/29495505/4d2ddbf2-7231-4ad2-8059-4b31b05137ae">
<img width="1920" alt="Screenshot 2023-08-27 at 1 04 36 PM" src="https://github.com/nvim-telescope/telescope.nvim/assets/29495505/832cd7c3-bf9b-428f-8ac0-bfb9da58958f">
<img width="1920" alt="Screenshot 2023-08-27 at 1 05 08 PM" src="https://github.com/nvim-telescope/telescope.nvim/assets/29495505/81abb997-9be0-48df-bf75-0d9d7fccb20d">

### Neovim version

```markdown
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.4.1

### Telescope version / branch / rev

telescope 0.1.2

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `projects` ~
- No healthcheck provided
```

### Steps to reproduce

1. cd .config/lvim
2.lvim 
3. f - find file
4. searching = home directory not .config/lvim
5. :q - out of lvim
6. lvim config.lua
7. <leader>f
8. still searching home directory not .config/lvim
9. :echo getcwd()
10. output = Users/muhammadraza

### Expected behavior

1. 

### Actual behavior

cd .config/lvim
2.lvim 
<img width="1920" alt="Screenshot 2023-08-27 at 1 04 27 PM" src="https://github.com/nvim-telescope/telescope.nvim/assets/29495505/b424f99f-dea9-4c46-9861-8a7684381324">

3. f - find file
<img width="1920" alt="Screenshot 2023-08-27 at 1 04 36 PM" src="https://github.com/nvim-telescope/telescope.nvim/assets/29495505/26be4907-0989-4b0a-affb-f59063c45e1c">

4. searching = home directory not .config/lvim
5. :q - out of lvim
6. lvim config.lua
7. :Telescope find_files
8. still searching home directory not .config/lvim
9. :echo getcwd()
<img width="1920" alt="Screenshot 2023-08-27 at 1 05 08 PM" src="https://github.com/nvim-telescope/telescope.nvim/assets/29495505/fe46c0cf-4c89-4cee-97b2-4e9be75be078">

10. output = Users/muhammadraza
<img width="1920" alt="Screenshot 2023-08-27 at 1 05 19 PM" src="https://github.com/nvim-telescope/telescope.nvim/assets/29495505/351a052d-acde-4676-bbeb-aacf5637f70b">

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
This seems like a lunarvim config issue. I won't be able to debug everyone's nvim config so it'd be appreciated and more actionable if the issue is able to be replicated with minimal changes to the minimal config present in the issue template.

Opening an issue with lunarvim or asking for support through their channels (I think they have a discord or something) will probably be best. I don't use lunarvim so I can't help you here.

**Comment by razamd784** [comment]
> This seems like a lunarvim config issue. I won't be able to debug everyone's nvim config so it'd be appreciated and more actionable if the issue is able to be replicated with minimal changes to the minimal config present in the issue template.
> 
> Opening an issue with lunarvim or asking for support through their channels (I think they have a discord or something) will probably be best. I don't use lunarvim so I can't help you here.

Thankyou
