### ISSUE TITLE
Stack trace on latest HEAD

### ISSUE THREAD

**Issue by levouh** [nvim-telescope/telescope.nvim#2670]
### Description

This is pretty much all it gives me:

```
[telescope] [WARN  11:13:57] /home/amasquelier/.local/share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:493: Finder failed with msg:  ...l/share/nvim/lazy/telescope.nvim/lua/telescope/utils.lua:180: attempt to compare nil with number
```

but after bisecting I can verify it only occurs on `1dfa66b845673effc8771f9ebe511bb36a09f560`, while `207285ccec21b69996a4d3bcfa59df35d48610e8` is fine.

### Neovim version

```markdown
v0.10.0-dev-953+g1635c9e75
```

### Operating system and version

Skipping, as likely not necessary. Will add if truly needed.

### Telescope version / branch / rev

1dfa66b845673effc8771f9ebe511bb36a09f560

### checkhealth telescope

```markdown
-- Skipping, as likely not necessary. Will add if truly needed.
```

### Steps to reproduce

1. `require("telescope.builtin").find_files()`

### Expected behavior

No error.

### Actual behavior

Error: 

```[telescope] [WARN  11:13:57] /home/amasquelier/.local/share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:493: Finder failed with msg:  ...l/share/nvim/lazy/telescope.nvim/lua/telescope/utils.lua:180: attempt to compare nil with number```

### Minimal config

```Lua
-- Skipping, as likely not necessary. Will add if truly needed.
```

**Comment by levouh** [comment]
@jamestrew

**Comment by jamestrew** [comment]
Interesting. I'll push a fix later today thanks.
