### ISSUE TITLE
Enable mouse scrolling by default

### ISSUE THREAD

**Issue by andrhua** [nvim-telescope/telescope.nvim#2680]
**Is your feature request related to a problem? Please describe.**
I find default mousewheel scroll behavior confusing, when the buffer behind float window gets scrolled.

**Describe the solution you'd like**
Result and preview windows can be scrolled with mousewheel with no extra configuration required.

**Describe alternatives you've considered**
fzf has this by default

**Comment by cristiansofronie** [comment]
For scrolling he results it could be  done with something like this

```lua
        ['<ScrollWheelUp>'] = actions.move_selection_previous,
        ['<ScrollWheelDown>'] = actions.move_selection_next,
```

This should be added in the default mappings. This should be quite easy to do.

**Comment by cristiansofronie** [comment]
As for the preview window maybe there is a simple solution also. If not there is the hard solution with vim.fn.getmousepos() to get the position of the mouse and see if it is over the preview window.

**Comment by cristiansofronie** [comment]
It seems that LSP hovers can be scrolled without being active so there should be a simple way to achieve this.

**Comment by cristiansofronie** [comment]
Maybe if we use focusable with nvim_open_win the preview will also scroll.

**Comment by cristiansofronie** [comment]
Setting focusable = true makes scrolling in the preview possible but only if the mappings for the results window are not set

**Comment by cristiansofronie** [comment]
focusable = true, the keybinds and holding Alt while scrolling the preview is the closes I have come to a complete solution.

**Comment by cristiansofronie** [comment]
Also 

```c
        set_vim_var_nr(VV_MOUSE_WIN, winnr);
        set_vim_var_nr(VV_MOUSE_WINID, wp->handle);
        set_vim_var_nr(VV_MOUSE_LNUM, lnum);
        set_vim_var_nr(VV_MOUSE_COL, col + 1);
```
There we to be vim.v variables for the line and col and winid. We could also make it so that on click we select a specific entry.

**Comment by cristiansofronie** [comment]
I looked in the C code and the mouse events seem to be sent to the current window and then in the default handler via a call to mouse_find_win it identifies the target window and sets curwin to it.

If you override the default handler scrolling in all the other windows is impossible unless implemented in that handler. So both the preview and results window scrolling should be handles in a listener in the prompt window.

**Comment by jamestrew** [comment]
There's been numerous requests for better mouse support and I agree. Unfortunately, everyone wants it but nobody want to actually implement it :laughing: 

I like fzf-lua's implementation. The scrolling, the clicking all feels intuitive. I think we should use fzf-lua's behavior as inspiration if we're ever going to go for it.

**Comment by cristiansofronie** [comment]
I need to download fzf-lua and see how it implements it. It might try to implement them myself

**Comment by cristiansofronie** [comment]
Some more progress I have made. fzf-lua doen't seem to implement any scrolling. The preview window is scrolled with the default handler for ScrollWheelDown|Up and the results window is created with vim.fn.termopen which opens a pseudo-terminal and runs the command in it. The results buffer then behaves more like an iframe inside the browser being totally isolated.

This can easily be seen with:
:enew
:lua vim.fn.termopen('fzf')

Also the information returned by vim.fn.getmousepos() is outdated

```c
void nv_mousescroll(cmdarg_T *cap)
{
  win_T *const old_curwin = curwin;

  if (mouse_row >= 0 && mouse_col >= 0) {
    // Find the window at the mouse pointer coordinates.
    // NOTE: Must restore "curwin" to "old_curwin" before returning!
    int grid = mouse_grid;
    int row = mouse_row;
    int col = mouse_col;
    curwin = mouse_find_win(&grid, &row, &col);
    if (curwin == NULL) {
      curwin = old_curwin;
      return;
    }
    curbuf = curwin->w_buffer;
  }

  // Call the common mouse scroll function shared with other modes.
  do_mousescroll(cap);

  if (curwin != old_curwin && curwin->w_p_cul) {
    redraw_for_cursorline(curwin);
  }
  curwin->w_redr_status = true;
  curwin = old_curwin;
  curbuf = curwin->w_buffer;
}
```
This is the default handler it sets `curwin` to the result of `mouse_find_win`, scrolls it and restores the curwin.

vim.fn.getmousepos updates only on click not on mousemove or scroll. We might need to make some core contributions to make possible a solution. Making mouse events to be handled by the window local mappings might be interesting or at least some way to get an up to date vim.fn.getmousepos().winid

**Comment by cristiansofronie** [comment]
Actually there is a method to get up to date mouse movement.
```lua
vim.o.mousemoveevent = true
vim.keymap.set('n', '<MouseMove>', function()
  print(vim.inspect(vim.fn.getmousepos()))
end)
```

**Comment by cristiansofronie** [comment]
I have managed do it with the thing from above and expr mappings  that makes it possible to add mappings but also keep the default handler depending on the return value. Like this:

```lua
  vim.keymap.set({ 'n', 'i', 'v' }, '<ScrollWheelDown>', function()
    if results_win == mouse_win then
      vim.defer_fn(function()
        actions.move_selection_next(prompt_bufnr)
      end, 0)
      return ''
    else
      return '<ScrollWheelDown>'
    end
  end, { expr = true })
```
