### ISSUE TITLE
allow yank_history allow paste in visual mode

### ISSUE THREAD

**Issue by yimingwangdell** [nvim-telescope/telescope.nvim#2688]
**Is your feature request related to a problem? Please describe.**
cannot paste in visual mode with ":Telescope yank_history", gives me "No range allowed"
**Describe the solution you'd like**
be able to paste in visual mode.
**Describe alternatives you've considered**

**Additional context**

**Comment by jamestrew** [comment]
I don't recall `yank_history` as a built-in picker we ship with telescope.

I'm guessing it's a third party telescope extension? You probably want to create the issue there. Unless I'm totally missing something. I'm on my phone so I can't verify anything.

**Comment by yimingwangdell** [comment]
@jamestrew agree, please close this ticket.
