### ISSUE TITLE
dynamic_preview_title doesn't update in builtin.resume picker

### ISSUE THREAD

**Issue by davidsierradz** [nvim-telescope/telescope.nvim#2689]
### Description

Hi!

When calling any picker that uses `dynamic_preview_title`, closing it, then calling `builtin.resume`, I expect the preview title to keep getting updated the same as the cached picker, but instead the preview title is frozen on the last item of the cached picker when closed.

Thanks!

### Neovim version

```markdown
NVIM v0.10.0-dev-069fad6
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

NixOS 23.11.20230902.e569908 (Tapir)

### Telescope version / branch / rev

6b79d7a6a45adc1508a7afee5bc973173ec22f59

### checkhealth telescope

```markdown
──────────────────────────────────────────────────────────────────────────────
telescope: health#telescope#check
 
Checking for required plugins  
- OK plenary installed.
- WARNING nvim-treesitter not found. (Required for `:Telescope treesitter`.)
 
Checking external dependencies  
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0
 
===== Installed extensions =====
```

### Steps to reproduce

1. nvim -u minimal.lua
2. Open file picker (`<Space>j`)
3. Close file picker
4. Open resume picker (`<Space>z`)
5. Move through different files 

### Expected behavior

I expect the `dynamic_preview_title` to update the filename in the preview title in the resume picker

### Actual behavior

https://github.com/nvim-telescope/telescope.nvim/assets/9190258/43f92448-ef41-4470-a804-eefaf9475ddb

### Minimal config

```Lua
vim.g.mapleader = ' '

local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  {
    'nvim-telescope/telescope.nvim',
    lazy = false,
    dependencies = { { 'nvim-lua/plenary.nvim', lazy = false } },
  },
}, {
  lockfile = os.getenv('HOME') .. '/nixos/hosts/base/config/nvim/lazy-lock-test.json',
  defaults = {
    lazy = false,
  },
})

require('telescope').setup({
  defaults = {
    dynamic_preview_title = true,
  },
})

vim.keymap.set('n', '<Leader>j', require('telescope.builtin').find_files, { noremap = true, desc = 'Find File' })
vim.keymap.set('n', '<Leader>z', require('telescope.builtin').resume, { noremap = true, desc = 'Resume' })
```

**Comment by cristiansofronie** [comment]
The problems seems to be in Pickeres:new
```lua
    if obj.preview_title == nil or #obj.all_previewers > 1 then
      obj.preview_title = obj.previewer:title(nil, config.values.dynamic_preview_title)
    else
      obj.fix_preview_title = true
    end
```
if a preview_title is given it will be fixed forever. Otherwise it is set dynamically. When we resume a picker we have the obj.preview_title not null so it assumes that the user has given a static title. The solution is to have some extra field to distinguish between when the title was originally not nil or when it became not nil at creation because of being resumed. Resuming a picker calls Picker:new again
