### ISSUE TITLE
Issue with :PlugClean

### ISSUE THREAD

**Issue by Norok-The-Diablo** [nvim-telescope/telescope.nvim#2692]
### Description

Whenever I run :PlugClean, it tries to delete telescope.

### Neovim version

```markdown
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 11

### Telescope version / branch / rev

Telescope Release 1.2

### checkhealth telescope

```markdown
2 telescope: require("telescope.health").check()
  3
  4 Checking for required plugins
  5 - OK plenary installed.
  6 - WARNING nvim-treesitter not found.
  7
  8 Checking external dependencies
  9 - OK rg: found ripgrep 13.0.0
 10 - OK fd: found fd 8.7.0
 11
 12 ===== Installed extensions =====
 13
```

### Steps to reproduce

if has('win64') || has('win32') || has('win16')
  if empty(glob('$LOCALAPPDATA\nvim\autoload\plug.vim'))
    silent ! powershell -Command "
    \   New-Item -Path ~\AppData\Local\nvim -Name autoload -Type Directory -Force;
    \   Invoke-WebRequest
    \   -Uri 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    \   -OutFile ~\AppData\Local\nvim\autoload\plug.vim
    \ "
  endif
else
  if empty(glob('~/.config/nvim/autoload/plug.vim'))
    silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  endif
endif
" Plugins
call plug#begin()
  Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.2' }
call plug#end()

### Expected behavior

For PlugClean to not try to remove telescope everytime.

### Actual behavior

It tries to remove telescope.

### Minimal config

```Lua
if has('win64') || has('win32') || has('win16')
  if empty(glob('$LOCALAPPDATA\nvim\autoload\plug.vim'))
    silent ! powershell -Command "
    \   New-Item -Path ~\AppData\Local\nvim -Name autoload -Type Directory -Force;
    \   Invoke-WebRequest
    \   -Uri 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    \   -OutFile ~\AppData\Local\nvim\autoload\plug.vim
    \ "
  endif
else
  if empty(glob('~/.config/nvim/autoload/plug.vim'))
    silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
      \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  endif
endif
" Plugins
call plug#begin()
  Plug 'nvim-telescope/telescope.nvim', { 'tag': '0.1.2' }
call plug#end()
```

**Comment by jamestrew** [comment]
strange. I don't think this is a telescope bug. doesn't seem to happen with other package managers.

somewhat related: https://github.com/junegunn/vim-plug/issues/1152

looks like you can get around this using the branch instead
`Plug 'nvim-telescope/telescope.nvim', { 'branch': '0.1.x' }`
