### ISSUE TITLE
Share copy/paste between the buffer and telescope input box

### ISSUE THREAD

**Issue by PeiweiHu** [nvim-telescope/telescope.nvim#2701]
**Is your feature request related to a problem? Please describe.**

I usually need to search a string like API names by telescope live_grep. However, sometimes the string is too long and it's annoying to input manually. I tried to copy by the command like `yy` and then paste the string to the input box of telescope by `p` but it didn't work.

**Describe the solution you'd like**

I wonder if there is a way to copy strings from the buffer and paste into the input box of telescope. Thanks!

**Describe alternatives you've considered**

**Additional context**

**Comment by jamestrew** [comment]
You can use `:Telescope grep_string` with your cursor over the word of interest.

**Comment by delphinus** [comment]
Telescope prompt usually opens in Insert Mode. You should use `<C-r>0` to paste yanked register instead of `p`.

**Comment by PeiweiHu** [comment]
Thanks for the suggestions. I tried and both methods work well.

**Comment by AntonC9018** [comment]
But why doesn't `p` work when in normal mode?
