### ISSUE TITLE
The command of builtin.commands or builtin.command_history that executed could be repeated by `@:`

### ISSUE THREAD

**Issue by gh-liu** [nvim-telescope/telescope.nvim#2703]
After running cmd of builtin.commands(nargs equals 0) or builtin.command_history, the command that executed can not be repeated by `@:`, maybe it should be.

**Comment by rudiejd** [comment]
I noticed that no history item added to the command line history is executable by doing `@:`, so it looks like it might be a Neovim thing. I'll dig a little bit more though

**Comment by gh-liu** [comment]
I know what you mean, but I think opening the `builtin.commands` picker is kind like opening the `:` command line.
