### ISSUE TITLE
cannot jump to next item in search window after upgrade plugin

### ISSUE THREAD

**Issue by yimingwangdell** [nvim-telescope/telescope.nvim#2706]
### Description

all works good before I lazy update.

I use   `<c-j>` to jump next item,
  `<c-k>` to jump pre item.
it display "J" in telescope search window, also display "<80>ü^DJ" (unrecognizable char) at bottom right.
for c-k it's normal to jump to previous item.

### Neovim version

```markdown
10
```

### Operating system and version

manjaro

### Telescope version / branch / rev

latest

### checkhealth telescope

```markdown
OK
```

### Steps to reproduce

		mappings = {
						i = {
							["<C-w>"] = "which_key",
							["<C-k>"] = "move_selection_previous",
							["<C-j>"] = "move_selection_next",
							["<C-h>"] = "preview_scrolling_up",
							["<C-l>"] = "preview_scrolling_down",
							["<esc>"] = "close",
							["<enter>"] = "select_tab"
						}
					},

### Actual behavior

as descripbed.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment]
yeah i cant reproduce this issue `<c-j>` works for me. can you at least provide the full telescope config, or correctly fill out the issue template.

because right now i dont see any steps to reproduce this issue neither do i see the mappings setup in the minimal reproduce config ......

**Comment by yimingwangdell** [comment]
this issue exists in any find searching function(<c-f>) in normal md, but not in content search (<c-j>)

**Comment by yimingwangdell** [comment]
@Conni2461 root cause found, nothing to do with this plugin

**Comment by Conni2461** [comment]
would be nice if you document the root cause here, maybe it helps other ppl in the future.

**Comment by yimingwangdell** [comment]
@Conni2461 javacomplete2 plugin have compatible issue with this plugin if using default key mapping.
