### ISSUE TITLE
select_tab do not work in :Telescope

### ISSUE THREAD

**Issue by yimingwangdell** [nvim-telescope/telescope.nvim#2711]
### Description

I bind `<CR>` to select_tab, when I open :Telescope and push `<CR>` on one of items( let's say keymaps), it just brings me to the telescope code  but not opens keymap items.

### Neovim version

```markdown
10
```

### Operating system and version

manjaro

### Telescope version / branch / rev

latest

### checkhealth telescope

```markdown
OK
```

### Steps to reproduce

					mappings = {
						i = {
                                                             ....
							["<esc>"] = "close",
							["<enter>"] = "select_tab",
						}
					},

### Expected behavior

open the item I selected in telescope floating window

### Actual behavior

open telescope code file.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
It doesn't make sense for `<CR>` to always default to `select_tab`. `select_tab` is for opening a selection in a new tab. Not all pickers support opening things in a new tab.
For example, you can't open a telescope picker in a new tab, telescope currently only supports opening as a floating window. So doing `:Telescope`, then `select_tab` on `keymaps` wouldn't work as expected (strange that it opens the telescope code but :shrug:).

`select_tab` however, does work as expected on pickers that open files like `find_files`.
My recommendation is to set these mappings to specific pickers:
```lua
require("telescope").setup({
  defaults = {
    -- telescope wide defaults
  },
  -- picker specific defaults
  pickers = {
    find_files = {
      mappings = {
        i = {
          ["<enter>"] = "select_tab",
        },
      },
    },
  },
})
```
