### ISSUE TITLE
`path_display` options do NOT work with extensions and some other builtins

### ISSUE THREAD

**Issue by searleser97** [nvim-telescope/telescope.nvim#2712]
### Description

display_path options like shorten, truncate, etc do not work with some telescope extensions and other builtin features,

Take a look at the following 2 comments

https://github.com/nvim-telescope/telescope.nvim/issues/895#issuecomment-1730442076

### Neovim version

```markdown
Beta-latest
```

### Operating system and version

Ubuntu 22.04

### Telescope version / branch / rev

latest

### checkhealth telescope

```markdown
All plugins listed here are installed
```

### Steps to reproduce

Described in description box

### Expected behavior

display path options should work with plugins and other builtins not just find_files

### Actual behavior

display path options don't work with extensions and other builtins

**Comment by jamestrew** [comment]
yeah this is a known issue. just haven't had the time.
also related https://github.com/nvim-telescope/telescope.nvim/issues/2658

**Comment by searleser97** [comment]
Also this is related issue https://github.com/nvim-telescope/telescope.nvim/issues/2408

**Comment by delphinus** [comment]
@searleser97  FYI: The current build of frecency supports `path_display`. `:Telescope frecency path_display={'smart'}` should work, for example.

**Comment by delphinus** [comment]
Sorry, this issue means that the default setting of telescope.nvim is ignored in some pickers (like frecency).

```lua
telescope.setup {
  path_display = { "shorten" },
}
```

```vim
" This is shorten
:Telescope frecency path_display={"shorten"}

" But this is NOT shorten
:Telescope frecency
```

I will fix this.

**Comment by searleser97** [comment]
I think it also doesn't work with this other plugin https://github.com/smartpde/telescope-recent-files so you guys can test with a plugin where it doesn't work

**Comment by jamestrew** [comment]
I fixed this for `git_status` but for extensions, they will have to add support for it themselves.
It should be just a one line change to add support for it.
