### ISSUE TITLE
Searching opened files is not working correctly

### ISSUE THREAD

**Issue by prss-ad** [nvim-telescope/telescope.nvim#2716]
### Description

Missing results when searching a term in opened files. 
I assume that by opened files we mean buffers  in their current state  not files on disk.

### Neovim version

```markdown
NVIM v0.10.0-dev-ac1c234
Build type: RelWithDebInfo
LuaJIT 2.1.1695409640
```

### Operating system and version

Debian 11

### Telescope version / branch / rev

Telescope 0.1.3

### checkhealth telescope

```markdown
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- WARNING nvim-treesitter not found. 

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fdfind 8.7.0

===== Installed extensions ===== ~
```

### Steps to reproduce

1 - run neovim with minimal config that you provide below (untouched).

2 - create file x with content:
one
three

3 - create file y with content:
one
two

4 - with both files opened , add a new line with the word 'two' to file x, do not  save it.

5 - Run Telescope grep_string grep_open_files=true

### Expected behavior

Searching opened files means to me, searching the buffers i have opened, buffers that may not have been written yet.
So i expect to find the search argument  in both buffers without being forced to save my work.

I understand that this might be a terminology issue, or maybe i'm misundertanding the documentation. So i'm not sure if this is actually a bug or not.

### Actual behavior

You find 'two' only for saved buffers, in this case modification in file x is not found.

![image](https://github.com/nvim-telescope/telescope.nvim/assets/107325360/07afa1af-4ea1-4973-932b-edad295476ea)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
I'm sure not if there's anything we can do about this. Under the hood, we're just calling out to ripgrep and it won't be able to find matches in an unsaved file.

**Comment by prss-ad** [comment]
Thought so. 

So not a bug. It would have to be something like current_buffer_fuzzy but for all open buffers. 

It might be good to make it really clear in the documentation that the search is for files on disk not internal neovim buffers. I suggest this because it does not make much sense to only grep  opened files if we are not grepping their actual state, at least not to me.

Anyway , thanks to all of you who are making this plugin possible.

**Comment by carbolymer** [comment]
I confirm this issue, but it seems that's a bug in `neovim` itself. It showed up after I upgraded my neovim nightly on friday. I've downgraded neovim to latest stable 0.9.2 and fuzzy search works correctly now.
