### ISSUE TITLE
ERROR Failed to run healthcheck for "telescope" plugin.

### ISSUE THREAD

**Issue by Flo-Slv** [nvim-telescope/telescope.nvim#2719]
### Description

Hi there,

I can not run `:checkhealth telescope`. I've got an error.

I have the minimal config of the Telescope homepage. No plugins except `plenary.nvim`.

I use `lazy.nvim` as package manager.

### Neovim version

```markdown
NVIM v0.9.2-dev-54+g953904c00
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu 22.04.3

### Telescope version / branch / rev

tag 0.1.3

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

- ERROR Failed to run healthcheck for "telescope" plugin. Exception:
  function health#check, line 25
  Vim(eval):E5108: Error executing lua .../share/nvim/lazy/telescope.nvim/lua/telescope/health.lua:113: bad argument #1 to 'pairs' (table expected, got nil)
  stack traceback:
  [C]: in function 'pairs'
  .../share/nvim/lazy/telescope.nvim/lua/telescope/health.lua:113: in function 'check'
  [string "luaeval()"]:1: in main chunk
```

### Steps to reproduce

:checkhealth telescope

### Actual behavior

telescope: require("telescope.health").check()

- ERROR Failed to run healthcheck for "telescope" plugin. Exception:
  function health#check, line 25
  Vim(eval):E5108: Error executing lua .../share/nvim/lazy/telescope.nvim/lua/telescope/health.lua:113: bad argument # 1 to 'pairs' (table expected, got nil)
  stack traceback:
  [C]: in function 'pairs'
  .../share/nvim/lazy/telescope.nvim/lua/telescope/health.lua:113: in function 'check'
  [string "luaeval()"]:1: in main chunk

### Minimal config
`plugins/telescope.lua`

```Lua
return {
  'nvim-telescope/telescope.nvim',
        tag = '0.1.3',
        -- branch = '0.1.x',
  dependencies = { 'nvim-lua/plenary.nvim' }
}
```

**Comment by jamestrew** [comment]
Strange.
I can't replicate it with this config
```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "nvim-telescope/telescope.nvim",
        tag = "0.1.3",
        requires = {
          "nvim-lua/plenary.nvim",
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
_G.load_config = function()
  require("telescope").setup()
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

**Comment by Flo-Slv** [comment]
> Strange. I can't replicate it with this config
> 
> ```lua
> vim.cmd([[set runtimepath=$VIMRUNTIME]])
> vim.cmd([[set packpath=/tmp/nvim/site]])
> local package_root = "/tmp/nvim/site/pack"
> local install_path = package_root .. "/packer/start/packer.nvim"
> local function load_plugins()
>   require("packer").startup({
>     {
>       "wbthomason/packer.nvim",
>       {
>         "nvim-telescope/telescope.nvim",
>         tag = "0.1.3",
>         requires = {
>           "nvim-lua/plenary.nvim",
>         },
>       },
>       -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
>     },
>     config = {
>       package_root = package_root,
>       compile_path = install_path .. "/plugin/packer_compiled.lua",
>       display = { non_interactive = true },
>     },
>   })
> end
> _G.load_config = function()
>   require("telescope").setup()
>   -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
> end
> if vim.fn.isdirectory(install_path) == 0 then
>   print("Installing Telescope and dependencies.")
>   vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
> end
> load_plugins()
> require("packer").sync()
> vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
> ```

Hey !

It was on my working environment. I arrived this morning at work, restarted my computer and it's working 😕 

Sorry for this !

**Comment by Flo-Slv** [comment]
> Strange. I can't replicate it with this config
> 
> ```lua
> vim.cmd([[set runtimepath=$VIMRUNTIME]])
> vim.cmd([[set packpath=/tmp/nvim/site]])
> local package_root = "/tmp/nvim/site/pack"
> local install_path = package_root .. "/packer/start/packer.nvim"
> local function load_plugins()
>   require("packer").startup({
>     {
>       "wbthomason/packer.nvim",
>       {
>         "nvim-telescope/telescope.nvim",
>         tag = "0.1.3",
>         requires = {
>           "nvim-lua/plenary.nvim",
>         },
>       },
>       -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
>     },
>     config = {
>       package_root = package_root,
>       compile_path = install_path .. "/plugin/packer_compiled.lua",
>       display = { non_interactive = true },
>     },
>   })
> end
> _G.load_config = function()
>   require("telescope").setup()
>   -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
> end
> if vim.fn.isdirectory(install_path) == 0 then
>   print("Installing Telescope and dependencies.")
>   vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
> end
> load_plugins()
> require("packer").sync()
> vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
> ```

Hey !

It was on my working environment. I arrived this morning at work, restarted my computer and it's working 😕 

Sorry for this !
