### ISSUE TITLE
current_buffer_fuzzy_find disable highlighting for results

### ISSUE THREAD

**Issue by temhelk** [nvim-telescope/telescope.nvim#2720]
**Is your feature request related to a problem? Please describe.**
This issue is related to 'builtin.current_buffer_fuzzy_find' picker.
I installed a tree-sitter parser for 'zig' and after that telescope started using it for syntax highlighting in two places:
1. In the preview
2. For every line that I found

I wanted to disable that, I found a way to disable that for preview using:
```lua
defaults = {
    preview = {
        treesitter = false
    }
}
```

But I did not find a way to do that with line results.

Is there a way to do it right now, or should it be added?

**Describe the solution you'd like**
An option to disable highlighting for result lines.

**Additional context**
Here's the comparison of how it looks with and without tree-sitter parser for zig:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/77777950/c68093c6-c019-4fcc-8e24-dde5ccc68137)
![image](https://github.com/nvim-telescope/telescope.nvim/assets/77777950/500399e8-a705-498d-9a27-3b975b50308e)

I think this code is related to that highlighting?
https://github.com/nvim-telescope/telescope.nvim/blob/84d53dfdbefbdf84e861a288abc71ef8ccafd04e/lua/telescope/builtin/__files.lua#L484

**Comment by jamestrew** [comment]
I don't believe we currently offer disabling treesitter highlighting for the results but I think adding one is a reasonable addition.

Maybe a new option like `results_ts_hightlight` (default true to preserver current behavior).
> I think this code is related to that highlighting?

That's correct. We can just add a check for this new option in this line. Should be fairly straight forward.

PR is welcome but I can also implement this too if that's preferred.

**Comment by temhelk** [comment]
It would be nice if you could implement this, thank you.
