### ISSUE TITLE
Anyway to disable abbreviations in prompt?

### ISSUE THREAD

**Issue by jonahfang** [nvim-telescope/telescope.nvim#2721]
I create abbrevaition like this:

```
vim.cmd('iab fn const  = () => {<cr><cr>}<esc>10h3k10')
```
When I do live_grep and input 'fn' and press SPACE, the above abbrevaition done and the window closed.

**Comment by jamestrew** [comment]
gonna have to be more specific than that

**Comment by jamestrew** [comment]
I'm not aware of any way to disable abbreviations for certain filetypes.
You could probably just only enable it for certain filetypes though using `ftplugin` and `<buffer>`.

Better yet, you should really use a snippet engine for things like that.
