### ISSUE TITLE
The `git_files` picker doesn't take working directory changes into account

### ISSUE THREAD

**Issue by marekdedic** [nvim-telescope/telescope.nvim#2725]
### Description

Hi,
starting fairly recently, the `git_files` picker stopped taking working directory changes into account - what I mean by that is for example:
- If I add a new file that is not yet tracked by git, it won't be in the picker
- If I delete a file, it will be still displayed in the picker

### Neovim version

```markdown
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Debian testing

### Telescope version / branch / rev

0.1.3

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - OK: lib working as expected
  - OK: file_sorter correctly configured
  - OK: generic_sorter correctly configured
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Ctrl+T
3. Enter name of file not in git

### Expected behavior

The file not in git should be in the list

### Actual behavior

The file not in git is not in the list

### Minimal config

```Lua
local Plug = vim.fn['plug#']

vim.call('plug#begin', vim.fn.stdpath('data') .. '/plugged')

Plug('nvim-lua/plenary.nvim')
Plug('nvim-telescope/telescope.nvim', {tag = "0.1.3"})

vim.call('plug#end')

vim.keymap.set('n', '<C-T>', require'telescope.builtin'.git_files, {})
```

**Comment by jamestrew** [comment]
The `git_files` picker is using the git command `git ls-files --cached --exclude-standard`.
The `--cached` (which is on by default with the `git ls-files` command) shows only tracked files. So this behavior:
>  If I add a new file that is not yet tracked by git, it won't be in the picker
    If I delete a file, it will be still displayed in the picker

is expected and hasn't change recently.
You can use `show_tracked` (`:Telescope git_files show_untracked=true`) to show untracked files.
Or pass a custom command like `git ls-files --others --exclude-standard` with the `git_command` option.
I'm not sure if there's a `git ls-files` flag for NOT showing deleted but still tracked files. You'll have to see the manpages for that.

It might just be easier to use `find_files`.

**Comment by marekdedic** [comment]
Hi,
thanks for the response, however, it has changed "recently" - I had to downgrade to tag `nvim-0.6` (for unrelated reasons) and it works as I expected - that is the `git_files` picker includes untracked files.

When I upgrade back up to a more recent version, I'll try your suggestions :)
