### ISSUE TITLE
Support the `^wr` map in the input window

### ISSUE THREAD

**Issue by coot** [nvim-telescope/telescope.nvim#2730]
**Describe the solution you'd like**
It would be nice if the input box would support `^wr` the same way command line supports it (input the word under the cursor from the buffer which telescope was called).

**Comment by jamestrew** [comment]
Do you mean `<c-r><c-w>` as in inserting the word under the cursor in the command line?

**Comment by konosubakonoakua** [comment]
any new progress or advice?

**Comment by jamestrew** [comment]
Created a mapping for it `<c-r><c-w>` on master.
