### ISSUE TITLE
Drop `builtin.lsp_*({ jump_type })` opt

### ISSUE THREAD

**Issue by hinell** [nvim-telescope/telescope.nvim#2743]
https://github.com/nvim-telescope/telescope.nvim/blob/74ce793a60759e3db0d265174f137fb627430355/lua/telescope/builtin/__lsp.lua#L42-L65
https://github.com/nvim-telescope/telescope.nvim/blob/74ce793a60759e3db0d265174f137fb627430355/lua/telescope/builtin/__lsp.lua#L189-L203

The above code is redundant.  If we specify "never", its' going to default to picker's action, which can be tweaked via default actions:
```lua
actions.select_horizontal -- eq to  { jump_type = "split" }
actions.select_vertical -- "vsplit"
actions.select_tab -- "tab"
actions.select_drop
actions.select_tab_drop
```

**Comment by jamestrew** [comment]
those bits of code is for when there's only one result and therefore telescope doesn't even open.
if telescope doesn't open, you can't use select_horizontal, etc.

so they do serve a purpose.
unless I'm misinterpreting something, we won't be dropping the `jump_type` option for this reason.

**Comment by hinell** [comment]
> _telescope doesn't even open._

@jamestrew Well, in my version 74ce793a60759e3db0d265174f137fb627430355 telescope opens anyway, even with one result.

**Comment by jamestrew** [comment]
In that case please open a bug report with reproducible config and steps.

**Comment by hinell** [comment]
@jamestrew Selecting single entry in the telescope - It's not a bug really, I'm fine with that.

**Comment by Conni2461** [comment]
if it doesnt work for you it would be interesting to know why, and maybe we can fix it, even if you dont like/mind that behaivor of selecting a single entry, we have the option do disable it for a reason.

But plese dont do things like that, opening a issue with "delete a bunch of code" and then saying code doesnt work and not explaining why or how it doesnt work. it just creates noice
