### ISSUE TITLE
Telescope breaking when upgrading to nvim version 0.9.4+

### ISSUE THREAD

**Issue by SlinkierElm5611** [nvim-telescope/telescope.nvim#2747]
### Description

I rebuilt my nvim today on both the `release-0.9` branch which is 0.9.5-dev and on the `stable` branch which is 0.9.4, For both of them the error below appears but it does not occur in versions earlier than 0.9.3.

### Neovim version

```markdown
NVIM 0.9.4
Build type: Release
LuaJIT 2.1.1692716794
```

### Operating system and version

Ubuntu 22.04

### Telescope version / branch / rev

telescope 1.4

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions ===== ~
```

### Steps to reproduce

1. re-clone nvim repository, 
2. checkout stable (0.9.4+)
3. build release type and packaged into deb file for installation
4. ran nvim
5. attempted to run `:Telescope find_files`

### Expected behavior

find files menu search comes up and allows searching of files

### Actual behavior

![image](https://github.com/nvim-telescope/telescope.nvim/assets/52179385/332dc26d-7336-493a-a0bd-78fd5890a798)

### Minimal config

```Lua
-- telescope
local telescope = require('telescope')
telescope.setup{
    pickers = {
        find_files = {
            hidden = true,
        },
        git_files = {
            hidden = true,
        },
        grep_string = {
            hidden = true,
        },
    },
}
```

**Comment by Conni2461** [comment]
Everyone with an error in pickers.lua line 347 has an out of date telescope. Als see #2735

**Comment by jamestrew** [comment]
You don't need to downgrade neovim. Just update telescope to 0.1.3+. If you're still getting the error, you've failed to update telescope correctly. Try uninstalling and reinstalling it.

**Comment by oiwn** [comment]
@jamestrew I have telescope 0.1.4 and error still there on nvim 0.9.4

**Comment by jamestrew** [comment]
@oiwn if it's the same error, same line number, then you're still stuck on pre-0.1.3 somehow. That line number literally doesn't exist on 0.1.3+.

Try cd'ing to the path where telescope is installed and manually git pull and troubleshooting (probably just rm -rf the directory and installing again should work). There's probably some stale help docs that's blocking lazy/git from updating telescope or something. Seems like that's what others have experienced.

**Comment by oiwn** [comment]
yea I rm'ed all plugins. weird I just get back to 0.9.4 and it works. Before someone who had same problem suggested me to revert to 0.9.2.

**Comment by xiongyu1988** [comment]
same issue here.

**Comment by jamestrew** [comment]
@xiongyu1988 just update telescope to 0.1.3+ (latest stable release is 0.1.6)

See my comments above for more info.
I'm locking this issue so I don't have to repeat myself anymore.
