### ISSUE TITLE
Per-edge border configuration results in incorrect layout

### ISSUE THREAD

**Issue by brettmitchelldev** [nvim-telescope/telescope.nvim#2749]
### Description

The `border` property supports wholesale configuration with a boolean: `border = true`, per-edge configuration with a table: `border = { 1, 0, 0, 1 }`, and a combined approach using specific `preview`, `prompt`, and `results` keys: `border = { preview = true, prompt = { 1, 0, 0, 1 }, results = false }`.

When using this feature, the resulting layout is not correct in all cases.

For example, when using:

```lua
{
  border = {
    prompt = { 1, 1, 1, 1 },
    results = { 1, 1, 1, 1 },
    preview = { 1, 1, 1, 1 },
  },
  borderchars = {
    prompt = { " ", " ", "─", "│", "│", " ", "─", "└" },
    results = { "─", " ", " ", "│", "┌", "─", " ", "│" },
    preview = { "─", "│", "─", "│", "┬", "┐", "┘", "┴" },
  }
}
```

This results in a (correct) layout that looks like:

![image](https://github.com/nvim-telescope/telescope.nvim/assets/36866021/f3e3f837-5356-4fc3-b6c5-567ef2cb6028)

But to reduce the amount of space between the prompt and results, I tried modifying my border characters as follows:
```lua
{
  border = {
    prompt = { 0, 1, 1, 1 },
    results = { 1, 1, 1, 1 },
    preview = { 1, 1, 1, 1 },
  }
}
```

This resulted in the following layout:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/36866021/a64fbd82-ca84-4d88-bc8e-c03b43fdfd06)

### Neovim version

```markdown
NVIM v0.10.0-dev-5f4f83b
Build type: RelWithDebInfo
LuaJIT 2.1.1695653777
Run "nvim -V1 -v" for more info
```

### Operating system and version

Linux Arch-Linux 6.4.12-arch1-1

### Telescope version / branch / rev

74ce793a60759e3db0d265174f137fb627430355

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `dap` ~
- No healthcheck provided

Telescope Extension: `lsp_handlers` ~
- No healthcheck provided
```

### Steps to reproduce

1. Use minimal config
2. Run `:Telescope help_tags` (or any other telescope command)
3. Observe the resulting layout

### Expected behavior

Layout properly accounts for per-edge border configuration.
Prompt does not shift down by one line.

### Actual behavior

Prompt shifts down by one line, hiding the bottom border.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup({
    defaults = {
      border = {
        prompt = { 0, 1, 1, 1 },
        results = { 1, 1, 1, 1 },
        preview = { 1, 1, 1, 1 },
      },
      borderchars = {
        prompt = { " ", " ", "─", "│", "│", " ", "─", "└" },
        results = { "─", " ", " ", "│", "┌", "─", " ", "│" },
        preview = { "─", "│", "─", "│", "┬", "┐", "┘", "┴" },
      }
    }
  })
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Unfortunately, I'm not very familiar with the layout config for telescope so I can't be of much help but if you're looking for something like this https://github.com/nvim-telescope/telescope.nvim/pull/2381 I don't think messing with those `border` and `borderchars` values alone will get you there.

We did fairly recently add a mechanism to do something like what I think you're looking for in this PR https://github.com/nvim-telescope/telescope.nvim/pull/2572

**Comment by MunifTanjim** [comment]
Added Fused Layout in Configuration Recipes Wiki: https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#fused-layout

**Comment by brettmitchelldev** [comment]
@jamestrew @MunifTanjim Thank you for the replies, I was able to use the fused layout recipe to get exactly what I wanted! :rocket:
