### ISSUE TITLE
Different initial_mode with different pickers

### ISSUE THREAD

**Issue by benqhdri** [nvim-telescope/telescope.nvim#2754]
I'd like to set different initial mode in different pickers, for example, "insert" mode in find_files picker, "normal" mode in buffers picker.

Here is the configuration I set, but it doesn't work now. It is still **normal mode** when I do find_files.
```lua
require('telescope').setup({
    defaults = {
        pickers = {
            find_files = {
                initial_mode = "insert",
            },
        },
        initial_mode = "normal",
    }
}
```
![image](https://github.com/nvim-telescope/telescope.nvim/assets/80582089/dc92573f-569f-4040-a114-5337aa347daf)

Option of **mapping** worked well in different pickers, wish this initial mode option works as well.

**Comment by rodhash** [comment]
Does it work for extensions too? Setting it as default works but trying to set it only to `telescope-session.nvim` doesn't seem to work

**Comment by jamestrew** [comment]
@rodhash It's currently on extension authors to merge options passed to the `setup` function with their defaults as they see fit.
Quickest workaround for you would be to pass the option directly when you invoke the picker like this `require('telescope.builtin').find_files({ initial_mode = 'normal' })`
