### ISSUE TITLE
Parameters of find_command does not support the * symbol

### ISSUE THREAD

**Issue by ztoiax** [nvim-telescope/telescope.nvim#2756]
`:Telescope find_files find_command=rg,--ignore,--hidden,--files` is work

`:Telescope find_files find_command=rg,--ignore,--hidden,--files,*` is not work

**Comment by jamestrew** [comment]
I believe `*` is a glob expansion happening via the shell and not a flag/option that ripgrep supports.

Pretty sure the second command is just equivalent to something like `rg --files --no-ignore-vcs`. It's basically negating the `--ignore` and `--hidden` flags. I not sure why you'd even want something like that.

I'm gonna lean towards saying that handling a command like the second one is outside the scope of telescope.
