### ISSUE TITLE
Telescope health check passes, but running other commands like find_files throws exception

### ISSUE THREAD

**Issue by anthony-somo** [nvim-telescope/telescope.nvim#2758]
### Description

I've been using Telescope in my neovim for a while now without issues on Linux.
However, in my new Apple M2 laptop, after working fine for some days, Telescope commands started to throw the following exception message:

```
E5108: Error executing lua: ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: Invalid 'event': 'User TelescopeFindPre'
stack traceback:
	[C]: in function 'nvim_exec_autocmds'
	...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: in function 'find'
	...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:342: in function 'v'
	...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:570: in function 'v'
	...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:511: in function <...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:478>
```

### Neovim version

```markdown
NVIM v0.10.0-dev-1386+g6c87d3e0f-Homebrew
Build type: Release
LuaJIT 2.1.1696795921
```

### Operating system and version

macOS Ventura 13.5

### Telescope version / branch / rev

telescope branch 0.1.x

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions ===== ~
```

### Steps to reproduce

1. Install neovim using `brew install --HEAD neovim`
2. Configure plugins using packer. The neovim config I use is [here](https://github.com/creativecomposer/neovim-config)
3. Start neovim
4. Issue a Telescope command. For example, `:Telescope find_files`

Notes:
1. The neovim config link above shows Telescope tag `0.1.1`, but I changed it to `branch = '0.1.x'`. Still the problem persists.
2. When I comment out the line `vim.api.nvim_exec_autocmds("User", { pattern = "TelescopeFindPre" })` at [pickers.lua](https://github.com/nvim-telescope/telescope.nvim/blob/7011eaae0ac1afe036e30c95cf80200b8dc3f21a/lua/telescope/pickers.lua#L351), then the exception disappeared. The `:Telescope find_files` command works fine.

### Expected behavior

The find files window should open

### Actual behavior

Running the Telescope commands throws the following exception and does not work.

```
E5108: Error executing lua: ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: Invalid 'event': 'User TelescopeFindPre'
stack traceback:
	[C]: in function 'nvim_exec_autocmds'
	...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: in function 'find'
	...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:342: in function 'v'
	...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:570: in function 'v'
	...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:511: in function <...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:478>
```

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Seems like a duplicate of these
https://github.com/nvim-telescope/telescope.nvim/issues/2735
https://github.com/nvim-telescope/telescope.nvim/issues/2747

I'm confident this has been fixed since 0.1.3. The line number in the error message indicates that you're on pre-0.1.3 telescope.
Please make sure telescope has actually updated to at least 0.1.3 (or the latest tag 0.1.4 or 0.1.x/master branch).

**Comment by anthony-somo** [comment]
Thank you, I reported the issue after updating Telescope to 0.1.4. However, let me double check again and report the results.

**Comment by Acyco** [comment]
I have the same problem.

**Comment by anthony-somo** [comment]
I did the following:

```
cd ~/.local/share/nvim/site/pack/packer/start/telescope.nvim
git checkout 0.1.x
git pull
```

Then started NeoVim. Now I do not see the error.

Yesterday, I did the above steps and still saw the error. Today, after repeating the steps again, it does not happen. Weird.
However, I will close the issue since I do not see the issue anymore.
