### ISSUE TITLE
Better preview for built-in diagnostics picker

### ISSUE THREAD

**Issue by filakhtov** [nvim-telescope/telescope.nvim#2761]
**Is your feature request related to a problem? Please describe.**
At the moment the built-in diagnostics picker displays a short problem description in the results window and a source code of the file where the problem occurred in the previewer. This has a few limitations:

- only the first line of the diagnostics message is displayed in the results window
- when a buffer has unsaved changes, the preview window can’t accurately display the source of the problem either

This can be seen well on the following two screenshots respectively:

![image](https://github.com/nvim-telescope/telescope.nvim/assets/5741553/4d97a29a-8c22-473a-82a2-0a9530d7362d)
the source of the error is located on the line that is way beyond the buffer that is displayed.

and

![image](https://github.com/nvim-telescope/telescope.nvim/assets/5741553/305f6098-5628-4727-adbd-f0a3f58f95c3)
 Only the first line of the diagnostics is visible, out of the:
```
error: expected identifier, found `<eof>`
  --> src/lib.rs:13:5
   |
13 | pub fn
   |     ^^ expected identifier


error: could not compile `etl` (lib) due to previous error
```
which is rather inconvenient.

**Describe the solution you'd like**
I would like to propose an idea of displaying a full diagnostic message in the preview window, instead of the contents of the file where the problem occurs. I am happy to contribute, but would need a bit of guidance as to the best way of implementing this.

**Describe alternatives you've considered**
- [lsp_lines](https://git.sr.ht/~whynothugo/lsp_lines.nvim), but it makes things look ugly and consuming a lot of vertical space at all times in the buffer area itself;
- Setting higher limit of the message width for telescope results, but this consumes a lot of space in the results window and doesn't really help in quick at a glance navigation;
- [trouble.nvim](https://github.com/folke/trouble.nvim), but that's yet another plugin with a lot of the same things I can get from Telescope;

**Additional context**
Open to any other thoughts and idea on this. Does everyone else thinks this is actually feasible?

**Comment by rudiejd** [comment]
You can actually do this right now in your config:

```lua
        local telescope = require('telescope')
        telescope.setup({
            defaults = {
                qflist_previewer =  function (opts)
                    return require('telescope.previewers').new_buffer_previewer {
                            title = "Diagnostics",
                            dyn_title = function(_, entry)
                                return entry.title
                            end,

                            get_buffer_by_name = function(_, entry)
                                return "diagnostics_" .. tostring(entry.nr)
                            end,

                            define_preview = function(self, entry)
                                print('what up bitches')
                                print(vim.inspect(entry))
                                vim.api.nvim_buf_set_lines(self.state.bufnr, 0, -1, false, {entry.text})
                            end,
                    }
                end,
            }
        })
```

However, this requires you to override the default `qflist_previewer`. I think a better would be to allow setting a previewer in the `opts` for `builtin.diagnostic`, since it already allows overridding `make_entry`. Maybe an even better approach would be to allow for configuring a custom previewer for each picker in the picker config.

**Comment by jamestrew** [comment]
I believe you can pass a `previewer` option directly to a picker's option.
eg.
```lua
require("telescope").setup({
  pickers = {
    diagnostics = {
      previewer = require("telescope.previewers").new_buffer_previewer({
        title = "Diagnostics",
        dyn_title = function(_, entry)
          return entry.title
        end,

        get_buffer_by_name = function(_, entry)
          return "diagnostics_" .. tostring(entry.nr)
        end,

        define_preview = function(self, entry)
          vim.api.nvim_buf_set_lines(self.state.bufnr, 0, -1, false, { entry.text })
        end,
      }),
    },
  },
})
```

I'm not sure if that helps the original issue much though. It's still the same one liner in the previewer. The LSP diagnostic message isn't the same thing as the `cargo check` output. Might be able to get more info by digging into the protocol but that might get into details that are language server specific, not sure.

If someone wants to explore this further, I did notice there something closer to the `cargo check` output nested deeper inside `vim.diagnostic.get(0)` (for an error in the current buffer). But again, not sure how universally available this data is across lang servers.

**Comment by filakhtov** [comment]
Hey @jamestrew and @rudiejd, happy holidays!

Thank you very much for looking into this issue and providing the examples. This is actually a bit better, but doesn't solve the problem in its entirety - it is still a single line that is cut off at the right edge:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/5741553/4994435e-4edf-47a6-823c-fc2c27e8f0a0)

and I am not sure how to enable word wrapping in the preview window. With word wrapping this could be a bit more useful, but still not as much as cargo's own output is.

Also, in full disclosure, when I opened this issue I was just starting my NeoVim journey. I have spent a bunch of time with NeoVim/Telescope as is right now and it doesn't seem to be as big of a hindrance as I have initially thought it would be. I have discovered a workflow that works pretty well - using Telescope to navigate to a source of the diagnostic, then using the diagnostics float, and if that's not the right place, I would simply reopen previous Telescope picker window and continue where I left off.

So unless that's something that the whole Telescope ecosystem can benefit from, I will be actually inclined to close this issue and move on. I am sure there are far more important issues that need attention. Once more, appreciate your thoughts on this and feel free to reopen this issue if you think this is actually valuable feature for the project itself!

**Comment by jamestrew** [comment]
> using Telescope to navigate to a source of the diagnostic, then using the diagnostics float, and if that's not the right place, I would simply reopen previous Telescope picker window and continue where I left off.

I personally user `<C-q>` (by default) to put all the diagnostics results into a quickfix list then use `:cnext` to work through them. 

Unrelated to telescope, I also have some lsp keymaps to jump to diagnostics in the current buffer
```lua
---@param key string
---@param direction "next"|"prev"
---@param severity DiagnosticSeverity?
---@param bufnr number
local function diagnostic_goto(key, direction, severity, bufnr)
  local go = direction == "next" and vim.diagnostic.goto_next or vim.diagnostic.goto_prev
  severity = severity or nil
  vim.keymap.set(
    "n",
    key,
    function() go({ severity = severity }) end,
    { silent = true, buffer = bufnr }
  )
end

-- then in my lsp `on_attach` function where `bufnr` is from the `on_attach` args
  diagnostic_goto("]d", "next", nil, bufnr)
  diagnostic_goto("[d", "prev", nil, bufnr)
  diagnostic_goto("]e", "next", vim.diagnostic.severity.ERROR, bufnr)
  diagnostic_goto("[e", "prev", vim.diagnostic.severity.ERROR, bufnr)
  diagnostic_goto("]w", "next", vim.diagnostic.severity.WARN, bufnr)
  diagnostic_goto("[w", "prev", vim.diagnostic.severity.WARN, bufnr)
```

**Comment by filakhtov** [comment]
Thanks for sharing! I literally have the same `]d` and `[d` shortcuts 😄
