### ISSUE TITLE
Show marks for the current buffer only

### ISSUE THREAD

**Issue by marconetto** [nvim-telescope/telescope.nvim#2763]
**Is your feature request related to a problem? Please describe.**
`Telescope marks` command shows the marks of all my files, and I would like to see only marks of the current buffer with a shortcut.

**Describe the solution you'd like**
`vim.api.nvim_set_keymap('n', '<leader>b', '<cmd>lua require"telescope.builtin".current_buffer_marks()<CR>', { noremap = true })`

**Describe alternatives you've considered**
I was trying something like this. Not sure if this would work with proper adjustment in the command: 

`vim.api.nvim_set_keymap('n', '<leader>b',
    '<cmd>lua require"telescope.builtin".marks({bufnr= vim.api.nvim_get_current_buf()})<CR>',
    { noremap = true })`

Ideally I would like the same output as the `MarksListBuff` command from https://github.com/chentoast/marks.nvim
but displayed in telescope.

**Comment by jamestrew** [comment]
I'm open to having something like this.
I would probably stick with just having the existing `marks` picker but adding a new option like `mark_type: "local" | "global" | "all"` so you can call `:Telescope marks mark_type=local` or something.

I'm a bit busy but if anyone is interested in implementing this, should be fairly simple and I can offer some pointers if needed.

**Comment by Nero-F** [comment]
I think I can try handle that

**Comment by lrfurtado** [comment]
working on this task

**Comment by lrfurtado** [comment]
@jamestrew am i a good path here with https://github.com/nvim-telescope/telescope.nvim/pull/2775

**Comment by lordgreg** [comment]
I am sorry for bumping this issue, but, I don't see the difference in the results at all.

all 3 types yield the exact same result.

**Comment by ErtaiBlue** [comment]
This fix is in the master branch but it is not in the tag 0.1.8. Can someone include it in the 0.1.8 branch?
