### ISSUE TITLE
can not get .env file with find_files 

### ISSUE THREAD

**Issue by t0mri** [nvim-telescope/telescope.nvim#2765]
### Description

![image](https://github.com/nvim-telescope/telescope.nvim/assets/123792488/ed94a3d0-8f4a-4439-945c-57fef3969898)

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

wsl1

### Telescope version / branch / rev

0.1.4-1

### checkhealth telescope

```markdown
nvim-treesitter installed.
telescope: require("telescope.health").check()
Checking for required plugins
- ok plenary installed.
- OK
Checking external dependencies
- OK rg: found ripgrep 13.0.0
- OK fd: found fdfind 8.6.0
Installed extensions
Telescope Extension: 'file_browser
- No healthcheck provided
```

### Steps to reproduce

refer the image

### Actual behavior

show .git files but not .env file

### Minimal config

```Lua
""
```

**Comment by Conni2461** [comment]
on default we use rg for file searching, so you can check if the file is present using `rg --hidden --files` in your cli. This "issue" is not related to telescope, but rather a misconfigured rg.

The problem is that `.env` is probably in your gitignore and on default rg ignores all these files so you can do `rg --no-ignore --files` to get all ignored files and then on top `rg --no-ignore --hidden --files` to also show ignored hidden files like `.env`

We expose this in telescope with the `no_ignore` option you your define your own `find_command` where you only disable ignore for a couple of files, pretty sure thats possible with either `fd` or `rg` just read the respected manpages.

`:help telescope.builtin.find_files`

**Comment by avahe-kellenberger** [comment]
Running into the same issue. Are you saying to put `no_ignore = true` in the telescope config? E.g.
```lua
use {
        'nvim-telescope/telescope.nvim', tag = '0.1.4',
        -- or, branch = '0.1.x',
        requires = { { 'nvim-lua/plenary.nvim' } },
        pickers = {
            find_files = {
                no_ignore = true
            }
        }
    }
```

This does not work for me. I'm also not finding the right documentation on how I could use `no_ignore` when invoking `require('telescope.builtin').find_files`

**Comment by t0mri** [comment]
> on default we use rg for file searching, so you can check if the file is present using `rg --hidden --files` in your cli. This "issue" is not related to telescope, but rather a misconfigured rg.
> 
> The problem is that `.env` is probably in your gitignore and on default rg ignores all these files so you can do `rg --no-ignore --files` to get all ignored files and then on top `rg --no-ignore --hidden --files` to also show ignored hidden files like `.env`
> 
> We expose this in telescope with the `no_ignore` option you your define your own `find_command` where you only disable ignore for a couple of files, pretty sure thats possible with either `fd` or `rg` just read the respected manpages.
> 
> `:help telescope.builtin.find_files`


Thanks a lot!!!

**Comment by Conni2461** [comment]
No i said checkout the underlying rg (and or fd command) and then configure telescope like you want. this can be a combination of no_ignore and hidden or a completely custom command.

Everything is documented in `:help telescope` there is a introduction of how to get started, followed by a introduction of how telescope is configured in `:help telescope.setup`, followed by documentation on how telescope can be called in `:help telescope.command` followed by an intro to builtins in `:help telescope.builtin` (most of this is outlined in the first 100 lines of the help file, so pretty accessible in my opinion).

But if you just want test out things without configuring things you can do `:Telescope find_files hidden=true no_ignore=true` this does `--hidden` and `--no-ignore`

**Comment by t0mri** [comment]
> Running into the same issue. Are you saying to put `no_ignore = true` in the telescope config? E.g.
> 
> ```lua
> use {
>         'nvim-telescope/telescope.nvim', tag = '0.1.4',
>         -- or, branch = '0.1.x',
>         requires = { { 'nvim-lua/plenary.nvim' } },
>         pickers = {
>             find_files = {
>                 no_ignore = true
>             }
>         }
>     }
> ```
> 
> This does not work for me. I'm also not finding the right documentation on how I could use `no_ignore` when invoking `require('telescope.builtin').find_files`

this is how im doing it now

```lua
telescope.setup({
  pickers = {
    find_files = {
      find_command = {
        "rg",
        "--no-ignore",
        "--hidden",
        "--files",
        "-g",
        "!**/node_modules/*",
        "-g",
        "!**/.git/*",
      },
    },
  },
  extensions = {
    file_browser = {
      hidden = { file_browser = true, folder_browser = true },
      prompt_path = true,
    },
  },
})
```

again thanks a lot @Conni2461

**Comment by avahe-kellenberger** [comment]
Thanks for the example, I didn't really understand what he was saying
