### ISSUE TITLE
Fixup/Enhancement: We should make overriding default pickers work more consistently

### ISSUE THREAD

**Issue by tjdevries** [nvim-telescope/telescope.nvim#277]
We should make it easier to override the default sorters, since not every builtin currently respects the config flags.

**Comment by tami5** [comment]
Our leader is back :smile: , yes I agree @tjdevries

**Comment by tjdevries** [comment]
Outline (for someone else to do):
- make all `sorter = ...` for the pickers take some function
- function that takes the `opts`, checks if `opts.sorter` is in keys, uses that if so
- otherwise, uses the `file_sorter`, `generic_sorter` or whatever type of sorter as specified.

We should add more documentation about this somewhere as well.

**Comment by nc1337** [comment]
Can't we just reuse `utils.get_default` from `utils.lua`? I am noob in lua so please don't mind it this is the wrong way?

**Comment by a420gmoon** [comment]
where from I will start Enhancement default pickers work more consistently.
