### ISSUE TITLE
Using line wrap in previewer causes wrong line to be highlighted

### ISSUE THREAD

**Issue by rjurga** [nvim-telescope/telescope.nvim#2777]
### Description

I want lines to wrap in the previewer. For that, I do something like the config suggested in the readme:

```
vim.api.nvim_create_autocmd("User", {
  pattern = "TelescopePreviewerLoaded",
  callback = function(args)
      vim.wo.wrap = true
  end,
})
```

However, this causes the wrong line to be highlighted in the previewer. If you use Telescope to search for `foo`, the line containing `foo` will not be vertically centered in the previewer, it will be lower (I guess due to the wrapping happening *after* the centering), and it will not be the line that is highlighted (I guess for the same reason).

Is there some way to set the wrapping while also getting the correct line to be centered and highlighted? I have no insight into what is the real cause of the misbehavior, but some naive guesses: the wrapping would have to be set in an event that occurs earlier than `TelescopePreviewerLoaded`, before the view is centered and the result line highlighted?

Please let me know if I can provide additional useful info.

### Neovim version

```markdown
NVIM v0.9.4                                                                                                             Build type: RelWithDebInfo                                                                                              LuaJIT 2.1.1696883897
```

### Operating system and version

Windows 10

### Telescope version / branch / rev

telescope 0.1.13

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0 (rev af6b6c543b)
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured
```

### Steps to reproduce

1. Add to init file:
```
vim.api.nvim_create_autocmd("User", {
  pattern = "TelescopePreviewerLoaded",
  callback = function(args)
      vim.wo.wrap = true
  end,
})
```

2. Use something like builtin.live_grep to make a search
3. Look at the preview window

### Expected behavior

I would like the line containing the result to be centered in the preview window and to be highlighted.

### Actual behavior

If there are some lines that are wrapped above the line containing the result, then the result line is not centered and is not the one that is highlighted.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]

-- Additional config required:

-- Wrap lines in previewer
vim.api.nvim_create_autocmd("User", {
    pattern = "TelescopePreviewerLoaded",
    callback = function(args)
        vim.wo.wrap = true
    end,
})
```

**Comment by MovieMaker93** [comment]
Hi @rjurga, can you post a screenshot of the actual behaviour?

**Comment by rjurga** [comment]
Sorry for the very late reply.

I tested this again with the latest nvim/telescope release, and it works fine now. So it likely got fixed since the time I first raised the issue.
