### ISSUE TITLE
Position of the selected line in vim-buffer vimgrep preview should be customizable

### ISSUE THREAD

**Issue by sankantsu** [nvim-telescope/telescope.nvim#2786]
**Is your feature request related to a problem? Please describe.**

Vim-buffer vimgrep previewer (e.g. `live_grep`) always shows selected line at the center of preview window.
This behavior is usually preferable, but sometimes it is useful to show selected line near the top or bottom of the window.

For example, I am using [telescope-heading.nvim](https://github.com/crispgm/telescope-heading.nvim) extension plugin and I prefer the heading line preview appears at the top of preview window.

**Describe the solution you'd like**

Add entry field to change the relative position of `lnum` in preview window of `previewers.vim_buffer_vimgrep()` previewer.
For example, `start` field which takes integer value indicating the start line of the preview (like `previewers.qflist()`).
Other possible option is `anchor` field with simple string value ("top", "middle" or "bottom"). This might be enough for most use-cases and easier to configure, but is less flexible.

**Describe alternatives you've considered**

- Use termopen previewer

`previewers.qflist()` (termopen previewer) provides `start` and `finish` entry field to customize the range of preview window (`finish` field is usually not very useful, because `less` pager is used by default and load entire file contents ignoring `finish` field value).
This method works, but syntax-highlight for some file type (especially vim help text) does not work.

- Creating custom previewer

This method also works, but buffer previewer implementation is relatively complex and also cannot benefit from future enhancement of builtin previewers.

**Additional context**

[#2611](https://github.com/nvim-telescope/telescope.nvim/pull/2611) added support for multi-line highlighting for `vim_buffer_vimgrep` previewer, but it is not addressing the position of selected line in the preview window.
Instead, it always shows middle line of the highlighted area at the center of the preview window.

Here is a screenshot describing what I want to achieve.
This example is selecting headings of vim help text using `telescope-heading.nvim`.

<img width="1470" alt="issue_description" src="https://github.com/nvim-telescope/telescope.nvim/assets/52688583/65bb96ff-71d8-404f-9a9e-22e539ec32d6">

**Comment by sankantsu** [comment]
After careful reading of documentation and codebase (`previewers/buffer_previewer.lua`), I successfully have written a custom previewer for my own purpose.
Here is a working example for those who interested in creating your own custom previewer (run `:luafile %`).

```lua
local previewers = require "telescope.previewers"
local conf = require("telescope.config").values

local ns = vim.api.nvim_create_namespace("")

local my_previewer = function()
  local jump_to_line = function (self, bufnr, entry)
    vim.api.nvim_buf_clear_namespace(bufnr, ns, 0, -1)
    vim.api.nvim_buf_add_highlight(bufnr, ns, "TelescopePreviewLine", entry.lnum-1, 0, -1)
    vim.api.nvim_win_set_cursor(self.state.winid, { entry.lnum, 0 })
    vim.api.nvim_buf_call(bufnr, function()
      vim.cmd "norm! zt"
    end)
  end
  return previewers.new_buffer_previewer {
    title = "Test previewer",
    get_buffer_by_name = function (self, entry)
      return entry.path
    end,
    define_preview = function (self, entry)
      local p = entry.path
      return conf.buffer_previewer_maker(p, self.state.bufnr, {
        bufname = self.state.bufname,
        winid = self.state.winid,
        callback = function(bufnr)
          jump_to_line(self, bufnr, entry)
        end,
      })
    end,
  }
end

require("telescope.builtin").live_grep({ previewer = my_previewer() })
```

General and easy-to-configure interface for customizing preview range seems to be hard, and now I think it is better to create external previewer for this purpose. So I will close this issue.
Thank you for nice plugin and thorough documentation!

**Comment by jamestrew** [comment]
awesome! glad you were able to come up with a custom solution.
