### ISSUE TITLE
Lazy loading extension in 0.1.x

### ISSUE THREAD

**Issue by qRoC** [nvim-telescope/telescope.nvim#2788]
### Description

From document (https://github.com/nvim-telescope/telescope.nvim/blob/0.1.x/README.md#loading-extensions)

>> You may skip explicitly loading extensions (they will then be lazy-loaded), but tab completions will not be available right away.

But this does not work.

Master branch: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/command.lua#L197
0.1.x branch: https://github.com/nvim-telescope/telescope.nvim/blob/0.1.x/lua/telescope/command.lua#L192

### Neovim version

```markdown
NVIM v0.10.0-dev-1507+g267c346e2-Homebrew
Build type: Release
LuaJIT 2.1.1699180677
```

### Operating system and version

macos 14

### Telescope version / branch / rev

0.1.x

### checkhealth telescope

```markdown
-
```

### Steps to reproduce

-

### Actual behavior

error 'Unknown command'

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Yeah sorry it's looks like it's non-functional on telescope 0.1.x but it looks to be working on master. I think it's a readme feature documentation misalignment issue. I don't think this ever worked on 0.1.x.

**Comment by Conni2461** [comment]
the commit wasn't backported because it was marked as feat (and semver https://semver.org says you should only backport bugfixes): https://github.com/nvim-telescope/telescope.nvim/commit/a19770625aed49ad2a9f591a5e3946707f7359f6

But we can argue that its actually a bugfix (as the docs state that lazy loading should work) and then backport the patch an cut a new release. I've a couple of other commits that could be part of that release, so i'll probably do that today

**Comment by Conni2461** [comment]
was just ported back to 0.1.x

https://github.com/nvim-telescope/telescope.nvim/commit/d90956833d7c27e73c621a61f20b29fdb7122709

0.1.5 release is done in the next few minutes
