### ISSUE TITLE
git_branches with pattern always returns empty list

### ISSUE THREAD

**Issue by adaviloper** [nvim-telescope/telescope.nvim#2790]
### Description

I feel like I might be doing something wrong, but when I try passing a pattern to the `git_branches` builtin picker, nothing happens.

I've tried calling the following with the same results:
```
:lua require('telescope.builtin').git_branches({ pattern = 'feat' })
:Telescope git_branches pattern='feat'
```
I have several branches that show up when I do just `:lua require('telescope.builtin').git_branches()` and then filter down by typing `feat`.

What I am expecting to happen is that it would launch the finder with a pre-filtered list of any branches that match that pattern.

Am I   simply misunderstanding how `pattern` is intended to be used?

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1697887905
```

### Operating system and version

MacOS Ventura 13.5.2

### Telescope version / branch / rev

telescope 0.1.4

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.1

===== Installed extensions ===== ~

Telescope Extension: `aerial` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `notify` ~
- No healthcheck provided
```

### Steps to reproduce

```
:lua require('telescope.builtin').git_branches({ pattern = 'feat' })
:Telescope git_branches pattern='feat'
```
1. Have multiple git branches pulled locally
2. Enter NeoVim
3. Run one of the following commands (replace the patter value with whatever makes sense for your local branches)

### Expected behavior

Should bring up a list of all branches that match the provided `pattern` key.

### Actual behavior

Nothing happens. Code runs, but the results list is empty, so nothing pops up.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
It branches is using `git  for-each-ref` under the hood so the pattern to match isn't quite branch names but rather refs. This is understandable a little confusing considering the name of the picker.

You can try something like `pattern='refs/**/feature*'`. Should work better.

**Comment by adaviloper** [comment]
@jamestrew Incredible! Thank you for the help and apologies for the inconvenience on something that was seemingly just my own ignorance!
