### ISSUE TITLE
New Picker idea - git diff

### ISSUE THREAD

**Issue by ColinKennedy** [nvim-telescope/telescope.nvim#2792]
**Is your feature request related to a problem? Please describe.**
I recently learned of [git jump](https://github.com/git/git/blob/master/contrib/git-jump/git-jump) and it's awesome. Using some simple lua + [hydra.nvim](https://github.com/anuvyklack/hydra.nvim) I've effectively replicated a `git add -p` but unlike that view, which is read-only and can only advance in one direction, Neovim buffers are editable so if a line isn't quite right, I can modify the lines, head to another file, and do whatever I need just before staging them. It makes adding/committing a lot easier.

https://github.com/nvim-telescope/telescope.nvim/assets/10103049/26abea2a-85ef-420e-995f-8da31dc55f6c

Anyway, the whole thing is quickfix driven, which made me think of Telescope. I was wondering if folks would be interested in contributing this back, as a basic file+line number picker.

**Comment by jamestrew** [comment]
Thanks for reaching out but unfortunately, I don't think we're adding new pickers to telescope at the moment without significant interest from one of the maintainers (see https://github.com/nvim-telescope/telescope.nvim/issues/1228 for more context).

For any new pickers, we encourage users to create them as telescope extensions. https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md

**Comment by ColinKennedy** [comment]
I was unclear in my earlier message. What I meant was "If I made an extension, would you consider it useful + would like to add it to https://github.com/nvim-telescope/telescope.nvim/wiki/Extensions"?

**Comment by jamestrew** [comment]
@ColinKennedy oh yes of course. That'll be awesome.
I'll mark this as closed but feel free to ask questions if you have any.
