### ISSUE TITLE
Intermittent error when trying to use Telescope [E5108]

### ISSUE THREAD

**Issue by Remi-Godin** [nvim-telescope/telescope.nvim#2796]
### Description

The issue happens frequently, but not all the time. Sometimes, everything works fine.

This issue happens when trying to use Telescope after opening Neovim. Sometimes it will throw an error, sometimes it wont. Waiting after opening neovim before trying to use Telescope does not seem to change anything, neither does opening a file first.

Was running stable nvim, tried Telescope version 0.1.3 and 0.1.4, still getting the error. Moved to the nightly nvim build and tried both telescope versions and still getting the error. I tried building a new neovim config from scratch since I thought perhaps there was an issue in my config but still getting the same issue.

Link to my neovim config: https://github.com/Remi-Godin/.dotfiles/tree/main/nvim

I saw people encountered similar errors in the past but were fixed with the latest update. Since it is still not working for me, I assume the issue might be different.

I get this error when using my keybindings:
```
E5108: Error executing lua: ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: Invalid 'event': 'User TelescopeFindPre'                                  
stack traceback:
        [C]: in function 'nvim_exec_autocmds'
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: in function 'find'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:350: in function 'v'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:595: in function 'v'
        ...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:511: in function <...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:478>
```
Or I get this error if opening Telescope through the Neovim command line with `:Telescope` or `:Telescope find_files`:
```
Error executing Lua callback: ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347:
 Invalid 'event': 'User TelescopeFindPre'
stack traceback:
        [C]: in function 'nvim_exec_autocmds'
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: in function 'find'
        ...lazy/telescope.nvim/lua/telescope/builtin/__internal.lua:119: in function 'v'
        ...lazy/telescope.nvim/lua/telescope/builtin/__internal.lua:1384: in function 'v'
        ...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:511: in function <...cker/
start/telescope.nvim/lua/telescope/builtin/init.lua:478>
        ...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:188: in function 'run_comm
and'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:229: in function 'load_com
mand'
        ...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:108: in function <...ocal/
share/nvim/lazy/telescope.nvim/plugin/telescope.lua:107>

```

### Neovim version

```markdown
NVIM v0.10.0-dev-1643+gee276f875
Build type: RelWithDebInfo
LuaJIT 2.1.1700008891
```

### Operating system and version

Pop!_OS 22.04 LTS

### Telescope version / branch / rev

telescope 0.1.4

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.3.1
```

### Steps to reproduce

1. Open Neovim
2. Open Telescope

### Expected behavior

Telescope should open without errors.

### Actual behavior

Sometimes Telescope opens without errors, sometimes I get an error when trying to open Telescope.

### Minimal config

```Lua
local M = {
    "nvim-telescope/telescope.nvim",
    version = "0.1.4",
    dependencies = "nvim-lua/plenary.nvim",
}

M.config = function()
    local builtin = require('telescope.builtin')
    vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
    vim.keymap.set('n', '<leader>pg', builtin.live_grep, {})
end

return M
```

**Comment by jamestrew** [comment]
Just update telescope to v0.1.3+
https://github.com/nvim-telescope/telescope.nvim/issues/2758#issuecomment-1778158677

**Comment by Remi-Godin** [comment]
As stated in my post, I already tried 0.1.3 and 0.1.4 and this did not fix my issue. Any other suggestions?

**Comment by jamestrew** [comment]
Hmm.. not sure. Maybe try deleting telescope and reinstall it? There's nothing we can do on the telescope side since that line doesn't even exist anymore. This error is straight up not possible on newer releases.

**Comment by Remi-Godin** [comment]
That worked, thanks! I guess I had leftover stuff from packer and I think that was what was creating the issue. Pretty sure the Lazy stuff was fine but sometimes there was a conflict between the new Lazy config and the old Packer one when Neovim would start up. 

Sorry for the duplicate issue. I didn't realize I forgot to clear out everything before I made the switch to Lazy.
