### ISSUE TITLE
Opening a file with find_files puts me into insert mode

### ISSUE THREAD

**Issue by Charlie-83** [nvim-telescope/telescope.nvim#2802]
### Description

This is super inconsistent. I will be using telescope just fine and then it will start putting me into insert mode every time I open a file. When this is happening, other methods of opening files such as with `:e` or nvimtree are fine. Exiting and reopening nvim usually fixes this although this issue is sometimes present as soon as I open nvim. My whole nvim config is in my `dotfiles` repo.

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891
```

### Operating system and version

Arch btw

### Telescope version / branch / rev

84c5a71

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.0.2
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities
```

### Steps to reproduce

`:Telescope find_files`

### Expected behavior

Opening file leaves me in normal mode

### Actual behavior

Opening file leaves me in insert mode

### Minimal config

```Lua
https://github.com/Charlie-83/.dotfiles/tree/master/nvim

I know that this isn't minimal, but I wasn't able to find a minimal config that reproduces. I will continue trying and update here if/when I find one
```

**Comment by Shougo** [comment]
It is dup of https://github.com/nvim-telescope/telescope.nvim/issues/2766.

**Comment by jamestrew** [comment]
Closing as it's a duplicate
