### ISSUE TITLE
LSP Code Action Previewer

### ISSUE THREAD

**Issue by ribru17** [nvim-telescope/telescope.nvim#2809]
**Describe the solution you'd like**
It would be great to have something like the `lsp_references` previewer but for code actions, showing a list of actions and a diff indicating what they would do.

**Describe alternatives you've considered**
[fzf-lua](https://github.com/ibhagwan/fzf-lua) got this functionality recently, but I would like to stick to Telescope :)

**Additional context**
Some reference for how fzf-lua did it: https://github.com/ibhagwan/fzf-lua/blob/6583f80e4e1e0dc4e6ee2c8c74822b727fcbc984/lua/fzf-lua/previewer/codeaction.lua

**Comment by jamestrew** [comment]
That's pretty nifty but we don't even have a code action picker as one of our builtins. And we're currently pretty reluctant on adding new pickers. Maybe someday.

For more immediate term, I think it would be a great idea for a telescope extension and I'd be willing to offer some advice/help if anyone is interested in working on one.

**Comment by Conni2461** [comment]
We have a telescope-ui-select repo which already has some special stuff for code actions (we inject the lsp client name in the display and a little bit more, stuff that isnt part of vim.select), we can add that there, as well. But this should never be part of telescope core, having this here would just be duplicated code, code already present in neovim.

So extending our official ui-select repo is fine with me

**Comment by ribru17** [comment]
Ok thanks, I will raise the issue there
