### ISSUE TITLE
Add results to location list

### ISSUE THREAD

**Issue by serhez** [nvim-telescope/telescope.nvim#2821]
Would it be possible to have a mapping similar to `C-q` for sending the results to the location list? I prefer using the location list to the quickfix list, as the earlier allows me to have different lists of items in complex scenarios, e.g., searching references of a function, and then searching references of another function called within the first, etc. In these scenarios, I like opening several windows and using loclists.

**Comment by jamestrew** [comment]
Yes it's possible and we have actions build to support it.
If you'd like to replace the mappings for quickfix list with location list, add the following mappings to your telescope config:
```lua
local actions = require("telescope.actions")
require("telescope").setup({
  defaults = {
    mappings = {
      i = {
        ["<C-q>"] = actions.send_to_loclist + actions.open_loclist,
        ["<M-q>"] = actions.send_selected_to_loclist + actions.open_loclist,
      },
      n = {
        ["<C-q>"] = actions.send_to_loclist + actions.open_loclist,
        ["<M-q>"] = actions.send_selected_to_loclist + actions.open_loclist,
      },
    },
  },
})
```

Closing this but feel free to ask questions :+1:

**Comment by serhez** [comment]
@jamestrew fantastic, thank you very much!
