### ISSUE TITLE
Add on_change callback option to colorscheme picker

### ISSUE THREAD

**Issue by greidinger-reis** [nvim-telescope/telescope.nvim#2826]
**Is your feature request related to a problem? Please describe.**

The colorscheme picker currently only serves the purpose of changing the colorscheme on the active vim instance, but it would be nice to have an option to do stuff with the new value selected on the colorscheme picker (persist the colorscheme on a file somewhere)

**Describe the solution you'd like**

A callback function option named `on_change` on the `pickers.colorscheme` table, that takes new_value and old_value as arguments.
This fix can be achieved in 3 lines of code.

**Describe alternatives you've considered**

I dug around the `Picker` source code and tried registering an `on_complete` callback on the `pickers.colorscheme` table, but I wasn't successful on implementing my callback function that receives the new selected value. It's probably possible to do it but it's not a very good experience trying to do that.

**Additional context**

This is what I would like to do with this callback function:

```lua
require('telescope').setup({
    pickers = {
        colorscheme = {
            enable_preview = true,
            on_change = function(new_val, old_val)
                local file = io.open(vim.fn.stdpath('config') .. '/lua/colorscheme.lua', 'w')
                if file then
                    file:write('vim.cmd("colorscheme ' .. new_val .. '")')
                    file:close()
                end
            end
        },
    }
})
```
then require this file on my `init.lua`
```lua
require("colorscheme")
```

**Comment by greidinger-reis** [comment]
I'm working on this

**Comment by jamestrew** [comment]
If I'm honest, I'm a little hesitant about adding an option like this at the individual picker level. I think it sets a slippery precedence for adding a bunch of similar but slightly different options for all the pickers.

Either way, there exists `ColorScheme` and `ColorSchemePre` autocommand events you can use to achieve this so you won't be restricted to using just telescope for doing arbitrary things when a colorscheme changes. I think this is the best way to do what you're trying to do.

Alternatively, to stick with just telescope, something like this could work:
```lua
local actions = require("telescope.actions")
local action_state = require("telescope.actions.state")
require("telescope").setup({
  pickers = {
    colorscheme = {
      mappings = {
        i = {
          ["<C-o>"] = function(prompt_bufnr)
            local selection = action_state.get_selected_entry()
            local old = vim.cmd.colorscheme()
            local new = selection.value

            actions.close(prompt_bufnr)
            vim.cmd.colorscheme(new)
            -- do whatever you want with old/new
          end,
        },
      },
    },
  },
})
```

For these reasons, I'm going to close this issue and the associated PR. Open to any questions if you have any.

**Comment by greidinger-reis** [comment]
Understandable. Thanks for the tips. I'll use that autocmd instead.

**Comment by greidinger-reis** [comment]
I think this would be nice to have on a section in the wiki [configuration recipes](https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes)
