### ISSUE TITLE
Go to definiton/ Go to reference are not taking the correct size

### ISSUE THREAD

**Issue by Ethnical** [nvim-telescope/telescope.nvim#2838]
### Description

 The two definitions/ references do not take the full space (that can be a bit annoying to check the value). 

![image](https://github.com/nvim-telescope/telescope.nvim/assets/23560242/7343ce90-fd4a-4dc0-9412-b4111b4b8b7b)

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.4/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS

### Telescope version / branch / rev

telescopev rev -> e065145

### checkhealth telescope

```markdown
e065145
```

### Steps to reproduce

Using the go-to definition on an arbitrary definition/reference if there are multiple definitions (and the terminal is on full screen) the size of the terminal should be at the max to have reproduce the bug.

### Expected behavior

the references should take the full size of the telescope windows without being cut in the half like on the screenshot.

### Actual behavior

The path is shown but cut in half. 

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Yeah I agree. I think this is a long (ish) standing annoyance https://github.com/nvim-telescope/telescope.nvim/issues/2121#issuecomment-1211196978

I can try to take a look if I can find some time. PR is welcome as well.
