### ISSUE TITLE
Create buffers for non-existing files directly inside the `find_files` picker

### ISSUE THREAD

**Issue by jaywonchung** [nvim-telescope/telescope.nvim#2839]
**Is your feature request related to a problem? Please describe.**

When I want to open some file, I automatically reach the `find_files` picker. Now sometimes, there are files that **must** be in my repository, like `README.md`, and thus if I found the urge to open it and if it does not exist, I want to create it. Currently in such cases, I close the picker and type `:e REAMDE.md` (or alike). This is mildly annoying.

**Describe the solution you'd like**

When `rg` returns zero entries to a `find_files` query, and when the user invokes an action that normally opens a file in a buffer (`actions.select_vertical`, `actions.file_tab`, etc), the picker will close and a new empty buffer will open (with path = user's query). Invoking `:w<CR>` in that buffer will actually create the file.

I think this is basically what `:e`, `:vsp`, etc do; they open the path if it exists, and if not, just opens an empty buffer that will create the file on `:w`.

This changes the behavior of file-open actions and I think this ought to be an opt-in feature.

**Additional context**
I think this breaks an invariant of the `find_files` picker -- that it is *read-only*. So I wanted to see if the maintainers are fine with this feature being added before I actually work on it. Thanks a lot!

**Comment by jamestrew** [comment]
I think this would be too opinionated and little more complicated than "just create a file if a matching file doesn't exist on `<CR>`".

For instance, what if `./README.md` doesn't exist but `./inner/README.md` exists and you want to create `./README.md`. The latter will still be matched. We can account for this by making it an explicit action. But what about folders? Do we support both relative and absolute paths? If it's an action, we can now opt to overwrite an existing file, etc etc.

It's probably easiest/best? to implement this as a personal custom action
```lua
local create_file = function(prompt_bufnr)
  local prompt = action_state.get_current_line()
  ---@type Path
  local prompt_path = Path:new(prompt)
  local ok
  if prompt:match("/$") then
    ok = prompt_path:mkdir({ parents = true, exists_ok = false })
  else
    ok = prompt_path:touch({ parents = true })
  end

  if ok then
    actions.close(prompt_bufnr)
    vim.cmd.e(prompt_path:absolute())
  end
end
```
Having written this snippet, I guess I forgot you maybe don't even want to create the file, just the buffer. Should be an easy tweak. I can help with questions as well.

**Comment by jaywonchung** [comment]
Thanks for your response! For others who might come across this need, this is the full snippet that does not attempt to create directories or files:

```lua
local actions = require'telescope.actions'
local action_state = require'telescope.actions.state'
local Path = require'plenary.path'

local create_buffer = function(prompt_bufnr)
  local prompt = action_state.get_current_line()
  local prompt_path = Path:new(prompt)
  actions.close(prompt_bufnr)
  vim.cmd.tabedit(prompt_path:absolute())
end

require'telescope'.setup{
  defaults = {
    mappings = {
      i = {
        ["<C-CR>"] = create_buffer,
      },
    },
  },
}
```
