### ISSUE TITLE
Invalid quickfix list entries when using `send_selected_to_qflist` and marks picker

### ISSUE THREAD

**Issue by serranomorante** [nvim-telescope/telescope.nvim#2855]
### Description

Sending a list of global marks from telescope to quickfix works, but trying to open any buffer from the quickfix throws an empty buffer.

### Neovim version

```markdown
NVIM v0.10.0-dev-2039+g583c1de17
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info


edit: also happens on 0.9.5
```

### Operating system and version

arch linux

edit: also happens on macos ventura

### Telescope version / branch / rev

main

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.0.3
- OK fd: found fd 9.0.0

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `git_worktree` ~
- No healthcheck provided

Telescope Extension: `undo` ~
- No healthcheck provided
```

### Steps to reproduce

Setup a dummy tree directory like this (**edit: please use a directory under home `~/directory...`**):

```bash
├── file1.md
└── repro.lua

1 directory, 2 files
```
> file1.md must not be blank, write something like "file 1 test" as content

1. Open vim with `nvim --clean +'so repro.lua'`
2. Wait for lazy.nvim to install telescope and plenary and close the window
3. Open `file1.md` and add any global mark on it `mA`, or `mB` or `mC`, etc.
4. Open the marks picker with `:Telescope marks`
5. Send the results to the quickfix list `<C-q>`
6. Go to the quickfix list and try to open your mark with `Enter`

Notice how it will open an empty buffer instead of opening `file1.md`. I think there is a problem with the naming on telescope's side. Names should be absolute I believe but telescope prepends a `~/directory...`

### Expected behavior

Valid entries on the quickfix list

### Actual behavior

Telescope seems to send invalid entries (paths) to the quickfix list

### Minimal config

```Lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")
root = root:sub(-1) == "/" and root or root .. "/"

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. name
end

--------------------------------------------------------------------------------

local plugins = {
  { "nvim-lua/plenary.nvim", lazy = true },
  {
    "nvim-telescope/telescope.nvim",
    lazy = false,
    keys = {
      {
        "<leader>f'",
        function() require("telescope.builtin").marks() end,
        desc = "Find marks",
      },
    },
  },
}

--------------------------------------------------------------------------------

local lazypath = root .. "/plugins/lazy.nvim"
---@diagnostic disable-next-line: undefined-field
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
I'm not actually able to reproduce this. Did I miss a step?

https://github.com/nvim-telescope/telescope.nvim/assets/66286082/b4a6d2f6-e57d-44eb-a512-845ff192747d

**Comment by serranomorante** [comment]
> I'm not actually able to reproduce this. Did I miss a step?
> 
>  telescope-marks-repro.mp4

Thank you for sharing a video! When I use `/tmp/...` it also works for me. Try using a directory under home `~/directory...` and I believe you'll replicate the issue.
![t-rec_48](https://github.com/nvim-telescope/telescope.nvim/assets/43413954/9b63e749-97ef-4c0f-9b23-f5d4927e54cf)

**Comment by jamestrew** [comment]
Yeah the `~/` was an issue for quickfix lists.
Small fix. Should be good now. Thanks!
