### ISSUE TITLE
Can't open oldfiles picker in cwds containing special characters

### ISSUE THREAD

**Issue by pascalporedda** [nvim-telescope/telescope.nvim#2857]
### Description

When trying to open the oldfiles picker inside a directory that has special characters I'll just get the error notice below.

A pathname which triggers this:
`/Users/pascal/Library/Mobile\ Documents/iCloud~md~obsidian/Documents`

So yeah I'm working in a folder which resides in my iCloud drive.

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377
```

### Operating system and version

macOS 14.2.1

### Telescope version / branch / rev

telescope 0.1.x

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `git_worktree` ~
- No healthcheck provided

Telescope Extension: `live_grep_args` ~
- No healthcheck provided

Telescope Extension: `ui-select` ~
- No healthcheck provided
```

### Steps to reproduce

I'll add this later

### Expected behavior

The oldfiles picker just works as it does in file paths without special symbols.

### Actual behavior

E5108: Error executing lua: Vim:E874: (NFA) Could not pop the stack!
stack traceback:
        [C]: in function 'matchstrpos'
        ...lazy/telescope.nvim/lua/telescope/builtin/__internal.lua:542: in function <...lazy/telescope.nvim/lua/telescope/builtin/__internal.lua:541>
        vim/shared.lua: in function 'tbl_filter'
        ...lazy/telescope.nvim/lua/telescope/builtin/__internal.lua:541: in function 'v'
        ...lazy/telescope.nvim/lua/telescope/builtin/__internal.lua:1384: in function 'v'
        .../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:541: in function 'oldfiles'
        /Users/pascal/.config/nvim/lua/lzrvim/telescope.lua:150: in function </Users/pascal/.config/nvim/lua/lzrvim/telescope.lua:150>

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Thanks, this should be fixed.
I was able to reproduce and figure out that the cwd path was being used as a regex pattern when checking whether a given file is in the cwd.
