### ISSUE TITLE
so,why,help me,

### ISSUE THREAD

**Issue by JanSky520** [nvim-telescope/telescope.nvim#2869]
### Description

![574830584a5e852e4f112ed7e9bc8134](https://github.com/nvim-telescope/telescope.nvim/assets/79568068/f50889f9-4e34-47d8-ae57-102a2b044f94)

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
```

### Operating system and version

archlinux

### Telescope version / branch / rev

Telescope 0.1.5

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 9.0.0

===== Installed extensions ===== ~
```

### Steps to reproduce

without

### Actual behavior

:Telescope find_files
:Telescope live_grep

### Minimal config

```Lua
require('telescope').setup{

}
```

**Comment by jamestrew** [comment]
Make sure you're on telescope 0.1.3+.
This error means your telescope version isn't up to date.

https://github.com/nvim-telescope/telescope.nvim/issues/2735#issuecomment-1848786066
