### ISSUE TITLE
Allow toggeling "hidden files" option via telescope action

### ISSUE THREAD

**Issue by Tal500** [nvim-telescope/telescope.nvim#2874]
I would like an option to toggle "show hidden files" as a telescope action during file search/live grep, say by `<C-h>`.

Currently we need to determine if to show hidden files before we launch the dialog.

ref: AstroNvim/AstroNvim#2423

**Comment by jamestrew** [comment]
I personally use something like this
```lua
local my_find_files = function(opts, no_ignore)
  opts = opts or {}
  no_ignore = vim.F.if_nil(no_ignore, false)
  opts.attach_mappings = function(_, map)
    map({ "n", "i" }, "<C-h>", function(prompt_bufnr) -- <C-h> to toggle modes
      actions.close(prompt_bufnr)
      no_ignore = not no_ignore
      M.project_files({}, no_ignore)
    end)
    return true
  end

  if no_ignore then
    opts.no_ignore = true
    opts.hidden = true
    opts.prompt_title = "Find Files <ALL>"
    require("telescope.builtin").find_files(opts)
  else
    opts.prompt_title = "Find Files"
    require("telescope.builtin").find_files(opts)
  end
end

vim.keymap.set("n", "...", my_find_files)
```

But I don't frequently use it. I don't find the `hidden=true` option that helpful since with ripgrep, it gives you a bunch of `.git` files. You can definitely tweak it to improve it (using the `find_command` option to filter with `--glob`) but I have other means of getting hidden files.

And this tweak-ability and how much of a personal preference plays role in these kinds of actions is why I don't think this deserves to come built in with telescope.

Hope that helps.

**Comment by Tal500** [comment]
> I personally use something like this
> 
> ```lua
> local my_find_files = function(opts, no_ignore)
>   opts = opts or {}
>   no_ignore = vim.F.if_nil(no_ignore, false)
>   opts.attach_mappings = function(_, map)
>     map({ "n", "i" }, "<C-h>", function(prompt_bufnr) -- <C-h> to toggle modes
>       actions.close(prompt_bufnr)
>       no_ignore = not no_ignore
>       M.project_files({}, no_ignore)
>     end)
>     return true
>   end
> 
>   if no_ignore then
>     opts.no_ignore = true
>     opts.hidden = true
>     opts.prompt_title = "Find Files <ALL>"
>     require("telescope.builtin").find_files(opts)
>   else
>     opts.prompt_title = "Find Files"
>     require("telescope.builtin").find_files(opts)
>   end
> end
> 
> vim.keymap.set("n", "...", my_find_files)
> ```
> 
> But I don't frequently use it. I don't find the `hidden=true` option that helpful since with ripgrep, it gives you a bunch of `.git` files. You can definitely tweak it to improve it (using the `find_command` option to filter with `--glob`) but I have other means of getting hidden files.
> 
> And this tweak-ability and how much of a personal preference plays role in these kinds of actions is why I don't think this deserves to come built in with telescope.
> 
> Hope that helps.

Thanks! But can you explain the code more for a newbe like me?

I didn't understand what is `M.project_files({}, no_ignore)` and how it do the magic.
Why is there `actions.close(prompt_bufnr)` before? If I understand correctly, it means that you close the telescope popup, but what prompt it back here?

**Comment by jamestrew** [comment]
Oh sorry that was a bad example, leaked some of my own original code + didn't explain imports.
```lua
local my_find_files
my_find_files = function(opts, no_ignore)
  opts = opts or {}
  no_ignore = vim.F.if_nil(no_ignore, false)
  opts.attach_mappings = function(_, map)
    map({ "n", "i" }, "<C-h>", function(prompt_bufnr) -- <C-h> to toggle modes
      local prompt = require("telescope.actions.state").get_current_line()
      require("telescope.actions").close(prompt_bufnr)
      no_ignore = not no_ignore
      my_find_files({ default_text = prompt }, no_ignore)
    end)
    return true
  end

  if no_ignore then
    opts.no_ignore = true
    opts.hidden = true
    opts.prompt_title = "Find Files <ALL>"
    require("telescope.builtin").find_files(opts)
  else
    opts.prompt_title = "Find Files"
    require("telescope.builtin").find_files(opts)
  end
end

vim.keymap.set("n", "...", my_find_files) -- you can then bind this to whatever you want
```

This should be better. I also tweaked it pipe the old prompt into the new picker.
Basically this is a wrapper around `find_files` to keep track of a toggle-able boolean value `no_ignore`. It's adds a new keymap to an actions that will toggle `no_ignore`, capture the old prompt, close the picker and reopen it with the old prompt (and any other options) and the new picker is opened with the correct options to show hidden/ignored files.

**Comment by Tal500** [comment]
> I personally use something like this
> 
> ```lua
> local my_find_files = function(opts, no_ignore)
>   opts = opts or {}
>   no_ignore = vim.F.if_nil(no_ignore, false)
>   opts.attach_mappings = function(_, map)
>     map({ "n", "i" }, "<C-h>", function(prompt_bufnr) -- <C-h> to toggle modes
>       actions.close(prompt_bufnr)
>       no_ignore = not no_ignore
>       M.project_files({}, no_ignore)
>     end)
>     return true
>   end
> 
>   if no_ignore then
>     opts.no_ignore = true
>     opts.hidden = true
>     opts.prompt_title = "Find Files <ALL>"
>     require("telescope.builtin").find_files(opts)
>   else
>     opts.prompt_title = "Find Files"
>     require("telescope.builtin").find_files(opts)
>   end
> end
> 
> vim.keymap.set("n", "...", my_find_files)
> ```
> 
> But I don't frequently use it. I don't find the `hidden=true` option that helpful since with ripgrep, it gives you a bunch of `.git` files. You can definitely tweak it to improve it (using the `find_command` option to filter with `--glob`) but I have other means of getting hidden files.
> 
> And this tweak-ability and how much of a personal preference plays role in these kinds of actions is why I don't think this deserves to come built in with telescope.
> 
> Hope that helps.

Thanks! But can you explain the code more for a newbe like me?

I didn't understand what is `M.project_files({}, no_ignore)` and how it do the magic.
Why is there `actions.close(prompt_bufnr)` before? If I understand correctly, it means that you close the telescope popup, but what prompt it back here?

> Oh sorry that was a bad example, leaked some of my own original code + didn't explain imports.
> 
> ```lua
> local my_find_files
> my_find_files = function(opts, no_ignore)
>   opts = opts or {}
>   no_ignore = vim.F.if_nil(no_ignore, false)
>   opts.attach_mappings = function(_, map)
>     map({ "n", "i" }, "<C-h>", function(prompt_bufnr) -- <C-h> to toggle modes
>       local prompt = require("telescope.actions.state").get_current_line()
>       require("telescope.actions").close(prompt_bufnr)
>       no_ignore = not no_ignore
>       my_find_files({ default_text = prompt }, no_ignore)
>     end)
>     return true
>   end
> 
>   if no_ignore then
>     opts.no_ignore = true
>     opts.hidden = true
>     opts.prompt_title = "Find Files <ALL>"
>     require("telescope.builtin").find_files(opts)
>   else
>     opts.prompt_title = "Find Files"
>     require("telescope.builtin").find_files(opts)
>   end
> end
> 
> vim.keymap.set("n", "...", my_find_files) -- you can then bind this to whatever you want
> ```
> 
> This should be better. I also tweaked it pipe the old prompt into the new picker. Basically this is a wrapper around `find_files` to keep track of a toggle-able boolean value `no_ignore`. It's adds a new keymap to an actions that will toggle `no_ignore`, capture the old prompt, close the picker and reopen it with the old prompt (and any other options) and the new picker is opened with the correct options to show hidden/ignored files.

Thanks!

**Comment by aj-ats** [comment]
@jamestrew thanks for the examples and insight ! very hepfull

**Comment by bethsay** [comment]
@jamestrew Thanks for the solution. I used it without understanding but can see that it works.
I was hoping to add description with this
```lua
    map({ "n", "i" }, "<C-h>", function(prompt_bufnr) -- <C-h> to toggle modes
      local prompt = require("telescope.actions.state").get_current_line()
      require("telescope.actions").close(prompt_bufnr)
      no_ignore = not no_ignore
      my_find_files({ default_text = prompt }, no_ignore)
    end,{ desc = "Toggle hidden files"})
``` 
When i tried to get  telescope.action list (with "Ctrl+/" or "?"),
i see the mapping listed with other telescope actions
> \<C-H>  -> \<anonymous>
\<C-U>  -> preview_scrolling_up
\<C-D>  -> preview_scrolling_down

And a warning at the bottom of neovim
>  [telescope.action.which_key]: No name available for anonymous functions.

Thanks in advance.!
