### ISSUE TITLE
Allow changing layout_config.width with ivy

### ISSUE THREAD

**Issue by mizlan** [nvim-telescope/telescope.nvim#2886]
**Is your feature request related to a problem? Please describe.**
I can't seem to change the width with ivy theme.

**Describe the solution you'd like**
When I use layout_config.width, the window respects that.

**Describe alternatives you've considered**
Rewriting the ivy theme options in the layout_config.

Ivy theme doesn't seem to respect the width field.

**Comment by jamestrew** [comment]
Sorry the `bottom_pane` layout strategy that the ivy theme is based on doesn't take a `width` option. I think the ivy theme being full width is how it's "supposed to be" as its based on emacs' ivy.

I think we're being quite conservative with adding more options to layouts. People just end up wanting infinite flexibility. So instead we're offering ways people can create their own custom layouts. See here: https://github.com/nvim-telescope/telescope.nvim/pull/2572
