### ISSUE TITLE
Allow setting description for anonymous functions 

### ISSUE THREAD

**Issue by caligian** [nvim-telescope/telescope.nvim#2888]
How to set descriptions for mappings in attach_mappings? I cannot get the help menu to display descriptions for decorated functions (function within another anon function). I have tried to pass .desc in map options but that did not work either. 

This would be a very helpful addition to my toolkit because I can determine the number of args to pass to an action depending on whether it is a multiselection or not and bypass the getting the picker from prompt_bufnr and manually closing the window and then doing the task. It is causing a lot of boilerplate even for things like simply rm -r selected files in telescope-file-browser just to ensure that the descriptions show up after pressing.

```
function T:selected(bufnr, many)
  local picker = self.action_state.get_current_picker(bufnr)

  if picker then
    self.actions.close(bufnr)

    if many then
      return picker:get_multi_selection()
    end

    return self.action_state.get_selected_entry()
  end
end

function T:module()
  local mod = mtset({}, {
    __newindex = function(MOD, key, value)
      if key:match "^multi_" then
        rawset(MOD, key, function(bufnr)
          list.each(T:selected(bufnr, true), value)
        end)
      else
        rawset(MOD, key, function(bufnr)
          return value(T:selected(bufnr))
        end)
      end
    end,
  })

  return mod
end
```

If I were to use module defined above then it would result in 'anonymous' for 'CR' (Enter/default action)

**Comment by jamestrew** [comment]
I created a PR to address this.

But on a side note, your code snippet is a bit funky. You can get a list of path(s) with or without multi-select with `require "telescope._extensions.file_browser.utils".get_selected_files`.

**Comment by caligian** [comment]
It is a just a singleton module with all the telescope requires merged into the table. Thanks for looking into the matter. As far as file-browser is concerned, I understand your point but I have defined stuff for even buffers and find-files and some pickers of my own that need multiselection.

```
local mod = {}

function mod.bwipeout(bufnr)
  local _ = user.telescope()
  local sel = _:selected(bufnr, true)

  list.each(sel, function(x)
    print("Wiping out buffer " .. x.bufnr)
    vim.cmd("bwipeout! " .. x.bufnr)
  end)
end

function mod.nomodified(bufnr)
  local _ = user.telescope()
  local sels = _:selected(bufnr, true)

  list.each(sels, function(sel)
    print("Setting buffer status to nomodified: " .. vim.fn.bufname(sel.bufnr))
    vim.api.nvim_buf_call(sel.bufnr, function()
      vim.cmd "set nomodified"
    end)
  end)
end

...
```

3 lines can be easily eliminated if I use custom module with decoration. That would make it equivalent to simply working with tables with certain keys making picker development much faster
