### ISSUE TITLE
search file with finding file  but got "not .git directory"

### ISSUE THREAD

**Issue by lainegates** [nvim-telescope/telescope.nvim#2889]
### Description

Hi,

I try to find files under root directory with <space><space> .

But telecope.nvim tell me that "not a git directory"

![image](https://github.com/nvim-telescope/telescope.nvim/assets/5265648/23819f0f-9cd4-421f-a209-9254d7748508)

Is there a way to disable the setting that the root directory must be a git directory?

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```

### Operating system and version

ubuntu 20.04

### Telescope version / branch / rev

branch master commit 20efb38

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0 (rev 7ec2fd51ba)
- OK fd: found fd 9.0.0

===== Installed extensions ===== ~

Telescope Extension: `aerial` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `projects` ~
- No healthcheck provided
```

### Steps to reproduce

1. setup telescope.nvim in host environment and a git repo.
2. go into a docker environment.
3. link host `.local/share/nvim` to same directory inside docker.
4. start nvim inside docker with root directory of the git repo.

### Actual behavior

![image](https://github.com/nvim-telescope/telescope.nvim/assets/5265648/3c53d5ac-fbd3-45e0-9f08-c7f67dc21d4b)

telescope.nvim tells error when trying to searching file inside docker

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
Sorry just to clarify, you want to find files inside a non git directory?

It seems like you're using `:Telescope git_files` which - obviously needs to be from a git directory.

Try `:Telescope find_files`.

**Comment by lainegates** [comment]
> Sorry just to clarify, you want to find files inside a non git directory?
> 
> It seems like you're using `:Telescope git_files` which - obviously needs to be from a git directory.
> 
> Try `:Telescope find_files`.

@jamestrew  Thanks ! It is my mistake that `Telescope find_files` works, but `Telescope git_files` failed.
`Telescope git_files` failed because owner of the repo is `$USER in host`, not `root` in docker.
