### ISSUE TITLE
Some normal mode mappings don't work

### ISSUE THREAD

**Issue by AntonC9018** [nvim-telescope/telescope.nvim#2891]
### Description

Some default vim normal mode mappings don't work, while in a telescope window, e.g. `u`, `p`, possibly others.

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891
```

### Operating system and version

macOS Sonoma 14.2.1

### Telescope version / branch / rev

0.1.5

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions ===== ~
```

### Steps to reproduce

1. `:Telescope`
2. Type something
3. `Esc` to enter normal mode
4. `Vy` to copy (works, but V selects the caret too, which is intended?)
5. `p` doesn't work.

### Actual behavior

Pasting doesn't work?

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
-- just the default config
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
This is just the behavior of the prompt buffer using vim's `buftype='prompt'` option.

Normal commands are only available on the last line of the buffer. So `p` will work on the if you type in insert mode first to create a line and go back to normal mode and try to paste. It's a little weird, I'd admit. I can't seem to get `u` to work but `<c-r>` works and `:undo` works. Maybe some of this behavior is a bug, maybe there's a good reason I'm not sure.
But part of the point of prompt buffers is to restrict available commands so plugins using them don't have to handle arbitrary commands.

I'm not sure it's telescope's responsibility to "fix" them. Even if we wanted to, it could result in even less intuitive behaviors.

**Comment by AntonC9018** [comment]
Sure... Is there a way to change the buffer type telescope uses then? Because it's stupid imo that paste works in insert mode but not in normal mode, it just makes no sense whatsoever to me as a user

**Comment by jamestrew** [comment]
I think that would break more things 😕

**Comment by soulomoon** [comment]
I am wondering if we could fix that in `neovim`

**Comment by jamestrew** [comment]
I think it's intended behavior so I doubt it will be actioned.

From `:h prompt-buffer`
```
5. Using a prompt buffer				*prompt-buffer*

If you want to type input for the job in a Vim window you have a few options:
- Use a normal buffer and handle all possible commands yourself.
  This will be complicated, since there are so many possible commands.
```

Using a prompt buffer let's us control behaviors of keys in telescope without having to fight with regular buffer commands. This is at the cost of losing some potentially intuitive commands. 

You can somewhat compensate by forcing bindings through telescope, but some normal commands are harder to replicate than others just due to the behaviors of prompt-buffers.

```lua
require("telescope").setup({
  defaults = {
    mappings = {
      n = {
        ["u"] = { ":undo<CR>", type = "command" }, -- undo
        ["p"] = function(prompt_bufnr) -- put/paste, using `:put` doesn't work
          local picker = require("telescope.actions.state").get_current_picker(prompt_bufnr)
          local text = vim.fn.getreg('"')
          picker:set_prompt(text, false)
        end,
      },
    },
  },
})
```

We've added the insert mode `<C-w>` behavior back by default https://github.com/nvim-telescope/telescope.nvim/pull/1650

But I don't think there's much plans to add any more regular commands.
