### ISSUE TITLE
Default <C-Space> binding for fuzzy_refine conflicts with MacOS language switching

### ISSUE THREAD

**Issue by dzirtusss** [nvim-telescope/telescope.nvim#2896]
### Description

In MacOS default language switching is (and always has been) with `C-Space` (forward) and `C-S-Space` (backward).

Surely, it is possible to locally redefine `fuzzy_refine` to another key (e.g., I've done it for myself for `M-Space`), but maybe it is better to change it to some other default? Anything, but not `C-Space`

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377
```

### Operating system and version

macOS 14.3

### Telescope version / branch / rev

telescope 0.1.5

### checkhealth telescope

```markdown
-
```

### Steps to reproduce

-

### Expected behavior

Some other keymap for `fuzzy_refine`, not `C-Space`

### Actual behavior

Conflicts with MacOS language switching.

### Minimal config

```Lua
-
```

**Comment by Conni2461** [comment]
thats why i am the only one always arguing for the fact that we should not even map actions on default. You cant make everyone happy and i never owned a MacOS so i didn't know about the shortcut. Changing it now would be not worth the effort or introducing a breaking change. There will always be the next environment in which a shortcut doesnt work!

its documented how to map it, so users should just do it themself imo.
