### ISSUE TITLE
Telescope picker prevent the execution of autocmd

### ISSUE THREAD

**Issue by yifan0414** [nvim-telescope/telescope.nvim#2901]
### Description

I use the autocmd to open terminal with insert mode:
```
autocmd TermOpen * startinsert
```
like this
![image](https://github.com/nvim-telescope/telescope.nvim/assets/45898625/3b308f55-8f3c-43f1-a6b2-c0288f1180d8)

But When I open terminal with the telescope picker, it will not execute this autocmd
![image](https://github.com/nvim-telescope/telescope.nvim/assets/45898625/897cbc97-870b-49e3-bc94-3f4ae16931ed)

### Neovim version

```markdown
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2  x86_64 ubuntu

### Telescope version / branch / rev

the latest

### checkhealth telescope

```markdown
==============================================================================
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.3.1

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured
```

### Steps to reproduce

1. create a command picker
2. add a open terminal command to this picker
3. open this picker, select the entry

### Expected behavior

the autocmd for terminal will execute, which is insert mode

### Actual behavior

open terminal by telescope picker, normal mode

### Minimal config

```Lua
local command = {
  { "Open terminal", "terminal" },
}

function telescope_command_picker(commands)
  local actions, action_state, pickers, finders, conf = init_telescope_modules()

  pickers
    .new({}, {
      prompt_title = "Select a Command",
      finder = finders.new_table({
        results = commands,
        entry_maker = function(entry)
          return {
            value = entry[2],
            display = entry[1] .. ": " .. entry[2],
            ordinal = entry[1],
          }
        end,
      }),
      sorter = conf.generic_sorter({}),
      attach_mappings = function(prompt_bufnr)
        actions.select_default:replace(function()
          local selection = action_state.get_selected_entry()
          -- vim.api.nvim_out_write(selection.value .. "\n")
          actions.close(prompt_bufnr)
          vim.cmd(selection.value)
        end)
        return true
      end,
    })
    :find()
end

vim.keymap.set(
      "<Leader>ty",
      function()
        telescope_command_picker(command)
      end,
      { noremap = true, silent = true },
   )
```

**Comment by jamestrew** [comment]
Is this your custom picker?

You just need to add a `vim.schedule`.
```lua
actions.close(prompt_bufnr)
vim.schedule(function()
    vim.cmd(selection.value)
end)
```

**Comment by yifan0414** [comment]
> Is this your custom picker?
> 
> You just need to add a `vim.schedule`.
> 
> ```lua
> actions.close(prompt_bufnr)
> vim.schedule(function()
>     vim.cmd(selection.value)
> end)
> ```

Thanks
