### ISSUE TITLE
Inverse of `ctrl+q`

### ISSUE THREAD

**Issue by kallisti-dev** [nvim-telescope/telescope.nvim#2907]
Sending telescope items to quickfix with `ctrl+q` is quite handy, but sometimes I realize later that I need to update my search terms. It would be nice if there could be a way to perform the inverse operation, and load the result of `ctrl+q` back into a telescope picker to modify the search. 

Not sure if this is technically feasible in all cases, but maybe it could use the quickfix windows title to reconstruct the correct picker. For example the quickfix window has a title like `Live Grep (your search term here)` which could be parsed to determine which picker to load.  I don't think this approach would work with custom pickers, so I'm not sure if there's a generic solution to this. Maybe there are better ways to do this?

**Comment by Conni2461** [comment]
i somewhat confused about this issue. do you mean the `:Telescope quickfix` picker, which opens the current quickfixlist as telescope picker

**Comment by kallisti-dev** [comment]
That could potentially work well enough for the workflow I want. I didn't
know that's what it does, so I might try that.

But what I'm describing is slightly different, because it uses the original
picker initialized with the search string that was originally used. So for
example if the original picker used for the quickfix list was `live_grep`
this action would start another `live_grep` picker with those exact search
terms.

My idea was to resume based on the information in the quickfix list, so for
example it could see that the buffer title says something like `Live Grep
(search string here)`  and reconstruct the picker from that. This would
only work for builtins though and not custom pickers.

Maybe a "resume previous picker with the same search string" action already
exists and I just missed it.. but that would also work similarly enough
that I could just use that instead for a similar workflow of: use picker to
type a search string, load into quickfix, edit files, load picker again
with same search string, repeat

**Comment by jamestrew** [comment]
See `:h telescope.builtin.resume()`

**Comment by kallisti-dev** [comment]
> See `:h telescope.builtin.resume()`

Whoops! didn't see that one. That probably works just fine for my use-case. 

Trying to backtrack from a quickfix list in the way I'm suggesting is probably too error-prone, but I am not knowledgeable  enough about NeoVim internals to say for certain.

The only benefit over `telescope.builtin.resume()` would be that it could resume from any telescope-builtin-generated quickfix list, rather than just the last search.

**Comment by jamestrew** [comment]
> Trying to backtrack from a quickfix list in the way I'm suggesting is probably too error-prone

I'm inclined to agree. Not sure how we'd implement this in a predictable way across all our pickers (and third party pickers) without a ton of work.
I'll close this for this reason.
