### ISSUE TITLE
lsp_document_symbols preview error

### ISSUE THREAD

**Issue by smartding** [nvim-telescope/telescope.nvim#291]
### Description

I get the following error when running `builtin.lsp_document_symbols()`, and preview area is empty:
```
Error executing vim.schedule lua callback: telescope.nvim/lua/telescope/previewers.lua:375  Cursor position outside buffer
```
No such error when I run `builtin.lsp_workspace_symbols()`.

**Expected Behavior**

Should be preview in the preview area
**Actual Behavior**

error as described above and no preview
### Details

<details><summary>Reproduce</summary>

open any simple golang program, e.g.
```go
package main

import "fmt"

func main() {
	s := make([]int, 0, 3)
	fmt.Printf("len: %d, cap: %d, value: %v", len(s), cap(s), s)
}
```
and run builtin.lsp_document_symbols()

</details>

<details><summary>Environment</summary>

- nvim version: NVIM v0.5.0-881-g4537ff659
- Operating system: archlinux
- Telescope commit: 0f9fd84a9742e22294cfaf46f32bad9b29de0b31

</details>

<details><summary>Configuration</summary>
<p>
 

```lua
  require('telescope').setup{
    defaults = {
      borderchars = { '─', '│', '─', '│', '┌', '┐', '┘', '└'},
      color_devicons = false,
      set_env = { COLORTERM = 'truecolor' }
    }
  }

  -- load fzy native plugin
  require('telescope').load_extension('fzy_native')

```

**Comment by smartding** [comment]
I printed out the `entry.lnum` before this function call https://github.com/nvim-telescope/telescope.nvim/blob/0f9fd84a9742e22294cfaf46f32bad9b29de0b31/lua/telescope/previewers.lua#L375
the line number seems correct, though I'm not sure if it starts with 0 or 1

**Comment by Conni2461** [comment]
This line should be fine. I noticed that bug too. The fix is in #287 which is about to get merged by @tami5 :)

**Comment by Conni2461** [comment]
I messed that up when i reworked the buffers. I wasn't aware that more pickers use that previewer. Sorry for the inconveniences

**Comment by Conni2461** [comment]
Could you try the latest master and close the issue if it is fixed. Thanks

**Comment by smartding** [comment]
> Could you try the latest master and close the issue if it is fixed. Thanks

it's fixed, @tami5 is fast
