### ISSUE TITLE
Error after toggling preview

### ISSUE THREAD

**Issue by geril2207** [nvim-telescope/telescope.nvim#2914]
### Description

Error when trying to `preview_scrolling_right/preview_scrolling_left` after toggling preview window.
https://github.com/nvim-telescope/telescope.nvim/assets/62308020/db05dd62-e959-4ee2-8c8c-75e24b343a83

### Neovim version

```markdown
NVIM v0.10.0-dev-67255652
Build type: Release
LuaJIT 2.1.1707061634
```

### Operating system and version

linux

### Telescope version / branch / rev

236083884cfe6c874e03e6cb4e7cb08809c1333c

### checkhealth telescope

```markdown
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.0.3
- OK fd: found fd 8.7.1

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured
```

### Steps to reproduce

1. nvim -nu repro_conf.lua
2. `:Telescope` find_files or whatever you want
3. Toggle preview(`A-p` from my repro)
4. Toggle again
5. Execute preview scroll(`C-h`/`C-l` from my repro)

### Expected behavior

Without error

### Actual behavior

E5108: Error executing lua: ...e/nvim/lazy/telescope.nvim/lua/telescope/actions/set.lua:267: Invalid window id: 1011
stack traceback:
        [C]: in function 'nvim_win_get_height'
        ...e/nvim/lazy/telescope.nvim/lua/telescope/actions/set.lua:267: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'scroll_horizontal_previewer'
        .../nvim/lazy/telescope.nvim/lua/telescope/actions/init.lua:234: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:269: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mapp
ings.lua:268>

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"nvim-telescope/telescope.nvim",
				requires = {
					"nvim-lua/plenary.nvim",
					{ "nvim-telescope/telescope-fzf-native.nvim", run = "make" },
				},
			},
			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
_G.load_config = function()
	local actions = require("telescope.actions")
	local action_layout = require("telescope.actions.layout")

	require("telescope").setup({
		defaults = {
			mappings = {
				i = {
					["<ESC>"] = actions.close,
					["<M-p>"] = action_layout.toggle_preview,
					["<M-k>"] = actions.cycle_history_prev,
					["<M-j>"] = actions.cycle_history_next,
					["<C-j>"] = actions.preview_scrolling_down,
					["<C-k>"] = actions.preview_scrolling_up,
					["<C-l>"] = actions.preview_scrolling_right,
					["<C-h>"] = actions.preview_scrolling_left,
					["<M-v>"] = actions.select_vertical,
					["<M-h>"] = actions.select_horizontal,
					["<C-u>"] = false,
				},
			},
		},
	})
	require("telescope").load_extension("fzf")
	-- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing Telescope and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

**Comment by jamestrew** [comment]
Thanks! Should be good with the latest commit.
