### ISSUE TITLE
buffers picker: add select_current option (PR included)

### ISSUE THREAD

**Issue by dam9000** [nvim-telescope/telescope.nvim#2917]
**Is your feature request related to a problem? Please describe.**

With the buffers picker I'd like the current buffer to be pre-selected, but I don't like the buffer list to be mru sorted.
So that I can either navigate to nearby buffers using arrow keys or do a fuzzy search as usual.

**Describe the solution you'd like**

add `select_current` option to buffers picker.

**Describe alternatives you've considered**

none

**Additional context**

I opened a PR with the proposed change:

https://github.com/nvim-telescope/telescope.nvim/pull/2918

Example usage:
```
    vim.keymap.set('n', '<M-b>', function()
    require('telescope.builtin').buffers {
        select_current = true,
        selection_strategy = 'closest',
    }
    end, { desc = 'Buffer list' })
```

**Comment by pirey** [comment]
the `select_current` option is not working as expected.
it does not select current buffer by default.
i created a PR to fix it in https://github.com/nvim-telescope/telescope.nvim/pull/3147

**Comment by dam9000** [comment]
@pirey thanks for improving this. I too noticed that in some occasions it was not working properly, from my observations it was working only for the files that were provided through the command line but not for any new files opened afterwards from within nvim. I have tested your PR and now that works too.
Thank you!
