### ISSUE TITLE
C-w doesn't work in telescope windows

### ISSUE THREAD

**Issue by AntonC9018** [nvim-telescope/telescope.nvim#2927]
### Description

`C-w` in vim deletes a word backwards, in insert and command modes. It doesn't work in telescope windows.

I've already opened an issue earlier regarding copying and pasting in these windows. This might be one of those features intentionally disabled for these kinds of windows.

Note that the default bindings include a binding for `<C-w>`, which I have manually unmapped. This might be the source of the issue -- the default binding might be manually applied, then removed by remapping it to `<Nop>`, or something. But that doesn't seem right either -- doing `<C-w>` in insert mode in a telescope window takes me into operator pending mode for some reason. I don't have any custom mappings for that.

If you say this is by design and you think this is intuitive, it's not, at least for me as a user.

### Neovim version

```markdown
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
```

### Operating system and version

Windows 10

### Telescope version / branch / rev

0.1.5

### checkhealth telescope

```markdown
not relevant
```

### Steps to reproduce

Use `<C-w>` in a telescope window.

### Expected behavior

It behaves the same as in regular insert mode?

### Actual behavior

It doesn't

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require("telescope").setup({
      defaults =
      {
          mappings =
          {
              i =
              {
                  ["<C-w>"] = false,
              }
          }
      }
  })
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
This is intended behavior for prompt-buffers in Vim (which telescope uses).

I agree it's not intuitive either but that's why we have the mapping.

This issue has already been covered here: https://github.com/nvim-telescope/telescope.nvim/issues/1579#issuecomment-989767519
