### ISSUE TITLE
can current_buffer_fuzzy_find go to line and column of search query?

### ISSUE THREAD

**Issue by joelpeapen** [nvim-telescope/telescope.nvim#2928]
The `current_buffer_fuzzy_find` only takes you to the line of the query, and not the actual query itself. I'd like the `current_buffer_fuzzy_find` to take me to the exact word i search for, not just the line, the same way default `/` search works

```c
1  # include <stdio.h>
2
3  int main() {
4      printf("hello world");
5  }
```

e.g, searcing for `hello` should take me to line 4 and column 12, and not the start of line 4

**Comment by jamestrew** [comment]
We added this to the master branch just a few days ago :+1:
