### ISSUE TITLE
Allow controlling/hiding prompt postfix

### ISSUE THREAD

**Issue by mturoci** [nvim-telescope/telescope.nvim#2929]
**Is your feature request related to a problem? Please describe.**
I have configured telescope so that it shows wider preview pane so that I can save some lines from wrapping. However, that means that sometimes my prompt window is not wide enough for the prompt text resulting in a text "behind" the prompt postfix. See the following screenshot. (should display the last bar, but does not)

![image](https://github.com/nvim-telescope/telescope.nvim/assets/64769322/c08acdfa-c34a-4181-ac19-aed8bc0eb613)

When navigating to the end, cursor is "hidden" behind the `0 / 11` window.

**Describe the solution you'd like**
I would like to either hide, override or see my cursor when at the end of the prompt.

![image](https://github.com/nvim-telescope/telescope.nvim/assets/64769322/2d6e2249-2030-4b0b-9add-f74602a19937)

**Describe alternatives you've considered**
Different layout, but this actual one is the most suitable.

**Comment by jamestrew** [comment]
You can achieve this with the `get_status_text` option like so
```lua
local config = require("telescope.config")
local default_status_text = config.values.get_status_text

require("telescope").setup({
  defaults = {
    get_status_text = function(picker, opts)
      local status_text = default_status_text(picker, opts)
      local prompt_winid = picker.prompt_win
      local cursor_col = vim.api.nvim_win_get_cursor(prompt_winid)[2]
      local prompt_width = vim.api.nvim_win_get_width(prompt_winid)

      local cursor_occluded = (prompt_width - cursor_col - #status_text) < 0
      if cursor_occluded then
        return ""
      end
      return status_text
    end,
  },
})
```

But I'm thinking this should be the default for telescope. I'll think on this more and leave this issue open for now.

**Comment by jamestrew** [comment]
Yeah I think this is a limitation with neovim's extmarks.
I want to see if this is a bug that can be fixed upstream or maybe it's intended behavior in which case we should come up with a workaround.

https://github.com/neovim/neovim/issues/27540

**Comment by mturoci** [comment]
> You can achieve this with the get_status_text option like so

Works like a charm. Thanks @jamestrew!
