### ISSUE TITLE
Make it so that `lsp_incoming_calls` takes you to the line of the function call itself, similar to `vim.lsp.buf.incoming_calls()`

### ISSUE THREAD

**Issue by tristan957** [nvim-telescope/telescope.nvim#2939]
**Is your feature request related to a problem? Please describe.**
The `lsp_incoming_calls` picker doesn't take you to the line of the call while `vim.lsp.buf.incoming_calls()` does.

**Describe the solution you'd like**
Take me to the line of parent function that calls the function I am analyzing.

**Describe alternatives you've considered**
Looked at the options of the picker and nothing stood out. `vim.lsp.buf.incoming_calls()` is an alternative.

**Comment by tristan957** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/2935 seems related.

**Comment by jamestrew** [comment]
I think this is actually a bug. It only seems to only one item from each file as well and not in line with `vim.lsp.buf.incoming_calls()`.
