### ISSUE TITLE
Bizarre behavior with `find_files` and `tcd`

### ISSUE THREAD

**Issue by synic** [nvim-telescope/telescope.nvim#2956]
### Description

There's some intermittent, bizarre behavior with `:tcd` and `find_files` that seems to be related to the asynchronous nature of telescope, but I can't be sure. 

The result is that if you use `:tcd` right before you call `find_files`, sometimes the file that you choose is not actually read and the buffer is blank. I've scattered various `print` statements in the telescope code, namely right here: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/actions/set.lua#L199 and the paths and files _look_ correct, nevertheless, the file is blank.

Any subsequent `find_files` will open other files correctly, but the first one remains blank, even if you `:q` the buffer and try to find it again.

This does NOT happen with `:cd` or `:lcd` (that I can tell, like I said, it's intermittent) 

### Neovim version

```markdown
NVIM v0.10.0-dev-2173+g6cbfe4545-Homebrew
Build type: Release
LuaJIT 2.1.1703358377
```

### Operating system and version

macOS 14.2.1

### Telescope version / branch / rev

2e1e382

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 9.0.0

===== Installed extensions ===== ~

Telescope Extension: `noun` ~
- No healthcheck provided

Telescope Extension: `ui-select` ~
- No healthcheck provided
```

### Steps to reproduce

1. Modify minimal example to match your FS
2. Run nvim, wait for picker to pop up
3. Pick a file

You may need to do this several times. It's hard to predict when it will happen.

### Actual behavior

Sometimes the first file you try to open is blank.

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"nvim-telescope/telescope.nvim",
				requires = {
					"nvim-lua/plenary.nvim",
					{ "nvim-telescope/telescope-fzf-native.nvim", run = "make" },
				},
			},
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
_G.load_config = function()
	require("telescope").setup()
	require("telescope").load_extension("fzf")
	vim.defer_fn(function()
		vim.cmd("cd ~/")
		vim.cmd.tabnew()
		vim.cmd("tcd ~/Projects/adamolsen.dev")

		local builtin = require("telescope.builtin")
		builtin.find_files({
			cwd = "/Users/synic/Projects/adamolsen.dev",
			hidden = false,
			mode = "insert",
		})
	end, 3000)
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing Telescope and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

**Comment by synic** [comment]
Nevermind, it does happen with `:lcd` as well.

**Comment by jamestrew** [comment]
Are you using `defer_fn` in your config or is that just a convenience thing for the minimal config?

I've tried the minimal config + reproduction steps about 40 times but I can't seem to get it.

**Comment by synic** [comment]
Not using `defer_fn` in my config, definitely just a convenience thing for this example.

I'm trying to figure out a way to make it more reproducible, but having a bit of trouble (since I don't actually know what's causing it).

I'm wondering if the fact that even if I close the file with `:q` and try to reopen it, it's still blank is a clue. It's like once it opens it in that blank state, you have to restart vim for it to open it properly.

`:read %` does seem to read the correct data just fine, it's only the initial open.

As a note, wrapping the `find_files` in a `vim.schedule` seems to help somewhat, and using a `defer_fn` with a timeout of 200 seems to help a lot (which is why I thought it was something related to an asynchronous callback).

It's always just the first file, after everything is loaded and ready it seems to be ok.

**Comment by synic** [comment]
I believe this is actually lazy.nvim, I'm pretty sure it's related to lazy loading plugins on `BufReadPre`. The more plugins you load that way, the more often this happens (but mostly only when using `:tcd`).

Point is, it has nothing to do with telescope (I think). I thought I was able to reproduce it with the minimal example here, but now I'm not so sure. Haven't been able to make it happen in a while, but it _definitely_ happens if I lazy load plugins with `BufReadPre`.
