### ISSUE TITLE
Adding a previewer option to colorscheme picker

### ISSUE THREAD

**Issue by shreyas-a-s** [nvim-telescope/telescope.nvim#2966]
**Is your feature request related to a problem? Please describe.**
Currently the option to customise colorscheme is the 'enable_preview' parameter and it controls whether selecting a colorscheme from list changes colorscheme. And changing colorscheme causes both the previewer as well as the currently open buffers to change colorscheme. I would like the addition of a 'proper' previewer option so that I can set enable_preview=true and previewer=false and selecting a colorscheme changes the colorscheme of currenly open buffers while the previewer is kept disabled. Currently when I run :Telescope colorscheme previewer=false enable_preview=true, somehow both options are coupled together so that the enable_preview functionality (changing colorscheme of currently open buffers) is connected to previewer functionality.

**Describe the solution you'd like**
'Decouple' previewer and enable_preview options to colorscheme picker so that they can be changed independently.

**Describe alternatives you've considered**
No alternatives as far as I thought.

**Additional context**
Nothing.

I know it's a bit confusing and I can provide more context if you'd like. Thanks for reading through this message.

**Comment by jamestrew** [comment]
Yeah I agree. Should be too hard.
I'd be willing to give guidance if anybody is interested. Otherwise, I'll try to get to this when I have some time.

**Comment by shreyas-a-s** [comment]
I tried to make some changes with my limited knowledge of lua that I got from tweaking neovim. But it is found to be not enough for the job. It would be nice if someone with more expertise could take a look and make further improvements when convenient.

**Comment by Jayanth-Parthsarathy** [comment]
Hey @jamestrew, @shreyas-a-s  . I would love to work on this. Can you please assign this to me?

**Comment by shreyas-a-s** [comment]
That's great, Jayanth. I would love to do that. But since I am new to Telescope github repo, I am not sure how the workflows are handled. It would be nice if you could mention @jamestrew in the issue thread so that he can give you directions on what to do next.
-------- Original Message --------

**Comment by Jayanth-Parthsarathy** [comment]
Hey @jamestrew, I'm eager to contribute, but I'm still getting the hang of Lua myself. I've been looking through the code for telescope colorschemes. Here's what I've understood so far:

```lua
local picker = pickers.new(opts, {
  prompt_title = "Change Colorscheme",
  finder = finders.new_table {
    results = colors,
  },
  sorter = conf.generic_sorter(opts),
  previewer = previewer,
  attach_mappings = function(prompt_bufnr)
    actions.select_default:replace(function()
      local selection = action_state.get_selected_entry()
      if selection == nil then
        utils.__warn_no_selection "builtin.colorscheme"
        return
      end

      actions.close(prompt_bufnr)
      need_restore = false
      vim.cmd.colorscheme(selection.value)
    end)
    return true
  end,
}, highlight_colors)
```

I think passing the highlight colors of the old theme might be beneficial, but I'm not entirely sure how to proceed from here. I've parsed the `highlight_colors` and turned them into a table with the highlight group and the corresponding color hex value. Then, I passed it as an optional argument to the `new_picker`  and the `default_create_layout` function.

If you could provide some guidance, I believe I can resolve this issue.

**Comment by jamestrew** [comment]
My approach would be to take advantage of the action to cycle through entries and change the colorscheme when a new entry is "selected".
This relates to the `shift_selection` action in `telescope.actions.set` (`actions.move_selection_next` and related actions all call this).
These actions are all fancy lua metatables that Telescope has added methods to (`replace`, `enhance`, etc - defined in `telescope.actions.mt`).
So similar to how we're `replace`-ing the `select_default` behavior, we can `enhance` the `shift_selection`'s post selection behavior. 

Something like so
```lua
      attach_mappings = function()
        actions.select_default:replace(...) -- no change
        action_set.shift_selection:enhance({ post = function()
          -- set colorscheme to the currently selected entry one
          -- this is for when someone cycles through the result
        end })
        actions.close:enhance({ post = function()
          -- reset back to original, pre-telescope colorscheme after closing telescope
        end })
        return true
      end,
      on_complete = {
        function()
          -- also set colorscheme to the currently selected entry
          -- this is for when someone prompts and searches for a result
        end,
      },
```

I think this way, we can

**Comment by Jayanth-Parthsarathy** [comment]
Hey @jamestrew. I assume you mean something like this right?
```lua
  local picker = pickers.new(opts, {
    prompt_title = "Change Colorscheme",
    finder = finders.new_table {
      results = colors,
    },
    sorter = conf.generic_sorter(opts),
    previewer = previewer,
    attach_mappings = function(prompt_bufnr)
      actions.select_default:replace(function()
        local selection = action_state.get_selected_entry()
        if selection == nil then
          utils.__warn_no_selection "builtin.colorscheme"
          return
        end

        actions.close(prompt_bufnr)
        need_restore = false
        vim.cmd.colorscheme(selection.value)
      end)
      action_set.shift_selection:enhance {
        post = function()
          local selection = action_state.get_selected_entry()
          if selection == nil then
            utils.__warn_no_selection "builtin.colorscheme"
            return
          end
          need_restore = true
          vim.cmd.colorscheme(selection.value)
        end,
      }
      actions.close:enhance {
        post = function()
          if need_restore then
            vim.cmd.colorscheme(before_color)
          end
        end,
      }
      return true
    end,
    on_complete = {
      function()
        local selection = action_state.get_selected_entry()
        if selection == nil then
          utils.__warn_no_selection "builtin.colorscheme"
          return
        end
        need_restore = true
        vim.cmd.colorscheme(selection.value)
      end,
    },
  })
```

**Comment by jamestrew** [comment]
That looks good at first glance.

**Comment by MovieMaker93** [comment]
Is still open? Can I take it?

**Comment by MovieMaker93** [comment]
> Hey @jamestrew. I assume you mean something like this right?
> 
> ```lua
>   local picker = pickers.new(opts, {
>     prompt_title = "Change Colorscheme",
>     finder = finders.new_table {
>       results = colors,
>     },
>     sorter = conf.generic_sorter(opts),
>     previewer = previewer,
>     attach_mappings = function(prompt_bufnr)
>       actions.select_default:replace(function()
>         local selection = action_state.get_selected_entry()
>         if selection == nil then
>           utils.__warn_no_selection "builtin.colorscheme"
>           return
>         end
> 
>         actions.close(prompt_bufnr)
>         need_restore = false
>         vim.cmd.colorscheme(selection.value)
>       end)
>       action_set.shift_selection:enhance {
>         post = function()
>           local selection = action_state.get_selected_entry()
>           if selection == nil then
>             utils.__warn_no_selection "builtin.colorscheme"
>             return
>           end
>           need_restore = true
>           vim.cmd.colorscheme(selection.value)
>         end,
>       }
>       actions.close:enhance {
>         post = function()
>           if need_restore then
>             vim.cmd.colorscheme(before_color)
>           end
>         end,
>       }
>       return true
>     end,
>     on_complete = {
>       function()
>         local selection = action_state.get_selected_entry()
>         if selection == nil then
>           utils.__warn_no_selection "builtin.colorscheme"
>           return
>         end
>         need_restore = true
>         vim.cmd.colorscheme(selection.value)
>       end,
>     },
>   })
> ```

Have you tried this code? What is missing?

**Comment by MovieMaker93** [comment]
> **Is your feature request related to a problem? Please describe.** Currently the option to customise colorscheme is the 'enable_preview' parameter and it controls whether selecting a colorscheme from list changes colorscheme. And changing colorscheme causes both the previewer as well as the currently open buffers to change colorscheme. I would like the addition of a 'proper' previewer option so that I can set enable_preview=true and previewer=false and selecting a colorscheme changes the colorscheme of currenly open buffers while the previewer is kept disabled. Currently when I run :Telescope colorscheme previewer=false enable_preview=true, somehow both options are coupled together so that the enable_preview functionality (changing colorscheme of currently open buffers) is connected to previewer functionality.
> 
> **Describe the solution you'd like** 'Decouple' previewer and enable_preview options to colorscheme picker so that they can be changed independently.
> 
> **Describe alternatives you've considered** No alternatives as far as I thought.
> 
> **Additional context** Nothing.
> 
> I know it's a bit confusing and I can provide more context if you'd like. Thanks for reading through this message.

If you don't mind could you give more context about the issue? Some screenshot of the desired output would be nice

**Comment by shreyas-a-s** [comment]
> > Hey @jamestrew. I assume you mean something like this right?
> > ```lua
> >   local picker = pickers.new(opts, {
> >     prompt_title = "Change Colorscheme",
> >     finder = finders.new_table {
> >       results = colors,
> >     },
> >     sorter = conf.generic_sorter(opts),
> >     previewer = previewer,
> >     attach_mappings = function(prompt_bufnr)
> >       actions.select_default:replace(function()
> >         local selection = action_state.get_selected_entry()
> >         if selection == nil then
> >           utils.__warn_no_selection "builtin.colorscheme"
> >           return
> >         end
> > 
> >         actions.close(prompt_bufnr)
> >         need_restore = false
> >         vim.cmd.colorscheme(selection.value)
> >       end)
> >       action_set.shift_selection:enhance {
> >         post = function()
> >           local selection = action_state.get_selected_entry()
> >           if selection == nil then
> >             utils.__warn_no_selection "builtin.colorscheme"
> >             return
> >           end
> >           need_restore = true
> >           vim.cmd.colorscheme(selection.value)
> >         end,
> >       }
> >       actions.close:enhance {
> >         post = function()
> >           if need_restore then
> >             vim.cmd.colorscheme(before_color)
> >           end
> >         end,
> >       }
> >       return true
> >     end,
> >     on_complete = {
> >       function()
> >         local selection = action_state.get_selected_entry()
> >         if selection == nil then
> >           utils.__warn_no_selection "builtin.colorscheme"
> >           return
> >         end
> >         need_restore = true
> >         vim.cmd.colorscheme(selection.value)
> >       end,
> >     },
> >   })
> > ```
> 
> Have you tried this code? What is missing?

Ohhh. I haven't really checked out this code before, but now that I did test it I think it works. This is the video after inserting the code into `telescope.nvim/lua/telescope/builtin/__internal.lua`:

https://github.com/nvim-telescope/telescope.nvim/assets/137637016/f5413f24-864c-4f4c-8a25-d01a885db0ff

As you can see in the video, when `previewer` is set to `false`, the live-preview functionality is not affected.

If you want to see what was the issue, see this. This is the video before inserting that code:

https://github.com/nvim-telescope/telescope.nvim/assets/137637016/892892df-2149-473f-b2c2-df16a9d0aa52

As you can see, when `previewer ` was set to `false`, the live-preview functionality was affected.

So I think it's fixed then?

**Comment by MovieMaker93** [comment]
Ok, nice; if it is fixed, @Jayanth-Parthsarathy, would you mind opening a PR?

**Comment by Jayanth-Parthsarathy** [comment]
Hey @MovieMaker93 . I have not made any progress on this.

**Comment by MovieMaker93** [comment]
> Hey @MovieMaker93 . I have not made any progress on this. Please feel free to work on this.

I have tried your code, and seems working as expected. Any suggestion or doubts about this implementation @jamestrew ?

**Comment by jamestrew** [comment]
@MovieMaker93 I don't have any concerns off the top of my head. Are you able to open a PR? I'd be better able to see the change and offer feedback with a PR.

Otherwise, I can also try to implement this myself over the next few days.

**Comment by MovieMaker93** [comment]
> @MovieMaker93 I don't have any concerns off the top of my head. Are you able to open a PR? I'd be better able to see the change and offer feedback with a PR.
> 
> Otherwise, I can also try to implement this myself over the next few days.

Yes i can do it, maybe you have to assign the issue (actually i have denied error when pushing new branch).

**Comment by Jayanth-Parthsarathy** [comment]
> > @MovieMaker93 I don't have any concerns off the top of my head. Are you able to open a PR? I'd be better able to see the change and offer feedback with a PR.
> > 
> > Otherwise, I can also try to implement this myself over the next few days.
> 
> Yes i can do it, maybe you have to assign the issue (actually i have denied error when pushing new branch).

If I am not mistaken this might be because you need to fork the repo before submitting a PR.
