### ISSUE TITLE
man_pages is empty

### ISSUE THREAD

**Issue by Kek5chen** [nvim-telescope/telescope.nvim#2977]
### Description

![Screenshot 2024-03-06 at 14 35 06](https://github.com/nvim-telescope/telescope.nvim/assets/52585984/107248d4-be10-4236-a525-f383b22d2f93)

As you can see, :Man works, but :Telescope man_pages doesn't show anything.

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1693350652
```

### Operating system and version

macOS Sonoma 14.3.1

### Telescope version / branch / rev

master

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 9.0.0

===== Installed extensions ===== ~
```

### Steps to reproduce

N/A

### Expected behavior

Show entries of man pages in the man page picker

### Actual behavior

The picker is empty

### Specifics

I don't have any specific configuration for telescope.
I don't even have a plugin manager.
My plugins, nvim and shell are managed over the nix home-manager.

I'm guessing this is probably related to MacOS again, similar to #2326, or due to home-manager that takes its files from the `/nix/store`.

If I can provide anything else, please just tell me.

```
~ % apropos ' '
 : nothing appropriate.
```

**Comment by jamestrew** [comment]
I experienced this issue a few weeks back but it was fixed by updating my packages.
I think you can also run the `mandb` shell command/program if that's available to you.

**Comment by Kek5chen** [comment]
So, apparently /var/cache (/private/var/cache) did not exist and that's why it failed.
