### ISSUE TITLE
Allow specifing the position of the help window when using `:Telescope help_tags`

### ISSUE THREAD

**Issue by nullptr-yxw** [nvim-telescope/telescope.nvim#2978]
**Is your feature request related to a problem? Please describe.**
I want to split the window vertically or open the help window in a new tab while using `:Telescope help_tags`, but the default behaviour is spliting the window horizontally.

https://github.com/nvim-telescope/telescope.nvim/assets/96286337/38b6c952-5ba5-449f-bca6-773bcf4a834e

So is it possible to specify the position of the help window?

**Comment by jamestrew** [comment]
See `<C-v>`, `<C-x>`, `<C-t>` bindings https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#default-mappings
