### ISSUE TITLE
Previewer does not work when there are whitespaces in the path after commit 3b8399c

### ISSUE THREAD

**Issue by Mishosan** [nvim-telescope/telescope.nvim#2994]
### Description

Previewer does not work when there are whitespaces in the path after commit [3b8399c](https://github.com/nvim-telescope/telescope.nvim/commit/3b8399c27380d09c44f55c8fbeff0bd7a4ed3f8d). So if a directory is called `this is a folder` instead of `this_is_a_folder`, Telescope cannot show previews of file content anymore. I had to revert to [an older commit](https://github.com/nvim-telescope/telescope.nvim/commit/c816406bd50ade6ec754474f08974154487d417c) by adding `commit = "c816406bd50ade6ec754474f08974154487d417c",` to my Lazy configuration to be able to do that again.

### Neovim version

```markdown
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1692716794
```

### Operating system and version

Pop!_OS 22.04

### Telescope version / branch / rev

git

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 8.3.1

===== Installed extensions ===== ~

Telescope Extension: `ui-select` ~
- No healthcheck provided
```

### Steps to reproduce

Have the latest version 

### Expected behavior

One should see a preview of the file content.

### Actual behavior

One does not see a preview of the file content.

### Minimal config

```Lua
-- using Lazy as my package manager

local map = vim.keymap.set

return {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      {
        "nvim-telescope/telescope-ui-select.nvim",
        "nvim-telescope/telescope-fzf-native.nvim",
        build = "make",
      },
    },

    opts = {
      extensions_list = { "themes", "terms", "fzf" },

      extensions = {
        fzf = {
          fuzzy = true,
          override_generic_sorter = true,
          override_file_sorter = true,
          case_mode = "smart_case",
        },
      },
    },

    config = function(_, opts)
      extensions = {
        ["ui-select"] = {
          require("telescope.themes").get_dropdown {
            -- even more opts
          },
          specific_opts = {
            codeactions = false,
          },
        },
      }

      require("telescope").load_extension("ui-select")

      map("n", "<leader>fg", "<cmd>Telescope git_files<CR>", { desc = "Find git files" })
      map("n", "<leader>ft", "<cmd>Telescope treesitter<CR>", { desc = "Treesitter search" })
      map("n", "<leader>fr", "<cmd>Telescope lsp_references<CR>", { desc = "Find LSP references" })

      require("telescope").setup(opts)
    end,
  },
}
```

**Comment by jamestrew** [comment]
Thanks for reporting!
I think I've fixed it with the above linked PR. If you can give it a try that'll be appreciated.

**Comment by Mishosan** [comment]
> Thanks for reporting! I think I've fixed it with the above linked PR. If you can give it a try that'll be appreciated.

Yes, [your commit](https://github.com/nvim-telescope/telescope.nvim/pull/2996) solved it!
