### ISSUE TITLE
Path errors on some actions after 3b8399c on Windows 10/11

### ISSUE THREAD

**Issue by slainn** [nvim-telescope/telescope.nvim#2998]
### Description

Path errors on some actions after 3b8399c on Windows 10

### Neovim version

```markdown
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
```

### Operating system and version

Windows 10

### Telescope version / branch / rev

221778e

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0 (rev e50df40a19)
- OK fd: found fd 9.0.0

===== Installed extensions ===== ~

Telescope Extension: `notify` ~
- No healthcheck provided
```

### Steps to reproduce

1. remove C:\Users\user\AppData\Local\nvim-data\lazy\telescope.nvim
2. start neovim
3. start telescope
4. press escape couple of times

### Expected behavior

Telescope popup closed

### Actual behavior

Path-related errors poped up
![tele](https://github.com/nvim-telescope/telescope.nvim/assets/9031190/9c1aadee-d49c-4a16-b0ef-dcdd6bd82af0)
![tele2](https://github.com/nvim-telescope/telescope.nvim/assets/9031190/b68b62c1-4e9c-43e3-b167-dea2260070bf)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by slainn** [comment]
same with Windows 11

**Comment by dangdd2003** [comment]
same error to me on windows 11 !
![image](https://github.com/nvim-telescope/telescope.nvim/assets/124034919/407a1558-cb6b-49d9-8fe4-dc99fac93b2a)

**Comment by jamestrew** [comment]
Thanks guys for reporting.
I don't have a Windows machine so I might need help in testing but I can look into this.

**Comment by jamestrew** [comment]
Can you guys give this PR a try? I believe this will address the issue.
https://github.com/nvim-telescope/telescope.nvim/pull/2999

**Comment by slainn** [comment]
> Can you guys give this PR a try? I believe this will address the issue.
> #2999
Thanks so much, tested on Win10, it fixes this for me!
