### ISSUE TITLE
Add option to open buffers in the insert mode

### ISSUE THREAD

**Issue by DUOLabs333** [nvim-telescope/telescope.nvim#3025]
**Is your feature request related to a problem? Please describe.**
Right now, if you open a buffer using `Telescope buffers`, you will always enter the buffer in normal mode. However, I usually work in insert mode, so it's an extra keystroke to enter insert mode after jumping to a buffer.

**Describe the solution you'd like**
An option to set the mode of the buffer that you open using `Telescope buffers`.

**Describe alternatives you've considered**

**Additional context**

**Comment by DUOLabs333** [comment]
How would you add this to a config? I tried pasting it in, but it starts Vim with the buffers window open.

**Comment by jamestrew** [comment]
That would depend on your config and things like package manager.
But in general that code you would do something like using that function as part of a keybinding.

Alternatively, you can put this in your telescope setup config
```lua
require("telescope").setup({
  defaults = {
    -- ...,
  },
  pickers = {
    buffers = {
      attach_mappings = function()
        require("telescope.actions.set").select:enhance({
          post = function()
            vim.schedule(function()
              vim.cmd([[startinsert]])
            end)
          end,
        })
        return true
      end,
    },
  },
})
```

**Comment by DUOLabs333** [comment]
This works. Thanks!
