### ISSUE TITLE
Feature Request: Add option to sync built-in search from Telescope search term

### ISSUE THREAD

**Issue by kevintraver** [nvim-telescope/telescope.nvim#3030]
**Proposal:**
Add a feature to Telescope's `current_buffer_fuzzy_find` pickers that would sync the built-in search from Telescope's search term.

**Implementation:**
To implement this feature, the following example demonstrates the addition of the `sync_builtin_search` option to Telescope's  `current_buffer_fuzzy_find` picker:

```lua
require("telescope.builtin").current_buffer_fuzzy_find({ sync_builtin_search = true })
```
In the Telescope codebase, modify the following section:

https://github.com/nvim-telescope/telescope.nvim/blob/4626aaa2bcfdacf55fd6d44b430e2df81b2403ff/lua/telescope/builtin/__files.lua#L566-L568

This sets the built-in search (using the `/` register) from Telescope's search term if `sync_builtin_search` is passed in.

```lua
vim.schedule(function()
  vim.api.nvim_win_set_cursor(0, { selection.lnum, first_col })
  if opts.sync_builtin_search then
    vim.fn.setreg("/", searched_for)
  end
end)
```

This allows for the use of normal search commands (`n`/`N`) using the search from Telescope.

**Comment by kevintraver** [comment]
It might also be useful to have the option to set the search as the _current word_ which would ensure a valid search term since the Telescope search is a fuzzy search.

`vim.fn.expand("<cword>")`

**Comment by kevintraver** [comment]
Another option is to just add a `after_cursor_set` hook, and let the user pass in whatever function they want.

**Comment by jamestrew** [comment]
Yeah using the search pattern for the `/` last-pattern won't really work because of fuzzy finder syntax differences.

Using `<cword>` doesn't really work either since you might not search for a word and then you get stuck with a random next word as your last pattern.

And I really want to avoid adding more hooks where feasible. You can still have a custom `select:replace` function in the `attach_mappings` option to fit whatever you're trying to accomplish here like so https://github.com/nvim-telescope/telescope.nvim/issues/2970#issuecomment-1979527677

**Comment by kevintraver** [comment]
Ok, that all makes sense. Thanks.

Question about the `attach_mappings`:

Is there a way to to inherit an existing mapping and just append some functionality to it?

Like in this case, I would just want to use what already exists in `select_default` for `current_buffer_fuzzy_find` , and just append to it instead of reimplementing it. This would be helpful in case you always want to keep in sync with however the upstream function is implemented. Or perhaps maybe the logic for `current_buffer_fuzzy_find` can be extracted out a little more?

**Comment by kevintraver** [comment]
This works, it just seems a bit verbose:

```lua
require("telescope.builtin").current_buffer_fuzzy_find({
  attach_mappings = function()
    local action_state = require("telescope.actions.state")
    local actions = require("telescope.actions")
    local utils = require("telescope.utils")
    actions.select_default:replace(function(prompt_bufnr)
      local selection = action_state.get_selected_entry()
      if not selection then
        utils.__warn_no_selection("builtin.current_buffer_fuzzy_find")
        return
      end
      local current_picker = action_state.get_current_picker(prompt_bufnr)
      local searched_for = require("telescope.actions.state").get_current_line()

      ---@type number[] | {start:number, end:number?, highlight:string?}[]
      local highlights = current_picker.sorter:highlighter(searched_for, selection.ordinal) or {}
      highlights = vim.tbl_map(function(hl)
        if type(hl) == "table" and hl.start then
          return hl.start
        elseif type(hl) == "number" then
          return hl
        end
        error("Invalid higlighter fn")
      end, highlights)

      local first_col = 0
      if #highlights > 0 then
        first_col = math.min(unpack(highlights)) - 1
      end

      actions.close(prompt_bufnr)
      vim.schedule(function()
        vim.api.nvim_win_set_cursor(0, { selection.lnum, first_col })
        vim.fn.setreg("/", vim.fn.expand("<cword>"))
      end)
    end)

    return true
  end,
})
```
