### ISSUE TITLE
Picker results on the same line for logically-identical symbols could be collapsed into one entry

### ISSUE THREAD

**Issue by jcoffa** [nvim-telescope/telescope.nvim#3031]
**Is your feature request related to a problem? Please describe.**

(Originally came from a GitHub issue in the [Kickstart.nvim repo](https://github.com/nvim-lua/kickstart.nvim) that I thought was a bug, [find that thread here](https://github.com/nvim-lua/kickstart.nvim/issues/815). Shoutout to feoh, aski, and dam9000 for the help).

When using certain LSP finders (e.g. `telescope.builtin.lsp_definitions` or `telescope.builtin.lsp_references`) in certain languages that can assign functions to variables (e.g. Lua) both the variable and the anonymous function definition show up in the list of results. Take this example when using the "goto definition" feature on any of the calls to [the map function in the Kickstart.nvim configuration](https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua#L459):

![318242725-a71db3f3-de0b-4071-83ca-bc00373d5116](https://github.com/nvim-telescope/telescope.nvim/assets/35551680/f86a98d0-f420-4943-a5cd-12e0a52fa2db)

2 entries are provided in the picker list which can be verified with some logging:

```
[plenary] [DEBUG 21:16:33] /home/andy3j/.local/share/nvim/lazy/telescope.nvim/lua/telescope/builtin/__lsp.lua:182: { {                                                                      
[plenary]     col = 17,
[plenary]     filename = "/home/andy3j/.config/nvim/init.lua",
[plenary]     lnum = 239,
[plenary]     text = "          local map = function(keys, func, desc)"
[plenary]   }, {
[plenary]     col = 23,
[plenary]     filename = "/home/andy3j/.config/nvim/init.lua",
[plenary]     lnum = 239,
[plenary]     text = "          local map = function(keys, func, desc)"
[plenary]   } }
```

One for the variable, in this case `map` (col 17):

```lua
local map = function(keys, func, desc)
      ^
```

and another for the actual `function` definition (col 23):

```lua
local map = function(keys, func, desc)
            ^
```

There are certainly many other scenarios that are similar to this one, but this is a relatively simple example that can be faithfully replicated by installing/using the [Kickstart.nvim configuration](https://github.com/nvim-lua/kickstart.nvim) without any changes.

**Describe the solution you'd like**

It would be nice if Telescope would be able to collapse these results into 1 result and then allow the "goto definition" finder to immediately jump the user to this line instead of returning multiple results and having the user pick between 2 near-identical options that are almost the same thing anyways.

**Describe alternatives you've considered**

Perhaps a config option to immediately jump to the first item in the picker if all options are on the same line and represent the same logical entity? In the example above, both the `map` variable and the actual `function()` definition refer to the same Lua function and are only a few characters away from each other.

**Additional context**

You can find the original "bug report" I made in the [Kickstart.nvim repo](https://github.com/nvim-lua/kickstart.nvim) here: https://github.com/nvim-lua/kickstart.nvim/issues/815

**Comment by jamestrew** [comment]
I don't feel like Telescope should be manipulating results from LSP servers. For one thing, it's not clear to me which of these results we should be filtering out. Neovim's `vim.lsp.buf.definition()` will also give you both results.

In the future, I'd like Telescope to support custom handlers better so users can manipulate/filter response from the LSP servers however they like.
