### ISSUE TITLE
Using the mouse while the keybind help menu is open results in a sticky window that cannot be closed

### ISSUE THREAD

**Issue by mihaifm** [nvim-telescope/telescope.nvim#3034]
### Description

This is a minor issue but it can still result in bad experience, especially for new users.

To reproduce, just click with the mouse anywhere in nvim after opening the telescope help menu with `?` or `C-/`. The telescope popup will be dismissed but the help menu remains open. The only way to get rid of it is to reopen Telescope.

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794
```

### Operating system and version

linux (via ssh, with and without tmux), windows (with neovide)

### Telescope version / branch / rev

*

### checkhealth telescope

```markdown
.
```

### Steps to reproduce

type `:Telescope`
press `C-/`
click with the mouse anywhere in vim
press Esc

The keymaps popup remains open

### Expected behavior

The keymaps popup should be dismissed with the Telescope popup

### Actual behavior

The keymaps popup remains open

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
thanks - should be fixed in the latest commit

**Comment by mihaifm** [comment]
Great, thanks for the quick response
