### ISSUE TITLE
Enable entry column width in Treesitter picker to be customized

### ISSUE THREAD

**Issue by scienceplease** [nvim-telescope/telescope.nvim#3041]
**Is your feature request related to a problem? Please describe.**
The treesitter picker does not allow for it's entry column widths to be customized via `opts` ([see hard-coded column widths here](https://github.com/nvim-telescope/telescope.nvim/blob/d26b666b45e5dde23332e4bde1227677f2d92e31/lua/telescope/make_entry.lua#L651)). This is in contrast to the LSP symbol picker which accepts `symbol_width` and `symbol_type_width`.

**Describe the solution you'd like**
Enable `symbol_width` and `symbol_type_width` options for treesitter picker to match LSP symbol picker.

**Comment by hardenedapple** [comment]
I have the same pain point.
I would like to suggest to the devs a general "symbol/filename/<whatever> width" default that is specified in terms of the width of the result window.

That way we could specify some percentage once and have it work for everything.
Would also be really nice if it could be implemented somewhere outside of the picker themselves so not every picker needed to implement the same thing -- but I don't know if that's feasible.

**Comment by jamestrew** [comment]
closed by https://github.com/nvim-telescope/telescope.nvim/pull/3105
