### ISSUE TITLE
Picker for argument list

### ISSUE THREAD

**Issue by hardenedapple** [nvim-telescope/telescope.nvim#3055]
**Is your feature request related to a problem? Please describe.**
I like to have a subset of files in my argument list as a "working set" for much quicker navigation to them.
I figure a telescope picker for that would make it even easier. 

**Describe the solution you'd like**
Select and jump to buffer in the argument list in same way as the buffer list, but with the smaller subset of buffers that is in the current arglist.

**Describe alternatives you've considered**
I am using a third-party picker [found here](https://github.com/sam4llis/telescope-arglist.nvim) and that seems to work fine, but I thought it such a core feature of vim that I figured it would be nice if in the core of telescope too (and hence making the suggestion).

**Comment by jamestrew** [comment]
I'm not gonna lie, I don't think I've even heard of `arglist` until now :grin:

We're freezing addition of new pickers to telescope core at the moment though. We have over 50 and frankly most of us maintainer maybe use half of them between all of us and not all of us our active. So we're not really looking to add something to core especially if a third party extension for it exists.
