### ISSUE TITLE
Seems like the height option is not working, meaning any height I pick for the bottom_pane is not affecting its actual height.

### ISSUE THREAD

**Issue by vladsolokha** [nvim-telescope/telescope.nvim#3061]
Seems like the height option is not working, meaning any height I pick for the bottom_pane is not affecting its actual height. 
<img width="1544" alt="Screenshot 2024-04-18 at 9 41 49 PM" src="https://github.com/nvim-telescope/telescope.nvim/assets/48961183/8061427b-2967-43b0-a316-6c2c41276c75">

_Originally posted by @vladsolokha in https://github.com/nvim-telescope/telescope.nvim/issues/771#issuecomment-2065692730_

**Comment by vladsolokha** [comment]
The only work around I found was to specify in each key binding that I want a hight of 10 or so. 
![Screenshot 2024-04-19 at 8 41 36 AM](https://github.com/nvim-telescope/telescope.nvim/assets/48961183/743a449f-0ca9-46c1-bcc5-9daf00dae1df)

**Comment by Conni2461** [comment]
Actually, i wanted to have you make an issue so you would fill out the bug report form, like which version you use, .... these templates exist for a reason and we usually dont provide support if you dont at least fill them out, this is still a hobby project

Regardless height is currently a shared setting so you can achieve this with `layout_config = { height = 10 }`
