### ISSUE TITLE
Latest commit(s) today broke all my Telescope pickers

### ISSUE THREAD

**Issue by GitMurf** [nvim-telescope/telescope.nvim#3062]
### Description

Reverting back to commit d00d9df works fine. Here is the error I am getting with the newest commits from today:

`[telescope] [WARN  22:57:50] C:/Users/.../lazy/telescope.nvim/lua/telescope/pickers.lua:669: Finder failed with msg:  ...ckstart-data/lazy/telescope.nvim/lua/telescope/utils.lua:702: bad argument #1 to 'ipairs' (table expected, got nil)`

I am on newest nightly build.

### Neovim version

```markdown
NVIM v0.10.0-dev-2961+g4d52b0cf6
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
```

### Operating system and version

Windows 11

### Telescope version / branch / rev

latest master

### checkhealth telescope

```markdown
n/a
```

### Steps to reproduce

n/a

### Actual behavior

n/a

### Minimal config

```Lua
n/a
```

**Comment by gsvaliente** [comment]
Exact same thing happened to me. Did as you pointed out and reverted to the commit and everything went back to normal.  

Running on NVIM v0.9.5 and macOS

**Comment by GitMurf** [comment]
Thanks @gsvaliente for confirming it is NOT only a nightly build issue. Looks like both stable and nightly have same problem.

**Comment by jamestrew** [comment]
Can someone provide a minimal config to test against? I can't reproduce this.

**Comment by jamestrew** [comment]
Are you guys all using a custom `path_display` function?
I believe this is the cause of the bug.

**Comment by chrisgrieser** [comment]
can confirm, I had the issue, and the latest commit fixes the issue

**Comment by GitMurf** [comment]
> Are you guys all using a custom `path_display` function?

Yes I am using custom path display. I will test in the morning and let you know. Thanks!

**Comment by gsvaliente** [comment]
Just to update, my errors **while** using path_display are now gone with the new commit.

**Comment by mawkler** [comment]
I'm having this exact issue on the latest commit fac83a556e7b710dc31433dec727361ca062dbe9 when using `path_display()`

**Comment by jamestrew** [comment]
@mawkler can you create a new issue? I think I'll need more specifics considering others are claiming that the issue is resolved.

**Comment by mawkler** [comment]
I tried to create a minimal config to reproduce the error, but instead I get another error:

```
E5108: Error executing lua: ...im/lazy/telescope.nvim/lua/telescope/actions/history.lua:76: attempt to call field 'path_expand' (a nil value)
```

Here's my minimal config:

<details>
<summary><b>Click to expand</b></summary>

```lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
  {
    'nvim-telescope/telescope.nvim',
    dependencies = 'nvim-lua/plenary.nvim',
    config = function()
      local function telescope_home()
        require('telescope.builtin').find_files({
          search_dirs = { '$HOME' },
          prompt_title = 'Press Ctrl-C for error',
          path_display = function(_, path)
            return path
          end,
        })
      end

      vim.keymap.set('n', 'H', telescope_home, {})
    end
  }
})
```

</details>

The error appears when I try to close Telescope.

It's a really odd error because the method `path_expand` is clearly there when I check in `lua/telescope/utils.lua:37`

**Comment by mattfbacon** [comment]
I have observed the same error, but only if the currently open file is Cargo.toml. Does this have something to do with automatic project root detection?

**Comment by jamestrew** [comment]
> I tried to create a minimal config to reproduce the error, but instead I get another error

I can't reproduce this. Seems like a weird installation issue or something if it's having issue calling a function from another module.

> I have observed the same error, but only if the currently open file is Cargo.toml. Does this have something to do with automatic project root detection?

We don't do any automatic project root detection besides for git related stuff. Certainly nothing involving Cargo.toml.

Again, these seem like separate issues. Best to open new issues and provide more context there.

**Comment by johanlieber** [comment]
> I tried to create a minimal config to reproduce the error, but instead I get another error:
> 
> ```
> E5108: Error executing lua: ...im/lazy/telescope.nvim/lua/telescope/actions/history.lua:76: attempt to call field 'path_expand' (a nil value)
> ```
> 
> Here's my minimal config:
> 
> Click to expand
> The error appears when I try to close Telescope.
> 
> It's a really odd error because the method `path_expand` is clearly there when I check in `lua/telescope/utils.lua:37`

hi if anyone's still having this issue, I found out that it was happening because sometime neovim would pick up my old packer installation and in it there was no path_expand. That would break when I tried navigating to somewhere or closing telescope.  really hard to debug or reproduce because it does always do it, only sometimes
