### ISSUE TITLE
Telescope File Picker is missing entries

### ISSUE THREAD

**Issue by V4G4X** [nvim-telescope/telescope.nvim#3063]
### Description

This only occurs on nightly neovim, the Telescope File Picker is missing entries:
<img width="1325" alt="image" src="https://github.com/nvim-telescope/telescope.nvim/assets/34249137/271d9b81-30eb-4bd1-8897-dbb547a1034a">

Mainly only occurs on larger codebases, haven't seen it on smaller codebases.

I can see the preview of the file, but not the file itself in the list. 
When I move the cursor up/down then the entries are shown:
<img width="1330" alt="image" src="https://github.com/nvim-telescope/telescope.nvim/assets/34249137/502ce616-f6e4-4015-a8be-d6d9f786bb0b">

What could be causing this?

I have a suspicion that the list **is** getting populated, just not above the input-text-box, but **under** it.

### Neovim version

```markdown
NVIM v0.10.0-dev-2961+g4d52b0cf6
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
```

### Operating system and version

macOS 14.4.1 23E224 arm64

### Telescope version / branch / rev

0.1.2

### checkhealth telescope

```markdown
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions ===== ~

Telescope Extension: `metals` ~
- No healthcheck provided

Telescope Extension: `notify` ~
- No healthcheck provided
```

### Steps to reproduce

1. Clone [this repo](https://github.com/V4G4X/nvim_config.git)
2. Open repo using `nvim path/to/repo`
3. Call `lua require('telescope.builtin').find_files()`
4. Type in "telescope"
5. Notice how preview is populated but not the list.

### Expected behavior

List should have the file entries as well as the preview.

### Actual behavior

List doesn't show the file entries until cursor is moved.

### Minimal config

```Lua
-- My minimal init.lua that recreates the issue.

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)
vim.g.mapleader = " " -- Make sure to set `mapleader` before lazy so your mappings are correct
require("lazy").setup({
    { 'nvim-telescope/telescope.nvim', dependencies = { 'nvim-lua/plenary.nvim' }, tag = '0.1.2' },
})
```

**Comment by jamestrew** [comment]
Can you try the master branch or even `tag = '0.1.6'?

**Comment by V4G4X** [comment]
Thanks that fixed it. Now I'm using `branch = '0.1.x',` instead of providing a static version. 

That should keep me on the latest stable branch.
