### ISSUE TITLE
Add support for vim.lsp.buf.subtypes(), vim.lsp.buf.supertypes()

### ISSUE THREAD

**Issue by bellini666** [nvim-telescope/telescope.nvim#3064]
LSP subtypes and supertypes has just been implemented in neovim: https://github.com/neovim/neovim/commit/f190f758ac58d9cc955368e047b070e0a2261033

It would be nice to have those available as a builtin picker on telescope, just like we do for the other lsp pickers

**Comment by jamestrew** [comment]
We're freezing addition of new pickers for now - see https://github.com/nvim-telescope/telescope.nvim/issues/1228

We may revisit this in the future but for now I will close this issue.
