### ISSUE TITLE
[BUG] `typescript` (`ts`) files are not previewed with custom mime_hook for images

### ISSUE THREAD

**Issue by pinarruiz** [nvim-telescope/telescope.nvim#3068]
### Description

Setting up the mimehook to the example shown in [Configuration-Recipes#use-terminal-image-viewer-to-preview-images](https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#use-terminal-image-viewer-to-preview-images) makes `ts` files not being rendered

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1693350652
```

### Operating system and version

NixOs unstable

### Telescope version / branch / rev

 1-unstable-2024-04-21

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 8.7.1

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `media_files` ~
- No healthcheck provided

Telescope Extension: `ui-select` ~
- No healthcheck provided

Telescope Extension: `undo` ~
- No healthcheck provided
```

### Steps to reproduce

`Telescope find_files hidden=True`

### Actual behavior

![image](https://github.com/nvim-telescope/telescope.nvim/assets/37040888/cb7eb271-da47-4b41-9669-37966eb0ca47)

### Minimal config

```Lua
function(filepath, bufnr, opts)
  local get_ext = function(filepath)
    local split_path = vim.split(filepath:lower(), '.', {plain=true})
    return split_path[#split_path]
  end
  local is_image = function(filepath)
    local image_extensions = {'png','jpg'}   -- Supported image formats
    return vim.tbl_contains(image_extensions, get_ext(filepath))
  end
  if is_image(filepath) then
    local term = vim.api.nvim_open_term(bufnr, {})
    local function send_output(_, data, _ )
      for _, d in ipairs(data) do
        vim.api.nvim_chan_send(term, d..'\r\n')
      end
    end
    vim.fn.jobstart({
      'chafa', filepath  -- Terminal image viewer command
    }, {on_stdout=send_output, stdout_buffered=true, pty=true})
  else
    require("telescope.previewers.utils").set_preview_message(bufnr, opts.winid, "Binary cannot be previewed (" .. get_ext(filepath) .. ")")
  end
end
```

Edit: Format

**Comment by jamestrew** [comment]
Are you sure it's the image preview code that's affecting ts file previews?
ts file, or really any text files in don't reach the `mime_hook` code path so having this image preview hook shouldn't matter.

I'm also not able to reproduce this. I can get a ts file to show its preview.

https://github.com/nvim-telescope/telescope.nvim/assets/66286082/57cc784d-2f0a-4986-bbaf-ec6ec8d6d023

This was done using this minimal config. Granted I switched out `chafa` for `catimg`.

<details>

<summary>min.lua</summary>

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-tree/nvim-web-devicons",
    },
    config = function()
      require("telescope").setup({
        defaults = {
          preview = {
            mime_hook = function(filepath, bufnr, opts)
              local get_ext = function(filepath)
                local split_path = vim.split(filepath:lower(), ".", { plain = true })
                return split_path[#split_path]
              end
              local is_image = function(filepath)
                local image_extensions = { "png", "jpg" } -- Supported image formats
                return vim.tbl_contains(image_extensions, get_ext(filepath))
              end
              if is_image(filepath) then
                local term = vim.api.nvim_open_term(bufnr, {})
                local function send_output(a, data, c)
                  for _, d in ipairs(data) do
                    vim.api.nvim_chan_send(term, d .. "\r\n")
                  end
                end
                vim.fn.jobstart({
                  "catimg",
                  -- "chafa,"
                  filepath, -- Terminal image viewer command
                }, { on_stdout = send_output, stdout_buffered = true, pty = true })
              else
                require("telescope.previewers.utils").set_preview_message(
                bufnr,
                opts.winid,
                "Binary cannot be previewed (" .. get_ext(filepath) .. ")"
                )
              end
            end,
          },
        },
      })
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

</details>

I'd like you to try this minimal config.
This also could be like a Neovim installation issue or something if the minimal config is still giving you issues. Telescope is failing to get the `filetype` of the typescript file through various mechanisms. The main one being Neovim's built-in `vim.filetype.match` function. There's been cases in the past where a botched install would cause something like this and reinstalling neovim helped.

**Comment by pinarruiz** [comment]
Hi @jamestrew,

I cannot try it right now, as i am answering from my phone, but I will try asap.

> Are you sure it's the image preview code that's affecting ts file previews?

Removing the mimehook makes the ts files preview return, also if you notice on the screenshot that I provided the extension is present on the `Binary cannot be previewed` message, and since this extension on the message was added by me, I am sure that the mime hook is somehow affectinc the ts files preview.

**Comment by jamestrew** [comment]
> I am sure that the mime hook is somehow affectinc the ts files preview.

That's strange. Seems to me like a couple of things have to go very wrong for this to be the case..
1. `vim.filetype.match` fails to identify the file type based on filepath -> I just learned that `vim.filetype.match` for the `.ts` extension doesn't return a match so I guess this condition passes
2. `file --mime-type -b <filepath>` also thinks that your typescript files are not a text/inode/json file

https://github.com/nvim-telescope/telescope.nvim/blob/35f94f0ef32d70e3664a703cefbe71bd1456d899/lua/telescope/previewers/buffer_previewer.lua#L171-L175

I'd ask you to try the `file` command in your terminal against one of the ts files. Maybe we're getting some result that telescope isn't expecting. In which case, we can try to fix it.

**Comment by pinarruiz** [comment]
Running against the same file that is on the screenshot:

```bash
$ file --mime-type -b en.ts
application/javascript
```

Doing the same against a tsx file returns the same result, weird:
```bash
$ file --mime-type -b index.tsx
application/javascript
```

**Comment by jamestrew** [comment]
Interesting... never really questioned how `file` determines the mime type but a simple "hello world" typescript file gives `text/plain` for me but proper production ts file gives `application/javascript`.

We can fix this though.

**Comment by jamestrew** [comment]
If we can give the linked PR a try, that would be helpful.

**Comment by pinarruiz** [comment]
Just tried it and its working now:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/37040888/9fcc5811-ab38-4116-ae61-19d17705e3dc)
It was blurred for privacy reasons.

Thanks for that, cant wait for it to merge :smile:, just to confirm, **without #3083** it does **not** work still:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/37040888/e3816da5-58a3-45fe-bddd-008694a33d29)
