### ISSUE TITLE
Allow resuming a search

### ISSUE THREAD

**Issue by AndrewHess** [nvim-telescope/telescope.nvim#3069]
**Is your feature request related to a problem? Please describe.**
I often want to do a live grep search with telescope, then go into one of the files that matched the search (e.g., to add a print statement for debugging), and then return to my live grep search so I can do similar things for other matches. 

**Describe the solution you'd like**
Add a command like `:Telescope resume` that will take me back to my last Find Files search or Live Grep search, with the matches sorted in the same order as they were, and with my cursor on the same match I was on when I last exited search (either through `<ESC>` or by `<CR>`). I personally don't care what `:Telescope resume` does when the search pane is already open.

**Describe alternatives you've considered**

**Additional context**

**Comment by jamestrew** [comment]
`:Telescope resume` already exists :grin: 

I would just use `<C-q>` to send the results to the quickfix list and use `:cnext`/`:cprev` to cycle between results (or select manual manually from the list) for your workflow you're describing though.

**Comment by AndrewHess** [comment]
Oh... thanks!
