### ISSUE TITLE
Error executing vim.schedule on Telescope Builtin features

### ISSUE THREAD

**Issue by mnabila** [nvim-telescope/telescope.nvim#308]
![Screenshot_20201203_063109](https://user-images.githubusercontent.com/37516576/100944505-06950b00-3532-11eb-95fd-928132f2dd54.png)
![Screenshot_20201203_064024](https://user-images.githubusercontent.com/37516576/100944777-81f6bc80-3532-11eb-86d7-a1bb36b9084a.png)

### Description
Get error when execute command `:Telescope builtin` and after hit enter cursor move to preview window

> "~/.local/share/nvim/plugged/telescope.nvim/lua/telescope/builtin/files.lua" 248L, 6699C                                            
Error executing vim.schedule lua callback: Vim(lua):E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:1
19: query: invalid node type at position 1483

### Details

<details><summary>Reproduce</summary>

1. open nvim from terminal 
2. execute `:Telescope builtin`
3. .... bang here is the issue

</details>

<details><summary>Environment</summary>

- nvim version:  NVIM v0.5.0-898-g8fb786e41
- Operating system: Arch Linux [neovim-git](https://aur.archlinux.org/neovim-git.git)
- Telescope commit: 2fd09b9

</details>

<details><summary>Configuration</summary>
<p>
 

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF
local actions = require('telescope.actions')
local telescope = require('telescope')

telescope.setup {
    defaults = {
        vimgrep_arguments = {
            'rg',
            '--color=never',
            '--no-heading',
            '--with-filename',
            '--line-number',
            '--column',
            '--smart-case'
        },
        prompt_position = "bottom",
        prompt_prefix = "❱❱",
        selection_strategy = "reset",
        sorting_strategy = "descending",
        layout_strategy = "flex",
        layout_defaults = {
            -- TODO add builtin options.
        },
        file_sorter = require('telescope.sorters').get_fuzzy_file,
        file_ignore_patterns = {},
        generic_sorter = require('telescope.sorters').get_generic_fuzzy_sorter,
        shorten_path = true,
        winblend = 0,
        width = 0.75,
        preview_cutoff = 120,
        results_height = 1,
        results_width = 0.8,
        border = {},
        borderchars = {"─", "│", "─", "│", "┌", "┐", "┘", "└"},
        color_devicons = true,
        use_less = false,
        set_env = {['COLORTERM'] = 'truecolor'}, -- default { }, currently unsupported for shells like cmd.exe / powershell.exe
        default_mappings = {
            i = {
                ['<C-j>'] = actions.move_selection_next,
                ['<C-k>'] = actions.move_selection_previous,
                ['<CR>'] = actions.goto_file_selection_edit,

                ['<C-v>'] = actions.goto_file_selection_vsplit,
                ['<C-x>'] = actions.goto_file_selection_split,
                ['<C-t>'] = actions.goto_file_selection_tabedit,
                ['<Esc>'] = actions.close,

                ['<C-u>'] = actions.preview_scrolling_up,
                ['<C-d>'] = actions.preview_scrolling_down
            },
            n = {
                ['<CR>'] = actions.goto_file_selection_edit,
                ['<C-v>'] = actions.goto_file_selection_vsplit,
                ['<C-x>'] = actions.goto_file_selection_split,
                ['<C-t>'] = actions.goto_file_selection_tabedit,
                ['<Esc>'] = actions.close,

                ["j"] = actions.move_selection_next,
                ["k"] = actions.move_selection_previous,

                ['<C-u>'] = actions.preview_scrolling_up,
                ['<C-d>'] = actions.preview_scrolling_down
            }
        }
    }
}
EOF
```

**Comment by tjdevries** [comment]
That looks like a tree sitter problem. You have something broken with tree sitter and lua perhaps?

**Comment by Conni2461** [comment]
Most definitely a treesitter issue. They did a parser version bump a couple of days ago. You need to run `:TSUpdate`

**Comment by mnabila** [comment]
> That looks like a tree sitter problem. You have something broken with tree sitter and lua perhaps?

@tjdevries  I don't know but this my configuration for treesitter
```
require('nvim-treesitter.configs').setup {highlight = {enable = true}, indent = {enable = true}}
```

**Comment by mnabila** [comment]
> Most definitely a treesitter issue. They did a parser version bump a couple of days ago. You need to run `:TSUpdate`



after try `:TSupdate` my problem is gone, thanks for your help 
![Screenshot_20201203_155431](https://user-images.githubusercontent.com/37516576/100986518-e2f8b180-357f-11eb-869e-d5ff7121da77.png)

cc @tjdevries @Conni2461
