### ISSUE TITLE
"follow" option should be available either globally or for all relevant builtin pickers.

### ISSUE THREAD

**Issue by CactusSoup** [nvim-telescope/telescope.nvim#3090]
**Is your feature request related to a problem? Please describe.**
When working in project directories that involve symlinks, neither _find_files_ nor _live_grep_ can read files through those symlinks by default. The "**follow**" option exists for find_files to follow symlinks, but doesn't exist for _live_grep_. While I can understand symlink following not being the default behaviour, I can't see a likely reason for only some pickers to support it through options.

**Describe the solution you'd like**
Either **follow** to be moved to defaults and apply wherever possible, or at least be made available across all pickers that use ripgrep.

**Describe alternatives you've considered**
Can currently work around by fiddling with vimgrep_arguments, but this is more vulnerable to breaking changes and is too easy to introduce errors.

**Additional context**
N/A

**Comment by jamestrew** [comment]
You can use the `additional_args` option on both `live_grep` and `grep_string` to pass any rg option including `--follow`.

I think that should help.
