### ISSUE TITLE
filename_first renders path not correctly for git_status

### ISSUE THREAD

**Issue by LinoWhy** [nvim-telescope/telescope.nvim#3106]
### Description

With the following config
```lua
path_display = { filename_first = { reverse_directories = false } },
```

Filename is shown first, directroies are shown with grey color.
![image](https://github.com/nvim-telescope/telescope.nvim/assets/43626684/14d09597-f681-480b-816e-f71a5a659470)

But the directroies are not in grey with git_status:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/43626684/265195af-946a-4580-97ff-b37f73d1af95)

### Neovim version

```markdown
NVIM v0.10.0-dev-3122+ga0a189a8e
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

### Operating system and version

Ubunut 22.04

### Telescope version / branch / rev

master

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- WARNING nvim-treesitter not found. (Required for `:Telescope treesitter`.)

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0 (rev 4aa92c5b6e)
- OK fd: found fd 10.1.0

===== Installed extensions ===== ~
```

### Steps to reproduce

1. open nvim with mini config
2. Type ":Telescope git_status"

### Actual behavior

Directories in telescope git_status is not shown in grey.

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
    opts = {
      defaults = {
        layout_strategy = "vertical",
        path_display = { filename_first = { reverse_directories = false } },
      },
    },
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
Thanks for reporting - I can reproduce this as well.
I'll try to get around to this when I get a chance. Also happy to help someone else would might be interested.

**Comment by jamestrew** [comment]
Oh ok so this is actually a known limitation of the `filename_first` `path_display` option at the moment. It doesn't work with all pickers (specifically those that use `entry_display.create` as part of the entry making process).
https://github.com/nvim-telescope/telescope.nvim/pull/3010#issuecomment-2067544927

This is definitely something I want to address sooner rather than later but needs some consideration.

**Comment by jamestrew** [comment]
Ok fixing the `entry_display.create` compatibility was actually pretty trivial.
Let me know if that above PR helps.

**Comment by LinoWhy** [comment]
> Ok fixing the `entry_display.create` compatibility was actually pretty trivial. Let me know if that above PR helps.

@jamestrew LGTM, thanks!
![image](https://github.com/nvim-telescope/telescope.nvim/assets/43626684/a10fdc44-34b6-4db2-b5d6-23d7bd4842dd)

**Comment by eddiezane** [comment]
Thanks for reporting this and the fix! I just came across this while pulling out hair for the past week trying to figure out why `filename_first` wasn't working with `find_files`. I had just ruled out it was something on my end :sweat_smile:. Appreicate y'all.
