### ISSUE TITLE
Prompt-line results count jumps one character to the left during window creation

### ISSUE THREAD

**Issue by sunjon** [nvim-telescope/telescope.nvim#311]
As stated in subject line. I created a [slowed down capture](https://streamable.com/hwf063) to help illustrate the issue.

**Comment by tami5** [comment]
Also when typing, I'm currently using fzy-native i'm experiencing the same thing

**Comment by sunjon** [comment]
It would be nice to hide the cursor on creation/teardown too.
There's a short period where the cursor changes to insertmode for some frames before the prompt is ready to be focused. It's also visible floating in the middle of nowhere on teardown.

I'd originally created the capture to sanity-check whatever made it look jumpy, and I think it's the cursor changing shape and not doing anything during creation.

**Comment by sunjon** [comment]
I dug into this a little more;

During window creation, `Picker:find()` is called multiple times, the first time it doesn't have `prompt_prefix` applied to it and [the padding is calculated](https://github.com/nvim-telescope/telescope.nvim/blob/68c587034588b114687e26a940f7d22334879363/lua/telescope/pickers.lua#L401) incorrectly.
