### ISSUE TITLE
Editorconfig to ignore 

### ISSUE THREAD

**Issue by alfonsocv12** [nvim-telescope/telescope.nvim#3114]
**Is your feature request related to a problem? Please describe.**
I can't grep find because theres files making noice on the code, if I look for CreateUser this files takes 500+ instances of CreateUser.

**Describe the solution you'd like**
I need to ignore this files, but I don't want to add this to my global config I'll like to added to project config under .editorconfig

**Describe alternatives you've considered**
Use globalconfig, or add a new property on editorconfig and created on my own

**Additional context**
I use this command to grep find on macOS

 `builtin.grep_string({ search = vim.fn.input("Grep > ") });`

**Comment by jamestrew** [comment]
I don't think editorconfig has anything to do with listing files to ignore.

I'm not sure exactly what you mean by "global config" - do you mean the telescope set up config or maybe you mean git config?
Either way, we use ripgrep as the "search engine" for `grep_string` and `live_grep` so anything ripgrep respects, you can use as well. By default this would be `.gitignore`, `.ignore` or `.rgignore`.

My first recommendation would be to put the file you want to ignore into one of these files in your project root directory.
Alternatively, you can use the `additional_args` option for `grep_string`, `live_grep` to pass the `--glob` flag and a pattern to match the file you want to ignore. see `:h telescope.builtin.grep_string()` and the rg manpages for more info.
