### ISSUE TITLE
Fuzzy finder for LSP diagnostics

### ISSUE THREAD

**Issue by alex-popov-tech** [nvim-telescope/telescope.nvim#313]
Hey! Thanks for the plugin!
I could not find some function to search through diagnostic errors for the buffer, which is super useful...
Did i miss that function, or it was not added yet?
Or maybe i can add it myself using telescope api?
Any help would be appreciated!

**Comment by Conni2461** [comment]
Are you talking about `builtin-lsp`?
If so you can do `:lua vim.lsp.diagnostic.set_loclist({open_loclist = false})` to populate location list with diagnostics
After that you can run `:lua require'telescope.builtin'.loclist{}`

**Comment by alex-popov-tech** [comment]
@Conni2461 yes exactly...if you have a complete function, can you please share it? i will try to build it myself meanwhile :)

**Comment by Conni2461** [comment]
```lua
local m = {}

m.show_diagnostics = function(opts)
  opts = opts or {}
  vim.lsp.diagnostic.set_loclist({open_loclist = false})
  require'telescope.builtin'.loclist(opts)
end

return m
```

Would be a lua modul. E.g. `.config/nivm/lua/modules/telescope.lua`.
Then you shoud be able to do `:lua 'require('module/telescope').show_diagnostics()`

**Comment by alex-popov-tech** [comment]
thanks, that works like a charm!

**Comment by fdschmidt93** [comment]
For anyone else coming here and wondering how to highlight the entries resulting from the above function like red for error (something quite worthwhile for my Python coding), etc. , you can easily create a custom `entry_maker` on top of @Conni2461's function (thanks!), similar to the below code which links signs and highlighting to builtin LSP highlight groups. Preview attached at the bottom.

```lua
local telescope_utils = require('telescope.utils')
local entry_display = require('telescope.pickers.entry_display')

local function gen_from_lsp_loclist(opts)
  opts = opts or {}
  opts.tail_path = telescope_utils.get_default(opts.tail_path, true)

  local displayer = entry_display.create {
    separator = "▏",
    items = {
    -- slighltly increased width
      { width = 11 },
      { width = 48 },
      { remaining = true }
    }
  }

  local make_display = function(entry)
    local filename
    if not opts.hide_filename then
      filename = entry.filename
      if opts.tail_path then
        filename = telescope_utils.path_tail(filename)
      elseif opts.shorten_path then
        filename = telescope_utils.path_shorten(filename)
      end
    end

    -- add styling of entries
    local type = {I = "Information", W = "Warning", E = "Error"}
    local sign = vim.trim(vim.fn.sign_getdefined("LspDiagnosticsSign" .. type[entry.type])[1].text)
    local pos = string.format("%3d:%2d", entry.lnum, entry.col)

    local line_info = {
      table.concat({sign, pos}, " "),
      "LspDiagnostics" .. type[entry.type]
    }

    return displayer {
      line_info,
      entry.text:gsub(".* | ", ""),
      filename,
    }
  end

  return function(entry)
    local filename = entry.filename or vim.api.nvim_buf_get_name(entry.bufnr)

    return {
      valid = true,

      value = entry,
      ordinal = (
        not opts.ignore_filename and filename
        or ''
        ) .. ' ' .. entry.text,
      display = make_display,

      filename = filename,
      type = entry.type,
      lnum = entry.lnum,
      col = entry.col,
      text = entry.text,
      start = entry.start,
      finish = entry.finish,
    }
  end
end

m.show_lsp_diagnostics = function(opts)
  opts = opts or {}
  opts.entry_maker = gen_from_lsp_loclist(opts)
  vim.lsp.diagnostic.set_loclist({open_loclist = false})
  require'telescope.builtin'.loclist(opts)
end
```

![diagnostic_preview](https://user-images.githubusercontent.com/39233597/107996092-d7921f80-6fdf-11eb-959a-3fa9fb265f92.png)

**Comment by clason** [comment]
To be honest, if `lsp_*_symbols` is built in, I don't see why a nice `lsp_diagnostics` shouldn't be -- it certainly sounds useful to me! 

(Especially if it's prettied up and not just a one-liner, although it probably shouldn't be fancy for the sake of it with colors and icons -- that is indeed something for an external plugin. But adding a column for `Hint`/`Warning`/`Error` -- and possibly allowing filtering on that with, e.g., `:warn:foo` would be worth it to me.)

**Comment by fdschmidt93** [comment]
> it probably shouldn't be fancy for the sake of it with colors and icons 

The LSP highlight group sign text defaults to "E", "I", and "W", which I'd find meaningful; in other words, if I didn't set it with `lspsaga` the red cross would be an E instead. 

> possibly allowing filtering on that with, e.g., `:warn:foo` would be worth it to me

Is something along these lines, i.e. filter prompt buffer by set tag, already setup? Grepping through telescope doesn't yield meaningful results off the top. 

In addition, a builtin `lsp_diagnostics` picker should maybe not even rely on `set_loclist` as I've realized it seems, once set, `loclist` severity levels don't seem to distinguish between hints and information. `vim.lsp.diagnostic.get(0)` (`get_all()`?*) should work instead. Severity filters could always be applied here (both `set_loclist` and `get`).

But agree, the general functionality should probably be included. Happy to try to polish the code snippet above and submit a PR eventually.

\* Side note: I'd expect `get_all()` to return diagnostics for my entire project, ideally regardless of whether buffer would be open or not. I'd have to check how coc.nvim handles that, possibly an upstream issue.

**Comment by clason** [comment]
> > it probably shouldn't be fancy for the sake of it with colors and icons
> 
> The LSP highlight group sign text defaults to "E", "I", and "W", which I'd find meaningful; in other words, if I didn't set it with `lspsaga` the red cross would be an E instead.

Sorry, that wasn't a direct comment on your snippet; just a general opinion.

> > possibly allowing filtering on that with, e.g., `:warn:foo` would be worth it to me
> 
> Is something along these lines, i.e. filter prompt buffer by set tag, already setup? Grepping through telescope doesn't yield meaningful results off the top.

No, it isn't. https://github.com/nvim-telescope/telescope-frecency.nvim does it for project, but I believe this would be generally useful (e.g., for LSP symbol kinds or grep file names).

As for the rest: 👍  :)

**Comment by clason** [comment]
I really do think this should be builtin (even if it can be done with simple snippet), for two reasons:
1. discoverability (people keep asking for a nicer way of accessing diagnostics)
2. providing a method that _doesn't_ clobber loclist on the way.

I therefore take the liberty of reopening this issue. @fdschmidt93 If you have the time and wouldn't mind turning your snippet into a PR, that would be appreciated!

**Comment by fdschmidt93** [comment]
I started working on it! And it already supports filtering by diagnostic type :) Main outstanding item is to check how to incorporate it cleanly such that it can also be levered for other pickers, e.g. :fuzzy_file_name: in vim grep.

I'll open the PR throughout next week. Apologies, was otherwise preoccupied and will finalize visual selection and this asap.

**Comment by fdschmidt93** [comment]
@clason mission completed :)

Many thanks to @Conni2461 and @elianiva ! This can be closed :)
