### ISSUE TITLE
find_files not hiding hidden files by default

### ISSUE THREAD

**Issue by andradei** [nvim-telescope/telescope.nvim#3132]
### Description

`:Telescope find_files` and `require('telescope.builtin').find_files()` are including `.git` directory in the results.

Even when I explicitly set ``require('telescope.builtin').find_files({ hidden = false})`, the `.git` directory and all the `.file_name`s are showing.

![Kooha-2024-05-21-22-12-28](https://github.com/nvim-telescope/telescope.nvim/assets/2653546/433b69af-b59e-46d3-a360-51312b445259)

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
```

### Operating system and version

Arch (EndeavourOS)

### Telescope version / branch / rev

branch: master / commit: 4aed639

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 10.1.0

===== Installed extensions ===== ~

Telescope Extension: `terms` ~
- No healthcheck provided

Telescope Extension: `themes` ~
- No healthcheck provided
```

### Steps to reproduce

1. Start Neovim on a fit project/directory
2. Run `:Telescope find_files`

### Expected behavior

Dot not display hidden files and directories.

### Actual behavior

`.git`, `.gitignore`, and all other hidden files and directories are present in the result.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by sineptic** [comment]
I can't reproduce your bug. Add YOUR minimal config, not default. Mb you change options in it.

**Comment by andradei** [comment]
@sineptic I didn't change any options. Straight up copied and pasted this minimal config from the bug report suggestion, called it `~/.config/nvim-minimal/init.lua`, and ran with `NVIM_APPNAME=nvim-minimal nvim .`

**Comment by andradei** [comment]
It's not an issue. My `ripgrep` loads my custom `ripgreprc` that includes `--hidden` and telescope is honoring that.

Perhaps telescope should run `ripgrep --no-config` and provide it's own set of "sensible defaults" for consistent behavior within neovim while keeping it isolated from the user's customization.

Let me know if this is desirable and I'll create a separate issue. Otherwise, this is resolved.

**Comment by jamestrew** [comment]
I think many would argue telescope respecting some global config for fd/ripgrep would be sensible but it's definitely a matter of preference and we offer options you can pass to augment this provided fd/ripgrep does.

`find_files` can take an option called `find_command`. You could do something like
```lua
require("telescope.builtin").find_files { find_command = { "rg", "--files", "--color", "never", "--no-config" } }
```
Similarly for `live_grep` and `grep_string`, these take a `additional_args` option
```lua
require("telescope.builtin").live_grep { additional_args = { "--no-config" } }
require("telescope.builtin").grep_string { additional_args = { "--no-config" } }
```
