### ISSUE TITLE
Need provision to stop ignoring files and folders that are ignored by git

### ISSUE THREAD

**Issue by shibisuriya** [nvim-telescope/telescope.nvim#3136]
**Is your feature request related to a problem? Please describe.**

I have a folder called 'temp-notes' where I store my notes inside a git repo, I want git to ignore this folder since it is personal notes (I added this folder to .gitignore)  but I don't want telescope to ignore this folder, I want telescope to list files from this folder as well when `find_files` is called.

**Describe the solution you'd like**

I want telescope's find_files api to list the files present in this folder which is gitignored, telescope shouldn't list files present in node_modules (obiviously).

**Describe alternatives you've considered**

I didn't try any alternative, I manually open the files for now.

**Additional context**

This can be achieved in vscode by,

```json 
{
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "**/*.code-search": true,
    "**/temp-notes": false
}  
}

```

**Comment by jamestrew** [comment]
You can use something like a `.ignore` file and just whitelist whatever directory/file you want `fd`/`rg` to always show.

eg.
```
!**/temp-notes
```

You can be more specific with `.fdignore` or `.rgignore`.

**Comment by shibisuriya** [comment]
Works, thank you. @jamestrew.
