### ISSUE TITLE
current_buffer_fuzzy_find searches first opened buffer instead of current buffer

### ISSUE THREAD

**Issue by Rydwxz** [nvim-telescope/telescope.nvim#3142]
### Description

I'm not sure what nvim-tree has to do with, but the issue reproduced as soon as I have both plugins. As you can see here I am looking at telescope.lua but nv-tree.lua appears in the search box.
![image](https://github.com/nvim-telescope/telescope.nvim/assets/114803384/8894faf7-4aba-48eb-8eb9-aae4419f69c3)

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
```

### Operating system and version

Arch Linux

### Telescope version / branch / rev

current master

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- WARNING nvim-treesitter not found. (Required for `:Telescope treesitter`.)

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 10.1.0

===== Installed extensions ===== ~
```

### Steps to reproduce

Open nvim. Open a buffer. Open another buffer in the same window. Use current_buffer_fuzzy_find

### Expected behavior

current_buffer_fuzzy_find searches the currently active buffer.

### Actual behavior

current_buffer_fuzzy_find searches the first buffer opened.

### Minimal config

```Lua
https://github.com/Rydwxz/nvim-config/tree/telescope_debug
```

**Comment by jamestrew** [comment]
Sorry but I can't help you without an proper minimal config. Your linked config doesn't qualify as a minimal config. 

A minimal config is the one that was originally in the bug report template with the minimal amount of changes requires to reproduce the issue.

**Comment by Rydwxz** [comment]
Sorry about that. I am so far unable to reproduce it in true minimal. I looked [at some of the code](https://github.com/nvim-telescope/telescope.nvim/blob/4c96370cf93e2ba287548da12d673442d0ffecc3/lua/telescope/builtin/__files.lua#L467) and saw that the bufnr came from the opts passed to the function. My keymaps were set up like this:
```
local ivy = require('telescope.themes').get_ivy()
vim.keymap.set('n', '<leader>f/', function() require('telescope.builtin').current_buffer_fuzzy_find(ivy) end)
``` 
So I took that theme out, leaving the opts blank, and it is working as expect now.

**Comment by jamestrew** [comment]
Oh that's because you're essentially initializing the options that will be used for the `current_buffer_fuzzy_find` picker outside of the keybinding when telescope is loaded.
And these options are mutated and reused each time you call `current_buffer_fuzzy_find`. One of fields in this table is `bufnr` which is set to the value of `nvim_get_current_buf()` when you first call `current_buffer_fuzzy_find`.

You just have to move the `get_ivy()` call inside the `keymap.set` callback.
```lua
vim.keymap.set("n", "<leader>f/", function()
  local ivy = require("telescope.themes").get_ivy()
  require("telescope.builtin").current_buffer_fuzzy_find(ivy)
end)
```

Hope that helps.

**Comment by Rydwxz** [comment]
I see, that makes perfect sense. Thank you for the explanation.
Honestly tho, I am not at all unhappy with the default style any more and I'm gonna keep using it.
