### ISSUE TITLE
A global file selector?

### ISSUE THREAD

**Issue by etherswangel** [nvim-telescope/telescope.nvim#3149]
**Is your feature request related to a problem? Please describe.**
To open a random file out of current project

**Describe the solution you'd like**
A similar behavior to shell completion for `ls` etc. Start with files/dirs under cwd. When I type `~`, the "cwd" changes to `$HOME`; if `/`, the "cwd" becomes `/`...

**Additional context**
Actually I'd like to make neovim as an alternative to command line file explorer. A combination of `telescope` and `oil` will be perfect in some scenarios. This could be a great way of searching random files.

If there's already something done this feature, please inform me and sorry to bother :D

**Comment by Conni2461** [comment]
why doesnt https://github.com/nvim-telescope/telescope-file-browser.nvim work for you?

**Comment by etherswangel** [comment]
If I didn't get wrong, `file-browser` always looks for files under cwd/path. I can't type "/" in the search box, "~" also doesn't work, every time I hit slash it enters the dir and clears the path, links are hidden (probably configurable)... It's great for navigating the project layer by layer but when searching for random files I just don't feel it as natural as `builtin.find_files`. However `builtin.find_files` shows all files recursively, and thus gets stuck if I set path to "/", "/" and "~" doesn't work in search box either

**Comment by Conni2461** [comment]
Then i have no idea what you are looking for, if you just want to relaunch find_files with a different cwd on `~` you can write an Action for that yourself. We will not provide somethong like that because its highly opinionated

**Comment by etherswangel** [comment]
Say I'm previewing "/path/to/config/conf_1/subdir/init.conf", if I wanted to check "conf_2", I should move the cursor (in search box) to '1', delete it, and type '2'. It should be a common workflow when using cmd-line tools like `ls`, `cat`, etc. 

But what `file-browser` offers is to go up twice, move cursor in the list to "conf_2", type "subdir" and enter, then type "init.conf". This isn't efficient at all, this example isn't common tho but I think you can understand the inconvenience of `file-browser` in such scenario.

And for `find_files`, it may take \~15s to respond when cwd is "\~", totally unusable. If it was "/" I have to restart neovim😂.

What I'm looking for is a way that I can freely type any valid path in the search box and modify it. The list should behave like shell completion, respond in real time as typing. I think this should be doable since the completion for `:edit` is already the thing? Just wish to use telescope's fuzzy search and wonderful UI, also I can filter the results easily.

**Comment by jamestrew** [comment]
Depending on how many files you have and your hardware, searching from `~` or `/` is expected to be totally impractical with telescope.

If it's just a directory/file navigating mechanism your looking for, then `file_browser` is the closest thing we offer. There was a request for something very similar to your request here https://github.com/nvim-telescope/telescope-file-browser.nvim/issues/288
Hopefully you can find some inspiration but I don't think we'd be implementing this into telescope core anytime soon.
