### ISSUE TITLE
Telescope results off the buffer

### ISSUE THREAD

**Issue by jcribeirooo** [nvim-telescope/telescope.nvim#3160]
### Description

 After updating Telescope, the results of find files comes off the buffer. Then, if I navigate up/down, the results will show. 

Searching:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/13478911/8297e510-a3a8-4688-8a23-ec94204f97d6)

After pressing arrow up:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/13478911/21abe3b8-29f4-4e3c-8e4f-ae212b54d186)

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
```

### Operating system and version

6.9.3-arch1-1

### Telescope version / branch / rev

"telescope.nvim": { "branch": "master", "commit": "776b509f80dd49d8205b9b0d94485568236d1192" }

### checkhealth telescope

```markdown
==============================================================================
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 10.1.0

===== Installed extensions ===== ~
```

### Steps to reproduce

Find files using telescope. Some files will be off the buffer.
Then press arrow up, and the files go back within the buffer.

### Expected behavior

All files to be in the Results buffer.

### Actual behavior

Searched files off the Results buffer.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
I'm pretty sure you just need to update telescope.

```
"telescope.nvim": { "branch": "master", "commit": "776b509f80dd49d8205b9b0d94485568236d1192" }
```
I think you're actually pinned to the commit, which is quite old. There was a fix for this issue that was related to a neovim 0.10 change.

Can you verify you're experiencing the issue with the minimal config?

**Comment by jcribeirooo** [comment]
You are right. I missed that my config was setting the tag on my Lazy vim config when defining the telescope. Thanks!
`{
        "nvim-telescope/telescope.nvim",
        tag = "0.1.2",  /* I removed it from here and got the fix as you said. */       
        dependencies = { "nvim-lua/plenary.nvim" },
        config = config("plugin.plenary"),
}`
