### ISSUE TITLE
`Cursor position outside buffer` error in `pickers.lua`

### ISSUE THREAD

**Issue by jghauser** [nvim-telescope/telescope.nvim#3163]
### Description

I'm the author of the plugin [papis.nvim](https://github.com/jghauser/papis.nvim), which implements a Telescope picker. A user has opened a [bug report](https://github.com/jghauser/papis.nvim/issues/36) and reported that they get an error when opening the picker. I've now realised that the only reason I wasn't getting the error was because I had `sorting_strategy = "ascending"` in my config. Once I changed that, I also started getting the error. It doesn't always happen when opening the picker -- sometimes I need to type some characters first.  The error is:

```
Error executing vim.schedule lua callback: ...mPackages/start/telescope.nvim/lua/telescope/pickers.lua:1472: Cursor position outside buffer                                  
stack traceback:                                                                                                                                                             
        [C]: in function 'nvim_win_set_cursor'                                                                                                                               
        ...mPackages/start/telescope.nvim/lua/telescope/pickers.lua:1472: in function ''                                                                                     
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

It seems to be triggered by a line that only executes when the `sorting_strategy` is `descending`:

https://github.com/nvim-telescope/telescope.nvim/blob/f12b15e1b3a33524eb06a1ae7bc852fb1fd92197/lua/telescope/pickers.lua#L1469-L1475

The error seems related to (at least) the following other bug reports (though it's caused by a different line/file):
- #957
- #1226 
- #1727 

It's of course possible that something is wrong with how I implemented the picker, though I'm at a loss as to how I should further troubleshoot this. I would be very grateful for any pointers!

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1693350652
```

### Operating system and version

Nix unstable

### Telescope version / branch / rev

35f94f0ef32d70e3664a703cefbe71bd1456d899

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 10.1.0

===== Installed extensions ===== ~

Telescope Extension: `papis` ~
- No healthcheck provided
```

### Steps to reproduce

I haven't been able to reliably reproduce the issue unfortunately. It requires installing my plugin, and (as far as I can tell) it only occurs when the picker is used to select from a sufficiently big number of entries (which in this case are bibliographic entries in a research library). In my library of about 1800 entries, the error happens very reliably.

My plugin provides a `flake.nix` with a devShell, where the command `nvim-test` launches a neovim instance with a minimal library (first clone the repo, then `nix develop` to enter the devShell). Unfortunately, that also doesn't cause the error as the test library is too small. I'm happy to provide access to my library for troubleshooting or to do whatever on my system to help find out what's going on.

### Expected behavior

I would expect the picker to open without errors and for no errors to occur when typing to search among entries.

### Actual behavior

The error mentioned in the description occurs.

### Minimal config

I've tried to get the minimal config to work but ran into a bunch of problems. Nix seems to make installing the `sqlite.lua` dependency difficult with packer. The config that I use to test my plugin is in my `flake.nix` [here](https://github.com/jghauser/papis.nvim/blob/main/nix/ci-overlay.nix) and is quite minimal. I can try to get this to work in a VM if needed, but I thought I'd ask first -- maybe someone knows what's up with the info provided already.

**Comment by jamestrew** [comment]
Hm..
I've not experienced this issue even with ~86k entries for `find_files` with `sorting_strategy='descending'` or any other pickers even with 1000+ entries.
But there's nothing obviously wrong with your picker either as far as I can tell.
Is the `wrap_results` option being used in your config?

I'm a little confused about that bit of code to begin with. What's with the double `nvim_win_set_cursor` call? Seems redundant to me.
Maybe @sultanahamer might have some insight?

**Comment by jghauser** [comment]
Thanks a lot for taking a look!

> I've not experienced this issue even with ~86k entries for `find_files` with `sorting_strategy='descending'` or any other pickers even with 1000+ entries.

It's possible, I suppose, that some particular entry causes the error and that large libraries simply increase the chances of having such an entry. I'll try 'bisecting' my library to see if I can find anything (might only get to it tomorrow, it's rather tedious).

> Is the `wrap_results` option being used in your config?

No, neither my own config nor the test config in my devShell uses this option.

**Comment by sultanahamer** [comment]
@jghauser stack trace is pointing to line

` vim.api.nvim_win_set_cursor(self.results_win, { self.max_results, 1 })`

if this has out of bounds issue then try some print statements to check what is the line count in the results buffer. 3rd line in below code should help you print it. Usually its always 250. Could you check if its the same in your case with and without the plugin? You can check the count by looking by running command :messages

```
      local visible_result_rows = vim.api.nvim_win_get_height(self.results_win)
      vim.api.nvim_win_set_cursor(self.results_win, { self.max_results - visible_result_rows, 1 })
      print(vim.api.nvim_buf_line_count(vim.api.nvim_win_get_buf(self.results_win)) .. "yolo line count")
      vim.api.nvim_win_set_cursor(self.results_win, { self.max_results, 1 })
```

**Comment by jghauser** [comment]
Thanks for looking into this @sultanahamer! Whenever the error occurs, the line count is 249.

**Comment by jghauser** [comment]
Ok, I found the error. One of the strings contained a `\n` and I suspect this was also the cause behind my user's error. The mistake is therefore with my plugin not giving telescope proper lines rather than with telescope itself. I'm gonna close this bug report. Thanks again!

**Comment by MoritzHamann** [comment]
@jghauser you have no idea how much debugging you saved me 🎉 thanks so much!

**Comment by sonictim** [comment]
I'm experiencing the same "Cursor position outside buffer" error at pickers.lua:1469, but with a different root cause that might warrant reopening this issue.

  **My scenario:**
  - Using `builtin.quickfix()` with Rust diagnostic entries
  - Quickfix entries have `filename=nil` but valid `bufnr` (e.g., `bufnr=1, filename=nil, lnum=15, col=7`)
  - Tried the filename resolution workaround from similar issues - still fails
  - No newlines in the text data (I specifically cleaned them)

  **Minimal reproduction:**
  ```lua
  vim.keymap.set('n', '<leader>sq', function()
    vim.diagnostic.setqflist { open = false }
    if vim.tbl_isempty(vim.fn.getqflist()) then
      vim.notify('Good Job!! Global Quickfix list is empty', vim.log.levels.WARN)
      return
    end
    require('telescope.builtin').quickfix()
  end)

  Extensive testing reveals this is specific to telescope's quickfix picker:
  - ✅ builtin.loclist() works perfectly with the same Rust diagnostics
  - ❌ builtin.quickfix() fails with cursor position error
  - ✅ Both loclist and quickfix work fine with Lua diagnostics (after cleaning up config)
  - ❌ Only quickfix fails with Rust diagnostics

  This suggests the issue is in telescope's quickfix-specific handling of Rust diagnostic entries, not in the diagnostic data itself or telescope's general picker logic.

  Additional context:
  - Occurs specifically with Rust diagnostics (rust-analyzer warnings/errors)
  - Sample entry: constant 'BIT_DEPTH_8' is never used with bufnr=1, filename=nil, lnum=15, col=7

  Note: The function does work correctly - telescope opens and I can navigate/select quickfix entries successfully. The error is just an annoying message that appears every time, requiring me to press Enter to dismiss it before I can use telescope.

  Environment:
  - Neovim v0.11.0
  - Latest telescope.nvim (updated via Lazy)
  - macOS

  The error suggests telescope's quickfix picker has issues when filename=nil but bufnr is valid with Rust diagnostics specifically, which is different from the newline issue that was originally resolved here. Should this be reopened or filed as a
  separate issue?

  Stack trace:
  Error executing vim.schedule lua callback: ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:1469: Cursor position outside buffer
  stack traceback:
          [C]: in function 'nvim_win_set_cursor'
          ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:1469: in function ''
          vim/_editor.lua: in function <vim/_editor.lua:0>
