### ISSUE TITLE
Telescope buffers is failing

### ISSUE THREAD

**Issue by andrzejsliwa** [nvim-telescope/telescope.nvim#3171]
### Description

When I'm trying to open Telescope for buffers I'm receiving error:

![obraz_2024-06-15_183641709](https://github.com/nvim-telescope/telescope.nvim/assets/9280/8678517e-59f8-42ac-b186-e31151e69b3b)

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
Run "nvim -V1 -v" for more info
```

### Operating system and version

Windows 11 / WSL2

### Telescope version / branch / rev

latest

### checkhealth telescope

```markdown

==============================================================================
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- WARNING nvim-treesitter not found. (Required for `:Telescope treesitter`.)

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 9.0.0

===== Installed extensions ===== ~
```

### Steps to reproduce

:Telescope buffers

 

### Expected behavior

list buffers

### Actual behavior

error (please look on screenshot), because of error I'm not able to get access to vim anymore)

Here is picture reproduce from minimal.lua
![obraz_2024-06-15_184625600](https://github.com/nvim-telescope/telescope.nvim/assets/9280/aab6cbfe-2b8f-4442-ae6d-a65238ef2a02)

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      require("telescope").setup {}
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by masar3141** [comment]
Spent a lot of time on this problem too. On Macos, Nvim 0.11

**Comment by jamestrew** [comment]
ahh sorry guys, silly error on my part :facepalm: 
Should be fixed now.

**Comment by masar3141** [comment]
Working here, thanks!
