### ISSUE TITLE
[feature request] Add configurable devicon padding

### ISSUE THREAD

**Issue by 0x0003** [nvim-telescope/telescope.nvim#3174]
**Is your feature request related to a problem? Please describe.**
With narrow fonts (e.g. Iosevka), devicons are located too close to the text, in some cases so close they blend with the letters.

**Describe the solution you'd like**
A configurable padding/separator option would be nice, either an integer to set the number of spaces, or just a straight up string of characters.

**Describe alternatives you've considered**
I did find a function that pads icons with one space in [utils.lua](https://github.com/nvim-telescope/telescope.nvim/blob/c392f1b78eaaf870ca584bd698e78076ed301b26/lua/telescope/utils.lua#L615), but while altering it to print 2+ spaces does provide the desired effect in some pickers (e.g. `builtin.find_files`), others (e.g. `builtin.buffers`) are not affected for whatever reason, and I couldn't figure out why.

**Additional context**
![iosevka_example](https://github.com/nvim-telescope/telescope.nvim/assets/110566889/b42d36d6-2d4b-4829-87d1-6513fc6be1f0)

**Comment by jamestrew** [comment]
This would be such a tedious option to implement for such a niche font preference issue. I can't see us implementing this, at least in the near future.
It'd probably be easier to set up override icons for [nvim-web-devicons](https://github.com/nvim-tree/nvim-web-devicons?tab=readme-ov-file#setup) with extra whitespace appended. Might be possible to do this programmatically.
