### ISSUE TITLE
Previewer not working on Neovim + MacOS + zsh

### ISSUE THREAD

**Issue by martini97** [nvim-telescope/telescope.nvim#318]
### Description
I just installed telescop.nvim, it's awesome and blazing fast, congrats! However I could not get the previewer to work. It just show a message:
```
zsh:1: number expected
[Process exited 1]
```

**Expected Behavior**
Show file preview

**Actual Behavior**
ZSH error

### Details

<details><summary>Reproduce</summary>

I installed it via [packer.nvim](https://github.com/wbthomason/packer.nvim) as described in your README.md, and added the same mappings you describe [here](https://github.com/nvim-telescope/telescope.nvim#usage). [This is my config](https://gitlab.com/martini97/dot-nvim/-/commit/8a8edb2b3945d5a0ccb20b1003fc1bf8a176adc1)

1. nvim -nu test.vim
2. `<leader>ff`
3. I get this error:
![Screen Shot 2020-12-09 at 17 20 23](https://user-images.githubusercontent.com/18130319/101683385-a62b2f80-3a43-11eb-8680-d72150f36e93.png)
</details>

<details><summary>Environment</summary>

- nvim --version
```
NVIM v0.5.0-dev+916-gee5ece084
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1607318522887.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
- Operating system
```
Darwin <redacted>-MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
```
- Telescope commit: c276db0
- Bat version: bat 0.15.4
- ZSH version: zsh 5.8 (x86_64-apple-darwin19.3.0)

</details>

<details><summary>Configuration</summary>
<p>
 

```viml
if &compatible
  set nocompatible
endif

if empty(glob('~/.config/nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

call plug#begin(stdpath('data') . '/plugged')
  Plug 'nvim-lua/popup.nvim'
  Plug 'nvim-lua/plenary.nvim'
  Plug 'nvim-telescope/telescope.nvim'
call plug#end()

nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>
```

**Comment by Conni2461** [comment]
Oh. Did you just installed it. I did a big change today inside `previewers.lua` and might messed something up.

I need some debug info to figure out whats going on because i can't reproduce it. I am also not on a mac.
I want this fixed but just a hint you can also use vim buffers rather then bat, since today. 😆 

Could you apply this and give me the output?
```diff
diff --git a/lua/telescope/previewers.lua b/lua/telescope/previewers.lua
index a2877e0..1e4cc7a 100644
--- a/lua/telescope/previewers.lua
+++ b/lua/telescope/previewers.lua
@@ -468,6 +468,7 @@ previewers.new_termopen_previewer = function(opts)
     end

     with_preview_window(status, bufnr, function()
+      print(get_cmd(status))
       set_term_id(self, vim.fn.termopen(get_cmd(status), term_opts))
     end)
```

**Comment by martini97** [comment]
@Conni2461 this is what is printed:
```
GIT_PAGER= bat --theme Solarized (light) --style=plain --color=always --paging=always -- '/Users/<redacted>/.config/nvim/lua/modules/providers.lua'
```

**Comment by martini97** [comment]
@Conni2461 the issue seems to be that you are not escaping the theme name, if you would like I can try to make a PR fixing it

**Comment by Conni2461** [comment]
Yeah feel free. Thanks for discovering this.
