### ISSUE TITLE
Results are hidden off-screen

### ISSUE THREAD

**Issue by carbolymer** [nvim-telescope/telescope.nvim#3180]
### Description

When using `builtin.find_files` picker, the results are shown off window, but they are still accessible

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
Run "nvim -V1 -v" for more info
```

### Operating system and version

Archlinux

### Telescope version / branch / rev

0.1.x

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 10.1.0

===== Installed extensions ===== ~

Telescope Extension: `dap` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `ht` ~
- No healthcheck provided

Telescope Extension: `luasnip` ~
- No healthcheck provided

Telescope Extension: `zoxide` ~
- No healthcheck provided
```

### Steps to reproduce

1. open find_files picker
2. start typing a file name

### Expected behavior

The list of matching files is shown in the picker

### Actual behavior

The list is hidden off-screen. You can  **sometimes** get to the hidden entries using CTRL-P / CTRL-N. See the attached image:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/228866/7ce790a3-f02a-4aab-b4a1-bb3ef2a30873)
Please note there are 12/257 matches, which are not shown in the window.

### Minimal config

```Lua
local t = require 'telescope'
  local builtin = require 'telescope.builtin'
  t.setup {
    defaults = {
      winblend = 20,
    },
    extensions = {
      fzf = {
        fuzzy = true, -- false will only do exact matching
        override_generic_sorter = true, -- override the generic sorter
        override_file_sorter = true, -- override the file sorter
        case_mode = "smart_case", -- or "ignore_case" or "respect_case"
        -- the default case_mode is "smart_case"
      }
    }
  }
```

**Comment by jamestrew** [comment]
When was the last time you updated telescope? You might just need to update.

**Comment by DamienSynthesis** [comment]
I was having this same issue, turns out I had pinned the version to 0.1.2. 
Updating to latest fixed it.
