### ISSUE TITLE
Picker results invisible or scrolled off screen

### ISSUE THREAD

**Issue by dyllandry** [nvim-telescope/telescope.nvim#3185]
### Description

If I do `:Telescope` I'll see all the pickers available, like find_files, keymaps, diagnostics, etc. But if I type out "find_files" then the list becomes empty while the preview window shows the correct thing. If I press "enter" it correctly selects find_files despite it not showing in the picker. Seems the picker result is invisible but the preview is correct.

If type just "find" I'll only see "current_buffer_fuzzy_find" despite the preview screen showing the "find_files" result. If I press Ctrl-N I see "current_buffer_fuzzy_find" get selected and show in the preview window, and if I press Ctrl-N again I see find_files appear in the picker list and in the preview window. Seems here that the "find_files" picker result was scrolled off screen.

![render1719329951078](https://github.com/nvim-telescope/telescope.nvim/assets/8714251/758e2d47-28c0-4668-8afd-f40a8d8f7975)

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
```

### Operating system and version

13.6.7 (22G720)

### Telescope version / branch / rev

master 0.1.2

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins
- OK plenary installed.
- WARNING nvim-treesitter not found.

Checking external dependencies
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions =====
```

### Steps to reproduce

1. :Telescope
2. Type "find_files"

### Actual behavior

Files didn't appear in picker.

### Minimal config

```Lua
--------------------------------------------------------------------------------
-- Install lazy.nvim plugin manager --------------------------------------------
--------------------------------------------------------------------------------

-- If lazy is not in user's data directory, git clone it.
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
-- Add lazy to runtimepath
vim.opt.rtp:prepend(lazypath)

--------------------------------------------------------------------------------
-- Plugins ---------------------------------------------------------------------
--------------------------------------------------------------------------------

-- Setup vim plugins using lazy
require("lazy").setup({
    -- Fuzzy file finder over any lists. Made of pickers, sorters, and
    -- previewers, it can be used to find files, language server results, and
    -- more.
    {
        'nvim-telescope/telescope.nvim',
        tag = '0.1.2',
        dependencies = { 'nvim-lua/plenary.nvim' },
        config = function()
            require('telescope').setup{}
        end
    },

})
```

**Comment by jamestrew** [comment]
See https://github.com/nvim-telescope/telescope.nvim/issues/3178
