### ISSUE TITLE
filename_first does not seem to be working for me.

### ISSUE THREAD

**Issue by leet0rz** [nvim-telescope/telescope.nvim#3199]
### Description

As far as I can see the filename_first changes were accepted but it does not seem to be working for me.

### Neovim version

```markdown
NVIM v0.11.0-dev-293+g26c2a56d9
Build type: RelWithDebInfo
LuaJIT 2.1.1716656478
Run "nvim -V1 -v" for more info
```

### Operating system and version

Windows 21H2 19044.3086

### Telescope version / branch / rev

Telescope 0.1.8

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0 (rev e50df40a19)
- OK fd: found fd 10.1.0

===== Installed extensions ===== ~
```

### Steps to reproduce

Install with lazy plugin manager.
Add the following telescope settings inside lazy's table:
```lua
    {
        'nvim-telescope/telescope.nvim',
        tag = '0.1.8',
        dependencies = { 'nvim-lua/plenary.nvim' },
        config = function()
            require("telescope").setup {
                defaults = {
                    path_display = {
                        filename_first = {
                            reverse_directories = false,
                        }
                    },
                    sorting_strategy = "ascending",
                    layout_strategy = "horizontal",
                    layout_config = {
                        horizontal = {
                            prompt_position = "top",
                        }
                    },
                },
            }
        end
    },
    { 'nvim-telescope/telescope-fzf-native.nvim', build = 'make' },
```

### Expected behavior

For filename to occur first and path after like in the thread.

### Actual behavior

Showing a mix of filenames and entire paths plus filenames at the end.

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    {
        'nvim-telescope/telescope.nvim',
        tag = '0.1.8',
        dependencies = { 'nvim-lua/plenary.nvim' },
        config = function()
            require("telescope").setup {
                defaults = {
                    path_display = {
                        filename_first = {
                            reverse_directories = false,
                        }
                    },
                    sorting_strategy = "ascending",
                    layout_strategy = "horizontal",
                    layout_config = {
                        horizontal = {
                            prompt_position = "top",
                        }
                    },
                },
            }
        end
    },
    { 'nvim-telescope/telescope-fzf-native.nvim', build = 'make' },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by kareem-abdul** [comment]
The issue seems to be in the version 0.1.8.
I tested this on the latest master branch and it works.

**Comment by leet0rz** [comment]
@kareem-abdul Thanks for the idea, however for me a lot of other telescope functions brick. Maybe I just need to wait a little bit for them to release another one.

**Comment by jamestrew** [comment]
We're using semver so we don't be releasing a new feature as part of 0.1.x.
You'll have to switch to the master branch if you really want to use `filename_first`.  We'll try to release 0.2.0 in the coming weeks which should include it but it will be very similar to just using the master branch.

**Comment by leet0rz** [comment]
> We're using semver so we don't be releasing a new feature as part of 0.1.x. You'll have to switch to the master branch if you really want to use `filename_first`. We'll try to release 0.2.0 in the coming weeks which should include it but it will be very similar to just using the master branch.

Thanks for getting back to me, just to make sure I am doing it right it would be done by doing: ` branch = "master"` above the `config = function()` call right?

**Comment by jamestrew** [comment]
There are several ways to do it. You should just be able to omit the `branch` option but `branch='master'` should work as well.

**Comment by leet0rz** [comment]
So I managed to get master working but it still looks like this:

https://i.imgur.com/PxHw2it.png

**Comment by jamestrew** [comment]
Yeah we're tracking several issues related to paths in Windows. https://github.com/nvim-telescope/telescope.nvim/issues?q=is%3Aissue+is%3Aopen+label%3Awindows
None of the maintainers use Windows so it's been painful addressing these issues. Hoping to address them long term.

**Comment by leet0rz** [comment]
> Yeah we're tracking several issues related to paths in Windows. https://github.com/nvim-telescope/telescope.nvim/issues?q=is%3Aissue+is%3Aopen+label%3Awindows None of the maintainers use Windows so it's been painful addressing these issues. Hoping to address them long term.

To me it looks like it is pulling parts of the path instead of separating it and being able to get the file and then putting the path at the end there. If that is all it should not be too hard to fix with \\ and / being the difference.
