### ISSUE TITLE
The initial position of the cursor isn't as expected.

### ISSUE THREAD

**Issue by NGPONG** [nvim-telescope/telescope.nvim#3203]
### Description

My prompt_prefix is set to `  >  `, with a space at both the beginning and end. In insert mode, some code in the plugin ensures that the cursor never crosses the boundary, always keeping it right after `  >  `.

![PixPin_2024-07-12_12-57-47](https://github.com/user-attachments/assets/f5f14e70-4f52-48d2-83e6-e514ef6b21ba)

This is a neat feature; however, when opening telescope with `initial_mode = 'normal'`, the cursor position doesn't match this behavior. It only returns to the expected behavior after entering insert mode again.

![image](https://github.com/user-attachments/assets/7ed0b1f9-1d4e-433d-bf54-d4bf998d0eef)

I've modified this part of the code. I'm not sure if there are any side effects, but it works fine now. If you're interested, I can submit a PR.

https://github.com/nvim-telescope/telescope.nvim/blob/bfcc7d5c6f12209139f175e6123a7b7de6d9c18a/lua/telescope/pickers.lua#L604

```diff
  if vim.tbl_contains({ "insert", "normal" }, self.initial_mode) then
    local mode = vim.fn.mode()
    local keys
    if self.initial_mode == "normal" then
      -- n: A<ESC> makes sure cursor is at always at end of prompt w/o default_text
-     keys = mode ~= "n" and "<ESC>A<ESC>" or "A<ESC>"
+     keys = mode ~= "n" and "<ESC>i<ESC>g$" or "i<ESC>g$"
    else
      -- always fully retrigger insert mode: required for going from one picker to next
      keys = mode ~= "n" and "<ESC>A" or "A"
    end
    a.nvim_feedkeys(a.nvim_replace_termcodes(keys, true, false, true), "ni", true)
  else
    utils.notify("pickers.find", {
      msg = "`initial_mode` should be one of ['normal', 'insert'] but passed " .. self.initial_mode,
      level = "ERROR",
    })
  end
```

![image](https://github.com/user-attachments/assets/0ef72a81-229b-4ac7-a8bd-1e7539b30966)

Anyway, thanks again for the community's hard work. Best wishes!

### Neovim version

```markdown
NVIM v0.11.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

### Operating system and version

ubuntu 22.04

### Telescope version / branch / rev

lastest

### checkhealth telescope

```markdown
telescope: 

- ERROR No healthcheck found for "telescope" plugin.
```

### Steps to reproduce

see above

### Expected behavior

see above

### Actual behavior

see above

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      require("telescope").setup {}
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
Isn't this the expected behavior for normal mode?
Like if you just input ` > ` (space, >, space) into a buffer, do `A` then followed by `<esc>`, you would get the same result.
![image](https://github.com/user-attachments/assets/9557cf46-ff81-46bc-8749-355be409ba5f)
![image](https://github.com/user-attachments/assets/39f3bb76-d53f-4924-8537-ad0e016a476b)

This bit of code you'd referenced has also been an area of much trouble with lots of unexpected consequences so I'm sorry but I don't think we'll be implementing for suggested change.
