### ISSUE TITLE
Only display filename on long paths

### ISSUE THREAD

**Issue by svartkanin** [nvim-telescope/telescope.nvim#3204]
**Is your feature request related to a problem? Please describe.**
I have the follow following keybinding 
```
map('n', 'gr', require('telescope.builtin').lsp_references, { desc = 'Goto References' })
```
do display the references. Problem is, on long paths the displayed filepath gets cut off 

![image](https://github.com/user-attachments/assets/d3597c0c-6a9f-4e16-b168-b5860b4fae3c)

**Describe the solution you'd like**
Option to display only filenames without the path, and then potentially display the full path as a header on top of the preview?

**Comment by ryanthedev** [comment]
I believe this should help but hasn't been released yet
https://github.com/nvim-telescope/telescope.nvim/issues/2014

In the meantime I have been using 
![image](https://github.com/user-attachments/assets/42b608a5-77f8-4469-9c64-2288dfcc4e09)


But still isn't perfect :(

**Comment by jamestrew** [comment]
The entry maker for quite a number of the pickers including LSP References were changed in the master branch to no longer use fixed width for filenames in this PR https://github.com/nvim-telescope/telescope.nvim/pull/2842

There's also a `fname_width` option you can pass to these pickers (default is 30) if you want to stay on which ever release you're currently on.

We're planning to do a telescope 0.2 release in the coming weeks but it will be quite similar to the existing master branch. You can pin your telescope version to that PR's commit just to be safe as well (4367e05c).

**Comment by kvqn** [comment]
> There's also a `fname_width` option you can pass to these pickers (default is 30) if you want to stay on which ever release you're currently on.

Thanks. This works perfectly!

![Image](https://github.com/user-attachments/assets/ae0bb052-ccfa-4123-bff4-ef93f57f20f7)
