### ISSUE TITLE
feat: git commits/log preview lacks commit message

### ISSUE THREAD

**Issue by tmillr** [nvim-telescope/telescope.nvim#3206]
**Is your feature request related to a problem? Please describe.**

When I list commits, I can only see the commit title/subject. Nowhere is the commit message displayed (e.g. in the preview).

**Describe the solution you'd like**

Make the preview like what `git show` outputs, so that I can read the full commit message.

**Describe alternatives you've considered**

Config or passing custom arguments. I haven't actually tried this as it appears that only the git cmd for the list/entries can be customized (as opposed to the cmd that generates the preview)?

**Additional context**

Commit messages are typically limited in length but are vital in summarizing what a commit does and/or why. They should be included in the preview similar to `git show [rev]`.

**Comment by jamestrew** [comment]
It's not documented nor easily accessible and I almost forgot about this but the `git_commits` picker actually has several previewers defined for it.

https://github.com/nvim-telescope/telescope.nvim/blob/bfcc7d5c6f12209139f175e6123a7b7de6d9c18a/lua/telescope/builtin/__git.lua#L76-L81

You can cycle through these previewers if you map actions to do so (not done by default) or set the default picker to the `git show` one in your settings.

```lua
local actions = require("telescope.actions")

require("telescope").setup({
  defaults = {
    -- .. defaults
  },
  pickers = {
    git_commits = {
      -- `git show` equivalent
      previewer = require("telescope.previewers").git_commit_diff_as_was.new({}),
      mappings = {
        i = {
          ["<C-h>"] = actions.cycle_previewers_next,
          ["<C-l>"] = actions.cycle_previewers_prev,
        },
      },
    },
  },
})
```

Hope that helps.

**Comment by tmillr** [comment]
Oh FWIW, after skimming the source it does seem that there's one small caveat to doing it this way (if I'm not mistaken), and that is that the previewer opts need to be specified early-on (when/where `git_commit_diff_as_was.new(opts)` is called), and as a result opts from any other sources will no longer be dynamically piped-thru to the previewer.

**Comment by jamestrew** [comment]
Yeah if I get some time, I'll try to repackage those previewers in an more accessible manner, document them and such.
