### ISSUE TITLE
Support for multiple projects

### ISSUE THREAD

**Issue by kkrime** [nvim-telescope/telescope.nvim#3208]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when;

I'm working on multiple projects and I use telescope to navigate to anothe file, but when I do so, it's searching from the root of the wrong project

(I also use `project.nvim`)

**Describe the solution you'd like**

I'm not sure what the best solution would be, but either way, there needs to be tighter project integration in telescope; as in telescope needs to be more `project aware`.

The solution could be to just run telescope searches for all currently opened projects, or you select which project you want to target with your search. 

This is up for debate and I'm open to suggestions on what others think is the best approach.

I'm happy to put in some work to make this happen, with the help of the telescope team to point me in the right direction :)

**Comment by jamestrew** [comment]
I fundamentally don't agree with the idea the telescope should be aware of multiple projects.
I'm of the opinion that there should only be one neovim instance per project. This keeps things like git integration, LSP integration, etc much simpler.

You don't have to subscribe to this opinion but at that point, project management within neovim becomes such a workflow specific thing, I wouldn't know how to accommodate it in a manner that would make most people happy even if I wanted to. And I don't even know of anyone who effectively works if multiple projects in a single neovim instance at the same time. Maybe using tabs and `tcd` is the closet thing.
If you wanted to search for files between multiple projects, how do I determine what constitutes a project? If it means doing something similar to project.nvim and searching your home directory for things like `.git`, you might as well just put all your projects into a `projects/` directory and open neovim there. Not that I think that's a good idea.

As consolation, I'll mention that `live_grep`, `grep_string` and `find_files` all support an option `search_dirs`, you can pass it directories you want to search in.
You can also pass a `cwd` option to dictate where the search begins from.
