### ISSUE TITLE
don't show the folder that you are in if you do nvim/path/to/different folder

### ISSUE THREAD

**Issue by killertofus** [nvim-telescope/telescope.nvim#3210]
### Description

if you type neovim /path/to/folder it shows the search for the folder you are in instead the folder you nvimed to

### Neovim version

```markdown
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1720049189
```

### Operating system and version

arch

### Telescope version / branch / rev

0.1.x

### checkhealth telescope

```markdown
==============================================================================
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- WARNING nvim-treesitter not found.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions ===== ~
```

### Steps to reproduce

mkdir foo
cd foo
touch test2.txt
mkidir bar
cd bar
touch test.txt
cd -
nviim bar/test.txt

### Expected behavior

don't show the contents of test2.txt or anyother one besides the one you are in

### Actual behavior

it shows foo2 for a search when you want only foo to be searched

### Minimal config
my config https://github.com/killertofus/awesome/blob/main/.config/nvim/init.vim
```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      require("telescope").setup {}
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
Telescope just goes off of the current `cwd` of neovim.
Starting nvim is some subdirectory doesn't set that cwd of nvim to that subdirectory.

ie. `nvim path/to/folder` and then doing `:echo getcwd()` will still just the pwd of the shell from which you started nvim from.

you have to cd to that directory, either in your shell, or in nvim with `:cd` or do `nvim -c "cd path/to/folder"`. You can optionally pass `cwd` as an option to telescope `:Telescope find_files cwd=path/to/folder`.

**Comment by killertofus** [comment]
@jamestrew what about just listing what's in the current file not in the other ones next to it?

**Comment by jamestrew** [comment]
If you have a file open, you can do `:Telescope find_files cwd=%:p:h` (see `:h expand` if you're not familiar with the `%:p:h` syntax).

If you just opened nvim to some folder, this won't help since I don't think you can get the current path from opening a folder. At least I'm not aware of one off the top of my head.
