### ISSUE TITLE
Allow configuring a callback when live_grep finishes - to call vim.notify etc

### ISSUE THREAD

**Issue by Ajaymamtora** [nvim-telescope/telescope.nvim#3216]
**Is your feature request related to a problem? Please describe.**
Allow configuring a callback when live_grep finishes - to call vim.notify etc

**Describe the solution you'd like**
provide a callback property in pickers.live_grep.callback etc

**Describe alternatives you've considered**
-

**Additional context**
When running a live grep on a big project, id like to know when its finished, because there's no indication that the grep is still running.

**Comment by jamestrew** [comment]
There's an `on_complete` option you can pass to any picker. It's currently undocumented but it has takes a list of function that takes a picker as an argument. ie. `on_complete: (fun(picker: table): nil)[]`.
The functions will get called once all results are processed.

I don't think it's necessary for what you want. The pickers already come with a status text.

https://github.com/user-attachments/assets/22ec0211-3fcd-438f-873b-477532177844

See on the right of the prompt, the asterisks shows up while the search is still happening and numbers counting up.

Hope that helps.
