### ISSUE TITLE
Set a theme globally

### ISSUE THREAD

**Issue by orhnk** [nvim-telescope/telescope.nvim#3220]
**Is your feature request related to a problem? Please describe.**
I want to use the theme `ivy`, not by writing everywhere I use telescope `require "telescope.themes".get_ivy()` but want to have that theme set globally in the config.

**Describe the solution you'd like**
```lua
  opts = {
    extensions = {
      ["*"] = {
        theme = "ivy",
      },
    },
  },
```

**Comment by vedant-pandey** [comment]
I can take up this task if no one is currently working on it

**Comment by jamestrew** [comment]
There's a number of related/duplicate issues.
https://github.com/nvim-telescope/telescope.nvim/issues/938
https://github.com/nvim-telescope/telescope.nvim/issues/848

This is a workaround 
https://github.com/nvim-telescope/telescope.nvim/issues/938#issuecomment-877539724

I'm open to a PR but I'll close this issue as a duplicate.
