### ISSUE TITLE
Look through config folder

### ISSUE THREAD

**Issue by tungstengmd** [nvim-telescope/telescope.nvim#3232]
**Is your feature request related to a problem? Please describe.**
On my config, I have a button in the start screen that opens the vimrc. However, that just says ```require("config.lazy")``` so nothing useful.

**Describe the solution you'd like**
I just want a function that lets you look through the config.

**Describe alternatives you've considered**
Using Lazyvim but I have my own config though

**Additional context**
N/A

**Comment by jamestrew** [comment]
> On my config, I have a button in the start screen that opens the vimrc. However, that just says require("config.lazy") so nothing useful.

Sorry but I don't know what you're referring to. What button? What's the "that" in "that just says". Seems like a config issue.

> I just want a function that lets you look through the config.

Again, don't know what exactly you mean by "the config" or "look through" even. If you have to search for files in your neovim config you can do something like `:Telescope find_files cwd=~/.config/nvim`

**Comment by tungstengmd** [comment]
the "that" is init.lua, and the config is the nvim config. cwd=~./config/nvim doesnt work on windows so uhh

**Comment by jamestrew** [comment]
Just point to the windows equivalent path for the nvim config directory then. I don't know what that is off the top of my head but I'm sure you can figure that out 👍

**Comment by jamestrew** [comment]
You guys are sharing configs?

You can use `:h stdpath` to dynamically find your config path.

**Comment by tungstengmd** [comment]
idk how to make it work with telescope ;-;

**Comment by tungstengmd** [comment]
figured it out
lua require('telescope.builtin').find_files({cwd=vim.fn.stdpath('config')})
