### ISSUE TITLE
live grep with dynamic filetype filter

### ISSUE THREAD

**Issue by w-tr** [nvim-telescope/telescope.nvim#3239]
I'm running telescope through kickstart neovim.

I might be missing a trick here, but i have seen that i can hardcode the setup such that when i use the key bindings " sg" it will open live_grep, and the call will use handles like --hidden and --glob.

However the problem is... I want to change the glob each time i'm in telescope live_grep.

The solution would be to have something like vscode search, where you have files to include/exclude.

Therefore imagine the following keystrokes.

" sg" (opens telescope live grep)
"distance" (Finds all files with distance in)
"<Tab>" (Move to files to include section) {overwrite builtin.git_status}
".py"

I'm raising this here because I can't believe such a feature doesn't exist. I hope i can be directed to it. Like I said before I've seen examples where the --glob is hardcoded.

**Comment by jamestrew** [comment]
Check out https://github.com/nvim-telescope/telescope-live-grep-args.nvim

There's also https://github.com/MagicDuck/grug-far.nvim for something closer to the vs code search and replace interface
