### ISSUE TITLE
automatic git versioning of lazy-lock.json on update/restore

### ISSUE THREAD

**Issue by Tal500** [nvim-telescope/telescope.nvim#3241]
**Is your feature request related to a problem? Please describe.**
According to [the docs](https://lazy.folke.io/usage/lockfile), it is suggested to put the `lazy-lock.json` file under version control manually. But it doesn't come out of the box!

**Describe the solution you'd like**
Have an automatic (git by default) versioning of the file `lazy-lock.json`, can be by a shortcut(windows)/symlink(the rest OS`s) to a tracking dir.
This way whenever the user update the plugins, Lazy.nvim will create a commit for that automatically by default.
If it's done out of the box automatically, it can be very helpful to users, and also users will always (by default) could report to nvim plugins github project the last version that they were using before they had a bug.

**Describe alternatives you've considered**
Define the tracking dir and the symlink manually, and connect somehow to Lazy.nvim hooks on update (if any). If there will be no hook, the user could easily forget to commit, or even not to notice.

**Comment by jamestrew** [comment]
I'm confused. What does this have to do with telescope.

Lazy's `lazy-lock.json` file is intended for end user use. It doesn't make sense for telescope itself to use this file, telescope doesn't use lazy.

**Comment by Tal500** [comment]
> 

> I'm confused. What does this have to do with telescope.
> 
> Lazy's `lazy-lock.json` file is intended for end user use. It doesn't make sense for telescope itself to use this file, telescope doesn't use lazy.

Oy sorry, didn't notice the github project I had in my web browser tab 😬
