### ISSUE TITLE
Add a `no_git_ignore` option to find_files options

### ISSUE THREAD

**Issue by j-krl** [nvim-telescope/telescope.nvim#3249]
**Is your feature request related to a problem? Please describe.**
Telescope ignores many files that I want to have in find_files because of the .gitignore, which I don't have control over. However I do want to ignore a subset of those files.

**Describe the solution you'd like**
I think there should be a `no_git_ignore` option in the find_files builtin where it will ignore only .ignore files, but _not_ .gitignore files. This way I can define my own .ignore that is unrelated to git, as I often want to search for files ignored by git, but still want to ignore a subset of them.

**Describe alternatives you've considered**
I don't want to do `no_ignore=true` and then put the subset in my `file_ignore_patterns` because these paths are very specific to the workspace. I don't want them in my global nvim config.

**Comment by jamestrew** [comment]
You can do `require('telescope.builtin').find_files({ find_command = { "fd", "--type", "f", "--color", "never", "--no-ignore-vcs" }})` assuming you use `fd`.

With the `find_command` option, you can pass it any arbitrary command for telescope to use (as long as it outputs a list of files with no color codes).

**Comment by j-krl** [comment]
@jamestrew Exactly what I was looking for. Thank you!
