### ISSUE TITLE
Layout guide in readme.md incorrect

### ISSUE THREAD

**Issue by SafetyMary** [nvim-telescope/telescope.nvim#3255]
### Description

I followed the instructions below 
https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#layout-display
trying to switch to a vertical layout. The lua command line works fine but coping the config stated in the guide does not work.
I then followed the solution in this reddit post and it works
https://www.reddit.com/r/neovim/comments/r22xrq/in_nvimtelescope_how_can_i_make_the_display_a/
I think the guide is missing the following line
layout_strategy = "vertical",

### Neovim version

```markdown
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
```

### Operating system and version

Ubuntu 24.04

### Telescope version / branch / rev

"branch": "0.1.x", "commit": "a0bbec21143c7bc5f8bb02e0005fa0b982edc026"

### checkhealth telescope

```markdown
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `ui-select` ~
- No healthcheck provided
```

### Steps to reproduce

copy and paste the config snipet in 
https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#layout-display

### Expected behavior

Telescope will change to a vertical layout

### Actual behavior

Telescope remains a horizontial layout

### Minimal config

```Lua
require('telescope').setup {
        -- You can put your default mappings / updates / etc. in here
        --  All the info you're looking for is in `:help telescope.setup()`
        --
        -- defaults = {
        --   mappings = {
        --     i = { ['<c-enter>'] = 'to_fuzzy_refine' },
        --   },
        -- },

        -- set vertical file preview
        defaults = {
          layout_config = {
            vertical = { width = 0.8 },
          },
        },

        -- pickers = {}
        extensions = {
          ['ui-select'] = {
            require('telescope.themes').get_dropdown(),
          },
        },
      }
```

**Comment by jamestrew** [comment]
I think this
```lua
require('telescope').setup({
  defaults = {
    layout_config = {
      vertical = { width = 0.5 }
      -- other layout configuration here
    },
    -- other defaults configuration here
  },
  -- other configuration values here
})
```
is configuration for the width of the vertical layout *WHEN* you use `layout_strategy = 'vertical'` as in `:Telescope find_files layout_strategy=vertical` or `require("telescope.builtin").find_files({ layout_strategy = "vertical" })`.

As stated:
> If we wanted to change the width for every time we use the vertical layout strategy, we could add the following to our setup() call:

It's not showing you show to default telescope to always use `layout_strategy = 'vertical'`.

I hope that's clear now.

**Comment by SafetyMary** [comment]
Its clear to me now. Thanks for the explaination.
