### ISSUE TITLE
Memory leak when using builtin.find_files

### ISSUE THREAD

**Issue by ronandalton** [nvim-telescope/telescope.nvim#3264]
### Description

When using find_files, memory which is used by the picker is not released to the operating system once the picker is closed. Subsequent uses of find_files compound the amount of memory that is used.

### Neovim version

```markdown
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
```

### Operating system and version

Linux 6.9.3

### Telescope version / branch / rev

master (5972437)

### checkhealth telescope

```markdown
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- WARNING nvim-treesitter not found. (Required for `:Telescope treesitter`.)

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 10.1.0

===== Installed extensions ===== ~
```

### Steps to reproduce

1. Be in a directory with a large number of files (eg. Linux kernel source or home directory)
2. `nvim -nu minimal.lua`
3. `:Telescope find_files`
4. `<Esc>`
5. `:Telescope find_files`
6. ...
7. Watch as memory usage increases

### Expected behavior

Memory used by find_files should be released back to the operating system when it is no longer needed. Subsequent calls to find_files should especially not increase memory usage. Memory should especially be released after using another picker such as oldfiles since `:Telescope resume` no longer needs to keep the find_files picker in memory.

### Actual behavior

More and more memory is used by Neovim.

Starting Neovim in a directory containing the Linux kernel source code and repeatedly issuing `:Telescope find_files` gives the resulting memory usage:

```
4.6 MB (Initial)
55.6 MB (After executing first find_files)
86.9 MB (After executing second find_files, and so on...)
126.3 MB
170.7 MB
172.9 MB
182.4 MB
182.4 MB
182.4 MB
183.5 MB
```

Browsing the results uses even more memory (+160 MB) which doesn't get freed either. I am able to get it up to 784 MB by repeatedly reopening the picker, searching for different things and scrolling the results.

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      require("telescope").setup {}
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
I can kind of reproduce this but I'm knowledgeable enough in this area to figure out what's happening.

This is htop with only one instance of neovim open.
![image](https://github.com/user-attachments/assets/18bf99a8-6ad7-40d0-8ad2-73c166f3e306)

I don't know why there's so many processes and what these `--embed` processes are.

I can also only reproduce this in the linux kernel repo. Any smaller repositories, I can't reproduce this.

All I know is that it's probably not related to
- telescope's global state related to `:Telescope resume` functionality since I can nil out the global variable and the memory is still held
- not related to previewer, happens without it

Seems to only be an issue with picker that subprocess ripgrep (live_grep, grep_string, find_files by default with ripgrep installed)? Changing `find_files` to use `fd` instead seems to prevent or at least help with the issue.

**Comment by ronandalton** [comment]
Thanks for looking into this. I tried setting the find command to use `fd` instead of `rg` but that didn't seem to make much of a difference. I can't really think of a reason why it would make any difference to Neovim's memory usage since it's an external process that outputs essentially the same thing.

There is the lua command `collectgarbage` which manually triggers a garbage collection and can report how much memory is in use by Lua. Here is the output from running a measurement:
```
[~7 calls to find_files with using fd followed by call to oldfiles in linux directory]
[current memory: 203.3 MB]
collectgarbage("count") -- gives 90999 (90 MB) in use by lua
collectgarbage("collect")
collectgarbage("count") -- gives 33517 (33 MB) in use by lua (57 MB drop)
[current memory: 198.3 MB (5 MB drop overall)]
```

I also tried with a much smaller project (950 files) and observed similar memory leaking behavior.

I also tested just creating some lua code that allocates a really large array of numbers and Neovim seems to free that memory just fine once.

EDIT: I tried assigning it to a global variable and persisting it for a bit longer and that seems to have changed things.

```
:lua local nums = {} for i = 1, 100000000 do nums[i]=i end vim.g.foo = j
(WARNING: uses 5 GB of memory!)
-- wait 30 seconds or so
:lua vim.g.foo = nil
```
Initially the `collectgarbage("count")` showed around 1 GB of memory usage and didn't go down. After something like 5-10 minutes I checked again and it was then under a megabyte. The process memory usage only dropped from 5 GB to 4.8 GB. Doing a `collectgarbage("collect")` had no observable effect.

I'm thinking this may be an issue with Neovim and how it embeds Lua, based on these findings. I'm also not entirely sure if this is perhaps expected to happen (even though it seems undesirable). I believe some programs keep memory pools so that future allocations can happen faster.

**Comment by ronandalton** [comment]
Since there's not much I think Telescope can do about this other than offloading the memory heavy indexing to an external process like fzf-lua does, I think I'll close this. The memory leak issue is something that should be fixed in Neovim.

**Comment by ronandalton** [comment]
For reference, I've raised an issue in the Neovim repository regarding this problem: https://github.com/neovim/neovim/issues/30283

**Comment by jamestrew** [comment]
Thanks for digging deeper!
