### ISSUE TITLE
LSP incoming/outgoing calls triggers error when selecting from multiple symbols at cursor

### ISSUE THREAD

**Issue by Diomendius** [nvim-telescope/telescope.nvim#3267]
### Description

See neovim/neovim#30122. Telescope inherits this bug from Nvim.

`require("telescope.builtin").lsp_incoming_calls()` and `require("telescope.builtin").lsp_outgoing_calls()` trigger an error when the cursor position resolves to more than one symbol, immediately after the user selects one of the listed options.

https://github.com/nvim-telescope/telescope.nvim/blob/5972437de807c3bc101565175da66a1aa4f8707a/lua/telescope/builtin/__lsp.lua#L64-L68

`return choice` should be replaced with `return call_hierarchy_items[choice]`.

### Neovim version

```markdown
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
```

### Operating system and version

Arch Linux up-to-date as of 2024-08-18

### Telescope version / branch / rev

5972437de807c3bc101565175da66a1aa4f8707a

### checkhealth telescope

```markdown
Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions ===== ~

Telescope Extension: `fzy_native` ~
- No healthcheck provided
```

### Steps to reproduce

See neovim/neovim#30122, but use `require("telescope.builtin").lsp_incoming_calls()` instead of `vim.lsp.buf.incoming_calls()`.

Use `vim.lsp.start { name = 'bugged-ls', cmd = { 'rust-analyzer' }, root_dir = '.' }` to attach `rust-analyzer`.

### Actual behavior

```
Error handling LSP Incoming Calls: Failed to deserialize callHierarchy/incomingCalls: invalid type: integer `1`, expected struct CallHierarchyItem; {"item":1}
```

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      require("telescope").setup {}
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
Thanks for the report!

**Comment by reybits** [comment]
Have the same error:

`Error handling LSP Incoming Calls: Method not found: callHierarchy/incomingCalls`

As far as I know, this problem occurs when `copilot.vim` or `copilot.lua` is attached to the current buffer.

### My config

```
macOS
15.6.1 (24G90)
```

```
NVIM v0.11.3
Build type: Release
LuaJIT 2.1.1753364724
```

```
copilot.lua
commit f0c0d98
```

```
telescope.nvim
tag 0.1.8
```

My nvim config: https://github.com/reybits/config-nvim

**Comment by jamestrew** [comment]
the fix has not be released. it's only in the master branch of telescope. 
telescope has not had a release in over a year and is not likely to get one any time soon.

**Comment by reybits** [comment]
> it's only in the master branch of telescope.

Unfortunately, the `master` branch has the same bug.

> telescope has not had a release in over a year and is not likely to get one any time soon.

Sad to hear it. :(
