### ISSUE TITLE
Resume in normal mode

### ISSUE THREAD

**Issue by ic-768** [nvim-telescope/telescope.nvim#3269]
I have a mapping to resume my last telescope picker

```
vim.keymap.set("n", "<leader><leader>", telescope.resume, {})
```

Usually what I want to do is keep searching through the results, so I instinctively go for `j/k` to navigate them.
Of course, this resumes in insert mode, so I end up writing on top of my last search query.

I would really like a way to be able to resume in normal mode.

**Comment by jamestrew** [comment]
See `:h telescope.defaults.initial_mode`
eg.
```lua
vim.keymap.set("n", "<leader><leader>", function()
    telescope.resume({ initial_mode = "normal" })
end, {})
```
