### ISSUE TITLE
This plugin will cause the code to jump to error: malformed object name HEAD

### ISSUE THREAD

**Issue by jicvi** [nvim-telescope/telescope.nvim#3279]
### Description

This plugin will cause the code to jump to error: malformed object name HEAD

### Neovim version

```markdown
NVIM v0.8.0-dev-751-g8952def50
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

ubuntu 

### Telescope version / branch / rev

telescope v0.1.8

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()                                                     
========================================================================    
## Checking for required plugins    
  - OK: plenary installed.    
  - OK: nvim-treesitter installed.    
    
## Checking external dependencies    
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)    
  - WARNING: fd: not found. Install sharkdp/fd for extended                                          capabilities    
    
## ===== Installed extensions =====
```

### Steps to reproduce

    Plug 'nvim-telescope/telescope.nvim'
    Plug 'neoclide/coc.nvim', {'branch': 'release'}
    Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

### Expected behavior

Exclude .git file branch error: malformed object name HEAD

### Actual behavior

![2024-09-06_17-03](https://github.com/user-attachments/assets/1b959b0c-1b34-40e4-a365-6a686ad6f872)
![2024-09-06_17-24_1](https://github.com/user-attachments/assets/d7456f7c-05ec-4ab4-82f2-5288512e1299)
![2024-09-06_17-24](https://github.com/user-attachments/assets/e4b9f2dc-74cc-44ed-96b2-3a020a57699c)
![2024-09-06_18-52](https://github.com/user-attachments/assets/89398aa7-10de-484d-949a-c90b646e4cd6)

### Minimal config

```Lua
require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_prefix = "> ",
    selection_caret = "> ",
    entry_prefix = "",
    initial_mode = "insert",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_config = {
      horizontal = {
        mirror = false,
      },
      vertical = {
        mirror = false,
      },
    },
    file_sorter =  require'telescope.sorters'.get_fuzzy_file,
    file_ignore_patterns = {"node_modules", ".git", "build", "dist", "yarn.lock"},
    generic_sorter =  require'telescope.sorters'.get_generic_fuzzy_sorter,
    winblend = 0,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
    color_devicons = true,
    use_less = true,
    path_display = {},
    set_env = { ['COLORTERM'] = 'truecolor' }, -- default = nil,
    file_previewer = require'telescope.previewers'.vim_buffer_cat.new,
    grep_previewer = require'telescope.previewers'.vim_buffer_vimgrep.new,
    qflist_previewer = require'telescope.previewers'.vim_buffer_qflist.new,

    -- Developer configurations: Not meant for general override
    buffer_previewer_maker = require'telescope.previewers'.buffer_previewer_maker
  }
}
```

**Comment by jamestrew** [comment]
Your steps to reproduce is incomplete. Those are just vimplug commands.
I don't know what you did to cause this error. What telescope operation were you doing?

**Comment by jicvi** [comment]
> Your steps to reproduce is incomplete. Those are just vimplug commands. I don't know what you did to cause this error. What telescope operation were you doing?

I upgraded neovim and it didn't show up

**Comment by jamestrew** [comment]
Alright, I'll close this.
