### ISSUE TITLE
Can not select items with some pickers.

### ISSUE THREAD

**Issue by steelsojka** [nvim-telescope/telescope.nvim#328]
### Description
Can not select items in various different pickers. The arrow chevre
on the left is missing and the bindings to move the selection don't do anything.
This works for the files picker but various others don't work.

![Screen Shot 2020-12-11 at 8 15 58 AM](https://user-images.githubusercontent.com/2062154/101913900-3f179300-3b89-11eb-9b3e-73f9b4188477.png)

**Expected Behavior**
Should be able to select items with arrow keys or other mappings

**Actual Behavior**
Rows get selected.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :Telescope marks 
</details>

<details><summary>Environment</summary>

- nvim version: NVIM v0.5.0-dev+930-g763de8dd8
- Operating system: MacOS
- Telescope commit: d5ee177306da9c977734f84ae016726778e1746f 

</details>

<details><summary>Configuration</summary>
<p>
 

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom", 
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment]
Issue with `descending`. TJ broke it here f3609abd7f9bf34ad482b1beb1c0482b76562af3.
Working on a fix right now.
This one is first attempt: https://github.com/nvim-telescope/telescope.nvim/pull/327 but `cycle` is broken if list is smaller than `max_results`

**Comment by Conni2461** [comment]
@steelsojka This pr should work now. I have to talk to @tjdevries about the impl and need to implement tests so it could take some time for it to get merged

**Comment by steelsojka** [comment]
No problem! I just set the commit prior to this commit just so I can get it up and running. I thought I would give this a try over my heavy, customized fzf setup. So far everything is going splendidly.
