### ISSUE TITLE
live_grep: sorting_strategy = "ascending": previous results persisting

### ISSUE THREAD

**Issue by alex-courtis** [nvim-telescope/telescope.nvim#3282]
### Description

Search results at the end remain after refining a search and are not selectable.

This only occurs when sorting_strategy = "ascending"

### Neovim version

```markdown
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1723675123
```

### Operating system and version

Linux 6.10.8-arch1-1

### Telescope version / branch / rev

5972437de807c3bc101565175da66a1aa4f8707a

### checkhealth telescope

```markdown
──────────────────────────────────────────────────────────────────────────────
telescope: health#telescope#check

Checking for required plugins
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies
- OK rg: found ripgrep 14.1.0
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions =====
```

### Steps to reproduce

Inside telescope codebase at 5972437de807c3bc101565175da66a1aa4f8707a

`nvim -nu minimal.lua`

`:Telescope live_grep`

First search for `l`:
Enter `l`
`<esc>`
`G`

Refine search to `lu`
`a`
`u`
`<esc>`
`G`

### Expected behavior

Previous results not present.

### Actual behavior

After first search:
![20240908_094958](https://github.com/user-attachments/assets/54b2cbc9-d00c-458c-871f-82239463e256)

After refining search:

![20240908_094757](https://github.com/user-attachments/assets/0cc55fb3-4bf0-47c8-9d3c-b4fa2bdcb38e)

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      require("telescope").setup({
        defaults = {
          path_display = {
            truncate = 1,
          },
          sorting_strategy = "ascending",
        },
      })
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
Can you try out the above linked PR?
Hard to believe this wasn't caught earlier but it looks like it's been an issue for a while.

**Comment by alex-courtis** [comment]
Works beautifully with minimal reproducer and full configuration, many thanks!

Apologies, I realise I did not put the sorting strategy in the minimal config. Updated.

**Comment by alex-courtis** [comment]
Offtopic:

We created the nvim-tree [bug report template](https://github.com/nvim-tree/nvim-tree.lua/blob/master/.github/ISSUE_TEMPLATE/nvt-min.lua) based on telescope's. It's still using EOL Packer but working nicely.

We were considering abandoning a package manager, just git cloning the two plugins directly.

I see you've used Lazy: any thoughts or advice on that choice?

/cc @gegoune

**Comment by gegoune** [comment]
I would prefer to use one Lewis is using on gitsigns. It's very minimal. I have asked him if he's ok with us copying it, he was fine with it, but never got to it.

**Comment by jamestrew** [comment]
> Apologies, I realise I did not put the sorting strategy in the minimal config. Updated.

No worries, it was trivially easy reproducing this issue.

I switched to our current template mainly due to the explosion in popularity of lazy over packer. And in my experience (nvim-tree likely experiences this as well), people typically completely disregard the minimal config and often dump their lazy config in the bug report. So using lazy as a minimal config, at least I can transfer some of that user config into the minimal config fairly easily.

Also I should mention, our current minimal config, I ripped straight from folke a while back. I believe he has an even simpler config now. https://lazy.folke.io/developers#reprolua

One I thing I like that folke's done is he's pointing stdpaths to within the reproduction path. This keeps things like logs isolated to each bug report. I can also easily point the minimal config to point to my local dev telescope path to test bugfixes with lazy's `dir` option.

**Comment by alex-courtis** [comment]
> people typically completely disregard the minimal config and often dump their lazy config in the bug report

That does indeed happen.

> One I thing I like that folke's done is he's pointing stdpaths to within the reproduction path. This keeps things like logs isolated to each bug report. I can also easily point the minimal config to point to my local dev telescope path to test bugfixes with lazy's dir option.

My dev/test harness does something similar. Cheers, sounds like it should be an easy move.

> explosion in popularity of lazy over packer

I guess I might just have to accept lazy. I really don't like it due to the somewhat unpredictably deterministic nature of its startup ordering, however the masses appear to have spoken.

**Comment by alex-courtis** [comment]
Thanks mate.
