### ISSUE TITLE
builtin current_buffer_fuzzy_find not working with worktrees

### ISSUE THREAD

**Issue by floork** [nvim-telescope/telescope.nvim#3291]
### Description

The Buffer fuzzy finder does not work when using the gitworktree plugin from "theprimeagen/git-worktree.nvim", "polarmutex/git-worktree.nvim" or even when only beeing in a worktree.

### Neovim version

```markdown
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
Run "nvim -V1 -v" for more info
```

### Operating system and version

arch linux

### Telescope version / branch / rev

telescope 0.1.x

### checkhealth telescope

```markdown
==============================================================================
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~
```

### Steps to reproduce

1. go to a worktree with the worktree plugin
2. try to use the fuzzy find
or
1. clone a repo with git clone --bare
2. cd <repo>
3. git worktree add <path> <branch>
4. cd <path>
5. vim <some-file>

### Expected behavior

Show the fuzzy find results like when not using worktrees.

### Actual behavior

It just shows a blank window
![image](https://github.com/user-attachments/assets/1615e3ab-ddb5-4ce2-88a7-2632eb26e556)

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    {
      '<leader>/',
      function()
        require("telescope.builtin").current_buffer_fuzzy_find(require('telescope.themes').get_dropdown {
          previewer = false,
        })
      end,
      desc = "[/] Fuzzily search in current buffer"
    },
    config = function()
      -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      require("telescope").setup {}

    end,
  },
  {
    "polarmutex/git-worktree.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
    },
    keys = {
      { "<leader>gw", "<cmd>Telescope git_worktree<CR>",                     desc = "Open Worktree selection" },
      { "<leader>gm", "<cmd>Telescope git_worktree create_git_worktree<CR>", desc = "Create Worktree " }
    },
    config = function()
      require('telescope').load_extension('git_worktree')
    end,
  }

}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
I'm not able to reproduce using the minimal config. The `keys` option for telescope is broken btw so I'm not sure if you've tried the minimal config yourself.


https://github.com/user-attachments/assets/d2cf8c7a-a79e-4ed9-9f12-827a95839858



There's really no reason `current_buffer_fuzzy_find` should be impacted either way by `git_worktree.nvim`.
All it does to get results is get lines in the current buffer with `nvim_buf_get_lines`

**Comment by floork** [comment]
Ok, I found the reason it did not work, it was my file_ignore_patterns...

Thanks for the help!
