### ISSUE TITLE
vim.tbl_islist is deprecated

### ISSUE THREAD

**Issue by lominoss-git** [nvim-telescope/telescope.nvim#3294]
### Description

When I launch telescope, the window appears but the borders are absent and I get this error `vim.tbl_islist is deprecated. Run ":checkhealth vim.deprecated" for more information`

### Neovim version

```markdown
NVIM v0.11.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu WSL

### Telescope version / branch / rev

telescope 0.1.5

### checkhealth telescope

```markdown
telescope: health#telescope#check

## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. Launch `telescope.find_files()`

### Expected behavior

I expect it to run properly by drawing all borders and without triggering any errors.

### Actual behavior

As mentioned above the telescope window has no borders and an error is triggered (`vim.tbl_islist is deprecated. Run ":checkhealth vim.deprecated" for more information`).

### Minimal config

```Lua
return {
    "nvim-telescope/telescope.nvim",
    tag = "0.1.5",
    dependencies = { "nvim-lua/plenary.nvim" },
    keys = {
	{
	    "<leader>f",
	    function() require("telescope.builtin").find_files() end,
	},
    },
    opts = {
        defaults = {
	    -- layout_config = { prompt_position = "top" },
	    sorting_strategy = "ascending",
            prompt_prefix = "λ ",
            borderchars = { "─", "│", "─", "│", "┌", "┐", "┘", "└" },
        },
    },
}
```

**Comment by Conni2461** [comment]
We fixed that in 0.1.7 https://github.com/nvim-telescope/telescope.nvim/releases/tag/0.1.7, and you are still running 0.1.5, maybe consider updating. 0.1.5 is a tag it will never change
