### ISSUE TITLE
`builtin.highlights` picker does not show all highlights in results list

### ISSUE THREAD

**Issue by puresick** [nvim-telescope/telescope.nvim#3296]
### Description

Opening the `builtin.highlights` picker without any search query results in an incomplete list of highlights.
On my machine there are hundreds of highlights listed (depending on the filetype). Scrolling through them they start with entries starting with `@` and most of the time end with entries around the letter `N`.

The other highlights are still available through that interface though: If I search for `QuickFixLine` for example it will result in it being shown as a result.

It is just the initial results list that is being cut off.

### Neovim version

```markdown
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1725453128
```

### Operating system and version

Linux Kernel 6.10.10-arch1-1 (Arch Linux)

### Telescope version / branch / rev

master

### checkhealth telescope

```markdown
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.1
- OK fd: found fd 10.2.0

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured
```

### Steps to reproduce

1. Open neovim
2. Execute `:Telescope highlights`
3. Press arrow down key to jump to last entry
4. Searching for an entry which is not listed, e.g. `QuickFixLine`
5. Observe it being available

### Expected behavior

All highlights are being listed in the initial results list.

### Actual behavior

Not all available highlights are being listed in the initial results list.

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      require("telescope").setup {}
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
Telescope only manages at max 250 result entries at a time to avoid having to sort potentially a huge number of results. The idea is people wouldn't really scroll through hundreds of results but rather search but it happens sometimes.

There's a private unstable option `temp__scrolling_limit` to control this. I say unstable but it's been around for over 2 years and there aren't plans to remove it anytime soon that I'm aware of. 
`:Telescope highlights temp__scrolling_limit=1000` should show you more results.

**Comment by puresick** [comment]
Ah I see, thank you for clarifying this @jamestrew. :pray:
