### ISSUE TITLE
Support normalization of the text to ignore accents 

### ISSUE THREAD

**Issue by barcell1** [nvim-telescope/telescope.nvim#3302]
basic the title. Would like to telescope do not take in consideration the accent of the words when finding, could be optional.

**Comment by jamestrew** [comment]
I think this a long been a todo item in telescope-fzf-native. https://github.com/nvim-telescope/telescope-fzf-native.nvim/pull/20

If it's to be implemented, it'll mostly likely be in downstream sorters as opposed to in telescope core. The builtin sorter is imo intended to be minimal, and frankly just to get people started with telescope, preferring other native sorters.
