### ISSUE TITLE
picker fails to load any results when options given have a tilde in the path

### ISSUE THREAD

**Issue by baroldgene** [nvim-telescope/telescope.nvim#3303]
### Description

I am attempting to use the [Obsidian.nvim](https://github.com/epwalsh/obsidian.nvim) which relies on Telescope for many of it's pickers.  While attempting to workaround the stupid limitations of Obsidian's mobile app I ran into this issue.  In order to get obsidian notes to sync to mobile using iCloud you are required to put the files into an App Library folder on iCloud.  This results in a file path that is something like `~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Notes`  

As best I can tell the Obsidian.nvim plugin passes these file paths into a Telescope picker which then crashes (without returning any errors) and displays no results in the picker.  

I'm not sure if the file paths should be escaped somehow (if so I can open a bug with the Obsidian plugin) but I would think that Telescope can/should handle this gracefully.

### Neovim version

```markdown
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
```

### Operating system and version

macOS 15

### Telescope version / branch / rev

  "telescope.nvim": { "branch": "master", "commit": "175178e3889c13a840f036d464aee2d145157b9e" }

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.1
- OK fd: found fd 10.2.0
```

### Steps to reproduce

1. Create a new telescope picker
2. Pass in a filename with a tilde in the file path
Example code in Obsidian.nvim: https://github.com/epwalsh/obsidian.nvim/blob/main/lua/obsidian/pickers/_telescope.lua#L271

### Expected behavior

Picker options are displayed

### Actual behavior

Picker is completely empty

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      require("telescope").setup {}
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
I'm not exactly sure where the issue is occurring.

Doing something like `:Telescope live_grep cwd=~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Notes` should work based on my testing and the code. Can you give that a try on your end?

My gut is that it's a obsidian.nvim issue but maybe there's something I'm not seeing.

**Comment by baroldgene** [comment]
So sorry, the title was wrong.  (Was very sleepy when trying to write this up).  

From what I can tell Obsidian is creating a new picker and feeding it a list of files.  If the filename contains a ~ then the picker completely fails to load any results.  To test this I pulled a local copy of the Obsidian plugin and manually changed [this line](https://github.com/epwalsh/obsidian.nvim/blob/main/lua/obsidian/pickers/_telescope.lua#L271) to no longer include the tilde and the picker suddenly populated with results.  

I'm not familiar enough with how Telescope's api works and how it's meant to be used to discern what should be happening there.  I'll continue poking at it though.

For context: What this picker does is show a list of "daily notes" files.  The Obsidian command takes arguments to determine how many days to go forward and back for this list.  These daily notes may or may not exist.  If they do they can be searched and opened and previewed.  if they don't that information is all blank obviously.  But when the Obsidian directory is in a path that includes a tilde then the picker shows no results.

**Comment by jamestrew** [comment]
Is it possible that the file path is already mangle at this line? https://github.com/epwalsh/obsidian.nvim/blob/main/lua/obsidian/pickers/_telescope.lua#L271

Trying this locally works as expected for me so telescope should be able to handle ~ inside or at the start of a file path.
```lua
local pickers = require("telescope.pickers")
local finders = require("telescope.finders")
local conf = require("telescope.config").values

local opts = {}

pickers
  .new(opts, {
    finder = finders.new_table({
      results = {
        "/tmp/testing/min.lua",
        "/tmp/testing/foo~bar/hello.txt",
        "/tmp/testing/foo~bar/goodbye.txt",
        "~/projects/telescope.nvim/README.md",
      },
      -- entry_maker = make_entry.gen_from_file(opts),
      entry_maker = function(entry)
        return {
          value = entry,
          ordinal = entry,
          display = entry,
          filename = entry, -- `entry` here is just the paths in the results table
        }
      end,
    }),
    sorter = conf.file_sorter(opts),
    previewer = conf.grep_previewer(opts),
  })
  :find()
```

**Comment by baroldgene** [comment]
So digging in a bit more it turns out this is fine and was a really odd bug in my config.  

Essentially I had tried to set an ignore for the `.obsidian` directory.  I didn't catch that this was a regex and not just a string so the `.` character was matching the `~` character which was then ignoring all files that had obsidian anywhere in the path.  Since the folder now matched that it essentially would just auto-ignore any files that were passed to it.  

Can close this ticket.  Sorry for the spam.

**Comment by zharmany** [comment]
@baroldgene -- Thanks for posting your solution! I had the same issue with `.git/` being in my `file_ignore_patterns` instead of `\\.git/` and was trying to make sense of what was going wrong by looking through the `obsidian.nvim` codebase.
