### ISSUE TITLE
can't open dir/(dir)/file.ext on windows with Telescope find_files

### ISSUE THREAD

**Issue by seccentral** [nvim-telescope/telescope.nvim#3306]
### Description

On a default lazyvim install, opening a nextjs project with a bunch of route groups that structure files inside dirs within brackets - Round  brackets - in the form of ./src/app/(myroutegroup)/layout.tsx fails with error 
` ENOENT: no such file or directory: [...]\src\app(app)`
Opening the same file on linux works just fine, must be a different way it handles paths and escaping. 

### Neovim version

```markdown
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

### Operating system and version

Windows 11 23H2

### Telescope version / branch / rev

cb3f98d

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.1 (rev 4649aa9700)
- OK fd: found fd 10.2.0

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured
```

### Steps to reproduce

just try opening a file in a path like dir/(dir)/file.txt

### Expected behavior

The file should open

### Actual behavior

Error: file not found probably because the path is not properly escaped 

### Minimal config

```Lua
- not needed -
```

**Comment by jamestrew** [comment]
See this issue. https://github.com/nvim-telescope/telescope.nvim/issues/2446
There is a workaround: https://github.com/nvim-telescope/telescope.nvim/issues/2446#issuecomment-1875123859

There is also something of a fix in the works but it relies on some upstream plenary changes.
https://github.com/nvim-telescope/telescope.nvim/pull/3275

I'll close this issue as its a duplicate.
