### ISSUE TITLE
Toggle hiding in telescope file finder.

### ISSUE THREAD

**Issue by waplet** [nvim-telescope/telescope.nvim#3307]
**Is your feature request related to a problem? Please describe.**
When i use `:Telescope file_browser`, there is a feature with `<C-h>` to toggle hidden files.

**Describe the solution you'd like**
But there is no such feature for `Telescope` builting `find_files`. You can either opt in for `hidden = true` or no other way.
Can there be implemented support for `<C-h>` to toggle hidden files inside `find_files` functionality?

**Describe alternatives you've considered**
Practically alternative would be using FIle browser only, as there you can go in parent folders., etc.. But it would be nice to have this toggle in find files too.

**Additional context**
File browser
<img width="1543" alt="image" src="https://github.com/user-attachments/assets/92a6425b-0edf-4e1b-92cb-10f984a8c82f">

Find file
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/2258ed01-89ca-41e1-b89a-2471cf4b0f16">

**Comment by jamestrew** [comment]
See https://github.com/nvim-telescope/telescope.nvim/issues/2874#issuecomment-1900967890
