### ISSUE TITLE
Add option to return to Insert mode after closing

### ISSUE THREAD

**Issue by DUOLabs333** [nvim-telescope/telescope.nvim#3317]
**Is your feature request related to a problem? Please describe.**
Currently, if you call `require('telescope.actions').close` without selecting a buffer, the buffer you go back to is invariable put in "Normal" mode, regardless of the mode it was in when you called `:Telescope`.

**Describe the solution you'd like**
Either a setup option like `insert_on_close`, or to be more general, an extra parameter like `require('telescope.actions').close(bufnr, mode)` --- `mode` is the mode that telescope should put the buffer in.

**Describe alternatives you've considered**

**Additional context**

**Comment by DUOLabs333** [comment]
I got this to work with
```lua
["<esc>"] = function(prompt_bufnr)
      require('telescope.actions').close(prompt_bufnr)
      	vim.cmd([[normal! i]])
	end
```

I'm not sure if there's a cleaner approach I should use instead.

**Comment by jamestrew** [comment]
Yeah that's pretty much the way to do it.
One tweak I would probably recommend is to schedule the `vim.cmd`. It's been observed that there's some scheduling funkiness that leads to the cursor moving https://github.com/nvim-telescope/telescope.nvim/issues/2319
```lua
["<esc>"] = function(prompt_bufnr)
  require("telescope.actions").close(prompt_bufnr)
  vim.schedule(function()
    vim.cmd [[normal! i]]
  end)
end,
```

**Comment by DUOLabs333** [comment]
Actually, if I wrap the vim.cmd in a `schedule`, this no longer works (ie, the buffer is opened in `normal` mode).
