### ISSUE TITLE
builtin.git_files calls on the directory in which neovim was initiated instead of current directory

### ISSUE THREAD

**Issue by oblassov** [nvim-telescope/telescope.nvim#3320]
### Description

When calling builtin.git_files the call is made not on the current file or directory, but on the file or directory which was initially opened via neovim. That results in error if the initial folder or file is not a part of git repo. I think changing the behavior to include current directory or file location as default value of {cwd} option is better user experience.

### Neovim version

```markdown
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
```

### Operating system and version

Windows 11

### Telescope version / branch / rev

telescope 0.1.8

### checkhealth telescope

```markdown
==============================================================================
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.1 (rev 4649aa9700)
- OK fd: found fd 10.2.0

===== Installed extensions ===== ~
```

### Steps to reproduce

1. nvim . //from a directory outside of a repo
2. navigate into repo in neovim
3. open any file or directory
4. call builtin.git_files

### Expected behavior

It would be nice for it to recognize the current location and return files if it is inside a repo

```
vim.keymap.set("n", "<C-p>", function()
	local path = vim.fn.expand("%:p:h")
	local is_git = os.execute("git -C " .. path .. " rev-parse --is-inside-work-tree") == 0
                                                                                            
	if is_git then
		builtin.git_files({ cwd = path }, { use_git_root = true })
	else
		builtin.find_files()
	end
end)

```
This is the code I came up as a workaround and expected behavior.

### Actual behavior

It returns error, as it checks the directory or location where neovim was initialized i.e. ":pwd"

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      -- I am not sure it is necessary, works with basic config
      require("telescope").setup {}
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment]
We try not to be too clever and opinionated about using non-cwd paths for cwd of commands/pickers.

Same goes for doing things like opening a different picker than the one initially called (opening `find_files` when `git_files` was called).

We likely won't change this philosophy any time soon. But we encourage people to tweak their telescope/neovim config to suite their needs and try to offer mechanisms to help with this.

There's a config recipes point about what you're trying to accomplish you might find helpful.
https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#falling-back-to-find_files-if-git_files-cant-find-a-git-directory

**Comment by oblassov** [comment]
@jamestrew Thanks for reply, and appreciate all the effort put into developing telescope! :clap:
