### ISSUE TITLE
Nightly: buggy utils.has_ts_parser() prevents treesitter highlighting in preview window

### ISSUE THREAD

**Issue by pappasam** [nvim-telescope/telescope.nvim#3332]
### Description

Treesitter is never used for file Previews on Neovim nightly. This is due to (what appears to be) buggy behavior with `utils.has_ts_parser`, which is called by `previewers.utils.ts_highlighter`. `utils.has_ts_parser` returns the result of `vim.treesitter.language.add`, which doesn't have a return value. Because of this, its result will never be truthy, and `previewers.utils.ts_highlighter` will never use treesitter for preview windows.

```help
add({lang}, {opts})                            *vim.treesitter.language.add()*
    Load parser with name {lang}

    Parsers are searched in the `parser` runtime directory, or the provided
    {path}

    Parameters: ~
      • {lang}  (`string`) Name of the parser (alphanumerical and `_` only)
      • {opts}  (`table?`) Options:
                • {filetype}? (`string|string[]`, default: {lang}) Default
                  filetype the parser should be associated with.
                • {path}? (`string`) Optional path the parser is located at
                • {symbol_name}? (`string`) Internal symbol name for the
                  language to load
```

For now, I've just disabled treesitter for Telescope. That said, this should be fixable by modifying the logic in these functions:

- https://github.com/nvim-telescope/telescope.nvim/blob/df534c3042572fb958586facd02841e10186707c/lua/telescope/utils.lua#L664
- https://github.com/nvim-telescope/telescope.nvim/blob/df534c3042572fb958586facd02841e10186707c/lua/telescope/previewers/utils.lua#L170

### Neovim version

```markdown
NVIM v0.11.0-dev-667+gd9ccd828b
Build type: RelWithDebInfo
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more info
```

### Operating system and version

Ubuntu 24.04.1 LTS

### Telescope version / branch / rev

df534c3

### checkhealth telescope

```markdown
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.1 (rev 4649aa9700)
- OK fd: found fd 10.2.0

===== Installed extensions ===== ~
```

### Steps to reproduce

1. Activate with `Telescope find_files`
2. Notice how preview window is not highlighting with treesitter, despite treesitter parsers being installed

### Expected behavior

Treesitter used in preview window

### Actual behavior

Treesitter appears to be loaded, but its highlights are never applied to the preview window

### Minimal config

```Lua
require("telescope").setup({})
```

**Comment by jamestrew** [comment]
@pappasam you have to update neovim. you're on a old commit. if you want to use nightly neovim, you should stay moderately up to date and telescope expects as such.

@dgmora I think you're having the reverse issue -- neovim is "up to date" but you're stuck on an older telescope commit.
This was fixed several weeks ago. https://github.com/nvim-telescope/telescope.nvim/pull/3308
Duplicate issue: https://github.com/nvim-telescope/telescope.nvim/pull/3313

**Comment by dgmora** [comment]
Doesn't look like that, this is what lazy shows:
```
    ● telescope.nvim 64.3ms  Telescope
        dir    /Users/david/.local/share/nvim/lazy/telescope.nvim
        url    https://github.com/nvim-telescope/telescope.nvim
        branch master
        commit df534c3
```
I'm also using `telescope-fzf-native`:
```
    ● telescope-fzf-native.nvim 7.76ms  telescope.nvim
        dir    /Users/david/.local/share/nvim/lazy/telescope-fzf-native.nvim
        url    https://github.com/nvim-telescope/telescope-fzf-native.nvim
        branch main
        commit cf48d4d
        readme README.md
```

**Comment by jamestrew** [comment]
@dgmora I think you just might have to update neovim as well. Can you try that?

**Comment by dgmora** [comment]
That was it, thanks a lot!
