### ISSUE TITLE
git_status picker, place cursor on first hunk

### ISSUE THREAD

**Issue by Tronikelis** [nvim-telescope/telescope.nvim#3341]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a tiny annoyance, when I open the `git_status` picker and select an entry, it opens the file with the cursor at the top, and I always need to find the closest hunk 

**Describe the solution you'd like**
A new config option in telescope git_status picker, e.g. `move_cursor` which would move the cursor to the first hunk

**Describe alternatives you've considered**
I could make this logic myself without telescope by checking if a new opened file has hunks and jump to them, but this is bad because now everytime it would jump, even when I don't want to, when with telescope picker I always want to jump

**Additional context**
I am willing to open a PR for this

Although a bit of searching around, git does not support a standard way of showing line number in `git status`, I guess this could be an extra plugin and not a native option

**Comment by xzbdmw** [comment]
you can bind cr in status picker to polling gitsigns's hunk information until it return something, then jump to next hunk.

**Comment by Tronikelis** [comment]
> you can bind cr in status picker to polling gitsigns's hunk information until it return something, then jump to next hunk.

thats a great idea, closing this issue

**Comment by hoxbro** [comment]
Would it be possible to share your solution @tronikelis?

**Comment by xzbdmw** [comment]
You can use some defer_fn on attach, at some point get_hunks will return information, only then you can jump.

**Comment by tronikelis** [comment]
Yeah I tried with defer_fn and it works, but I just really dislike this solution as it is unstable and pc dependent.

I have a PR for a new config https://github.com/lewis6991/gitsigns.nvim/pull/1146 hope it gets accepted

**Comment by tronikelis** [comment]
The PR was closed without comment, so I assume the author does not think this should be in the gitsigns plugin, which I understand.

So my current solution is this @hoxbro 

```lua
git_status = {
    mappings = {
        i = {
            ["<cr>"] = function(prompt_bufnr)
                local JUMPED_TO_HUNK = "_jumped_to_hunk"

                actions.select_default(prompt_bufnr)

                local buf = vim.api.nvim_get_current_buf()
                if vim.b[buf][JUMPED_TO_HUNK] then
                    return
                end

                vim.system(
                    { "git", "diff", "-U0", "HEAD", vim.fn.expand("%:p") },
                    {},
                    vim.schedule_wrap(function(out)
                        if out.code ~= 0 or not out.stdout then
                            return
                        end
                        if vim.api.nvim_get_current_buf() ~= buf then
                            return
                        end

                        local line = out.stdout:match("@@.++(%d+)")
                        line = tonumber(line)

                        vim.b[buf][JUMPED_TO_HUNK] = true
                        vim.api.nvim_win_set_cursor(0, { line, 0 })
                    end)
                )
            end,
        },
    },
},
```

**Comment by tronikelis** [comment]
as was mentioned here https://github.com/lewis6991/gitsigns.nvim/issues/1147#issuecomment-2481024440 `GitSignsUpdate` works as well

**Comment by xzbdmw** [comment]
I'm updating with these
```lua
            local goto_next_hunk_cr = function(prompt_bufnr)
                actions.select_default(prompt_bufnr)
                local ok = false
                local fn = function()
                    if ok then
                        return
                    end
                    local hunks = require("gitsigns").get_hunks(api.nvim_get_current_buf())
                    if hunks ~= nil and #hunks > 0 then
                        ok = true
                        require("gitsigns").nav_hunk("first", { navigation_message = false })
                    end
                end
                fn()
                local id
                id = api.nvim_create_autocmd("User", {
                    pattern = "GitSignsUpdate",
                    callback = function()
                        if ok then
                            api.nvim_del_autocmd(id)
                        end
                        fn()
                    end,
                })
            end

```

**Comment by g0t4** [comment]
@tronikelis was your goal to jump to the selected hunk from the git_status picker? Or just to jump to first hunk regardless of what you picked in the picker?

IIAC you want to jump to the selected hunk? But I might assume wrong!

**Comment by tronikelis** [comment]
> [@tronikelis](https://github.com/tronikelis) was your goal to jump to the selected hunk from the git_status picker? Or just to jump to first hunk regardless of what you picked in the picker?
> 
> IIAC you want to jump to the selected hunk? But I might assume wrong!

It's hard to recall, but I think I wanted to jump to the first hunk when you select an entry in the git_status picker, but this was 2 years ago and I'm not using telescope now
