### ISSUE TITLE
live grep but only for open buffers instead of cwd

### ISSUE THREAD

**Issue by meetmangukiya** [nvim-telescope/telescope.nvim#3347]
**Is your feature request related to a problem? Please describe.**
It could be useful sometimes

**Describe the solution you'd like**
Being able to live grep but limit the files to only open buffers

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by AyaanAhmed25** [comment]
the option for this already exists.
look [here](https://github.com/nvim-telescope/telescope.nvim/blob/60660334c70d9d81dccc10a563e01920b9455e76/lua/telescope/builtin/files.lua#L42) for more details
example:
`vim.keymap.set('n', '<leader>sb', "<cmd>lua require('telescope.builtin').live_grep({grep_open_files=true})<cr>")`

**Comment by meetmangukiya** [comment]
looks like you are right, thanks
