### ISSUE TITLE
cycle_history functions appear broken

### ISSUE THREAD

**Issue by thisisrandy** [nvim-telescope/telescope.nvim#3348]
### Description

The functionality described in `:h telescope.defaults.history` appears broken in a minimal install. 

### Neovim version

```markdown
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
```

### Operating system and version

Ubuntu 22.04.5

### Telescope version / branch / rev

telescope 0.1.8 / master

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- WARNING nvim-treesitter not found. 

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.3.1

===== Installed extensions ===== ~
```

### Steps to reproduce

1. Create a minimal config as below. Note the addition of the `cycle_history_...` mappings.
2. Run `nvim -u minimal.vim`
3. `:Telescope`
4. `<C-Down>` or `<C-Up>`

### Expected behavior

Picker history is cycled through.

### Actual behavior

```
E5108: Error executing lua: ...im/plugged/telescope.nvim/lua/telescope/actions/init.lua:1016: attempt to index local 'current_picker' (a nil value)                                                                                           
stack traceback:                                                                                                       
        ...im/plugged/telescope.nvim/lua/telescope/actions/init.lua:1016: in function 'run_replace_or_original'        
        ...nvim/plugged/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'cycle_history_prev'               
        [string ":lua"]:2: in function <[string ":lua"]:2>   
```

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      require("telescope").setup {}
    end,
    keys = {
      i = {
	["<C-Down>"] = require("telescope.actions").cycle_history_next,
	["<C-Up>"] = require("telescope.actions").cycle_history_prev,
      },
    }
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by thisisrandy** [comment]
This was user error. I was failing to provide `prompt_bufnr`. This is a bit confusing in the docs, which reference plain functions in the mapping examples, e.g. `["<C-Down>"] = require('telescope.actions').cycle_history_next`. What I actually needed to do, apparently, is something like `["<C-Down>"] = require('telescope.actions').cycle_history_next(vim.fn["bufnr"]("%"))`.

Functionality-wise, this bug is closed, but I maintain that the docs are not at all clear, so perhaps there's room for improvement. Is there a preferred way to do this (I imagine my `vim.fn...` solution is not it), and can the docs be clarified to use that preferred way? This comes up in probably many other contexts, e.g. the "Mapping `<esc>` to quit in insert mode" [recipe](https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#mapping-esc-to-quit-in-insert-mode), which is why I realized out I wasn't experiencing an error specific to `cycle_history`. Is there guidance on producing `prompt_bufnr` somewhere that I'm missing?

**Comment by KriBielinski** [comment]
Hey,
I don't know how you came up with that configuration, but the proper way to do those bindings (which was also described in the docs) is like this:
```
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      require("telescope").setup({
        defaults = {
          mappings = {
            i = {
	      ["<C-Down>"] = require("telescope.actions").cycle_history_next,
	      ["<C-Up>"] = require("telescope.actions").cycle_history_prev,
            },
          }
        },
      })
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by thisisrandy** [comment]
Thanks for your response, @KriBielinski. I recently switched to [LazyVim](https://www.lazyvim.org/), which specifies that plugin key maps be [specified under the key `keys`](https://www.lazyvim.org/configuration/plugins#%EF%B8%8F-adding--disabling-plugin-keymaps). Evidently telescope is doing some additional processing of mappings specified under `defaults/mappings` that doesn't happen when mappings are specified under `keys`.

I do see now that this is mentioned fairly prominently in the [README](https://github.com/nvim-telescope/telescope.nvim/tree/master#telescope-setup-structure), so no need for additional documentation. Thanks again.
