### ISSUE TITLE
How do i get this 'welcome screen' to appear?

### ISSUE THREAD

**Issue by hrqmonteiro** [nvim-telescope/telescope.nvim#336]
![2020-12-14_09-25](https://user-images.githubusercontent.com/17055027/102081082-628f4780-3dee-11eb-87ae-6b053890fb7c.png)

This is in the Gif on the readme but i couldn't find it nowhere on how do i access this..

**Comment by Conni2461** [comment]
[Plugin](https://github.com/glepnir/dashboard-nvim) by @glepnir

**Comment by hrqmonteiro** [comment]
> [Plugin](https://github.com/glepnir/dashboard-nvim) by @glepnir

Thanks, man!
