### ISSUE TITLE
git_files and find_files don't allow spaces anymore

### ISSUE THREAD

**Issue by Laurensdc** [nvim-telescope/telescope.nvim#3364]
### Description

- For a directory structure of `/saving-action/nested/folder/error.ts` I used to find that file by searching `saving-action error`
- Now, adding a space between my words no longer fuzzy finds for a match with both of those words

https://github.com/user-attachments/assets/b0f9189d-9c55-4bb1-95dd-4f181427bf0b

### Neovim version

```shell
❯ nvim --version
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info
```

### Operating system and version

macOS 14.7

### Telescope version / branch / rev

0.1.8

### checkhealth telescope

```shell
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.1
- OK fd: found fd 10.2.0

===== Installed extensions ===== ~

Telescope Extension: `gitmoji` ~
- No healthcheck provided
```

### Steps to reproduce

- Open either picker: `git_files` or `find_files`
- Search for a term with 2 words: `some_directory [space] the_filename`
- There are no matches

### Expected behavior

- It fuzzy finds and matches the entries containing both of the words I entered

### Actual behavior

- It shows no entries

### Minimal config

I don't believe my config changed when this started happening. 
If necessary I can try and add this, let me know.

**Comment by Laurensdc** [comment]
I had a secondary machine where I introduced this bug through doing a `:Lazy` update.

These are the packages and versions that were bumped, introducing the bug:
https://github.com/Laurensdc/dotfiles/commit/941105605899ca33a64a6dd4ee85a2f488a5f76f

**Comment by ArnauLlamas** [comment]
Hey @Laurensdc 

I had the same issue and turns out that during a refactor of my config I accidentally deleted the loading of the fzf extension call, you should add `require("telescope").load_extension("fzf)` somewhere after the Telescope plugin setup; more details on how to load it correctly [here](https://github.com/nvim-telescope/telescope-fzf-native.nvim?tab=readme-ov-file#telescope-setup-and-configuration).

Just for your info, I think that this "issue" is actually the default behavior of the plugin and the white space behavior works only after loading the fzf native extension correctly.

**Comment by Laurensdc** [comment]
Wow, exactly, the `require("telescope").load_extension("fzf")` was missing from my config.
Thank you so much!

**Comment by theherk** [comment]
What the hell? I guess I'm crazy. I could have sworn that was working before, but yeah this was the solution.

I added

```lua
  {
    "nvim-telescope/telescope-fzf-native.nvim",
    build = "make",
    dependencies = { "nvim-telescope/telescope.nvim" },
  },
```

and

```lua
    config = function(_, opts)
      require("telescope").setup(opts)
      require("telescope").load_extension("fzf")
    end,
```

**Comment by Laurensdc** [comment]
I'll add my solution as well: https://github.com/Laurensdc/dotfiles/commit/263f879e63bc1715c765e5a2667930c37f5ea145
