### ISSUE TITLE
Only current buffer is listed.

### ISSUE THREAD

**Issue by OliverWarrington** [nvim-telescope/telescope.nvim#338]
### Description
Telescope is not listing all the currently open buffers using the builtin buffer picker.

**Expected Behavior**
A list of all currently open buffers like the fzf Buffers command.

**Actual Behavior**
Only the current buffer is listed. Or only the currently visible buffers (a split results in both buffers being listed).

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. Open some buffers (not in splits) 
3. :Telescope buffers
4. Only current buffer is listed

<details><summary>Environment</summary>

- nvim version: NVIM v0.5.0-dev+4383c0f
- Operating system: macos Big Sur
- Telescope commit: Not sure but I installed and updated with Paq today

</details>

**Comment by Conni2461** [comment]
Duplication of https://github.com/nvim-telescope/telescope.nvim/issues/97.
You have to do: `lua require'telescope.builtin'.buffers{ show_all_buffers = true }` or
 `Telescope buffers show_all_buffers=true`
Discussion why it currently defaults to false is at the other issue.

**Comment by OliverWarrington** [comment]
Ah thank you very much @Conni2461, missed that extra option! Working now.
