### ISSUE TITLE
Adjustable debounce time for input

### ISSUE THREAD

**Issue by steelsojka** [nvim-telescope/telescope.nvim#343]
### Description
When using live grep, inputing text becomes unbearably slow in medium to large codebases. Is there a way to debounce the input to only search once I've stopped typing for N milliseconds?

**Expected Behavior**
Should be able to type my query without lag

**Actual Behavior**
Typing the first character causes the UI to freeze until the results for a single letter come back.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. Live grep
3. Start typing
</details>

<details><summary>Environment</summary>

- nvim version:
- Operating system: 
- Telescope commit: 

</details>

<details><summary>Configuration</summary>
<p>
 

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom", 
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by rockerBOO** [comment]
Currently no debouncing as the goal is to get it as fast as possible without debouncing tricks. The bigger plan is to async searching so it wont block input. 

Maybe someone can suggest a quick and dirty way to debounce it for now.

**Comment by steelsojka** [comment]
What is the road map for moving the searching async and are there any road blockers for it?

**Comment by rockerBOO** [comment]
These are the main issues:

https://github.com/nvim-telescope/telescope.nvim/issues/269
https://github.com/nvim-telescope/telescope.nvim/pull/192

Currently want to use libuv to do the full async but there have been some hangups in getting it all working well.

- commands block input while running (ripgrep running)
- we dont have a cancel option for commands
- ideally we do the commands on a co-routine so we can continue to take input on the main thread.
- How do we send data between the main thread and the co-routine efficiently 

Pull to get performance tested so we can isolate whats going on.
https://github.com/nvim-lua/plenary.nvim/pull/17

**Comment by Conni2461** [comment]
@steelsojka The best thing we can offer you right now would be to check out https://github.com/nvim-telescope/telescope-fzf-writer.nvim. You can set the `minimum_grep_characters` which should help at least a little bit :)

**Comment by tjdevries** [comment]
if you know how to get threads to work well within neovim, that would be a significat step in the right direction :)

**Comment by fdschmidt93** [comment]
Solved from angle that grep is now much more async and debouncing is implement, see this example [here](https://github.com/nvim-telescope/telescope.nvim/pull/987#issuecomment-885762691).
