### ISSUE TITLE
List renamable items

### ISSUE THREAD

**Issue by ChrisAmelia** [nvim-telescope/telescope.nvim#363]
The idea is to list every renamable item that is recognized as such by the LSP, something like `builtin.lsp_rename`.

**Comment by clason** [comment]
Isn't that exactly what `builtin.lsp_document_symbols` (for the current document only) and ` builtin.lsp_workspace_symbols` (for the whole project) are for?

**Comment by Conni2461** [comment]
I think clason is right here, this should be sufficient. Closing for now
