### ISSUE TITLE
Buffers within a session not properly listed

### ISSUE THREAD

**Issue by mrdgo** [nvim-telescope/telescope.nvim#368]
### Description
When I open a saved session and call `:Telescope buffers` I don't see all buffers.

**Expected Behavior**
I would expect to see all the buffers I see with `:ls`.

**Actual Behavior**
I actually see an incomplete list of only the buffers, that are active in a window.

### Details

<details><summary>Reproduce</summary>

0. Place `test.vim` in your current dir from down below. (It is the default one)
1. `mkdir test; cd test; touch file1 file2 file3`
2. `nvim -nu test.vim file1`
3. `:e file2`
4. `:e file3`
5. `:mks test_sess`
6. `:q`
7. `nvim -nu test.vim -S test_sess`
8. `:ls` (shows all three files)
9. `:Telescope buffers` (only shows file3)
</details>

<details><summary>Environment</summary>

- nvim version: v0.5.0-dev+916-gee5ece084
- Operating system: Artix Linux (Arch based)
- Telescope commit: 3e884e8

</details>

<details><summary>Configuration</summary>
<p>
Reproducible with default `test.vim` from the template.

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment]
Dup of #338 and #97

**Comment by mrdgo** [comment]
Thanks for your quick response, I just didn't search through closed issues.

In my opinion that option should be default behaviour, as @ruifm pointed out.

**Comment by akinsho** [comment]
Just to note that I also just hit this today and definitely think (biased obviously 😄 ) that it should be the default, tbh I didn't read all of the context on why it isn't so might be missing something

**Comment by R0LA1mRifcF8yAkk** [comment]
Just chiming in here. Was about to open an issue until I found this one on the 3rd page. I had screenshots ready and all. Would really save on the confusion if this was the default.

**Comment by R0LA1mRifcF8yAkk** [comment]
> Edit: Maybe we need to talk again about changing the default :/
> Edit 2: Just for reference `lua require'telescope.builtin'.buffers{ show_all_buffers = true }` or `Telescope buffers show_all_buffers=true`

@Conni2461 Could you please point me in the right direction? Disclaimer: I have never writter lua before.

I have tried this in every which way and can't figure out where am I supposed to put this. I have my telescope config in a subfolder: `~/.config/nvim/lua/plugins/telescope.lua`. I tried just including this line in the file, didn't work right – all it did, was open an empty file picker automatically whenever I opened neovim.

I also tried this custom method and bound it to a keymap, `sort_lastused` and `ignore_current_buffer` work but it still doesn't show every buffer that I have open in the background.

```lua
local builtin = require('telescope.builtin')
local sorters = require('telescope.sorters')

...

local M = {}
M.all_buffers = function()
  builtin.buffers({
    sort_lastused = true,
    ignore_current_buffer = true,
    sorter = sorters.get_substr_matcher(),
  })
end

return M
```
