### ISSUE TITLE
Telescope.nvim previewer doesn't seem to work with Powershell

### ISSUE THREAD

**Issue by ndavidpsi** [nvim-telescope/telescope.nvim#381]
The default cmd for Windows is not very powerful. Often a better alternative is using Powershell.
I recently switched nvim's shell to pwsh by putting the following in my init.vim (it's the recommended in nvim's docs, see `:h shell-powershell`):
```
		let &shell = has('win32') ? 'powershell' : 'pwsh'
		set shellquote= shellpipe=\| shellxquote=
		set shellcmdflag=-NoLogo\ -NoProfile\ -ExecutionPolicy\ RemoteSigned\ -Command
		set shellredir=\|\ Out-File\ -Encoding\ UTF8
```
Unfortunately, telescope.nvim's previewer doesn't seem to be working properly (whereas with cmd it does).
This is the output of `:lua require('telescope.builtin').find_files()` without and with powershell as the default nvim shell, respectively:
![a](https://user-images.githubusercontent.com/73792104/103486192-ed62d100-4df3-11eb-8753-9987f8beed16.PNG)
![b](https://user-images.githubusercontent.com/73792104/103486196-f358b200-4df3-11eb-8f01-f64c638ec7d2.PNG)

**Comment by Conni2461** [comment]
I know whats the problem. I'll be at my PC in 15 min and can send you a PR that fixes that problem

**Comment by ndavidpsi** [comment]
wow thanks, I'll be waiting

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/382

**Comment by ndavidpsi** [comment]
Is it a matter of time until it's merged then?

**Comment by Conni2461** [comment]
Its a matter of you telling me it works :) I am allowed to merge to that repo.
Do you know how to checkout a PR or do you need help?

**Comment by ndavidpsi** [comment]
oh 🤣 . Yeah I probably need help I have only done basic stuff in git/github so far

**Comment by ndavidpsi** [comment]
Oh a Pull Request... I'll try it now haha

**Comment by Conni2461** [comment]
- `git fetch origin pull/382/head:pr-382`
- `git checkout pr-382`
- Test it
- `git checkout master`

**Comment by ndavidpsi** [comment]
![1](https://user-images.githubusercontent.com/73792104/103486940-6c0e3d00-4df9-11eb-8369-d9f6bdb1cf94.PNG)
Works flawless! 💯
