### ISSUE TITLE
Move from `telescope/path` to `plenary/path`

### ISSUE THREAD

**Issue by Conni2461** [nvim-telescope/telescope.nvim#387]
I think everything from `telescope.path` can already be found in `plenary.path` so we should use that module instead and remove `telescope.path`

**Comment by tjdevries** [comment]
Yes, this is a good idea. At the time, `plenary.path` used `vim.fn`, which made it not available during certain times of telescope operaiton.

Should be OK now to use anywhere, since I switched impl in plenary.path.

**Comment by anott03** [comment]
I'm trying to take this on... I see that in `telescope.path` there is `path.separator`. I don't see an equivalent in `plenary.path`. Can separator be moved somewhere else? Maybe to config?

**Comment by tjdevries** [comment]
We can add it to plenary.path if it's not available there currently.

**Comment by anott03** [comment]
I searched through plenary.path and didn't find anything related to separator. I'll just switch everything else for now and leave path.lua there until plenary is updated.

**Comment by anott03** [comment]
The other thing I don't see in plenary.path is an equivalent to `read_file_async`. Should I open issues on plenary for missing functions?

**Comment by Conni2461** [comment]
There is `require'plenary.path'.path.sep` as separator equivalent.

I would suggest you working on both at the same time. Like trying to replace something with plenary.path and when its missing there copy it over. So we end up with one PR per project.

There are also a lot of things used all over the place. E.g. we have `a .. sep .. b` everywhere and plenary.path has a join or you can do `Path:new({a, b})` i think.
Or we have some `vim.loop.fs_stat` in the previewers to check if its a dir. We can replace it with `plenary.path` as well.

**Comment by anott03** [comment]
@Conni2461 Thanks!

**Comment by anott03** [comment]
As far as I can tell, I've gotten this working. The one thing I noticed: there are extensions that require `telescope.path` (the instance I came across was frecency). Should I leave path.lua in the project for now, or delete it and leave it up to extensions to move away from it?

**Comment by Conni2461** [comment]
I kinda wanna remove the file. If its only frecency we could ask sunjon to update it the second we merge the PR. 
Maybe we just get rid of all content and have only the signatures left which will error on calling. Similar to what tj decided to do with `goto_file_selection`

**Comment by anott03** [comment]
Will do

**Comment by anott03** [comment]
I am consistently getting the following error when I run tests. Does anyone know what it means? I'm struggling to make anything out of it.
```
Testing: 	@/home/an/dev/nvim/telescope.nvim/lua/tests/automated/pickers/scrolling_spec.lua	
Fail	||	scrolling strategies should handle cycling for full list	
            Vim:E474: Expected null: nvim: ../src/nvim/message.c:2266: msg_scroll_flush: Assertion `to_scroll >= 0' failed.
            
            stack traceback:
            	.../dev/nvim/telescope.nvim/lua/telescope/pickers/_test.lua:163: in function 'get_results_from_file'
            	.../dev/nvim/telescope.nvim/lua/telescope/pickers/_test.lua:217: in function 'run_file'
            	...cope.nvim/lua/tests/automated/pickers/scrolling_spec.lua:7: in function <...cope.nvim/lua/tests/automated/pickers/scrolling_spec.lua:6>
```

**Comment by Conni2461** [comment]
Is the plenary version you are working on based on the current master?
I think i fixed a bug in plenary.scandir that caused that error.
