### ISSUE TITLE
Grep is unusably slow

### ISSUE THREAD

**Issue by lynndylanhurley** [nvim-telescope/telescope.nvim#392]
### Description

Grep hangs for 10+ seconds when used in a large codebase.

**Expected Behavior**

I'm coming from FZF, which seems to stream the results in as they become available. The UI never hangs and I get instant feedback as I type.

**Actual Behavior**

Telescope seems to hang until all the results have been processed, which sometimes takes 10+ seconds in large codebases.

In this .gif I'm typing continuously, but as you can see the input is frozen for several seconds:

![telescope-slow](https://user-images.githubusercontent.com/468037/103602782-80723880-4ed2-11eb-9a51-0b192d32c2df.gif)

In this horrible codebase the only way to find things is to grep for them, so this is quite frustrating.

### Details

- nvim version: `NVIM v0.5.0-dev+9223d1450`
- Operating system: MacOS 11.1
- Telescope commit: `5d121ee`
- ripgrep `11.0.2`

### Configuration

```viml
" relevant plugins
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'romgrk/fzy-lua-native', { 'do': 'make' }
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-telescope/telescope-fzf-writer.nvim'
Plug 'nvim-telescope/telescope-fzy-native.nvim'
Plug 'nvim-telescope/telescope-vimspector.nvim'

" telescope config
nnoremap <leader>t :lua require('telescope').extensions.fzf_writer.files()<CR>
nnoremap <leader>/ :lua require('telescope').extensions.fzf_writer.staged_grep()<CR>
nnoremap <leader>b <cmd>Telescope buffers<cr>
nnoremap <leader>c :lua require('telescope.builtin').git_bcommits()<cr>

lua <<EOF
require('telescope').setup {
    extensions = {
        fzf_writer = {
            use_highlighter = true
        }
    }
}
require('telescope').load_extension('fzy_native')
EOF
```

**Comment by tami5** [comment]
@lynndylanhurley it would be nice if you have this issue open in fzf-telescope so that @tjdevries when god well, and he has time to refactor :laughing: he will take notice of the issue. 

but as far as I know about fzf_writer is:
- There is ongoing issue with performance when enabling the highlighter `use_highlighter = true`
- Increasing minimal characters to trigger the fzf does improve performance by a lot . eg. `minimum_grep_characters = 3`, `minimum_files_characters = 3` in fzf_writer dict

**Comment by lynndylanhurley** [comment]
Thanks @tami5, I'll raise the issue in the fzf-telescope repo as well.

The problem also exists with the built-in `live_grep` function, i.e.:

```viml
nnoremap <leader>/ :lua require('telescope.builtin').live_grep()<CR>
```

I tried using `fzf_writer` with the hope that it would resolve the issue, but it only improved the hang time slightly.

**Comment by tami5** [comment]
@lynndylanhurley I think this might fix our issue with current problems with live_grep and grep_string, https://github.com/nvim-telescope/telescope.nvim/pull/386 please test it out by doing `gh pr checkout 386` in the repo root, or something similar.

**Comment by lynndylanhurley** [comment]
Thanks @tami5 ! I just pulled down and tested, but I'm still getting the same slowness. There does seem to be an additional UI update that happens before the final results render but the input is still frozen for several seconds:

![telescope-slow-2](https://user-images.githubusercontent.com/468037/103677053-71799d80-4f47-11eb-909a-54ffc7e45093.gif)

**Comment by tssm** [comment]
For reference, if you want to replicate, I'm seeing the same while grepping the [nixpkgs](https://github.com/NixOS/nixpkgs) repo (which I do often) with the `fzy-native` extension enabled and disabled, which makes me thinks it is a UI issue as lynndylanhurley has pointed out

**Comment by Conni2461** [comment]
There is an async take 2 which comes closer to not blocking input https://github.com/nvim-telescope/telescope.nvim/pull/457. If i recall correctly it doesn't have on live_grep tho, because the string processing, still happens in main thread which makes it block. 

Tj was talking about continuing this work in a take 3 if i recall correctly.

For now, what i am doing is this. Most of the time i already know what i am looking for, so i basically prefilter the results.
```lua
require'telescope.builtin'.grep_string{ only_sort_text = true, search = vim.fn.input("Grep For >") }
```

**Comment by dagadbm** [comment]
just curious to ask how this is moving along. I noticed the plenary issue was already merged and there are plans to make the async/await part of neovim core. 
Any news?

**Comment by elianiva** [comment]
see #709

**Comment by elianiva** [comment]
see #709 for progress

**Comment by rnevius** [comment]
Looks like #709 did not include making `live_grep()` async.

**Comment by clason** [comment]
No, as it says right in the commit message :)

`live_grep` repeatedly spawns an external job (rather than doing it once and then continuously) filtering the results and so requires https://github.com/nvim-lua/plenary.nvim/pull/113.

**Comment by elianiva** [comment]
I mentioned that because we're *moving* towards async, not necessarily mean "we're making live_grep async". Sorry if that causes confusion 😆

**Comment by Conni2461** [comment]
Tj made some progress regarding live_grep. See https://github.com/nvim-telescope/telescope.nvim/pull/987

**Comment by fdschmidt93** [comment]
Solved/stale.
