### ISSUE TITLE
Place to publish extensions

### ISSUE THREAD

**Issue by delphinus** [nvim-telescope/telescope.nvim#393]
I made a extension: [telescope-ghq][]. Do this project have any place to list extensions? Can I write to README? or Wiki?

[telescope-ghq]: https://github.com/delphinus/telescope-ghq.nvim

**Comment by tami5** [comment]
Hey @delphinus, hmm I guess we should create a wiki page for extensions cc @rockerBOO . 

Currently we use nvim-telescope org to list and host extensions. If you like I can create a repo for telescope-ghq and give me access. Otherwise, wiki page would do it.

**Comment by rockerBOO** [comment]
Community Extensions somewhere would be good. 

We can start by listing them on the README for good exposure or a Wiki page would be good.

**Comment by tami5** [comment]
> Do we offer a certain level of support? Or is it just superficial?

@rockerBOO 

I guess, it kinda increases visibility and accessibility in which members ans users can navigate telescope-nvim, read the code and open issues or prs. And if there a major change in the future, I’d say these extensions will most likely have better support in that they will be easily updated in accordance with the breaking changes upstream.

**Comment by delphinus** [comment]
@tami5 Thank you for your offer, and I added you to telescope-ghq.

[ghq][] is a popular utility and there is demand for telescope-ghq, I think. So this may exists on telescipe.nvim org. And wiki page is also good for extensions for less popular or more niche tools.

[ghq]: https://github.com/x-motemen/ghq

For now, I will update [this page][] to list extensions in README and mine.

[this page]: https://github.com/nvim-telescope/telescope.nvim/wiki/Extensions

**Comment by tami5** [comment]
Oh I was that I create something like nvim-telescope/telelscope-gqh if you like, as I think it can provide better visibility

**Comment by Conni2461** [comment]
You should be able to just transfer his repo to this org. If he wants ro

**Comment by delphinus** [comment]
Yes, I intended it. Pls transfer telescope-ghq to this org ;)

**Comment by tami5** [comment]
@delphinus sure Did you send an invite? I don't see it, can you resend

**Comment by tami5** [comment]
@delphinus I think I'd need a admin access, I can't see settings

**Comment by tami5** [comment]
@delphinus in end of settings page you can do 
```
Transfer ownership
Transfer this repository to another user or to an organization where you have the ability to create repositories. 
```

Then insert nvim-telescope

**Comment by delphinus** [comment]
I did this,

<img width="435" alt="スクリーンショット 0003-01-06 17 55 35" src="https://user-images.githubusercontent.com/1239245/103749180-868a2580-5048-11eb-9ca1-29e234fe2111.png">

and get an error

```
You don’t have the permission to create public repositories on nvim-telescope
```

I wonder I should join nvim-telescope org to do this?

**Comment by tami5** [comment]
@delphinus yep I'd need admin access or maybe transfer to me

**Comment by delphinus** [comment]
@tami5 hmm.. I saw no options to set permissions in inviting you.

https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository

> Repositories owned by an organization can grant more granular access. For more information, see "Access permissions on GitHub."

Perhaps this means any collaborator joining a personal repo cannot have admin access on it.

I'm not confident because this is my first attempt to transfer my personal repo to organizations. I should become nvim-telescope org's member, don't you think?

**Comment by tami5** [comment]
@delphinus done, now you have admin access https://github.com/nvim-telescope/telescope-ghq.nvim

**Comment by delphinus** [comment]
@tami5 Thank you, but you've created a new repo on nvim-telescope instead of transferring mine? So I still have no access for the repo: nvim-telescope/telescope-ghq.nvim. I cannot even push simply.

As I thought, we should do either of plans below.

1. I become a nvim-telescope member (temporarily?), and transfer telescope-ghq.nvim from delphinus org to nvim-telescope org.
2. You create an empty repo and give my an admin access, and I (forcely) push my commit tree.
   * Now unfortunately nvim-telescope/telescope-ghq.nvim lacks my commit history.

**Comment by delphinus** [comment]
Too sorry! I missed the invitation. Finally I got admin access to nvim-telescope/telescope-ghq.nvim.  Thanks all.

**Comment by tami5** [comment]
> Now unfortunately nvim-telescope/telescope-ghq.nvim lacks my commit history.

@delphinus you can hard reset to the first commit and push your history back, I'm actually wondering if you even can get the repo history to the new one.

**Comment by delphinus** [comment]
@tami5 Hi, I created [telescope-z.nvim][] and [telescope-node-modules.nvim][]. They are also useful for everyone. Can you transfer them to nvim-telescope org? It is enough to create empty repos and you give me permissions as you did ;)

[telescope-z.nvim]: https://github.com/delphinus/telescope-z.nvim
[telescope-node-modules.nvim]: https://github.com/delphinus/telescope-node-modules.nvim

**Comment by elianiva** [comment]
I've made them both and invited you as an admin :)

**Comment by delphinus** [comment]
Thank you! I've transferred them.
