### ISSUE TITLE
Support symlinks

### ISSUE THREAD

**Issue by sharksforarms** [nvim-telescope/telescope.nvim#394]
### Description
Trying to use builtin find_files on a directory which is a symlink

**Expected Behavior**
Should show contents of path symlink points to

**Actual Behavior**
Telescope pops up, shows no files, no errors are shown

### Details

```lua
function M.nvim_config(opts)
  local opts = require('telescope.themes').get_dropdown{
    -- cwd = "~/.config/nvim" is a symlink to "~/source/dotfiles/nvim",
    cwd = vim.fn.stdpath("config"),
    file_ignore_patterns = { "plugged/" },
  }

  require('telescope.builtin').find_files(opts)
end
```

**Comment by Conni2461** [comment]
right now you should be able to do `cwd = vim.loop.fs_realpath('~/.config/nvim')` but we should check if something like this is in `plenary.path` and fix it when doing #387

**Comment by Conni2461** [comment]
@sharksforarms Does this still happen? I am trying to reproduce this for @anott03 but i can't :laughing: everything works as expected.

**Comment by sharksforarms** [comment]
The issue is about following symlinks inside folders.

```
mkdir /tmp/test
mkdir /tmp/other
touch /tmp/test/file1
touch /tmp/other/file2
ln -s /tmp/other /tmp/test/other
```

```rust
  local opts = require('telescope.themes').get_dropdown{
    cwd = "/tmp/test/",
  }

  require('telescope.builtin').find_files(opts)
```

Only `file1` will be shown. The symlink to `/tmp/other` is not followed.

**Comment by Conni2461** [comment]
Oh that is completely different then your original post. Is it not?

> By default, fd does not descend into symlinked directories. Using this flag, symbolic links are also traversed.

Just add `-L` to the options. So do a new find_files command. We could do a opt for that as well and add it to the other commands. But i don't know if `rg` supports it.

**Comment by sharksforarms** [comment]
Ahh thanks! That makes sense. I actually made the issue as I had symlinked folders in my nvim config, but then ended up just making nvim the top level directory and didn't have this issue anymore.

**Comment by Conni2461** [comment]
I still think we can do an opt here :) It seems to be `-L` for all commands.

**Comment by DavidePatria** [comment]
could you please share how this option should be added to telescope config?

**Comment by dgrabla** [comment]
@DavidePatria Did you find out how to add the option?

**Comment by dgrabla** [comment]
@DavidePatria Got it

![image](https://user-images.githubusercontent.com/1942073/141302859-fb0d6dc1-6465-481c-b05c-64e2e848c37c.png)

**Comment by DavidePatria** [comment]
Thank you! I have to read the doc more thoroughly. I had only found how to pass opts to the function and had added those to the mappings, but of course the opts would need to be rewritten every time.

**Comment by GhiathAjam** [comment]
For future visitors, you can also do:
``` lua
  require('telescope').setup {
    pickers = {
      find_files = {
        follow = true
      }
    }
  }
```

**Comment by volovikariel** [comment]
> For future visitors, you can also do:
> 
> ```lua
>   require('telescope').setup {
>     pickers = {
>       find_files = {
>         follow = true
>       }
>     }
>   }
> ```

Where can someone get the list of all the valid arguments?

**Comment by GhiathAjam** [comment]
@volovikariel :help telescope

**Comment by SurajKharkwal** [comment]
I tried following the suggested approach for [telescope](https://github.com/SurajKharkwal/dotfiles/blob/main/nvim/.config/nvim/lua/plugins/telescope.lua), but the issue persists. Whenever I try to open Neovim (default **LazyVim**) in any of my _~/.dotfiles/cava/.config/cava_ directories, it opens Neovim in the parent dotfiles folder instead or i can say  both Telescope and Neo Tree opens at the parent folder.
