### ISSUE TITLE
Feature image preview

### ISSUE THREAD

**Issue by windwp** [nvim-telescope/telescope.nvim#408]
today i am try to implement this https://github.com/seebye/ueberzug on telescope and i got this

https://user-images.githubusercontent.com/7578110/104086706-b164bb80-528c-11eb-8ca7-fd68dab50016.mp4

it work perfect inside tmux but i don't know why the image position is not correct on terminal
i try many way to get that position correct but I can't
I hope somebody can help me with it.

I am not made a PR because it only work on linux.

https://gist.github.com/windwp/ccbd2ca4696059ccdd91f8811453ae8f

**Comment by tami5** [comment]
:heart_eyes: :heart_eyes: :heart_eyes:, you should definitaly make a pr as we can add note about image previews not working in windows

**Comment by elianiva** [comment]
This is very cool! You should definitely make a PR because as tami5 said, we can add a note that it only works on Linux

**Comment by Conni2461** [comment]
Okay my thoughts to the current code.
1. I don't know if we need a media_files in core. I kinda don't open media_files with git.
2. I would not do that search in the find command. It doesn't work for `rg --files` users. We can make the filtering in `make_entry` or we can make a `only` similar to `file_ignore_patterns` in `pickers.lua`

**Comment by elianiva** [comment]
Would this be better as a telescope extension instead of implementing it in core?

**Comment by Conni2461** [comment]
Oh @windwp please don't ping people in the wishlist. Ping them in your issue or PR. Forgot to mention that 😆

**Comment by windwp** [comment]
i agree we should not put it to core function because it require to install many stuff for working.
and it have bug and only working on linux

**Comment by elianiva** [comment]
The image position is correct outside of tmux btw, I don't know why you commented out the part that makes it work :laughing:

**Comment by windwp** [comment]
what part ?  i change many way but it always display  outside of the preview.

**Comment by elianiva** [comment]
https://gist.github.com/windwp/ccbd2ca4696059ccdd91f8811453ae8f#file-vimg-sh-L43-L57

you don't need an if statement here, the first condition works fine with or without tmux

**Comment by windwp** [comment]
lol my  Überzug is old and after update  Überzug  it it work. :smile:

**Comment by elianiva** [comment]
do we want to make an extension repo so we can close this issue?

**Comment by tjdevries** [comment]
Yeah, extension repo is a good idea. Please ping me in the repo (anyone on core can make?) with anything missing from core for plugins. I can implement some features (perhaps ability to register "hey, I can preview that image / filetype" or something similar is what I'm thinking off the top of my head).

**Comment by elianiva** [comment]
I've made one [here](https://github.com/nvim-telescope/telescope-media-files.nvim) and invited @windwp
