### ISSUE TITLE
Feature: Add option to open Telescope in normal mode

### ISSUE THREAD

**Issue by wordhou** [nvim-telescope/telescope.nvim#409]
Currently Telescope always opens a list in insert mode. For some use cases the user may wish to open a list in normal mode. For instance, for quick previewing of buffers. It would be nice to have an option to set the initial mode when calling Telescope, like `:Telescope buffers initial_mode=normal`, and perhaps a global option to set the default initial mode.

**Comment by tami5** [comment]
+1. Indeed an important option to have

**Comment by Conni2461** [comment]
Cool idea. Not hard to realize but i would wait until https://github.com/nvim-telescope/telescope.nvim/pull/293 is merged. I don't want tj to refactor again.

But its a good first issue so let me explain whats need to be done:
1. Create config value
2. Set config value like others so opts can overwrite it in pickers.lua
3. Find `startinsert` in pickers.lua

**Comment by tjdevries** [comment]
you could probably already do this just by adding an `on_complete` callback.

**Comment by Conni2461** [comment]
Yes its works with `on_complete` good point. I still think it would be more elegant to have a config value unless you think differently. I ran
```
:lua require'telescope.builtin'.find_files{ on_complete = { function() vim.cmd"stopinsert" end } }
```

**Comment by Conni2461** [comment]
Done in #442
