### ISSUE TITLE
Calling a customized entry_maker causes an error

### ISSUE THREAD

**Issue by delphinus** [nvim-telescope/telescope.nvim#414]
### Description

I'm developing [telescope-z.nvim][]. I implemented [entry_maker][] with referring to [gen_from_git_commits][]. My implementation has almost the same logic as `gen_from_git_commits`'s one, but Neovim raises an error with mine.

[entry_maker]: https://github.com/delphinus/telescope-z.nvim/blob/45bdd99d2315f35a151bd303a66b81beb794df45/lua/telescope/_extensions/z_builtin.lua#L11-L38
[gen_from_git_commits]: https://github.com/nvim-telescope/telescope.nvim/blob/9503603f888305ec799c9346f51a6e3da7f5b89b/lua/telescope/make_entry.lua#L262-L292
[telescope-z.nvim]: https://github.com/delphinus/telescope-z.nvim

**Expected Behavior**

`:Telescope z list` causes no error.

**Actual Behavior**

`:Telescope z list` causes an error below.

```vim
Error executing luv callback:
...t/telescope.nvim/lua/telescope/pickers/entry_display.lua:6: E5560: vimL function must not be called in a lua loop callback
Error executing luv callback:
cannot resume dead coroutine
```

`entry_display.lua:6` is calling `vim.fn.strdisplaywidth()`. I comment out this `if` block, then no error occurs.

https://github.com/nvim-telescope/telescope.nvim/blob/de80a9837cd1d207981c1f6dbf504436f8bfee13/lua/telescope/pickers/entry_display.lua#L6

### Details

<details><summary>Reproduce</summary>

1. nvim test.lua

   ```lua
   local install_path = vim.fn.stdpath'data'..'/site/pack/packer/opt/packer.nvim'
   if vim.fn.isdirectory(install_path) == 0 then
     os.execute('git clone https://github.com/wbthomason/packer.nvim '..install_path)
     vim.cmd'packadd packer.nvim'
   end

   require'packer'.startup(function()
     use'wbthomason/packer.nvim'
     use{
       'nvim-telescope/telescope.nvim',
       requires = {
         'nvim-lua/popup.nvim',
         'nvim-lua/plenary.nvim',
         {'delphinus/telescope-z.nvim', branch = 'feature/entry-maker'},
       },
       config = function()
         vim.cmd[[packadd telescope-z.nvim]]
         require'telescope'.load_extension'z'
       end,
     }
   end)
   ```

2. nvim -i NONE -nu test.lua
3. `:PackerInstall` then `:PackerCompile` then `:qa`
4. nvim -i NONE -nu test.lua
5. `:Telescope z list`
6. An error occurs.

   ```vim
   Error executing luv callback:
   ...t/telescope.nvim/lua/telescope/pickers/entry_display.lua:6: E5560: vimL function must not be called in a lua loop callback
   Error executing luv callback:
   cannot resume dead coroutine
   ```
</details>

<details><summary>Environment</summary>

- nvim version: NVIM v0.5.0-dev+1005-ga1ed941a7
- Operating system: macOS 10.15.7
- Telescope commit: de80a9837cd1d207981c1f6dbf504436f8bfee13

</details>

<details><summary>Configuration</summary>
<p>
 

```lua
local install_path = vim.fn.stdpath'data'..'/site/pack/packer/opt/packer.nvim'
if vim.fn.isdirectory(install_path) == 0 then
  os.execute('git clone https://github.com/wbthomason/packer.nvim '..install_path)
  vim.cmd'packadd packer.nvim'
end

require'packer'.startup(function()
  use'wbthomason/packer.nvim'
  use{
    'nvim-telescope/telescope.nvim',
    requires = {
      'nvim-lua/popup.nvim',
      'nvim-lua/plenary.nvim',
      {'delphinus/telescope-z.nvim', branch = 'feature/entry-maker'},
    },
    config = function()
      vim.cmd[[packadd telescope-z.nvim]]
      require'telescope'.load_extension'z'
    end,
  }
end)
```

**Comment by Conni2461** [comment]
Known issue but still thanks for reporting.
`finders.new_oneshot_job` doesn't work with `displayer` because we are not allowed to call any vimL function inside a luv callback. But `vim.fn.strdisplaywidth` is a vimL function and needed for truncating a string.
We had this discussion here: https://github.com/nvim-telescope/telescope.nvim/pull/274#discussion_r528363826

Maybe you know an lua function which does the same or we need to write our own and i think `#` will really work for here.

The solution is to use something like `local results = vim.split(utils.get_os_command_output(cmd), '\n')` and do a static table. Not perfect but will make it work at least :)

**Comment by delphinus** [comment]
Thanks. I used `get_os_command_output` for a stopgap measure.
