### ISSUE TITLE
Better Default Experience

### ISSUE THREAD

**Issue by tjdevries** [nvim-telescope/telescope.nvim#415]
- [x] Use vim buffer previewers out of the box
- [ ] Better default highlights and documentation

cc @nvim-telescope/core , please comment below with items we should add to this list.

**Comment by tami5** [comment]
syntax highlighting for fuzzy search in current in buffer

**Comment by elianiva** [comment]
Make previewer wider than the entry list? Currently the entry list takes a lot of space compared to the preview.

**Comment by tjdevries** [comment]
Sorry, I meant without repeating other issues. This is just about how to make telescope work better right after install.

**Comment by rockerBOO** [comment]
I think `:Telescope` should show a default onboarding document, showing all the available functions as well as a short intro on what Telescope can do. 

Would be nice for people to start with `:Telescope` for everything to start. They go down and pick their option form the list and then see the results. Then we would be re-affirming how it works as well as the next step of configuring all their keybinds. 

One component of using telescope is learning all the stuff it can do and then having to find keybinds for ALL the different things it can do. This is a barrier to onboarding because you will need to discover binding you like to even really try it out.

I think this would work like how `'telescope.builtin'.builtin{}` but have an intro item at the top of the list. The document would show on the preview on what telescope is, the `:Telescope *` and how to bind the commands. Also links for additional configuration docs.

**Comment by numToStr** [comment]
IMO `sorters.get_fzy_sorter` is better and should be the default sorter.

**Comment by Conni2461** [comment]
We should discuss if `builtin.buffers` should have `show_all_buffer = true` as default like its suggested in #368, #338 and #97. That way we would follow `:buffers` more closely.

The second thing that was requested(and we could discuss) was using `sorter = require'telescope.sorters'.get_substr_matcher()` as a sorter when `sort_lastused = true`. Ref #451

**Comment by jesseleite** [comment]
@Conni2461 Just came across `sort_lastused = true`, love how it pre-selects the last open buffer. I know `<C-^>` is faster, but this is a nice touch that fzf users coming over are already used to. Definitely think that `sort_lastused = true` should be default ❤️

PS. I'm confused what `show_all_buffer` does?

**Comment by lucastrvsn** [comment]
Default mappings to select items up and down should also work with <C-h> and <C-j>. I think this mappings is much more convenient for selection navigation.

**Comment by smithbm2316** [comment]
> Default mappings to select items up and down should also work with `<C-h>` and `<C-j>`. I think this mappings is much more convenient for selection navigation.

While I know there are a number of people who use `<C-h>` and `<C-j>` as bindings for scrolling, I'm not sure if this should be a default. `<C-n>` and `<C-p>` are the normal vim bindings for this, and I think it makes more sense to keep those as the defaults. One can always add `<C-h>` and `<C-j>` in their own personal config, just my two cents.

I think adding documenation on some example custom functions/pickers could be something beneficial to add to the builtin help documentation for Telescope (after I complete documenting the pickers, sorters, and clean up the README first of course). While the goal of Telescope is certainly not to teach people basic Lua (which a lack of knowledge of seems to often be the source of confusion for new people, including myself when I didn't know much Lua and didn't know much about Neovim), I do think considering how big of a following it has in the Neovim community and how often it is recommended to people it may be beneficial to try and have a few more examples for people to pick apart would be useful. Perhaps we could make a post on r/neovim requesting for people to submit some of their favorite custom Telescope functions that they have in their config to the Wiki, and eventually transition a few of them to the help docs themselves? Just an idea, not sure how many people would even be willing to submit or try and contribute to that part of the project, as writing code is often the more fun part than writing the docs :rofl:

**Comment by R0LA1mRifcF8yAkk** [comment]
> Default mappings to select items up and down should also work with `<C-h>` and `<C-j>`. I think this mappings is much more convenient for selection navigation.

Don't you mean `<C-j>` and `<C-k>`? What am I missing here? Why `h` for vertical movement?

**Comment by smithbm2316** [comment]
> Don't you mean `<C-j>` and `<C-k>`? What am I missing here? Why `h` for vertical movement?

Yes, that is what I meant. Just had a brain freeze when I wrote that I guess 🤣

**Comment by Conni2461** [comment]
Other than `<c-h>` and `<c-j>` for scrolling as well as `:Telescope` having builtin docs (might have been more of a feature request) we have resolved all other things here.

I am closing this
