### ISSUE TITLE
git_branches can't checkout to remote(fixed) and no log for remote branch

### ISSUE THREAD

**Issue by 3nuc** [nvim-telescope/telescope.nvim#424]
### Description
If you have branch names like `remotes/origin/feature/1234`, git_branches will strip the `remotes/origin/feature/` part when checking out after you press enter. Notice that the "feature/" should not be stripped as it's not a git "builtin" prefix.

Problem is that it later when you press enter and actions.git_checkout is called - I assume - it uses `git checkout 1234` (doesn't exist) rather than `git checkout feature/1234`

This happens here due to the naive regex
https://github.com/nvim-telescope/telescope.nvim/blob/dda5b44b94f715395798f92f9e17e84bd0666f4a/lua/telescope/builtin/git.lua#L77

![image](https://user-images.githubusercontent.com/5359825/104263532-10dbea80-548a-11eb-826c-a9e9c32f7ad1.png)

**Expected Behavior**
it should be possible to checkout to a branch whose name contains multiple slashes eg. "remotes/origin/feature/1234" using :Telescope git_branches

**Actual Behavior**
Telescope doesn't checkout to the remotes/origin/feature/1234 branch. It stays on the current branch.

### Details

<details><summary>Reproduce</summary>

```sh
$ git clone https://github.com/3nuc/git_branches_repro
$ cd git_branches_repro
$ git branch --all # ensure remotes/origin/feature/5678 shows up here. remember that you are on feature/1234 branch initially after clone
$ nvim -nu test-vim .
:Telescope git_branches "press enter
5678 "type 5678 to find the feature/5678 branch then press enter
:qa
$ git branch " you should still be on feature/1234, which is wrong because you should be on feature/5678
```
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-DZns5T/neovim-0.5.0+ubuntu2+git202101090620-b535575ac-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-DZns5T/neovim-0.5.0+ubuntu2+git202101090620-b535575ac-d569569c9/build/config -I/build/neovim-DZns5T/neovim-0.5.0+ubuntu2+git202101090620-b535575ac-d569569c9/src -I/build/neovim-DZns5T/neovim-0.5.0+ubuntu2+git202101090620-b535575ac-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-DZns5T/neovim-0.5.0+ubuntu2+git202101090620-b535575ac-d569569c9/build/src/nvim/auto -I/build/neovim-DZns5T/neovim-0.5.0+ubuntu2+git202101090620-b535575ac-d569569c9/build/include
Compiled by buildd@lgw01-amd64-060

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

- Operating system: OS: Kubuntu Hirsute Hippo (development branch) x86_64 
- Telescope commit: 4ca523232ec8ed6da56b57f3ec501693f63dc723

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by 3nuc** [comment]
There are also other related issues - the git log preview on the right will say "no log found for branch 5678" because it looks for 5678 rather than feature/5678

![image](https://user-images.githubusercontent.com/5359825/104265609-4256b500-548e-11eb-9719-5b484e749f19.png)

**Comment by 3nuc** [comment]
Oh this is #423

**Comment by Conni2461** [comment]
Thanks for your detailed report :)
We still wont get any log for `remotes/fork/feature/1234` if `feature/1234` is not local as `feature/1234` maybe i find a good fix that works with our previewer architecture.

**Comment by 3nuc** [comment]
I think something like "git log unavialable for remote branches" would be ok.

This issue is mostly about what #423 addressed. Should I close this issue or would you like to keep it to track the remaining git log preview issues?

**Comment by Conni2461** [comment]
Lets keep it open. I will try to figure out something later today
