### ISSUE TITLE
Q:  How to set the ratio of result window and preview window

### ISSUE THREAD

**Issue by bryceyang** [nvim-telescope/telescope.nvim#425]
background:  I want to set the ratio of result window and preview window, cause I want preview window bigger.

Is there any official and detail doc about config options I can do with telescope?

**Comment by Conni2461** [comment]
We are still working on that documentation and its really confusing. I also have no idea how it works.
Currently i use:
```lua
require('telescope').setup {
  defaults = {
    layout_strategy = "flex",
    winblend = 5,
    layout_defaults = {
      horizontal = {
        width_padding = 0.1,
        height_padding = 0.1,
        preview_width = 0.6,
      },
      vertical = {
        width_padding = 0.05,
        height_padding = 1,
        preview_height = 0.5,
      }
    },
  }
}
```
Which gives me a bigger preview window. Maybe that works for you

**Comment by bryceyang** [comment]
Thanks for your help. The demo you provided is much helpful.
