### ISSUE TITLE
find_files gives error "vim/shared.lua:226: key found in more that one map: 1"

### ISSUE THREAD

**Issue by jvgrootveld** [nvim-telescope/telescope.nvim#426]
### Description
While invoking `:Telescope find_files` as described in the readme [Usage](https://github.com/nvim-telescope/telescope.nvim#usage) the below error is shown and the find functionality is not working.

I found [this](https://www.reddit.com/r/neovim/comments/kv17d1/neovim_telescope_find_files_search_error/) Reddit post and after installing [sharkdp/fd](https://github.com/sharkdp/fd), the functionality works.

**Expected Behavior**
The find functionality works with the already installed `find` command.

**Actual Behavior**
The below error message is shown:
```
vim/shared.lua:226: key found in more that one map: 1
```

After installing `fd` the functionality works.

### Details

<details><summary>Reproduce</summary>

1. Install Telescope though vim-plug
```
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
```

2. Invoke `find_files`
```
:Telescope find_files
```
</details>

<details><summary>Environment</summary>

- nvim --version output:
```
NVIM v0.5.0-dev+1016-g0af5a56e4
Build type: Release
LuaJIT 2.1.0-beta3
```
- Operating system:
```
MacOS 11.1 (Big Sur)
```
- Telescope commit:
```
4ca5232
```

</details>

<details><summary>Configuration</summary>
Just the default install no extra configuration.
</details>

**Comment by Conni2461** [comment]
Thanks for the report :)
Can reproduce looking into it later today
