### ISSUE TITLE
Pressing enter in an empty list and moving cursor left/right blocks backspace

### ISSUE THREAD

**Issue by OkanEsen** [nvim-telescope/telescope.nvim#429]
### Description
As per: https://github.com/nvim-telescope/telescope.nvim/issues/231#issuecomment-758282094:

> [...] The second issue still persists though: just fill the input, until no entry is matched/visible and press enter. Cursors moves len(input) - 1 and moving the cursor to the end and pressing backspace is prevented.
> 
> Video: https://i.imgur.com/srnllRo.mp4

It actually doesn't matter, if the cursor is moved to the end or not, it happens always after the cursor move.

**Expected Behavior**
Backspace should not be prevented.

**Actual Behavior**
Backspace is being prevented.

### Details

See video or:

1. Open file finder
2. Type anything which results in no entries.
3. Press enter
4. Move the cursor left or right
5. Press backspace

Typing another char fixes the issue.

**Comment by caojoshua** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/974 prevents the cursor from moving

> Backspace is being prevented.

see https://github.com/nvim-telescope/telescope.nvim/issues/852. upstream prompt buffer bug
