### ISSUE TITLE
Help previewer configuration

### ISSUE THREAD

**Issue by plagache** [nvim-telescope/telescope.nvim#431]
Hi,

I am trying to make previewer work, with treesitter (or bat) for all preview.
However I don't know how to set it, and I don't understand the following line in the config file:
```
file_previewer = require'telescope.previewers'.cat.new
```

I have try this :
```
file_previewer = require'telescope.previewers'.treesitter.new
```

with no succes unfortunately.

From what I have understand while "reading" the code, it is supposed to work out of the box with bat? 

Sorry for the inconvenience.
And thanks for the help in advance.

**Comment by Conni2461** [comment]
All good. Please tell me if the documentation is not clear

```lua
file_previewer = require'telescope.previewers'.cat.new
```
sets the var `file_previewer` to the function `require'telescope.previewers'.cat.new` so we end up with a "function pointer". Thats the current default and will result in you using `term_open` and `bat`.
If you are interested in using the new buffer_previewers which make use of tree-sitter highlighting put this inside your setup function:
```lua
    file_previewer = require'telescope.previewers'.vim_buffer_cat.new,
    grep_previewer = require'telescope.previewers'.vim_buffer_vimgrep.new,
    qflist_previewer = require'telescope.previewers'.vim_buffer_qflist.new,
```

**Comment by plagache** [comment]
After reading your explanation, I understood what vim_buffer is. And now I understand the documentation.
Thanks for your quick response and clear explanation, it works like a charm. 

![image](https://user-images.githubusercontent.com/47725921/104358757-2d6e3600-550f-11eb-8de3-c782685fe419.png)

**Comment by lougreenwood** [comment]
@Conni2461 

I'm also using the new previewer config, but I don't get any highlighting. Is any other config required, is it possible to check which previewer is actually being used at runtime?

```lua
local telescope = require('telescope')
local previewers = require('telescope.previewers')

telescope.setup{
    defaults = { 
        file_ignore_patterns = {"node_modules", "/dist"},
    },
    extensions = {
        frecency = {
            show_scores = false,
            show_unindexed = true,
            ignore_patterns = {"*.git/*", "*/tmp/*", "*/node_modules/*"},
        }
    },
    file_previewer = previewers.vim_buffer_cat.new,
    grep_previewer = previewers.vim_buffer_vimgrep.new,
    qflist_previewer = previewers.vim_buffer_qflist.new,
    layout_strategy = 'flex'
}

telescope.load_extension("frecency")
```

**Comment by Conni2461** [comment]
Everything has to be inside defaults unless its an extension. So should work
```lua
telescope.setup{
    defaults = { 
        file_ignore_patterns = {"node_modules", "/dist"},
        file_previewer = previewers.vim_buffer_cat.new,
        grep_previewer = previewers.vim_buffer_vimgrep.new,
        qflist_previewer = previewers.vim_buffer_qflist.new,
        layout_strategy = 'flex'
    },
    extensions = {
        frecency = {
            show_scores = false,
            show_unindexed = true,
            ignore_patterns = {"*.git/*", "*/tmp/*", "*/node_modules/*"},
        }
    }
}
```

**Comment by lougreenwood** [comment]
hmm, I installed bat and it seems to be working without putting the config in defaults. Will try that next and see what happens

**Comment by Conni2461** [comment]
It currently still defaults to bat but this configuration uses a completely different way of previewing files. It doesn't need an external program it uses vim buffers and vims regex highlighting or treesitter without sacrificing performance because of some lua/luv async magic. That way your color scheme will perfectly be applied, etc.

These previewers will also be default very soon and bat previewers will be marked deprecated.

**Comment by lougreenwood** [comment]
Yep, I removed `bat`, moved into defaults and I have the new style... I can tell because markdown is not highlighted because of the lack of bundled nvim treesitter plug-in 😎

**Comment by elianiva** [comment]
Yeah, the existing markdown parser still has a segfault issue but tami5 is working on the new parser
