### ISSUE TITLE
find_command - support environment variables and aliases

### ISSUE THREAD

**Issue by roginfarrer** [nvim-telescope/telescope.nvim#435]
I was trying to create a custom search command for my dotfiles. I have my dotfiles in a bare git repository, so it's not as simple as pointing `git_files` to a specific directory. My first attempt, and what I want to see work as expected, is the following:

```lua
function search_dotfiles()
  require('telescope.builtin').find_files {
    find_command = {'git', '--git-dir', '$HOME/.dotfiles/', '--work-tree', '$HOME', 'ls-tree', '--full-tree', '-r', '--name-only', 'HEAD'}
  }
end
```

`$HOME` is an environment variable set to `/Users/rfarrer/` on my machine. 

Furthermore, it would be cool if my shell aliases also worked. I have the command `config` mapped to `git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME`, and it would be cool if that would work, as well:

```lua
function search_dotfiles()
  require('telescope.builtin').find_files {
    find_command = {'config', 'ls-tree', '--full-tree', '-r', '--name-only', 'HEAD'}
  }
end
```

If I try to use my `config` command or `$HOME`, Telescope fails to find any files (I think because it fails to expand those variables).

**Comment by Conni2461** [comment]
About the first one: We would need to either expand each entry of the table, or we would need to pass in your whole env to plenary job because a plenary job, which uses luvit, has an empty env on calling. I don't like both tbh.

About the second one: If i am not wrong but i think thats impossible for the same reason why `:!config status` will also give you `command not found` we would need to source your `.bashrc`/`.zshrc` before we actually could run a command which can be slow.

But you could just solve that issue by your own. Put a bash script called `config` in your path (don't forget to make it executable):
```bash
#!/bin/sh

/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $*
```

**Comment by roginfarrer** [comment]
Thanks for the help. I thought I'd mention it since I could see this be a common use case. I can do this pretty easily in fzf, which I understand interacts with the terminal environment differently:

```vim
function! s:fzf_dotfiles()
  let command = 'config ls-tree --full-tree -r --name-only HEAD'
  call fzf#run(fzf#wrap({ 
    \ 'dir': '~/', 
    \ 'source': command }))
endfunction
```

Feel free to close this if you don't think it will be implemented.

**Comment by Conni2461** [comment]
I think its not a trivial think to realize. If someone wants to prove me wrong, they are very welcome to do so.

Closing for now.

**Comment by rieje** [comment]
Following works, thanks to @fdschmidt93 who is always helpful on Gitter:

    M.dotfiles = function(opts)
      opts = opts or {}
      pickers.new(opts, {
                      prompt_title = '~~ dotfiles ~~',
                      finder = finders.new_oneshot_job(
                        -- Your external process here
                        { "git", "--git-dir=" .. os.getenv("HOME") .. "/.dotfiles.git", "ls-tree", "-r", "HEAD", "--name-only" }
                      ),
                      previewer = previewers.vim_buffer_cat.new(opts),
                      sorter = conf.file_sorter(opts),
      }):find()
    end

More customization [here](https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md) if you know some lua.
