### ISSUE TITLE
Warn if trying to live_grep but rigrep is not installed (linux)

### ISSUE THREAD

**Issue by 3nuc** [nvim-telescope/telescope.nvim#436]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I do :Telescope live_grep<cr>, write a search term and nothing happens. Am I supposed to wait? Is it just taking a very long time to get results? This is fixed by installing rgrep, but README never says "INSTALL RIGREP OR IT WON'T WORK" explicitly

**Describe the solution you'd like**
When:
1. rigrep is not installed
2. and user tries to :Telescope live_grep<cr> and writes some text
A warning should be displayed (press ENTER to continue) that rigrep is not installed and the user should not be wasting time waiting for results

**Describe alternatives you've considered**
Instead of the message Telescope could just return 1 result saying "RIGREP NOT INSTALLED - no results"

**Additional context**
Tbh live_grep if rgrep is not installed behaves as if everything is ok - it will "lag" giving users the impression that a search is underway

It would be good to also add some text next to live_grep saying "THIS WON'T WORK UNLESS YOU INSTAL RIGREP". If someone goes back to read the README for the third time wondering why live_grep doesn't work (like me), you can come across eg. the "default config" part in the README and you can see it uses rg there, it can make you think "oh so maybe it'll work if I install rg?" but not "ah of course I'm stupid it says right there - install rigrep or it won't work"

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/396 There is a PR already. I just think that should be in plenary.

**Comment by Conni2461** [comment]
https://github.com/nvim-lua/plenary.nvim/pull/53 added this. It is shown in `messages` for me.
