### ISSUE TITLE
Specify list of directories for live_grep.

### ISSUE THREAD

**Issue by vishfrnds** [nvim-telescope/telescope.nvim#440]
**Is your feature request related to a problem? Please describe.**
Want to do a grep on list of folders only not all folders.
This works for find_files by either
find_files find_command=rg,--files,[list of dir]
or looks like added as a feature in https://github.com/nvim-telescope/telescope.nvim/issues/238

Would love if similar thing is available for live_grep.

**Comment by tami5** [comment]
if you are okay with reading lisp, you can port this 

```clj
(def paths
  ;; "Paths used to create custom find file prompt."
  {:config (vim.fn.stdpath "config")
   :deps (.. (vim.fn.stdpath "data") "/site/pack")
   :refs (or (a.string? (vim.fn.getenv "REFSDIR")) "~/refs")
   :repos (or (a.string? (vim.fn.getenv "REPOSDIR")) "~/repos")})

(def- alldirs [paths.refs paths.notes paths.repos "~/code"
               (let [cwd (vim.loop.cwd)
                     not-m #(not (string.match cwd (string.gsub $1 "~/" "")))]
                 (if (and (not-m paths.repos)
                          (not-m paths.refs)
                          (not-m "~/code"))
                   cur))])
```

Then in fd function, add alldirs to `search_dirs` 

Now thats just temp workaround I use
