### ISSUE TITLE
Should Telescope command parse more complex arguments?

### ISSUE THREAD

**Issue by delphinus** [nvim-telescope/telescope.nvim#447]
**Is your feature request related to a problem? Please describe.**

I'm refactoring `man_pages` picker in #413. I added an option: `sections` to limit sections to list man pages.

```vim
:Telescope man_pages sections=1,3,5
```

In Lua codes, it transforms `1,3,5` string into `{'1', '3', '5'}` table. Should `convert_user_opts()` have this logic to use this conversion for any other command?

**Describe the solution you'd like**

```vim
sections=1,2,3tiff,n,x
```

```lua
{sections = {'1', '2', '3tiff', 'n', 'x'}}`
```

It should convert values into not numbers but strings.

Any thoughts?

**Comment by Conni2461** [comment]
CC @glepnir 

I think the lua side should always expect a table and not a comma separated string. Similar that `find_command` is a table.

**Comment by glepnir** [comment]
Yes, I have found a way to achieve it.

**Comment by Conni2461** [comment]
One sec. Doesn't that already work? I can do `telescope find_files find_command=rg,--files,/tmp` e.g. which gives me a table

**Comment by Conni2461** [comment]
Oh i see. So all we need to do is add it to here https://github.com/nvim-telescope/telescope.nvim/blob/b82d6a7cba0af2d44850d9669d6ee320d6cf1eee/plugin/telescope.vim#L106

But i think a more general solution would be better but how do we know when to split the arg. Eg `:Telescope grep_string search=test,test` maybe i actually wanna look for `test,test` 🤔

**Comment by glepnir** [comment]
@Conni2461  Now I had rewrite it in my local. this issue can work.  About this `:Telescope grep_string search=test,test`, want to see `test,test` not a table right?

**Comment by glepnir** [comment]
maybe can do this?
```
search=test,test  => test,test
search->test,test => {test,test}
```

**Comment by Conni2461** [comment]
Hmm. I am not sure right now if we should convert every string that is comma separated to a table. Also i am not sure about having a difference between `=`, `==`, `->` that might be just more confusing.

I kinda think we should have a table with all options that should be converted and then if `arg_list[0]` is in that list convert.

**Comment by glepnir** [comment]
@Conni2461 I update my comment with `search={test,test} =>{test,test}`

**Comment by glepnir** [comment]
Like this issue the `section` keyword is not in default config values. it's a custom keyword, so we need to determine its type by certain matches

**Comment by Conni2461** [comment]
I kinda don't like any solution to this point. By doing `search={test,test}` we would break convention with `find_command=rg,--files,/tmp` which may be confusing and be only doing `search={test,test}` we may break mappings for users :|

**Comment by glepnir** [comment]
check the count of comma? if count is 1 we do not convert it to table?

**Comment by Conni2461** [comment]
`sections=1,3` should still be converted

**Comment by glepnir** [comment]
Now this can work in my local code
```lua
    elseif param[2]:find(',',1) ~= nil then
      user_opts[param[1]] = utils.split_by_pattern(param[2],'[^,]+')
    ...
```

**Comment by Conni2461** [comment]
I think we should specify somewhere which options should be converted. And if people wanna do some conversion in an extension they just have to do it themselves like this
```lua
opts.option = type(opts.option) == 'table' and opts.option or vim.split(opts.option, ',')
```
that would make lua side and vim side work

**Comment by glepnir** [comment]
This way need user parss they custom keywords to  config.values

**Comment by Conni2461** [comment]
Not really. The conversion doesn't happen in `config.values`. e.g. `find_command` is not even in `config.values`. The conversion happens here https://github.com/nvim-telescope/telescope.nvim/blob/b82d6a7cba0af2d44850d9669d6ee320d6cf1eee/plugin/telescope.vim#L106 or am i wrong

**Comment by glepnir** [comment]
this code is out.. check the pr

**Comment by glepnir** [comment]
this code is out.. check the pr

**Comment by windwp** [comment]
@glepnir  telescope autocomplete is broken on extension gh 
it can't autocomplete the second path  sample :`Telescope gh pull_request`

**Comment by glepnir** [comment]
@windwp  Now should be work in #450

**Comment by tjdevries** [comment]
Does it work now?
