### ISSUE TITLE
neovim tab-local current directory overwritten by find_files (possibly others as well)

### ISSUE THREAD

**Issue by urandom** [nvim-telescope/telescope.nvim#449]
### Description
When I set different current directories for different tabs with `:tcd`, and then proceed to use `find_files` in one of the tabs, the current directory of that tab is set as the current directory of the other tabs as well, overwriting the previous one set by `:tcd`

**Expected Behavior**
When using `find_files` in a tab, its current directory should not be set to every other tab in the editor

**Actual Behavior**
The current directory from the tab where `find_files` is invoked is set as the current directory for all other tabs

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :tcd some-dir
3. :tabnew
4. :tcd other-dir
5. :Telescope find_files
6. :tabp
7. :pwd

</details>

<details><summary>Environment</summary>

- nvim --version output: 
<pre>
NVIM v0.5.0-828-g0a95549d6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-abaca5c2-51e7-4cf1-bc06-8cf3e644ab24

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
</pre>
- Operating system: linux
- Telescope commit: b82d6a7

</details>

**Comment by Conni2461** [comment]
There was a time where i could reproduce this but i just rechecked and i can't.
@urandom can you check if this still happens. Thanks :)

**Comment by urandom** [comment]
@Conni2461 
Unfortunately, it's still happening with 8369ace

**Comment by Conni2461** [comment]
I still wasn't been able to reproduce this over the last year. Telescope changed significantly over this time period so i am closing this issue.

This might still be an issue for you. Sadly at the time of creating this issue we had a pretty minimal issue template which changed in the last few months, and we now require a minimal config, which helps us reproduce issues like that.

So if this is still a thing for you i kindly ask you to create a new issue thanks :)
