### ISSUE TITLE
Buffers Picker ignores sort_lastused option after typing input

### ISSUE THREAD

**Issue by relnod** [nvim-telescope/telescope.nvim#451]
### Description
When using the internal buffers picker with the option `sort_lastused = true`, the lastused sorting only gets applied in the beginning, before any input was typed.

**Expected Behavior**
Even when typing some characters, the sorting should still be lastused, as configured. The input should only filter the result.

**Actual Behavior**
When typing character, the lastused sorting is not applied anymore.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :e foo
3. :e foo2
4. :e barfoo
5. :e foobar
6. :lua require("telescope.builtin").buffers({ sort_lastused = true, ignore_current_buffer = true })
7. the order is now "barfoo", "foo", "foo2"
8. type "foo"
9. the order is now "foo", "foo2", "barfoo"
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/6r1zcjrxphs5ayn41smkn18p3ng08254-neovim-nightly-master/share/nvim"

Run :checkhealth for more info
```
- Operating system: 
```
Linux noone 5.4.87 #1-NixOS SMP Wed Jan 6 13:48:41 UTC 2021 x86_64 GNU/Linux
```
- Telescope commit: 
```
b82d6a7
```

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}

**Comment by Conni2461** [comment]
Not really a bug more like a question :) Thats expected behaivor, `sort_lastused = true` only affects the initial sorting, after that the fuzzy finder is responsible for sorting. So `foo` has just the highest score.

What you could do right now is use the substring sorter which will give you the expected result, but that one isn't fuzzy:
```
:lua require("telescope.builtin").buffers({ sort_lastused = true, ignore_current_buffer = true, sorter = require'telescope.sorters'.get_substr_matcher() })
```

**Comment by relnod** [comment]
Thanks for the quick answer :) Changing the sorter as you suggested works perfectly!

The only thing I'm wondering is, if we could set `ignore_current_buffer = true` and `sorter = require'telescope.sorters'.get_substr_matcher()` if the options `sort_lastused = true` was set, providing a "better" default experience for the `sort_lastused = true`  use case. But maybe it's only me who would expects this behaviour.

Anyway, I'm closing this, since it's now working for me!

**Comment by Conni2461** [comment]
I requested it in our better default experience issue for 1.0 release.
