### ISSUE TITLE
Have an actions.select

### ISSUE THREAD

**Issue by Conni2461** [nvim-telescope/telescope.nvim#461]
Have an `actions.select` to replace `_goto_file_selection` as default actions so `actions.select:replace` is more intuitive. 

CC @anott03

**Comment by anott03** [comment]
Is this only for  the "edit" command? Right now it seems to me I should define the function select
```lua
function actions.select(bufnr)
    actions._goto_file_selection(bufnr, "edit")
end
```
and then use this to replace the current mapping for `<CR>`. Does that sound correct, or is there more to it than that?

**Comment by tami5** [comment]
> Is this only for  the "edit" command? Right now it seems to me I should define the function select
> 
> ```lua
> 
> function actions.select(bufnr)
> 
>     actions._goto_file_selection(bufnr, "edit")
> 
> end
> 
> ```
> 
> and then use this to replace the current mapping for `<CR>`. Does that sound correct, or is there more to it than that?

🤔🤔 not sure what you mean here. But we can check out action.mt. Also grep over for the old keywords and replace them with the new ones.

I suggest 

- select 
- vselect
- hselect 
- tselect 

cc @Conni2461

**Comment by Conni2461** [comment]
If i recall correctly the idea was to have `<CR>` be mapped to `actions.select` so its a more intuitive default and people are understanding what they actually replace :)

I wouldn't rename all functions that would break compatibility with all extensions. I would introduce the function like that `goto_file_selection_edit` will be a alias and rename all internal use of `goto_file_selection_edit` to `select`

**Comment by tami5** [comment]
hmm then i'm not sure what @tjdevries meant
