### ISSUE TITLE
feat: Normal mode: Walking multiple steps at once (ie 5j or 5k)

### ISSUE THREAD

**Issue by matu3ba** [nvim-telescope/telescope.nvim#466]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to type single j and k to walk inside the editor, so I always do 5j,5k etc for navigation.
However, in normal mode I can not use 5j or 5k to walk 5 steps down and up.

**Describe the solution you'd like**
I would like to have the same walking behavior like (neo)vim, wher you can use 5j and 5k (after changing to normal mode) for walking 5 steps down and up.

**Describe alternatives you've considered**
I think the default behavior of neovim should be represented, if feasible, to reduce learning or configuration need.

**Comment by Conni2461** [comment]
Dup of #403 
Opened PR 463 yesterday

**Comment by matu3ba** [comment]
Sorry for the noise then. Feel free to close.
