### ISSUE TITLE
Ultisnips List Snippets builtin

### ISSUE THREAD

**Issue by daveb68** [nvim-telescope/telescope.nvim#467]
It would be great to see an Ultisnips list available snippets builtin that previewed the snippet.

**Comment by Conni2461** [comment]
We have that for [snippets.nvim](https://github.com/norcalli/snippets.nvim) [here](https://github.com/nvim-telescope/telescope-snippets.nvim).

I don't use Ultisnips so i can't build it but it should be very similar to that implementation.

**Comment by tjdevries** [comment]
Sorry, this would have to be in another repo. Generally, any extensions that require anything else to be installed would live in one of the extension repos.

Thanks for the suggestion tho!

**Comment by fhill2** [comment]
@daveb68 check out [telescope-ultisnips.nvim](https://github.com/fhill2/telescope-ultisnips.nvim)
