### ISSUE TITLE
docs: File Picker: options to search also 1.gitignore, 2. hidden files, 3.binary files

### ISSUE THREAD

**Issue by matu3ba** [nvim-telescope/telescope.nvim#470]
**Is your feature request related to a problem? Please describe.**
I can not search through files in git submodules, because they are part of the `.gitignore`. All file pickers ignore the files that are part of `.gitignore`.

**Describe the solution you'd like**
ripgrep has the option `-u` to do the search more unrestricted and I would favor a similar solution:
```txt 
-u, --unrestricted
            Reduce the level of "smart" searching. A single -u won't respect .gitignore
            (etc.) files. Two -u flags will additionally search hidden files and
            directories. Three -u flags will additionally search binary files.
```
So something like `:Telescope picker -u` or `:Telescope picker u`.
Probably the option can be adadpted for other pickers, but I did not saw very useful ones yet.

**Describe alternatives you've considered**
Manually specifying APIs is too cumbersome for such a feature. 

**Additional context**
Documentation should mention what things are ignored __xor__ how to enable things. 
There is only `builtin.live_grep | Searches in current directory files. (respecting .gitignore)`, which looks like a rather exclusive behavior of the picker.

**Comment by Conni2461** [comment]
I don't see any restrictions because you can configure the grep command like you want :) We are merely describing the default.

You can either configure the default so it always applies
```lua
require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case',
      '-u' -- thats the new thing
    },
}
```

Or per finder run `:lua require'telescope.builtin'.live_grep{ vimgrep_arguments = { 'rg', '--color=never', '--no-heading', '--with-filename', '--line-number', '--column', '--smart-case', '-u' } }`

Btw thats documented [here](https://github.com/nvim-telescope/telescope.nvim#telescope-defaults) and [here](https://github.com/nvim-telescope/telescope.nvim#options-affecting-sorting).

If you have any suggestions for better documentation feel free to mention them :)

**Comment by Conni2461** [comment]
I am closing this. Its doable, its documented and after #370 is merged everything should be fine

**Comment by EduardGol** [comment]
> I don't see any restrictions because you can configure the grep command like you want :) We are merely describing the default.
> 
> You can either configure the default so it always applies
> 
> ```lua
> require('telescope').setup{
>   defaults = {
>     vimgrep_arguments = {
>       'rg',
>       '--color=never',
>       '--no-heading',
>       '--with-filename',
>       '--line-number',
>       '--column',
>       '--smart-case',
>       '-u' -- thats the new thing
>     },
> }
> ```
> 
> Or per finder run `:lua require'telescope.builtin'.live_grep{ vimgrep_arguments = { 'rg', '--color=never', '--no-heading', '--with-filename', '--line-number', '--column', '--smart-case', '-u' } }`
> 
> Btw thats documented [here](https://github.com/nvim-telescope/telescope.nvim#telescope-defaults) and [here](https://github.com/nvim-telescope/telescope.nvim#options-affecting-sorting).
> 
> If you have any suggestions for better documentation feel free to mention them :)

Where i must to put this function ?
I don't find anywhere. I have tried to put in init.vim, but are crushing.

**Comment by ishaan-kapoor** [comment]
this is lua code and is compatible with neovim and its derivatives.

**Comment by RheaAyase** [comment]
That's nice that you "can achieve it" but it's very difficult even for quite experienced engineers to figure out "how" to do that. This restrictive default is not useful. Last week I spent ages trying to get it to show hidden files, now I have a problem with gitignore. You will simply go through all of these being an issue sooner or later.

In this instance, having miraculously found this ticket to get at least some idea of what to do, still can't achieve what i need to achieve - to edit anything without arbitrary explicit limits that should not exist and are not default behaviour in linux. Can I do `cat file` on a file that's hidden, or in .gitignore, without any additional configuration? Yes. Can I do that in neovim? No. Wrong user experience, inconsistent, and definitely not what most people need to do.

I'd strongly suggest making the default less limiting. Everywhere - the same limitations apply to many features.

Anyway. The above suggestion for vimgrep args doesn't do the trick at all. Probably outdated info.
