### ISSUE TITLE
lsp_document_symbols are not working when buffer is not saved

### ISSUE THREAD

**Issue by rustiever** [nvim-telescope/telescope.nvim#476]
### Description
lsp_document_symbols are not working when buffer is not saved, when I open lsp_document_symbols preview window is opening, but the when I want to jump to some symbol it doesn't work unless it is a saved buffer.
But when I save the file or buffer it works as expected

**Expected Behavior**
should jump to the symbol

**Actual Behavior**
E5108: Error executing lua ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:127: Vim(edit):E37: No write since last change (add ! to override)
Press ENTER or type command to continue

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :Telescope lsp_document_symbols
3. and here you'll get the error like this
4. E5108: Error executing lua ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:127: Vim(edit):E37: No write since last change (add ! to override)
Press ENTER or type command to continue
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+nightly
Build type: Release
LuaJIT 2.1.0-beta3
- Operating system: Mac OS
- Telescope commit: 9d4670c

</details>

<details><summary>Configuration</summary>
<p>

```viml
" Find files using Telescope command-line sugar.
nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>

" only i use this much from telescope plugin
```

**Comment by Conni2461** [comment]
We are not allowed to run edit, when `filename = current_buffer_name`. The check is already there but its broken due to some other changes.
Thats a good first issue.

If someone wants to look at it: `actions/init.lua`: `_goto_file_selection` is the function you wanna look at :)

If #472 is already merged you want to look at `actions/set.lua` `edit`
