### ISSUE TITLE
Slow to change buffer 

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [nvim-telescope/telescope.nvim#477]
### Description

When running `:Telescope find_files` in a rust src directory (with rust-analyzer LSP) there is a substantial delay between the time a files is selected and when the buffer switches. The actually loading of the popup and previews is very fast though.

**Expected Behavior**

I expect buffer switching to be mostly instantaneous

**Actual Behavior**

It takes 3-4 seconds before buffer switches.

### Details

<details><summary>Reproduce</summary>

1.  git clone https://github.com/davidpdrsn/witter.git && cd witter
2. nvim -nu min.lua witter-backend/src/main.rs
3. :Telescope find_files
</details>

<details><summary>Environment</summary>

- nvim --version output: v0.5.0-dev+1055-g8950f4e94
- Operating system:  Arch Linux
- Telescope commit: 9d4670c

</details>

<details><summary>Configuration</summary>
<p>

```lua
require('telescope').setup{
    defaults = {
      vimgrep_arguments = {
        'rg',
        '--color=never',
        '--no-heading',
        '--with-filename',
        '--line-number',
        '--column',
        '--smart-case'
      },
      prompt_position = "bottom",
      prompt_prefix = ">",
      initial_mode = "insert",
      selection_strategy = "reset",
      sorting_strategy = "descending",
      layout_strategy = "horizontal",
      layout_defaults = {
        -- TODO add builtin options.
      },
      file_sorter =  require'telescope.sorters'.get_fuzzy_file,
      file_ignore_patterns = {"target"},
      generic_sorter =  require'telescope.sorters'.get_generic_fuzzy_sorter,
      shorten_path = true,
      winblend = 0,
      width = 0.75,
      preview_cutoff = 120,
      results_height = 1,
      results_width = 0.8,
      border = {},
      borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
      color_devicons = true,
      use_less = true,
      set_env = { ['COLORTERM'] = 'truecolor' }, -- default { }, currently unsupported for shells like cmd.exe / powershell.exe
      file_previewer = require'telescope.previewers'.cat.new, -- For buffer previewer use `require'telescope.previewers'.vim_buffer_cat.new`
      grep_previewer = require'telescope.previewers'.vimgrep.new, -- For buffer previewer use `require'telescope.previewers'.vim_buffer_vimgrep.new`
      qflist_previewer = require'telescope.previewers'.qflist.new, -- For buffer previewer use `require'telescope.previewers'.vim_buffer_qflist.new`
  
      -- Developer configurations: Not meant for general override
      buffer_previewer_maker = require'telescope.previewers'.buffer_previewer_maker
    }
}

if vim.fn.executable("rust-analyzer") > 0 then
    require('lspconfig').rust_analyzer.setup {
        checkOnSave = {
            command = "clippy"
        },
    }
end
```

**Comment by Conni2461** [comment]
Its instant without `rust-analyzer` and slow with it. We can't really do anything against that.
All we do is `:new file`.

**Comment by Th3Whit3Wolf** [comment]
Is there another way to make it faster? Vim-clap is instant regardles

**Comment by Conni2461** [comment]
https://github.com/liuchengxu/vim-clap/blob/c6ed3de48693d754ef47ec9422ecb065200f8a70/autoload/clap/sink.vim#L12

Clap kinda does the same. I can even reproduce that lag when opening the file with `:e backend/src/clock.rs`. So i am kinda lost here

**Comment by Th3Whit3Wolf** [comment]
Is there any process that happens between the time the file is chosen and when edit happens?

**Comment by Th3Whit3Wolf** [comment]
You are right. it is related to rust-analyzer lsp. Not sure why vim-clap opens faster. Closing now.
