### ISSUE TITLE
Add small improvement to the attach_mappings documentation

### ISSUE THREAD

**Issue by StenSipma** [nvim-telescope/telescope.nvim#480]
**Is your feature request related to a problem? Please describe.**
It is easy to miss the `return true` line inside the function which is used to extend the default mapping using `attach_mappings`.

**Describe the solution you'd like**
Maybe add a small comment or note to this example that it is required to add this return statement! [Link to the example in the readme](https://github.com/nvim-telescope/telescope.nvim#picker)

Maybe something like, but of course I don't know if that is factually accurate ^^
```lua
function my_custom_picker(results)
  pickers.new(opts, {
    prompt_title = 'Custom Picker',
    finder = finders.new_table(results),
    sorter = sorters.fuzzy_with_index_bias(),
    attach_mappings = function(_, map)
      -- Map "<CR>" in insert mode to the function, actions.set_command_line
      map('i', '<CR>', actions.set_command_line)

      -- Makes sure that the other defaults are still applied
      return true
    end,
  }):find()
end
```

**Comment by Conni2461** [comment]
Thanks :) i passed it on to the current actions improvement PR #472

**Comment by StenSipma** [comment]
Cool! :+1:

**Comment by tjdevries** [comment]
Maybe we should assert that attach mappings returns _something_. We can `assert(result ~= nil, "'attach_mappings" must return a value')`

**Comment by Conni2461** [comment]
Tj implemented that assert. Closing for now
