### ISSUE TITLE
Telescope find_files resetting indentexpr set by treesitter

### ISSUE THREAD

**Issue by yzia2000** [nvim-telescope/telescope.nvim#481]
I want to use treesitter indentations. However, when I open a file using `:Telescope find_files` or a grep command, it resets the indentexpr to a vim runtime default. For example when opening a javascript file this way, the `indentexpr=GetJavascriptIndent()` from $runtime/indents/javascript.vim instead of `indentexpr=nvim_treesitter#indent()`. This does not occur when I open the files directly through `nvim *.js` or `:e path/to/*.js`.
Please assist me.

**Comment by elianiva** [comment]
You could try to use this

```viml
au Filetype * set indentexpr=nvim_treesitter#indent()
```

I use that because there are other reasons that resets the `indentexpr` other than Telescope (which I'm not entirely sure, this solution works for me so I couldn't be bothered to debug it :laughing:)

**Comment by yzia2000** [comment]
Haha. I have been trying to do that too but it seems more like a bypass than a fix and my inner OCD gets the best of me. I was hoping that someone could explain to me how indentations work in Telescope to see if I could fix this myself.

**Comment by elianiva** [comment]
I think it's because how `indentexpr` being a local buffer variable. It gets overriden when you open any file using `:edit` or `:buffer`. It's strange that you don't have this issue when you do `:e filename` manually because I do.

**Comment by yzia2000** [comment]
> I think it's because how `indentexpr` being a local buffer variable. It gets overriden when you open any file using `:edit` or `:buffer`. It's strange that you don't have this issue when you do `:e filename` manually because I do.

Do you perhaps have `filetype syntax indent on` in your init.vim?

**Comment by elianiva** [comment]
> > I think it's because how `indentexpr` being a local buffer variable. It gets overriden when you open any file using `:edit` or `:buffer`. It's strange that you don't have this issue when you do `:e filename` manually because I do.
> 
> Do you perhaps have `filetype syntax indent on` in your init.vim?

Nope, I don't have that.

**Comment by yzia2000** [comment]
I see. That is surprising because I only encounter the issue when using telescope haha

**Comment by Conni2461** [comment]
Wild guess

https://github.com/nvim-telescope/telescope.nvim/blob/fc54211868fcca8e53fec7071b3fab3591d250da/lua/telescope/actions/init.lua#L139

Removing that line. Does that fix the issue? We just need that so filetype autocommands run.
So stuff like

```
au Filetype cpp setlocal ...
```

works

**Comment by elianiva** [comment]
Same here, removing that line doesn't seem to change anything. The `Filetype` autocommands still get executed.

**Comment by yzia2000** [comment]
> Wild guess
> 
> https://github.com/nvim-telescope/telescope.nvim/blob/fc54211868fcca8e53fec7071b3fab3591d250da/lua/telescope/actions/init.lua#L139
> 
> Removing that line. Does that fix the issue? We just need that so filetype autocommands run.
> So stuff like
> 
> ```viml
> au Filetype cpp setlocal ...
> ```
> 
> gets run.
> 
> Edit: Or at least that was the case a while ago. Maybe the bug was fixed upstream, because right now i no longer need it thinking

Actually that is exactly what solved the issue for me.

**Comment by elianiva** [comment]
Then I guess we should remove that line? Since it fixes @yzia2000's issue and it doesn't break anything (as far as I'm aware).

**Comment by Conni2461** [comment]
Was applied https://github.com/nvim-telescope/telescope.nvim/pull/283 and should fix that issue https://github.com/nvim-telescope/telescope.nvim/issues/115

So we would need to ask @mhartington if he could confirm that fold still work even without that line. For me they do. What folds currently break is the `actions.center` which i don't understand 😕

**Comment by mhartington** [comment]
So I tested this with and without the `filetypedetect` autocmd, but it didn't seem to change things. Even with `indentexpr="nvim_treesitter#indent()"` being set as a buffer option, it looks like it gets reset by any filetype plugin that could exist. 

Not sure if the filetypedetect bit actually is the culprit here.

**Comment by yzia2000** [comment]
Its getting set by `/usr/share/nvim/runtime/indent/javascript.vim` for me when I do `:verbose setlocal indentexpr` for example with js. I dont have an autocmd for `nvim_tresitter#indent()` which is why it is probably not getting overridden.

**Comment by yzia2000** [comment]
Also, I cannot use `au Filetype * setlocal indentexpr=nvim_treesitter#indent()` because nvim_treesitter does not indentation support for all languages and I would prefer not to have set them individually for each file.

**Comment by yzia2000** [comment]
Hi my PR to treesitter got merged so this issue is not a problem. However, please do think about removing the line if it no longer poses an issue.
