### ISSUE TITLE
E475 Invalid argument when searching in files

### ISSUE THREAD

**Issue by cafce25** [nvim-telescope/telescope.nvim#484]
### Description

Any call to `:Telescope <finder>` where finder is any one that accesses file system (`find_files`, `live_grep`, ...)

**Expected Behavior**

Starts a telescope search for the respective finder.

**Actual Behavior**

After first file system access (I suspect, immediately for `find_files`, after the first character typed for `live_grep`):

`Error executing vim.schedule lua callback: Vim:E475: Invalid argument: env`

Cursor moves from input to preview.
The search windows remain floating and i can now type in preview.

### Details

<details><summary>Reproduce</summary>

1.  Be in a folder with files in it (current directory, any subdirectory)
2.  nvim -nu test.vim
3.  :Telescope live_grep or find_files or ...
4.  if in live_grep press any character to start search
5.  ... error

</details>

<details><summary>Environment</summary>
- nvim --version:

```
NVIM v0.5.0-dev+1061-ge85c8dff6
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/jona/aur/neovim-git/src/build/config -I/home/jona/aur/neovim-git/src/neovim-git/src -I/usr/include -I/home/jona/aur/neovim-git/src/build/src/nvim/auto -I/home/jona/aur/neovim-git/src/build/include
Compiled by jona@alcyone

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system: Arch linux
- Telescope commit: ef3262f

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by kristijanhusak** [comment]
Anyone know how to get around this? I tried checking out older commit, but issue still persist.

**Comment by peacock0803sz** [comment]
Hi, I have reproduced the same thing.
But it resolved add `set_env = { ['COLORTERM'] = 'truecolor' },` into setup function.
I'll paste my vimrc link. https://github.com/peacock0803sz/dotfiles/blob/master/.config/nvim/init.vim#L221

By the way, my environment is here.

```
$ nvim -v
NVIM v0.5.0-dev+1062-gcc1851c9f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

OS: Arch Linux (Gnome)
Terminal: Tilix version 1.9.1

I hope this helps you.

**Comment by Conni2461** [comment]
Oh that yeah that issue is because our env workaround got fixed yesterday in neovim. https://github.com/nvim-telescope/telescope.nvim/pull/482 Will fix that issue.

I can merge immediately i just wanted to wait until some more people have build the new version :)
