### ISSUE TITLE
Buffer previewers have no fallback highlight if Treesitter is disabled for a filetype

### ISSUE THREAD

**Issue by akinsho** [nvim-telescope/telescope.nvim#493]
### Description

Whilst using buffer previewers, when I have `nvim-treesitter` installed but have deactivated highlights for a specific filetype the buffer does not fallback to regex highlighting. 

**Expected Behavior**

If treesitter highlighting isn't available for a filetype buffer previewers should fallback to regex highlighting instead. Since treesitter support isn't stable yet and would be dependent on there being support even if it were it seems likely that many users will find themselves searching through files that treesitter doesn't support. In those cases rather than no highlighting I wonder if it would be possible to fall back to regex highlighting.

**Actual Behavior**

![telescope-highlight](https://user-images.githubusercontent.com/22454918/106660448-e7e5db80-6597-11eb-888b-8285d1d42dc2.gif)
### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :Telescope find_files
3.  Search for a filetype you have disabled in your treesitter config
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-HUQB5O/neovim-0.5.0+ubuntu2+git202102020036-cc1851c9f-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-HUQB5O/neovim-0.5.0+ubuntu2+git202102020036-cc1851c9f-d569569c9/build/config -I/build/neovim-HUQB5O/neovim-0.5.0+ubuntu2+git202102020036-cc1851c9f-d569569c9/src -I/build/neovim-HUQB5O/neovim-0.5.0+ubuntu2+git202102020036-cc1851c9f-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-HUQB5O/neovim-0.5.0+ubuntu2+git202102020036-cc1851c9f-d569569c9/build/src/nvim/auto -I/build/neovim-HUQB5O/neovim-0.5.0+ubuntu2+git202102020036-cc1851c9f-d569569c9/build/include
Compiled by buildd@lcy01-amd64-029

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system: 
- Telescope commit: 

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF
  require "nvim-treesitter.configs".setup {
    ensure_installed = "maintained",
    highlight = {
      enable = true,
      disable = {"<FILETYPE-TO-TEST>"}
    },
}

local previewers = require("telescope.previewers")

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
    file_previewer = previewers.vim_buffer_cat.new,
    grep_previewer = previewers.vim_buffer_vimgrep.new,

  }
}
EOF
```

**Comment by Conni2461** [comment]
Actually it does but we can't detect the filetype with autocmds, was way too slow, so we guess it based on the file extension. More info [here](https://github.com/nvim-telescope/telescope.nvim#previewers).
For dart we probably just miss the entry in the table. Our script that generated that table missed some values because we don't have a good enough file that list all file extensions vim filetypes correlation 😆.

So you can set it up yourself locally. For more information read [this](https://github.com/nvim-lua/plenary.nvim#plenaryfiletype)

**Comment by akinsho** [comment]
@Conni2461 thanks for the explanation and the links, I'll give those a try and if it works will open a PR with plenary to add the `dart` filetype to the guesser.

**Comment by Conni2461** [comment]
Feel free to do that but put them into `data/plenary/filetypes/builtin.lua` not `base.lua`. Thats the autogenerated one :)

**Comment by akinsho** [comment]
Thanks for the heads up 👍🏿  will close this out now since I have a solution
