### ISSUE TITLE
Option to escape telescope from insert mode

### ISSUE THREAD

**Issue by beauwilliams** [nvim-telescope/telescope.nvim#495]
This is not a problem, but more of a preference coming from FZF

I would like to be able to open for example file search, and then hit escape to close the window

I have tried to remap, in various ways but have yet to have success.. eg.

  `au FileType * tnoremap <Esc> <Esc><Esc>`

**Comment by sunjon** [comment]
Configuration of mappings is described [here](https://github.com/nvim-telescope/telescope.nvim#mappings)
For what you want, try the following in your setup call:

```
  telescope.setup {
    defaults = {mappings = {i = {["<esc>"] = actions.close, }}},
  }
```

**Comment by beauwilliams** [comment]
Hold on, I have it working   au FileType * imap <Esc> <C-c> 
But I will try your suggestion above. Thanks! Probably spoke too soon 😀

**Comment by beauwilliams** [comment]
> Configuration of mappings is described [here](https://github.com/nvim-telescope/telescope.nvim#mappings)
> For what you want, try the following in your setup call:
> 
> ```
>   telescope.setup {
>     defaults = {mappings = {i = {["<esc>"] = actions.close, }}},
>   }
> ```

This works. Thankyou.

_**Note for future viewers**, you will need to make a local var by placing this line at top for the actions global `local actions = require('telescope.actions')`

**Comment by YodaEmbedding** [comment]
How does one switch to normal mode? I'd like to swap the default mappings.

```
telescope.setup {
  defaults = {
    mappings = {
      i = {
        ["<Esc>"] = actions.close,
        ["<C-c>"] = actions.switch_to_normal_mode,
      },
    },
  },
}
```

**Comment by Conni2461** [comment]
```lua
telescope.setup {
  defaults = {
    mappings = {
      i = {
        ["<Esc>"] = actions.close,
        ["<C-c>"] = function()
          vim.cmd [[stopinsert]]
        end,
      },
    },
  },
}
```
