### ISSUE TITLE
How do I map `<C-u>` to clear current prompt?

### ISSUE THREAD

**Issue by jrop** [nvim-telescope/telescope.nvim#499]
**Is your feature request related to a problem? Please describe.**

In insert mode, an common mapping to clear the current prompt in any readline-program is `<C-u>`.

**Describe the solution you'd like**

```lua
require('telescope').setup{
  defaults = {
    mappings = {
      i = {
        ['<C-u>'] = some_action_to_clear_current_prompt_how_do_i_do_this
      }
    }
  }
}
```

**Describe alternatives you've considered**

I looked through the source (a low-effort scan, admittedly), and could not find an obvious way to do this, nor did any predefined action seem to accomplish what I wanted.

**Additional context**

None

**Comment by Conni2461** [comment]
This is possible without a new action. Currently it doesn't work because `<C-u>` is mapped to scrolling up. So after disabling this mapping this should work.
```lua
require('telescope').setup{
  defaults = {
    mappings = {
      i = {
        ['<C-u>'] = false,
      }
    }
  }
}
```

**Comment by jrop** [comment]
@Conni2461 That did the trick.  Thank you very much.

**Comment by genmzy** [comment]
How about to <c-a> mapping to <Home> (this is not a default behavior of command)  and <c-e>(defaul beavior of vim command) mapping to <End>  ???

**Comment by jamestrew** [comment]
@genmzy neither of those are vim defaults I don't think but none the less you can do something like this
```lua
require("telescope").setup({
  defaults = {
    mappings = {
      i = {
        ["<C-a>"] = {"<home>", type = "command"},
        ["<C-e>"] = {"<end>", type = "command"},
      },
    },
  },
})
```
