### ISSUE TITLE
Scroll lines in the preview window

### ISSUE THREAD

**Issue by delphinus** [nvim-telescope/telescope.nvim#500]
**Is your feature request related to a problem? Please describe.**

Scroll lines when I input `<C-d>`/`<C-u>` is hard-coded to 30 lines [here][]. Should this be configurable?

[here]: https://github.com/nvim-telescope/telescope.nvim/blob/5f1d16acf6716261bd52466733e096a49b9eadad/lua/telescope/actions/init.lua#L61

**Describe the solution you'd like**

1. Add a config value (such as `conf.scroll_lines`).

   ```lua
   require'telescope'.setup{
     defaults = {
       ...
       scroll_lines = 30,
       ...
     },
   }
   ```

2. If this value is not set, it should fallback the value from `'scroll'` option, or the half of the preview window's height.

**Describe alternatives you've considered**

**Additional context**

Anyway, I'll make PR later for this logic.

**Comment by elianiva** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/405#issuecomment-757117454 (related)

**Comment by delphinus** [comment]
@Conni2461 You say in that comment, it should be set different scroll amount for "horizontal" or "vertical" strategies?

**Comment by Conni2461** [comment]
I just thought this should be part of layout, like different layouts different needs :)
But fallback to preview_win height sounds cool as well

This works for me (`buffer_previewers`) but i don't see why it should work with `term_previewers` as well

```diff
diff --git a/lua/telescope/actions/init.lua b/lua/telescope/actions/init.lua
index 4e82777..8282476 100644
--- a/lua/telescope/actions/init.lua
+++ b/lua/telescope/actions/init.lua
@@ -58,11 +58,13 @@ function actions.get_current_line()
 end
 
 function actions.preview_scrolling_up(prompt_bufnr)
-  actions.get_current_picker(prompt_bufnr).previewer:scroll_fn(-30)
+  local lines = vim.api.nvim_win_get_height(state.get_status(prompt_bufnr).preview_win)
+  actions.get_current_picker(prompt_bufnr).previewer:scroll_fn(-(lines / 2))
 end
 
 function actions.preview_scrolling_down(prompt_bufnr)
-  actions.get_current_picker(prompt_bufnr).previewer:scroll_fn(30)
+  local lines = vim.api.nvim_win_get_height(state.get_status(prompt_bufnr).preview_win)
+  actions.get_current_picker(prompt_bufnr).previewer:scroll_fn(lines / 2)
 end
 
 -- TODO: It seems sometimes we get bad styling.
 ```

**Comment by Conni2461** [comment]
@elianiva Implemented this in https://github.com/nvim-telescope/telescope.nvim/commit/6e941e0ecec1ab6a1b4ce40c693ef1272c505abb

Closing
