### ISSUE TITLE
unable to choose files from previous directory using find_files()

### ISSUE THREAD

**Issue by saahiluppal** [nvim-telescope/telescope.nvim#502]
If i am in particular directory and hit find_files(), opened window will only allow to choose files from current directory onwards and unable to choose files from previous directory.

For example with this file structure:
```
--> home
      --> folder1
            --> main.py
            --> test.py
      --> folder2
      --> file.py
      --> file.txt
```
if i am in folder1 and using nvim and use find_files(), i can only access (main.py and test.py), but what if i need to access file.py or file.txt?

**Comment by Conni2461** [comment]
You can't do this within `find_files` but you can do `Telescope find_files cwd=..` for example to go one up or pass in a absolute path.

I am also working on a more traditional #290 which lets you navigate up and down the directory tree and will only show you the current directory. See https://streamable.com/v79mjb

**Comment by gennaro-tedesco** [comment]
I would also support the idea to add an option to `find_files` that defaults to the (project) git root: this is generally the location most people search files in, it is very unlikely that one is interested in the files of the current sub-directory only. It is true that one can pass an option `Telescope find_files cwd=..`, however in a big project you do not really know where exactly you are located (and therefore how many "steps back" you need to project root), whereas by defaulting to the project directory you are where you want more often than not.

For instance `fzf` [implements it](https://github.com/junegunn/fzf.vim/issues/47#issuecomment-160237795) and so do other file pickers. Even if not by default, it can be an extreme win to just have the user specify it with one little parameter only (say `nnoremap <mapping> Telescope find_files(git)<cr>`).

**Comment by Conni2461** [comment]
Okay that is not really implemented, it is just supported that you can easily write this function yourself. :)
```lua
M.my_fd = function(opts)
  opts = opts or {}
  opts.cwd = vim.fn.systemlist("git rev-parse --show-toplevel")[1]
  require'telescope.builtin'.find_files(opts)
end
```

Also you can take a look at `Telescope git_files` which will run on git root.

**Comment by gennaro-tedesco** [comment]
This will do, thanks for the hint!

**Comment by Conni2461** [comment]
@saahiluppal I have no idea what you expect more from this. You can define your cwd however you want.

Closing for now. Feel free to reopen if I haven't answered everything to your liking.
