### ISSUE TITLE
Buffer previewer throws Index out of bounds when opening python files

### ISSUE THREAD

**Issue by yujinyuz** [nvim-telescope/telescope.nvim#503]
### Description

Buffer previewers throw errors. Not really sure if it's an issue in nvim-treesitter or telescope but if I open a file directly e.g. `nvim path/to/file.py`, I don't get any errors.

When opening python files, I get:
Error executing vim.schedule lua callback: ...7/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:255: Index out of bounds

Here's a screencast
[![asciicast](https://asciinema.org/a/4pvyihsaiIhEYeIT7oBL4lJ3L.svg)](https://asciinema.org/a/4pvyihsaiIhEYeIT7oBL4lJ3L)

**Expected Behavior**

There shouldn't be any errors

**Actual Behavior**

Throwing Index out of bounds error

### Details

<details><summary>Reproduce</summary>

Search for a python file

1. nvim -nu test.vim
2. Telescope find_files
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- Telescope commit: 

</details>

<details><summary>Configuration</summary>
<p>

```viml
set packpath=""
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-treesitter/nvim-treesitter'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
nnoremap <C-p> <cmd>Telescope find_files<CR>
lua << EOF

require('nvim-treesitter.configs').setup {
  ensure_installed = "maintained",
  highlight = { enable = true },
}

local previewers = require('telescope.previewers')
require('telescope').setup{
  defaults = {
    file_previewer = previewers.vim_buffer_cat.new,
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}


EOF
```

**Comment by elianiva** [comment]
Seems like an issue from Treesitter doing `rst` injection on `python` file? Because the injection uses `offset` which might cause an issue, not sure though. Just a wild guess. Also, I found this comment on `languagetree.lua`

```
-- TODO(vigoux): proper byte computation here, and account for EOL ?
```

I've tried removing the injection for Python, the error seems to be gone after doing that.

**Comment by Conni2461** [comment]
We only attach a ts parser so if you are getting a treesitter error its them. I think you would get this error even when just opening the file with `:e`

What i am currently thinking is pcall ing the attach function so that we at least don't "kill" telescope

**Comment by elianiva** [comment]
> We only attach a ts parser so if you are getting a treesitter error its them. I think you would get this error even when just opening the file with `:e`
> 
> What i am currently thinking is pcall ing the attach function so that we at least don't "kill" telescope

Though I didn't get any error if I open the file using `:e`, I'm not sure why TS behave differently inside Telescope preview

**Comment by Conni2461** [comment]
Could you pcall 
https://github.com/nvim-telescope/telescope.nvim/blob/5f1d16acf6716261bd52466733e096a49b9eadad/lua/telescope/previewers/utils.lua#L86
And try again if we get the error.

Especially move to the same file multiple times. :) Thanks elianiva

**Comment by elianiva** [comment]
>  ts_highlight.attach(bufnr, lang)

That works, the previewer doesn't get highlighted but it doesn't break Telescope

**Comment by Conni2461** [comment]
Hmm okay if ts errors we don't get highlighting. 🤔 
Let me think about this for day or so.

It might be weird for some people. "Why is python file a highlighted but b not. These buffer previewers s###" 🤣

**Comment by elianiva** [comment]
Yeah, the issue only occur if the `python` file has a docstring which is injected with the `rst` parser

**Comment by Conni2461** [comment]
@elianiva How about this: we do pcall and if we fail we print, (tree-sitter failed) and fallback to regex?

**Comment by elianiva** [comment]
agree, falling back to regex seems like a good idea for the time being.

**Comment by elianiva** [comment]
FWIW this also happens to any injection that uses offset predicate (which confirms my previous thought), just got this issue in graphql injection because it also uses offset predicate. Still unsure why TS treats Telescope preview buffer differently than a regular buffer.

**Comment by Conni2461** [comment]
That bug is the one that keeps me up at night :rofl: If it wasn't for that i would have made buffer previewer already default. Let me look at some neovim code i have no idea about :)

Thanks for the offset predicate hint :)

We are looking at the line: 
```lua
          local start_byte = a.nvim_buf_get_offset(self.bufnr, start_row) + start_col
```

self.bufnr is nil. Which shouldn't happen so i think i just have to track that down :)

**Comment by Conni2461** [comment]
HYPE fixed it.
Opening a neovim PR. :)

**Comment by Conni2461** [comment]
Fixed in core :)
