### ISSUE TITLE
live_grep not working...

### ISSUE THREAD

**Issue by wantyapps** [nvim-telescope/telescope.nvim#504]
### Description

When trying to open live_grep and type a random letter like `a` this error appears:
```
[telescope] ^I...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:451: in function <...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:413>```
**Expected Behavior**
<!-- what is the Expected Behaviour in the steps you've defined above? -->
live_grep working
**Actual Behavior**
<!-- what is the Actual Behaviour your getting from the steps you've defined above? -->
An error at the bottom of Neovim
### Details

<!-- Steps to reproduce -->
<details><summary>Reproduce</summary>

<!--
Example:

1. nvim -nu test.vim
2. :Telescope live_grep or git_commits
3. .... bang here is the issue
...
-->

1. nvim -nu test.vim
2. :Telescope live_grep
3. Type a letter
</details>

<!-- Environment Information -->
<details><summary>Environment</summary>

<!--
- nvim --version
- Operating system
- git log --pretty=format:'%h' -n 1
...
-->
- nvim --version output:
```
NVIM v0.5.0-dev+nightly
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210131-41830-15tjx9v/build/config -I/tmp/neovim-20210131-41830-15tjx9v/src -I/usr/local/include -I/tmp/neovim-20210131-41830-15tjx9v/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210131-41830-15tjx9v/build/src/nvim/auto -I/tmp/neovim-20210131-41830-15tjx9v/build/include
Compiled by uriarev@Uri's-MacBook-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-55add1c/share/nvim"

Run :checkhealth for more info
```
- Operating system: macOS Big Sur 11.1
- Telescope commit: How do I get it?

</details>

<!-- Configuration -->
<details><summary>Configuration</summary>
<p>
<!-- adopt your telescope configuration to the following template,
save it to test.vim then execute `nvim -NU test.vim` -->

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment]
Probably missing `rg`. I don't see stuff because the template you filled out is broken. So this is a guess.

You could do `:messages` to see the full stack trace. It probably will tell you that command `rg` is not found. So you should install `ripgrep`. live_grep needs it (hard requirement)

**Comment by wantyapps** [comment]
Oh...

**Comment by wantyapps** [comment]
Thank you!

**Comment by wantyapps** [comment]
[telescope] [WARN  13:59:42] ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:456: Failed with msg:  ...ocal/share/nvim/plugged/plenary.nvim/lua/plenary/job.lua:80: rg: Executable not found    
[telescope] stack traceback:                                                                                                                                                                                
[telescope] ^I...ocal/share/nvim/plugged/plenary.nvim/lua/plenary/job.lua:80: in function 'new'                                                                                                             
[telescope] ^I...re/nvim/plugged/telescope.nvim/lua/telescope/finders.lua:85: in function 'finder'                                                                                                          
[telescope] ^I...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:452: in function <...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:451>                                                
[telescope] ^I[C]: in function 'pcall'                                                                                                                                                                      
[telescope] ^I...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:451: in function <...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:413>

**Comment by wantyapps** [comment]
Now it works!
