### ISSUE TITLE
Grep not working

### ISSUE THREAD

**Issue by debianw** [nvim-telescope/telescope.nvim#506]
![Screen Shot 2021-02-06 at 7 44 21 PM](https://user-images.githubusercontent.com/1002407/107134163-3d322d80-68b5-11eb-9da6-4df9eb96c0f2.png)

### Config
`nnoremap <leader>fg <cmd>Telescope live_grep<cr>`

### Description
Grep not working

**Expected Behavior**

**Actual Behavior**
Nothing shows in the preview screen. A Lua error shows up `[telescope] ^I...ig/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:451: in function <...ig/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:413>`

### Details

<details><summary>Reproduce</summary>

Example:

1. nvim .
2. :Telescope live_grep
3. type something

NVIM v0.5.0-dev+1064-gb96db38af
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Linux Ubuntu

<details><summary>Configuration</summary>
<p>

```viml
...
nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>

 call plug#begin()
   Plug 'neoclide/coc.nvim', {'branch': 'release'}
   Plug 'preservim/nerdtree'
   Plug 'morhetz/gruvbox'
   Plug 'vim-airline/vim-airline'
   Plug 'vim-airline/vim-airline-themes'
   Plug 'nvim-lua/popup.nvim'
   Plug 'nvim-lua/plenary.nvim'
   Plug 'nvim-telescope/telescope.nvim'
   Plug 'dracula/vim'
   Plug 'ryanoasis/vim-devicons'
call plug#end()
...
EOF
```

**Comment by delphinus** [comment]
Do you have `rg` executable? `live_grep` uses `vimgrep_arguments` in config. See [Telescope Defaults](https://github.com/nvim-telescope/telescope.nvim#telescope-defaults).

**Comment by SuperCuber** [comment]
Is there a way to live grep without installing external dependencies?

**Comment by Conni2461** [comment]
@SuperCuber It might be possible to to use grep you just need to end up with a line that we can interpret. Our regex:
https://github.com/nvim-telescope/telescope.nvim/blob/b3d3d938696a533c199031418e0da553a8424a46/lua/telescope/make_entry.lua#L165

Example:
```
./lua/telescope/previewers/buffer_previewer.lua:659:25:  return previewers.new_buffer_previewer {
```

Just change your `vimgrep_arguments` to the desired `grep` command with `args`.

If you have something please let me know we could put something like this in the wiki :)

**Comment by robbycostales** [comment]
I have the same problem, but only when I switch a different Anaconda environment. On my `base` environment, the live grep search works fine.

**Comment by Conni2461** [comment]
@robbycostales Does ripgrep in terminal returns something in that different anaconda env?

**Comment by robbycostales** [comment]
> @robbycostales Does ripgrep in terminal returns something in that different anaconda env?

Yes, the command was not found in my new environment (but worked in my base env), so I used `conda install -c conda-forge ripgrep`. This got it working, thanks!---but I do wonder: is there a way to not have to install these dependencies for each new environment, i.e. always point to my base installation for them?

@Conni2461

**Comment by mherna** [comment]
I have `rg` installed and I'm running into a similar issue live grep returned: 

`[telescope] ^I...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:453: in function <...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:415>`

**Comment by Conni2461** [comment]
Can i get the whole error message. `:messages` to show it. Thanks :)

**Comment by mherna** [comment]
@Conni2461 my bad didn't have `fzf` installed, `brew install fzf` solved the issue...

```
|| [telescope] [WARN  05:36:37] ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:458: Failed with msg:  .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:80: fzf: Executable not found
|| [telescope] stack traceback:
|| [telescope] ^I.../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:80: in function 'new'
|| [telescope] ^I...ck/packer/start/telescope.nvim/lua/telescope/finders.lua:85: in function 'finder'
|| [telescope] ^I...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:454: in function <...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:453>
|| [telescope] ^I[C]: in function 'pcall'
|| [telescope] ^I...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:453: in function <...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:415>
```

**Comment by Conni2461** [comment]
> Is fzf a requirement?

Only if you are using [fzf-writer](https://github.com/nvim-telescope/telescope-fzf-writer.nvim)

**Comment by zupatisc** [comment]
Maybe ripgrep should be listed under non-optional dependencies considering that a builtin picker is using it.

**Comment by matu3ba** [comment]
> Maybe ripgrep should be listed under non-optional dependencies considering that a builtin picker is using it.

I would favor generating a vim help page for the plugin and then separating the README. The README is already far too long.
Personally I like how nvim-dap does it.

Disclaimer: I wrote the [Troubleshooting article in the wiki](https://github.com/mfussenegger/nvim-dap/wiki/Troubleshooting).

**Comment by tristone13th** [comment]
Can it use the vim internal grep such as vimgrep?

**Comment by lvela** [comment]
For those who need to install ripgrep: https://github.com/BurntSushi/ripgrep#installation

**Comment by M4nojM** [comment]
you can also install ripgrep by `$sudo apt install ripgrep` in ubuntu it just works as charm.

**Comment by diegolikescode** [comment]
> Do you have `rg` executable? `live_grep` uses `vimgrep_arguments` in config. See [Telescope Defaults](https://github.com/nvim-telescope/telescope.nvim#telescope-defaults).

It worked for me, thank you!

**Comment by PAVAN507-STAR** [comment]
> Do you have `rg` executable? `live_grep` uses `vimgrep_arguments` in config. See [Telescope Defaults](https://github.com/nvim-telescope/telescope.nvim#telescope-defaults).

worked for me. Thanks a  bunch man

**Comment by adarmaori** [comment]
I'm getting the same behavior from the grep window but without the error message. (I have ripgrep installed and working)
