### ISSUE TITLE
Feature: builtin.git_recents picker

### ISSUE THREAD

**Issue by kyoh86** [nvim-telescope/telescope.nvim#509]
With many files in a repo, I want to open one of them which is updated recently.
(I'll create a pull-request for this one)

**Comment by YodaEmbedding** [comment]
Some possible heuristics could be:

 - Files recently committed _by the current author_ on the current branch. (Avoids issues with multi-developer projects.)
 - Modified files in current working tree.
 - MRU database for the current git project. (See also: [fzf-filemru](https://github.com/tweekmonster/fzf-filemru) and [fzf-mru.vim](https://github.com/pbogut/fzf-mru.vim).)

**Comment by Conni2461** [comment]
We already have this mru database extension https://github.com/nvim-telescope/telescope-frecency.nvim

It works with one database for all projects but you can limit it to the directory where the lsp is currently attached with `:LSP:` tag. (I think he is also wanted to add a `:CWD` tag, not sure). Tag will be remebered. You can also define your own Projects and use them as tags. You can also enable `show_unindexed` which will show all files in the current tag even if they are never opened.
