### ISSUE TITLE
loop or previous error loading module 'telescope'

### ISSUE THREAD

**Issue by lalitmee** [nvim-telescope/telescope.nvim#511]
### Description

The issue is that I am not able to use Telescope becuase as nvim start it gives
this error
```vim
loop or previous error loading module 'telescope' nvim
```

**Expected Behavior**

I wanna use Telescope but this error won't let me do that.

**Actual Behavior**

I am getting the error as I start neovim.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. 
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 

```bash
NVIM v0.5.0-dev+1073-gb894fbcbe
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az90-68

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

- Operating system: Pop_os 20.04 LTS
- Telescope commit: 5f1d16a 

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment]
Does this happen with the minimal vimrc

**Comment by lalitmee** [comment]
No, I have my own config which I have created using some of the configs from https://github.com/ChristianChiarulli/nvim.

**Comment by glepnir** [comment]
close. @lalitmee  had found problem and make telescope works.

**Comment by beauwilliams** [comment]
use _telescope in future for configs. adding _ in front helps with duplication of same file name. 👍

**Comment by Kapi2910** [comment]
> use _telescope in future for configs. adding _ in front helps with duplication of same file name. 👍

@beauwilliams could you please elaborate on this. I am quite new to lua, so I don't understand where the _ is to be added

**Comment by beauwilliams** [comment]
> > use _telescope in future for configs. adding _ in front helps with duplication of same file name. 👍
> 
> @beauwilliams could you please elaborate on this. I am quite new to lua, so I don't understand where the _ is to be added

Okay, so instead of naming your .lua configuration file for telescope "telescope.lua"
Call it something such as "_telescope.lua" really you can choose to name it how you like. A common convention is just to stick a _ in front and call it a day.
Why? Loading two files with same name, both from the plugin itself, and your config file can cause a conflict

**Comment by Kapi2910** [comment]
> > > use _telescope in future for configs. adding _ in front helps with duplication of same file name. 👍
> > 
> > 
> > @beauwilliams could you please elaborate on this. I am quite new to lua, so I don't understand where the _ is to be added
> 
> Okay, so instead of naming your .lua configuration file for telescope "telescope.lua"
> Call it something such as "_telescope.lua" really you can choose to name it how you like. A common convention is just to stick a _ in front and call it a day.
> Why? Loading two files with same name, both from the plugin itself, and your config file can cause a conflict

Thank you very much

**Comment by danielo515** [comment]
> > > use _telescope in future for configs. adding _ in front helps with duplication of same file name. 👍
> > 
> > 
> > @beauwilliams could you please elaborate on this. I am quite new to lua, so I don't understand where the _ is to be added
> 
> Okay, so instead of naming your .lua configuration file for telescope "telescope.lua" Call it something such as "_telescope.lua" really you can choose to name it how you like. A common convention is just to stick a _ in front and call it a day. Why? Loading two files with same name, both from the plugin itself, and your config file can cause a conflict

Thanks for that explanation, and sorry for the comment on an old thread, but will it be enough to put it under a subfolder? like `user/telescope` ?

**Comment by quantumfate** [comment]
> > > > use _telescope in future for configs. adding _ in front helps with duplication of same file name. +1
> > > 
> > > 
> > > @beauwilliams could you please elaborate on this. I am quite new to lua, so I don't understand where the _ is to be added
> > 
> > 
> > Okay, so instead of naming your .lua configuration file for telescope "telescope.lua" Call it something such as "_telescope.lua" really you can choose to name it how you like. A common convention is just to stick a _ in front and call it a day. Why? Loading two files with same name, both from the plugin itself, and your config file can cause a conflict
> 
> Thanks for that explanation, and sorry for the comment on an old thread, but will it be enough to put it under a subfolder? like `user/telescope` ?

I recommend you to do exactly that. I have my configuration files for each plugin in ~/.config/nvim/lua/user and my init.lua in  ~/.config/nvim/lua/ will source all the files. I just fixed tonns of issues in my own configurations.

**Comment by tarikwaleed** [comment]
I got a buch of errors when I reinstall neovim on a new machine and simply stow my config files .. i don't know what is the cause of these errors and it seems really hard to troubleshoot

**Comment by melkster** [comment]
I also started seeing the error "packer.nvim: Error running config for telescope.nvim: [string "..."]:0: loop or previous error loading module 'telescope'" recently. It appears sometimes when I do `:PackerCompile` and if I don't re-run `:PackerCompile` a couple of times until the error goes away it re-appears whenever I launch Neovim. I haven't changed anything significant in my Telescope config, and I also have it in `~/.config/nvim/lua/user/telescope.lua`

**Comment by crusj** [comment]
I have initially integrated telescope, you can use the git branch` integrate-with-telescope `for trial and feedback.
`require("telescope").load_extension("bookmarks")
`

**Comment by tmillr** [comment]
> **Note** For anyone _still_ having issues with this error (as this very GitHub issue seems to be one of the top Google results when you search for this error), even after ensuring that there are no duplicate file names, just know that this error can also be caused by 2 different files requiring each other (i.e. depending on each other). This is something that I just ran into. It doesn't appear that Lua's `require()`/module loader is apt enough to attempt to handle such cases intelligently, at least not when it comes to the version of Lua currently used in Neovim.
