### ISSUE TITLE
Displayer broken on Windows

### ISSUE THREAD

**Issue by Conni2461** [nvim-telescope/telescope.nvim#513]
Reported by @sp1n0r on gitter. Reproducible.

```
cannot resolve symbol 'linetabsize_col'
```
And if that one is ignored:
```
cannot resolve symbol 'utf_ptr2len'
```

Possible hotfix: 
```diff
diff --git a/lua/telescope/utils.lua b/lua/telescope/utils.lua
index 9cfc23c..188c1ea 100644
--- a/lua/telescope/utils.lua
+++ b/lua/telescope/utils.lua
@@ -203,7 +203,7 @@ function utils.get_os_command_output(cmd)
 end

 utils.strdisplaywidth = (function()
-  if jit then
+  if jit and pathlib.separator ~= '\\' then
     local ffi = require('ffi')
     ffi.cdef[[
       typedef unsigned char char_u;
@@ -224,7 +224,7 @@ utils.strdisplaywidth = (function()
 end)()

 utils.utf_ptr2len = (function()
-  if jit then
+  if jit and pathlib.separator ~= '\\' then
     local ffi = require('ffi')
     ffi.cdef[[
       typedef unsigned char char_u;
```

Other possible solution from @tjdevries:
> We can just expose the functions in the api and mark it as fast

CC @delphinus

**Comment by delphinus** [comment]
Thx for the report. I made PR for this: #515.

I'm afraid one more calling for `ffi` exists [here][] in path.lua.

[here]: https://github.com/delphinus/telescope.nvim/blob/6888f32750defb7c56ac6d848fc5b1f1dda7c9b7/lua/telescope/path.lua#L24

Should this also be fixed?

----

And I'm not familiar with the reason why some funcs are marked as api-fast and others are not. Can `strdisplaywidth()`, `strcharpart()`, and `pathshorten()` be marked as api-fast...?

**Comment by Conni2461** [comment]
The weird thing is `path.shorten` works :laughing: Or at least it didn't notice it not working so this is fine.

Would also be cool if you can join gitter now that you are a member :)

**Comment by sp1n0r** [comment]
Thanks :D

**Comment by JSchrtke** [comment]
Windows user here (sadly), I just tried the fix that was merged earlier. All working fine now 👍

**Comment by Conni2461** [comment]
We have a more solid solution in plenary.strings for a while now. Closing
