### ISSUE TITLE
Is it possible to configure the results list?

### ISSUE THREAD

**Issue by tssm** [nvim-telescope/telescope.nvim#514]
Because I always have the preview open I would like to edit how some result lists look. For example, given the Quickfix results:

![Screenshot 2021-02-08 at 10 37 08](https://user-images.githubusercontent.com/1188977/107202351-66100b00-69fa-11eb-9c70-9b358080daac.png)

We see the line and column numbers, then the file path, then a preview of the line (which is cut for lack of space), and then the filename. I would like to have the path, line and column numbers, and nothing else, because the preview shows me all the context I need in a better way.

I would like to also edit the LSP pickers' result lists. Is it possible or are they hardcoded? If the latter, could you point me out where? I couldn't fin it myself

**Comment by Conni2461** [comment]
Yes you can change them and we have one example how this can be done. For [buitlin.buffers](https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#customize-buffers-display-to-look-like-leaderf).

You would need to over write the `entry_maker` which should be possible. You can just copy the current entry maker and add, remove or move columns:
- [quickfix ref](https://github.com/nvim-telescope/telescope.nvim/blob/b3d3d938696a533c199031418e0da553a8424a46/lua/telescope/make_entry.lua#L309-L363)
- [lsp ref](https://github.com/nvim-telescope/telescope.nvim/blob/b3d3d938696a533c199031418e0da553a8424a46/lua/telescope/make_entry.lua#L365-L457)

The overall entry that needs to be change is  [display](https://github.com/nvim-telescope/telescope.nvim/blob/b3d3d938696a533c199031418e0da553a8424a46/lua/telescope/make_entry.lua#L353) with the corresponding [make_display function](https://github.com/nvim-telescope/telescope.nvim/blob/b3d3d938696a533c199031418e0da553a8424a46/lua/telescope/make_entry.lua#L322-L340)

If you end up with an overall better solution. We could talk about changing the default. But we would need to ask @sunjon he introduced this design. :)

Note: For lsp you should be able to just set: `show_line = false`

**Comment by tssm** [comment]
Thanks! I completely overlooked that. I'll close for now and reopen if I happen to come with something better

**Comment by smartding** [comment]
@tssm have you made your custom `entry_maker`?
I'm trying to do the same thing.

**Comment by tssm** [comment]
Yes, I wrote a `make_entry` for the [buffers list](https://github.com/tssm/.config/blob/master/nvim/plugin/telescope.fnl#L70), another [for LSP](https://github.com/tssm/.config/blob/master/nvim/lua/configs/lsp.fnl#L22) symbols and one for the [quickfix list](https://github.com/tssm/.config/blob/master/nvim/lua/procedures.fnl#L6), they are in Fennel though 🙈 I followed Telescope's source code. Basically your `make_entry` should return a table with at least `display`, `value`, `filename`, `col` and `lnum`. Some pickers may require other properties as well

**Comment by smartding** [comment]
@tssm  thanks.
Don't know anything about Fennel, guess I'll write my own in lua.

**Comment by tssm** [comment]
Fennel is a Lisp that compiles to Lua and has the same semantics, so where it says `(function)` in Lua would be `fucntion()`, and where it says `{:property bleh :property2 blah}` in Lua would be `{property = bleh, property2 = blah}`. The first function would be roughly

```lua
function entry_maker(entry)
  local bufname = entry.info.name
  local display
  if (bufname == "") then
    display = "🆕"
  elseif (vim.startswith(bufname, "man://") then
    display = vim.fn.substitute(bufname "^man://" "" "")
  elseif (vim.fn.match(bufname "^\w*://") > -1) then
    display = bufname
  else
    display = path:new(bufname):make_relative(vim.fn.getcwd)
  end
  return {bufnr = entry.bufnr, display = display, ordinal = display, value = display}
end
```

Sorry if it's not completely correct. The parameter `entry` varies depending on the picker. You can search for `gen_for_` here in the repo to see other examples. [Here is the original one for buffers](https://github.com/nvim-telescope/telescope.nvim/blob/79644ab67731c7ba956c354bf0545282f34e10cc/lua/telescope/make_entry.lua#L410)

**Comment by MuhammedZakir** [comment]
You can convert Fennel to Lua here -- https://fennel-lang.org/see.

**Comment by smartding** [comment]
@tssm @MuhammedZakir, thank you.
Here's the `entry_maker` I wrote for my custom lsp_references.
It's based on `make_entry.gen_from_quickfix`, which is the default `entry_maker` for telescope's builtin `lsp_references`.

  ```lua
  function entry_maker(entry)
    local Path = require "plenary.path"
    local entry_display = require "telescope.pickers.entry_display"

    local filename = entry.filename or vim.api.nvim_buf_get_name(entry.bufnr)

    local displayer = entry_display.create {
      separator = " ",
      items = {
        { width = 4 },
        { remaining = true },
      },
    }

    local make_display = function(entry)
      return displayer {
        entry.lnum,
        Path:new(filename):make_relative(vim.loop.cwd()),
      }
    end

    return {
      valid = true,

      value = entry,
      ordinal = filename .. " " .. entry.text,
      display = make_display,

      bufnr = entry.bufnr,
      filename = filename,
      lnum = entry.lnum,
      col = entry.col,
      text = entry.text,
      start = entry.start,
      finish = entry.finish,
    }
  end
  ```
