### ISSUE TITLE
Previewer crashes my neovim

### ISSUE THREAD

**Issue by cetanu** [nvim-telescope/telescope.nvim#519]
### Description
When my terminal is large enough that the previewer appears, I am unable to open files or perform regular actions using any commands like `find_files`, `live_grep`, `buffers`, `help_tags`.

**Expected Behavior**
For example when I use `Telescope find_files`, find a file, and hit enter, it should open the file

**Actual Behavior**
When I hit enter, to open a file, I get an error regarding `nvim_buf_delete` and my vim gets into a funky state where my cursor is inside the previewer buffer, and then I have to `:q!` approximately 3 or 4 times before I can get it back to a normal state.

```
E5108: Error executing lua .../.vim/plugged/telescope.nvim/lua/telescope/utils.lua:146: attempt to call field 'nvim_buf_delete' (a nil value)
```

![image](https://user-images.githubusercontent.com/2289018/107313335-67b6fd00-6ae6-11eb-8542-9ca3cbd24c08.png)

### Details

<details><summary>Reproduce</summary>

1. nvim test.vim
2. :Telescope find_files
3. enter any text to find a file
4. Hit <enter> to open the file
5. File doesn't open, error is displayed
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-709-g4f8d98e58
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/usr/local/opt/gettext/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
- Operating system: 
Mac OSX
```
Darwin C02W104NHTDG 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
```
- Telescope commit: `ef3262f`

</details>

<details><summary>Configuration</summary>
<p>
I found the ask of this section confusing, but this is my effective config:

```viml
call plug#begin('~/.vim/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'sharkdp/bat'
Plug 'sharkdp/fd'
Plug 'BurntSushi/ripgrep'
call plug#end()

" Find files using Telescope command-line sugar.
nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>
```

**Comment by Conni2461** [comment]
Can't reproduce this. And i don't get why we would pass in a nil value to `nvim_buf_delete`. We could add a nil check.

You could also try the new buffer previewers which will because default very soon anyway:
```lua
require('telescope').setup {
  defaults = {
    file_previewer = previewers.vim_buffer_cat.new,
    grep_previewer = previewers.vim_buffer_vimgrep.new,
    qflist_previewer = previewers.vim_buffer_qflist.new,
  }
}
```

**Comment by cetanu** [comment]
It doesn't seem like a nil value is being passed to it, it seems that `nvim_buf_delete` itself is nil, which makes absolutely no sense to me. Is that environment messed up? I should maybe reinstall neovim?

this is the function being called in telescope

```lua
function utils.buf_delete(bufnr)
  if bufnr == nil then return end

  -- Suppress the buffer deleted message for those with &report<2
  local start_report = vim.o.report
  if start_report < 2 then vim.o.report = 2 end

  if vim.api.nvim_buf_is_valid(bufnr) and vim.api.nvim_buf_is_loaded(bufnr) then
    vim.api.nvim_buf_delete(bufnr, { force = true }) -- <------------------- Problem occurs here
  end

  if start_report < 2 then vim.o.report = start_report end
end
```

So for some reason.... `vim.api.nvim_buf_delete` is `nil`? :(

**Comment by Conni2461** [comment]
Oh i forgot to look at your neovim version before.

> NVIM v0.5.0-709-g4f8d98e58

Is way too old. We use new things that come into neovim after some time. You should try too keep it somewhat up to date. Like rebuild once a week :)

**Comment by cetanu** [comment]
Aha, glad it was something simple. I'll have to remember to `brew reinstall neovim` when I update my vim plugins.

Thanks for the assist!
