### ISSUE TITLE
Saving lists in telescope

### ISSUE THREAD

**Issue by rockerBOO** [nvim-telescope/telescope.nvim#52]
Saving or re-populating lists for fetching the fuzzed list out. 

This will allow users to use the smaller fuzzed list to do additional things. Like doing actions to each item on the fuzzed list.

**Comment by tjdevries** [comment]
So you want something that you can take the current results and then make a new fuzzy finder with those results?

Or you want to put them into quickfix list? or what?

**Comment by rockerBOO** [comment]
So use cases initially.

I want to take the fuzzy list in telescope and paste it into a document. 
I want to extract each item to run a macro on the matches. 
I want to come back to the list to use the fuzzy list again (maybe go back and forth from telescope).

So saving the list would allow us to export the list. We'd also be able to restore the list to like be able to iterate through items on a list (going to the items). 

Being able to use something like `n` (not sure on the keybind) to go through the list in telescope would be the idea. Toggling back to telescope is tough right now (to append the list or find something new).

Being able to use a fuzzy find on errors to limit the list of errors (in the case when you have a lot of them) and then go through the errors, then come back to telescope to search or just iterate through. Telescope is a common interface for using lists so I think this makes sense?

**Comment by tjdevries** [comment]
Yes, each of those makes sense I think.

We can chat about it on stream maybe.

**Comment by weilbith** [comment]
Hey guys, whats the current state of this issue?
I'm about to switch to this plugin. But the feature to restore the last opened list and it updates it automatically is a must-have for me.

**Comment by tjdevries** [comment]
OK, we can now save things to quickfix list and then you could reload them from the quickfix list as well, using the telescope picker that allows you to do that.

I don't think I understand what you're looking for @weilbith . Perhaps you could make a new issue? I'm going to close this one since you can now add things to quickfix list. We can discuss other feature requests elsewhere.
