### ISSUE TITLE
Recent git_files and find_files history like FZF for Vim

### ISSUE THREAD

**Issue by saragiotto** [nvim-telescope/telescope.nvim#520]
**Is your feature request related to a problem? Please describe.**
On FZF for Vim there is a history with all last inputs easily access via <c-p> <c-n>.

**Describe the solution you'd like**
I would like to see something like that here.

**Describe alternatives you've considered**
No alternative found until now.

**Additional context**
mac os x 11.1 big sur
nvim version v0.5.0-dev+1062-gcc1851c9f
tmux 3.1c
zsh 5.8 (x86_64-apple-darwin20.0)

**Comment by Conni2461** [comment]
Do you mean `Telescope oldfiles`? Because for us `oldfiles` is only `v:oldfiles` and doesn't add buffers.
Alternative [frecency](https://github.com/nvim-telescope/telescope-frecency.nvim)

**Comment by saragiotto** [comment]
Not sure that frecency tackle this issue correctly.

For deeper description of my daily basis: I work on a project with very long file names and I got often type too much letters in order to find the right file. 

On my previous FZF configuration on VIM I got this couple lines that solve this problem for me:

```javascript
" Enable per-command history.
" CTRL-N and CTRL-P will be automatically bound to next-history and
" previous-history instead of down and up. If you don't like the change,
" explicitly bind the keys to down and up in your $FZF_DEFAULT_OPTS.
let g:fzf_history_dir = '~/.local/share/fzf-history'
```

**Comment by Conni2461** [comment]
I see what you saying sounds like a cool feature :) Is this history saved per `cwd`/`project` or is it just one history file?

I know how we could implement something like this. Will work on this in the next couple of days

**Comment by saragiotto** [comment]
It keeps in just one big file, mine gets 1000 lines, I think that is the maximum. But definitely It's not based on `cwd/project`.

**Comment by Conni2461** [comment]
I kinda have to thank you :) This was super fun to implement :rofl: 
https://streamable.com/w3wpri

Right now its hacky and tj is doing a big refactoring of actions. So i kinda wanna hold this until that refactor is done. But i will open a PR so you can check it out with all the setup information :)

**Comment by saragiotto** [comment]
Sorry about the delay on answer back, I'll clone this right now.
