### ISSUE TITLE
How exactly can I ignore folders like node_modules in telescope?

### ISSUE THREAD

**Issue by melodyogonna** [nvim-telescope/telescope.nvim#522]
Apart from the fact that indexing these sort of folders takes some time to index, it also messes up my search results when I try to find files.

I have this ignore pattern but none seems to work.

`lua << EOF
require('telescope').setup{
    file_ignore_patterns = {"./node_modules/*", "node_modules", "^node_modules/*", "node_modules/*"},
}
EOF
`

**Comment by Conni2461** [comment]
It has to be a lua regex. But i think whats failing here is `_`. I think that has to be escaped in lua: `%_` other than this i think this should work: `file_ignore_patterns = { "node%_modules/.*" }`

**Comment by elianiva** [comment]
doing `file_ignore_patterns = { "node_modules" }` and removing the rest works fine for me

**Comment by melodyogonna** [comment]
I found the problem, setup takes a `defaults` argument, so I should have done `lua << EOF
require('telescope').setup{
    defaults = {
        file_ignore_patterns = {"node_modules"}
      }
}
` instead.

**Comment by thomaszdxsn** [comment]
`file_ignore_patterns` make the find_files extrem slowly

**Comment by ilan-schemoul** [comment]
For future googler : are also ignored everything listed in .rgignore .ignore .gitignore (see https://github.com/BurntSushi/ripgrep)

**Comment by arsaccol** [comment]
This issue is the first result on Google. An explanation for newcomers or a link to the relevant part of the documentation on how to make Telescope ignore `node_modules` for file search would be greatly appreciated!

**Comment by hazeled** [comment]
> `file_ignore_patterns` make the find_files extrem slowly

This is still an issue almost a year later. Really hoping this can get fixed soon

**Comment by CarloCattano** [comment]
Following , since I would like not only to ignore certain files on the ignore such as node_modules but also entire paths on my system when using it globally, atm always shows random folders of a backup drive I have. Didnt quite get where I can add the regex to

**Comment by emilBeBri** [comment]
Could someone explain how to make files and folders ignored, without slowing the system down then? I'm confused. I tried putting a gitignore file in the project dir, that is not being respected.  I thought this was using fzf?

**Comment by melodyogonna** [comment]
> 

Install https://github.com/BurntSushi/ripgrep on your machine. Telescope will use it automatically and Ripgrep ignores everything inside your .gitignore file.

**Comment by emilBeBri** [comment]
Already have that but thanks for the suggestion :)  

I have a .gitignore file  with the following:

```
/.cargo/
.cargo/
*.cargo*
```
(I included all three just to make sure I got thefolder  exluded)

and it still searches the .cargo folder! what insulence.  Perhaps it's because I have some envir variable setup, I have this in my .bashrc

```
export RIPGREP_CONFIG_PATH="$HOME/Dropbox/share/.ripgreprc"
```
Which also includes the above.


and still .cargo shows up in my search. Really odd.

**Comment by Bechemude** [comment]
> It has to be a lua regex. But i think whats failing here is `_`. I think that has to be escaped in lua: `%_` other than this i think this should work: `file_ignore_patterns = { "node%_modules/.*" }`

thx it's also helped to me with ".clj-kondo"

**Comment by rodrigopsasaki** [comment]
> Already have that but thanks for the suggestion :)
> 
> I have a .gitignore file with the following:
> 
> ```
> /.cargo/
> .cargo/
> *.cargo*
> ```
> 
> (I included all three just to make sure I got thefolder exluded)
> 
> and it still searches the .cargo folder! what insulence. Perhaps it's because I have some envir variable setup, I have this in my .bashrc
> 
> ```
> export RIPGREP_CONFIG_PATH="$HOME/Dropbox/share/.ripgreprc"
> ```
> 
> Which also includes the above.
> 
> and still .cargo shows up in my search. Really odd.

@emilBeBri I had the same issue as you, in my case it turns out all I needed to do was open a fresh terminal session. Don't know if you tried that yourself.

**Comment by nubunto** [comment]
if you landed on this like me, friendly reminder that ripgrep will only respect .gitignore inside git repos

**Comment by benjamin051000** [comment]
@nubunto Good to know. My work doesn't use git (sad!) so I was wondering if I could trick ripgrep by throwing a "fake" `.gitignore` in a dir that I frequent in. I may test `file_ignore_patterns` because I want to be able to ignore Python `venv/` folders (something which is typically in a `.gitignore` file. Not sure what the best solution is at this point... 🤔

**Comment by jamestrew** [comment]
@benjamin051000 mentioned a couple times above but there are alternatives to `.gitignore` that rg/fd will respect, like `.ignore`, `.rgignore`, `.fdignore` respectively.

Also @nubunto, this isn't exactly true. there's a `--no-require-git` flag so you can use that in conjunction with `.gitignore` inside a non-git repo.

**Comment by 9mm** [comment]
@jamestrew is there a secret to this? I have `~/.fdignore` and fzf telescope is still ignoring that file?

**Comment by jamestrew** [comment]
@9mm anything you put into `.fdignore` (except for whitelist rules) will be ignored by fd when using fd in that directory (so using fd inside `~` unless using the `--base-directory` flag). If you're using the `find_files` picker, that means having a `.fdignore` inside the cwd of the current nvim session.
But also `find_files` uses rg as a first option if available, fd next, then plain `find`. So double check which "finder" is being used -- you may need to use `.rgignore` instead.

If you're meaning to have like a global `.fdignore`, you should use `$XDG_CONFIG_HOME/fd/ignore` (with fd v8.1.0).

**Comment by 9mm** [comment]
ah ok, this helps a lot. Thanks!

**Comment by benjamin051000** [comment]
@jamestrew hmm... I created a `~/.config/fd/ignore` text file with `venv/` and `__pycache__/` in it, and it appears to work when I run `fd` from the command line, but using telescope in nvim still shows me files within those dirs. I am running both from the same directory, which has `venv/` and `__pycache__/` as subdirs.

**Comment by jamestrew** [comment]
@benjamin051000 depending on the picker, it might be using rg if available (find_files, live_grep, grep_string, maybe others too i forget). In which case, you'll have to use `.rgignore` (for rg) or `.ignore` (which both rg and fd respect).
I don't think rg has a global ignore file location but you can pass `--ignore-file` and give the global fd ignore file I guess. then you can set this as a global config with https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file

**Comment by benjamin051000** [comment]
`.ignore` works, so I bet it is using ripgrep after all... Interesting! I figured `fd` would be faster than `rg` for `find_files()`, but it still seems to be plenty quick. Awesome, thank you!

**Comment by jamestrew** [comment]
I think based on some benchmarks, it was determined that rg has a slight edge over fd searching for files. So we're prioritizing using rg over fd if available.

**Comment by martin-braun** [comment]
I only want to ignore the contents of the `.git` folder, but putting `.git` in the list will also ignore a file called `git-src`. I also tried to use regex (i.e. `\\.git`), but it will not ignore the `.git` folder.

Could anybody please advice?

**Comment by jaywhy13** [comment]
I can't get Telescope to ignore the `.git` directory. I'm using LunarVim and I've put this in my config file and Telescope is still listing files from the `.git` folder.

```lua
require("telescope").setup { defaults = { file_ignore_patterns = { ".git/" } } }
```

**Comment by danieluhl** [comment]
Just in case anyone else found this thread trying to escape a series of things like `package-lock.json` or `yarn.lock` the trick is listed nicely in the friendly manual: `file_ignore_patterns` are lua regex matches, so you gotta find the online regex matcher to see what's up. Namely you gotta escape any `-` or `.` with `%`:

```
		local file_ignore_patterns = {
			"yarn%.lock",
			"node_modules/",
			"raycast/",
			"dist/",
			"%.next",
			"%.git/",
			"%.gitlab/",
			"build/",
			"target/",
			"package%-lock%.json",
		}

...

		vim.keymap.set("n", "<leader>sf", function()
			builtin.live_grep({
				file_ignore_patterns = file_ignore_patterns,
			})
		end, { desc = "[S]earch by [F]inding a word" })
```

**Comment by JamesHertz** [comment]
Wouldn't it be better to have something like .gitignore, but for telescope?

**Comment by mguellsegarra** [comment]
> Wouldn't it be better to have something like .gitignore, but for telescope?

+1

**Comment by jamestrew** [comment]
Like a `.telescopeignore`?
I don't know... I don't love the idea.

I also generally don't recommend adding a ton of things to `file_ignore_patterns`. Telescope itself has to pattern match results against the items in `file_ignore_patterns` in the main neovim lua event loop which can be considerably slower than letting `fd` or `rg` or `git` handle `.ignore`/`.fdignore`/`.rgignore`/`.gitignore`.

**Comment by gokayburuc** [comment]
just add the `.ignore` file written like `.gitignore` syntax. 

```bash 

# folders to ignore 
node_modules/

# filetypes to ignore - optional 
*.js 
*.jsx
*.json

```

Especially some file extensions such as json,js and some folders such as node_modules are totally nightmare for old computers like my Sony Vaio. So I am adding this before commit the project.Writing my changes  and deleting the .ignore file afterwards.No performance issues, no complex configurations.

**Comment by JamesHertz** [comment]
> Like a `.telescopeignore`? I don't know... I don't love the idea.
> 
> I also generally don't recommend adding a ton of things to `file_ignore_patterns`. Telescope itself has to pattern match results against the items in `file_ignore_patterns` in the main neovim lua event loop which can be considerably slower than letting `fd` or `rg` or `git` handle `.ignore`/`.fdignore`/`.rgignore`/`.gitignore`.

I mean, you could probably ship the functionality to a binary and call it from telescope or you could read the file once when neovim is started. I only mentioned that because, depending on the project I am working on, I don't want all the `.o`s, `.class`, `.hi`, etc to pop up when I want to move to another file. Adding it to `file_ignore_patterns` feels like doing a precommitment that such patterns are the only ones I will ever use. This means, that if I add folders to `file_ignore_patterns` it could be very very troublesome for some projects.

Additionally, you could add a restriction that `.telescopeignore` had to be placed on the root of the project (where neovim was launched).

**Comment by gokayburuc** [comment]
> > Like a `.telescopeignore`? I don't know... I don't love the idea.
> > I also generally don't recommend adding a ton of things to `file_ignore_patterns`. Telescope itself has to pattern match results against the items in `file_ignore_patterns` in the main neovim lua event loop which can be considerably slower than letting `fd` or `rg` or `git` handle `.ignore`/`.fdignore`/`.rgignore`/`.gitignore`.
> 
> I mean, you could probably ship the functionality to a binary and call it from telescope or you could read the file once when neovim is started. I only mentioned that because, depending on the project I am working on, I don't want all the `.o`s, `.class`, `.hi`, etc to pop up when I want to move to another file. Adding it to `file_ignore_patterns` feels like doing a precommitment that such patterns are the only ones I will ever use. This means, that if I add folders to `file_ignore_patterns` it could be very very troublesome for some projects.
> 
> Additionally, you could add a restriction that `.telescopeignore` had to be placed on the root of the project (where neovim was launched).

Just add your ignored files into the `.ignore` file. That's all. Every project has their own dynamics. So you can bypass the general configuration of telescope by this way. I'm currently using it with `mdbook` project. At that project i only need markdown files. Other files are not necessary for me. So i'm ignoring `*.js` and `*.json`. And also you can pass the specific folders and paths with this way.  Especially when i am using todo-comments it extends my area of movements and performance improvements.

**Comment by JamesHertz** [comment]
> > > Like a `.telescopeignore`? I don't know... I don't love the idea.
> > > I also generally don't recommend adding a ton of things to `file_ignore_patterns`. Telescope itself has to pattern match results against the items in `file_ignore_patterns` in the main neovim lua event loop which can be considerably slower than letting `fd` or `rg` or `git` handle `.ignore`/`.fdignore`/`.rgignore`/`.gitignore`.
> > 
> > 
> > I mean, you could probably ship the functionality to a binary and call it from telescope or you could read the file once when neovim is started. I only mentioned that because, depending on the project I am working on, I don't want all the `.o`s, `.class`, `.hi`, etc to pop up when I want to move to another file. Adding it to `file_ignore_patterns` feels like doing a precommitment that such patterns are the only ones I will ever use. This means, that if I add folders to `file_ignore_patterns` it could be very very troublesome for some projects.
> > Additionally, you could add a restriction that `.telescopeignore` had to be placed on the root of the project (where neovim was launched).
> 
> Just add your ignored files into the `.ignore` file. That's all. Every project has their own dynamics. So you can bypass the general configuration of telescope by this way. I'm currently using it with `mdbook` project. At that project i only need markdown files. Other files are not necessary for me. So i'm ignoring `*.js` and `*.json`. And also you can pass the specific folders and paths with this way. Especially when i am using todo-comments it extends my area of movements and performance improvements.

Ok, I didn't even know that there was such a thing. Thanks.

**Comment by byildiz** [comment]
If you wonder why telescope still shows the files in .gitignore, you need to initialize git repo with `git init`.
