### ISSUE TITLE
Find_Command vars not applied

### ISSUE THREAD

**Issue by beauwilliams** [nvim-telescope/telescope.nvim#524]
See the below code. **I am trying to search hidden files, however it is not working**

As you can see I have tried 

```
 find_command= {
            'hidden',
            'prompt_prefix=🔍'
    },
```

**MY CONF**
```
local actions = require('telescope.actions')
local telescope = require('telescope')
telescope.setup{
    defaults = {
        mappings = {i = {["<esc>"] = actions.close, }},
        vimgrep_arguments = {
            'rg',
            '--hidden', --SHOW FILES IN DIRS PRECEDING WITH A . i.e .config
            '--color=never',
            '--no-heading',
            '--with-filename',
            '--line-number',
            '--column',
            '--smart-case'
        },
        find_command= {
            'hidden',
            'prompt_prefix=🔍'
    },
        prompt_position = "top",
        prompt_prefix = ">",
        initial_mode = "insert",
        selection_strategy = "reset",
        sorting_strategy = "ascending",
        layout_strategy = "horizontal",
        layout_defaults = {
            -- TODO add builtin options.
        },
        file_sorter =  require'telescope.sorters'.get_fuzzy_file,
        file_ignore_patterns = {"forks",".backup",".swap",".langservers",".session",".undo",".git/*","node_modules","vendor",".cache",".vscode-server",".Desktop",".Documents","classes"},
        generic_sorter =  require'telescope.sorters'.get_generic_fuzzy_sorter,
        shorten_path = true,
        winblend = 0,
        width = 0.75,
        preview_cutoff = 120,
        results_height = 1,
        results_width = 0.8,
        border = {},
        borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
        color_devicons = true,
        use_less = true,
        set_env = { ['COLORTERM'] = 'truecolor' }, -- default = nil,
        file_previewer = require'telescope.previewers'.cat.new, -- For buffer previewer use `require'telescope.previewers'.vim_buffer_cat.new`
        grep_previewer = require'telescope.previewers'.vimgrep.new, -- For buffer previewer use `require'telescope.previewers'.vim_buffer_vimgrep.new`
        qflist_previewer = require'telescope.previewers'.qflist.new, -- For buffer previewer use `require'telescope.previewers'.vim_buffer_qflist.new`

        -- Developer configurations: Not meant for general override
        -- buffer_previewer_maker = require'telescope.previewers'.buffer_previewer_maker
    },
    extensions = {
        fzy_native = {
            override_generic_sorter = false,
            override_file_sorter = true,
        },
    },

}

vim.cmd[[highlight TelescopeBorder guifg=#4c4c4c]]
vim.cmd[[highlight TelescopeSelection guifg=#ffffff guibg=#393939 gui=bold]]
vim.cmd[[highlight TelescopeSelectionCaret guifg=#749484 gui=bold]]

-- require('telescope').load_extension('fzy_native')
require('telescope').load_extension('fzy_native')
```

**Comment by beauwilliams** [comment]
I have this working. Perhaps I am reading docs incorrectly

`utils.nnoremap(leader..'s', ":lua require'telescope.builtin'.find_files(require('telescope.themes').get_dropdown({hidden = true}))<cr>")`

**Comment by tami5** [comment]
Hey @beauwilliams, `find_command` can only be the shell augments to run. Additionally, this opt will only work if you pass it to `find_files`.

```lua
find_command =  { 'fd', '--type', 'f' }
find_command = { 'rg', '--files'. '--hidden ' } -- man rg, --hidden let you search hidden files
```

The prompt_prefix needs to be set right under `defaults` dict in order for it to work.

For better customization experience, look at this snippet https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#having-a-factory-like-function-based-on-a-dict

**Comment by beauwilliams** [comment]
I must not be getting it. 
I have tried adding 
`find_command = { 'rg', '--files', '--hidden' } ` 
to my telescope.setup() but its not doing anything

**Comment by tami5** [comment]
Yah it won't work inside setup only in find_files like 

```lua
lua require'telescope.builtin'.find_files({
   find_command = {'rg', '--files', '--hidden'},
   cwd = "~/",
   search_dirs = {} -- for multiple dirs,
})

```

**Comment by beauwilliams** [comment]
Okay thanks for that :) Will do it in my autocmd functions then

**Comment by Conni2461** [comment]
FYI you can also do `:Telescope find_files hidden=true` or `:lua require'telescope.builtin'.find_files({ hidden = true })`. Its a finder specific opt so it won't work in `telescope.setup`

**Comment by jaydorsey** [comment]
I mapped like this:

    nnoremap <leader>p :lua require 'telescope.builtin'.find_files({ find_command = {'rg', '--files', '--hidden', '--glob=!.git'} })<cr>

Sharing in case it helps someone else.

**Comment by beauwilliams** [comment]
> I mapped like this:
> 
> ```
> nnoremap <leader>p :lua require 'telescope.builtin'.find_files({ find_command = {'rg', '--files', '--hidden', '--glob=!.git'} })<cr>
> ```
> 
> Sharing in case it helps someone else.

Thanks, that's a good suggestion. Inspired me to try and get these opts working with the dropdown. I had not tried this before until now but it seems to work

`:lua require'telescope.builtin'.find_files(require('telescope.themes').get_dropdown({hidden = true, find_command = {'rg', '--files', '--hidden', '--glob=!.git'}}))<cr>`
