### ISSUE TITLE
Clicking telescope area creates prompt buffer

### ISSUE THREAD

**Issue by rakin406** [nvim-telescope/telescope.nvim#526]
### Issue
When I click a file in the telescope area/window, a "prompt" buffer gets created and tells me to save before quitting. When I do this on an existing buffer, it gets replaced by the prompt buffer.

### Info
Neovim version 0.5 release build

### Illustration
![telescopeissue1](https://user-images.githubusercontent.com/63601725/107760416-e6fd3880-6d53-11eb-8df5-ea4789bcac89.gif)

**Comment by Conni2461** [comment]
We are not creating a new prompt buffer. That is just the buffer where you usually type in that is not cleaned up.

**Comment by rakin406** [comment]
I see, but sometimes I have to scroll the preview window and I mistakenly click it, closing the telescope window and that weird buffer appears.

**Comment by Conni2461** [comment]
You can scroll with `<C-d>` and `<C-u>` See https://github.com/nvim-telescope/telescope.nvim#mappings
If that doesn't work then probably because of your `LESS` env setting. Make sure `-X` is not set.

Or use buffer previewer which don't need less :D

**Comment by rakin406** [comment]
Alright, thanks! :)
