### ISSUE TITLE
[feature] :help telescope

### ISSUE THREAD

**Issue by kassio** [nvim-telescope/telescope.nvim#527]
**Is your feature request related to a problem? Please describe.**

First of all thanks telescope maintainers/community. It's a great plugin. But every once in a while I try to see my telescope options from within neovim and then I remember this plugin doesn't have a `doc/` folder.

**Describe the solution you'd like**

Basically, copy the wiki and readme to `doc/`

**Describe alternatives you've considered**

Open the browser. 😭 

**Additional context**

Thanks again! <3

**Comment by Conni2461** [comment]
See https://github.com/nvim-telescope/telescope.nvim/pull/370
We want to go from lua documentation to vim `doc/` documentation, but we are not quite yet there. We are using treesitter to get the docs and annotation and generate the text file with it. https://github.com/tjdevries/tree-sitter-lua is just not quite there :)

**Comment by tjdevries** [comment]
We now have the very first versions of `:help telescope` -- we will work on adding more!
