### ISSUE TITLE
Cycle through all results

### ISSUE THREAD

**Issue by fedoranvar** [nvim-telescope/telescope.nvim#532]
Great tool! Thank you vey much!

So, the point:
**Is your feature request related to a problem? Please describe.**
Couldn't find a way (nor in README.md, nor in issues) to cycle through all results, so it cycles only in visible results

![image](https://user-images.githubusercontent.com/52028706/107863505-bcf06700-6e76-11eb-8feb-509a5ee3a344.png)

**Describe the solution you'd like**
I want to be able to cycle through all result - something like paging (ResultsPageDown, ResultPageUp)

**Describe alternatives you've considered**
none

**Additional context**
none

thanks!

**Comment by fedoranvar** [comment]
yup, found in https://github.com/nvim-telescope/telescope.nvim/pull/463 that it's hasn't been implemented yet,
so, i'm closing it.

**Comment by Conni2461** [comment]
Duplication of https://github.com/nvim-telescope/telescope.nvim/issues/42

We talked about this internally. There are two ways we could implement this
- Do a page jump
- Stream in new entries when scrolling. Like a new entry each time

Problem currently is only the displayed values are sorted. All others have a score but they are not sorted. 

Note #463 is not related. It does 10k and 10j jumps. It can't jump at the begging or end of the list
