### ISSUE TITLE
Strange matching behaviour

### ISSUE THREAD

**Issue by itmecho** [nvim-telescope/telescope.nvim#535]
### Description
When running `:Telescope find_files` I see strange matching behaviour. I search for `Checkbox` but I get back files like `src/reducers/helpTheClass.ts` where it's matched `bo` and `heC`.

I tried looking in the README and wiki but I can't see anything that lets me set a matching strategy.

**Expected Behavior**
I would expect it to match similarly to `fzf` where it will match the full search term or something like `(Check.*box)` instead of random parts of the string. Maybe it's not a bug but more of a preference/config thing. I feel like it should only return matches that contain all characters from my search string.

**Actual Behavior**
<img width="637" alt="image" src="https://user-images.githubusercontent.com/8384983/108347714-c102e880-71d8-11eb-912a-65e0f8dff9c5.png">

It matches sections of the search term but out of order (`bo` before `heC`)

### Details
<details><summary>Reproduce</summary>

1. `mkdir /tmp/test && cd /tmp/test && touch Checkbox.tsx helpTheClass.tsx`
2. Open nvim
3. Run `:Telescope find_files`
4. Search for `Checkbox`
</details>

<details><summary>Environment</summary>

- `nvim --version`
```
NVIM v0.5.0-dev+1089-gdc3ca16a9
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/<removed>/src/neovim/build/config -I/Users/<removed>/src/neovim/src -I/Users/<removed>/src/neovim/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/<removed>/src/neovim/build/src/nvim/auto -I/Users/<removed>/src/neovim/build/include
Compiled by <removed>

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/<removed>/.local/share/nvim"

Run :checkhealth for more info
``` 
- Operating system: MacOS 11.2.1
- Telescope commit:
```
commit 1c5e42a6a5a6d29be8fbf8dcefb0d8da535eac9a (HEAD -> master, origin/master, origin/HEAD)
Author: Asbjørn Håland <asbjornhaland@users.noreply.github.com>
Date:   Fri Feb 12 22:31:27 2021 +0100

    feat: add 'follow' opt to find_files (#530)

    This will add possibility to follow symlinks
```

</details>

<details><summary>Configuration</summary>
<p>

**NOTE:** This is the default config from the template, unchanged

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by clason** [comment]
This is due to how the ngram matcher works. I suggest installing https://github.com/nvim-telescope/telescope-fzy-native.nvim, which should give you a more expected behavior.

**Comment by elianiva** [comment]
The matching algorithms is listed here btw https://github.com/nvim-telescope/telescope.nvim#sorters

**Comment by itmecho** [comment]
Ah so it was a documentation reading failure on my part! Thanks for that, `fzy-native` is exactly what I was after!
