### ISSUE TITLE
Select current buffer when `builtin.buffers` is opened

### ISSUE THREAD

**Issue by mroavi** [nvim-telescope/telescope.nvim#537]
When `builtin.buffers` is opened, the bottom-most option is always selected:

![image](https://user-images.githubusercontent.com/19517248/108627609-d6854600-7456-11eb-87c6-cd051d75c65f.png)

My feature request is to select the current buffer from which `builtin.buffers` was opened. This is how `tmux` does it. In the example above, I was working on `test_PartialEvaluation.jl` when I opened telescope's buffers. I would like this buffer to be initally selected.

**Comment by Conni2461** [comment]
We have `sort_lastused` which does sort currently and prev opened. But it will set the selection index to prev buffer. Similar to fzf.
So you can do: `Telescope buffers show_all_buffers=true sort_lastused=true default_selection_index=1` which will reset that default selection index back to 1.
Or in lua `require'telescope.builtin'.buffers{ show_all_buffers = true, sort_lastused = true, default_selection_index = 1}`

Note that `sort_lastused` will put current and prev at the bottom of the list. If you don't wanna have this you need to write a own wrapper function that does this:
- Collect all buffnrs in table.
- Iterate table to find position of current buffer
- Set `default_selection_index` to that position

I don't think we are going to change the internal thing :) But if you write such a wrapper we could add that to the wiki :)

**Comment by mroavi** [comment]
Very clear. Thank you very much.
