### ISSUE TITLE
Error executing vim.schedule lua callback: attempt to concatenate field

### ISSUE THREAD

**Issue by huyvohcmc** [nvim-telescope/telescope.nvim#540]
### Description
telescope config:
```
telescope.setup{
    defaults = {
        vimgrep_arguments = {
            'rg',
            '--color=never',
            '--no-heading',
            '--with-filename',
            '--line-number',
            '--column',
            '--smart-case',
            '--glob "!{.git,node_modules,flow-typed}"'
        },
    }
}
```

When I use `grep_string`, I got this error:
```
Error executing vim.schedule lua callback: ...packer/start/telescope.nvim/lua/telescope/make_entry.lua:198: attempt to concatenate field 'filename' (a nil value)
```
![Screen Shot 2021-02-23 at 4 24 21 PM](https://user-images.githubusercontent.com/17645203/108823874-97402c00-75f3-11eb-85c8-8576f315efa8.png)

If I remove `'--glob "!{.git,node_modules,flow-typed}"'` from `vimgrep_arguments`, I got no error. 

- nvim --version output: NVIM v0.5.0-dev+1089-gdc3ca16a99ec
- Operating system: MacOS 10.15.7
- Telescope commit: d7c02e3b52b5a13265e071d0de2d6a989110a515

**Comment by Conni2461** [comment]
I can't make it work in bash as well. But take a look at https://github.com/nvim-telescope/telescope.nvim#options-affecting-sorting and `file_ignore_patterns`. Git should be ignored by default but something like this could help:
`file_ignore_patterns = { 'node_modules', 'flow%-typed' }`. (I think - has to be escaped with % but not sure right now) :)

**Comment by huyvohcmc** [comment]
Nice, thanks @Conni2461 file_ignore_patterns works for me

**Comment by Conni2461** [comment]
Closing i don't think this is a bug. `--glob` might be called wrongly here.
