### ISSUE TITLE
actions.move_selection_{next,previous} no longer work after scrolling the previewer.

### ISSUE THREAD

**Issue by elianiva** [nvim-telescope/telescope.nvim#545]
### Description

Telescope `action.move_selection_next` and `action.move_selection_previous` no longer work after scrolling the previewer buffer.

**Expected Behavior**

It should work as it would normally after I scroll the previewer buffer.

**Actual Behavior**

It can only jump between the topmost or the bottommost item. Here's a screencast that shows which key I'm pressing.

https://user-images.githubusercontent.com/51877647/108946286-b214ae00-7690-11eb-8b5e-cd36a9f76501.mp4

As you can see, I'm holding `<C-n>` and `<C-p>` but the cursor can only move between the topmost and the bottommost item.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. `:Telescope find_files`
3. Scroll between the result items using `<C-n>` or `<C-p>`
4. Scroll the buffer previewer using `<C-d>` or `<C-u`
5. Try to do step 3 once more.
6. It doesn't scroll like before, it only jumps between the topmost or the bottommost item.
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1109-g6b7cc45c4
- Operating system: Archlinux
- Telescope commit: b5051ee

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment]
I actually laugh for a second its a funny bug. I can't see the screen recording but tried it myself and its reproducible.

Advanced normal mode introduced it. And i think it has something to do with the count in `shift_selection`. If you wanna take a look at it @elianiva feel free otherwise i doo it in ~10h

**Comment by elianiva** [comment]
lol, you're right, the video is broken for some reason. I'll try to take a look at it, thanks for the hint!

**Comment by elianiva** [comment]
I fixed it but idk if it's the best solution. I just check the current mode before moving to the next/previous item, if we're on insert mode, ignore the count because you won't be able to do something like `12j` from insert mode.

```diff
 set.shift_selection = function(prompt_bufnr, change)
   local count = vim.v.count
   count = count == 0 and 1 or count
+  count = a.nvim_get_mode().mode == "n" and count or 1
   action_state.get_current_picker(prompt_bufnr):move_selection(change * count)
 end
```

**Comment by Conni2461** [comment]
Seems good.

I just ran into `M` (middle) not working for "descending" if `num_results` is smaller than `max_results` if you wanna look into this too. :) thanks
