### ISSUE TITLE
Error executing luv callback: attempt to index field '_tracked_node' (a nil va lue)                                                                                           

### ISSUE THREAD

**Issue by kevinpita** [nvim-telescope/telescope.nvim#549]
### Description

I can't use telescope, when opening find files (just an example) the window appears but it doesn't work and I get tons of errors

**Expected Behavior**

Telescope to work

**Actual Behavior**

```
Error executing luv callback:
...ugged/telescope.nvim/lua/telescope/algos/linked_list.lua:77: attempt to index field '_tracked_node' (a nil va
lue)                                                                                                            
Press ENTER or type command to continue                                                                         
Error executing luv callback:
cannot resume dead coroutine
Press ENTER or type command to continue
Error executing vim.schedule lua callback: ...lugged/telescope.nvim/lua/telescope/pickers/scroller.lua:59: Must 
never return a negative row: { result = -2, args = { -1 1 -2 } }
```

after that an infinite loop of
```
Press ENTER or type command to continue
Error executing luv callback:
cannot resume dead coroutine
```

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :Telescope find_files
</details>

<details><summary>Environment</summary>

- nvim --version output:  NVIM v0.5.0-dev+1108-g0450e155d
- Operating system:  Linux ubuntudesktop 5.8.0-43-generic - Ubuntu 20.04.1
- Telescope commit: 1c5e42a

</details>

<details><summary>Configuration</summary>
<p>

```viml



call plug#begin('~/.vim/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>


lua << EOF
require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    initial_mode = "insert",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {
      -- TODO add builtin options.
    },
    file_sorter =  require'telescope.sorters'.get_fuzzy_file,
    file_ignore_patterns = {},
    generic_sorter =  require'telescope.sorters'.get_generic_fuzzy_sorter,
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
    set_env = { ['COLORTERM'] = 'truecolor' }, -- default = nil,
    file_previewer = require'telescope.previewers'.vim_buffer_cat.new,
    grep_previewer = require'telescope.previewers'.vim_buffer_vimgrep.new,
    qflist_previewer = require'telescope.previewers'.vim_buffer_qflist.new,

    -- Developer configurations: Not meant for general override
    buffer_previewer_maker = require'telescope.previewers'.buffer_previewer_maker
  }
}
EOF

```

**Comment by Conni2461** [comment]
Thats really weird :thinking: It happens with that config and `-nu`
First of all can you make sure plenary and telescope are up to date.
Also what are you using for finding? `fd`, `ripgrep` or `find`? So basically which one is installed.

**Comment by kevinpita** [comment]
> Thats really weird thinking It happens with that config and `-nu`
> First of all can you make sure plenary and telescope are up to date.
> Also what are you using for finding? `fd`, `ripgrep` or `find`? So basically which one is installed.

Yes, using -nu too
everything up to date
I have installed ripgrep (as rg) and find as system default

**Comment by Conni2461** [comment]
Hmm i have no idea whats going on.

Could you run `make test` in telescope directory? Maybe it will tell us something

**Comment by kevinpita** [comment]
Everything succeeded 0 fails/errors

**Comment by Conni2461** [comment]
Thats super weird now. Because we have integration tests that run `Telescope find_files`, search for a file in the repository and open it. We are using a `minimal_init.vim` for that.

So running: `nvim -nu scripts/minimal_init.vim` in telescope root. Does this make `Telescope find_files` work?

**Comment by tami5** [comment]
I'm getting invalid scrolling strategy with that configuration

**Comment by tami5** [comment]
No it works fine no errors, odd

**Comment by kevinpita** [comment]
> Thats super weird now. Because we have integration tests that run `Telescope find_files`, search for a file in the repository and open it. We are using a `minimal_init.vim` for that.
> 
> So running: `nvim -nu scripts/minimal_init.vim` in telescope root. Does this make `Telescope find_files` work?

No :( same error

**Comment by Conni2461** [comment]
I am soooooooo lost right now :sob: 
Okay can you rebuild neovim with `make distclean` and then rebuild.
Remove the plugins and clone again.
And paste the whole `nvim --version` Maybe something is odd with the lua version. Are you using: `LuaJIT 2.1.0-beta3`

**Comment by clason** [comment]
Also make sure to update `plenary.nvim` to the latest version!

**Comment by kevinpita** [comment]
every plugin is up to date
```
NVIM v0.5.0-dev+1111-g7d82aaa6f
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/kevin/clone/neovim/build/config -I/home/kevin/clone/neovim/src -I/home/kevin/clone/neovim/.deps/usr/include -I/usr/include -I/home/kevin/clone/neovim/build/src/nvim/auto -I/home/kevin/clone/neovim/build/include
Compiled by root@ubuntudesktop

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

```

Using `LuaJIT 2.1.0-beta3`

I have just distclean, pull and rebuild. Same status :(

**Comment by kevinpita** [comment]
> I am soooooooo lost right now sob
> Okay can you rebuild neovim with `make distclean` and then rebuild.
> Remove the plugins and clone again.
> And paste the whole `nvim --version` Maybe something is odd with the lua version. Are you using: `LuaJIT 2.1.0-beta3`

I found the problem :)

So, I'm using Gnome, gnome-terminal seems to cause the issue. 
I have just installed Alacritty and it works!

![imaxe](https://user-images.githubusercontent.com/69063372/109657899-e8a16b80-7b5d-11eb-8f56-5a27c0d632e7.png)

**Comment by elianiva** [comment]
that is super weird :rofl:

**Comment by Conni2461** [comment]
Works fine for me with gnome-terminal. Whats your `TERM` env when using gnome?

I just always suggest setting it to `export TERM=xterm-256color`.

**Comment by kevinpita** [comment]
Same TERM as you have suggested.

Ok, real "problem" here, I always use a big line height + big font size.

If I put it to 14 rows (included) or lower it gives me the error, if I put it more than 14 it just works

**Comment by elianiva** [comment]
That's odd, I tried to reproduce it using this stupidly large font size on gnome-terminal and it still works.

https://user-images.githubusercontent.com/51877647/109777398-40aba100-7c36-11eb-8e0b-6bb9d47a8b80.mp4

**Comment by Kavantix** [comment]
I also ran into this, seems to be caused by `scroll-strategy = 'limit'`
If I have that turned on and there are no results this error is thrown

**Comment by beauwilliams** [comment]
I can confirm setting `scroll_strategy ="limit"`

Causes a bug on my machine  

`/start/telescope.nvim/lua/telescope/pickers/scroller.lua:59: Must never return a negative row: { result = -1, args = { 15 0 0 } }`

**Comment by jaapz** [comment]
When I put a `preview_height` thats larger than my window, I get the same error and telescope renders all fucky

**Comment by devinjameson** [comment]
I got this error with my `layout_config` height options were causing the telescope floating window to be super super short. I had "height" set to "1", thinking that it would be "100%", but it actually was "1 line".

This caused a bug:
```
layout_config = {
  prompt_position = "top",
  preview_cutoff = 120,
  horizontal = { width = 0.8, height = 1, mirror = false },
  vertical = { mirror = false }
},
```
This works:
```
layout_config = {
  prompt_position = "top",
  preview_cutoff = 120,
  horizontal = { width = 0.8, height = 0.8, mirror = false },
  vertical = { mirror = false }
},
```

**Comment by Conni2461** [comment]
Stale for quite some time. Closing. I dont think this is still an issue. If I am wrong feel free to reopen and provide new up to date information :)
