### ISSUE TITLE
How to use sk or fzf

### ISSUE THREAD

**Issue by Kyle-Thompson** [nvim-telescope/telescope.nvim#55]
I'm a little confused at the architecture of the plugin. It seems like the "scorer" does the job that fzf or sk would typically do but does so in a built in way that I have to say is less than ideal. There doesn't seem to be any documentation on how to replace the built in functionality with fzf or sk or anything like that.

**Comment by tjdevries** [comment]
Sorry for the late response, I have a plan on how to use these in the future.

I will add documentation when it's available.
