### ISSUE TITLE
Fuzzy search algorithm requiring multiple characters to match a word?

### ISSUE THREAD

**Issue by jesseleite** [nvim-telescope/telescope.nvim#550]
#### _**Disclaimer:** Telescope is SICK! Really excited about the work you are doing!_ ❤️

If I have two files, say `install` and `install.conf.yaml`, and I want to open the latter file, I have to sometimes type multiple characters for the fuzzy algorithm to match a word. Not sure if this is a bug, or something that is configurable. If it's by design, I apologize for this issue.

**Expected Behavior**

In Fzf, trying to fuzzy search `install y` to select `install.conf.yaml works...

![CleanShot 2021-02-24 at 10 06 37](https://user-images.githubusercontent.com/5187394/109023426-c5bd1600-768a-11eb-88b2-b136b6b11d90.gif)

**Actual Behavior**

In Telescope, trying to fuzzy search `install y` isn't enough, I need to `install yam` for it to match the file...

![CleanShot 2021-02-24 at 10 07 48](https://user-images.githubusercontent.com/5187394/109023592-ef763d00-768a-11eb-99fb-e6b162278405.gif)

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. Create two files in project: `install` and `install.conf.yaml`
2. :Telescope file_files and try to fuzzy search the latter file with `install y`
3. Notice you have to `install yam` for it to select that file. A `y` isn't enough.
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev+6b7cc45
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210224-61858-t4ge9j/build/config -I/tmp/neovim-20210224-61858-t4ge9j/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210224-61858-t4ge9j/build/src/nvim/auto -I/tmp/neovim-20210224-61858-t4ge9j/build/include
Compiled by jesseleite@Jesses-MBP
```
- Operating system: macOS Big Sur 11.2.1
- Telescope commit: 8b3d08d

</details>

<details><summary>Configuration</summary>
<p>

```viml
call plug#begin()
 
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
 
call plug#end()
```

**Comment by Conni2461** [comment]
You probably should setup `sorters.get_fzy_sorter` or https://github.com/nvim-telescope/telescope-fzy-native.nvim
Example to setup `sorters.get_fzy_sorter`
```lua
require('telescope').setup{
  defaults = {
    file_sorter =  require'telescope.sorters'.get_fzy_sorter,
    generic_sorter =  require'telescope.sorters'.get_fzy_sorter,
  }
}
```
We should make that one default. I think. I think someone already suggested that in better defaults issue

**Comment by jesseleite** [comment]
@Conni2461 Rad thanks, I'll have to give it a try. That said, the nerdy part of me is curious what the default sorter is actually doing?

I have another example where I'm trying to fuzzy search for `vim/config/fugitive.vim` with `v fugitive`, and the `v` is not though. In that case, `vi` (2 characters) is enough. Whereas in the above case, `yam` (3 characters) is required. What is it looking for, that it inconsistently needs more input data to properly match?

**Comment by clason** [comment]
The [default sorter](https://github.com/nvim-telescope/telescope.nvim/blob/8b3d08d7a6e8eccc2997ccbf91a7e12d506196e5/lua/telescope/sorters.lua#L147) algorithm is based on ngrams, with n=2 by default (you can pass other values as an option if you want to customize it).

I second the recommendation for `fzy-native`; it's enough to load the extension to out of the box get matching/sorting that is much closer to FZF.

**Comment by jesseleite** [comment]
Hmm, I realize at this point that this isn't a bug, but me asking for customer support (I am sorry, we can close this issue any time I'm being a bother)!  That said, I tried the `get_fzy_sorter` as you suggested @Conni2461, and now I lose my results as soon as I type `y` 🤔

![CleanShot 2021-02-24 at 11 19 13](https://user-images.githubusercontent.com/5187394/109030846-2bf96700-7692-11eb-8137-fa3d908d5a93.gif)

**Comment by Conni2461** [comment]
Its just a different sorting alg than fzf. `fzy` strips away the trailing whitespaces but as soon as you have `install y` it recognizes that whitespace and can't find it in the matches so the score will be below 0.
fzf just ignores whites completely. We have https://github.com/nvim-telescope/telescope-fzf-writer.nvim which uses fzf which could help(i actually never tried it).
Something else i suggested some time ago was doing something similar to `fzy-native`. Porting fzf sorter from go to c and providing `fzf-native`. Something like that should be possible just takes a lot of time doing.

**Comment by jesseleite** [comment]
>Btw instally should give you the correct result

@Conni2461 It does indeed. However, I think fzf does more than just ignoring whitespaces. When you separate terms with spaces, I think it'll treat each word as it's own fuzzy search. Then with this [search syntax](https://github.com/junegunn/fzf#search-syntax) you could searching something like:

```'fug lua$ v```

...to match something like `vim/fugtive.lua`

- 1st term `fug` is searched as exact match, because it's prefixed with `'`
- 2nd term `lua` is searched as a matching suffix because of the `$` 
- 3rd term `v` is enough to scope to `vim` directory

With fzf, it doesn't even matter the order you enter those 3 terms, so I think it does more than just ignore whitespace, nawmean?

It's cool for Telescope to have different defaults, but it's not clear in the Telescope readme how the default algorithm works, so it's a bit jarring for fzf users coming over. Not complaining though, just learning! ❤️

**Comment by Conni2461** [comment]
yeah fzf and fzy are just different algorithms. fzy is a small and fast fuzzy finder while fzf is fast and has a lot of features. You can see the lua impl of fzy [here](https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/algos/fzy.lua)

Yeah i agree that telescope default and documentation of ngram isn't that great and can be improved. But we have that problem in a lot of areas and are working on a tree sitter docgen generator (function header -> vim documentation).

So to achieve that search syntax we need to implement fzf ourselves (or fzf writer but that works differently). One way (easier but still pretty hard) would be to implement that algorithm in lua. For us a sorter is just a function that can be replaced. Someone can write the interface -> tests with plenary.busted and then port that go code to lua. I think its that [code](https://github.com/junegunn/fzf/blob/master/src/algo/algo.go) we are mainly interested in.

Alternative and probably the better version would be to check if we can generate a lib/shared object of that go code (i don't know go) so we can use ffi to call the underlying algorithm. If that is not possible we need to port it to c, write ffi binding, (can use plenary.busted for tests again) and package that as fzf-native similar to fzy-native. I think a lot of people would like that and this solution should be faster than the lua one. Like the fzy one.

A third solution that just popped in my head is `skim`/`sk` maybe we can export the lib into a shared object and then write bindings (the rust docs at least say that ffi bindings into rust libs are possible. [See](https://doc.rust-lang.org/1.5.0/book/rust-inside-other-languages.html#ruby))

Thats my thoughts on that topic. Would be a cool project, tough but cool.

> Not complaining though, just learning!

All good. Its fun talking about those things

**Comment by jesseleite** [comment]
Love the idea of an fzf-native option, both in terms of speed, and in terms of fzf's [algorithm and query syntax features](https://github.com/junegunn/fzf#search-syntax). Some of us are so used to using fzf on the command line, or fzf.vim, that the speed and algorithm were immediately noticeable coming over to Telescope.

I could totally learn to love Telescope's sorting/algorithms, but fzf is fast, viable, and already very common, so I see the benefit of fzf-native for us fzf lovers coming over to Telescope. That said, I absolutely love the non-VimL extendability of Telescope ❤️

>Its fun talking about those things

Appreciate the discussion!

**Comment by clason** [comment]
> Love the idea of an fzf-native option, both in terms of speed, and in terms of fzf's [algorithm and query syntax features](https://github.com/junegunn/fzf#search-syntax). Some of us are so used to using fzf on the command line, or fzf.vim, that the speed and algorithm were immediately noticeable coming over to Telescope.

Do you still see such a huge performance and quality gap with `fzy-native` installed?

**Comment by Conni2461** [comment]
I also wouldn't say we would get any performance improvements with a fzf-native compared to fzy-native. Just a more wide "syntax" and different sorting algorithm. 
We need to do other things for better speed. Currently just too much string processing happens on neovim event loop rather than in another thread but tj had some new ideas and wanted to work on that at some point.

**Comment by jesseleite** [comment]
Between `fzy-native` and which, the default lua sorting, or fzf? Personally can't feel a performance difference between fzy-native and fzf; Both are fast as hell. I just miss the fzf [query syntax](https://github.com/junegunn/fzf#search-syntax).

**Comment by clason** [comment]
fzy vs fzf -- thanks, that was exactly what I was interested in (it's about the query, not performance)

I agree that installing fzy should be a no-brainer ;)

**Comment by Conni2461** [comment]
Status update abou `telescope-fzf-native.nvim` progress for everyone subbed to this thread:
![image](https://user-images.githubusercontent.com/15233006/114577581-68057d00-9c7c-11eb-965c-2bfe4a4af175.png)

Missing:
- invert
- and probably more, i am not thinking about right now :rofl:

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope-fzf-native.nvim

Read the friendly readme ;)

Also highlighting for prefix_match does not work because how telescope handles things. But i didn't want that you have to wait until eternity laughing i will fix that at some point

**Comment by Conni2461** [comment]
I think we can close this for now. The implementation is not perfect, i know but all other issues can be tracked in the extension repo
