### ISSUE TITLE
feat: caret change options

### ISSUE THREAD

**Issue by yamatsum** [nvim-telescope/telescope.nvim#552]
**Is your feature request related to a problem? Please describe.**
`prompt_prefix` can be changed by option, but `caret` cannot be changed.

**Describe the solution you'd like**
I hope to be able to change caret with `setup()` method
https://github.com/nvim-telescope/telescope.nvim/blob/4dd35ef0e154ab1836fc923a33196a4101a97a9c/lua/telescope/pickers.lua#L745

<img width="590" alt="Screen Shot 2021-02-25 at 14 49 25" src="https://user-images.githubusercontent.com/42740055/109109946-90432600-7779-11eb-889d-9d4c91b0550d.png">

By the way, it would be nice to be able to add padding on the left.

**Describe alternatives you've considered**

**Additional context**

**Comment by tami5** [comment]
:heart_eyes: is this an icon of telescope where can I find it.

Ability to set caret globally make sense, but It shouldn't not override preset by prompt, e.g. some users have stuff like:

```lua
  oldfiles = {
    prompt_prefix = "Recent>",
  },
  qf = {
    prompt_prefix = "QFlist>",
  },
  stags = {
    prompt_prefix = "Tags>",
    hide_filename = true,
    full = true
  },

```

**Comment by yamatsum** [comment]
> 😍 is this an icon of telescope where can I find it.

This is from octicons.
I extended this to create a font.
https://github.com/yamatsum/nonicons
I plan to create a plugin that is compatible with Nvim-web-devicons

> Ability to set caret globally make sense, but It shouldn't not override preset by prompt, e.g. some users have stuff like:

It is not overwritten by prompt.
It is supposed to add the change option of caret completely independently.

**Comment by Conni2461** [comment]
Yeah should be doable. Thanks for the suggestion. I can do this in the next 2 days. I wanted to make a PR with some super small changes anyway. I will add this to the list. Unless someone else does it in the meantime :)

Do you want a padding on the left for all the other items? Because that might actually be a font issue on your side. They already line up perfectly for me. And for elianiva as well. See gif in README

@tami5 he is not talking about the prompt its that small thingy/prefix in the results list which indicates the current selection.

**Comment by yamatsum** [comment]
> Do you want a padding on the left for all the other items? Because that might actually be a font issue on your side. They already line up perfectly for me. And for elianiva as well. See gif in README

yes. The display is not broken, but it is more beautiful with padding.

no padding
<img width="312" alt="Screen Shot 2021-02-25 at 18 50 05" src="https://user-images.githubusercontent.com/42740055/109135403-60584a80-779a-11eb-9b48-a6ebe49048b0.png">

with left padding
<img width="313" alt="Screen Shot 2021-02-25 at 18 50 33" src="https://user-images.githubusercontent.com/42740055/109135427-677f5880-779a-11eb-8e42-1929b4de7af5.png">

**Comment by tami5** [comment]
@yamatsum how do install your awesome stuff :laughing: it looks so much better then the default I have

**Comment by yamatsum** [comment]
@tami5 I created a suitable configuration repository.
https://github.com/yamatsum/nvim-web-nonicons
