### ISSUE TITLE
Is there any easy way to create a command?

### ISSUE THREAD

**Issue by lourenci** [nvim-telescope/telescope.nvim#555]
Sorry if this is not the right place to raise questions, but it's not clear to me reading the docs how to extends/create new commands.

Is there any easy way to do that?

I would like to iterate over all files changed from origin/master. In fzf, I could do that:

`command! -bang GFilesChangedFromMaster call fzf#run(fzf#wrap({'source': 'git diff --name-only --diff-filter=d origin/master'}, <bang>0))`

Thanks for the plugin.

**Comment by tami5** [comment]
hmmm 

```lua

GFilesChangedFromMaster = function(opts)
  -- By creating the entry maker after the cwd options,
  -- we ensure the maker uses the cwd options when being created.
  opts.entry_maker = opts.entry_maker or make_entry.gen_from_file(opts)

  pickers.new(opts, {
    prompt_title = 'Git File',
    finder = finders.new_oneshot_job(
      vim.tbl_flatten( {
        "git", "diff", "--name-only", "--diff-filter=d", "origin/master"
      } ),
      opts
    ),
    previewer = conf.file_previewer(opts),
    sorter = conf.file_sorter(opts),
  }):find()
end

```

btw copy/paste with some modification from `/lua/builtin/git.lua` you should take a look, all builtin are created the same way but this file is specific to git pickers, if you want preview there are a function with `previewer` field set to diff.

Hope that helps
