### ISSUE TITLE
[Trivial Question] What Color Scheme is used in Gallery? 

### ISSUE THREAD

**Issue by alexpopov** [nvim-telescope/telescope.nvim#556]
The [Gallery](https://github.com/nvim-telescope/telescope.nvim/wiki/Gallery) has a really nice Cobalt-esque blue colorscheme. Is that available somewhere? 

Thanks!

**Comment by tami5** [comment]
I might be wrong, but I think its a custom colorscheme from @pwntester :laughing:

**Comment by pwntester** [comment]
Yep, just published it in case you want to give it a try:
https://github.com/pwntester/nautilus.nvim

**Comment by alexpopov** [comment]
Thanks so much for getting back to me and the link! It's a beauty!
