### ISSUE TITLE
Not possible to create `<Esc>` insert mode mapping for prompt buffer?

### ISSUE THREAD

**Issue by jesseleite** [nvim-telescope/telescope.nvim#561]
### Description

I usually reach for my `jk` exit insert mode mapping, and would prefer if `<Esc>` would just close Telescope. Thus, I add this insert mapping to tell Telescope to close. Other insert mappings work, but it doesn't seem I can remap `<Esc>`.

```lua
mappings = {
  i = {
    ["<Esc>"] = require('telescope.actions').close,
  },
},
```

Also curious, I'm reading through the source and cannot figure out what filetype the prompt buffer is? If I wanted to create specific filetype mappings outside of my Telescope config for the prompt buffer, is it possible for me to hook onto some kind of filetype or `TelescopePromptBufnrEnter` autocmd?

**Expected Behavior**

I would expect the above mapping to take precedence over any other `<Esc>` mappings.

**Actual Behavior**

Hitting `<Esc>` still exits insert mode, and Telescope does not close.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. Open a Telescope finder
3. With the above mapping, hit `<Esc>`
4. Notice Telescope is not closed
</details>

<details><summary>Environment</summary>

- nvim --version output:
```
NVIM v0.5.0-dev+6b7cc45
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210224-61858-t4ge9j/build/config -I/tmp/neovim-20210224-61858-t4ge9j/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210224-61858-t4ge9j/build/src/nvim/auto -I/tmp/neovim-20210224-61858-t4ge9j/build/include
Compiled by jesseleite@Jesses-MBP
```
- Operating system:  macOS Big Sur 11.2.1
- Telescope commit:  8b3d08d

</details>

<details><summary>Configuration</summary>
<p>

```viml
call plug#begin()

Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'

call plug#end()

lua << EOF
require('telescope').setup{
  mappings = {
    i = {
      ["<Esc>"] = require('telescope.actions').close,
    },
  },
}
EOF
```

**Comment by Conni2461** [comment]
configuration is wrong. `mappings` has to be inside the `defaults` tbl. See https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#mapping-esc-to-quit-in-insert-mode

**Comment by jesseleite** [comment]
@Conni2461 Ah shoot, I am sorry! RTFM. Thank you 😅
