### ISSUE TITLE
Prompt buffer ftplugin config or autocmd event?

### ISSUE THREAD

**Issue by jesseleite** [nvim-telescope/telescope.nvim#562]
### Description

I apologize, this is not a bug with Telescope per sey, but more of a question around how to deal with conflicting plugins, and/or create `ftplugin` behaviour for the Telescope prompt specifically.

For a more concrete example of my problem, I have [pear-tree](https://github.com/tmsvg/pear-tree) also installed, and hitting `<Enter>` in Telescope does not confirm and open the file result. I can disable specfic buffer filetypes in my pear-tree config:

```vim
let g:pear_tree_ft_disabled = []
```

However, reading the source, I'm struggling to find what filetype the Telescope prompt bufnr uses? Does the Telescope prompt have a unique filetype that we can hook `ftplugin` config on and/or `BufEnter` style autocmds on?

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. Open a Telescope finder
3. Search for something and hit `<Enter>`
4. Notice the result is not opened, due to a conflict with pear-tree.
</details>

<details><summary>Environment</summary>

- nvim --version output:
```
NVIM v0.5.0-dev+6b7cc45
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210224-61858-t4ge9j/build/config -I/tmp/neovim-20210224-61858-t4ge9j/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210224-61858-t4ge9j/build/src/nvim/auto -I/tmp/neovim-20210224-61858-t4ge9j/build/include
Compiled by jesseleite@Jesses-MBP
```
- Operating system:  macOS Big Sur 11.2.1
- Telescope commit:  8b3d08d

</details>

<details><summary>Configuration</summary>
<p>

```viml
call plug#begin()

Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'tmsvg/pear-tree'

call plug#end()

```

**Comment by Conni2461** [comment]
filetype is `TelescopePrompt` see https://github.com/nvim-telescope/telescope.nvim#how-to-add-autocmds-to-telescope-prompt- and
https://github.com/nvim-telescope/telescope.nvim/blob/d37dc88eab1be7dc853af212537fdeb9fe2542a7/lua/telescope/pickers.lua#L501-L502

**Comment by jesseleite** [comment]
@Conni2461 Dang, I'm sorry for another RTFM failure. Walking away in shame.

**Comment by Conni2461** [comment]
:laughing: Yeah read the friendly manual. :rofl: 

I have to admit doc is not that great. We will add more documentation soon. But we are trying a new way with document generation with custom tree-sitter grammar and a document parser written in lua. We just merged the first version and can now start writing function header documentation and CI just generates the resulting `doc/telescope.txt`

See #370

**Comment by jesseleite** [comment]
Very cool. That said, the `TelescopePrompt` filetype was quite clear in the readme, I just missed it somehow 😢
