### ISSUE TITLE
git_branches no action working

### ISSUE THREAD

**Issue by gennaro-tedesco** [nvim-telescope/telescope.nvim#565]
### Description
`git_branches` does not switch branch on enter. Is this the expected behaviour or must one configure the git action on selection?

**Expected Behavior**
I would expect that selecting the branch in the list would automatically switch.

**Actual Behavior**
No response is given upon selection.

### Details

1. navigate to any git repository
2. `:Telescope git_branches`
3. branches show effectively together with their own commits tree
4. upon selection (`<CR>` on branch name) nothing happens (I would expect the branch to switch to selection)

- nvim --version
```
nvim --version
NVIM v0.5.0-dev+1083-g1aec5ba85
Build type: Release
LuaJIT 2.1.0-beta3
```
- Operating system
```
macOS BigSur 11.2.1
```

**Comment by Conni2461** [comment]
Hmm it should. I don't like that we are not giving any feedback. I gonna change that and i am going to add a error message when return value is not 0. Maybe we can track it down :)

**Comment by gennaro-tedesco** [comment]
Thank you, I will try out the new branch :).

By the way, can one configure the actions on `git_branches` using a similar grammar like in `setup()`? Namely something along the lines of
```
git_branches = {
    mappings = {
        ["<cr>"] = switch branch,
        ["<C-t>"] = track and checkout,
        ["<C-d>"] = delete branch,
        ....
    }
}
```
I am sure one could override the original picker by themselves, but given that more or less everybody would want to switch/delete/diff branches (that is the entire point of a git checkout) it may be convenient to expose it as option (I assume they are not yet, correct me if I a wrong!).

**Comment by Conni2461** [comment]
There is a way to do this for a builtin. Not like you suggested because that would require some internal changes in setup but you can basically write your own wrapper function that injects new actions. I suggested that a couple of weeks ago. See https://github.com/nvim-telescope/telescope.nvim/pull/472#issuecomment-770028668

That is implemented now. But currently that would require you to define those actions. These are pretty common ones so i could add them :)

So you can do something like this afterwards:

```lua
require'telescope.builtin'.git_branches({ attach_mappings = function(_, map)
  map('i', '<c-t>', actions.track_branch)
  map('i', '<c-d>', actions.delete_branch)
  map('i', '<c-r>', actions.rebase_branch)
  return true
end})
```

**Comment by gennaro-tedesco** [comment]
Woow this is fantastic, thank you very much! I guess we can close this issue as it answered all questions I had :)

**Comment by Conni2461** [comment]
I would prefer to close it when the branch is merged (95% today) :)

**Comment by Conni2461** [comment]
I added those actions. Should i also map them?
I named them
- actions.git_track_branch
- actions.git_delete_branch
- actions.git_rebase_branch

**Comment by gennaro-tedesco** [comment]
I would say providing a default mapping can do no harm and would help the users set it up more quickly (or alternatively a link in the README where users can look up how to set them up themselves) :-)

**Comment by Conni2461** [comment]
I mapped:
- actions.git_track_branch (`<C-t>` both insert and normal)
- actions.git_rebase_branch (`<C-r>` both insert and normal)

I didn't map delete because it could be dangerous. Especially on <c-d> which is default for scrolling.

I ask someone for review and will merge

**Comment by gennaro-tedesco** [comment]
Great, thank you very much!! (Perhaps on a second iteration more down the road, some actions could prompt the user for confirmation, say delete/rebase or so, but this is of course second order approximation).

**Comment by Conni2461** [comment]
Confirmation sounds like a good thing to do. Adding that after that i merge :)
