### ISSUE TITLE
help tags extremely slow

### ISSUE THREAD

**Issue by gennaro-tedesco** [nvim-telescope/telescope.nvim#566]
### Description
`help_tags` search is extremely slow. From what I have seen this is due to the fact that the help tags not only search among the tags but also through the _text_ of such tags, thereby massively increasing the response time. Is this the expected behaviour? I would say that one can benefit from reducing the scope of the search and only look up tags instead (assuming this is not what happens at the moment, please correct me if I am wrong).

### Details
In order to reproduce the issue I am comparing the `help_tags` function provided by Telescope against a similar one provided by `fzf.vim`. Whilst on "small queries" the two are comparable, on big queries Telescope is redundantly slower. Try search for "nvim open", for instance

1. open a nvim empty
2. `:Telescope help_tags`
3. search for `nvim open...`

I do not have numerical benchmarks to support my claim, however, as I have not measured them.

- nvim --version
```
nvim --version
NVIM v0.5.0-dev+1083-g1aec5ba85
Build type: Release
LuaJIT 2.1.0-beta3
```
- Operating system
```
macOS BigSur 11.2.1
```

**Comment by Conni2461** [comment]
We are matching for `ordninal` which is only set to the tags name.
https://github.com/nvim-telescope/telescope.nvim/blob/d37dc88eab1be7dc853af212537fdeb9fe2542a7/lua/telescope/builtin/internal.lua#L407

Which sorting algorithm are you using? That one? https://github.com/nvim-telescope/telescope-fzy-native.nvim If not you probably should because its a speed boost that comes for free :rofl: But it won't move mountains

**Comment by gennaro-tedesco** [comment]
thank you for your quick reply: I have not specified any sorting algorithm myself, so I guess I am using the default. I will be trying out some others to see if they speed up.

After a few more tries I am led to think that the apparent lag is due to the help text preview: the tags are being fetched quickly by the algorithm(s) but the delay is caused by synchronisation with the preview (understandably, since the help text are a massive wall of text). I believe there is a way to switch previews off for certain pickers, I will look into it myself.

**Comment by Conni2461** [comment]
`Telescope help_tags previewer=false`

Yeah default is still ngram sorter which isn't the faster. So i suggest using fzy.

The previewers shouldn't make that much of a difference because they are using some libuv async magic :rofl:

**Comment by gennaro-tedesco** [comment]
I confirm that using 
```
## preview false
:lua require'telescope.builtin'.help_tags({previewer=false})<cr>

## telescope options
file_sorter =  require'telescope.sorters'.get_fzy_sorter,
```
_does_ indeed speed it up consistently. In particular I noticed that removing the preview is what gives the biggest boost (somehow contrary to your statement above 😅 ).

Thank you very much for your help!

**Comment by Conni2461** [comment]
Another tip for more speed use fzy-native (repo i linked earlier). It uses fzy c lib and c is way better in handling speed. That what i do and i don't notice a speed difference with that :laughing: 

The line you mentioned about:
` file_sorter =  require'telescope.sorters'.get_fzy_sorter, ` will load the lua port which isn't that much faster than ngram. 
You need to do after telescope.setup :)
```lua
require('telescope').load_extension('fzy_native')
```

And i might have overselled the previewers async ness. Some things still need to happen in main thread but reading file is async, and will happen only once. So e.g. telescope help file will be read once and when i scroll thought the results i just reuse the buffer and change the linenr.

**Comment by Conni2461** [comment]
Closing this for now we have a issue that tracks slowness in general: #392 and people are working on it :)
