### ISSUE TITLE
Telescope lsp_workspace_symbols not functioning

### ISSUE THREAD

**Issue by jacksonludwig** [nvim-telescope/telescope.nvim#568]
### Description

``:Telescope lsp_workspace_symbols`` not functioning.
**Expected Behavior**

``:Telescope lsp_workspace_symbols`` launches the finder and displays the workspace symbols sent from the LSP.
**Actual Behavior**

``:Telescope lsp_workspace_symbols`` has no effect; it is as if ``:Telescope lsp_workspace_symbols`` is an unrecognized command. This is the case even when the LSP supports workspace symbols, e.g. ``:lua vim.lsp.buf.workspace_symbol()<CR>`` works.
### Details

<details><summary>Reproduce</summary>

1.) Use simple test.vim config
2.) Go to a python project (or any other language/LSP if you prefer)
3.) Run ``:Telescope lsp_workspace_symbols``
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/nn2wx8i57jqqsd4qaajfg66i83vyia1y-neovim-nightly-master/share/nvim"

Run :checkhealth for more info
```
- Operating system: Ubuntu (+ nix/home-manager)
- Telescope commit: 84732d1d780f1aecb799502be97ec3a403066268

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'neovim/nvim-lspconfig'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}

require'lspconfig'.pyright.setup{}
EOF

```

**Comment by Conni2461** [comment]
Thanks for reporting. pyright expects a query. I have already a PR ready that prints a message in that case. I am about to merge that PR :)

For now: `Telescope lsp_workspace_symbols query=something` should work. We just use a empty string as query and most servers will show all workspace symbols in that case but pyright and clangd don't

**Comment by jacksonludwig** [comment]
Alright, that would make sense. However, in three LSPs I've used (tsserver, gopls, and pyright) I still get this issue even with ``query=something``, just to be clear. @Conni2461 

In the past I called ``vim.lsp.buf.workspace_symbol()`` with an empty string and it worked just fine with telescope set as the handler.

**Comment by jacksonludwig** [comment]
Welp... regardless your PR fixed the issue XD, thanks and ignore my last comment

**Comment by Conni2461** [comment]
Can't comment for `tsserver` and `gopls` but `pyright` just worked for me. I tested that :rofl: 
I don't know what the specification says for an empty string.

Good to hear that this fixes your issue :)

**Comment by ranjithshegde** [comment]
btw the issue still exists for ccls. Same error as above

**Comment by Conni2461** [comment]
@ranjithshegde yeah because this issue isn't fixable from our side. `ccls`, `clangd` and probably more are not returning results for an empty query.
So what i am doing is i have this mapped:
```
lua require'telescope.builtin'.lsp_workspace_symbols({ query = vim.fn.input("Query >") })
```

So if i know that my lsp accepts an empty query like sumneko i just press enter again and if not i can type in my query

**Comment by ranjithshegde** [comment]
> ```
> lua require'telescope.builtin'.lsp_workspace_symbols({ query = vim.fn.input("Query >") })
> ```
Thanks. that worked like a chard. I just changed it to `query = vim.fn.expandd ('<cword>')` to get symbol under cursor

Live grep sounds nice!

**Comment by eulertour** [comment]
> I am thinking about a live grep version of `workspace_symbols` lately. Maybe something like this could solve that problem.

Please do, this is one of the major advantages of coc.nvim

**Comment by oberblastmeister** [comment]
@ranjithshegde @eulertour `live_workspace_symbols` is here! #705
