### ISSUE TITLE
Feature: show remote/local, last committer and date in branch list

### ISSUE THREAD

**Issue by kyoh86** [nvim-telescope/telescope.nvim#569]
**Is your feature request related to a problem? Please describe.**

`builtin.git_branch` shows many branches at once.
Often I can NOT select a target quickly.

If they are shown with remote/local, last committer and last commit date, I may be able to find a target easily.

When I was using Fzf, I wrote a configuration to display and switch that list using my tool, [git-branches](https://github.com/kyoh86/git-branches).

![a49fc69bdb8c91b94ff565a168e235c9](https://user-images.githubusercontent.com/5582459/109394306-ac0d1e80-7969-11eb-9710-8008f859f09b.png)

So I am convinced that this feature will improve the identifiability of the branch.

**Comment by Conni2461** [comment]
Seems like a good idea. I just don't know go so i would try to do that without looking at your code.
Or if you say you wanna give it a try feel free to do so :)

**Comment by kyoh86** [comment]
For your reference, a core of the `git-branches` is the following git command.

```console
$ git for-each-ref --format "%(if:notequals=refs/stash)%(refname:rstrip=-2)%(then)%(if:notequals=refs/tags)%(refname:rstrip=-2)%(then)
%(if:notequals=HEAD)%(refname:lstrip=3)%(then)%(HEAD)%09%(refname:lstrip=2)%09%(authorname)%09%(if)%(upstream)%(then)%(upstream:
lstrip=2)%(end)%09%(committerdate:format-local:%Y/%m/%d %H:%M:%S)%(end)%(end)%(end)"
```

**Comment by Conni2461** [comment]
Implemented in https://github.com/nvim-telescope/telescope.nvim/commit/2e03f67de9eab023098bd05916bf26556520a467
