### ISSUE TITLE
Use "-u" option for git status picker to show all files

### ISSUE THREAD

**Issue by kristijanhusak** [nvim-telescope/telescope.nvim#579]
**Is your feature request related to a problem? Please describe.**
When I'm working on new features where I add new folders and files inside, git status picker prints only the folders. 

**Describe the solution you'd like**
I'd love to append `-u` to the git status command so it prints out all the files inside those new folders, or at least make `git_status` function accept the command through options like `find_files` does.

**Describe alternatives you've considered**
To create custom picker

**Screenshots**:

Before:
![before](https://i.imgur.com/uZMu5zo.png)
![after](https://i.imgur.com/1lYAHHs.png)

**Comment by Conni2461** [comment]
Seems like a good idea. We could make this an opt or just always do it.

**Comment by kristijanhusak** [comment]
Works great, thanks!
