### ISSUE TITLE
:Telescope should open builtin

### ISSUE THREAD

**Issue by singlexyz** [nvim-telescope/telescope.nvim#581]
Telescope subcommand is too much, if can use telescope to list all the subcomand, that's convenient.
Just like when I execute: 
`:Telescope`
it will list all the telescope subcommand with telescope itself, like: 

find_files
live_grep
buffers (cursor here)
help_tags
...

at this time, when I hit enter, it will execute `:Telescope buffers`

**Comment by elianiva** [comment]
it should be `:Telescope builtin`

https://github.com/nvim-telescope/telescope.nvim/wiki/Showcase#builtin

**Comment by tami5** [comment]
I think it's a great idea to make 'Telescope<cr>' run builtin by default @glepnir what do you think?

**Comment by singlexyz** [comment]
> it should be `:Telescope builtin`
> 
> https://github.com/nvim-telescope/telescope.nvim/wiki/Showcase#builtin

Wow, that,s it, I missing document.

**Comment by Conni2461** [comment]
I reopen this because i think its kinda handy to have that :)
