### ISSUE TITLE
Enable users to setup configuration for individual pickers

### ISSUE THREAD

**Issue by tami5** [nvim-telescope/telescope.nvim#582]
**Is your feature request related to a problem? Please describe.**

It is quite hard for new users to configure there telescopes. Configuration recipes in the wiki prove that setting up telescope to user liking is difficult and a bit complex, thus requiring a lot of investment/

**Describe the solution you'd like**

In setup method, the user shall be able to: 

- Setup configuration (mappings, layout, sorters ...) for individual pickers
- Reference functions by string rather than requiring the actions/preview module

```lua
require'telescope'.setup({
  defaults = {...};
  pickers = {
      git_status = { -- overrides git_status
        prompt_prefix = "git_status>",
        mappings = {}, 
        theme = dropdown,
      },
      dotfiles = { -- new custom picker
        func = "fd" -- that requires func to be defined
        prompt_prefix = "dotfiles>",
        cwd = 'path/to/dir',
        theme = full, -- gets merged to picker opts
        
      };
    }
  }

```
**Describe alternatives you've considered**

Currently the user need to define a custom, yet complex alternative to get individual pickers behaving or looking a certain way. For example, this is how my custom setup looks like https://gist.github.com/tami5/d49ac7f5fb6ce7d06788582446652760 

While this setup serve my needs, new commers will need to copy and paste similar setups or be limited by design.

**Additional context**
https://github.com/nvim-telescope/telescope.nvim/pull/578

**Comment by elianiva** [comment]
I agree with this, I have some simple wrapper functions on my config just to pass the different opts.

**Comment by tjdevries** [comment]
We could do this for the builtin ones I think -- it seems a good idea.

I'm not as confident about doing it for custom ones. We can chat about that more though.
