### ISSUE TITLE
Renaming files and folder on Telescope file_browser

### ISSUE THREAD

**Issue by ghost** [nvim-telescope/telescope.nvim#584]
It would be really nice to have a feature that pressing <C-r> on a folder or file, it redirect to the prompt where you can type the new name

**Comment by sharksforarms** [comment]
Similar train of thought, a "Move" feature could accomodate both renaming and moving of files/folders. I wouldn't mind both. Renaming could be an action on the basename where moving would be the full path.

**Comment by FabioRamatis** [comment]
Yeah I agree, on NERDTree you can press mm to "Move" or to "Rename" on the same binding

**Comment by timsofteng** [comment]
It would be great.

**Comment by elianiva** [comment]
Here's a quick and dirty implementation which doesn't cover all edge cases. Renaming `foo/` to `foo/bar` for example
I also added `Path:rename()` for plenary

https://user-images.githubusercontent.com/51877647/110080838-a24a4780-7dbd-11eb-8fd2-bda0a3806842.mp4

**Comment by Conni2461** [comment]
@elianiva Now you get it. Double PR incoming :rofl: 
You can make a PR for plenary, i can merge stuff over there. You can also add more things like `move`/`copy`, if you want. But tests are a requirement over at plenary. :)

**Comment by timsofteng** [comment]
I guess `nnn` is good example of how to implement copy or move feature.
At first user just select item or multiple items by space key. Than user need to go to specific directory where he want to move or copy file and just press `p` for copy or `v` for move. That's it.

**Comment by fdschmidt93** [comment]
Closing now as https://github.com/nvim-telescope/telescope-file-browser.nvim now exists to address these use cases.
