### ISSUE TITLE
nvim_command must not be called in a lua loop callback

### ISSUE THREAD

**Issue by numToStr** [nvim-telescope/telescope.nvim#589]
### Description
I am getting the following error when I start `telescope` for the first time.

```
Error executing luv callback:
...packer/start/nvim-web-devicons/lua/nvim-web-devicons.lua:869: E5560: nvim_command must not be called in a lua loop callback
```

I am not sure but I think 678494e503d3c717df8295f55a6f3c7d3309b7fa commit introduced this bug, as I revert back one commit everything works fine.

**Expected Behavior**
No Error

**Actual Behavior**

![image](https://user-images.githubusercontent.com/24727447/109602799-cfd98b80-7b46-11eb-984b-4522fbdea0e2.png)

### Details

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1109-g6b7cc45c4
- Operating system: Linux 5.10.15-1-MANJARO
- Telescope commit: 678494e503d3c717df8295f55a6f3c7d3309b7fa

</details>

**Comment by elianiva** [comment]
try to update your nvim-web-devicons

**Comment by numToStr** [comment]
I am already on the nvim-web-devicons HEAD. I don't know why this issue is still coming if it is fixed.

**Comment by elianiva** [comment]
wait, sorry, I didn't saw the latest Telescope commit. Is this easily reproducable? (I couldn't try it myself atm)

**Comment by numToStr** [comment]
Yes, it is.

**Comment by Conni2461** [comment]
I know whats the issue. He forgot to copy the has_loaded srufd in front of both return functions. Resulting in webdevicons getting loaded in callback.

Didn't catch that because i load dem manually

**Comment by Conni2461** [comment]
#590 fixes this. Will merge in 5. Gonna try it first with minrc
