### ISSUE TITLE
Find files from current file's project.

### ISSUE THREAD

**Issue by singlexyz** [nvim-telescope/telescope.nvim#592]
request `find_project_files` feature.
Same as `find_files` but from current file's project directory.
Just like nvim-lspconfig how to figure out project root:
`root_dir = root_pattern("package.json", "tsconfig.json", "jsconfig.json", ".git")`

**Comment by Conni2461** [comment]
Like are you asking from the location of the current buffer?

You can write a wrapper for that yourself:
```lua
require('telescope.builtin').find_files( { cwd = vim.fn.expand('%:p:h') })
```

**Comment by singlexyz** [comment]
> Like are you asking from the location of the current buffer?
> 
> You can write a wrapper for that yourself:
> 
> ```lua
> require('telescope.builtin').find_files( { cwd = vim.fn.expand('%:p:h') })
> ```

Not the current file's directory, it's the project root directory. 
For example, a nodejs project like this.
```
root/
  package.json
  dir1/
    file1
```
when I edit file1 or any other file in root/,  execute `find_project_files`, it's will `find_files` from root/.
I used fzf.vim to achieve this feature before:
```
function! s:find_git_root()
  return system('git rev-parse --show-toplevel 2> /dev/null')[:-2]
endfunction
command! ProjectFiles execute 'Files' s:find_git_root()
```

**Comment by Conni2461** [comment]
Oh you are basically asking for this: https://github.com/nvim-telescope/telescope.nvim/issues/502#issuecomment-774726122 or just do `Telescope git_files` when in git directory.

Copied snippet for reference
```lua
M.my_fd = function(opts)
  opts = opts or {}
  opts.cwd = vim.fn.systemlist("git rev-parse --show-toplevel")[1]
  require'telescope.builtin'.find_files(opts)
end
```

**Comment by singlexyz** [comment]
> ```lua
> -
> ```



> Oh you are basically asking for this: [#502 (comment)](https://github.com/nvim-telescope/telescope.nvim/issues/502#issuecomment-774726122) or just do `Telescope git_files` when in git directory.
> 
> Copied snippet for reference
> 
> ```lua
> M.my_fd = function(opts)
>   opts = opts or {}
>   opts.cwd = vim.fn.systemlist("git rev-parse --show-toplevel")[1]
>   require'telescope.builtin'.find_files(opts)
> end
> ```

em... what if not in a git directory... and need to specify other filename, like package.json

**Comment by Conni2461** [comment]
You can get a little bit more creative and ask the active lsp client.

(This is not tested code i have written in github)
```lua
M.my_fd = function(opts)
  opts = opts or {}
  opts.cwd = vim.fn.systemlist("git rev-parse --show-toplevel")[1]
  if vim.v.shell_error ~= 0 then
    -- if not git then active lsp client root
    -- will get the configured root directory of the first attached lsp. You will have problems if you are using multiple lsps 
    opts.cwd = vim.lsp.get_active_clients()[1].config.root_dir
  end
  require'telescope.builtin'.find_files(opts)
end
```

**Comment by singlexyz** [comment]
> You can get a little bit more creative and ask the active lsp client.
> 
> (This is not tested code i have written in github)
> 
> ```lua
> M.my_fd = function(opts)
>   opts = opts or {}
>   opts.cwd = vim.fn.systemlist("git rev-parse --show-toplevel")[1]
>   if vim.v.shell_error ~= 0 then
>     -- if not git then active lsp client root
>     -- will get the configured root directory of the first attached lsp. You will have problems if you are using multiple lsps 
>     opts.cwd = vim.lsp.get_active_clients()[1].config.root_dir
>   end
>   require'telescope.builtin'.find_files(opts)
> end
> ```

Thanks a lot. I found a plugin `airblade/vim-rooter`, It can find project root according to the file I set
```
let g:rooter_patterns = ['.git', '.svn', 'package.json', '!node_modules']
nnoremap <expr> sp ':Telescope find_files cwd='.FindRootDirectory().'/<cr>'
```

**Comment by Conni2461** [comment]
Closing for now. I think we support everything that is needed to do stuff like this in small wrappers
