### ISSUE TITLE
Mapping <Esc> to quit in insert mode doesn't work

### ISSUE THREAD

**Issue by oponkork** [nvim-telescope/telescope.nvim#595]
### Description

Mapping <esc> to `actions.close` in insert mode does not work. Instead of closing the finder, it leaves me in normal mode. Other mappings like `<C-p>` to `actions.close` do work, and correctly closes the finder.

### Details

The mapping is mentioned in the wiki here:
https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#mapping-esc-to-quit-in-insert-mode

### Relevant config
```lua
local actions = require('telescope.actions')
require('telescope').setup{
  defaults = {
    mappings = {
      i = {
        ["<esc>"] = actions.close, -- Does not work
        ["<C-p>"] = actions.close -- Works
      },
    },
  }
}
```

**Comment by elianiva** [comment]
what's the output of `:verbose inoremap <Esc>` ? I had this issue before and turned out it was caused by lexima overriding my mapping

**Comment by oponkork** [comment]
> what's the output of `:verbose inoremap <Esc>` inside Telescope window? I had this issue before and turned out it was caused by lexima overriding my mapping

Aah, Similar issue here. For me pear-tree is the culprit.

**Comment by Keating950** [comment]
> what's the output of `:verbose inoremap <Esc>` inside Telescope window? I had this issue before and turned out it was caused by lexima overriding my mapping

Did you find a workaround for this?

**Comment by elianiva** [comment]
> Did you find a workaround for this?

yes, I stopped using an autopair plugin 😆

**Comment by matheusfillipe** [comment]
Just in case someone ever falls here pear_tree does have an option to disable for specific buffer types. This works for me:
`let g:pear_tree_ft_disabled = ["TelescopePrompt"]`

**Comment by KarlWithK** [comment]
I am still having this issue with lexima. Any tips?

**Comment by issadarkthing** [comment]
For those who are using lexima, you can add this `autocmd! FileType TelescopePrompt let b:lexima_disabled = 1`
