### ISSUE TITLE
Start with the normal mode when run from mappings

### ISSUE THREAD

**Issue by delphinus** [nvim-telescope/telescope.nvim#600]
### Description

I run a new Telescope picker from mappings on the prompt, then it runs in the normal mode.

**Expected Behavior**

Start the picker with the insert mode.

**Actual Behavior**

It runs in the normal mode.

### Details

<details><summary>Reproduce</summary>

See [this Dockerfile][Dockerfile] for the full reproducible procedures.

[Dockerfile]: https://gist.github.com/delphinus/b5fbe569238707aa7483f993846faeec

1. `nvim` with `init.lua` below.

   ```lua
   local telescope = require"telescope"
   local builtin = require"telescope.builtin"
   telescope.setup{
     defaults = {
       mappings = {
         i = {
           ["<C-a>"] = function() builtin.find_files{} end
         },
       },
     },
   }
   ```

2. `:Telescope help_tags` or any pickers
3. Press `<C-a>` and it runs `find_files` but with the normal mode.
</details>

<details><summary>Environment</summary>

- nvim --version output: 

  ```
  NVIM v0.5.0-dev+1115-gc1fbc2ddf
  Build type: Debug
  LuaJIT 2.1.0-beta3
  Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/root/neovim/build/config -I/root/neovim/src -I/root/neovim/.deps/usr/include -I/usr/include -I/root/neovim/build/src/nvim/auto -I/root/neovim/build/include
  Compiled by root@142285a955e0
  
  Features: +acl +iconv +tui
  See ":help feature-compile"
  
     system vimrc file: "$VIM/sysinit.vim"
    fall-back for $VIM: "/root/local/nvim/share/nvim"
  
  Run :checkhealth for more info
  ```

- Operating system: Ubuntu 21.04
- Telescope commit: db76155

</details>

<details><summary>Configuration</summary>
<p>

```lua
local telescope = require"telescope"
local builtin = require"telescope.builtin"
telescope.setup{
  defaults = {
    mappings = {
      i = {
        ["<C-a>"] = function() builtin.find_files{} end
      },
    },
  },
}
```

or see [Dockerfile][].

</details>

**Comment by elianiva** [comment]
https://github.com/nvim-telescope/telescope.nvim/blob/11674ac021e39f92eb51d2884904b0300c5133a3/lua/telescope/actions/init.lua#L211-L213

It seems like `keepinsert` is always set to false and I don't see any way to change it apart from directly changing the argument of `do_close`

https://github.com/nvim-telescope/telescope.nvim/blob/11674ac021e39f92eb51d2884904b0300c5133a3/lua/telescope/actions/init.lua#L222

I also tried to run `startinsert` after opening a picker from the prompt but it seems that it gets ignored/run before the `stopinsert`.

**Comment by Conni2461** [comment]
You can solve this by running `actions._close(prompt_bufnr, true)` this function is public for quite some time. Closing
