### ISSUE TITLE
Feature request: lsp_diagnostics show project diagnostic

### ISSUE THREAD

**Issue by vpeopleonatank** [nvim-telescope/telescope.nvim#601]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add diagnostic to telescope like this https://github.com/neovim/nvim-lspconfig/issues/69

**Describe alternatives you've considered**

**Additional context**

**Comment by elianiva** [comment]
https://github.com/nvim-telescope/telescope.nvim/pull/543

**Comment by vpeopleonatank** [comment]
I 've just updated Telescope, `:Telescope lsp_diagnostics` only show diagnostic of current buffer. Not all file in project

**Comment by elianiva** [comment]
yeah, it requires #599

**Comment by vpeopleonatank** [comment]
#599 support diagnostic for currently opening buffer. Not diagnostic for all file in project. Anw that pr is very nice.

**Comment by fdschmidt93** [comment]
#599 supports workspace now via `lsp_workspace_diagnostics` - note what's being displayed depends on the LSP. For sumneko lua LSP, you'll get the workspace diagnostics, whereas e.g. pyright only shows for the currently opened buffers. README will reflect that.

**Comment by Conni2461** [comment]
Implemented in 908752f
