### ISSUE TITLE
Error on LSP workspace diagnostics when unsetting LSP sign

### ISSUE THREAD

**Issue by etrnal70** [nvim-telescope/telescope.nvim#603]
### Description

Using lsp_workspace_diagnostics give error when unsetting LSP sign
**Expected Behavior**

It works fine
**Actual Behavior**

Error like : 
![image](https://user-images.githubusercontent.com/5826834/109988561-3bd01580-7d3a-11eb-87d2-1101be62a75d.png)

### Details

<details><summary>Reproduce</summary>

1. Start nvim and LSP on a project
2. :lua vim.fn.sign_define("LspDiagnosticsSignError", {text = "", numhl = "LspDiagnosticsDefaultError"})
3. :Telescope lsp_workspace_diagnostics
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1117-g6995fad26
- Operating system: Linux
- Telescope commit: 908752fc67f0aff43e35ffb175b5e6226874bad5

</details>

<details><summary>Configuration</summary>
<p>

```lua
local vim = vim
vim.cmd [[packadd packer.nvim]]

require('packer').startup(function()

  use {'neovim/nvim-lspconfig'}
  use {
    'nvim-telescope/telescope.nvim',
    requires = {'nvim-lua/popup.nvim','nvim-lua/plenary.nvim'}
  }
end)

require('telescope').setup{}
require('lspconfig').rust_analyzer.setup {}

```

**Comment by Conni2461** [comment]
CC @fdschmidt93 

we should `pcall` it and if not ok then default to something

**Comment by Conni2461** [comment]
Oh it just returns nil :laughing: I thought `vim.fn.sign_getdefined` starts burning or something.
Sounds like a good plan

**Comment by fdschmidt93** [comment]
Yes, I'm aware. Apologies, if it came across wrongly but merely wanted to suggest to catch that case explicitly as opposed to a more general `pcall` :)
