### ISSUE TITLE
Disable escaping of chars in live grep

### ISSUE THREAD

**Issue by Kazy** [nvim-telescope/telescope.nvim#604]
Hello !

When using live grep, some characters (see https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/files.lua#L19) are escaped from the prompt (see https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/builtin/files.lua#L50), in particular `*`. This makes using regex patterns impossible for searching impossible.

Could it be possible to disable it/would you be open to such an option, or is there a strong reason to escape them ?

Thanks !

**Comment by Conni2461** [comment]
If i recall correctly it completely broke `live_grep` but we could re-enable for `grep_string`.

CC @elianiva

**Comment by elianiva** [comment]
yeah, it broke `live_grep` if it's not a complete regex. e.g if you type `(` instead of `()`.
I think we could remove it for `grep_string`, it's doing fine without `escape_chars`

**Comment by zygous** [comment]
I too would like a nice way to search using a regex instead of just a string. I've no strong opinions on how that should work, but "grep" is a misnomer without it. `live_grep` is nice but not powerful enough.

**Comment by Conni2461** [comment]
See https://github.com/nvim-telescope/telescope.nvim/pull/670

**Comment by languitar** [comment]
Before telescope I was using clap. There, grepping simply stopped and showed an error message until the syntax of the regex was fixed. That was actually pretty usable that way.

**Comment by Conni2461** [comment]
We no longer escape them for quite some time. Closing
