### ISSUE TITLE
Implement "delta" as preview window for diffs

### ISSUE THREAD

**Issue by ecosse3** [nvim-telescope/telescope.nvim#605]
Hi everyone,

I'm trying to move completely from fzf and fzf-preview to telescope and I'm missing ability to shows diffs with [delta](https://github.com/dandavison/delta). I know it's possible to add custom previewers in telescope but I'm not good in Lua yet. Implementation for this viewer should be actually easy because it works natively with git.

That's how I implemented it with fzf-preview:

    let g:fzf_preview_git_status_preview_command =
      \ "[[ $(git diff --cached -- {-1}) != \"\" ]] && git diff --cached --color=always -- {-1} | delta || " .
      \ "[[ $(git diff -- {-1}) != \"\" ]] && git diff --color=always -- {-1} | delta || " .

It looks like this for example in git-status: (see right side)
![image](https://user-images.githubusercontent.com/17691791/109995531-aa977980-7d0e-11eb-9e5e-f5cced6aec91.png)

It would be nice to have this preview with git-status, git commits and git-bcommits or whenever is useful.

Thank you so much!

**Comment by Conni2461** [comment]
I am not sure if i am going to implement it in core but i can send a implementation and you can use it locally. Not in core because we had issues with term_previewer and switched over to buffer previewer where we collect `git diff` output in a buffer and then do `filetype diff` and highlighting with delta isn't possible until i have finished termcolors -> hlgroups.

Okay implementation:
```lua
local previewers = require('telescope.previewers')
local builtin = require('telescope.builtin')
local conf = require('telescope.config')

local delta = previewers.new_termopen_previewer {
  get_command = function(entry)
    -- note we can't use pipes
    -- this command is for git_commits and git_bcommits
    return { 'git', '-c', 'core.pager=delta', '-c', 'delta.side-by-side=false', 'diff', entry.value .. '^!' }

    -- this is for status
    -- You can get the AM things in entry.status. So we are displaying file if entry.status == '??' or 'A '
    -- just do an if and return a different command
    -- return { 'git', '-c', 'core.pager=delta', '-c', 'delta.side-by-side=false', 'diff', entry.value }
  end
}


local my_git_commits = function(opts)
  opts = opts or {}
  opts.previewer = delta

  builtin.git_commits(opts)
end

my_git_commits()
```

**Comment by elianiva** [comment]
We could probably add it to the [Configuration Recipes](https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes) section in the Wiki.

**Comment by Conni2461** [comment]
Oh yeah we can add a more polished version :) And i thought we might also want to do some collapsible sections. Its a wall of code :laughing: so it could feel discouragingly

**Comment by ecosse3** [comment]
It works, thank you so much! I have never written in lua before but I was able to achieve this in that way:

_ecosse/telescope.lua [file]_

    -- Implement delta as previewer for diffs
    
    local previewers = require('telescope.previewers')
    local builtin = require('telescope.builtin')
    local conf = require('telescope.config')
    local E = {}
    
    local delta = previewers.new_termopen_previewer {
      get_command = function(entry)
        -- this is for status
        -- You can get the AM things in entry.status. So we are displaying file if entry.status == '??' or 'A '
        -- just do an if and return a different command
        if entry.status == '??' or 'A ' then
          return { 'git', '-c', 'core.pager=delta', '-c', 'delta.side-by-side=false', 'diff', entry.value }
        end
    
        -- note we can't use pipes
        -- this command is for git_commits and git_bcommits
        return { 'git', '-c', 'core.pager=delta', '-c', 'delta.side-by-side=false', 'diff', entry.value .. '^!' }
    
      end
    }
    
    E.my_git_commits = function(opts)
      opts = opts or {}
      opts.previewer = delta
    
      builtin.git_commits(opts)
    end
    
    E.my_git_bcommits = function(opts)
      opts = opts or {}
      opts.previewer = delta
    
      builtin.git_bcommits(opts)
    end
    
    E.my_git_status = function(opts)
      opts = opts or {}
      opts.previewer = delta

      builtin.git_status(opts)
    end
    
    return E

Then I made mapping:
`nnoremap <silent> <Leader>gla <cmd>lua require('ecosse.telescope').my_git_commits()<CR>`
`nnoremap <silent> <Leader>glc <cmd>lua require('ecosse.telescope').my_git_bcommits()<CR>`
`nnoremap <silent> <Leader>gs <cmd>lua require('ecosse.telescope').my_git_status()<CR>`

Thank you so much. For me delta is the best diff viewer and now I have it with telescope.nvim <3

**Comment by jupblb** [comment]
I am afraid this does not work anymore. :/ Looks like a good approach though.

**Comment by ggsalas** [comment]
The example from @ecosse3 is working perfect. 
The only thing I can't achieve is allow scroll the preview with`<C-d>` and `<C-u>`, that only fails with delta.

**Comment by tbo** [comment]
Is there any way to omit the `[Process exited 0]` at the very end of the diff output?

**Comment by ecosse3** [comment]
@ggsalas Yes, I have this problem too. But I kinda "fixed" that by clicking `<C-d>` and scrolling together. Then it works.

@tbo Unfortunately I want able to fix that. It only happens to me when a file is shorter than the preview window. If it's longer, then I don't see it and I see END indicator as on the screenshot below:

![image](https://user-images.githubusercontent.com/17691791/126007044-79b0a27d-2920-4828-abe6-beef82c5ad71.png)

**Comment by tuxflo** [comment]
I also want to say thank you for providing your config, works for me too. Only `C-d`/`C-u` isn't working. But on a site note: one can scroll in the preview window by using the mouse.
Kind of funny that the mouse is working in neovim better than the keyboard shortcuts (for this scenario)

**Comment by tombh** [comment]
I got this working too! Thanks everyone. The only thing (apart from the problematic scrolling) is that the previews for `bcommits` are for the *whole* commit, not just the diff of the file. Anyone else have that problem?

**Comment by ecosse3** [comment]
> ...the previews for `bcommits` are for the _whole_ commit, not just the diff of the file. Anyone else have that problem?

I'm using for long time already and doesn't have any issues. bcommits shows me only buffer commits with delta.

My current function:
```lua
M.my_git_bcommits = function(opts)
  opts = opts or {}
  opts.previewer = {
    delta,
    previewers.git_commit_message.new(opts),
    previewers.git_commit_diff_as_was.new(opts),
  }

  builtin.git_bcommits(opts)
end
```

**Comment by ecosse3** [comment]
@tombh I had the same issue and just started investigating into that. I made it work by this (I use 3 previewers):

```lua
local delta = previewers.new_termopen_previewer {
  get_command = function(entry)
    return { 'git', '-c', 'core.pager=delta', '-c', 'delta.side-by-side=false', 'diff', entry.value .. '^!', '--', entry.current_file }
  end
}

M.my_git_bcommits = function(opts)
  opts = opts or {}
  opts.previewer = {
    delta,
    previewers.git_commit_message.new(opts),
    previewers.git_commit_diff_as_was.new(opts),
  }

  builtin.git_bcommits(opts)
end
```

**Comment by tombh** [comment]
`'--', entry.current_file` — that was it! Thank you so much 🥳

**Comment by zdmgmail** [comment]
@ecosse3 

thanks your config, and I confused why use 

```
 opts.previewer = {
    delta,
    previewers.git_commit_message.new(opts),
    previewers.git_commit_diff_as_was.new(opts),
  }
```

instead `opts.previewer = delta` ?

**Comment by timoleistner** [comment]
Somehow it isnt working for me with the following config
```
local actions = require('telescope.actions')
local previewers = require('telescope.previewers')
local builtin    = require('telescope.builtin')
local M = {}
local delta = previewers.new_termopen_previewer {
    get_command = function(entry)
        -- this is for status
        -- You can get the AM things in entry.status. So we are displaying file if entry.status == '??' or 'A '
        -- just do an if and return a different command
        if entry.status == '??' or 'A ' then
            return {'git', '-c', 'core.pager=delta', '-c', 'delta.side-by-side=false', 'diff', entry.value}
        end

        -- note we can't use pipes
        -- this command is for git_commits and git_bcommits
        return {'git', '-c', 'core.pager=delta', '-c', 'delta.side-by-side=false', 'diff', entry.value .. '^!'}

    end
}
M.delta_git_status = function(opts)
    opts = opts or {}
    opts.previewer = delta

    builtin.git_status(opts)
end
return M
```
```
map("n", "<leader>gls", "<CMD>lua require('plugins.telescope').delta_git_status()<CR>",
    { noremap = true, silent = true })
```
Using this mapping, telescope opens and I get the following in the preview window:
```
fatal: ambiguous argument 'config/nvim/lua/keymappings.lua':
unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]' 
[Process exited 128]
```
Looking at git_commits and git_bcommits works with delta using the configs you provided.
Help greatly appreciated to get git_status to work too :)

**Comment by ecosse3** [comment]
@timoleistner Use `entry.path` instead to pass the full path of file for status. `entry.value` passes relative path and your `:pwd` can be different so that's why it doesn't work.

**Comment by bluz71** [comment]
Ever since commit [7695d224](https://github.com/nvim-telescope/telescope.nvim/commit/7695d224c81e4ceeb3100d759c296814183ccfae), a fix for #1480, my custom Telescope git status with delta command (as documented in this issue) is leaving me in insert mode by default after selection (aka hitting Enter), which is very similar to issue #1595.

I think the Telescope command prompt being in insert mode get inherited back to the edit buffer (or some such).

Anyone have a fix for this super-duper annoying issue?

**Comment by Conni2461** [comment]
#1480 basically only reverted the changes introduced here https://github.com/nvim-telescope/telescope.nvim/commit/b952c2f852de1ec5ce7306ccd9262c97e27902d2

Next time i work on telescope is Wednesday and then i would look into fixing our `closing` step because this would also fix our folding issues: https://github.com/nvim-telescope/telescope.nvim/issues?q=is%3Aissue+is%3Aopen+folding because they are caused by opening a file before we leave insert mode.

**Comment by bluz71** [comment]
@Conni2461, I have spawned this insert mode issue into a new issue #1804. Better to discuss insert mode issue over there than here.

**Comment by bluz71** [comment]
@Conni2461, any chance you can have a look at the issue?

**Comment by asmodeus812** [comment]
I am unable to actually use the configurations provided above with delta. I have tested the commands in the terminal and delta works fine, once i put it in a telescope previewer config the preview windows is simply empty nothing is shown, tried with status, commits and bcommits, same effect. What am i missing here, these configurations seem to not be working with current telescope master.

**Comment by bluz71** [comment]
Checkout my Telescope and Telescope + Delta configuration:

- [telescope.lua](https://github.com/bluz71/dotfiles/blob/master/vim/lua/plugin/telescope.lua)
- [telescope-commands.lua](https://github.com/bluz71/dotfiles/blob/master/vim/lua/util/telescope-commands.lua)

First file has the mappings (see `git_bcommits` and `git_status`), second file has the actual Delta setup functions that gets mapped in the first file.

Telescope + Delta works great for me since @Conni2461 fixed the insert bug.

**Comment by winkee01** [comment]
Hello, how can I scroll in the preview window?

**Comment by benfrain** [comment]
Arrived here looking for a way to get delta used in the bcommits too. There [was talk](https://github.com/nvim-telescope/telescope.nvim/issues/605#issuecomment-790770703) of getting something added to the configuration recipes but I can't find anything there.

Could someone confirm the current 'canonical' way of seeing git-delta diffs in bcommits?

**Comment by manymee** [comment]
@benfrain I don't know about canonical, but this is what I ended up using for **bcommits** (today, so it's not battle-tested yet 😅):

```lua
vim.g.git_bcommits_delta = function()
  local opts = {}

  opts.previewer = previewers.new_termopen_previewer({
    get_command = function(entry)
      return {
        -- Show diff between selected commit and previous commit (only showing changes in current file).
        -- If there is no previous commit, throw away stderr
        -- and show the selected commit (only showing changes in current file).

        "zsh", "-c", table.concat({
          "git diff",
          table.concat({ entry.value, '~:', vim.fn.expand('#') }),
          table.concat({ entry.value, ':', vim.fn.expand('#') }),
          "2> /dev/null || git show",
          table.concat({ entry.value, ':', vim.fn.expand('#') })
        }, ' ')

        -- normal notation, same effect as above...
        -- "zsh", "-c", "git diff " .. entry.value .. '~:' .. vim.fn.expand('#') .. ' ' .. entry.value .. ':' .. vim.fn.expand('#') ..
        -- " 2> /dev/null || git show " .. entry.value .. ':' .. vim.fn.expand('#')

        -- if you don't have delta set up in .gitconfig:
        -- "zsh", "-c", "git -c core.pager=delta -c delta.paging=always diff " .. entry.value .. '~:' .. vim.fn.expand('#') ..
        -- ' ' .. entry.value .. ':' .. vim.fn.expand('#') ..
        -- " 2> /dev/null || git -c core.pager=delta -c delta.paging=always show " .. entry.value .. ':' .. vim.fn.expand('#')
      }
    end,
  })

  builtin.git_bcommits(opts)
end
```
This picker lists the commits of the file where you summoned the picker, showing a delta diff of **only this file**.
One tiny issue with this is that when you get to the commit where this file was created, the preview doesn't really diff the file (with green highlights) but "only" shows syntax-highlighted contents of the file. I couldn't make `git diff` work here.

NOTE: If you don't have `delta` set up in your git config, then you have to explicitly use it in the git commands, using something like:
```
git -c core.pager=delta -c delta.paging=always diff ...
```

@winkee01 The default key bindings are `<c-d>` and `<c-u>`. If your issue is that it throws an error saying `Can't send data to closed stream`, then it might be because you have `paging` set to `never` in your command/config. Make sure to set it to `always`, same as I do in my commands above. That might fix it :)

@benfrain ps: thanks for your awesome YT channel :) besides the Vim stuff, you inspired me to get a Dygma Raise a few months ago thanks to your review and I've been extremely happy with it.

**Comment by Zeioth** [comment]
I'm able to use Delta, but it shows [Process exited 0]. There is some way to avoid this?

![screenshot_2023-06-05_02-58-54_288060983](https://github.com/nvim-telescope/telescope.nvim/assets/3357792/ecabab86-36ab-4df0-abd2-04d7ba21198f)

**Comment by diegodox** [comment]
If you always get process exited 0 on last line. Pipe output to `head -n -1` may work. (not yet tested, sorry)

**Comment by agoodshort** [comment]
`head -n -1` did not work for me, but I found a way using `new_buffer_previewer` instead (took inspiration from [here](https://github.com/debugloop/telescope-undo.nvim/blob/1d971cb63cf485e176dbb131531d0c646df9e206/lua/telescope-undo/previewer.lua#L45-L54))

```lua
previewer = previewers.new_buffer_previewer({
    define_preview = function(self, entry, status)
        local dir_name = vim.fn.substitute(vim.fn.getcwd(), "^.*/", "", "")
        local t = {}
        if entry == dir_name then
            local s = vim.fn.system("git status -s")
            for chunk in string.gmatch(s, "[^\n]+") do
                t[#t + 1] = chunk
            end
        else
            local s = vim.fn.system("git -C " .. entry .. " status -s")
            for chunk in string.gmatch(s, "[^\n]+") do
                t[#t + 1] = chunk
            end
        end
        vim.api.nvim_buf_set_lines(self.state.bufnr, 0, -1, true, t)
    end,
}),

```

**Comment by ribru17** [comment]
To anyone still struggling to get `<C-d>` and `<C-u>` to work, I fixed it by adding the following to my setup:
```lua
telescope.setup {
  defaults = {
    set_env = {
      LESS = '',
      DELTA_PAGER = 'less',
    },
  },
},
```
