### ISSUE TITLE
Show date, author and commit message in git-commits & git-bcommits

### ISSUE THREAD

**Issue by ecosse3** [nvim-telescope/telescope.nvim#609]
Hi,

I want to put more of my ideas to make this plugin even better, so I think the feature of showing date, author, and commit message of currently selected commit in git-commits and git-bcommits could be very useful.

That information could be added to selected line like in fzf-preview plugin as example:
![image](https://user-images.githubusercontent.com/17691791/110014136-bdb44480-7d22-11eb-93c1-f14465c6fa8c.png)

Or even at top of the preview window.

What do you think about it?

**Comment by Conni2461** [comment]
Yes i would add stuff like that. Or more like i have something almost almost done https://github.com/nvim-telescope/telescope.nvim/pull/528 where you can cycle between different previewers.
So we have multiple views on the diff.
- git_commit_diff_to_parent
- git_commit_diff_to_head
- git_commit_diff_as_was
- git_message

So you can basically say. go to prev and you have message content. You can also like change order and integrate that with delta. So because you set `previewer = delta` you can do (after that PR is merged)
```lua
previewer = {
  delta,
  previewers.git_commit_message.new(opts),
}
```

And you can cycle between full message and diff.

**Comment by ecosse3** [comment]
Thank you so much @Conni2461 for finally merging PR #528. Below all of you can see my config for git commits & git bcommits with delta & cycle previewers:

```lua
local previewers = require('telescope.previewers')
local builtin = require('telescope.builtin')
local M = {}

local delta = previewers.new_termopen_previewer {
  get_command = function(entry)
    return { 'git', '-c', 'core.pager=delta', '-c', 'delta.side-by-side=false', 'diff', entry.value .. '^!' }
  end
}

M.my_git_commits = function(opts)
  opts = opts or {}
  opts.previewer = {
    delta,
    previewers.git_commit_message.new(opts),
    previewers.git_commit_diff_as_was.new(opts),
  }

  builtin.git_commits(opts)
end

M.my_git_bcommits = function(opts)
  opts = opts or {}
  opts.previewer = {
    delta,
    previewers.git_commit_message.new(opts),
    previewers.git_commit_diff_as_was.new(opts),
  }

  builtin.git_bcommits(opts)
end

return M
```

**Comment by johans** [comment]
@Fedora7 Did you find a solution to this?

**Comment by Fedora7** [comment]
> @Fedora7 Did you find a solution to this?

Nope

**Comment by ecosse3** [comment]
@johans @Fedora7 For buffer commits with telescope & delta this work to me perfectly all the time:

```lua
local delta_bcommits = previewers.new_termopen_previewer {
  get_command = function(entry)
    return { 'git', '-c', 'core.pager=delta', '-c', 'delta.side-by-side=false', 'diff', entry.value .. '^!', '--', entry.current_file }
  end
}

M.my_git_bcommits = function(opts)
  opts = opts or {}
  opts.previewer = {
    delta_bcommits,
    previewers.git_commit_message.new(opts),
    previewers.git_commit_diff_as_was.new(opts),
  }

  builtin.git_bcommits(opts)
end
```

<C-d> and <C-u> works great and I can see whole diff. For git commits (all) I use solution already in this topic.

**Comment by dudicoco** [comment]
For anyone who's running into an issue with scrolling the preview, this can be fixed by adding `export LESS=-R` to your shell profile / rc file.
See https://github.com/aaronhallaert/advanced-git-search.nvim/issues/54#issuecomment-1725309733 for more context.
