### ISSUE TITLE
Mixture of find_file and file_browser

### ISSUE THREAD

**Issue by TornaxO7** [nvim-telescope/telescope.nvim#615]
**Is your feature request related to a problem? Please describe.**
If I'm in a nested project structure like in this one:
```
├── BrightnessWidget.dart
├── Classes
│   ├── alarm_clock.dart <-- I'm in this file
│   ├── alarm_clock_handler.dart
│   └── alarm_database.dart
├── main.dart
...
```
and if I'd like to edit `main.dart`, than I'd have to leave vim before and navigate manually with it.

**Describe the solution you'd like**
Is it possible to let Telescope detect the project and add a command, where it looks in a whole project directory (for example by going through all parent directories until it found a `.git` directory)?

**Describe alternatives you've considered**
Well, just leaving vim and navigating to the file manually. I'm aware of the `:Telescope file_browser` command, but it's the almost same as navigating manually to it (in my opinion).

**Additional context**
Eeh... I don't know what to add here.

**Comment by elianiva** [comment]
you could `cd` into the root of the project, open neovim there, and then go to `alarm_clock.dart` using Telescope. Next time you open Telescope, it's going to use the root of the project. This is what I always do when I'm working on something.

If you want to detect the root automatically regardless of where you open the file, there's `vim-rooter` plugin for that.

**Comment by TornaxO7** [comment]
Thank you! It works with `vim-rooter` :)
