### ISSUE TITLE
Fix: Unable to close telescope when you have no listed buffers

### ISSUE THREAD

**Issue by polarmutex** [nvim-telescope/telescope.nvim#62]
If you open telescope with no listed buffers (such as vim-startify or other start screens) and try to close the telescope floating window bu hitting Esc or selecting a finder option, the window will not close

This is an issue within neovim when calling bwipeout on a buffer with no listed buffers. It will not delete the unlisted buffer even though it is safe to do so.

I have created an issue in Neovim and PR to fix this. 
Issue: neovim/neovim#12895
PR: neovim/neovim#12897

This issue is to track this issue

**Comment by tjdevries** [comment]
Wow! Awesome :) that's very helpful.

**Comment by Conni2461** [comment]
I just merged a commit that should help with `nobuflisted`.

Big thanks to @l-kershaw

Closing. Feel free to reopen when this issue still persists.
