### ISSUE TITLE
Feature: CD_TO_DIRECTORY picker

### ISSUE THREAD

**Issue by timsofteng** [nvim-telescope/telescope.nvim#620]
Hello. The idea of picker is absolutely same idea of of `FZF_ALT_C_COMMAND` in fzf. 
Just invoke it and go to specific directory of working directory and with pickers chain (https://github.com/nvim-telescope/telescope.nvim/issues/618) invoke any other picker. So useful.

Combine it with file system `bookmarks` which I describe in another issue (https://github.com/nvim-telescope/telescope.nvim/issues/619) and you can do amazing thing with immediately jumping to any location of your file system.

**Comment by Conni2461** [comment]
I don't know this: `FZF_ALT_C_COMMAND`.

But there is https://github.com/nvim-telescope/telescope-project.nvim which allows you to create bookmarks / projects and do `tcd`.

**Comment by Conni2461** [comment]
Also telescope-filebrowser offers the same thing. Closing
