### ISSUE TITLE
Question: closing buffers on the buffers picker

### ISSUE THREAD

**Issue by dimas-cyriaco** [nvim-telescope/telescope.nvim#621]
Sorry if this is not the correct place for asking question, but, is there a mapping for closing the selected buffer on the builtin buffers picker? If not, how could I create one?

Thank you for the awesome plugin!

**Comment by Conni2461** [comment]
No there is no such mapping yet but you can inject your own mapping. Something like this should be possible:

```lua
local action_state = require('telescope.actions.state')
local actions = require('telescope

local m = {}
m.my_buffer = function()
  require('telescope.builtin').buffers{
    attach_mappings = function(prompt_bufnr, map)
      local delete_buf = function()
        local selection = action_state.get_current_selection()
        -- depending if you want to close or not, include this or not
        actions.close(prompt_bufnr)
        -- print(vim.inspect(selection))
        -- better print selection before first running this. I am not sure if it have a bufnr or if this field is named differently
        vim.api.nvim_buf_delete(selection.bufnr, { force = true })
      end

      -- mode, key, func
      -- this is just an example
      map('n', 'd', delete_buf)
    end
  }
end
return m
```

If more people find this a useful action we can include in core, but i am not sure about default mapping for it. Because its so easy to just map something yourself

Note: No idea if this works or not. Its written inside github :rofl:

**Comment by oberblastmeister** [comment]
I actually think that this is pretty useful

**Comment by Conni2461** [comment]
We would need a refresh for picker that allows us to take out only one element. Then we can get rid of `close`

**Comment by dimascyriaco** [comment]
Sorry, but it's not clear to me where do I put this code, and how do I tell Telescope to use this `my_buffer` function.

I tried to put this simplified version directly on `init.lua` but it does not look to be the correct way, since it behaves strangely:

```lua
  require'telescope.builtin'.buffers{ attach_mappings = function(_, map)
    map('i', '<c-u>', function()
      print('inside test function!')
    end)

    return true
  end}
```

It seams that this code just tells telescope to open this picker (as it automatically opens when I resource the file, and the mapping works) but if I open the picker with `:Telescope buffers`, the mapping does not work.

What am I missing?

**Comment by Conni2461** [comment]
Its not a configuration its a wrapper around our function. So the way you do this, is you put this function into a lua module (own file) put this file into `lua/dimascyriaco/telescope.lua` and then you can map `require('dimascyriaco/telescope').my_buffers()`

**Comment by dimascyriaco** [comment]
@Conni2461 thank you! It's working now. Your first code worked almost perfectly, just had to substitute `get_current_selection` for `get_selected_entry` and add `return true` to the attach function.

Here's the working code (file on `lua/config/telecope`:

```lua
local action_state = require('telescope.actions.state')
local actions = require('telescope.actions')

local m = {}

m.my_buffer = function()
  require'telescope.builtin'.buffers{
    attach_mappings = function(prompt_bufnr, map)
      local delete_buf = function()
        local selection = action_state.get_selected_entry()
        actions.close(prompt_bufnr)
        vim.api.nvim_buf_delete(selection.bufnr, { force = true })
      end

      map('i', '<c-u>', delete_buf)

      return true
    end
  }
end

return m

```

And the invocation:

```lua
vim.api.nvim_set_keymap('n', '<leader>b', ":lua require('config/telescope').my_buffer()<cr>", {noremap = true})
```

It would be a good improvement to have a refresh, but just closing the picker works fine.

**Comment by tami5** [comment]
> ```lua
>  attach_mappings = function(prompt_bufnr, map)
>       local delete_buf = function()
>         local selection = action_state.get_selected_entry()
>         actions.close(prompt_bufnr)
>         vim.api.nvim_buf_delete(selection.bufnr, { force = true })
>       end
> 
>       map('i', '<c-u>', delete_buf)
> 
>       return true
>     end
> ```

Oh that's so useful, thank you

**Comment by markhagemann** [comment]
Really useful, thanks for that @Conni2461 @dimas-cyriaco. It looks like it breaks the integration with using themes? 

e.g. `require('config/telescope').my_buffer(require('telescope.themes').get_dropdown({ results_height = 15; previewer = false }))<CR>` 

unlike the default which supports it `require('telescope.builtin').buffers(require('telescope.themes').get_dropdown({ results_height = 15; previewer = false }))<CR>]], opt)`

**Comment by Conni2461** [comment]
Oh yeah thats because it doesn't accept a opts table. You can refactor that it accepts a table or just add it to the function itself:
```lua
m.my_buffer = function(opts)
  opts = opts or {}
  opts.attach_mappings = function(prompt_bufnr, map)
    local delete_buf = function()
      local selection = action_state.get_selected_entry()
      actions.close(prompt_bufnr)
      vim.api.nvim_buf_delete(selection.bufnr, { force = true })
    end
    map('i', '<c-u>', delete_buf)
    return true
  end
  opts.previewer = false
  -- define more opts here
  -- opts.show_all_buffers = true
  -- opts.sort_lastused = true
  -- opts.shorten_path = false
  require('telescope.builtin').buffers(require('telescope.themes').get_dropdown(opts))
end
```

**Comment by markhagemann** [comment]
That works perfectly. Thanks a lot @Conni2461

**Comment by dhruvmanila** [comment]
For anyone interested in deleting multiple buffers, you can use the multi-selection key bindings to select multiple entries and delete those buffers in one go. It would be even better to have a key binding to remove the buffer and stay in telescope.
```lua
function M.buffers(opts)
  opts = opts or {}
  opts.previewer = false
  -- opts.sort_lastused = true
  -- opts.show_all_buffers = true
  -- opts.shorten_path = false
  opts.attach_mappings = function(prompt_bufnr, map)
    local delete_buf = function()
      local current_picker = action_state.get_current_picker(prompt_bufnr)
      local multi_selections = current_picker:get_multi_selection()

      if next(multi_selections) == nil then
        local selection = action_state.get_selected_entry()
        actions.close(prompt_bufnr)
        vim.api.nvim_buf_delete(selection.bufnr, {force = true})
      else
        actions.close(prompt_bufnr)
        for _, selection in ipairs(multi_selections) do
          vim.api.nvim_buf_delete(selection.bufnr, {force = true})
        end
      end

    map('i', '<C-x>', delete_buf)
    return true
  end
  require('telescope.builtin').buffers(require('telescope.themes').get_dropdown(opts))
end
```

**Comment by nrmnqdds** [comment]
Not sure if im late into the discussion but just wanna share my simplified mapping;
- opens buffer picker(Ctrl+e)
- delete buffer under the cursor(Ctrl+d) WITHOUT automatically closing telescope
- open buffer picker in normal mode so that i can directly use "j" and "k" to navigate the list

```lua
local builtin = require('telescope.builtin')
local action_state = require('telescope.actions.state')

vim.keymap.set('n', '<C-e>', function()
  builtin.buffers({
    initial_mode = "normal",
    attach_mappings = function(prompt_bufnr, map)
      local delete_buf = function()
        local current_picker = action_state.get_current_picker(prompt_bufnr)
        current_picker:delete_selection(function(selection)
          vim.api.nvim_buf_delete(selection.bufnr, { force = true })
        end)
      end

      map('n', '<c-d>', delete_buf)

      return true
    end
  }, {
    sort_lastused = true,
    sort_mru = true,
    theme = "dropdown"
  })
end)
```

**Comment by OleJoik** [comment]
> Not sure if im late into the discussion but just wanna share my simplified mapping;
> 
> * opens buffer picker(Ctrl+e)
> * delete buffer under the cursor(Ctrl+d) WITHOUT automatically closing telescope
> * open buffer picker in normal mode so that i can directly use "j" and "k" to navigate the list
> 
> ```lua
> local builtin = require('telescope.builtin')
> local action_state = require('telescope.actions.state')
> 
> vim.keymap.set('n', '<C-e>', function()
>   builtin.buffers({
>     initial_mode = "normal",
>     attach_mappings = function(prompt_bufnr, map)
>       local delete_buf = function()
>         local current_picker = action_state.get_current_picker(prompt_bufnr)
>         current_picker:delete_selection(function(selection)
>           vim.api.nvim_buf_delete(selection.bufnr, { force = true })
>         end)
>       end
> 
>       map('n', '<c-d>', delete_buf)
> 
>       return true
>     end
>   }, {
>     sort_lastused = true,
>     sort_mru = true,
>     theme = "dropdown"
>   })
> end)
> ```

I seem to be unable to close the currently active buffer with this, otherwise great. That might be because of some other problem in my configuration though. Are you able to delete the currently active one?

**Comment by nrmnqdds** [comment]
@OleJoik 
yeah my config cant delete currently active buffer, but can delete other buffers on the list

**Comment by jamestrew** [comment]
Closing currently active buffer will be addressed here https://github.com/nvim-telescope/telescope.nvim/pull/3145

**Comment by CoinCheung** [comment]
So there is no internal options for this, and we still need to write a function of our own, right?

**Comment by NikolaB131** [comment]
> So there is no internal options for this, and we still need to write a function of our own, right?

@CoinCheung there is: https://github.com/nvim-telescope/telescope.nvim/pull/828#issuecomment-857912430
