### ISSUE TITLE
Feature request: preprocess command results using Lua function?

### ISSUE THREAD

**Issue by luc-tielen** [nvim-telescope/telescope.nvim#624]
**Is your feature request related to a problem? Please describe.**
Hi, I'm trying to build hoogle integration for telescope (a very much WIP can be found here: https://github.com/luc-tielen/telescope_hoogle), similar how to live-grep works.
Normal hoogle output is line by line which works out of the box with telescope, but if I add `--json` flag I get a one-line JSON back of the form:

```js
[{key1: value1, ...}, {key1: value2, ...}, ...]
``` 

Right now I'm using `telescope.finders.new_job` for this which requires returning a command with some args.. but there is no way to run a Lua function first on the results (such as vim.fn.json_decode)?

**Describe the solution you'd like**
Can functionality be added to run a Lua function on the output that is returned (such as `vim.fn.json_decode`) before converting them to entries? Or am I overlooking a certain feature here?

**Describe alternatives you've considered**
For now I will think of a workaround with a shell script, but it feels much more brittle.

**Comment by Conni2461** [comment]
There was already a hoogle json question so does this answer some of your questions https://github.com/nvim-telescope/telescope.nvim/issues/523? If not people say so and i can go over your issue again

**Comment by luc-tielen** [comment]
Ah, looks like somebody had the same idea! I should've done a better search. 
I will look into writing a custom finder for processing the hoogle JSON, seems like the best way to go!

I will close the ticket. :)
