### ISSUE TITLE
Question: How to make a copy of live_grep with fuzzy behaviour.

### ISSUE THREAD

**Issue by luisiacc** [nvim-telescope/telescope.nvim#625]
I have this doubt, I tried using grep_string, but it just doesn't do what I expect, for example if I have a text somewhere that says: `class BalanceForm`, if I write on the grep_string input `BForm` it does not find the BalanceForm text, so I would like to use a fuzzy version of live_grep, or at least change the behaviour of grep_string. I have installed the plugin `telescope-fzy-native` but doesn't seem to make a difference there.

**Comment by Conni2461** [comment]
The whole search query will be forwarded to `ripgrep` so it will never be fuzzy. Same applies to `live_grep` which forwards the each prompt to `ripgrep` after each keypress.
What you can do and i do this for small projects is, basically get all lines and let us do the sorting.

```lua
require'telescope.builtin'.grep_string{ shorten_path = true, word_match = "-w", only_sort_text = true, search = '' }
```

**Comment by luisiacc** [comment]
> The whole search query will be forwarded to `ripgrep` so it will never be fuzzy. Same applies to `live_grep` which forwards the each prompt to `ripgrep` after each keypress.
> What you can do and i do this for small projects is, basically get all lines and let us do the sorting.
> 
> ```lua
> require'telescope.builtin'.grep_string{ shorten_path = true, word_match = "-w", only_sort_text = true, search = '' }
> ```

Oh, this is actually the results that I want, but on a medium size project is really laggy, any way to make it faster ?

**Comment by Conni2461** [comment]
Yeah i know. Like it kills projects with the size of neovim or bigger. This https://github.com/nvim-telescope/telescope.nvim/pull/457 makes it snappier, but it has other problems. TJ said he was planing to picked it up tho. So you would need to wait a little bit longer until these performance issues are (hopefully) resolved :)

**Comment by gabrielbidula** [comment]
Is it possible to add the default config to the overridden grep_string? ie: ```    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case',
      '--ignore',
      '--hidden',
      '--fixed-strings',
    },```
