### ISSUE TITLE
Feature: Expand shortened result paths in the preview title

### ISSUE THREAD

**Issue by TC72** [nvim-telescope/telescope.nvim#627]
When using a layout with a vertical preview window the results window is quite narrow.
Because of this paths often get shortened to just the first letter in the results window:
```
/p/n/d/nvim-treesitter.txt:38:11:  require'nvim-treesitter.conf
```

Right now the Preview title just says "Preview" it would be really useful if the preview could show the expanded path to the file it's currently previewing.
```
Preview: plugged/nvim-treesitter/doc/nvim-treesitter.txt:38:11
```
You could probably lose the word 'Preview' as well.
I'd be happy to code this just want to see if it's something people would want inside telescope or just a recipe?

**Comment by Conni2461** [comment]
I added https://github.com/nvim-lua/plenary.nvim/commit/41b4f834c4cc22ff283f381fd3fe3e00ead3099d to our window/border api to do something similar in #528, which will show you the context of the preview window. Useful for cycling when you are looking at `git diff to parent` or `git diff to head`. I can rewrite it that it will show the filename as title. Just have to decide if i want to make it optional.

Thanks for the suggestion :) is a good one

**Comment by TC72** [comment]
That's great, I need to remember to keep up to date on Plenary changes as well as Telescope.

**Comment by Conni2461** [comment]
![image](https://user-images.githubusercontent.com/15233006/110529721-e1f49480-8119-11eb-8669-04ac86bd106d.png)
Doing that in the #528 PR. I will run this PR for a day and so and make sure everything works after that i kinda tend to merging :laughing:

**Comment by FinallyFinancialFreedom** [comment]
how can you show the path like `/p/n/d/nvim` this?  My full path is too long to see the filename.

**Comment by FinallyFinancialFreedom** [comment]
> > how can you show the path like `/p/n/d/nvim` this? My full path is too long to see the filename.
> 
> You should be able to add `shorten_path = true` to your Telescope config or pass that opt to whatever picker you run and it will do that. Check the [Telescope Defaults](https://github.com/nvim-telescope/telescope.nvim#telescope-defaults) part of the README for this :)

yes i add this config but it does not show like yours. README said this config only affect the sorting behavior, not the presentation.

**Comment by Conni2461** [comment]
This feature can be enabled with `dynamic_preview_title = true,` option

**Comment by TC72** [comment]
Finally got around to trying this. It's great, thanks for getting it added.
