### ISSUE TITLE
Prompt buffer remains when using :close command 

### ISSUE THREAD

**Issue by mah-shee** [nvim-telescope/telescope.nvim#628]
### Description

When I close TelescopePrompt by `:close` command, prompt buffer won't close properly, which causes `E37` and `E162`.

**Expected Behavior**

Prompt buffer closes 

**Actual Behavior**

Prompt buffer remains

### Details

<details><summary>Reproduce</summary>
1. nvim -nu test.vim  
2. :Telescope   
3. :close   
4. :q  

</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+nightly
- Operating system: macOS
- Telescope commit: 

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by elianiva** [comment]
why don't you use `require"telescope.actions".close()` ? It's specifically made to close Telescope window because it needs to do some extra stuff instead of just running `:close` (which is cleaning other stuff like the prompt buffer). Here's the function that gets run for that action https://github.com/nvim-telescope/telescope.nvim/blob/1c80a92d4027c03b65cce1fe27ef664cff77186d/lua/telescope/actions/init.lua#L199-L217

**Comment by mah-shee** [comment]
@elianiva Thanks for the the information. It helped me.
Didn't know that it is required for using the special function to just close a buffer.
