### ISSUE TITLE
Tag sources associated to filetype

### ISSUE THREAD

**Issue by ranjithshegde** [nvim-telescope/telescope.nvim#633]
**Is your feature request related to a problem? Please describe.**
When using the tag(picker?) in telescope, it only displays results if ctags R has been run on that directory. However there are other tags as associated to filetypes such as supercollider.

![CocList](https://user-images.githubusercontent.com/10258296/110620074-e57b3080-8198-11eb-91f9-c687f1516d9a.gif)

Here is the telescope output for the same file

![Telescope](https://user-images.githubusercontent.com/10258296/110620028-d5fbe780-8198-11eb-9d28-7c182b2620b5.gif)

**Describe the solution you'd like**
A functionality like the first gif. I am not sure if its a specific Coc feature, because the same tags (not generated by ctags) are also read by ins-completion already

**Describe alternatives you've considered**
Sticking to cocLists just for this small but significant functionality

**Comment by Conni2461** [comment]
how does this tag file look like? Does it look similar just with a different name? If so you can try this:
```
lua require('telescope.builtin').tags({ ctags_file = 'my_tag_file' })
```

**Comment by ranjithshegde** [comment]
Its a regular tag file. I am attaching it below
Its autogenerated by another vim pluggin scnvim for supercollider. It is usually in /path/to/vim/pluggins/scnvim/scnvim-data/HERE

I am not sure how either Coc or ins-completion finds it, without being in cwd
Quick note, I am attaching it as .txt else hub wont let me

[tags.txt](https://github.com/nvim-telescope/telescope.nvim/files/6115515/tags.txt)

**Comment by ranjithshegde** [comment]
So I suppose the question is not about the tag file variety as much as its location beyond cwd. the root of the. pluggin is ofcourse in nvim's runtime path, if there is someway for telescope to access that?

**Comment by Conni2461** [comment]
Yeah it will only look for `tags` in cwd, but you can specify it with: `ctags_file` option. Should accept a path, but i am not sure if it will resolve relative paths correctly.

There is this PR #288, which i need to figure out why its not working, that will integrate `set tags?` and async tag loading(this still makes problems. I will try to find a solution for it.)

**Comment by ranjithshegde** [comment]
Thanks. I look forward to the PR.
in the meantime I did try your suggestion. regardless of whether I specify the path or place the tag file in cwd and call unaltered :Telescope tags I get the following error

`E5108: Error executing lua ...nvim/plugged/telescope.nvim/lua/telescope/make_entry.lua:844: attempt to concatenate local 'tag' (a nil value)`
Perhaps it is also about the tag format

**Comment by Conni2461** [comment]
Yeah the format is probably slightly off. I wanted to revisited the regex again anyway because since last week we have tag filtering, for lsp and i kinda want it for `tags` as well. So you can do `:func:` and it shows you all functions. But that would require me to read the last part, the `f`, `m`, `c`, `v` to get the typ. I will try to do this this week :) Including #288 PR

**Comment by ranjithshegde** [comment]
oh that would be incredible! Love this plugin and everyone working for it!
Will keep an eye out for the PR

**Comment by Conni2461** [comment]
Sorry for the long wait. I just merged a fix with allowed me to load the provided tag file
