### ISSUE TITLE
Quickfix marked files

### ISSUE THREAD

**Issue by timsofteng** [nvim-telescope/telescope.nvim#634]
Hello. How can I add only marked files to quickfix list?
At this moment if i press `ctrl-q` all files from list added to quickfix list despite of marked files.

**Comment by timsofteng** [comment]
> the action name is `actions.send_selected_to_qflist`

how about map it to `ctrl-q` as well if marked files exist? If no then add all

**Comment by Conni2461** [comment]
We have a `actions.smart_send_to_qflist`, that will send selected to qf if there are selected otherwise send send all. Its just not mapped because @elianiva and I introduced it later. `send_selected_to_qflist` is mapped to `<a-q>` per default

**Comment by timsofteng** [comment]
> We have a `actions.smart_send_to_qflist`, that will send selected to qf if there are selected otherwise send send all. Its just not mapped because @elianiva and I introduced it later. `send_selected_to_qflist` is mapped to `<a-q>` per default

how about changing mapping to each other?

**Comment by timsofteng** [comment]
Or just remap `actions.smart_send_to_qflist` to `ctrl-Q` (capital Q).

**Comment by Conni2461** [comment]
No currently `actions.send_to_qflist` is still mapped to `<c-q>` and `smart_send_to_qflist` is not mapped and we haven't talked about what should be default at all. Mappings is really hard to do right anyway :laughing: because everybody remaps it anyway. 
I currently have mapped:
```lua
["<C-q>"] = actions.smart_send_to_qflist + actions.open_qflist,
```
because i want that `qflist` actually opens after i send stuff to it.

**Comment by timsofteng** [comment]
Got it. How do you think is it any way to add files to existed quickfix list? Not to new one

**Comment by Conni2461** [comment]
Basically the same code but with `'a'` rather than `'r'` its a little bit harder to put in config but basically you can write your your own action and map that. (maybe we can make it configurable or provide an additional action thoughts @elianiva)

This should work (maybe :rofl: )
```lua
local my_actions = {}

my_actions.add_selected_to_qflist = function(prompt_bufnr)
  local picker = action_state.get_current_picker(prompt_bufnr)

  local qf_entries = {}
  for _, entry in ipairs(picker:get_multi_selection()) do
    table.insert(qf_entries, entry_to_qf(entry))
  end

  actions.close(prompt_bufnr)

  vim.fn.setqflist(qf_entries, 'a')
end

my_actions.add_to_qflist = function(prompt_bufnr)
  local picker = action_state.get_current_picker(prompt_bufnr)
  local manager = picker.manager

  local qf_entries = {}
  for entry in manager:iter() do
    table.insert(qf_entries, entry_to_qf(entry))
  end

  actions.close(prompt_bufnr)

  vim.fn.setqflist(qf_entries, 'a')
end

my_actions.smart_add_to_qflist = function(prompt_bufnr)
  local picker = action_state.get_current_picker(prompt_bufnr)
  if table.getn(picker:get_multi_selection()) > 0 then
    my_actions.add_selected_to_qflist(prompt_bufnr)
  else
    my_actions.add_to_qflist(prompt_bufnr)
  end
end

require('telescope.actions.mt').transform_mod(my_actions)

require('telescope').setup {
  defaults = {
    mappings = {
      i = {
        ["<C-q>"] = my_actions.smart_add_to_qflist,
      },
    }
  }
}
```

**Comment by timsofteng** [comment]
looks scary 😬

**Comment by marcelarie** [comment]
Hi everyone, is there a better way now of doing this?

I want that if there are some items marked, `<C-q>` is mapped to what `<M-q>` does (send only the marked ones), but if there are no marked items then it uses the default behavior of `<C-q>` (send all the list).

Is there a simple way of accomplishing this?

**Comment by marcelarie** [comment]
Found a simple way:

```lua
local actions = require "telescope.actions"

local smart_send_to_qflist = function(prompt_bufnr)
    local multi = picker:get_multi_selection()
    local picker =
        require("telescope.actions.state").get_current_picker(
	    prompt_bufnr
	)

    if not vim.tbl_isempty(multi) then
        actions.send_selected_to_qflist(prompt_bufnr)
        actions.open_qflist(prompt_bufnr)
    else
        actions.select_default(prompt_bufnr)
    end
end

require "telescope".setup {
    defaults = {
        mappings = {
           i = { ["<C-q>" = smart_send_to_qflist }
           n = { ["<C-q>" = smart_send_to_qflist }
        }  
    } 
}
```

**Comment by jamestrew** [comment]
fyi `smart_send_to_qflist` exists (as well as other similar actions).
`:h telescope.actions.smart_send_to_qflist`
