### ISSUE TITLE
Default git-related pickers showing literal color codes in Results and Preview windows

### ISSUE THREAD

**Issue by andweeb** [nvim-telescope/telescope.nvim#635]
### Description

I'm having issues using the default git pickers, as literal color codes are rendered on the results list items (and in the preview) for the following:
* `git_commits`
* `git_bcommits`
* `git_branches`
* `git_status`

For example, running `:Telescope git_branches` will show the following results:
```
^[[31mremotes/origin/master^[[m
^[[31mremotes/origin/develop^[[m
master^[[m
```
If I were to select the `master` branch, it seems to include the literal `^[[m` since I get the following error:
```
Error when checking out: master^[[m. Git returned: "error: pathspec 'master?[m' did not match any file(s) known to git"
```

Here's a demo video:
![Demo](https://user-images.githubusercontent.com/10726590/110688855-e317d700-8196-11eb-9695-4d26ce076613.mp4)

**Expected Behavior**
I'd expect the color codes to either not be there or be correctly rendered, and to be able to select a result without an error.

**Actual Behavior**
Color codes are displayed literally in the results and preview text, and errors occur when making a selection.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. Run any of the git pickers mentioned above (`:Telescope git_branches`)
3. Select an item (e.g. a branch), which should lead to an error
</details>

<details><summary>Environment</summary>

- nvim --version output: `NVIM v0.5.0-dev+1133-g0869cbd55`
- Operating system: macOS 11.2.2
- Telescope commit: `add7ee394350f268684cff03d844f32f255fec47`
- Terminal: Kitty/Alacritty with `$TERM=screen-256color`

</details>

<details><summary>Configuration</summary>
<p>

```viml
" (Can reproduce error on my end without any config)
call plug#begin(stdpath('data') . '/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
```

**Comment by Conni2461** [comment]
You probably have a setting in gitconfig that forces color codes to always be displayed even in a job that is not run inside a interactive terminal.
Thats a good catch and we should probably do something like this:
```
git -c "color.status=false" status --short
```

and similar. I can provide a fix in 30mins.

**Comment by andweeb** [comment]
Ooh yep you're exactly right, I had `ui = always` for the color config block in my git config.

Updating it to be `auto` fixed it, thanks!

**Comment by Conni2461** [comment]
You're welcome :)

Still thanks for reporting, i will (or someone else) fix this in the next couple of days :)

**Comment by l-kershaw** [comment]
I've just added a section in the [FAQ](https://github.com/nvim-telescope/telescope.nvim/wiki/FAQ#why-arent-git-pickers-working) to explain this.
Closing this issue now.
