### ISSUE TITLE
None of the Telescope commands works with latest neovim-git.

### ISSUE THREAD

**Issue by edge90** [nvim-telescope/telescope.nvim#638]
### Description

None of the Telescope commands works, eg when running `:Telescope find_files<CR>`.

**Expected Behavior**

A file picker should open.

**Actual Behavior**

`vim.lua:269: Tried to call API function with vim.fn: use vim.api.nvim_create_buf instead`

### Details

<details><summary>Reproduce</summary>

1. Command `:Telescope find_files<CR>`
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1140-g097ec71bd
- Operating system: Linux
- Telescope commit: add7ee394350f268684cff03d844f32f255fec47

</details>

<details><summary>Configuration</summary>
<p>

Add packer
```bash
git clone https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
 ``` 
init.lua
```viml
require'packer'.startup(function()
  -- Telescope
  use {
    'nvim-telescope/telescope.nvim',
    requires = {{'nvim-lua/popup.nvim'}, {'nvim-lua/plenary.nvim'}}
  }
end)
```
Install telescope
 ```viml
 :PackerSync<CR>
 ```

**Comment by elianiva** [comment]
Are you sure you're on the latest version? because 07ce3c3 isn't the latest Telescope, it was from last year :laughing: 
That shouldn't happen though because we've already fixed it (and I couldn't reproduce it)

**Comment by edge90** [comment]
I'm sorry, Don't know what happend. I'm on commit add7ee394350f268684cff03d844f32f255fec47.
