### ISSUE TITLE
Telescope async system actions

### ISSUE THREAD

**Issue by fedoranvar** [nvim-telescope/telescope.nvim#641]
**Is your feature request related to a problem? Please describe.**
I'm a developing on js and css. And I need often need to use terser and sass to convert my files. So I'm spawning float terminal in vim and executing command manually for that

**Describe the solution you'd like**
I would like to spawn `Telescope job` (or place another name for command) and in list choose job I want to do in current buffer (or session, or cwd). 
e.g.
```
1. terser --compress ...
2. sass ...
```
also i  need to be able to declare this commands dynamically, so I can preEdit them before execution (to insert buffername in command for example)
 
**Describe alternatives you've considered**
Can I do it using plenary.job and create bindings ? Or please direct me in a way where I can find a solution

**Additional context**
don't have at the moment

Thanks!

**Comment by tami5** [comment]
Not sure but this might what you are looking for https://github.com/GustavoKatel/telescope-asynctasks.nvim.

**Comment by fedoranvar** [comment]
@tami5 

Yes, that's exactly what I need.

Thanks!
