### ISSUE TITLE
Feature Request : Command History Edit

### ISSUE THREAD

**Issue by FardeenCodes** [nvim-telescope/telescope.nvim#646]
**Is your feature request related to a problem? Please describe.**

The problem is that sometimes i make mistakes in my command
eg. `:lua vim.lsp.buf.signature_help` (forgot the brackets)

**Describe the solution you'd like**

Instead of typing the whole command i just open `Telescope command_history` and press any key e.g. `Ctrl-e` and the commands comes in the command bar

**Describe alternatives you've considered**

Fzf.vim

**Additional context**
In fzf.vim
![Screenshot_20210312-141208~2](https://user-images.githubusercontent.com/71399984/110914992-1f853780-833d-11eb-9ffc-285aab487d39.png)

After pressing `Ctrl-e`
![Screenshot_20210312-141248~2](https://user-images.githubusercontent.com/71399984/110915049-33309e00-833d-11eb-8e7b-2c28664145aa.png)`

**Comment by tami5** [comment]
@FardeenCodes indeed this is very awesome and useful feature. You can test it out in #656
