### ISSUE TITLE
`E13: File exists (add ! to override)` when opening a file from Telescope find_files

### ISSUE THREAD

**Issue by gainhad** [nvim-telescope/telescope.nvim#648]
### Description

If I try to save a file that I've opened via telescope, I get `E13: File exists (add ! to override)`. This doesn't occur when opening a file via `:edit`. This also doesn't occur for every file type. Right now, I'm seeing it for Elixir and JavaScript files, but not Markdown or CSS.

**Expected Behavior**

It saves :)

**Actual Behavior**

It doesn't save :( and I get `E13: File exists (add ! to override)`. I can save with `:w!` though.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. `:Telescope find_files`
3.  Select a file of the types listed above.
4. `:w`
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev+dc8273f2f
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210312-24846-1foiys8/build/config -I/tmp/neovim-20210312-24846-1foiys8/src -I/usr/local/include -I/usr/local/opt/luv/include -I/usr/local/Cellar/tree-sitter/0.19.3/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210312-24846-1foiys8/build/src/nvim/auto -I/tmp/neovim-20210312-24846-1foiys8/build/include
Compiled by hadley@Hadleys-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-dc8273f_1/share/nvim"

Run :checkhealth for more info
```
- Operating system: macOS 10.15.7
- Telescope commit: c8cc024

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment]
This happens when neovim had a read error. `:f` should give you more information.

**Comment by gainhad** [comment]
@Conni2461 Is there a way to get more information? All I see from `:f` is:
```
"filename" [Read errors] 146 lines

**Comment by Conni2461** [comment]
I can't imagine how we would cause this issue. This happens with the linked minimal rc?
Does `:messages` tell us something

**Comment by gainhad** [comment]
Nothing more unfortunately. Maybe this is related: https://github.com/nvim-treesitter/nvim-treesitter/issues/1004

**Comment by gainhad** [comment]
I figured it out. I was using [vim-lsp-settings](https://github.com/mattn/vim-lsp-settings) to install language servers. It's suggested on the nvim-lspconfig wiki, but it looks like it has some autocommands that assume the vim-lsp plugin is installed. For some reason, this caused the issue when opening the file with telescope, but not with `:edit`. Not sure why this happened with the minimal vimrc though. I'm using [Paq](https://github.com/savq/paq-nvim) as a package manager if that helps.
