### ISSUE TITLE
Color devicons settings does nothing

### ISSUE THREAD

**Issue by LoydAndrew** [nvim-telescope/telescope.nvim#652]
### Description
Color devicons settings does nothing, when you change it to true or false it doesn't higlight icons (they are installed in nvim).

**Expected Behavior**
If color_devicons property is set to true it should higlight icons, otherwise shouldn't

**Actual Behavior**
With any configuration setup color_devicons property doesn't effect anything.
But without any config in init.vim icons are actually higlighted.

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev
- Operating system: Xubuntu 20.10 x86_64
- Telescope commit: c8cc024ebf86d58dc37913e1e9ec7e465d687d68

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2
set termguicolors

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'kyazdani42/nvim-web-devicons'
Plug 'joshdick/onedark.vim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
     prompt_position = "top",
     layout_strategy = "horizontal",
     initial_mode = "insert",
     sorting_strategy = "ascending",
     color_devicons= true,
  }
}
EOF
```
set background=dark
colorscheme=onedark

**Comment by Conni2461** [comment]
Only work with `set termguicolors`, because highlight groups only have guifg set. See https://github.com/kyazdani42/nvim-web-devicons/blob/master/lua/nvim-web-devicons.lua#L874 

Also minimal rc is missing: https://github.com/kyazdani42/nvim-web-devicons

**Comment by LoydAndrew** [comment]
Termguicolors is set.
As I mentioned icons is highlighted when I don't provide any `require('telescope').setup` config.

**Comment by Conni2461** [comment]
Oh sorry i just read the title my bad :laughing: 
I tried your min rc (added the missing `set termguicolors`) and it works just fine

**Comment by LoydAndrew** [comment]
I updated config file in bug description - just set colorscheme to any available and it won't work

**Comment by Conni2461** [comment]
Config was missing a `'` probably just copy paste mistake but still can't reproduce. Really sorry about this:
Can you share the `neovim --version` output with git commit hash.

**Comment by LoydAndrew** [comment]
It's on commit 314b222

NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-wDoKOf/neovim-0.5.0+ubuntu2+git202103140420-314b222c2-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-wDoKOf/neovim-0.5.0+ubuntu2+git202103140420-314b222c2-d569569c9/build/config -I/build/neovim-wDoKOf/neovim-0.5.0+ubuntu2+git202103140420-314b222c2-d569569c9/src -I/build/neovim-wDoKOf/neovim-0.5.0+ubuntu2+git202103140420-314b222c2-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-wDoKOf/neovim-0.5.0+ubuntu2+git202103140420-314b222c2-d569569c9/build/src/nvim/auto -I/build/neovim-wDoKOf/neovim-0.5.0+ubuntu2+git202103140420-314b222c2-d569569c9/build/include
Compiled by buildd@lcy01-amd64-028

Features: +acl +iconv +tui

**Comment by windwp** [comment]
My color of devicon is lost too I don't know what happen.
My file tree with nvim-web-devicon has a color.

btw if you change a colorscheme in command after telescope setup  color is lost too.

**Comment by Conni2461** [comment]
`hl_groups` are cleared after doing a `colorscheme ...`
So:
```
:highlight DevIconLua # has output if devicons are loaded, Telescope does this lazy of do lua require'nvim-web-devicons'.setup()
:colorscheme default
:highlight DevIconLua # will be cleared, no highlights
:lua require'nvim-web-devicons'.setup()
:highlight DevIconLua # back again.
```

So you can try to do the `devicon setup` in config. maybe that fixes it for you guys :)

**Comment by LoydAndrew** [comment]
Thanks, that worked. But it looks like a hack, maybe it should be fixed in a proper way. If not I will just close this issue.

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/blob/284f38c57539967b25c7d32700acffd46599c49f/lua/telescope/utils.lua#L341-L345

We have lazy loading, and i don't have `require'nvim-web-devicons'.setup()` in my config so i am not sure why it is not working for you :| we can keep it open for now and i will come back to it in 2/3 weeks when i have time :) If it is not solved by then by another awesome telescope member/contributor :)

**Comment by windwp** [comment]
vim.cmd[[
     autocmd ColorScheme * lua require'nvim-web-devicons'.setup()
  ]]
@LoydAndrew  you can do this

**Comment by dhruvmanila** [comment]
I was facing the same issue but it turned out to be a plugin problem. I have [`nvim-nonicons`](https://github.com/yamatsum/nvim-nonicons) installed which loads `nvim-web-devicons` in the setup function. This sets up the highlight before the colorscheme is set and thus the colors are not rendered as per this comment:
> hl_groups are cleared after doing a colorscheme ...

If you're using `nvim-tree`, then they load `nvim-web-devicons` without checking whether it is loaded or not.
https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/nvim-tree/colors.lua#L72
>My color of devicon is lost too I don't know what happen.
My file tree with nvim-web-devicon has a color.

Telescope only loads it if it was not loaded before.

**Comment by windwp** [comment]
```
vim.cmd[[
autocmd ColorScheme * lua require'nvim-web-devicons'.setup()
]]
```
@dhruvmanila 
you can add this to your config or ask a developer of web-devicons add this on plugin.

It is a not good solution if we call the setup function every time we open telescope.

**Comment by dhruvmanila** [comment]
> It is a not good solution if we call the setup function every time we open telescope.

@windwp Maybe you misunderstood, but the reason for my problem was due to some other plugin calling the setup function of nvim-web-devicons before the colorscheme was set. I solved it simply by calling the setup function once after I set my colorscheme. Something like this:
```lua
vim.cmd[[colorscheme ...]]
require('nvim-web-devicons').setup()
```

Telescope calls the setup function for nvim-web-devicons **only** if it was not called before. This type of scenario can take place: 
- Some plugin calls the setup function for nvim-web-devicons
- `colorscheme` is set (thus, highlight groups are cleared)
- Telescope is fired up

In this case, there won't be any colors for the icons as telescope did not call the setup function because some other plugin already called it before.

@Conni2461 Should telescope call the setup function for nvim-web-telescope without checking if it was loaded before? [nvim-tree does it.](https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/nvim-tree/colors.lua#L72)

**Comment by Conni2461** [comment]
I agree with @windwp. i think @kyazdani42 needs to handle a ColorScheme change by recreating the hl_groups.

I don't think that is something that we have to handle, i think our code of only calling setup when its not loaded makes sense.

https://github.com/nvim-telescope/telescope.nvim/blob/2c4efc2f8af0575526f7b5dcc35fba9e0f1cc944/lua/telescope/utils.lua#L343-L345

**Comment by kyazdani42** [comment]
Hi, is the latest master for nvim-web-devicons fix this issue ?

**Comment by dhruvmanila** [comment]
@kyazdani42 Hey, yes it does fix it for me. Thanks!

**Comment by Conni2461** [comment]
Yep can confirm that works.

Thanks @kyazdani42
