### ISSUE TITLE
Telescope keymaps broken for comma

### ISSUE THREAD

**Issue by rnevius** [nvim-telescope/telescope.nvim#658]
### Description

When searching through `:Telescope keymaps` for mappings which use a comma `,` as the `mapleader`, the fuzzy finder seems to have trouble recognizing the comma character.

**Expected Behavior**

Using `,` in the fuzzy finder returns results that contain a comma and sorts these results properly.

**Actual Behavior**

The comma is not recognized when used with or without an escape character (i.e. searching `,` or `\,`).

### Details

<details><summary>Reproduce</summary>

1. `:Telescope keymaps`
2. `,` ... nothing happens

Or...

1. `:Telescope keymaps`
2. `\,` ... The number of results does not change, but the order (sorting) of the results changes
</details>

<details><summary>Environment</summary>

- `nvim --version` output: NVIM v0.5.0-dev+nightly-93-gc1fbc2ddf
- Operating system: macOS Big Sur
- Telescope commit: 284f38c57539967b25c7d32700acffd46599c49f

</details>

<details><summary>Configuration</summary>

```viml
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-telescope/telescope-fzy-native.nvim'

let mapleader = ","
lua require('telescope').setup {}
```
</details>

**Comment by Conni2461** [comment]
Thats just the default sorter, ngram with n = 2 (if input < n then don't do anything). Works fine with fzy. Another great example why we should change default sorters.
Change `generic_sorter` (and `file_sorter` if you want to use it for `find_files` etc as well) in `telescope.config` to `require'telescope.sorters'.get_fzy_sorter` to use the lua version. See readme for more information

Or even better use https://github.com/nvim-telescope/telescope-fzy-native.nvim for the c/lua ffi version

**Comment by rnevius** [comment]
That does indeed fix the comma issue, but now searching for `<Space>` or `Space` actually filters out the results with "space" in the mapping:

<img width="412" alt="image" src="https://user-images.githubusercontent.com/4516305/111214574-60e24500-85d2-11eb-9153-1cbab3679bba.png">

<img width="511" alt="image" src="https://user-images.githubusercontent.com/4516305/111214514-4c9e4800-85d2-11eb-9c88-14407bd8966c.png">
