### ISSUE TITLE
live_grep does nothing on Windows 10

### ISSUE THREAD

**Issue by TimUntersberger** [nvim-telescope/telescope.nvim#66]
I don't know whether this is something related to `Windows 10` or not, but `builtin.live_grep` does nothing.

It successfully shows the floating window popup and doesn't throw an error, but simply doesn't react to input changes.

### live_grep
![image](https://user-images.githubusercontent.com/32014449/92998341-90c46900-f519-11ea-8638-c1f035040a9d.png)

### cli
![image](https://user-images.githubusercontent.com/32014449/92998363-b7829f80-f519-11ea-8a42-4dc88535d38e.png)

**Comment by rockerBOO** [comment]
Can you show the command you use to run it?

This happened to me but I didn't have rg (which you have).

**Comment by tjdevries** [comment]
my guess is I probably assumed some file separator somewhere?

darn file paths :'(

I don't think it'd be anything with plenary, but I suppose it could do something with jobs.

Other stuff works fine (besides live_grep)?

**Comment by TimUntersberger** [comment]
@rockerBOO telescope uses the predefined command

@tjdevries everything else seems to be working, if I find anything else I'll open a separate issue. 

I tried to recreate `live_grep` myself using `finders.new_job` and added a `print` statement to the `_find` function, but it seems like the function never gets called.

**Comment by tjdevries** [comment]
Any luck after the last few updates? I have cleaned up a lot of things related to this area. (I don't have easy access to windows machine setup to test this out)

**Comment by TimUntersberger** [comment]
It sadly still doesn't work for me. Do you have any idea why the `_find` function won't even be called on Windows?

Btw can you somehow enable crash reports for neovim? Something like a backtrace for segfaults? I need this for a plugin of my own, where neovim just crashes without an error. Sorry for the non issue related question

**Comment by tjdevries** [comment]
I'm wondering if it has something to do with this: https://github.com/luvit/luv/blob/master/docs.md#uv_process_t--process-handle

Check out the `vebatim` section. I can explore some more windows things if I can ever figure out this big memory leak we're having (it could be from plenary's job implementation).

So I'm working on those & related issues at the moment.

**Comment by JSchrtke** [comment]
Just FYI, I am also on win 10, this seems to work now. Not sure since when it's fixed though, I just saw the [latest merged pull in plenary](https://github.com/nvim-lua/plenary.nvim/pull/45) which prompted me to try it again. Anyway, I think this can be closed.

**Comment by Conni2461** [comment]
Oh there is another issue related to this problem 😆 . I only knew about #385 and i fixed that here #422

The last merge plenary merge request is unrelated :)

Closing for now. Thanks for bringing this issue up again @JSchrtke
