### ISSUE TITLE
Preview Section not coming by default

### ISSUE THREAD

**Issue by adityasinha-personal** [nvim-telescope/telescope.nvim#660]
For some reason on my ubuntu system. Preview in case of find_files, grep_string etc is not coming by default.

I have not added any configuration, have only added the plugins and ran :Telescope find_files

I am probably doing something wrong. Please help

**Comment by Conni2461** [comment]
Missing template. Can you share more information. Try with minimal vimrc, `nvim --version` and maybe an image to show whats happening. Otherwise nobody will be able to help you. Bug templates exist for a reason :)

**Comment by adityasinha-personal** [comment]
@Conni2461 Sorry for not creating the issue in the given template. Have mentioned the details. Please have a look.



### Description


Preview in case of find_files, grep_string etc is not coming by default.

**Expected Behavior**


![image](https://user-images.githubusercontent.com/59874185/111383379-1f36c480-86ce-11eb-899a-35dd2eb4a991.png)

**Actual Behavior**


![image](https://user-images.githubusercontent.com/59874185/111383102-cbc47680-86cd-11eb-9649-f16ff0030391.png)


### Details


#### Reproduce

Have commented out all the code in .vimrc and just kept telescope and its mappings. Is this the expected default behaviour or should there also be a preview section?


#### Environment


- nvim --version output:
```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-URUx7I/neovim-0.5.0+ubuntu2+git202103130422-d38508d88-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-URUx7I/neovim-0.5.0+ubuntu2+git202103130422-d38508d88-d569569c9/build/config -I/build/neovim-URUx7I/neovim-0.5.0+ubuntu2+git202103130422-d38508d88-d569569c9/src -I/build/neovim-URUx7I/neovim-0.5.0+ubuntu2+git202103130422-d38508d88-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-URUx7I/neovim-0.5.0+ubuntu2+git202103130422-d38508d88-d569569c9/build/src/nvim/auto -I/build/neovim-URUx7I/neovim-0.5.0+ubuntu2+git202103130422-d38508d88-d569569c9/build/include
Compiled by buildd@lcy01-amd64-022
```
- Operating system: 
` Ubuntu 20.04.2 LTS `


#### Configuration

```viml
" source $HOME/Dotfiles/vim-settings/general.vim
" source $HOME/Dotfiles/vim-settings/plugins.vim
" source $HOME/Dotfiles/vim-settings/common-mappings.vim
" source $HOME/Dotfiles/vim-settings/plugin-mappings/colorscheme.vim
" source $HOME/Dotfiles/vim-settings/plugin-mappings/airline.vim
" source $HOME/Dotfiles/vim-settings/plugin-mappings/autosave.vim
" source $HOME/Dotfiles/vim-settings/plugin-mappings/nvim-completion.vim
" luafile $HOME/Dotfiles/vim-settings/plugin-mappings/nvim-lsp.lua
call plug#begin('~/.vim/plugged')

Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'

call plug#end()

nnoremap ff <cmd>lua require('telescope.builtin').find_files()<cr>
nnoremap fg <cmd>lua require('telescope.builtin').live_grep()<cr>
nnoremap fb <cmd>lua require('telescope.builtin').buffers()<cr>
nnoremap fh <cmd>lua require('telescope.builtin').help_tags()<cr>
```

**Comment by stefanlenoach** [comment]
Hi, I'm running into the same issue as well. Also the UP and DOWN keys have no effect, leaving me unable to do any scrolling within the 'Results' section

**Comment by Conni2461** [comment]
I can't reproduce it with your minimal rc. Make sure you ran it with `nvim -nu minimal.vim`. Also it would be interesting to see the telescope config so can you print the result of following command after running telescope (you have to run it once because `setup` runs on first run when it doesn't run explicit in config)
```
:lua print(vim.inspect(require('telescope.config').values))
``` 

@stefanlenoach `up` and `down` are probably not working because you have an out of date neovim nightly (because we are using a fairly new api function for changing selection). Please rebuild current HEAD and report back :)

**Comment by adityasinha-personal** [comment]
@Conni2461 
My vimrc only has the following lines

```
call plug#begin('~/.vim/plugged')

Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'

call plug#end()

nnoremap ff <cmd>lua require('telescope.builtin').find_files()<cr>
nnoremap fg <cmd>lua require('telescope.builtin').live_grep()<cr>
nnoremap fb <cmd>lua require('telescope.builtin').buffers()<cr>
nnoremap fh <cmd>lua require('telescope.builtin').help_tags()<cr>
```

If I put this in a minimal.vim file and use this config it throws an error for vim-plug

```
Error detected while processing /home/aditya/Dotfiles/minimal.vim:
line    1:
E117: Unknown function: plug#begin
line    3:
E492: Not an editor command: Plug 'nvim-lua/popup.nvim'
line    4:
E492: Not an editor command: Plug 'nvim-lua/plenary.nvim'
line    5:
E492: Not an editor command: Plug 'nvim-telescope/telescope.nvim'
line    7:
E117: Unknown function: plug#end

```
The output of the command you mentioned is -

```
{                                                                                                                       
  border = {},
  borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
  buffer_previewer_maker = <function 1>,
  color_devicons = true,
  entry_prefix = "  ",
  file_previewer = <function 2>,
  file_sorter = <function 3>,
  generic_sorter = <function 4>,
  get_status_text = <function 5>,
  grep_previewer = <function 6>,
  initial_mode = "insert",
  layout_defaults = {},
  layout_strategy = "horizontal",
  mappings = {},
  prefilter_sorter = <function 7>,
  preview_cutoff = 120,
  prompt_position = "bottom",
  prompt_prefix = "> ",
  qflist_previewer = <function 8>,
  results_height = 1,
  results_width = 0.8,
  scroll_strategy = "cycle",
  selection_caret = "> ",
  selection_strategy = "reset",
  sorting_strategy = "descending",
  use_less = true,
  vimgrep_arguments = { "rg", "--color=never", "--no-heading", "--with-filename", "--line-number", "--column", "--smart-case" },

  width = 0.75,
  winblend = 0
}
```

**Comment by Conni2461** [comment]
I think i know whats going on. If the window is too small we don't open a previewer, because it doesn't make sense. I just tested it with a super big font and can reproduce it. 

Try again with a smaller font size or a bigger terminal window.

**Comment by Conni2461** [comment]
You can also add this to your config and try different values. Default 120, it should work if you make this value smaller. Eg. 80
```
lua << EOF
require('telescope').setup{
  defaults = {
    preview_cutoff = 80
  }
}
EOF
```

**Comment by adityasinha-personal** [comment]
Worked like a charm!! :fire: :fire: Thanks @Conni2461

**Comment by stefanlenoach** [comment]
@Conni2461 thanks for the help, working now with nightly nvim :)
