### ISSUE TITLE
Blank content is shown when opening file with Telescope

### ISSUE THREAD

**Issue by Cuzzie** [nvim-telescope/telescope.nvim#661]
### Description
I have all my web dev codes inside a folder call "My Development Stuff" in E: drive. Whenever I try to open any of the files with Telescope, it'll just show me an empty file. There is also a ~ symbol in front of the filename. For example when I try to open E:\My Development Stuff\test.js, it'll show me a blank file, with filename of ~My Development Stuff\test.js. 

I suspect this might have something to do with the E: drive and spaces in my folder name. For example if I open a file in C:\Test Stuff\test.js (C: drive + folder name with space), it works. If I open a file in E:\php\php.ini file (E: drive + folder name without space), it works as well. So this issue seems to only happen when the file is in E: drive and has space in its name. I am not sure if this is a bug or if there are some settings that I need to configure for this to work. 

Let me know if you need more information, thanks.

**Expected Behavior**
When I open a file in a E:\ drive folder which has space in its name using Telescope, the file should be opened correctly.

**Actual Behavior**
When I open a file in a E:\ drive folder which has space in its name using Telescope, a blank file is opened. 

Edit: Added a gif in case my explanation wasn't clear enough.
![telescope_nvim_blank_file_issue](https://user-images.githubusercontent.com/4451176/111293670-79ab3300-8684-11eb-8a60-0a44433e22ed.gif)

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :cd E:\My\ Development\ Stuff\
3. :Telescope find_files
4. Search and open any file (for e.g. test.js)
5. A blank file is opened, with filename of ~My Development Stuff\test.js.
</details>

<details><summary>Environment</summary>

- nvim --version output: 
NVIM v0.5.0-dev+1133-g0869cbd55
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az159-173

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by RRikor** [comment]
I'm experiencing similar behavior. I made a simple function to find files in my home directory, so I can always find files there wherever I am on my system. My home directory is also a git repository. If my pwd is set to my home directory, this will always display a empty file and I have to use fzf. If my pwd is somewhere else, the function works.

```
local M = {}
M.search_dotfiles = function()
    require('telescope.builtin').find_files({
        prompt_title = "~ dotfiles ~",
        cwd = "~/"
    })
end

return M
```

**Comment by l-kershaw** [comment]
I _**think**_ that this may have been fixed by  nvim-lua/plenary.nvim#279

@Cuzzie can you confirm if this fixes your issue?

**Comment by Cuzzie** [comment]
Yeah looks like the issue is now fixed. Thanks for the help!
