### ISSUE TITLE
results_height has no effect when using vertical layout

### ISSUE THREAD

**Issue by jaapz** [nvim-telescope/telescope.nvim#667]
When I use the vertical, mirrored layout, my results window is 4 lines high. The preview window takes up most of the space. I'd like the results window to be larger so I can cycle through more options. Sadly it seems the `results_height` option does not have any effect. I use the following config:

```lua
require('telescope').setup{
  defaults = {
    prompt_prefix = "> ",
    selection_strategy = "reset",
    sorting_strategy = "ascending",
    layout_strategy = "vertical",
    layout_defaults = {
      vertical = {
        mirror = true,
      },
    },
    results_height = 10,
    use_less = false,
    set_env = { ['COLORTERM'] = 'truecolor' }, -- default = nil,
  }
}
```

**Comment by jaapz** [comment]
In fact, the mirror doesn't really matter. It doesn't work for the vertical layout strategy regardless if it's mirrored or not

**Comment by Conni2461** [comment]
`result_height` is only used by `center`. We still plan to do some refactoring of the whole layout_strategies thing. See https://github.com/nvim-telescope/telescope.nvim/projects/2#card-52469090
I have this config for vertical:
```lua
      vertical = {
        width_padding = 0.05,
        height_padding = 1,
        preview_height = 0.5,
        mirror = true,
      }
```

This are the available keys and you can find documentation for them here: `:help telescope.layout`

**Comment by jaapz** [comment]
Thanks, `preview_height` is what I actually needed! Is this issue still needed or can it be closed then?

**Comment by Conni2461** [comment]
We just reworked how layout configuration worked to make configuration more consistent. See `help telescope.changelog` for the breaking changes and `help telescope.layout` for how to configure it.

`result_height` does no longer exist. Closing for now. Feel free to reopen
