### ISSUE TITLE
Default key mapping (<Down> / <Up>) not working for picker.

### ISSUE THREAD

**Issue by PiotrNap** [nvim-telescope/telescope.nvim#669]
### Description
When I'm activating telescope built in functions and want to search for files/ buffers/ words the keys Down and Up aren't working. (for picking the desired search result) 

**Expected Behavior**
Be able to pick the desired result with my Down/Up keys.

**Actual Behavior**
The keys Down and Up aren't working. (they are working fine in neovim)

### Details

<details><summary>Reproduce</summary>

1. Open your project with nvim
2. Run :Telescope find_files
3. .... bang here is the issue

</details>

<details><summary>Environment</summary>

- nvim --version output: v0.5.0-dev+991-g74b343a6f
- Operating system: macOS Big Sur 11.2.1

</details>

<details><summary>Configuration</summary>
<p>

```viml
filetype plugin indent on                                                     
set cot=menuone,noinsert,noselect                                            
                                       
call plug#begin('~/.vim/plugged')
                                                                                                               
Plug 'nvim-lua/popup.nvim'                                                      
Plug 'nvim-lua/plenary.nvim'                                                    
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-telescope/telescope-fzy-native.nvim'
    
call plug#end()
      

```
</details>

https://user-images.githubusercontent.com/59693946/111679961-ffb0b080-8821-11eb-80a4-c0bb0e018746.mov

**Comment by Conni2461** [comment]
Your neovim is fairly old. Please rebuild current HEAD. We are using a fairly new api function for changing the selection thats why its not working.

**Comment by PiotrNap** [comment]
@Conni2461 thank you! This was the issue for me. Have a wonderful day!
