### ISSUE TITLE
Unexpected sorting/matching results

### ISSUE THREAD

**Issue by clason** [nvim-telescope/telescope.nvim#67]
The generic fuzzy sorter seems to have an issue where expected matches don't show up.

For example, doing a fuzzy grep (not live grep! -- see below) over the neovim repo for `onyank` gives the following result:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/2361214/93005353-870a2800-f550-11ea-945c-e46427deaa67.png">

Note that it _doesn't_ show the `highlight.on_yank()` function, which should be the best match, and which fzf.vim returns as the best match:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/2361214/93005384-bae54d80-f550-11ea-8d45-f0285145f3e4.png">

Since that's clearly a better match than the best one in the first screen shot, I have the sneaking suspicion that it's actually returned by the sorter but cut off due to an off-by-one error...

---

Here's the fuzzy grepper function:
```lua
finder.rg = function() builtin.grep_string { search = '' } end
```

**Comment by rockerBOO** [comment]
I think its removing the first result on LSP references?

**Comment by clason** [comment]
I haven't observed that, myself -- and I just checked, and a minimal example (with my server) returns all references.

**Comment by tjdevries** [comment]
(does this still happen for you? I've changed several items related to this area, but can dig into it if it's still happening)

**Comment by clason** [comment]
Yes, same behavior (not exactly the same results, probably due to neovim files changing, but the expected results still doesn't show up).

**Comment by tami5** [comment]
Is this still ongoing issue @clason

**Comment by clason** [comment]
Yes, the sorter still gives (sometimes much) worse results than fzf. Since now you can see the actually matched characters, I don't think it's a bug but rather a shortcoming of the algorithm. So feel free to close in favor of a general "better sorters/matchers" issue.

**Comment by tami5** [comment]
@clason I agree on opening a new issue and explaining the enhancement needed. That way its much clearer. Perhaps titling "better match highlighting", and explain what would better behavior?? Thanks.

**Comment by clason** [comment]
> @clason I agree on opening a new issue and explaining the enhancement needed. That way its much clearer. Perhaps titling "better match highlighting", and explain what would better behavior?? Thanks.

It's not about the highlighting (which is fine now), it's the quality of the sorting (for example, order doesn't seem to be taken into account -- if I type `foobar`, `barxfoo` is sorted before `fooxxbar`, which is clearly not what I want).

**Comment by clason** [comment]
I think sorting/matching in general is a big topic, which probably deserves its own [Project](https://github.com/nvim-telescope/telescope.nvim/projects).

**Comment by tami5** [comment]
> > @clason I agree on opening a new issue and explaining the enhancement needed. That way its much clearer. Perhaps titling "better match highlighting", and explain what would better behavior?? Thanks.
> 
> It's not about the highlighting (which is fine now), it's the quality of the sorting (for example, order doesn't seem to be taken into account -- if I type `foobar`, `barxfoo` is sorted before `fooxxbar`, which is clearly not what I want).

Ohhh I see what you mean, this one of the draw back for using telescope as oppose to something like LeaderF and Fzf.

> which probably deserves its own Project

Hmm I'm not sure what projects are used for now, or would tj even relay on them but an issue can be the starting point for that. 

Do you think that the issue is different for each sorter tele support? or is it something on lower level?

**Comment by clason** [comment]
> Ohhh I see what you mean, this one of the draw back for using telescope as oppose to something like LeaderF and Fzf.

Well, not in itself; it's just the current algorithm that's implemented.

> Hmm I'm not sure what projects are used for now, or would tj even relay on them but an issue can be the starting point for that.

Projects are good for organizing on a larger scale than single issues and PRs -- like sorting, when you might need to implement multiple algorithms and coordinate other improvements. (Otherwise you have a single "big" issue with multiple todos that stays open forever.)

> Do you think that the issue is different for each sorter tele support? or is it something on lower level?

It's different for each sorter of course (as long as it doesn't implement the same simple ngram sorter) -- for example, `fzy_sorter` behaves differently, naturally.

**Comment by tami5** [comment]
> Projects are good for organizing on a larger scale than single issues and PRs -- like sorting, when you might need to implement multiple algorithms and coordinate other improvements. (Otherwise you have a single "big" issue with multiple todos that stays open forever.)

@tjdevries lets use projects heavily to organize our stuff. :D a project I have in mind is "maintain or improve docs"

**Comment by tami5** [comment]
@clason Since we are creating useful conversations around the topic, perhaps is better to reopen the issue and rename to a proper title with changing the content of the first post no?

**Comment by clason** [comment]
> @tjdevries lets use projects heavily to organize our stuff. :D a project I have in mind is "maintain or improve docs"

That would be a good project, yes.

> @clason Since we are creating useful conversations around the topic, perhaps is better to reopen the issue and rename to a proper title with changing the content of the first post no?

Hmm, a new issue might be better. Let's see what @tjdevries thinks about the whole topic of sorting algorithms :)
