### ISSUE TITLE
Broken image link in wiki

### ISSUE THREAD

**Issue by vuki656** [nvim-telescope/telescope.nvim#673]
Image link for LSP Diagnostics [here](https://github.com/nvim-telescope/telescope.nvim/wiki/Showcase#lsp-diagnostics) is broken 

![image](https://user-images.githubusercontent.com/8104698/111848644-d79d7c00-890b-11eb-95ac-047cbb1cbc0f.png)

**Comment by Conni2461** [comment]
Here are the files https://github.com/tjdevries/media.repo/pull/5

**Comment by elianiva** [comment]
yes, I'll fix that once the files have been merged

**Comment by vuki656** [comment]
> Here are the files [tjdevries/media.repo#5](https://github.com/tjdevries/media.repo/pull/5)

Oh, okay. Didn't realize it was a separate repo. 

@elianiva I can fix it as well if you'd like.

**Comment by elianiva** [comment]
sure, thanks! :)

**Comment by elianiva** [comment]
@vuki656 they've been merged, if you want to fix it :)

**Comment by vuki656** [comment]
Fixed in https://github.com/nvim-telescope/telescope.nvim/wiki/Showcase/13f947a209dcbba6ca8c56d4115fd3b6acdcd432

I also added the other 3 gifs for workspace diagnostics, definitions and autocompletion.

Just curios, how was I able to edit it and it went live instantly instead trough a PR? Couldnt someone trash the whole wiki like that? You could revert but still.

**Comment by elianiva** [comment]
you gotta put your trust on people 😆 
I also thought about that when I used the wiki feature for the first time but that never happen
