### ISSUE TITLE
segmentation fault when trying to preview lua files

### ISSUE THREAD

**Issue by wantyapps** [nvim-telescope/telescope.nvim#677]
### Description

I have `<leader>ff` set for file browser and when hovering on a lua file I get a segfault
<img width="1440" alt="Screen Shot 2021-03-21 at 9 25 45" src="https://user-images.githubusercontent.com/56798701/111897217-6c48cc80-8a27-11eb-8084-2bcb962cf9d3.png">

**Expected Behavior**

A preview of the file in the right section

**Actual Behavior**

Segmentation fault

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :Telescope file_browser
3. Hover a lua file
4. Bang. Segfault.
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+nightly-30-gdc3ca16a9
- Operating system: macOS Big Sur 11.1.2
- Telescope commit: How do I get it? I updated a second before posting this issue. Should be latest. (Sorry)

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by wantyapps** [comment]
The terminal is Kitty if that helps

**Comment by wantyapps** [comment]
Update: Updated to latest nvim HEAD and I did not get a seg fault but an error:
<img width="1440" alt="Screen Shot 2021-03-21 at 9 39 48" src="https://user-images.githubusercontent.com/56798701/111897579-62c06400-8a29-11eb-9c39-0a327074a6cd.png">

**Comment by wantyapps** [comment]
I think the problem is treesitter

**Comment by tami5** [comment]
Update nvim-treesitter and TSUpdate

**Comment by wantyapps** [comment]
Oh

**Comment by wantyapps** [comment]
Trying...

**Comment by wantyapps** [comment]
weird... I got something even worse when uninstalled treesitter:
<img width="1440" alt="Screen Shot 2021-03-21 at 9 43 36" src="https://user-images.githubusercontent.com/56798701/111897647-ea0dd780-8a29-11eb-9d65-58dc30060d35.png">

**Comment by tami5** [comment]
Okay this is an error from lua server, basically in current directory you have a huge number of lua files. I'm sure they are some type of generated files

**Comment by wantyapps** [comment]
yeah this is my home (`~`) directory

**Comment by wantyapps** [comment]
So...

**Comment by wantyapps** [comment]
Preview works now but not in home

**Comment by wantyapps** [comment]
BTW Thank you @tami5 for helping me. You answered so fast...

**Comment by wantyapps** [comment]
So in theory the preview should work in any other directory than my home...

**Comment by wantyapps** [comment]
Closing issue.
