### ISSUE TITLE
Telescope doesn't play well with vim-startify

### ISSUE THREAD

**Issue by shubham-cpp** [nvim-telescope/telescope.nvim#678]
### Description

If I open nvim with any files startify plugin is activated. If if then activate telescope find_files and hit escape startify screen is all messed up.
If i open a file using telescope find_files then it hides line numbers,etc Dont know why

![Screen Record of the problem](https://imgur.com/a/LqGbOlK)
[Link to view screen record of bug](https://ufile.io/1em8rvop)

**Expected Behavior**

Work well with vim-startify causing no problem with whats displayed on screen
**Actual Behavior**

For some reason telescope messes up with startify. I believe this is not a startify bug because everything works fine with fzf.vim
### Details

<details><summary>Reproduce</summary>

1. Install `mhinz/vim-startify`
2. start nvim on a directory without providing a file as an arguement
3. run `:lua require('telescope.builtin').find_files()`
4. Select or dont select a file
</details>

<details><summary>Environment</summary>

- nvim --version output: v0.5.0-dev+1165-ge5bef5974(Build type: Release)
- Operating system: Arch Linux
- Telescope commit: Latest(installed this an hour ago)

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF
local actions = require('telescope.actions')

require('telescope').setup {
    defaults = {
        mappings = {
            i = {["<esc>"] = actions.close, ["<A-CR>"] = actions.select_tab},
            n = {["<A-CR>"] = actions.select_tab}
        },
        -- find_command = {'rg', '--hidden', '--files','--follow'},
        vimgrep_arguments = {
            'rg', '--color=never', '--no-heading', '--with-filename',
            '--line-number', '--column', '--smart-case'
        },
        prompt_prefix = "🔍",
        initial_mode = "insert",
        -- get_fuzzy_file,get_generic_fuzzy_sorter,get_fzy_sorter,fuzzy_with_index_bias
        -- file_sorter = require'telescope.sorters'.get_fuzzy_file,
        -- file_sorter = require('telescope.sorters').get_fzy_sorter,
        file_ignore_patterns = {
            ".backup", ".swap", ".langservers", ".session", ".undo", ".git",
            "node_modules", "vendor", ".cache", ".vscode-server", "classes",
            ".venv","%.png","%.jpeg","%.jpg","%.mkv","%.mp3","%.mp4"
        },
        color_devicons = true,
        use_less = true,
        set_env = {['COLORTERM'] = 'truecolor'}, -- default = nil,
        file_previewer = require'telescope.previewers'.cat.new, -- For buffer previewer use `require'telescope.previewers'.vim_buffer_cat.new`
        grep_previewer = require'telescope.previewers'.vimgrep.new, -- For buffer previewer use `require'telescope.previewers'.vim_buffer_vimgrep.new`
        -- qflist_previewer = require'telescope.previewers'.qflist.new, -- For buffer previewer use `require'telescope.previewers'.vim_buffer_qflist.new`
        extensions = {
            fzy_native = {
                override_generic_sorter = false,
                override_file_sorter = true
            }
        }
    }
}
require('telescope').load_extension('fzy_native')

EOF
```

**Comment by tami5** [comment]
relates to #62 #207 #377

**Comment by shubham-cpp** [comment]
My bad. I search for startify for issues it did show anything.Anyways I'll close this since its just a duplicate

**Comment by tami5** [comment]
That's okay @shubham-cpp , the issue needs to be kept open though, unless one of the linked issues solves your problem, then close with a comment for other can benefit from it.

**Comment by shubham-cpp** [comment]
Hey @tami5 I dont how but the problem seems to be fixed right now on the latest release. Installed telescope 2 hrs ago and everything is working as expected

**Comment by Conni2461** [comment]
I just merged a commit that should help with nobuflisted (so startify and others).

Big thanks to @l-kershaw

Closing. Feel free to reopen when this issue still persists.
