### ISSUE TITLE
Make preview buffers load tree-sitter modules besides "highlight"

### ISSUE THREAD

**Issue by m00qek** [nvim-telescope/telescope.nvim#679]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to be able to choose which treesitter modules should be used by the preview bufffer.

**Additional context**
There is a module for tree-sitter that [enable rainbow parenthesis](https://github.com/p00f/nvim-ts-rainbow) in LISP files and I would like to use it in preview windows.
If this feature is indeed something useful for others I, with some guidance, could give a try to implement it.
Thanks!

**Comment by Conni2461** [comment]
Thats all the treesitter magic.

https://github.com/nvim-telescope/telescope.nvim/blob/a7fa60411efbfddc0674d65346a5311e33f6deb1/lua/telescope/previewers/utils.lua#L84-L90

All you would need to do is `require` module and attach it. But i am not sure if we should do this. This might make things slow.

**Comment by m00qek** [comment]
I think I could create a custom `buffer_previewer_maker` that calls the original and then do the logic to get the filetype and to activate other treesiter modules. That would solve it for me. 
If `the original `buffer_previewer_maker` could return a hashmap containing information about the buffer it just created, like ft, lang, etc.) I think it would be fairly easy to do this type of post processing of the preview buffer

**Comment by Conni2461** [comment]
You can just disable `ft_detect` and call `pfiletype.detect(filepath)` yourself. `putils.highlighter` doesn't not have to happen in the scheduled async callback. I already proposed something similar in this commit message https://github.com/nvim-telescope/telescope.nvim/commit/1d40ab5ccda6be3680fd809d34d93366b11c4ef8. The signature just changed from `(filepath, bufnr, bufname, use_ft_detect, callback)` to `(filepath, bufnr, opts)` and `opts` being, `opts.use_ft_detect`, `opts.bufname` and `opts.callback`

**Comment by Conni2461** [comment]
I am closing this issue. We only want to load "highlight" module on default. Everything else should be done with configuration.

If you have a configuration to share, feel free to put it in the wiki. I am almost done with rewriting it and i am about to push after that you can put it in Configuration Recipes, section previewer
