### ISSUE TITLE
Bug: no results in find_files when you type too fast

### ISSUE THREAD

**Issue by Luxed** [nvim-telescope/telescope.nvim#68]
You read that right. This is the first thing that I thought to test.
This is actually something that I really liked about fzf, no matter how fast I write, it will always work properly once it's opened.
This is nothing groundbreaking and I don't know if this only applies to `find_files` or something else.

Here is a demonstration:
[![asciicast](https://asciinema.org/a/mapjHqYH12Fx4FgnsMguYjnR9.svg)](https://asciinema.org/a/mapjHqYH12Fx4FgnsMguYjnR9)

**Comment by tjdevries** [comment]
Awesome, thanks for the bug report and video. I'll see if I can track this down in the next week sometime. Seems like I've got some race condition somewhere.

**Comment by Luxed** [comment]
> Awesome, thanks for the bug report and video.

No problem! Since it's a visual issue, I thought having a video to demonstrate what happens would be a good idea.
I've also got another issue once (that I could not reproduce, so I didn't create a card) where I got 2 file names on the same line.

**Comment by rockerBOO** [comment]
Yes I am also getting the 2 items on 1 line thing.

**Comment by tjdevries** [comment]
Do you still experience the typing too fast thing? I will see if I can reproduce somehow on my machine or something to track down the issue if so.

**Comment by Luxed** [comment]
@tjdevries I'm still able to reproduce it, but now it's only the first time it opens that I can do it every time.
It's more difficult once it has already run once now. But I'm able to get the issue once in a while.
If I'm _really_ fast, I'm still able to do it almost every time, but I think it's out of my typing speed now.

Since what I just said is confusing even to me: yes, I can still experience the issue.

In reality it's not that I type "too fast" (my typing speed is around 60wpm which is quite average or even bad for a programmer). The issue is that I _start_ typing _before_ telescope even appears. Basically when I know what I'm searching for, I'll start typing right after I finished my mapping to spawn telescope (in my case `,ff`). So what I would do to reproduce this issue is `,ffasdf` in one shot instead of doing `,ff` waiting a little and then inputting `asdf`.
I hope this makes more sense now.

**Comment by tjdevries** [comment]
That's very helpful. Thanks.

**Comment by elianiva** [comment]
Is this still an issue? I tried to type before telescope appeared several times (I also restarted nvim in between) and it still works. Tried to use `redrawdebug` to make stuff slower so I can make sure if I typed *before* Telescope appeared, still works just fine. Now that we have `TelescopeFindPre` autocmd, I tried to use `feedkeys` on that event and everything still works.

**Comment by tjdevries** [comment]
OK, let's close then! We have done a lot of refactoring on this code path, so wouldn't surprise me if we fixed it :)

**Comment by Luxed** [comment]
I can confirm, the issue is resolved now!
