### ISSUE TITLE
Add scope information to vim_options

### ISSUE THREAD

**Issue by clason** [nvim-telescope/telescope.nvim#682]
A frequent question when setting options from Lua is "is this local or global or...?"

This information could be added to the `vim_options` picker in addition to / instead of the type (`float`, `bool`, ...). 

Alternatively, one could add an option to print the "Lua names" of options (so, e.g., `vim.wo.number` instead of `number`) -- but this would be made obsolete by https://github.com/neovim/neovim/pull/13479. (The info would still be useful, I think.)

**Comment by Conni2461** [comment]
Merged into dev branch. Please read https://github.com/nvim-telescope/telescope.nvim/issues/1938 if you want to know when it hits master.
