### ISSUE TITLE
custom action example in README produces error

### ISSUE THREAD

**Issue by AndrewECarlson** [nvim-telescope/telescope.nvim#684]
### Description
When I try to use the example config in the README for my_cool_custom_action, it produces an error. When I don't use the transform_mod function to wrap the custom function and just create the new action function directly, it works. 

It looks like the transform_mod way should add some nice stuff like conflict detection that the workaround would miss out on. Also, when I remove the transform_mod call, the workaround breaks with an error message from mt saying it expected a table.

**Expected Behavior**
Printing "This function ran after another action. Prompt_bufnr: <number>" when I hit <c-i> in normal mode from Telescope
**Actual Behavior**
E5108: Error executing lua ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:231: attempt to call local 'key_func' (a table value)

### Details

<details><summary> try to use the custom function in Telescope </summary>

1. nvim -nu test.vim
2. :Telescope <any>
3. .... bang here is the issue

<details><summary>Environment</summary>

- nvim --version output: 
NVIM v0.5.0-dev+1157-g0ab88c2ea
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az204-778

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
- Operating system: Arch Linux
- Telescope commit: I'm not really sure where to check this, but I just updated with packer and the current commit is 83e1993d875d88ab1b715bfdf36c10e6a8ed1ff4

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF
local transform_mod = require('telescope.actions.mt').transform_mod

local actions = require('telescope.actions')


-- or create your custom action

local my_cool_custom_action = transform_mod({ -- Doesn't work
  x = function()
   print("This function ran after another action. Prompt_bufnr: " .. prompt_bufnr)
    -- Enter your function logic here. You can take inspiration from lua/telescope/actions.lua
  end,
})
function actions.my_rad_custom_action(prompt_bufnr) -- workaround
   print("This function ran after another action. Prompt_bufnr: " .. prompt_bufnr)
end

-- Global remapping
------------------------------
require('telescope').setup{
  defaults = {
    mappings = {
      i = {
        -- To disable a keymap, put [map] = false
        -- So, to not map "<C-n>", just put
        ["<c-x>"] = actions.my_rad_custom_action,

        -- Otherwise, just set the mapping to the function that you want it to be.
        ["<C-i>"] = actions.select_horizontal,

        -- Add up multiple actions
        ["<CR>"] = actions.select_default + actions.center,

        -- You can perform as many actions in a row as you like
        ["<CR>"] = actions.select_default + actions.center + my_cool_custom_action,
      },
      n = {
        ["<esc>"] = actions.close,
        ["<C-i>"] = my_cool_custom_action,
      },
    },
  }
}

EOF
```

**Comment by AndrewECarlson** [comment]
Though looking at some of the extensions, I tried creating the action using the format my_neat_custom_action = function()...end and that didn't have any issues after I removed the transform_mod call. I'm new to lua and thought the difference between 

function name() ... end 

vs 

name = function()...end 


was just syntactic sugar

**Comment by Conni2461** [comment]
This is a regression (tj will look into it).

It doesn't work because when concating (`tbl.action1 + other_tbl.action2`) it will now look for `action2` in `tbl` rather than in `other_tbl`. (`action2` does not exist in `tbl`)

It works for builtin actions because they are in the same table.

Hope that makes sense tj :)
