### ISSUE TITLE
open file_browser on the directory of the current file

### ISSUE THREAD

**Issue by tcoopman** [nvim-telescope/telescope.nvim#685]
I can't find this in the documentation, so I don't think it's possible at the moment, but I would love the feature to open `file_browser` on the directory of the current file.

**Comment by Conni2461** [comment]
Option key `cwd` is almost always supported where it makes sense. We are working on documentation (needed to get our own docgen system in usable state first https://github.com/tjdevries/tree-sitter-lua).

Something like this should work
```
lua require('telescope.builtin').file_browser({cwd = vim.fn.expand('%:p:h')})
```

**Comment by tcoopman** [comment]
Thanks, that's exactly what I wanted!
