### ISSUE TITLE
Error while selecting lua file in the list.

### ISSUE THREAD

**Issue by chandrahmuki** [nvim-telescope/telescope.nvim#686]
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch
 : supported between 13 and 13, found 12

this is what i have when i do so 

Thanks a lot for your help

**Comment by elianiva** [comment]
try reinstalling all TS parsers. `:TSUninstall all` and install them again

**Comment by Conni2461** [comment]
Nothing we can do here. Closing
