### ISSUE TITLE
Feature: Possibility to remove buffers in the buffer list

### ISSUE THREAD

**Issue by timjackleus** [nvim-telescope/telescope.nvim#689]
**Is your feature request related to a problem? Please describe.**
When I've been moving around in a project for long enough my buffer list is filling up and I find it very convenient to simply remove the files I'm no longer working in. Before Telescope I used Denite where this feature is available.

**Describe the solution you'd like**
When browsing the buffer list `:Telescope buffers`, I would like to remove the buffer that is focused by a short command like `<c-d>`.

**Describe alternatives you've considered**
Please let me know if you already have alternative / preferred ways of achieving this.

**Additional context**
Nope, but I will take the opportunity to say this plugin truly is amazing and beautiful 🤩

**Comment by elianiva** [comment]
I think we have a couple of these issues, I'm in the middle of something at the moment (internship :laughing:) so I won't be able to implement it. But feel free to make a PR :) 

see these issues:
https://github.com/nvim-telescope/telescope.nvim/issues/621 (Conni has written a solution for this)
https://github.com/nvim-telescope/telescope.nvim/issues/672
https://github.com/nvim-telescope/telescope.nvim/issues/655 (this has more ideas than just closing a buffer)

**Comment by Conni2461** [comment]
I am busy till next Wednesday after that i can finish it. I also kinda want a remove selected entry (that's the tricky part). But i would also accept a PR :) just don't expect a review before Wednesday :laughing:

**Comment by timjackleus** [comment]
Thank you for info, I'm completely new to lua but I'll have a check on the related issues and see if I can figure something out :)

**Comment by Conni2461** [comment]
I am sorry but i wont do this. Someone else should pick it up :)

**Comment by dhruvmanila** [comment]
I can complete this as I already implemented it in my own config. A question: Should this be included in the buffers picker or should it be implemented as an action with a default mapping?

I will open the PR with the implementation and we can discuss there :)
