### ISSUE TITLE
Prompt text insertion is broken if HOME or END is pressed

### ISSUE THREAD

**Issue by ronisbr** [nvim-telescope/telescope.nvim#692]
### Description

The prompt of Telescope is broken if HOME is pressed. When you are typing something and press HOME, the cursor goes to the beginning of the field, as expected, but then it is not moved when inserting characters, remaining in the beginning of the field.

If END is pressed, then the same behavior occurs, the cursor goes to the beginning of the field.

**Expected Behavior**

The prompt should work as any input field when HOME and END is pressed.

**Actual Behavior**

The prompt is broken when HOME or END is pressed.

### Details

1. Open neovim.
2. `:Telescope find_file`
3. Type something and hit HOME or END.
4. Continue typing.

<details><summary>Environment</summary>

- nvim --version output:

```
NVIM v0.5.0-dev+095f5da
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210325-6757-1rdq8rw/build/config -I/tmp/neovim-20210325-6757-1rdq8rw/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210325-6757-1rdq8rw/build/src/nvim/auto -I/tmp/neovim-20210325-6757-1rdq8rw/build/include
Compilado por ronan.arraes@iMac-de-Ronan.local

Features: +acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM/sysinit.vim"
            padrão para $VIM: "
/usr/local/Cellar/neovim/HEAD-095f5da_2/share/nvim"

Run :checkhealth for more info
```
- Operating system:  macOS BigSur
- Telescope commit: a7fa60411efbfddc0674d65346a5311e33f6deb1

</details>

<details><summary>Configuration</summary>
<p>

```viml
require('telescope').setup{
  defaults = {
    prompt_position = "top",
    vimgrep_arguments = {
      'rg',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    }
  }
}
```

**Comment by elianiva** [comment]
the prompt is an upstream bug, see https://github.com/neovim/neovim/issues/13715

**Comment by ljmf00** [comment]
@elianiva This should fix the issue https://github.com/neovim/neovim/pull/15881 .

**Comment by Conni2461** [comment]
This issue is fixed in the latest neovim master: neovim/neovim#16421. Its not part of the 0.6 release
