### ISSUE TITLE
Telescope find files not finding a certain folder

### ISSUE THREAD

**Issue by jrock2004** [nvim-telescope/telescope.nvim#696]
### Description

When I bring up find files and try to find files under the files dir, telescope cannot find anything under it. 

**Expected Behavior**

When I type `files/` I would expect to see files under that directory. I even tried typing a name under that folder and it cannot find it. All other folders work.

**Actual Behavior**

![image](https://user-images.githubusercontent.com/655716/112784034-a7965d00-901e-11eb-85ff-0a8c7d12aae9.png)

### Details

<details><summary>Reproduce</summary>

1. cd ~/.dotfiles
2. nvim
3. :Telescope find_files
4. files/
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+f0ace6d41
- Operating system: macOS Big Sir 11.2.3
- Telescope commit: 

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by elianiva** [comment]
the files under `files/` directory are hidden files (prefixed by `.`) so you need to do `:Telescope find_files hidden=true` to show them

**Comment by jrock2004** [comment]
That did it, thank you very much

```
map('n', '<leader>t', ':Telescope find_files hidden=true<CR>', options)
```
