### ISSUE TITLE
find_files should prioritize partial string matches

### ISSUE THREAD

**Issue by rnevius** [nvim-telescope/telescope.nvim#703]
### Description

When searching for `.scss` files via `:Telescope find_files` and `css` as the search string, `.scss` files are not prioritized. Example:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/4516305/112986919-6a3ae800-9162-11eb-9e9e-dbc645102ebc.png">

**Expected Behavior**

Files with a direct match for `css` should be prioritized before the characters in the search string are split (I hope this makes sense). In other words, this should be the result:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/4516305/112987129-a8d0a280-9162-11eb-9e1a-5fe96cf88815.png">

### Details

<details><summary>Reproduce</summary>

1. `:Telescope find_files` in a project with .scss files
2. Search for `css` ... In some cases, scss results are not prioritized properly.
</details>

<details><summary>Environment</summary>

- `nvim --version` output: NVIM v0.5.0-dev+nightly-169-gf89bfa686
- Operating system: macOS Big Sur
- Telescope commit: aefc831

</details>

<details><summary>Configuration</summary>

```viml
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-telescope/telescope-fzy-native.nvim'
```

```lua
require('telescope').setup {
  defaults = {
    file_ignore_patterns = {
      '%.gif',
      '%.git',
      '%.jpe?g',
      '%.lock',
      '%.pdf',
      '%.png',
      '%.svg',
    },
    file_sorter = require('telescope.sorters').get_fzy_sorter
  },
  extensions = {
    fzy_native = {
      override_generic_sorter = true,
      override_file_sorter = true,
    }
  }
}
require('telescope').load_extension('fzy_native')
```
</details>

**Comment by Conni2461** [comment]
This is not really a bug thats just how the fzy algorithm works. See https://github.com/jhawthorn/fzy/blob/master/ALGORITHM.md

If you want something different, not fuzzy, you should probably take a look at 
```lua
file_sorter = require('telescope.sorters').get_substr_matcher
```

**Comment by rnevius** [comment]
Thanks, closing this.
