### ISSUE TITLE
lsp_workspace_symbols does not work with multiple lsp servers

### ISSUE THREAD

**Issue by ovikk13** [nvim-telescope/telescope.nvim#707]
### Description

If an LSP client receives an id other than 1, then `lsp_workspace_symbols` will fail. This may happen if you use more
than one LSP client, and you are switching between buffers of different file types.

The guard in `telescope/builtin/lsp.lua` will stop if it does not find result from client with id 1:
```lua
-- Clangd returns { { result = {} } } for query=''
  if not results_lsp or vim.tbl_isempty(results_lsp) or
     vim.tbl_isempty(results_lsp[1]) or vim.tbl_isempty(results_lsp[1].result) then
    print("No results from workspace/symbol. Maybe try a different query: " ..
      "Telescope lsp_workspace_symbols query=example")
    return
  end
```

**Expected Behavior**
`lsp_workspace_symbols` should work with even though there is no result for id 1, as long as there is result for
another client.

**Actual Behavior**
`lsp_workspace_symbols` does not work if there is no result for LSP client with id 1. Even though there is result for
another client.

**Comment by fdschmidt93** [comment]
This was an [upstream issue](https://github.com/neovim/neovim/issues/14062) and has now been fixed as of 9 hrs ago. Updating to recent master fixes it - just confirmed myself.

**Comment by ovikk13** [comment]
I'm still able to reproduce this.
## Environment
 - **neovim version**: `NVIM v0.5.0-dev+1211-g6db3ba9df`
 - **telscope.nvim version**: latest commit: `2c4efc2f8af0575526f7b5dcc35fba9e0f1cc944`
 - **OS**: Ubuntu 20.04.02 LTS

## Steps to reproduce
1. `nvim -u NORC`
Configure at least two LSP servers that support `workspace/symbol`. Here I'm using intelephense and sumneko_lua
![image](https://user-images.githubusercontent.com/16265319/113477207-8ef3d000-9480-11eb-9b01-2f96f957fbc2.png)

2. Open a file matching the first LSP, here a `test.php` file, and add some symbols. `Telescope lsp_workspace_symbols query=<name of symbol>` works here.

3. Open the other file type, here a `test.lua` file. After adding some symbols, and running `Telescope lsp_workspace_symbols query=<name of symbol>` you get this error:\
`E5108: Error executing lua vim/shared.lua:199: Expected table, got nil`

## Expected
Should work with the lua client as well. I can confirm it works using the following command:\
`lua print(vim.inspect(vim.lsp.buf_request_sync(0, 'workspace/symbol', { query = 'util' }, 1000)));

![image](https://user-images.githubusercontent.com/16265319/113477315-37099900-9481-11eb-9903-3bb44b8b732d.png)

**Comment by fdschmidt93** [comment]
I see - apologies, I overlooked that you had opened the original issue upstream :) I can also reproduce your scenario; my test case was a bit different in which it seemed to work after upstream issue got fixed. I'll test your PR.
