### ISSUE TITLE
live_grep word under cursor

### ISSUE THREAD

**Issue by 3nuc** [nvim-telescope/telescope.nvim#708]
**Is your feature request related to a problem? Please describe.**
Say I see a translation label code eg. `MyApp_ErrorMessage` in a text file (that's not connected to LSP, so can't go to reference) and wonder:
 > damn, I wish there was a 2 keystroke way to find all occurences of this term across all of my current workspace

For now in the case above, I just run `:Telescope live_grep` and just retype the search term manually 

**Describe the solution you'd like**
1. Allow `live_grep` to take arguments  
`:Telescope live_grep MyApp_ErrorMessage `
Then you could do `nmap <leader>fG <cmd>Telescope live_grep <C-r><C-w><cr>` (`<C-r><C-w>` inserts word under cursor, vim native). That would make live_grep appear with the word under cursor already prefilled  
I kinda expected it to work but passing args just returrns  
``` 
E5108: Error executing lua ...lugged/telescope.nvim/lua/telescope/_extensions/init.lua:11: This extension doesn't exist or is not   installed: live_grep
module 'telescope._extensions.live_grep' not found:
```

2. Make popup window normal mode respect `<C-r><C-w>`  
That way you could do
`nmap <leader>fG <cmd>telescope live_grep<cr><esc><C-r><C-w>`  
So this opens the popup, presses esc to get to normal mode (assuming popup started with insert), then inserts word under cursor

**Describe alternatives you've considered**
Mentioned everything above.

**Additional context**
https://vim.fandom.com/wiki/Word_under_cursor_for_command

Some people also opt to saving the current word under cursor to a register then immediately using the register contents, so if variant 2 is picked, it'd make sense to support registry entry in picker normal mode

**Comment by 3nuc** [comment]
https://github.com/nvim-telescope/telescope.nvim/blob/2c4efc2f8af0575526f7b5dcc35fba9e0f1cc944/lua/telescope/builtin/files.lua#L76

`nmap <leader>fG :Telescope grep_string search=<C-R><C-W><CR>`

I now realized the issue title may mean "well grep_string has a search param but why doesn't live_grep?" but that's not really what I meant, I just wanted "grep a string with args, not keyboard input"

**Comment by jayceekay** [comment]
> https://github.com/nvim-telescope/telescope.nvim/blob/2c4efc2f8af0575526f7b5dcc35fba9e0f1cc944/lua/telescope/builtin/files.lua#L76
> 
> `nmap <leader>fG :Telescope grep_string search=<C-R><C-W><CR>` - had to use `:` because doesn't work with `<cmd>` for some reason
> 
> I now realized the issue title may mean "well grep_string has a search param but why doesn't live_grep?" but that's not really what I meant, I just wanted "grep a string with args, not keyboard input"

wasn't able to get this working, but `nnoremap \ :execute 'Telescope grep_string search='.expand('<cword>')<CR>` did

**Comment by 3nuc** [comment]
If you want the mapping to look more like something from the Telescope readme I came up with this:
```
nnoremap <leader><f2> <cmd>lua require('telescope.builtin').grep_string({search = vim.fn.expand("<cword>")})<cr>
```
or with lua:
```
vim.api.nvim_set_keymap( 'n', '<leader><f2>', '<cmd>lua require(\'telescope.builtin\').grep_string({search = vim.fn.expand("<cword>")})<cr>', options)

```
