### ISSUE TITLE
Colorize terminal buffer preview

### ISSUE THREAD

**Issue by Matts966** [nvim-telescope/telescope.nvim#714]
**Describe the solution you'd like**

It would be awesome to colorize terminal buffer preview for more visibility.

Current previewer does not invoke buffer related autocommands maybe for performance perspective. Could we invoke some color related autocommands only when the buffer is terminal?

**Comment by Conni2461** [comment]
I would need to restructure some things to make this possible. I talked about it somewhere. Its on my todo list. 

But thanks to open a issue to make it trackable :)

**Comment by fdschmidt93** [comment]
#1120 would fix it if it gets merged (I'm not crazy about it myself). If not, I'm happy to guide anyone who wants authentic terminal buffers in the buffer previewer enough to work on it him/herself to a more principled solution.

**Comment by fdschmidt93** [comment]
Considering how involved the solution is for such a supposedly innocent issue, I'd kindly ask users who want to see this fix get merged to please test drive #1120 

Thank you in advance :)

**Comment by tjdevries** [comment]
Is the problem that we don't highlight terminal buffers? I'm not sure what's happening here.

Maybe instead we can use the builtin: `nvim_open_term` to get terminal highlighting?

Sorry, I'm confused about this issue.

**Comment by Matts966** [comment]
Sorry @tjdevries, I should show some screenshots.

With denite, the preview is simply the terminal buffer itself and colorized.

<img width="1440" alt="スクリーンショット 2021-08-21 11 18 19" src="https://user-images.githubusercontent.com/28551465/130307521-2b5309c5-4514-4360-b1ea-cb954da5161f.png">

`Telescope buffers` is performant, but it shows monochrome terminal preview

<img width="1440" alt="スクリーンショット 2021-08-21 11 18 53" src="https://user-images.githubusercontent.com/28551465/130307559-4ad68293-5991-4ae6-a5d1-6343b9515bb2.png">

This sometimes leads to difficulty in finding terminal buffers with many open buffers.

**Comment by fdschmidt93** [comment]
@tjdevries Conni and I've got this :) It's quite convoluted.. if you want me to give you the full rundown, happy to elaborate.

**Comment by Matts966** [comment]
@fdschmidt93 
Using latest `Telescope buffers` perfectly visualize my terminal buffers 🚀 
Thank you!!

**Comment by fdschmidt93** [comment]
PSA: #1120 will essentially be reverted #1400. The original PR introduced a lot of additional maintenance burden and unexpected behavior/side effects we can hardly, if at all, recover from. Therefore, we decided to revert the previewer to how it was before.

**Comment by kuator** [comment]
> PSA: #1120 will essentially be reverted #1400. The original PR introduced a lot of additional maintenance burden and unexpected behavior/side effects we can hardly, if at all, recover from. Therefore, we decided to revert the previewer to how it was before.

:cry:

**Comment by fdschmidt93** [comment]
If anyone comes up with a way to extract the lines from a terminal buffer _including_ the ANSI color codes, it would be relatively straightforward. I've spent some time on this and maybe I'm missing something, but I unfortunately haven't yet found a way to do so.
