### ISSUE TITLE
undolist builtin (maybe even a session builtin)

### ISSUE THREAD

**Issue by zenfailure** [nvim-telescope/telescope.nvim#715]
I think the tilte suffices, a jump list builtin with file preview and undolist builtin with vimdiff preview could be an interesting additional default feature. Perhaps also a session builtin for vim sessions.

**Comment by weilbith** [comment]
The undolist is kinda hard as it is a tree not a list. But I like the jumplist.

**Comment by Conni2461** [comment]
Jumplist is in master. I am not sure about the undolist tho. 

You might want to use this for undo https://github.com/mbbill/undotree

**Comment by Conni2461** [comment]
For session you can use this session manager: https://github.com/Shatur/neovim-session-manager
For undotree: https://github.com/mbbill/undotree

Closing for now
