### ISSUE TITLE
Generating pickers from buffer lines matching regexp

### ISSUE THREAD

**Issue by zenfailure** [nvim-telescope/telescope.nvim#716]
I hate folding, and really, the only occasion where I do use folding is to section config files, but i'd like to avoid it.
If it was possible to generate pickers from lines matching regexp, we could replace folding comments in config files by just marked comments such as " *** for vim. We'd have a nice ability to list and filter every section of a config file by matching comment lines starting with whatever regexp (3 asterisks here). This, I guess, could also be used for all kinds of other file formats, I'm thinking markdown.

**Comment by Conni2461** [comment]
I think this is possible. Just get the buffer content and find all the lines matching this regex and put it in a table finder into picker.

But i dont think this should be part of telescope core. Could be a nice addition to the wiki or a small extension. Closing
