### ISSUE TITLE
Open TelescopeMultiSelection items in splits/tabs

### ISSUE THREAD

**Issue by horseinthesky** [nvim-telescope/telescope.nvim#717]
**Is your feature request related to a problem? Please describe.**
I'm trying to move from fzf.vim to telescope and can't find how to achieve the most frequently used feature in fzf - opening several selected items in splits/tabs.
Telescope already has multiple selection but running any of `actions.select_horizontal`/`actions.select_vertival`/`actions.select_tab` opens only the last item added to multiple selection.

**Describe the solution you'd like**
`actions.select_horizontal`/`actions.select_vertival`/`actions.select_tab` should open each item of multiple selection in its own split/split/tab.

**Describe alternatives you've considered**
There are none.

**Comment by elianiva** [comment]
see https://github.com/nvim-telescope/telescope.nvim/pull/571

**Comment by fdschmidt93** [comment]
I'm preemptively closing that as it reflects a duplicated issue, the team is aware and this will eventually be universally supported by multi-select actions.

#1048 also has a workaround in the meantime.
