### ISSUE TITLE
Highlighting not applied correctly to the preview for `bash` shebangs

### ISSUE THREAD

**Issue by marioortizmanero** [nvim-telescope/telescope.nvim#721]
### Description

**Expected Behavior**

If you look for a file with `:Telescope find_files` without an extension but with a `bash` shebang, the syntax highlighting is disabled.

Cases where it works:

```
#!/bin/sh

echo "test"
```

```
#!/usr/bin/env python

print("test")
```

```
#!/bin/python

print("test")
```

```
#!/usr/bin/env sh

echo "test"
```

Cases where it doesn't:

```
#!/usr/bin/env bash

echo "test"
```

```
#!/bin/bash

echo "test"
```

**Actual Behavior**

Telescope should take the shebang into account and use that for highlighting, like vim usually does for regular editing, or like Telescope itself does for the working examples.

### Details

<details><summary>Reproduce</summary>

1. Create one of the non-working examples

2. Run `:Telescope find_files` with the default config. You'll notice that the preview appears all white:

    ![image](https://user-images.githubusercontent.com/25647296/113505907-ea39c700-9541-11eb-89d8-e4a8d260da27.png)

    But if you use `#!/bin/sh` it does work...

    ![image](https://user-images.githubusercontent.com/25647296/113506110-1dc92100-9543-11eb-8815-0753cb20fec7.png)

</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: Arch Linux, `Linux 5.11.11-arch1-1 #1 SMP PREEMPT Tue, 30 Mar 2021 14:10:17 +0000 x86_64 GNU/Linux`
- Telescope commit: 0944c4a88f79ff45e5e750ebecdcb476ca221193

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment]
We have shebang detection. (we are guessing filetypes because we can't run auto commands, too slow).
https://github.com/nvim-lua/plenary.nvim/blob/913bbcde1a4b719e6540b6c350b9388f4f7683a5/data/plenary/filetypes/builtin.lua#L1-L4

Maybe bash should return filetype `sh` and not `bash`. But it works for me :thinking: 
![image](https://user-images.githubusercontent.com/15233006/113506507-90d39700-9545-11eb-99fe-fc5280a76a3b.png)

**Comment by marioortizmanero** [comment]
Huh interesting. I'll try on another machine later today, maybe it's my setup outside of neovim.

**Comment by Conni2461** [comment]
You can also just ask the "oracle" yourself.
```
:lua print(require('plenary.filetype').detect('path/to/file'))
```

**Comment by marioortizmanero** [comment]
With that it does return `bash`... And it seems to work if the file ends with `.bash`.

**Comment by Conni2461** [comment]
Maybe i did an upsi here and 
https://github.com/nvim-lua/plenary.nvim/blob/913bbcde1a4b719e6540b6c350b9388f4f7683a5/data/plenary/filetypes/builtin.lua#L4
shoud be
```lua
['bash'] = 'sh',
```
because https://github.com/nvim-lua/plenary.nvim/blob/913bbcde1a4b719e6540b6c350b9388f4f7683a5/data/plenary/filetypes/base.lua#L543 is :laughing:

If that fixes the issue feel free to create a PR in plenary

**Comment by marioortizmanero** [comment]
That indeed did the trick. Thanks, just opened https://github.com/nvim-lua/plenary.nvim/pull/128
