### ISSUE TITLE
LSP: include language client name in code action picker

### ISSUE THREAD

**Issue by williamboman** [nvim-telescope/telescope.nvim#724]
**Is your feature request related to a problem? Please describe.**
When selecting which code action to apply, it's often a bit unclear to me which language server is actually suggesting the action. I think it'd be helpful to get some info about who/what is suggesting a code action.

**Describe the solution you'd like**
Display the name of the language server at the end of each code action line (see screenshot). My findings so far suggests that using the LSP client name is the most straight forward, as the code action response doesn't seem to include any `source` field

**Describe alternatives you've considered**
Implementing my own custom picker.

**Additional context**

I've got a working patch locally (based off of #722).

![Screenshot 2021-04-04 at 15 27 39](https://user-images.githubusercontent.com/6705160/113517328-86ce8a00-957f-11eb-948f-b2aff45d73da.png)

**Comment by lrvpxl** [comment]
Hey, off-topic but how did you managed to show code actions from ESLint in the list? What plugins did you installed to achieved that, and if possible can you link your dotfiles where that code is defined?

**Comment by williamboman** [comment]
Sure! It's via https://github.com/williamboman/nvim-lsp-installer. See https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/installers/eslintls.lua

**Comment by lrvpxl** [comment]
One more question, is `eslintls.lua` only providing code actions or is it also providing linting errors and warnings?

**Comment by williamboman** [comment]
> One more question, is `eslintls.lua` only providing code actions or is it also providing linting errors and warnings?

It gives you diagnostics as well, for example:

<img width="715" alt="Screenshot 2021-04-05 at 13 00 08" src="https://user-images.githubusercontent.com/6705160/113567431-e58f1480-960e-11eb-9bd5-0d13fd69d885.png">

<img width="1061" alt="Screenshot 2021-04-05 at 13 04 53" src="https://user-images.githubusercontent.com/6705160/113567781-87aefc80-960f-11eb-9219-b92f96ce8201.png">


> There is [`validate` turned on](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/installers/eslintls.lua#L13), is this reponsible for providing linting errors?

Yep, see the LSP implementation [here](https://github.com/microsoft/vscode-eslint/blob/main/server/src/eslintServer.ts#L1106) for example.
