### ISSUE TITLE
Run scripts from telescope

### ISSUE THREAD

**Issue by tcoopman** [nvim-telescope/telescope.nvim#727]
Not sure if this is a feature request / help.
What I want is simplified version of tasks in vscode but with telescope.

I would like a telescope finder that searches:
1. package.json for scripts
2. a configurable directory for scripts (for example bin/dev.sh, bin/test.sh)

Then I want to execute those in a term and in the correct split: for example pressing `<ctrl+x>` on the entry `bin/dev.sh` would do: `sp term://bin/dev.sh`

I'm not sure if this is currently possible and if it is, I don't have a good idea on how to do it.

**Comment by elianiva** [comment]
I think it's possible, here's how I'd do it.

- read package.json and decode it using `vim.fn.json_decode`
- take the `scripts` table (and preprocess it, if you want)
- generate a new picker from this table (see builtin pickers for references)
- attach a custom mappings that would prepend `term://` if someone tries to open a split, if not, just run that script using plenary Job

**Comment by tcoopman** [comment]
Thanks, going to try that

**Comment by sunjon** [comment]
Have you seen/tried [Asynrun](https://github.com/skywind3000/asyncrun.vim) (and [Asyntasks](https://github.com/skywind3000/asynctasks.vim)) ? It provides output for plugins like Telescope to manipulate.

**Comment by fdschmidt93** [comment]
@elianiva surely works, I'm doing the same thing with Zathura and PDFs.

I'll note it to myself to have an example for that. 

For the time being, I'll close this. Please comment if there are further issues or you'd like me to share my example here.
