### ISSUE TITLE
Feature request: Ability to add results to location list

### ISSUE THREAD

**Issue by chasinglogic** [nvim-telescope/telescope.nvim#729]
**Is your feature request related to a problem? Please describe.**
When using `live_grep` it is not possible to add all of the locations to the location list. This prevents multiple use cases (such as visiting or operating on each match).

**Describe the solution you'd like**
When doing `live_grep` (or similar) I should be able to add all the matches to the location list.

**Describe alternatives you've considered**
None. (If this feature exists and isn't documented it should be, I'd be happy to write those docs).

**Additional context**
FZF.vim's equivalent of live grep supports this feature by pressing `M-a` then `Enter`.

**Comment by elianiva** [comment]
we can send them all to `qflist`, any reason why you'd need loclist instead of qflist?

**Comment by chasinglogic** [comment]
Nope quickfix list would be fine as well. Are you saying that's already supported?

**Comment by elianiva** [comment]
yes, it's `<C-q>` by default. There are some other variants as well, see `lua/telescope/actions/init.lua`

**Comment by chasinglogic** [comment]
Ah thanks!

I tried searching for lists in the README / help docs and couldn't find it.
