### ISSUE TITLE
Add a 'builtin.lsp_implementations' picker similar to lsp_definitions

### ISSUE THREAD

**Issue by urandom** [nvim-telescope/telescope.nvim#730]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to list an interface's implementations using telescope

**Describe the solution you'd like**
An LSP Picker like builtin.lsp_definitions.

It looks like the only difference between the two would be the lsp method, which for implementations would be: "textDocument/implementation"

**Describe alternatives you've considered**
I'm currently using nvim's builtin implementations action, which shows them in a quickfix window.

**Additional context**
N/A

**Comment by tami5** [comment]
Indeed that a nice feature to have. For now, if you want to work, just map a key to the function below:

```lua
OpenLspImplmentations = function(opts)
  opts = opts or {}

  local params = vim.lsp.util.make_position_params()
  local result = vim.lsp.buf_request_sync(0, "textDocument/implementation", params, opts.timeout or 10000)
  local flattened_results = {}
  for _, server_results in pairs(result) do
    if server_results.result then
      vim.list_extend(flattened_results, server_results.result)
    end
  end

  if #flattened_results == 0 then
    return
  elseif #flattened_results == 1 then
    vim.lsp.util.jump_to_location(flattened_results[1])
  else
    local locations = vim.lsp.util.locations_to_items(flattened_results)
    pickers.new(opts, {
      prompt_title = 'LSP Implementations',
      finder = finders.new_table {
        results = locations,
        entry_maker = opts.entry_maker or make_entry.gen_from_quickfix(opts),
      },
      previewer = conf.qflist_previewer(opts),
      sorter = conf.generic_sorter(opts),
    }):find()
  end
end

```

If you have time you can open a pr and we can further test it and refine it.

**Comment by amirrezaask** [comment]
What is stopping us from merging this ?
