### ISSUE TITLE
New builtin to list buffers in current working directory only

### ISSUE THREAD

**Issue by thornomad** [nvim-telescope/telescope.nvim#733]
> NOTE: I did see you have a `telescope-project` plugin but it doesn't seem to have the feature specifically I am looking for.

**Is your feature request related to a problem? Please describe.**

In neovim you can set a "current working directory" for each tab/window.  See `:h tcd`.  I use this to organize my tabs into "projects".  Each tab has it's own working directory and when I switch between them the working directory switches.

The problem is: I want Telescope to _show me the active buffers of **only** the current working directory_. 

**Describe the solution you'd like**

It would be nice to implement something like `builtin.buffers_in_current_directory` that would filter the buffers based on the current working directoy.

I am coming from FZF and have been using: https://github.com/m00qek/nvim-contabs with fzf.  It works great!

**Comment by Conni2461** [comment]
Could be an option (If someone wants to do it).
- get cwd with (vim.loop.cwd())
- And filter out all buffers that are not in that directory (nvim_buf_get_name (should return full path, maybe not expanded))

**Comment by tami5** [comment]
@thornomad this can be added as an option to buffers picker, basically checking against a variable, for example `only_cwd` and when it's true it will filter buffers that are not based on current directory. feel free to tag me if you need help implementing this

**Comment by thornomad** [comment]
> feel free to tag me if you need help implementing this

@tami5 "need help" would be an understatement!  Smile.  Haven't ever done any vim scripting or lua myself (aside from custom configurations and copy-pasta).  So this would be a ground up learning experience.

I am glad to hear though it's not too difficult — but will have to find time to even begin learning how to make it happen!  If someone else comes across this in the meantime and wants to implement it by all means.  Otherwise: one day when I have an itch to dive into a whole new programmatic rabbit hole I will be back.

**Comment by nc1337** [comment]
@tami5  I would like to work on this one if it's fine. This is my first time contributing. So might need some help.

**Comment by tami5** [comment]
> @tami5  I would like to work on this one if it's fine. This is my first time contributing. So might need some help.

sure you can contact me on gitter ot tag in the pr .
