### ISSUE TITLE
How can I open more than 1 file?

### ISSUE THREAD

**Issue by tomzaku** [nvim-telescope/telescope.nvim#734]
**Is your feature request related to a problem? Please describe.**
Hi, Thank you for creating an awesome package.
I have a problem with opening more than 1 file.

**Describe the solution you'd like**
- I can able to select multi files from results but I cannot see the windows to switch those files.
Do you have any ideas about this?
![image](https://user-images.githubusercontent.com/19413272/113889665-06658e80-97f6-11eb-9272-17c5df2afcd4.png)

And How can I save the previous results/ and search text? Sometimes, I would like to reopen to double-check those files.

Thank you again. This plugin helps me a lot in my work.

**Comment by tami5** [comment]
I'm not sure if there's a builtin function for opening selected items. But there's a default mapping that send selected items to quick fix and open that quick fix:

```lua
      ["<M-q>"] = actions.send_selected_to_qflist + actions.open_qflist,
      ["<C-q>"] = actions.send_to_qflist + actions.open_qflist,
```

I guess it would be easy to create a custom action to iter over the quick fix and open each file.

For saving search text there's a pr that record a global history #521 and an extended version using sqlite that record user input pre picker, it's currently under development. 

Hope that helps.

**Comment by tomzaku** [comment]
That is  a big help
