### ISSUE TITLE
<Tab> searches upwards while <S-Tab> searches downwards

### ISSUE THREAD

**Issue by saahiluppal** [nvim-telescope/telescope.nvim#740]
while in find_files() or find_buffers(),
<Tab> acts as Ctrl-P (goes upwards) while <S-Tab> acts as Ctrl-N (goes downwards).
Which is opposite of what i'm used to.

Can we change this behaviour?

**Comment by tami5** [comment]
yah, you can remap, see https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes and https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/actions/init.lua
