### ISSUE TITLE
Is there a way to copy the content of a file on click and paste it in current cursor position?

### ISSUE THREAD

**Issue by Tinku10** [nvim-telescope/telescope.nvim#746]
I am trying to build a feature where I would pass a folder to Telescope. After that when I issue a command, telescope would pop-up with all the files in that folder.
From here if I click enter on a filename, rather than going to the file I want the content of that file to be copied and put inside my current buffer at the cursor position.

Here is a function I tried building.

```lua
local lookup = {  }

local function take_content(content)
  -- this function will grab the content and put it in the current buffer cursor point
end

-- dir will be passed from the current buffer
lookup.get_from_source = function(dir)
    require('telescope.builtin').find_files({
        prompt_title = 'Files',
        cwd = dir,
        attach_mapping = function (prompt_bufnr, map)
          local function get_content(close)
            local content = require('telescope.actions.state').get_selected_entry(prompt_bufnr)
            take_content(content.value)
            if close then
              require('telescope.actions').close(prompt_bufnr)
            end
          end
          return false
        end
    })
end

return lookup
```

I had this behaviour working previously with FZF, but I want to replace that behaviour with Telescope. I want to know if this is possible.

Sorry if this does not make any sense.

**Comment by Tinku10** [comment]
I was able to do it with @ThePrimeagen's help.

**Comment by jonahfang** [comment]
@Tinku10 ,I'm curious how you achieved this function, which is exactly what I need now.

**Comment by Tinku10** [comment]
You can take a look at https://github.com/Tinku10/config-nvim/blob/b1f6bb0fbc438938999b34b0882ff1ccf6c1c9b3/lua/configs/telescope.lua#L112-L133 for reference. Hope it helps!

**Comment by jonahfang** [comment]
@Tinku10 ,Thank you very much for so quick reply . My opened file name like this '/home/fzx/mysnippets/jsprompt prompt.js' (has space in file name), and this command fail:

```

  │ local content = vim.fn.systemlist('cat ' .. require('plenary/path'):new(path_to_file):absolute())

  cat: /home/fzx/mysnippets/header: No such file or directory
  cat: hugo: No such file or directory
  cat: article: No such file or directory
  cat: header.txt: No such file or directory
```

**Comment by Tinku10** [comment]
You can try something like this:

```lua
file_path = "/path/to/file with space.txt"
file_path = string.gsub(file_path, " ", "\\ ")
file_path = require('plenary/path'):new(file_path):absolute()
vim.fn.systemlist("cat " .. file_path))
```

This will escape the space in file name with a `\` so that Unix can treat it as a single argument to `cat`. This will basically make the file path like `/path/to/file\ with\ space.txt`

**Comment by jonahfang** [comment]
Thanks, it works!
