### ISSUE TITLE
Added Sessions support to telescope

### ISSUE THREAD

**Issue by JoseConseco** [nvim-telescope/telescope.nvim#749]
I made sessions loader based on  https://github.com/nvim-telescope/telescope-project.nvim
But rather than 'cd' into project directory my plug just loads vim session file ( :so  SessionFile) on Enter key.
It assumes that user did not change default sessions location for now. I'm using default vim sessions dir:
`local sdir = vim.fn.stdpath('data') ..'/session/'`
If Telescope devs are interested I could upload it somewhere. I'm new to lua ad vim so do not expect high quality code : )

https://user-images.githubusercontent.com/13521338/114282783-63578380-9a46-11eb-9393-76883a409d14.mp4

**Comment by tjdevries** [comment]
Yeah, this seems cool. If you want to make a PR, I can take a look at some point.

You can make the session dir an option as well, but we can talk about that in the PR. Looks cool!

**Comment by Conni2461** [comment]
https://github.com/Shatur/neovim-session-manager seems like a pretty good solution as well

**Comment by fedoranvar** [comment]
Also there is https://github.com/rmagatti/session-lens

**Comment by Conni2461** [comment]
The community has provided a good enough solution for this Problem. There is no need to ship this inside telescope core.

Closing
