### ISSUE TITLE
resume previous list

### ISSUE THREAD

**Issue by sodiumjoe** [nvim-telescope/telescope.nvim#751]
**Is your feature request related to a problem? Please describe.**
I'm switching from [denite](https://github.com/Shougo/denite.nvim), and the one thing I'm missing is its `-resume` flag, which simply restores the previous list, in the same filtered state/order. This allows me to, for example, search my project for a token, then go through the list and make modifications. The quickfix workflow from https://github.com/nvim-telescope/telescope.nvim/issues/52 is close, but it doesn't give me the ability to keep track of where in the list my current progress is.

**Describe the solution you'd like**
`:Telescope resume` to simply re-open my last Telescope search, in the same state.
`:Telescope resume cursor_pos=+1` to re-open my last Telescope search with the cursor one line above the previous state.
`:Telescope resume cursor_pos=-1` to re-open my last Telescope search with the cursor one line below the previous state.

**Describe alternatives you've considered**
`:Telescope next/previous` to take the default action on the next/previous item in the previous search, e.g. open the next buffer after `:Telescope buffers`.

**Additional context**
https://github.com/Shougo/denite.nvim/blob/master/doc/denite.txt#L905
https://github.com/Shougo/denite.nvim/blob/master/doc/denite.txt#L684

**Comment by egidijusz** [comment]
This is also a thing I miss coming from doom-emacs. I'm so used to it that it's kind of a blocker to fully embrace Telescope.

[LeaderF](https://github.com/Yggdroot/LeaderF) has `--recall` option. So I'm currently using a mix of both Telescope and LeaderF. :sweat_smile:  Would love to fully switch to Telescope though!

**Comment by YodaEmbedding** [comment]
In a similar vein, `:Telescope builtin mru=true` or `:Telescope builtin open_latest=true` would be nice too.

**Comment by 9ary** [comment]
This would also make telescope a solid replacement for [ack.vim](https://github.com/mileszs/ack.vim), if not even more ergonomic. The quickfix window doesn't interact very nicely with splits.

**Comment by RRethy** [comment]
fzf has `<c-p>` and `<c-n>` to cycle through previous searches that would be nice in telescope and would sort of allow resuming a previous list.

**Comment by Conni2461** [comment]
> fzf has `<c-p>` and `<c-n>` to cycle through previous searches that would be nice in telescope and would sort of allow resuming a previous list.

See https://github.com/nvim-telescope/telescope.nvim/pull/521 (the day will come when it will be merged)

**Comment by fdschmidt93** [comment]
If anyone subscribed to the issue has time to take #1051 for a test drive (ie require"telescope.builtin".resume() and require"telescope.builtin".pickers()) whether it works as intended for you as well (e.g. preserve prompt, selections, preview properly for pickers(), etc) that would be very much appreciated :)
