### ISSUE TITLE
git checks fail within bare git repo

### ISSUE THREAD

**Issue by polarmutex** [nvim-telescope/telescope.nvim#756]
### Description
I am writing an extension for git-worktree that operate on git bare directories (git clone --bare <repo>). when using the git branches builtin, it reports that I am not in a git repo. the apply checks that looks for the git root directory does not work for git bare directories

the "git rev-parse" command cannot be run in a bare repo, but the "git for-each-ref" command used for git branches does work for bare repos. 

**Expected Behavior**
I should be able to view branches in a git bare repo

**Actual Behavior**
running the telescope.builtin.git.branches in a bare repo prints an error that it is not in a git repo

### Details

<details><summary>Reproduce</summary>

1. git clone --bare <repo>
2. cd repo
3. nvim
4. :Telescope live_grep or git_commits
5. .... bang here is the issue

</details>

<details><summary>Environment</summary>

NVIM v0.5.0-dev+1245-gc9817603c
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

latest telescope

</details>

<details><summary>Configuration</summary>
<p>
n/a

**Comment by ThePrimeagen** [comment]
I think this project is abandoned.  Maybe we should fork it?
