### ISSUE TITLE
We should fire `vim.cmd` if the command is not `edit`

### ISSUE THREAD

**Issue by Conni2461** [nvim-telescope/telescope.nvim#760]
This is bothering me for quite some time. I do a search with `current_buffer_fuzzy_find` (e.g.) and i want to open it in a split `<c-v>` and just doesn't fire the command because i am already in that buffer.

https://github.com/nvim-telescope/telescope.nvim/blob/07d518105cdd6778919181ebf3502cd6f4e9f493/lua/telescope/actions/set.lua#L115-L117

We should add a `and command ~= "edit"` here. (imo). The person who fixes the other issue here should also fix this.

CC @oberblastmeister

**Comment by oberblastmeister** [comment]
I agree, that is a good catch.

**Comment by oberblastmeister** [comment]
Fixed with #760

**Comment by Conni2461** [comment]
thx :)
