### ISSUE TITLE
Release of FZF Native Sorter

### ISSUE THREAD

**Issue by tami5** [nvim-telescope/telescope.nvim#761]
Thanks to @Conni2461 we now have a native fzf sorter.

https://github.com/nvim-telescope/telescope-fzf-native.nvim

**Comment by entropitor** [comment]
Is this supposed to speed up performance or give better search results?

**Comment by clason** [comment]
Why don't you try it? :)

(Both, depending on the point of comparison.)

**Comment by Conni2461** [comment]
I think this was open long enough and tj unpinned it yesterday. So i am closing this issue :)

(BTW i also pinned 3 important repositories at the top of our organization. I think this, fzf-native and frecency are the most important once that we offer but we have still 3 open spots :wink:)

**Comment by fredizzimo** [comment]
Is this actually documented somewhere? I don't see it mentioned in the readme or in the wiki one the page with the list of extensions https://github.com/nvim-telescope/telescope.nvim/wiki/Extensions.

**Comment by tami5** [comment]
shoot we forgot to add it, thanks for the heads up @fredizzimo
