### ISSUE TITLE
Live grep current buffer and fuzzy find in cwd

### ISSUE THREAD

**Issue by JoseConseco** [nvim-telescope/telescope.nvim#762]
I see no place to ask questions so I write here. Is there way to Iive grep current buffer?
I tried this:
`Telescope live_grep{search_dirs=expand("%:p")} `

but it wont work. I just want something like 'current_buffer_fuzzy_find' but not fuzzy.  This way I could get:

![image](https://user-images.githubusercontent.com/13521338/114929604-5070f480-9e34-11eb-934c-db8f7ada4c78.png)

**Comment by JoseConseco** [comment]
Ok I found way to do fuzzy search in pwd (from other issue report):
`require'telescope.builtin'.grep_string{ shorten_path = true, word_match = "-w", only_sort_text = true, search = '' }`
So only current buffer non fuzzy search is left..

**Comment by JoseConseco** [comment]
And I found the non fuzzy way to search current buffer/file:
`lua require'telescope.builtin'.live_grep{ search_dirs={"%:p"} } `
But it sucks. Entering into selected  search result does not move cursor to it, and preview does not work, and the listing contains file path which takes way too much space and is redundant when searching current buffer:


https://user-images.githubusercontent.com/13521338/114933495-03dbe800-9e39-11eb-9c86-f2b2ae178722.mp4

Maybe I'm missing some options?

**Comment by mherna** [comment]
you can try the sorter `telescope-fzf-native.nvim` with the `current_buffer_fuzzy_find` its matching strategy is really good and does move the cursor.

**Comment by tjdevries** [comment]
I'm suprised that `lua require'telescope.builtin'.live_grep{ search_dirs={"%:p"} }` even works at all. You should use `vim.fn.expand("%:p")` or someting similar to give you the search directory you want to use.

You can also pass in a sorter directly to a picker, so you could do non-fuzzy search by passing in one of the non-fuzzy sorter options with ` sorter = ...` (pick which one you want).

**Comment by smackesey** [comment]
Would be really nice to have an option on `current_buffer_fuzzy_find` that controls the kind of matching: fuzzy, literal, or using a vim pattern (i.e. as if you were using `:/`). I can't find an existing sorter in telescope that does vim pattern matching, maybe I missed it.

**Comment by vxio** [comment]
> You can also pass in a sorter directly to a picker, so you could do non-fuzzy search by passing in one of the non-fuzzy sorter options with ` sorter = ...` (pick which one you want).

@tjdevries could you give an example how we can do this with `current_buffer_fuzzy_find`? I don't think that function current allows any overrides like that.

**Comment by Conni2461** [comment]
You can always pass in sorter. 
```
lua require("telescope.builtin").current_buffer_fuzzy_find({ sorter = require('telescope.sorters').get_substr_matcher({})})
```

**Comment by vxio** [comment]
Thanks @Conni2461 ! It's almost working. Something like `Thing` won't match if I type in `Thing`, it'll only match with lowercase input (`thing`). 

I found a few [TODO lines in sorters.lua about this](https://github.com/nvim-telescope/telescope.nvim/blob/e46ef8ffec1637d17dc3f91ade54af3258d5284e/lua/telescope/sorters.lua#L268), so it seems like this still needs to be fixed up? Or are there any options I can pass to fix this?

**Comment by Conni2461** [comment]
We kinda long moved on from this sorter because its lacking things (like you said, also sorter written in lua are not that fast).

So if you are using https://github.com/nvim-telescope/telescope-fzf-native.nvim (make sure to override both sorters or dont set a fzf config, only load it) then you can just do `Telescope current_buffer_fuzzy_find fuzzy=false`.

NOTE: `fuzzy` is a key provided by the `fzf-native` sorter. ITS not builtin, but it can be passed to any picker that uses the `fzf-native` sorter. You can also pass in `case_mode` (also part of that sorter). `Telescope current_buffer_fuzzy_find fuzzy=false case_mode="ignore_case"` or `"respect_case"` or `"smart_case"` (default).

We also already talked about making `fzf-native` part of this repo and replacing the `get_substr_matcher` with the `fzf` one. But there is no roadmap for this plan yet.

**Comment by vxio** [comment]
Awesome, thanks for the info @Conni2461 , that setup works for me.
A minor correction, we'll have to use something like
```
Telescope current_buffer_fuzzy_find fuzzy=false case_mode=ignore_case
```

Using `case_mode="ignore_case"` with quotations will result in an error.
