### ISSUE TITLE
File browser throws segmentation fault

### ISSUE THREAD

**Issue by ed-kemp** [nvim-telescope/telescope.nvim#764]
### Description
Hey there, love this neovim extension however, I've run into a problem with the telescope file browser. It throws a segmentation fault and messes up my terminal, I have to close the tmux pane and open a new one up. 

**Expected Behavior**
The file browser in Telescope should work when the command is run.

**Actual Behavior**
Telescope throws a segmentation fault closing vim in the process and messes up my terminal formatting. 

### Details
I'm using neovim 0.5
OS: MacOs Catalina 10.15.6
Terminal: Alacritty with Tmux

<img width="1307" alt="Screenshot 2021-04-16 at 14 41 57" src="https://user-images.githubusercontent.com/80253838/115034449-6c6fa700-9ec3-11eb-8f81-9a50e4fdd3a0.png">

**Comment by Steadyx** [comment]
This can be deleted, tested on another laptop and it works all good. Apologies.

**Comment by elianiva** [comment]
you probably has the [same issue](https://github.com/nvim-telescope/telescope.nvim/issues/671) that I had a while ago :laughing:

**Comment by Steadyx** [comment]
Yeah, I'm guessing that's my issue! 😆😆
