### ISSUE TITLE
Bottom horizontal split theme

### ISSUE THREAD

**Issue by AnatoleLucet** [nvim-telescope/telescope.nvim#765]
**Is your feature request related to a problem? Please describe.**
This is just a feature I think some people might like (including myself).

**Describe the solution you'd like**
I'd be nice to have a theme where the results are shown in a horizontal split at the bottom of the screen.
For e.g. something like CoC's fuzzy finder:

![image](https://user-images.githubusercontent.com/35486736/115040105-5d8ff100-9ed1-11eb-8b45-1f45f129cf09.png)

I'd personally prefer this layout in a few cases like the `commands` built-in.

**Comment by tjdevries** [comment]
How about something like this:

https://github.com/nvim-telescope/telescope.nvim/pull/771

It's just a rough draft

**Comment by AnatoleLucet** [comment]
It's looking great, thanks!
If the input is on the top, maybe the results list could go from top to bottom / stick to the top of the "results buffer"?
I also think that an horizontal line on the top'd nice to mark the separation between telescope and the background (like the borders of the other themes).

**Comment by elianiva** [comment]
> If the input is on the top, maybe the results list could go from top to bottom / stick to the top of the "results buffer"?

this part is configurable

**Comment by tjdevries** [comment]
OK, you can try this now with:

`lua require('telescope.builtin').find_files(require('telescope.themes').get_ivy())`

Let me know if that is what you're looking for. It still allows for all the normal telescope configurations.

**Comment by tjdevries** [comment]
![image](https://user-images.githubusercontent.com/4466899/118375264-c29d3c00-b58e-11eb-9cfd-0a587b970c92.png)

![image](https://user-images.githubusercontent.com/4466899/118375269-ca5ce080-b58e-11eb-9591-a64f446a16d1.png)

**Comment by smithbm2316** [comment]
@tjdevries thanks for the hard work on this new layout, I'm really looking forward to playing around with it! Is there a particular difference between setting your default `layout_strategy` to `bottom_pane` versus using the `ivy` theme, other than all of your pickers would be using the `bottom_pane` strategy by default? Or is it otherwise the same pretty much?

Hope you had a wonderful vacation! I'm looking forward to popping into a Teej stream again soon 😃

**Comment by tjdevries** [comment]
`layout_strategies` are _only_ for how the windows are laid out.

`themes` are for combining `layout_strategies`, `sorting_strategies`, `borders` and more to make a cohesive unit that is easy for end users to consu.e

So the `ivy` theme, sets the sorting, borders, bordercharsx, etc. to make it look "ivy-ish". While the layout_strategy is ONLY concerned with where to place the windows.

**Comment by AnatoleLucet** [comment]
Thanks. It's looking great!
Though there seems to be some minor issues with Airline:
![image](https://user-images.githubusercontent.com/35486736/118463983-a5887a80-b700-11eb-9825-ba1db590ce78.png)
The status line seems to be blended into the telescope popup.

**Comment by evolify** [comment]
> OK, you can try this now with:
> 
> `lua require('telescope.builtin').find_files(require('telescope.themes').get_ivy())`
> 
> Let me know if that is what you're looking for. It still allows for all the normal telescope configurations.

It's great, but I wonder how to put the prompt in the bottom?

**Comment by Conni2461** [comment]
> It's great, but I wonder how to put the prompt in the bottom?

Currently not supported. PR welcome :)

**Comment by smackesey** [comment]
This is really great, and I'd love to use it as a quickfix replacement.  In order to do that,  one would need to be able to:

1. Switch out of the Telescope window while leaving it open.
2. Have mappings to move to the next/prev selection in the Telescope window and jump to that location while maintaining focus in the current window.

Is there any plan to support functionality like this?

**Comment by zetashift** [comment]
Is there also a way to get the ivy theme to have less height? Using the ivy theme with the `file_browser` makes the window take 50% of my my screen

![image](https://user-images.githubusercontent.com/1857826/126047763-b9e93cfd-6b70-461e-94ed-b063492e1294.png)

**Comment by smackesey** [comment]
@zetashift Not sure if it's the best way, but you can modify various params of the theme like this:

```lua
local theme = require('telescope.themes').get_ivy()
theme['find_command'] = opts.find_command
theme['layout_config']['height'] = 10
require('telescope.builtin').find_files(theme)
```

**Comment by zetashift** [comment]
@smackesey thanks that worked!

**Comment by l-kershaw** [comment]
Closing now as the `bottom_pane` layout now supports the `prompt_position` option, so everything directly related to the original issue is implemented.
