### ISSUE TITLE
Use a tmux popup instead of nvim popup?

### ISSUE THREAD

**Issue by cpakkala** [nvim-telescope/telescope.nvim#766]
The one thing holding me back from migrating to telescope from fzf is the popup buffer.  I usually have nvim running in just one of many panes per tmux window; so the telescope popup just doesn't have enough room unless I zoom into the nvim pane before triggering telescope.  I've been using fzf-tmux and, as it stands, I have a single, consistent popup (which covers all tmux panes so that it has plenty of room) whether I'm in my shell in a tmux pane or in nvim.

So my question is, would it be possible to add an option to telescope to use tmux popups?  

I'm envisioning usage of the nvim client/server API where the tmux popup could actually run some super-simple implementation of an nvim client, so that it could have an actual nvim buffer so that all the highlights, etc. work properly.  If this is possible, then it seems to me it's just a step away from being able to call all of the same telescope functions directly from shell functions, outside of nvim, as well.  That would truely complete my workflow...

**Comment by windwp** [comment]
+1

**Comment by tami5** [comment]
It's feasible, I think someone did os level popup.

**Comment by windwp** [comment]
a latest tmux version have a floating popup

**Comment by tjdevries** [comment]
Hmm, I'm not sure how easy this would be -- what would be in the tmux window? an embedded nvim? an external nvim sending messaging back and forth?

Either way, we wouldn't implement this here. I'm going to close because we won't do any tmux specific items in this repo. if you're interested, you can continue discussing on this issue but I'm going to close.

Thanks for your interest!

**Comment by tjdevries** [comment]
(to be clear, it does seem possible that you could have a remote nvim do some of the basic set up, but it would be very difficult to implement and the API has not stablized enough for me to consider this worthwhile at the time. Perhaps after more API stabilization, it could be investigated)

If someone really wanted to attempt to do this, I could try and guide how the steps would go, but they would need to be really serious :)
