### ISSUE TITLE
git_files duplicate entries during merge/rebase

### ISSUE THREAD

**Issue by YodaEmbedding** [nvim-telescope/telescope.nvim#774]
### Description

Duplicate file entries in `:Telescope git_files` results during rebase/merge conflict resolution.

**Expected Behavior**
No duplicate entries.

**Actual Behavior**
Duplicate entries for `file`:
```
0╭────────── Results ──────────╮
~│                             │
~│  file                       │
~│  file                       │
~│> file                       │
~╰─────────────────────────────╯
~╭───────── Git Files ─────────╮
~│>                    3 / 3   │
~╰─────────────────────────────╯
```

### Details

<details><summary>Reproduce</summary>

```bash
mkdir tmp
cd tmp
git init
echo apple > file
git add file
git commit -m "apple"
echo yummy >> file
git commit -am "yummy"
git branch yummy
git reset --hard HEAD~
echo icky >> file
git commit -am "icky"
git branch icky
git rebase yummy
nvim
```

```vim
:Telescope git_files
```

</details>

<details><summary>Environment</summary>

- nvim --version output: v0.5.0-dev+1229-g91cdc1198
- Operating system: Arch Linux
- Telescope commit: d0cf646

</details>

<details><summary>Configuration</summary>

[Same as default template.]

</details>

**Comment by levouh** [comment]
This is the intended behavior for `git`, and telescope is just displaying the output. It [looks like](https://stackoverflow.com/questions/50568422/why-does-git-ls-files-modified-show-files-multiple-times-in-a-merge-conflict/50569451) at some point there will be a `--deduplicate` option for `git ls-files`, but that would require checking `git` versions, etc.

It becomes a bit more apparent what is actually happening if you `git ls-files -s` which shows that they all have a distinct SHA-1 during the merge.

If you update to version `2.31` of `git` yourself, you can update the picker to do this by something like:

```
local utils = require('telescope.utils')
local make_entry = require('telescope.make_entry')
local pickers = require('telescope.pickers')
local finders = require('telescope.finders')
local conf = require('telescope.config').values

local function my_git_files(opts)
  local show_untracked = utils.get_default(opts.show_untracked, true)
  local deduplicate = utils.get_default(opts.deduplicate, true)
  local recurse_submodules = utils.get_default(opts.recurse_submodules, false)
  if show_untracked and recurse_submodules then
    error("Git does not suppurt both --others and --recurse-submodules")
  end

  -- By creating the entry maker after the cwd options,
  -- we ensure the maker uses the cwd options when being created.
  opts.entry_maker = opts.entry_maker or make_entry.gen_from_file(opts)

  pickers.new(opts, {
    prompt_title = 'Git Files',
    finder = finders.new_oneshot_job(
      vim.tbl_flatten( {
        "git", "ls-files", "--exclude-standard", "--cached",
        show_untracked and "--others" or nil,
        deduplicate and "--deduplicate" or nil
      } ),
      opts
    ),
    previewer = conf.file_previewer(opts),
    sorter = conf.file_sorter(opts),
  }):find()
end
```

**Comment by tjdevries** [comment]
@levouh do you want to add that as an option for git files and the default is false (to keep backwards compat?)

It will be up to users to decide if they want to enable the option.

**Comment by Conni2461** [comment]
You can set your own git command that has deduplicate set.

```lua
lua require("telescope.builtin").git_files{ git_command = { "git", "ls-files", "--exclude-standard", "--cached", "--deduplicate" } }
```
or with telescope.setup
```lua
require("telescope").setup {
  defaults = { 
    -- ...
  },
  pickers = {
    git_files = {
      git_command = { "git", "ls-files", "--exclude-standard", "--cached", "--deduplicate" },
    },
  },
}
```
