### ISSUE TITLE
Is there anyway that I can search files/text in particular directory?

### ISSUE THREAD

**Issue by tomzaku** [nvim-telescope/telescope.nvim#775]
Hi. My project is so big and I don't want to take a lot of time to search for the whole project. So is there any way that I can search in a particular directory?
Or are there any plugins that can I combine with Tree.nvim or NERDTree to our telescope.

Thank you.

**Comment by tomzaku** [comment]
But it is only fast for doing a file search. How about live grep & a word search?

**Comment by tami5** [comment]
Well, I had the same issue and with [vim-rooter](https://github.com/rendon/vim-rooter) I managed to define a pattern (.proj/.root empty files) and vim-rooter made sub directory with that pattern cwd (when I ever I switch manually, or between buffers).

my config for vim rooter
```lua
    vim.g.rooter_patterns = {
      ".git",
      "build/sh",
      "index.md",
      ".proj",
      ".root",
      ".nrepl-port",
      ".exercism" ,
    }
    vim.g.rooter_change_directory_for_non_project_files = "current" -- when non of the above patterns is found
    vim.g.rooter_cd_cmd =  "lcd"
    vim.g.rooter_silent_chdir = true
```

Since this issue isn't something you can solve with telescope. I suggest closing it,  hope the above helps

**Comment by windwp** [comment]
you can try to use nvim-spectre @tomzaku

**Comment by tomzaku** [comment]
@windwp  nvim-spectre is good but I prefer can use searching tool in telescope such as grep live. So I will not install another similar package.

**Comment by windwp** [comment]
it is your choice .Telescope live_grep already support to change directory with cwd and grep args You can customize it. write your own function to get cwd and send to telescope.
 tami5 already say we can't do anything more on that.

btw spectre has a replace function and you can toggle options.

**Comment by tusqasi** [comment]
> @tomzaku You can just set `cwd` option like this to search in the a specific folder:
> 
> ```lua
> function M.installed_plugins()
>   require('telescope.builtin').find_files {
>     winblend = 5,
>     border = true,
>     cwd = vim.fn.stdpath('data') .. '/site/pack/packer/start/'
>   }
> end
> ```

Where do I put this though?
