### ISSUE TITLE
Question: how to ignore patterns in search?

### ISSUE THREAD

**Issue by baldore** [nvim-telescope/telescope.nvim#776]
How to ignore patterns when fuzzy searching? In fzf.vim with Rg you could use something like `!.test` to say that you don't want files with `.test` extension. Also ignore other words. How can this be done with Telescope?

**Comment by nc1337** [comment]
@baldore You can check out https://github.com/nvim-telescope/telescope-fzf-native.nvim for these kinds of searching.

**Comment by baldore** [comment]
Awesome! I'll see how it works.

**Comment by irl-segfault** [comment]
@baldore did you ever figure this out?

**Comment by baldore** [comment]
> @baldore did you ever figure this out?

It didn't work for me and didn't want to spend too much time since Fzf already does it. I'm still using Fzf on my workflow.

**Comment by Conni2461** [comment]
@irl-segfault what issue do you have? You need to install `fzf-native` and build it with make. After that a simple `require('telescope').load_extension('fzf')` after `require('telescope').setup` should make the search syntax available in telescope. You need to uninstall fzy-native of course :)
