### ISSUE TITLE
Session switching on the fly.

### ISSUE THREAD

**Issue by thepenguinthatwants** [nvim-telescope/telescope.nvim#778]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to change sessions I need to shut nvim and reopen the session file.
I've defined all the sessions from a certain directory that I open them from.

**Describe the solution you'd like**
A switcher capable of changing sessions on the fly, and not messing the original sessions settings.

**Describe alternatives you've considered**
Not any that I've gotten thinked of. 
Shutting nvim and reopening tediously.

**Comment by Shatur95** [comment]
You could check my plugin: https://github.com/Shatur95/neovim-session-manager

**Comment by thepenguinthatwants** [comment]
> You could check my plugin: https://github.com/Shatur95/neovim-session-manager

interesting, so its able to disable it to autoload session and opening sessions from predefined locations. I'll try ur plugin. Just need to figure out the syntax to set those up using lua. Thanks

**Comment by Shatur95** [comment]
@thepenguinthatwants, the plugin can be configured from Vimscript as well. But to enable Telescope extension you should call `:lua require('telescope').load_extension('session_manager')`

**Comment by Conni2461** [comment]
Thanks @Shatur this looks cool :)

This issue is a duplication of #749 I am not sure if we should support sessions builtin but i am closing this issue for now you can track #749
