### ISSUE TITLE
Adding custom file finder

### ISSUE THREAD

**Issue by premell** [nvim-telescope/telescope.nvim#779]
A custom file finder where you can specify which ever files you like and get to choose from that list of files. For example one could put their most used config files in the list and easily access them.

**Comment by tami5** [comment]
You can easily do that by creating a new picker and set finder to a list of paths you would like to hard code. Else create a wrapper around find_files and set search_dir to the directories you want find_files to get list of files from

Here a custom picker

```lua 

MyConfifPicker = function(opts)
  pickers.new(opts, {
    prompt_title = 'ConfigPicker',
    finder = finders.new_table {
      results = {
         "path/to/file", 
          "path/to/another_file", ...... 
      },

      entry_maker = opts.entry_maker,
    },
  }):find()
end
```

For more example checkout builtins dir

**Comment by drazde** [comment]
I have the same need. 
I try so this:
```lua
local M = {}
M.search_doc2 = function(opts)
  pickers.new(opts, {
    prompt_title = "< doc >",
    finder = finders.new_table {
      results = {
        "$HOME/doc/",
      },
      entry_maker = opts.entry_maker,
    },
  }):find()
end

return M
```

And call
`:lua require('nv-telescope').search_doc2()`

but doesn't work
![immagine](https://user-images.githubusercontent.com/2643448/115385398-61c15480-a1d8-11eb-95af-23793d21b1e6.png)

**Comment by levouh** [comment]
You are going to run into issues from various missing "imports". Try adding:

```
local finders = require('telescope.finders')
local pickers = require('telescope.pickers')
```

**Comment by drazde** [comment]
ok after i did it. 
Now I don't have error message, but now it show no file

PS: I remove ` entry_maker = opts.entry_maker,`  because it gave me an error 

![immagine](https://user-images.githubusercontent.com/2643448/115417627-0f446000-a1f9-11eb-924f-e345361fe783.png)

> 
> 
> You are going to run into issues from various missing "imports". Try adding:
> 
> ```
> local finders = require('telescope.finders')
> local pickers = require('telescope.pickers')
> ```

**Comment by levouh** [comment]
Well the item you are putting in the table is the string literal `'$HOME/doc/'`, so that is what it is going to show. If you want it to show all files from your home documents directory, then you can do something like:

```
local Path = require('plenary.path')

local function find_home_dir_files()
    local opts = {
        search_dirs = { Path:new(vim.env.HOME, 'doc'):absolute() },
    }
    
    require('telescope.builtin').find_files(opts)
end
```

**Comment by tjdevries** [comment]
I'm going to close this issue since we won't implement this feature since the tools already exist to do what is being asked here. Thanks for the ideas and for using telescope :)
