### ISSUE TITLE
Use proper globbing engine in file_ignore_patterns

### ISSUE THREAD

**Issue by zacmar** [nvim-telescope/telescope.nvim#780]
**Is your feature request related to a problem? Please describe.**
I just tried to set up `file_ignore_patterns` because `:Telescope find_files` tried to preview a very large (~800MB) binary file and kept crashing because of this (so maybe this is another problem to discuss). I expected typical globbing-like functionality, so I tried to put (`.npz` is the binary format)
```lua
require('telescope').setup {
  defaults = {
    file_ignore_patterns = {
        "*.npz",
    },
  }
}
```
To my surprise, this did not work. I then had to look into the source code of `telescope` to find how this dict is processed to find out that it uses `lua`'s native pattern matching library (`string.find`). Then, I had to look up the documentation of `lua` to find out how it does it's things.

**Describe the solution you'd like**
Proper "globbing" support, for lack of a better word. I expected `gitignore`-like syntax to work here.

**Describe alternatives you've considered**
Using it as-is. However, the usage should be properly documented somewhere (the examples are not exactly straight forward for a user that is not familiar with `lua`). I was not able to find any mention of `file_ignore_patterns` anywhere, except the projects README, which does not really explain how it is treated.

**Comment by windwp** [comment]
string.find use a lua regex you can try `npz$`

**Comment by windwp** [comment]
You can make a PR for that docunent.
