### ISSUE TITLE
Displaying Telescope in regular window instead of popup

### ISSUE THREAD

**Issue by psakalo** [nvim-telescope/telescope.nvim#784]
**Is your feature request related to a problem? Please describe.**
I don't really like popup windows for some reasons, but I like how LeaderF for example appears on the bottom of my screen, in a temp window. I didn't really find a simple solution to this, but maybe there is one I'm not aware of? 

**Describe the solution you'd like**
I took a quick look at Picker implementation, and I see that right now popup is kind of hardcoded into it, and there is no abstraction around it at all. So as I understand, the only way to achieve what I want is to rewrite the necessary Picker methods, and create windows myself? I would really like to have some abstraction over it, so it could be easily replaced with regular window

**Describe alternatives you've considered**
I considered using other fuzzy finder plugins, but I really like Telescope extensibility and the variety of pickers that come out of the box. Options I've tried are:
- https://github.com/Yggdroot/LeaderF 
- https://github.com/vijaymarupudi/nvim-fzf

**Additional context**
What I want to achieve is something similar to LeaderF when used without popup enabled. I also like how bufferpicker2 from https://github.com/vijaymarupudi/nvim-fzf-commands#commands looks

**Comment by KarlWithK** [comment]
I would also love this. I really don't like floating windows. I feel like it will be better if there is a bottom window, so I can still get the context of my code and still search for what I need.

**Comment by psakalo** [comment]
For anyone interested, see this https://github.com/nvim-telescope/telescope.nvim/pull/771
