### ISSUE TITLE
Add search history picker

### ISSUE THREAD

**Issue by VVKot** [nvim-telescope/telescope.nvim#788]
**Is your feature request related to a problem? Please describe.**
I want `:History/` from FZF but in Telescope.

**Describe the solution you'd like**
I already have it here: https://github.com/nvim-telescope/telescope.nvim/pull/769

**Describe alternatives you've considered**
Writing it in my dotfiles instead/continuing to use FZF.

**Additional context**
---

**Comment by tjdevries** [comment]
Looks like we merged this 😁
