### ISSUE TITLE
Default timeout for sync actions might be too high

### ISSUE THREAD

**Issue by urandom** [nvim-telescope/telescope.nvim#790]
Some actions have a default timeout of 10 seconds:

https://github.com/nvim-telescope/telescope.nvim/blob/3adeab2bed42597c8495fbe3a2376c746232f2e3/lua/telescope/builtin/lsp.lua#L22

From a user standpoint, this is a bit too high, as these operations are blocking. For example, with golsp, if the user requests the a list of implementations for a non-interface, the whole nvim interface freezes for the duration of the timeout. Perhaps these timeouts should be reduced to 1-2 second by default

**Comment by Conni2461** [comment]
I don't think its that big of an issue. The documentation for the timeout is just missing (CC @smithbm2316)

Also ober wanted to make it non blocking with the `plenary.async` work from him anyway. Idk if he is still wants to work on it. The last time i saw him was a big refactor for `async_lib` so (CC @oberblastmeister)

**Comment by Conni2461** [comment]
We moved to async some time ago. Closing
