### ISSUE TITLE
Telescope buffers should allow ordering by most recent buffer

### ISSUE THREAD

**Issue by gcollura** [nvim-telescope/telescope.nvim#791]
**Is your feature request related to a problem? Please describe.**
Coming from Unite.vim, buffers should allow sorting by most recent instead of buffer number. 

**Describe the solution you'd like**
Either a configuration or a option like `require('telescope.builtin').buffers(most_recent_order=1)`

**Comment by Conni2461** [comment]
We already have a bunch of options for `builtin.buffers`:
- `show_all_buffers`
- `ignore_current_buffer`
- `only_cwd`
- `sort_lastused` <- you want this

There already where a bunch of issue request for this: https://github.com/nvim-telescope/telescope.nvim/issues/415#issuecomment-764622897 and https://github.com/nvim-telescope/telescope.nvim/issues?q=is%3Aissue+sort_lastused

@smithbm2316 apparently these options are missing in your recently merged documentation. And not just for that function :rofl: You can always ask me if you need help tracking down all options ;) you just have to w8 for a response :rofl:

**Comment by smithbm2316** [comment]
I've added it to my list to document, sorry for missing that. When I started that initial PR with documentation I didn't realize picker-specific options could also be found in other places than the pickers themselves. Guess I have more familiarizing to do with the Telescope codebase :rofl:. Thanks for the heads up @Conni2461

**Comment by Conni2461** [comment]
> other places than the pickers themselves

I don't wanna be the know it all, but these are in the builtin implementation :rofl:

**Comment by smithbm2316** [comment]
> I don't wanna be the know it all, but these are in the builtin implementation :rofl: 

Yeah...like I said I didn't realize that when I started working on that documentation. NOW I realize there's options for the pickers in other places lol and have some more work to do there

**Comment by gcollura** [comment]
Thank you @Conni2461 for the reply! I was indeed only basing my question on what I read from the documentation. Sorry I missed past issues, I tried using GitHub search but lead to nothing for me. Feel free to close this issue or hijack it to track its documentation efforts!

**Comment by cseelus** [comment]
```lua
require('telescope.builtin').buffers({ sort_lastused = true, ignore_current_buffer = true })
```

Seems to still not work properly. First in list is the previously used buffer, which is nice. 
After that its still sorted only by buffer number.

<img width="303" alt="Screen Shot 2021-05-30 at 23 08 03" src="https://user-images.githubusercontent.com/3188392/120120168-e4f0a580-c19b-11eb-8bc4-d887ff833b81.png">

**Comment by alvarosevilla95** [comment]
> ```lua
> require('telescope.builtin').buffers({ sort_lastused = true, ignore_current_buffer = true })
> ```
> 
> Seems to still not work properly. First in list is the previously used buffer, which is nice.
> After that its still sorted only by buffer number.
> 
> <img alt="Screen Shot 2021-05-30 at 23 08 03" width="303" src="https://user-images.githubusercontent.com/3188392/120120168-e4f0a580-c19b-11eb-8bc4-d887ff833b81.png">

That's because it seems like its just using the buffer's `last_used` field, which only marks the last buffer. AFAIK (neo)vim doesn't keep track of buffer MRU, so you have to implement this logic yourself using variables and autocommands.

Now, if like me, you're coming from FZF and want the same functionality as the :Buffers command, and you still have fzf.vim around, you already have this logic accessible in the form of `fzf#vim#_buflisted_sorted`. So you can rely on that. This is a patch that injects it to the main `buffers` function (make sure to set `sort_lastused` to false, it mess with the sorting):

```
diff --git a/lua/telescope/builtin/internal.lua b/lua/telescope/builtin/internal.lua
index d53776d..09d7e9f 100644
--- a/lua/telescope/builtin/internal.lua
+++ b/lua/telescope/builtin/internal.lua
@@ -590,7 +590,7 @@ internal.buffers = function(opts)
       return false
     end
     return true
-  end, vim.api.nvim_list_bufs())
+  end, vim.fn['fzf#vim#_buflisted_sorted']())
   if not next(bufnrs) then return end
 
   local buffers = {}
```

**Comment by n1ghtmare** [comment]
This is *the one thing* that I miss from fzf and I'm about to switch back if I can't get it to work. I open buffers and it's a mess, I would love it to be ordered all the way by when the buffer was last used.

@alvarosevilla95 Sorry I'm a bit of a noob when it comes to telescope, how do I install this patch?

**Comment by cseelus** [comment]
Yeah, same here. 
While it was possible to patch it, it’s a bit of a bummer that one has to go to such lengths to get a basic feature like sorted recent buffers to work (and loosing the ability to update in the process).

**Comment by Conni2461** [comment]
Its a real bummer, thats it. Nothing more to say. https://github.com/nvim-telescope/telescope.nvim/pull/1028

`require('telescope.builtin').buffers({ sort_mru = true })`

**Comment by n1ghtmare** [comment]
@Conni2461 Bruh, you're a boss! I hope this gets merged!

**Comment by l-kershaw** [comment]
Hi @n1ghtmare, thought I'd jump in to help, as @Conni2461 is clearly distracted by their black pepper ramen 🤣 

You can either do:
```
lua << EOF
require('telescope').load_extension('fzf')
require('telescope').setup{
    defaults = {
        color_devicons = false,
        layout_config = {
            width = 0.7,
            horizontal = {
                preview_width = 0.6
            }
        }
    },
    pickers = {
        buffers = {
            ignore_current_buffer = true,
            sort_lastused = true,
        },
  },
}
EOF
```
in your config, or call
```
:lua require('telescope.builtin').buffers({ sort_lastused = true, ignore_current_buffer = true })
```
each time you want to use the buffers picker.

The first lets you set and forget, and means that calling `:Telescope buffers` will work as wanted.

**Comment by n1ghtmare** [comment]
@l-kershaw Thank you so much, it works just fine! You guys are the best! Cheers! Also, I must say, black pepper ramen sound amazing.

**Comment by Conni2461** [comment]
I prefer if someone else submits a PR for such a "basic feature" next time.

**Comment by lucax88x** [comment]
For anyone coming in this topic and wondering why sort_lastused doesn't work correctly, please, check sort_mru.

**Comment by johnmathews** [comment]
Thanks for `sort_mru` <3

**Comment by CarsonSlovoka** [comment]
from [doc/telescope.txt](https://github.com/nvim-telescope/telescope.nvim/blob/2eca9ba22002184ac05eddbe47a7fe2d5a384dfc/doc/telescope.txt#L1462-L1467)


```
        {sort_lastused}         (boolean)   Sorts current and last buffer to
                                            the top and selects the lastused
                                            (default: false)
        {sort_mru}              (boolean)   Sorts all buffers after most
                                            recent used. Not just the current
                                            and last one (default: false)
```

so `sort_mru` is better than `sort_lastused` for me
