### ISSUE TITLE
Telescope file browser leaking file descriptors of directories

### ISSUE THREAD

**Issue by bphilly96** [nvim-telescope/telescope.nvim#802]
### Description

Telescopes file browser seems to be leaking file descriptors of directories when the previewer is active. As seen in the screen cast below, whenever a directory is previewed 2 file descriptors are opened but never closed. As I repeatedly preview `.IdentityService/` more and more file descriptors are created, 2 at a time. This doesn't happen when previewing files, only directories. The leaking file descriptors eventually cause neovim to hit the OS limit on the number of open file descriptors for each process.

I had a cursory look at telescope's source code and _think_ the issue might be caused by plenary's scandir, specifically `scan_dir_async()`, however since I'm not really familiar with either codebases I thought I would create an issue here first in case you guys can better see what's causing the problem.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. Monitor the open file descriptors for the neovim process. On MacOS you can do this in activity monitor by double clicking on the process and selecting the open files and ports tab.
3. In neovim type `:lua require'telescope.builtin'.file_browser()`
4. Move around the file system previewing directories and files and observe that 2 file descriptors are leaked for every directory previewed.
</details>

<details><summary>Environment</summary>

- nvim --version output:
NVIM v0.5.0-dev+nightly-166-gecf075eb2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210427-7118-v9yxw1/build/config -I/tmp/neovim-20210427-7118-v9yxw1/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210427-7118-v9yxw1/build/src/nvim/auto -I/tmp/neovim-20210427-7118-v9yxw1/build/include
Compiled by bradyphillips@Bradys-MacBook-Pro.local
Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-ecf075e_2/share/nvim"
Run :checkhealth for more info
- Operating system: MacOS Big Sur 11.3
- Telescope commit: the latest, 1675d37

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```
</details>

### Screen Cast

https://user-images.githubusercontent.com/65504429/116328347-bc524600-a7c0-11eb-84ec-b84e177e914c.mp4

**Comment by Conni2461** [comment]
Finally the first issue in weeks that sounds slightly interesting :rofl: 
I can reproduce it but i am sorry to tell you its not `plenary.scandir`. Its `plenary.filetype.detect` and my implementation of `plenary.path.head` and `plenary.path.tail` that is leaking one descriptor each if it is a directory. I will fix it later

**Comment by Conni2461** [comment]
@bphilly96 wanna try https://github.com/nvim-lua/plenary.nvim/pull/151 (i will merge if you can no longer reproduce with that fix)

**Comment by bphilly96** [comment]
@Conni2461 that fixed it for me. Thanks!

**Comment by Conni2461** [comment]
fixed in https://github.com/nvim-lua/plenary.nvim/commit/d4476cdac636f3e6ae35aa9eb9bda6cbf4e11900
