### ISSUE TITLE
Find files equivalent for SCP?

### ISSUE THREAD

**Issue by thorlucas** [nvim-telescope/telescope.nvim#804]
Is there a viewer that will browse files like netrw? Thanks

**Comment by tami5** [comment]
What do you mean?

**Comment by thorlucas** [comment]
> What do you mean?

My apologies for my lack of specificity. With `netrw`, you can browse files on a network machine using `scp`. I would like to do the same thing with telescope.

**Comment by smithbm2316** [comment]
I'm not particularly familiar with what `scp` is, but the `file_browser` picker may be what you're looking for. If your current working directory for Neovim is set to that location, the `file_browser` picker will give you a list of all the files/folders in that directory and allow you to navigate the filesystem somewhat like `netrw`. You can run it to check this out for yourself by opening Neovim and running the ex-command `:Telescope file_browser` to see if that's what you're looking for.

**Comment by Racle** [comment]
I'll add my 2 cents to this, as this would be nice feature to have at some point. I'm sure there is more important issues/enhancements than this.

> I'm not particularly familiar with what scp

Works ex. like sftp, so you could use `nvim username@server.com/files` (equivalent to `sftp username@server.com:files`) and it will open folder/file `/files` at `server.com` under your `username` directory.
Or use `nvim username@server.com//var/www/index.html` (notice the double `//`)  to edit `index.html` under `/var/www` folder on remote server. 

`:Telescope file_browser` only shows files in directory where you have ran `nvim` while `:Explore` shows files on that remote location.

**Comment by Conni2461** [comment]
We are currently not interested in adding support for remote machines.

https://github.com/chipsenkbeil/distant.nvim approach looks interesting and has at leastsupport for telescope on remote machines in its roadmap.

Closing as won't fix

**Comment by booth-w** [comment]
Is this still not planned?
