### ISSUE TITLE
Different results for default_text

### ISSUE THREAD

**Issue by danymat** [nvim-telescope/telescope.nvim#808]
### Description

When passing default_text to live_grep, I get different results than passing the same text to the picker without default_text.
**Expected Behavior**

I expect to have the same results passing `default_text` and without passing `default_text` and searching for the name
**Actual Behavior**

I get different results:

```
nnoremap <leader>§§ :lua require("telescope.builtin").live_grep({ default_text = "§§" })<CR>
```
Gives me

![Capture d’écran 2021-04-29 à 10 20 41](https://user-images.githubusercontent.com/5306901/116521668-8dc58f80-a8d4-11eb-804b-1d66618e98e4.png)

```
nnoremap <leader>§§ :lua require("telescope.builtin").live_grep()<CR>
```

Gives me

![Capture d’écran 2021-04-29 à 10 21 23](https://user-images.githubusercontent.com/5306901/116521748-a766d700-a8d4-11eb-851d-dcdc9c6fc04a.png)

### Details

<details><summary>Reproduce</summary>

1. Search for a recurring word without `default_text`:

```
:lua require("telescope.builtin").live_grep()
```

2. Search for the same recurring word with `default_text`:
```
:lua require("telescope.builtin").live_grep({ default_text = "§§" })
```
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev+nightly-3-gfbe18d9
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210428-35321-1ktgk9d/build/config -I/tmp/neovim-20210428-35321-1ktgk9d/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210428-35321-1ktgk9d/build/src/nvim/auto -I/tmp/neovim-20210428-35321-1ktgk9d/build/include
Compilé par danielmathiot@MacBook-Pro-de-Daniel.local

Features: +acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "
/usr/local/Cellar/neovim/HEAD-fbe18d9_2/share/nvim"

Run :checkhealth for more info
```
- Operating system: 

![Capture d’écran 2021-04-29 à 10 24 55](https://user-images.githubusercontent.com/5306901/116522155-252ae280-a8d5-11eb-81df-13a05e639e3e.png)

- Telescope commit: 
```
ad30a7b
```
</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment]
`default_text` is currently broken for all pickers (you can't type afterwards or something like that) I have a workaround for that issue in https://github.com/nvim-telescope/telescope.nvim/pull/521 If that is merged we can look at this issue again.

But i think whats happening here is that the `default_text` goes to the sorter and not to rg leading to different results.

**Comment by danymat** [comment]
Thanks @Conni2461 for your response, I will watch this issue and wait for it to be merged!

**Comment by phaazon** [comment]
I reproduce. I tried to implement a small local note workflow by having some keybindings to telescope to grep through a formatted markdown file, and stuff like `default_text = '^# [ ]'` shows way too much / doesn’t seem to apply correctly.

**Comment by danymat** [comment]
> I reproduce. I tried to implement a small local note workflow by having some keybindings to telescope to grep through a formatted markdown file, and stuff like `default_text = '^# [ ]'` shows way too much / doesn’t seem to apply correctly.

Not only that, but it seems to break the input field

**Comment by Conni2461** [comment]
As i said before the fix is in #521 Its no longer reproducible with that PR. [Current Status of PR](https://github.com/nvim-telescope/telescope.nvim/pull/521#issuecomment-864250537). You can use that branch without any issues and being affected of the new changes. Its rebased, and i don't have any time this week to work on telescope and with tj on vaccation, i don't think there will be any updates to telescope till then. So you should stay up to date.

When tj is back i plan to finish that PR and sort out the remaining issue

**Comment by Conni2461** [comment]
This issue should now be fixed. Thanks for your patience :)

Closing for now. If i am wrong feel free to reopen :)

**Comment by danymat** [comment]
Works like a charm, thanks @Conni2461 🙇🏻
