### ISSUE TITLE
Option to hide line preview in results list (lsp symbols)

### ISSUE THREAD

**Issue by karlc1** [nvim-telescope/telescope.nvim#811]
**Is your feature request related to a problem? Please describe.**

When I use Telescope to list document symbols, many of the actual names of the symbols in the results gets truncated to the point of being useless. This is especially common in Golang code where the struct name is part of the symbol name, so they can be a bit long. Here is an example: 

(deadlineExceededError).… method   func (deadlineExceededError) Temporary() bool { return true }  
(deadlineExceededError).… method   func (deadlineExceededError) Timeout() bool   { return true }    
(deadlineExceededError).… method   func (deadlineExceededError) Error() string   { return "context deadline exceeded" }  

These are 3 different functions with different names, but the names themselves are not getting printed out. I also don't really care about the right most part of the output, the line preview where the symbols occur. 

**Describe the solution you'd like**
I would like an option to hide the line preview and give more space to the symbol name and type, so that it looks like this:

(deadlineExceededError).Temorary        method  
(deadlineExceededError).TImeout          method  
(deadlineExceededError).Error               method  

**Describe alternatives you've considered**
I have tried giving the options `{show_line = true}` since it looks in the code that this might do the trick, but it does nothing for me. I'm not familiar with Lua so  I might be missing something here. What I have tried is showing the document symbols by calling this: 

`:lua require'telescope.builtin'.lsp_document_symbols({previewer = false, show_line = false})`

**Additional context**

An exemple of how cluttered it can look:

![clutter](https://user-images.githubusercontent.com/12910613/116721725-f2204600-a9dd-11eb-955c-c86fc03f8c19.png)

**Comment by tami5** [comment]
hmm maybe try dropdown theme. Preview:
 
![image](https://user-images.githubusercontent.com/65782666/116803643-54825f00-ab22-11eb-9766-668ab8730673.png)

![image](https://user-images.githubusercontent.com/65782666/116803656-649a3e80-ab22-11eb-8c66-2726fe7518a4.png)

My config

```lua
local dropdown = themes.get_dropdown({
  previewer = false,
  prompt_title = "",
  results_height = 16,
  width = 0.6,
  borderchars = {
    {"─", "│", "─", "│", "╭", "╮", "╯", "╰"},
    prompt = {"─", "│", " ", "│", "╭", "╮", "│", "│"},
    results = {"─", "│", "─", "│", "├", "┤", "╯", "╰"},
    preview = {"─", "│", "─", "│", "╭", "╮", "╯", "╰"}
  },
  winblend = 10
})

```

**Comment by tom-anders** [comment]
There's also my Pull Request #812 that let's you customize the widths of the entries

**Comment by karlc1** [comment]
@tami5 Many of my symbols still don't fit when using drop down theme, and a lot of the horizontal space is still taken up by the content prview. I think that for me, the ideal config would to use drop down, but with the content preview removed and the symbol type right aligned. 

@tom-anders Yes, that actually does look like it would help me to fit the symbol names in the row, I will try it out.

**Comment by karlc1** [comment]
The options added in #812 allows me to solve this issue by just shifting the symbol type way to the right with symbol_width=40 and then hiding the line preview completely with symbol_type_width=100, so im closing this. Thanks!
