### ISSUE TITLE
How can I open several files?

### ISSUE THREAD

**Issue by jjalonsoc** [nvim-telescope/telescope.nvim#814]
I want to use telescope to search for some text or file names, and then open several of the options.

I was trying to do this with the following config:

```
["<TAB>"] = actions.add_selection + actions.move_selection_next,
["<S-TAB>"] = actions.remove_selection + actions.move_selection_previous,
 ["<CR>"] = actions.select_default + actions.center
```
But somehow <CR> is just opening the file under the cursor. Is there an actions.select_selection or something like that that I am missing?

**Comment by smithbm2316** [comment]
Unfortunately at the moment Telescope is not able to select multiple files in a picker and then open all of them. This is being worked on by TJ at #807 right now, so keep your eyes peeled for that PR to be merged!

**Comment by n0ks** [comment]
You can open multiple files using 
:Files and then <TAB> select then.

**Comment by smithbm2316** [comment]
> You can open multiple files using
> `:Files`
> TAB to select and then just press Enter to open all at once

Are you using `fzf.vim` @n0ks? Telescope doesn't have a `:Files` command, it does have `:Telescope find_files`. `:Files` IIRC is a `fzf.vim` command

**Comment by n0ks** [comment]
> > You can open multiple files using
> > `:Files`
> > TAB to select and then just press Enter to open all at once
> 
> Are you using `fzf.vim` @n0ks? Telescope doesn't have a `:Files` command, it does have `:Telescope find_files`. `:Files` IIRC is a `fzf.vim` command

Sorry, i think i've might mixed up the commands 😅 
ur right.

**Comment by jjalonsoc** [comment]
Thanks for your answer, I still think that this will be most powerful when mixed with `Telescope live_grep` and `Telescope grep_string`. @smithbm2316 The PR you mentioned is now closed, do you know what can I do?

**Comment by smithbm2316** [comment]
> Thanks for your answer, I still think that this will be most powerful when mixed with `Telescope live_grep` and `Telescope grep_string`. @smithbm2316 The PR you mentioned is now closed, do you know what can I do?
> 
> 

#807 is still open when I just checked now...are you looking at the wrong PR perhaps?

**Comment by jjalonsoc** [comment]
@smithbm2316 you are right, ;)

**Comment by Integralist** [comment]
Looks like that PR might have long gone stale. 

Does anyone know if there's a workaround for selecting multiple files in telescope yet as this is quite a key missing feature compared to FZF. 

Thanks.

**Comment by ryanburda** [comment]
I have these two mappings in my setup as a workaround.
- Ctrl-o will open the file and immediately resume the previous picker.
- Ctrl-q will add all of the files to the quickfix list. This can then be chained together with a function that opens all files in the quickfix list.
```
defaults = {
  mappings = {
    i = {
      ["<C-o>"] = function(prompt_bufnr) require("telescope.actions").select_default(prompt_bufnr) require("telescope.builtin").resume() end,
      ["<C-q>"] = actions.send_to_qflist,
    },
  },
}
```

Function to open all files in quickfix list.
```
vim.cmd([[
function!   QuickFixOpenAll()
    if empty(getqflist())
        return
    endif
    let s:prev_val = ""
    for d in getqflist()
        let s:curr_val = bufname(d.bufnr)
        if (s:curr_val != s:prev_val)
            exec "edit " . s:curr_val
        endif
        let s:prev_val = s:curr_val
    endfor
endfunction
]])

vim.api.nvim_set_keymap('n', '<leader>ka' , ':call QuickFixOpenAll()<CR>', { noremap=true, silent=false })
```

**Comment by eriteric** [comment]
Question out of curiosity: What are the multiple selections for, then? If not for opening multiple files.

**Comment by syukronarie** [comment]
> I have these two mappings in my setup as a workaround.
> 
> * Ctrl-o will open the file and immediately resume the previous picker.
> * Ctrl-q will add all of the files to the quickfix list. This can then be chained together with a function that opens all files in the quickfix list.
> 
> ```
> defaults = {
>   mappings = {
>     i = {
>       ["<C-o>"] = function(prompt_bufnr) require("telescope.actions").select_default(prompt_bufnr) require("telescope.builtin").resume() end,
>       ["<C-q>"] = actions.send_to_qflist,
>     },
>   },
> }
> ```
> 
> Function to open all files in quickfix list.
> 
> ```
> vim.cmd([[
> function!   QuickFixOpenAll()
>     if empty(getqflist())
>         return
>     endif
>     let s:prev_val = ""
>     for d in getqflist()
>         let s:curr_val = bufname(d.bufnr)
>         if (s:curr_val != s:prev_val)
>             exec "edit " . s:curr_val
>         endif
>         let s:prev_val = s:curr_val
>     endfor
> endfunction
> ]])
> 
> vim.api.nvim_set_keymap('n', '<leader>ka' , ':call QuickFixOpenAll()<CR>', { noremap=true, silent=false })
> ```

Hi, I am interested in this approach, however, I am still looking for a way to delete records in quicklist, anyone if now this solution please kindly help it. thanks

**Comment by bkerz** [comment]
> I have these two mappings in my setup as a workaround.
> 
> * Ctrl-o will open the file and immediately resume the previous picker.
> * Ctrl-q will add all of the files to the quickfix list. This can then be chained together with a function that opens all files in the quickfix list.
> 
> ```
> defaults = {
>   mappings = {
>     i = {
>       ["<C-o>"] = function(prompt_bufnr) require("telescope.actions").select_default(prompt_bufnr) require("telescope.builtin").resume() end,
>       ["<C-q>"] = actions.send_to_qflist,
>     },
>   },
> }
> ```
> 
> Function to open all files in quickfix list.
> 
> ```
> vim.cmd([[
> function!   QuickFixOpenAll()
>     if empty(getqflist())
>         return
>     endif
>     let s:prev_val = ""
>     for d in getqflist()
>         let s:curr_val = bufname(d.bufnr)
>         if (s:curr_val != s:prev_val)
>             exec "edit " . s:curr_val
>         endif
>         let s:prev_val = s:curr_val
>     endfor
> endfunction
> ]])
> 
> vim.api.nvim_set_keymap('n', '<leader>ka' , ':call QuickFixOpenAll()<CR>', { noremap=true, silent=false })
> ```

Thank you so much :)

**Comment by younger-1** [comment]
> Question out of curiosity: What are the multiple selections for, then? If not for opening multiple files.

The capability of multiple selections provided by telescope is designed for quickfix, aka the only direct usage of it, as most of us would do, is to send items to quickfix list.

**Comment by yannickperrenet** [comment]
The workaround that works for me:
```lua
defaults = {
  mappings = {
    i = {
        ["<C-o>"] = function(p_bufnr) require("telescope.actions").send_selected_to_qflist(p_bufnr) vim.cmd.cfdo("edit") end,
    },
  },
}
```
It is similar to the approach of @ryanburda, except that you can select the files you want to open with the default `<TAB>` and open only those files in hidden buffers using just `<C-o>`.

**Comment by Drew-Daniels** [comment]
For anyone reading this (checks watch) at 10/26/2023 or after, you can do this with `<C-q>` by default

**Comment by Madoshakalaka** [comment]
For anyone reading this (checks watch) at Feb/07/2024 or after, by defauld <C-Q> sends everything to the list. <M-q> sends the selected to the list.

**Comment by ooloth** [comment]
If you're here and haven't found a good workaround, [this one](https://github.com/nvim-telescope/telescope.nvim/issues/1048#issuecomment-1679797700) from #1048 lets you use the same key (`<CR>`) to open one _or_ many selected files.

(No need to remember a secondary key like `<C-o>` or `<M-q>` for opening multiple selections, and no need to spend time in the quickfix list if all you want is to open all of your selections.)

**Comment by sasugo** [comment]
I'm glad this works but, where is this in the documentation?
