### ISSUE TITLE
Custom rg command

### ISSUE THREAD

**Issue by kuator** [nvim-telescope/telescope.nvim#816]
I want find_files to use specific command  "rg --files --ignore-file ~/.config/.ignore".
I tried the example from readme, but it doesn't pick up the ignore file. `Telescope find_files find_command=rg,--files,--ignore-file,~/.config/.ignore prompt_prefix=🔍`

**Comment by kuator** [comment]
@tjdevries I summon thee

**Comment by Conni2461** [comment]
I think you just need to expand `~/.config/.ignore` because usually the shell does do that, but there is no shell in the whole "pipeline".

So something like this should (hopefully) work:
```lua
require("telescope.builtin").find_files{ 
  prompt_prefix = "🔍",
  find_command = { "rg", "--files", "--ignore-file", vim.fn.expand("~/.config/.ignore") } 
}
```

**Comment by kuator** [comment]
One more question: I have different find_files mappings in my config. Does it mean I should specify find_command for every mapping I make? Is it possible to specify a default config which will be used in every subsequent mappings?

**Comment by Conni2461** [comment]
Feature request: https://github.com/nvim-telescope/telescope.nvim/issues/582

Right now you can make a own `custom_find_files` function in a lua file that has the `default_opts` and than have a function parameter `additional_opts` (or similar) and extend `default_opts` with `additional_opts`.

Then you can just call 
```
:lua require("kuator/telefunc.lua").custom_find_files { cwd = a }
:lua require("kuator/telefunc.lua").custom_find_files { cwd = b }
```

and your custom opts like `prompt_prefix` still applies. Does this makes sense for you?

**Comment by kuator** [comment]
Oooh, I see, thank you for the help!
