### ISSUE TITLE
Telescope broken on neovim HEAD

### ISSUE THREAD

**Issue by clason** [nvim-telescope/telescope.nvim#821]
Neovim just merged https://github.com/neovim/neovim/pull/13664, which breaks Telescope: Opening any finder (e.g., just `:Telescope`) yields
```
E5108: Error executing lua .../packer/start/plenary.nvim/lua/plenary/window/border.lua:138: Vim(autocmd):E680: <buffer=6>: invalid buffer number
```

I suspect this is due to https://github.com/neovim/neovim/pull/13664/commits/97abf8ee63994c19c2119e34bc7a7aa66457a7f2, which changed how autocommands are triggered in popups.

**Comment by clason** [comment]
That doesn't fix it, unfortunately; then I get
```
E5108: Error executing lua ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:343: Invalid window id:
 1006
```

**Comment by Conni2461** [comment]
Thanks for testing :) I am pretty sure that got us further. I will try to track it down tomorrow morning. I wanted to do some telescope work this weekend anyway, so its at least a little bit maintained while tj is on vacation.

**Comment by clason** [comment]
In the meantime, for those coming here:
```
git checkout 4be0e92db01a502863ac4bb26dd0fee16d833145
make
make install
```
"unbreaks" telescope.

**Comment by Conni2461** [comment]
https://github.com/nvim-lua/plenary.nvim/pull/155 and https://github.com/nvim-lua/popup.nvim/pull/13 to fix this issue.

@clason I can merge anything into plenary but i don't have write rights for popup. Is there any chance that you can merge things into popup? Otherwise i will write tj in private

**Comment by tjdevries** [comment]
🎶 🎶 🎶 
Listen, baby, ain't no mountain high
Ain't no valley low, ain't no river wide enough, baby
If you need me, call me, no matter where you are
No matter how far, don't worry, baby
Just call my name, I'll be there in a hurry
You don't have to worry 
🎶 🎶 🎶

**Comment by clason** [comment]
aaaand it's fixed :)

**Comment by raka26** [comment]
Thanks for your hard work!
