### ISSUE TITLE
Telescope doesn't clean up properly on <c-c>

### ISSUE THREAD

**Issue by mhinz** [nvim-telescope/telescope.nvim#822]
### Description

It seems that the Telescope buffer isn't cleaned up properly on `<c-c>` in a buffer with `nobuflisted` and `hidden` set. No preview window must be shown, since it isn't using `TelescopeNormal`.

**Expected Behaviour**

Telescope should clean up properly on `<c-c>` and bring you back to the same buffer where `:Telescope` was executed from.

**Actual Behavior**

You end up up in a different buffer (8 instead of 1 following the test.vim) which obviously belonged to Telescope, since the background is still green (because `'winhl'`). And the original buffer (1) was deleted.

### Details

<details><summary>Reproduce</summary>

0. I did not find a way to disable the preview in the docs, so make sure to use a small enough window...
1. nvim -nu test.vim
2. `:set nobuflisted`
3. `:Telescope`
4. `<c-c>`
</details>

<details><summary>Environment</summary>

- nvim --version output: `NVIM v0.5.0-dev+1307-g17434b88b`
- Operating system: `macOS 11.3`
- Telescope commit: `88f7b27`

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close

highlight TelescopeNormal guibg=green

" using Telescope default settings otherwise
```

**Comment by Conni2461** [comment]
Can reproduce. (thanks for the better reproduce) Probably related to #62 #207 #377 #678

to disable previewer: `Telescope find_files previewer=false`, should work for all pickers. (not for just `:Telescope`, because dispatcher does not recognize it as option)

**Comment by Conni2461** [comment]
Hopefully this works. I can no longer reproduce this issue.

Big thanks to @l-kershaw
