### ISSUE TITLE
Change default of git_files to show_untracked=false

### ISSUE THREAD

**Issue by kaddkaka** [nvim-telescope/telescope.nvim#826]
Problem: `git_files` has an unexpected default of listing untracked files.
Suggestion: make the default of `git_files` *not* list untracked files.

`:Telescope git_files` currently lists all files in a git repo folder; the default is to also list untracked files. This is not the same default as git and other tools have. For example

 - `git ls-files` lists all tracked files in the repo and a flag is needed to list untracked files as well.
 - `fzf.vim`'s `:GFiles` lists tracked files (has `:GFiles?` to list untracked files as well)

It is possible to list tracked files with `lua require"telescope.builtin".git_files({ show_untracked = false }) ` but I think that the default behavior is unexpected. The first time I tried telescope I thought that `git_files` was broken because it acted just like `find_files`.

Related: There is already `git_status` which can be used to find new untracked files in the repo.

**Comment by Conni2461** [comment]
#842 was merged into dev branch. Please read https://github.com/nvim-telescope/telescope.nvim/issues/1938 if you want to know when it hits master.
