### ISSUE TITLE
grep_string not searching anything

### ISSUE THREAD

**Issue by rakula4** [nvim-telescope/telescope.nvim#833]
### Description
I have this in my `init.vim`
`nnoremap <leader>ps :lua require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ") })<CR>`

If I use this remap, it opens up the "Grep For > " properly. However, if I search (for instance "lua"), it doesn't find anything

**Expected Behavior**
The `ps` command should find all the searched instances

**Actual Behavior**
The actual behavior is that it doesn't find anything. At the area where I can type my vim commands, I get a red message as follows:
"[telescope] ^I...cope.nvim/lua/telescope/finders/async_oneshot_finder.lua:39: in function <...cope.nvim/lea/telescope/finders/async_oneshot_finder.lua:28>"

### Details

<details><summary>Reproduce</summary>

1. Add `nnoremap <leader>ps :lua require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ") })<CR>` to init.vim
2. Save (:w), :so %
3. Try leader ps command
4. Search for something (something thats in init.vim such as "lua")
</details>

<details><summary>Environment</summary>
- nvim --version output: NVIM v0.5.0-dev+f8173df
- Operating system: MacOS
- Telescope commit: (I am not sure how to find this)

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2


call plug#begin('/vim/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

lua require('telescope').setup({defaults = {file_sorter = require('telescope.sorters').get_fzy_sorter}})
nnoremap <leader>ps :lua require('telescope.builtin').grep_string({ search = vim.fn.input("Grep For > ") })<CR>
nnoremap <C-p> :lua require('telescope.builtin').git_files()<CR>
```

**Comment by smithbm2316** [comment]
I believe that you'll want to change `search` to `prompt_prefix`. The `search` key tells `grep_string` the exact string that you want to  search for, so you'd be searching for "Grep For String >" in this case.

**Comment by Conni2461** [comment]
[ripgrep](https://github.com/BurntSushi/ripgrep) binary needs to be installed.

`:message` should show you the full error message and should show that `rg need to be installed`

**Comment by shashinvision** [comment]
> Install ripgrep worked. I just did `brew install ripgrep` and it's working fine now.

This fix the problem for me, thanks

**Comment by storrence88** [comment]
> Install ripgrep worked. I just did `brew install ripgrep` and it's working fine now.

This worked for me as well. Thanks!

**Comment by RyandenOtter** [comment]
> Install ripgrep worked. I just did `brew install ripgrep` and it's working fine now.

Thanks! That worked for me too.

**Comment by ChrisW-priv** [comment]
had the same issue and the solution worked  for me too. Can there be an option added to make it install it for the user? by default it is not included in many distros.

**Comment by Tiriyon** [comment]
On wsl2 - ubuntu 22.04. Also `sudo apt install ripgrep` solved the issue aswell.

Keymap:
```
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ")})
end)
```

(Following the primeagen video on nvim configuration [video link](https://www.youtube.com/watch?v=w7i4amO_zaE&t=629s) )

**Comment by Murat-Sahin1** [comment]
Same thing for the windows as well, `choco install ripgrep` solves the issue.

**Comment by TheDinner22** [comment]
same issue same solution on ubuntu 22.04 just called `sudo apt install ripgrep -y`

**Comment by daUnknownCoder** [comment]
on arch :
[yay/paru/sudo pacman] -S ripgrep worked

**Comment by ninbura** [comment]
Works on Windows as well with `winget install burntsushi.ripgrep.gnu`

**Comment by youssef-snoussi** [comment]
@cesarlpb if you're talking about the primeagen it is stated in the github repo

**Comment by Rohan-Muslekar** [comment]
> On wsl2 - ubuntu 22.04. Also `sudo apt install ripgrep` solved the issue aswell.
> 
> Keymap:
> 
> ```
> vim.keymap.set('n', '<leader>ps', function()
> 	builtin.grep_string({ search = vim.fn.input("Grep > ")})
> end)
> ```
> 
> (Following the primeagen video on nvim configuration [video link](https://www.youtube.com/watch?v=w7i4amO_zaE&t=629s) )

Just now faced this issue, searched, got this and now its fixed. Thanks!

**Comment by bananaback** [comment]
> > On wsl2 - ubuntu 22.04. Also `sudo apt install ripgrep` solved the issue aswell.
> > Keymap:
> > ```
> > vim.keymap.set('n', '<leader>ps', function()
> > 	builtin.grep_string({ search = vim.fn.input("Grep > ")})
> > end)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (Following the primeagen video on nvim configuration [video link](https://www.youtube.com/watch?v=w7i4amO_zaE&t=629s) )
> 
> Just now faced this issue. Searched, got this and now its fixed. Thanks!

I'm on Ubuntu 23.10, currently following the Primeagen video on Neovim configuration. I encountered this issue, searched for a solution, found this fix, and now everything works. Thanks!

**Comment by MarkMutai5** [comment]
> Install ripgrep worked. I just did `brew install ripgrep` and it's working fine now.

Worked perfectly for me too. Thanks

**Comment by andrewhessler** [comment]
Doesn't work with ripgrep@14.1.0, but does with ripgrep@13.0.0

**Comment by jamestrew** [comment]
I'm not sure if this is the solution but have you tried v14.1.1 https://github.com/BurntSushi/ripgrep/releases/tag/14.1.1

It's working for me and I highly doubt this is a telescope issue. Check if ripgrep on its own is working first.

**Comment by harshad2112** [comment]
> [ripgrep](https://github.com/BurntSushi/ripgrep) binary needs to be installed.

Thanks worked for me as well :)

**Comment by jayshozie** [comment]
> [ripgrep](https://github.com/BurntSushi/ripgrep) binary needs to be installed.
> 
> `:message` should show you the full error message and should show that `rg need to be installed`

This fixed it. Still works, thanks.
