### ISSUE TITLE
Scroll file list horizontally

### ISSUE THREAD

**Issue by roginfarrer** [nvim-telescope/telescope.nvim#834]
**Is your feature request related to a problem? Please describe.**
I work in a codebase that includes very long paths and filenames intermingled with short ones. I frequently encounter scenarios where the file list is to the right to show the filename, and this can mean that I cannot see the shorter filenames at all. This makes it very difficult to navigate the file list.

**Describe the solution you'd like**
Introduce key mappings to scroll the file list horizontally (left or right)

<img width="1176" alt="CleanShot 2021-05-10 at 10 42 40@2x" src="https://user-images.githubusercontent.com/9063669/117677460-7a3fe180-b17c-11eb-9213-353a64a6de0a.png">

**Comment by asymmetric** [comment]
Alternatively, there could be some kind of elision (`...`) and/or shortening (`~/D/f/bar.txt`) for paths beyond a certain length

**Comment by caojoshua** [comment]
@asymmetric we can shorten paths beyond certain length after https://github.com/nvim-telescope/telescope.nvim/pull/886 is merged

**Comment by asymmetric** [comment]
@caojoshua it’s been merged, FYI

**Comment by ZyriabDsgn** [comment]
Super necro-opening of this issue but is there a way to actually scroll horizontally?
I work on a gigantic monorepo and the various layers often share the filename and sometimes a part of the path is similar but the root, I'd like to keep the entire path displayed while being able to check the filename that's being partially hidden as you can see on this screenshot

![image](https://github.com/nvim-telescope/telescope.nvim/assets/2111910/fbaac208-35c5-4aad-a6dd-6d325720213c)

**Comment by jamestrew** [comment]
@ZyriabDsgn there's a `results_scrolling_left` (and right) action.

You can also toggle_preview as well.
