### ISSUE TITLE
Filter for LSP document symbols based on symbol type

### ISSUE THREAD

**Issue by marconetto** [nvim-telescope/telescope.nvim#837]
I would like to select specific symbol types to see in "lsp_document_symbols". For instance when I use lsp_document_symbols I'm usually most interested in the symbol type "method" (so I can navigate through the code faster)

One possible solution would be to allow an initial input when calling lsp_document_symbols. Example:
:Telescope lsp_document_symbols prompt_input="method "

Perhaps there is already something to allow that.

BTW, telescope is really cool!

**Comment by Conni2461** [comment]
We have a prefiltering. `:method:` should show only methods. There is also autocomplete with `<C-l>` in insert mode

**Comment by Conni2461** [comment]
(needs to be documented @smithbm2316)

Should work for `workspace_`/`document_` + `symbols`/`diagnostics`

**Comment by tami5** [comment]
Hmm buggy though
![CleanShot 2021-05-12 at 14 40 36](https://user-images.githubusercontent.com/65782666/117969599-4c9b9980-b330-11eb-8335-8369cf4525f8.gif)

**Comment by Conni2461** [comment]
@tami5 broken with fzf: https://github.com/nvim-telescope/telescope-fzf-native.nvim/issues/12 should work with other sorters

**Comment by tami5** [comment]
😆 😆 you are supper fast conni.

**Comment by Conni2461** [comment]
This is now documented. The bug in fzf-native fixed. If #521 is merged you will also be able to do `Telescope lsp_document_symbols default_text=:method:`

I think this is resolved. Closing. If something is missing feel free to reopen

**Comment by tristone13th** [comment]
> 

any idea if I want to filter out the function and the class both?

**Comment by Conni2461** [comment]
`:help builtin.lsp_document_symbols` you can define a table of symbols to filter on. `lua require("telescope.builtin").lsp_document_symbols({ symbols = { "class", "field" } })`. Or take a look at https://github.com/nvim-telescope/telescope-fzf-native.nvim it has support for or. So you can search for `class | field` or so

**Comment by tristone13th** [comment]
> `:help builtin.lsp_document_symbols` you can define a table of symbols to filter on. `lua require("telescope.builtin").lsp_document_symbols({ symbols = { "class", "field" } })`. Or take a look at [nvim-telescope/telescope-fzf-native.nvim](https://github.com/nvim-telescope/telescope-fzf-native.nvim) it has support for or. So you can search for `class | field` or so

Many thanks, it worked. BTW, how to know the name of all the symbols...

**Comment by Conni2461** [comment]
In the specification: https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol

Scroll a little bit down and you find `SymbolKind`

**Comment by tristone13th** [comment]
> In the specification: [microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol)
> 
> Scroll a little bit down and you find `SymbolKind`

Thanks, very nice of you!
