### ISSUE TITLE
How do I unmap a key? 

### ISSUE THREAD

**Issue by qazip** [nvim-telescope/telescope.nvim#841]
I have this bit in my .lua:

```
require('telescope').setup{
  defaults = {
    mappings = {
      i = {
        -- To disable a keymap, put [map] = false
        -- So, to not map "<C-n>", just put
        ["<c-x>"] = false,
      },
  }
}
```

C-x is still mapped though. What am I doing wrong?

**Comment by qazip** [comment]
Nevermind. I was not loading  the file. What a moron.

**Comment by smithbm2316** [comment]
That should be the way to disable a keymap, by setting it to false. Can you please test this issue with the minimal configuration that we provide in the issue template for a bug, as well as send us all of the information listed there? It's challenging for us to debug without all of that information.
