### ISSUE TITLE
How do I debug a non-working setup?

### ISSUE THREAD

**Issue by thornomad** [nvim-telescope/telescope.nvim#843]
### Description
I was trying to utilize this new feature that was implemented via PR #739.  

 I am having an issue where this feature works for me when I open `nvim` in certain directories on my system but not when I open `nvim` in other directories.  I can't figure out what is causing the conflict based on the directory and in what context.

When it  _doesn't work_ the command simply fails to run—there is no error message or output—that is: nothing happens (see video below).

I've looked around through the docs here but I can't figure out: **How do I debug a non-functioning command?** Is there a way to view a debug console or log or something that might give me a hint?  Just trying to figure out what the missing piece to my puzzle is and am not much of a neovim pro so not sure how I start to pull apart this problem.  Thanks in advance.

Here is a video:

![out2](https://user-images.githubusercontent.com/124717/114176414-19b54e80-9909-11eb-9310-a20660f24bf6.gif)

Here is [my original description of the problem](https://github.com/nvim-telescope/telescope.nvim/pull/739#issuecomment-816631404) I am seeing.  NOTE: I have tested it again with `nvim -NU test.vim test.txt` with the same results.

Thanks for any guidance.

**Comment by smithbm2316** [comment]
Hey @thornomad! This is...an odd issue. Certainly not helpful when there's not any error output :slightly_frowning_face:. I'm unfortunately no Neovim expert myself either, and even after taking a bit of a peek at the source code for this picker I can't say I'm any closer to really understanding what the issue might be. Does this only happen when you use the `only_cwd` option, or just anytime that you run the `builtin.buffers` picker? You might try reaching out to the Telescope Gitter community to see if someone might be able to offer some advice of how to go about debugging something like this. I'm sorry I don't have any more useful suggestions at the moment, usually when I come across an issue in Telescope there's an error and I just start tossing `print` functions in the source code and see what's going on :laughing:.

**Comment by thornomad** [comment]
Hi @smithbm2316 — thanks for chiming in!

> Does this only happen when you use the `only_cwd` option, or just anytime that you run the `builtin.buffers` picker?

Yes, the regular `builtin.buffers` picker works well for me.  It's a little head scratcher and I'm sure it has something to do with my particular setup: I just can't figure out why one directory has one behavior and another a different behavior!  Grr.  I will try the Gitter community.  

> It might also be worth trying (if you haven't already) to see if the problem persists with multiple buffers open, with some in the cwd and some in different directories.

Thanks for that suggestion.  I did try opening some varied buffers (including in my home directory) but no luck:  😢 Let's see if I can figure out how to get any meaningful debug via Gitter.

**Comment by thornomad** [comment]
Thank you for getting me on the right track!  Sorted I think with PR #849
