### ISSUE TITLE
`current_buffer_fuzzy_find` gives E5108 in a vue file with Treesitter support

### ISSUE THREAD

**Issue by h0adp0re** [nvim-telescope/telescope.nvim#844]
### Description

With Treesitter for vue enabled, trying to run `:Telescope current_buffer_fuzzy_find` in a vue file gives me an error:
```
E5108: Error executing lua ...im/bundle/telescope.nvim/lua/telescope/builtin/files.lua:413: attempt to get length of a nil value
```

_Note: It used to work fine a week ago._

**Expected Behavior**

Well, the picker should open.

**Actual Behavior**

I get an error, as described above.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. run `:Telescope current_buffer_fuzzy_find` in a vue file
3. `E5108: Error executing lua ...im/bundle/telescope.nvim/lua/telescope/builtin/files.lua:413: attempt to get length of a nil value`
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+nightly-55-g61aefaf29
- Operating system: macOS 11.3
- Telescope commit: 22a78a4

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF
require('nvim-treesitter.configs').setup{
  ensure_installed = {
    "vue",
  }
}

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by smithbm2316** [comment]
I am able to reproduce this. From an initial peek at this, it looks like Treesitter is not parsing part of the Vue file properly, which is causing the issue. I simply wrapped the line that was throwing the error with an `if` statement to check if it was nil or not, so that this error wouldn't happen and I could take a closer look. May be an issue with the Vue parser for treesitter or perhaps something else. I'll try to look into this in more detail in the coming week sometime, but if you want to avoid the error for now, you can add the following to the `lua/telescope/builtin/files.lua` file on line 413 to get the picker to at least open:

```lua
if lines[row] then  -- <------- add this if statement around the for loop below to avoid highlighting lines where lines[row] is nil
  for index = 0, #lines[row] do
    line_highlights[row][index] = hl
  end
end
```

![image](https://user-images.githubusercontent.com/37027883/118387894-97f3c780-b610-11eb-96ac-79686d8e005d.png)

**Comment by R0LA1mRifcF8yAkk** [comment]
@smithbm2316 Thank you so much for looking into this. I think I will use standard vim search in the meantime, I can't be bothered to tweak the plugin code in between updates. But thanks for the workaround, it may be of help to someone else.

**Comment by Conni2461** [comment]
Seems like something is wrong with language injection. If it was working last week, then its probably not a issue here (code hasn't changed in the last 2 weeks and that section in the last month). Probably do to some changes in neovim and `runtime/lua/vim/treesitter/query.lua` (or maybe nvim-treesitter queries, but the language injection in the preview looks correct).

Would probably be good if someone could bisect it. Its just me guessing, but maybe trying to checkout a commit pre the two in this history? https://github.com/neovim/neovim/commits/master/runtime/lua/vim/treesitter/query.lua

**Comment by h0adp0re** [comment]
Hello @smithbm2316, I have been away for a bit and having returned now, the issue still stands, have you been able to take a look?

**Comment by smithbm2316** [comment]
> Hello @smithbm2316, I have been away for a bit and having returned now, the issue still stands, have you been able to take a look?

@h0adp0re my apologies for the belated response. I did get a chance to look into it briefly, but with no success. I unfortunately don't have enough experience with Treesitter to be able to make much of an educated guess on what the source of the bug is. I was able to reproduce the issue but I was not able to find any kind of useful info on what is causing this issue.

**Comment by tjdevries** [comment]
We could probably just skip rows that don't have anything in them -- it's  just for the highlights (if I recall correctly)

**Comment by h0adp0re** [comment]
@tjdevries Is the abovementioned workaround good enough for a fix? It's been working for me for all this time and seemingly nothing has broken. I may as well submit the small PR if that's the case.

```lua
if lines[row] then  -- <------- add this if statement around the for loop below to avoid highlighting lines where lines[row] is nil
  for index = 0, #lines[row] do
    line_highlights[row][index] = hl
  end
end
```

**Comment by tjdevries** [comment]
yeah, that's probably good enough, or we can do `#(lines[row] or {})`. I do not mind either way.

**Comment by talksik** [comment]
anyone else getting this in react files? it works on one computer but not another, and both are using the same nvim config

**Comment by calvinchoy** [comment]
@talksik while using the same config are you also sure that the packages are updated to the same versions?

**Comment by talksik** [comment]
> @talksik while using the same config are you also sure that the packages are updated to the same versions?

Yep just updated with packersync. Still same problem.

**Comment by qngdt** [comment]
> anyone else getting this still? it works on one computer but not another, and both are using the same nvim config
> 
> ```
> /start/telescope.nvim/lua/telescope/builtin/__files.lua:413: attempt to call method '_get_hl_from_captu
> re' (a nil value)
> ```

Can confirm I have the same problem.
