### ISSUE TITLE
Grep for regular expression using rip grep

### ISSUE THREAD

**Issue by anoop1005** [nvim-telescope/telescope.nvim#845]
### Description
By default telescope doesn't allow to search for regular expression. 
How to search for a regular expression in the below format on the current buffer using telescope
rg -i 'error|fatal'

**Expected Behavior**
The telescope should support regular expression search

**Actual Behavior**
The telescope is not supporting regular expression search

### Details

Try to search for a regular expression in the format 'error|fatal' using telescope live grep. Gettting the below error
Error executing vim.schedule lua callback: ...data\plugged\telescope.vim\lua\telescope\make_entry.lua:163: attempt to concatenate field 'filename' (a nil value)

**Comment by smithbm2316** [comment]
`live_grep` does not support this at the moment. 

Check out #767 for a recent PR that merged the `use_regex` option that can be used with the `grep_string` picker to search for a string with regex supported. 

`grep_string` searches the word under your cursor, but can be overridden to work like `:Rg` from fzf with a setup like [this]()

**Comment by anoop1005** [comment]
Thanks created a mapping like this...
nnoremap <leader>rg :lua require 'init'.grep_prompt()<cr>
function M.grep_prompt()
  require('telescope.builtin').grep_string {
    search = vim.fn.input("Rg> "),
  }
end

Few more queries
1. How can I limit the search to the current buffer instead of the current directory
2. How can i find what is the expression grep_string is executing?. ie I am interested in what are the parameters passed to "rg "?

**Comment by smithbm2316** [comment]
1. Maybe I'm missing something here, but if you want to perform a regex search for just your current buffer, is there a reason why you aren't just using Vim's `/` search? That's exactly what it does, and Telescope is primarily targeted at being a _fuzzy finder_ in most of its use cases. I'm not aware of any way to make the `grep_string` picker use only the current buffer only, but I'm sure it's something that could be added to it if you wanted to submit a PR for it. I don't think it's possible to do so without writing a custom wrapper around the `grep_string` picker at the moment, but I could be wrong.

2. You can check the source code for the picker in the `lua/telescope/builtin/files.lua` file, the code for the `grep_string` picker starts at line 100.

**Comment by VVKot** [comment]
There is `builtin.current_buffer_fuzzy_find` for search current buffer specifically.

**Comment by Conni2461** [comment]
regex is supported by `grep_string` and `live_grep` for quite some time. Closing
