### ISSUE TITLE
Telescope find_files errors out on On NVIM v0.5.0-dev+1330-gd16e9d8ed

### ISSUE THREAD

**Issue by pranithk** [nvim-telescope/telescope.nvim#851]
### Description
On NVIM v0.5.0-dev+1330-gd16e9d8ed `:Telescope find_files` fails with
E5108: Error executing lua .../.vim/plugged/plenary.nvim/lua/plenary/window/border.lua:138: Vim(autocmd):E680: <buffer=6>: invalid buffer number

**Expected Behavior**
On NVIM v0.5.0-dev+1302-g8a93d1028 the same command works as expected

**Actual Behavior**
It gives error mentioned in the description

### Details

1. Download the nvim.appimage nightly release(today it is NVIM v0.5.0-dev+1330-gd16e9d8ed) from https://github.com/neovim/neovim/releases
2. chmod +x /path/to/the/downloaded/nvim.appimage
3. Launch the application and type `:Telescope find_files`
4. This errors out with the message: `E5108: Error executing lua .../.vim/plugged/plenary.nvim/lua/plenary/window/border.lua:138: Vim(autocmd):E680: <buffer=6>: invalid buffer number
`

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev+1330-gd16e9d8ed
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az32-571

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

```
- Operating system: 
`Fedora 34`
- Telescope commit: 
```
commit 69eb5eacff421e05aeb1e02ff97ef64bfd955c53 (HEAD -> master, origin/master, origin/HEAD)
Author: Damon Timm <damontimm@gmail.com>
Date:   Sun May 16 14:36:16 2021 -0400

    fix: string.find() matching for only_cwd option (builtin.buffers) (#849)
    
    `string.find()` is defaulting to _pattern_ matching (rather than string
    literal matching).  If you are using the `only_cwd` command in a
    directory with a `-` (for example) the option fails to work.
    
    This fix asks `string.find()` to interpret the arguments as literal
    strings rather than patterns.
    
    Reference: https://stackoverflow.com/a/15258515/181902

```

</details>

<details><summary>Configuration</summary>
<p>

Default configuration

**Comment by Conni2461** [comment]
Did you also make sure popup.nvim is up to date?

**Comment by pranithk** [comment]
@Conni2461 That fixed it! Thanks a lot!
