### ISSUE TITLE
Backspace doesn't work after normal mode

### ISSUE THREAD

**Issue by kuator** [nvim-telescope/telescope.nvim#852]
Backspace doesn't work after normal mode
Reproduction steps:
1. `:Telescope find_files`
2. `search-pattern<esc>i`
3. try to delete inserted text with backspace, it doesn't work

**Comment by LamprosPitsillos** [comment]
Having the same problem here...

**Comment by elianiva** [comment]
should've been fixed by this PR https://github.com/neovim/neovim/pull/16421

**Comment by kuator** [comment]
> should've been fixed by this PR [neovim/neovim#16421](https://github.com/neovim/neovim/pull/16421)

can confirm, it works

**Comment by ryoppippi** [comment]
I have the same problem still rn

**Comment by Conni2461** [comment]
Its a neovim bug which was fixed in the latest nightly. If you are still running 0.6.* of course you still experience this bug. This bug will be fixed with neovim 0.7 for you

**Comment by ryoppippi** [comment]
Ok Thanks
