### ISSUE TITLE
Race condition when using `vim.fn.termopen` with `new_buffer_previewer`

### ISSUE THREAD

**Issue by camgraff** [nvim-telescope/telescope.nvim#859]
### Description

See my [my post on gitter](https://gitter.im/nvim-telescope/community?at=60a871f145c2185a5ee18fd0) for a description of my use case and how it relates to the issue. TLDR I'm making an extension for tmux that uses `vim.fn.termopen` inside a `new_buffer_previewer` which can result in a distortion of the preview window.

After much debugging I've found the reason is because there is a [delay in attaching the preview buffer to the window](https://github.com/nvim-telescope/telescope.nvim/blob/69eb5eacff421e05aeb1e02ff97ef64bfd955c53/lua/telescope/previewers/buffer_previewer.lua#L188) which creates a race condition that can distort the previewer. You can verify that this is indeed the cause of the issue by commenting out the `vim.schedule` wrapping and then running my reproduction steps below and see that the issue disappears. The workaround I'm currently using is to manually call `vim.api.nvim_win_set_buf(self.state.winid, self.state.bufnr)` inside `define_preview` which avoids the delay of `vim.schedule`. 

Additionally, I have found that this is not consistent across machines. On my Thinkpad, I always see the issue, but on my Mac sometimes the preview looks normal.

What I think is happening:
since the attachment of the buffer previewer to the preview window is delayed due to `vim.schedule`, the terminal inside the preview buffer is not yet full size when the `termopen` command is run. So, the output of the terminal command is "compressed". 

For reference, this behavior popped up due to #797.

**Expected Behavior**

The preview window should display correctly. i.e. like this:
![Screenshot from 2021-05-21 21-53-56](https://user-images.githubusercontent.com/46980357/119241478-3bb30b00-bb1c-11eb-80bb-1dbc9e7aaa6a.png)

**Actual Behavior**

The preview window is distorted.
![Screenshot from 2021-05-21 20-33-49](https://user-images.githubusercontent.com/46980357/119241470-28a03b00-bb1c-11eb-8701-ef6bd08c9711.png)

### Details
This is not specific to tmux. You can reproduce with a simple terminal command like `less`.

<details><summary>Reproduce</summary>

prev_bug.lua
```lua
local telescope = require('telescope')
local finders = require('telescope.finders')
local pickers = require('telescope.pickers')
local previewers = require('telescope.previewers')

local bug_example = function(opts)
    pickers.new(opts, {
        finder = finders.new_table {
            results = {"dummy_result"}
        },
        previewer = previewers.new_buffer_previewer{
            define_preview = function(self, entry, status)
                vim.api.nvim_buf_call(self.state.bufnr, function()
                   vim.fn.termopen(vim.fn.expand("less ~/.vimrc"))
                end)
            end
        }
    }):find()
end

return telescope.register_extension {
    exports = {
        bug_example = bug_example
    }
}

```

test.vim
```viml
call plug#begin('~/.vim/plugged')

Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'

call plug#end()

lua <<EOF
-- telescope
require('telescope').load_extension('prev_bug')
EOF

```
1. nvim -nu test.vim
2. :Telescope prev_bug bug_example

See that the preview only shows the first few lines.
![Screenshot from 2021-05-22 16-46-15](https://user-images.githubusercontent.com/46980357/119241597-46ba6b00-bb1d-11eb-9aad-073fc9d2bed5.png)

</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
$ nvim --version
NVIM v0.5.0-dev+1345-g6dd04ed5f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/cam/projects/neovim/build/config -I/home/cam/projects/neovim/src -I/home/cam/projects/neovim/.deps/usr/include -I/usr/include -I/home/cam/projects/neovim/build/src/nvim/auto -I/home/cam/projects/neovim/build/include
Compiled by root@cam-thinkpad

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- Operating system: Ubuntu 20.04
- Telescope commit: 69eb5ea

</details>

<details><summary>Configuration</summary>
<p>
see reprodution steps above.

**Comment by Conni2461** [comment]
Hm i am not sure what you are expecting here. Yeah we could remove the `vim.schedule` but the schedule actually reduced the flickering.
Another option would be to use the way more modern and way cooler `vim.api.nvim_open_term`.

```lua
local finders = require('telescope.finders')
local pickers = require('telescope.pickers')
local previewers = require('telescope.previewers')

local Job = require("plenary.job")

local get_job_opts = function(chan, cmd)
  local writer = vim.schedule_wrap(function(_, data)
      vim.api.nvim_chan_send(chan, data .. '\r\n')
  end)
  cmd.on_stdout = writer
  cmd.on_stderr = writer
  return cmd
end

pickers.new({}, {
  finder = finders.new_table {
    results = {"dummy_result"}
  },
  previewer = previewers.new_buffer_previewer{
    define_preview = function(self, entry, status)
      local chan = vim.api.nvim_open_term(self.state.bufnr, {})
      Job:new(get_job_opts(chan, { 'bat', '--color', 'always', vim.fn.expand('~/.vimrc') })):start()
    end
  }
}):find()
```

**Comment by camgraff** [comment]
> Hm i am not sure what you are expecting here. Yeah we could remove the `vim.schedule` but the schedule actually reduced the flickering.
> Another option would be to use the way more modern and way cooler `vim.api.nvim_open_term`.
> 
> ```lua
> local finders = require('telescope.finders')
> local pickers = require('telescope.pickers')
> local previewers = require('telescope.previewers')
> 
> local Job = require("plenary.job")
> 
> local get_job_opts = function(chan, cmd)
>   local writer = vim.schedule_wrap(function(_, data)
>       vim.api.nvim_chan_send(chan, data .. '\r\n')
>   end)
>   cmd.on_stdout = writer
>   cmd.on_stderr = writer
>   return cmd
> end
> 
> pickers.new({}, {
>   finder = finders.new_table {
>     results = {"dummy_result"}
>   },
>   previewer = previewers.new_buffer_previewer{
>     define_preview = function(self, entry, status)
>       local chan = vim.api.nvim_open_term(self.state.bufnr, {})
>       Job:new(get_job_opts(chan, { 'bat', '--color', 'always', vim.fn.expand('~/.vimrc') })):start()
>     end
>   }
> }):find()
> ```

When I run this, I get 
```
E317: pointer block id wrong
E317: pointer block id wrong
```
and my neovim crashes :confused: 

Also, I don't think `nvim_open_term` would work to display with an interactive process like `tmux attach`?

**Comment by camgraff** [comment]
> > Hm i am not sure what you are expecting here. Yeah we could remove the `vim.schedule` but the schedule actually reduced the flickering.
> > Another option would be to use the way more modern and way cooler `vim.api.nvim_open_term`.
> > ```lua
> > local finders = require('telescope.finders')
> > local pickers = require('telescope.pickers')
> > local previewers = require('telescope.previewers')
> > 
> > local Job = require("plenary.job")
> > 
> > local get_job_opts = function(chan, cmd)
> >   local writer = vim.schedule_wrap(function(_, data)
> >       vim.api.nvim_chan_send(chan, data .. '\r\n')
> >   end)
> >   cmd.on_stdout = writer
> >   cmd.on_stderr = writer
> >   return cmd
> > end
> > 
> > pickers.new({}, {
> >   finder = finders.new_table {
> >     results = {"dummy_result"}
> >   },
> >   previewer = previewers.new_buffer_previewer{
> >     define_preview = function(self, entry, status)
> >       local chan = vim.api.nvim_open_term(self.state.bufnr, {})
> >       Job:new(get_job_opts(chan, { 'bat', '--color', 'always', vim.fn.expand('~/.vimrc') })):start()
> >     end
> >   }
> > }):find()
> > ```
> 
> When I run this, I get
> 
> ```
> E317: pointer block id wrong
> E317: pointer block id wrong
> ```
> 
> and my neovim crashes 
> 
> Also, I don't think `nvim_open_term` would work to display with an interactive process like `tmux attach`?
> 
> Edit: got a different error message this time
> ![Screenshot from 2021-05-23 10-36-59](https://user-images.githubusercontent.com/46980357/119267098-e83fcc00-bbb2-11eb-81a2-5c774b29d88b.png)
> Maybe some upstream bug?

I had `vim.schedule` still commented out from earlier testing which caused the above errors interestingly. But, yeah `nvim_open_term` won't work with `tmux attach` :cry: 
![Screenshot from 2021-05-23 10-42-38](https://user-images.githubusercontent.com/46980357/119267315-a3686500-bbb3-11eb-9d44-4ca25cab3da3.png)

I'm not too concerned with fixing this since I have a good workaround in place, but it does seem like something that people could realistically run into issues with in the future. Perhaps keep the default behavior with `vim.schedule`, but add an option for calling `nvim_win_set_buf` synchronously and some documentation explaining the consequences of this?

**Comment by Conni2461** [comment]
Since this issue was opened we fixed the remaining issues with `new_termopen_previewer`. So please just dont use `vim.fn.termopen` with `new_buffer_previewer`

Example:

```lua
local finders = require('telescope.finders')
local pickers = require('telescope.pickers')
local previewers = require('telescope.previewers')

local bug_example = function(opts)
  pickers.new(opts, {
    finder = finders.new_table {
      results = {"dummy_result"}
    },
    previewer = previewers.new_termopen_previewer {
      get_command = function(entry)
        return { 'tmux', 'attach' }
      end
    }
  }):find()
end

bug_example({})
```

Thanks :)
