### ISSUE TITLE
Option to start live grep after typing a minimum number of chars

### ISSUE THREAD

**Issue by weeman1337** [nvim-telescope/telescope.nvim#862]
**Is your feature request related to a problem? Please describe.**

Grepping something with only a single char doesn't make sense in most cases. Also live grep takes quite "a long time" until the first char results are displayed and typing further drills down the results.

**Describe the solution you'd like**

I would like to have a configuration option to start the live grep after typing e.g. 3 characters.

**Comment by smithbm2316** [comment]
You may want to try the `grep_string` picker with a setup like the following:

```lua
:lua require('telescope.builtin').grep_string{ search = vim.fn.input('Grep for > ' ) })
```

This would allow you to type in a string first, and then open up Telescope with the results of that string and drill down from there. This is something I still need to add to the docs, but may be what you're looking for. As an added bonus, you can add the `use_regex = true` option to the table you pass to `grep_string` above if you want to do a search with regex allowed as well.

I have a custom Lua function that sets something similar to this that you can take a look at [here](https://github.com/smithbm2316/dotfiles/blob/a98da8ae5b0b55632d060fb314452769e4b0ef1f/nvim/lua/my/plugs/telescope.lua#L148). Hope this helps, let me know if anything about this isn't clear!

**Comment by fdschmidt93** [comment]
Closing this since grep_string with vim.fn.input does the job. I'll note it to maybe mention it in a FAQ. Please comment if more questions.
