### ISSUE TITLE
Add LSP outgoing and incoming calls

### ISSUE THREAD

**Issue by languitar** [nvim-telescope/telescope.nvim#863]
**Is your feature request related to a problem? Please describe.**
I am using telescope as my primary interface for list-like LSP results. One thing that is missing is support for the `outgoing_calls` and `incoming_calls` methods provided by the neovim LSP implementation.

**Describe the solution you'd like**
Having telescope lists similar to what is available for other LSP results would be great.

**Describe alternatives you've considered**

**Comment by tami5** [comment]
Hmmm, I'm having trouble understanding that feature. Could you please provide an example implementation. Thanks

**Comment by gokulsoumya** [comment]
It shows the external function calls made from inside the current function (outgoing calls) and the places where the current function is being called from (incoming calls, similar to references) - https://stackoverflow.com/a/56010680/7115678

**Comment by zeertzjq** [comment]
[telescope-lsp-handlers.nvim](https://github.com/gbrlsnchs/telescope-lsp-handlers.nvim) has these two handlers. Maybe this can be a reference.

**Comment by Conni2461** [comment]
#1484 was merged into the current dev branch

See https://github.com/nvim-telescope/telescope.nvim/issues/1938 for more infos
