### ISSUE TITLE
Vertical monitor and preview.

### ISSUE THREAD

**Issue by cr0wt** [nvim-telescope/telescope.nvim#864]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
If I use vertical monitor, it would be nice if preview window would move to top part of monitor, not hide outside of view on right.

I just want to through it outside of my head.

**Comment by clason** [comment]
You can use the `vertical` layout strategy for that:
```
telescope.setup {
  defaults = {
    layout_strategy = "vertical",
 }
}
```

**Comment by cr0wt** [comment]
Thank you!
