### ISSUE TITLE
Only show lines which don't match search query

### ISSUE THREAD

**Issue by RRethy** [nvim-telescope/telescope.nvim#871]
**Is your feature request related to a problem? Please describe.**
I'm looking to replace `cfilter`s `:Cfilter` and `:Cfilter!` with telescope since it can be used to filter quickfix list. However, `:Cfilter!` cannot be replaced since telescope only does positive matches.

**Describe the solution you'd like**
Not sure the best solution, but maybe a filter mode where you can use the actions feature to change the mode from keeping matches to discarding them.

**Describe alternatives you've considered**
Right now I'm just using `:Cfilter!` to discard matches.

**Comment by Conni2461** [comment]
Try https://github.com/nvim-telescope/telescope-fzf-native.nvim where `!test` will return all matches besides `test`. It exist because of the search syntax https://github.com/junegunn/fzf#search-syntax

**Comment by RRethy** [comment]
Good enough for me, thanks.
