### ISSUE TITLE
Action window with the ability to close buffers

### ISSUE THREAD

**Issue by osenvosem** [nvim-telescope/telescope.nvim#873]
**Is your feature request related to a problem? Please describe.**
I can list open buffers but I unable to close a buffer.

**Describe the solution you'd like**
Make action window with context based action list for a provider.

**Describe alternatives you've considered**
Currently using coc-list as an alternative.

Maybe I missed something and this feature exists. Sorry in advance then.

**Comment by l-kershaw** [comment]
There is currently a PR in the works (#803) that will implement a keyboard mapping to delete selected buffers.

I'm not sure what you mean by an "action window", but is a mapping sufficient for your use case?

**Comment by osenvosem** [comment]
@l-kershaw yep, that would be sufficient. Thanx.
