### ISSUE TITLE
Workspace search and replace

### ISSUE THREAD

**Issue by MatthiasGrandl** [nvim-telescope/telescope.nvim#875]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem. But migrating from VSCode I find myself missing the search and replace feature and I feel like it could be replicated nicely with telescope.

**Describe the solution you'd like**
Basically similar to livegrep but it in addition to having an input field for search, having a second input field with a replacement.
It should then list all files with matches and on hover preview the changes it is going to make in each file.

I tried to see if something similar had been suggested, but didn't find anything.

**Comment by Conni2461** [comment]
You probably want to read this thread https://github.com/nvim-lua/wishlist/issues/18

**Comment by MatthiasGrandl** [comment]
@Conni2461 ok that's a good starting point. Wouldn't you agree though that having such a module in telescope sounds like a great fit?

**Comment by Conni2461** [comment]
No i don't think it needs to be part of telescope. I currently can't imagine how the ui should look like that and its to VSCode like for me. I am happy with what the qflist offers me. If someone wants to make an extension for that i don't mind, but i don't think it should be part of core. ThePrimeagen summed it up pretty good in his comment in the linked thread and it looks like that windwp has a pretty good plugin solution for that https://github.com/windwp/nvim-spectre

I should probably say that this is my personal opinion and i am not speaking for the whole telescope team.

**Comment by DerWeh** [comment]
So far I used [qfreplace](https://github.com/thinca/vim-qfreplace/blob/master/doc/qfreplace.txt) for this task.
I used [Denite](https://github.com/Shougo/denite.nvim) to grep, put it in the quickfix and then replaced the entries.
This could probably easily be mimicked by `telescope`. Probably, we just have to define a mapping to `  actions.send_selected_to_qflist()` or `actions.send_selected_to_qflist()`.

**Comment by clason** [comment]
You mean like https://github.com/nvim-telescope/telescope.nvim/blob/4e629cdea197b7c4f3c476346a8841b74bf9fd56/lua/telescope/actions/init.lua#L717-L719
(bound to `<c-q>` by default)?

**Comment by DerWeh** [comment]
Thanks, I overlooked this key-binding. For me, this is a sufficient workflow. It lacks the elegance of `telescope` but it is practical enough. `Telescope live_grep` → search ⇾ select via `<Tab>` if only fraction wanted ⇾ `Qfreplace` ⇾ type substitution command.

**Comment by Nargonath** [comment]
If you want to send to the quickfix list only the items you selected you need to use `<M-q>` and not `<C-q>`. I didn't know both of these keybindings before so might be useful to somebody else as well.
