### ISSUE TITLE
Error when opening pop-up in a non-modifiable pane

### ISSUE THREAD

**Issue by 5c077m4n** [nvim-telescope/telescope.nvim#876]
### Description

When I try to open a pop-up window from a non-modifiable pane - ie nvim-tree - I get an error message and a broken pop-up appears instead, so I need to close nvim and re-open so it'll go away.

**Expected Behavior**

Should open and be searchable (like last week)

**Actual Behavior**

A broken window appeared [just like this](
https://user-images.githubusercontent.com/35409124/120094226-da94c400-c127-11eb-8d5b-399c5bbf56bc.mov
)

### Details

<details><summary>Reproduce</summary>

1. nvim <some_work_dir>
2. go to nvim-tree pane
3. run `require'telescope.builtin'.find_files()` (or any other)
4. .... bang here is the issue
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```bash
NVIM v0.5.0-dev+1361-gcabf8ab26
Build type: Debug
LuaJIT 2.1.0-beta3
```
- Operating system(s): Alpine linux v3.14.0_alpha20210212 & MacOS big sur
- Telescope commit: ec8cf12

[config](https://github.com/5c077m4n/scottconfig.lua/tree/master/lua/vimrc/plugins/telescope)

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !c
https://user-images.githubusercontent.com/35409124/120094226-da94c400-c127-11eb-8d5b-399c5bbf56bc.mov
 --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by l-kershaw** [comment]
I'm not sure what has caused this I'm afraid, and I can't reproduce this on my machine (Windows).
I'm also not sure what has caused this issue to crop up for you specifically in the last week or so, as nothing in the `Picker:find` function has been changed in at least the last month 😕 

---

Also, it seems like almost everything in your given Telescope `setup()` config is setting options to their default values (everything except `prompt_prefix` and `layout_defaults` as far as I can tell).
This is not required, as anything not specified by the user falls back to Telescope defaults.
Removing them has the benefit of making it easier for you to see where you are actually changing the default behaviour, making it easier to debug.
It also allows the Telescope team to improve the defaults over time and for it to not be overridden by your config 🙂

**Comment by 5c077m4n** [comment]
Thank you for the quick reply :)

The more I try to debug it the more I think that it's a Neovim bug/incompatibility with the popup api in non-modifiable buffers - it doesn't work with [Floaterm](https://github.com/voldikss/vim-floaterm) either...

And about the Telescope setup function, where did I go wrong? I couldn't find the configs that you mentioned in my setup 🙈

**Comment by l-kershaw** [comment]
Ah, I've just realised that you linked your config under the "Environment" fold.
I was looking at the config under the "Configuration" fold, my mistake 😅

Your linked config seems perfectly fine (although you could remove the `vimgrep_arguments` if you wanted, as those are the default values).

**Comment by 5c077m4n** [comment]
Yes, I've been playing around with using `ag` instead of the default `rg` command - but the MacOS terminal is super slow.

Thank you so much!
