### ISSUE TITLE
Segfault in builtins.oldfiles when previewing a folder

### ISSUE THREAD

**Issue by Akeboshiwind** [nvim-telescope/telescope.nvim#884]
### Description
When scrolling over a folder with the `oldfiles` picker, nvim segfaults.

Unfortunately I'm having trouble replicating this consistently, there seems to be some part of my local filesystem that's broken. I'll include more info about this in case it helps in the `Reproduce` section.

Regardless of whether this is something broken in my filesystem or not, I don't think telescope should segfault here.

**Expected Behavior**
No segfault

**Actual Behavior**
Segfault 😭

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :e /path/to/broken/folder
3. :Telescope oldfiles
    Note: This only segfaults immediately because the folder happends to be the first in the list
              If it's not first in the list you can scroll to it and then it will segfault
4. Segfault 🎉 

As mentioned above I'm having trouble replicating this.
When I try it in my `/tmp` filesystem it doesn't segfault (when opening `/tmp/test/test`):
```
$ ls -la /tmp/test
total 8
drwxr-xr-x   4 oliverm  wheel      128  2 Jun 00:22 .
drwxrwxrwt  20 root     wheel      640  2 Jun 00:06 ..
drwxr-xr-x   2 oliverm  781575264   64  2 Jun 00:22 test
-rw-r--r--   1 oliverm  wheel      419  2 Jun 00:05 test.vim
```

But in my home filesystem this isn't working (when opening `~/dotfiles/nvim/.config/nvim/modules/rust`):
```
$ ls -la ~/dotfiles/nvim/.config/nvim/modules/
total 0
drwxr-xr-x  12 oliverm  781575264  384  1 Jun 23:26 .
drwxr-xr-x   4 oliverm  781575264  128 30 Nov  2020 ..
drwxr-xr-x   4 oliverm  781575264  128  8 May  2020 00_base
drwxr-xr-x   4 oliverm  781575264  128 27 Nov  2020 01_theme
drwxr-xr-x   4 oliverm  781575264  128 31 May 20:10 02_which-key
drwxr-xr-x   4 oliverm  781575264  128  1 Jun 23:45 03_telescope
drwxr-xr-x   4 oliverm  781575264  128  1 Jun 23:06 04_lsp
drwxr-xr-x   4 oliverm  781575264  128  1 Jun 22:15 clojure
drwxr-xr-x   4 oliverm  781575264  128  1 Jun 22:17 filetypes
drwxr-xr-x   4 oliverm  781575264  128  1 Jun 00:19 nvim-treesitter
drwxr-xr-x   4 oliverm  781575264  128  1 Jun 23:35 rust
drwxr-xr-x   5 oliverm  781575264  160 31 May 16:24 vimspector
```

I have no idea what the group `781575264` is btw. I think it's something added by my work.
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1362-g3cd688ff7
- Operating system: Mac OS
- Telescope commit: 5b6b23a

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
```
</details>

**Comment by elianiva** [comment]
what if you change the group ownership the same as your username? I had a similar thing before and in my case it was 1000

**Comment by Conni2461** [comment]
@elianiva I think i actually know whats causing this. Will open PR to plenary later.

**Comment by Akeboshiwind** [comment]
It turns out that it *is* a group set by my work.
Although for some reason it just wasn't being rendered while I was off the VPN I think?

Now when I run `ls` I get something like:
```
$ ls -la ~/dotfiles/nvim/.config/nvim/modules/
total 0
drwxr-xr-x  12 oliverm  <some corp thing>\Domain Users  384  1 Jun 23:26 .
drwxr-xr-x   4 oliverm  <some corp thing>\Domain Users  128 30 Nov  2020 ..
drwxr-xr-x   4 oliverm  <some corp thing>\Domain Users  128  8 May  2020 00_base
drwxr-xr-x   4 oliverm  <some corp thing>\Domain Users  128 27 Nov  2020 01_theme
drwxr-xr-x   4 oliverm  <some corp thing>\Domain Users  128 31 May 20:10 02_which-key
drwxr-xr-x   4 oliverm  <some corp thing>\Domain Users  128  1 Jun 23:45 03_telescope
drwxr-xr-x   4 oliverm  <some corp thing>\Domain Users  128  1 Jun 23:06 04_lsp
drwxr-xr-x   4 oliverm  <some corp thing>\Domain Users  128  1 Jun 22:15 clojure
drwxr-xr-x   4 oliverm  <some corp thing>\Domain Users  128  1 Jun 22:17 filetypes
drwxr-xr-x   4 oliverm  <some corp thing>\Domain Users  128  1 Jun 00:19 nvim-treesitter
drwxr-xr-x   4 oliverm  <some corp thing>\Domain Users  128  2 Jun 00:40 rust
drwxr-xr-x   5 oliverm  <some corp thing>\Domain Users  160 31 May 16:24 vimspector
```

And now the `:Telescope oldfiles` command works just fine.

My current guess is that when telescope gets info about the folder to render it and the group is broken in some way then it segfaults.

**Comment by Akeboshiwind** [comment]
I thought I'd come up with a way to reproduce it:
- Create a new group
- Add it to a folder
- Delete the group

But that didn't work :/

Here's what I did on osx:
```
$ sudo dscl . -create /Groups/mygroup
$ sudo dscl . -create /Groups/mygroup RealName "test"
$ sudo dscl . -create /Groups/mygroup passwd "*"
$ sudo dscl . -create /Groups/mygroup gid 799
$ sudo dscl . -create /Groups/mygroup GroupMembership oliverm
$ mkdir /tmp/my_test_dir
$ sudo chgrp mygroup /tmp/my_test_dir
$ sudo dscl . -delete /Groups/mygroup
```

With this I end up with:
```
$ ls -la /tmp/ | grep my_test_dir
drwxr-xr-x   2 oliverm  799       64  2 Jun 00:06 my_test_dir
```

**Comment by Conni2461** [comment]
Before you do endless searching. I think this fixes it. https://github.com/nvim-lua/plenary.nvim/pull/165

Basically the c functions `getpwuid` and `getgrgid` can return `NULL` and i just forgot to check for that

**Comment by Akeboshiwind** [comment]
Cool I'm glad you were able to figure it out so quickly!

I was just hoping to be able to reproduce it once it get's fixed 😅

**Comment by Conni2461** [comment]
@Akeboshiwind can you validate if the issue is fixed if that PR is checked out? If so i would merge.

**Comment by Akeboshiwind** [comment]
Conviniently my filesystem has broken itself again so I was able to test it.

That PR fixes it perfectly 🎉
