### ISSUE TITLE
Unable to open files from insert mode using Enter

### ISSUE THREAD

**Issue by Liquidmantis** [nvim-telescope/telescope.nvim#889]
From insert mode the split and tab open bindings work, but the simple default binding of Enter doesn't open the selected file and instead only clears the input field.  It works in normal mode, however.

_this is a retroactive issue to leave breadcrumbs_

**Comment by Liquidmantis** [comment]
I tracked this down to `vim-peartree`, an auto-pairing plugin.  It apparently rebinds `<CR>` to an internal action.  After disabling it, Enter does properly open files in Telescope from insert mode.

**Comment by Conni2461** [comment]
You should take a look at this issue: https://github.com/nvim-telescope/telescope.nvim/issues/731#issuecomment-819028282

**Comment by Liquidmantis** [comment]
Bah!  I totally missed that, and there are only a handful of results when you search for `<CR>`.   Well, now there's a search hit for `enter`.
