### ISSUE TITLE
grep_string not work

### ISSUE THREAD

**Issue by paopaol** [nvim-telescope/telescope.nvim#891]
### Description
`lua require('telescope.builtin').grep_string({search = "extern"})`  search nothing   
`:Telescope grep_stirng` search nothing   too

**Expected Behavior**
display extern result lines
**Actual Behavior**
result is empty

### Details

:lua require('telescope.builtin').grep_string({search = "extern"}) 
```

**Comment by Conni2461** [comment]
`ripgrep` executable is required for `live_grep` and `grep_string`. Also `:messages` should give you that error. It sadly just prints the whole stacktrace so its not that noticeable

**Comment by Conni2461** [comment]
Closing. Because havent received any feedback

**Comment by daUnknownCoder** [comment]
it should be installed with the package as imp deps right?
