### ISSUE TITLE
How To: replace netrw file explorer with file_browser

### ISSUE THREAD

**Issue by yourfavouriteuncle** [nvim-telescope/telescope.nvim#892]
Hello,

I've been playing around with the neovim nightly for 2 days and I discovered Telescope. I'm wondering if it's possible to replace the simple file browsing capabilities of netrw with `builtins.file_browser`. I tried to do the following, inspired from [ranger.vim](https://github.com/francoiscabrol/ranger.vim/pull/36/files#diff-67bb7608922e889f86b15c4a024114eea2dde063ca71d8261c2071e9d616a4b9R94).

And after substitutions I got the following patch in my `init.vim`.

```
augroup ReplaceNetrw
    autocmd VimEnter * silent! autocmd! FileExplorer
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | Telescope file_browser({argv()[0]}) | endif
augroup END
```

When I do `nvim documents/` I get a strange bunch of errors that I don't know how to begin debugging. Is there a quick fix for this, or is this still uncharted territory?

**Comment by Conni2461** [comment]
Excuse my viml ignorance but this should work, might not be optimal:

```viml
augroup ReplaceNetrw
    autocmd VimEnter * silent! autocmd! FileExplorer
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | call luaeval("require('telescope.builtin').file_browser({cwd = _A})", argv()[0]) | endif
augroup END
```
