### ISSUE TITLE
search_dirs for grep_string not working

### ISSUE THREAD

**Issue by sriramkandukuri** [nvim-telescope/telescope.nvim#893]
Hi,

I have an environment variable having list of directories space separated.
say `DIRLIST="dir1 dir2 dir3 dir4"`

How can I pass this to `search_dirs` option so that find, fd, grep, rg works only with these directories?

If `DIRLIST` is empty I dont want to set `search_dirs`, how can I achieve this.

Thanks,
Sriram.K

**Comment by sriramkandukuri** [comment]
Did it like below,

``` lua
M.dirfiles = function()
    local tab={}
    local t=vim.env.DIRLIST
                                                                                                                                                                       
    if t == nil then
        return tab
    end
    for str in string.gmatch(t, "([^ ]+)") do
        table.insert(tab, str)
    end
    return tab
end
```
And in mappings like

```vim
nnoremap <Leader>t<leader> :lua require('telescope.builtin').find_files( {search_dirs = require('devenv.tscope').csfiles() } )<CR>
```

This way its working for `live_grep`, `find_files`, `git_files` but not working for `grep_string`

Thanks,
Sriram.K

**Comment by Conni2461** [comment]
Yeah apparently searchdirs is currently broken: https://github.com/nvim-telescope/telescope.nvim/issues/881#issuecomment-855229888

`dirfiles` can be a simplified a bit:
```lua
M.dirfiles = function()
  local t=vim.env.DIRLIST
  if t == nil then
    return {}
  end
  return vim.split(t, ' ')
end
```

**Comment by sriramkandukuri** [comment]
Thanks for the fix working with master.
