### ISSUE TITLE
Can't move cursor in win10 WSL

### ISSUE THREAD

**Issue by kdurant** [nvim-telescope/telescope.nvim#898]
### Description

When entering `Telescope git_files`, I can't select any files by `<Up>, <Down>, <C-n>, <C-p>`

**Expected Behavior**

**Actual Behavior**

### Details

```viml
set autochdir
call plug#begin('~/.config/nvim/bundle')
Plug 'git@github.com:nvim-lua/popup.nvim.git'
Plug 'git@github.com:nvim-lua/plenary.nvim.git'
Plug 'git@github.com:nvim-telescope/telescope.nvim.git'
call plug#end()
```

**Comment by Conni2461** [comment]
Does this happen with a minimal rc?

**Comment by Conni2461** [comment]
Closing because of missing information. Feel free to reopen when you are back and had time to fill out the template.
