### ISSUE TITLE
Layout for large screens suboptimal

### ISSUE THREAD

**Issue by PSeitz** [nvim-telescope/telescope.nvim#899]
On large screens (3440x1440), the middle is pretty much empty in the show reference lsp integration.

![Screenshot from 2021-06-08 07-23-29](https://user-images.githubusercontent.com/1109503/121128011-f9cbd980-c82a-11eb-9a52-40369a989d0b.png)

**Comment by PSeitz** [comment]
Thanks, then I will wait.

I think for this use case, the padding should only be active after a certain threshold, or even better (and probably easier) that you can set a maximum width for the window.

**Comment by l-kershaw** [comment]
@PSeitz just a heads up that the layout preferences PR has now been merged.

With the new changes you can pass a function to determine the width of the picker exactly how you want, so your threshold idea wouldn't be to difficult to implement in your config files.

If you have any further problems with the layout stuff, feel free to ping me 🙂

**Comment by fdschmidt93** [comment]
Closing this as it has become a stale issue and can easily be handled on the user side with good documentation. Please ping here if there is more to discuss.
