### ISSUE TITLE
Add options to pre-filter LSP Document Symbols by type

### ISSUE THREAD

**Issue by cseickel** [nvim-telescope/telescope.nvim#901]
**Is your feature request related to a problem? Please describe.**
I would like to be able to quickly jump to a method/function within the file I am currently in.

**Describe the solution you'd like**
The builtin lsp_document_symbol viewer is a good start, but I would like to filter out all properties and constants as they drown out the functions I am actually searching for. Vista has the option to filter out specific types in it's finder and I would like to see the same option here: 
`let g:vista_ignore_kinds=["Variable", "Constant", "Property"] `

**Describe alternatives you've considered**
I've tried Vista with the finder option which is OK, but I would prefer to have the preview functionality of Telescope. Also Vista is often out of sync with the current buffer.

**Additional context**
Alternative solutions could be to just add the ability to provide the filters in the options when calling the function. Also, I would be happy to impliment this myself if I can get an example of how to filter out the results by symbol type.

Thanks!

**Comment by Conni2461** [comment]
See https://github.com/nvim-telescope/telescope.nvim/issues/837

**Comment by cseickel** [comment]
Thanks for the quick response! I did try the suggustion of using `Telescope lsp_document_symbols default_text=:method:` but it does not work in the current version. Has the option changed?

When I use the completion after it opens it works, but I'd really prefer to get to that point from straight from my mapping. Also, what I'm really looking for is :method: OR :function: OR :constructor: OR :class: OR :interface:

Is there another syntax/option that accomplishes this?

**Comment by fdschmidt93** [comment]
@cseickel see #903 -- ideally, you'd give that branch a whirl and provide feedback as to whether that implements what you'd have in mind, thanks in advance!

**Comment by cseickel** [comment]
@fdschmidt93 Yup, that is perfect! For others that see this, it wasn't clear how to use a list from the vim command, I ended up making a lua function to call it for multiple symbols:

```
local showSymbolFinder = function ()
    local opts= {
        symbols = {
            "interface",
            "class",
            "constructor",
            "method",
        }
    }
    if vim.bo.filetype == "vim" then
        opts.symbols = { "function" }
    end
    require('telescope.builtin').lsp_document_symbols(opts)
end
```

**Comment by fdschmidt93** [comment]
> it wasn't clear how to use a list from the vim command

Mhm, I've also now tried a couple of things but the list doesn't seem to be properly parsed. I'm afraid I wouldn't know how to address this.

> The builtin lsp_document_symbol viewer is a good start, but I would like to filter out all properties and constants as they drown out the functions I am actually searching for. 

For completeness/reference as to why this is not implemented explicitly. This could be just as well achieved with

```lua
local showSymbolFinder = function ()
    -- lowercase for simplicity :)
    local lsp_symbols = vim.tbl_map(string.lower, vim.lsp.protocol.SymbolKind)
    -- define a filter function to excl. undesired symbols
    local symbols = vim.tbl_filter(function(symbol) return symbol ~= "function" end, lsp_symbols)
    require('telescope.builtin').lsp_document_symbols{symbols = symbols}
end
```
I didn't run the code myself though the idea kind of has to work, hopefully :)

**Comment by pidgeon777** [comment]
How could I specify multiple symbols to be filtered? For example:

Telescope lsp_document_symbols symbols=module,function

**Comment by fdschmidt93** [comment]
On mobile, so I cannot test, but in lua you'd specify it as a table and hence my hunch is it would have to be `symbols=['module', 'function']`

**Comment by pidgeon777** [comment]
Just tried but unfortunately it doesn't work.

**Comment by l-kershaw** [comment]
It is currently not possible to pass tables to Telescope via the vimscript excommands due to the way our command parser is set up. This also came up [here](https://github.com/nvim-telescope/telescope.nvim/issues/1036#issuecomment-885491418).

This is currently on my list of things to implement, but in the mean time, I would suggest you use the lua api.

**Comment by Conni2461** [comment]
`Telescope lsp_document_symbols symbols=module,function` would work if `symbols` is allowed to be interpreted as list. It needs to be marked here https://github.com/nvim-telescope/telescope.nvim/blob/b742c50bf119d7c442a553cc52e8afde0086ae02/lua/telescope/command.lua#L126-L131

But the current setup kinda sucks. I am excited to see what @l-kershaw comes up with :)
