### ISSUE TITLE
Prefill find_files query with visually selected text by expression register

### ISSUE THREAD

**Issue by jackysee** [nvim-telescope/telescope.nvim#905]
I want to prefill the find_files with currently visually selected text. Here is the function and mappings

```
function! VisualSelection()
    let [line_start, column_start] = getpos("'<")[1:2]
    let [line_end, column_end] = getpos("'>")[1:2]
    let lines = getline(line_start, line_end)
    if len(lines) == 0
        return ''
    endif
    let lines[-1] = lines[-1][: column_end - (&selection == 'inclusive' ? 1 : 2)]
    let lines[0] = lines[0][column_start - 1:]
    return join(lines, "\n")
endfunction

vnoremap <leader>F :<BS><BS><BS><BS><BS>Telescope find_files find_command=rg,--files<cr>'<c-r>=VisualSelection()<cr>

vnoremap <leader>rg :<BS><BS><BS><BS><BS>Telescope grep_string use_regex=true search=<c-r>=VisualSelection()<cr><cr>

```

If I press `<leader>F` at visual mode, the find_files prompt show, only has the single quote (using fzf native),  but the query string is empty. I tried to manually do `<c-r>=VisualSelection()` there it print nothing. After close the prompt, I can still get the visual selection by `:<c-r>=VisualSelection()` at command line. 

I might tried to get the selected text before calling find_files and fill it, but my vimscript/lua knowledge is quite limited.

The above also includes a mapping for grep_string, which is easier as it provides a parameter for search string.

**Comment by kcivkulis** [comment]
I also wanted something similar. I added
```
  local selected_text = (function()
      vim.cmd('noau normal! "vy"')
      local text = vim.fn.getreg('v')
      vim.fn.setreg('v', {})
      text = string.gsub(text, "\n", "")
      if string.len(text) == 0 then
          text = nil
      end
      return text
    end
  )()
```

and changed `default_text = opts.default_text,` to `default_text = selected_text or opts.default_text,` in function `Picker:new()`. This automatically prefills selected text for any picker, and it works with both visual and visual line modes. It uses "v" register, but that's OK for me.

I would like to know if there is more elegant way to get selected text without using registers though.

**Comment by trevorwhitney** [comment]
FWIW, the following worked for me for `live_grep`, similar to @kcivkulis's solution where I take over a register to copy the text (and then escape the heck out it!):
```
xnoremap <leader>* "sy:Telescope live_grep default_text=<C-R>=substitute(substitute(escape(substitute(@s, '\', '\\\\\\', 'g'), ' '), '\n', '', 'g'), '/', '\\/', 'g')"<cr><cr>
```

**Comment by Conni2461** [comment]
prefilling the query with any text works for all pickers using the `default_text` option. Closing
