### ISSUE TITLE
Buffer close and keep window open

### ISSUE THREAD

**Issue by dahmc** [nvim-telescope/telescope.nvim#906]
**Is your feature request related to a problem? Please describe.**
I saw the commit https://github.com/nvim-telescope/telescope.nvim/commit/495f84fd35e7b5bb0bb670e232725924b3b85b88 which introduced the ability to delete buffers directly from the buffer list, which is awesome!

However, when I close it, the split gets closed as well. I usually have 3 splits next to each other, and I would love to keep them open.

**Describe the solution you'd like**
Currently I use https://github.com/romgrk/barbar.nvim for the bufferline/tabline, and it comes with a `:BufferClose` command that's basically what https://github.com/moll/vim-bbye does as well. It closes the buffer, but keeps the split open.

Is there a possibility to implement this in Telescope as well, maybe as either an option to the command or that we can run `:BufferClose` on the currently highlighted buffer in the list?

**Comment by tami5** [comment]
> Not sure whether it should be part of telescope.nvim but here is a function that you can easily use to overwrite buffers to be deleted with empty buffers.

Oh that's very useful, thanks @fdschmidt93 . I believe it should. Although, commonly with plugins and hacks that closes a buffer without closing the window is reverting back to the previous buffer in the window list.

**Comment by fdschmidt93** [comment]
> Although, commonly with plugins and hacks that closes a buffer without closing the window is reverting back to the previous buffer in the window list.

To clarify, what would the preferred logic be (doesn't have to mirror bbye exactly). A few variants come to mind -
* Just open the previous buffer (essentially `:bprevious` w/ buffer deletion included), in which case this `bprevious` buffer might already be opened somewhere
* Open the previous buffer that's not yet currently opened (at least in the current tab)
* Callback to pick a replacement buffer with telescope?

With an empty buffer being a fallback/selection option in all three cases I suppose.

In any case, I'm afraid I'm not versed in vimscript but from what I see vim-bbye (and hence barbar) does it a bit more complicated than we'd need to (and the logic isn't perfectly clear to me from reading vimscript I'm afraid :sweat_smile: ), though I might be mistaken. 

Happy to take a crack at it some time, once the desired feature is laid out a bit more clearly :)

**Comment by dahmc** [comment]
Thanks @fdschmidt93 

I think just open the previous buffer, and fallback to empty if no more buffers sounds very reasonable. That would be awesome :)

**Comment by fdschmidt93** [comment]
```lua
local action_state = require 'telescope.actions.state'
require'telescope'.setup {
  pickers = {
    buffers = {
      mappings = {
        i = {
          ["<C-x>"] = function(prompt_bufnr)
            local current_picker = action_state.get_current_picker(prompt_bufnr)
            local selected_bufnr = action_state.get_selected_entry().bufnr

            --- get buffers with lower number
            local replacement_buffers = {}
            for entry in current_picker.manager:iter() do
              if entry.bufnr < selected_bufnr then
                table.insert(replacement_buffers, 1, entry.bufnr)
              end
            end

            current_picker:delete_selection(function(selection)
              local bufnr = selection.bufnr
              -- get associated window(s)
              local winids = vim.fn.win_findbuf(bufnr)
              -- verify to only close windows with current buffer
              local tabwins = vim.api.nvim_tabpage_list_wins(0)
              -- fill winids with new empty buffers
              for _, winid in ipairs(winids) do
                if vim.tbl_contains(tabwins, winid) then
                  local new_buf = vim.F.if_nil(table.remove(replacement_buffers),
                 -- if not found, create unlisted scratch buffer
                                               vim.api.nvim_create_buf(false, true))
                  vim.api.nvim_win_set_buf(winid, new_buf)
                end
              end
              -- remove buffer at last
              vim.api.nvim_buf_delete(bufnr, {force = true})
            end)
          end
        }
      }
    },
  }
}
```

Does this implement the desired functionality?

**Comment by dahmc** [comment]
@fdschmidt93 damn, that's beautiful. 
That works flawlessly from the tests that I just did.

Thank you so much!
