### ISSUE TITLE
Default to using :h 'tags' in builtin.tags

### ISSUE THREAD

**Issue by milisims** [nvim-telescope/telescope.nvim#909]
**Is your feature request related to a problem? Please describe.**
`:Telescope tags` uses a file named `'tags'` to find tags, or `ctags_file` in opts if supplied. The `:tag` command uses the `:h 'tags'` option to find tags, so I think it's a good default to behave how other vim tag finding functions (i.e. `C-]`) behave.

**Describe the solution you'd like**
Instead of defaulting to `'tags'` in [the implementation](https://github.com/nvim-telescope/telescope.nvim/blob/398a0d391aa2afcda1521a8e86b820ffb599b60b/lua/telescope/builtin/files.lua#L445), default to `vim.opt.tags:get()`, and loop over it.

EDIT: TIL `opt:get()`

**Describe alternatives you've considered**
Setting `ctags_file` to the first value of `'tags'`, which might be insufficient. `vim.fn.tagfiles()` expands the tags option to valid files.

**Comment by Conni2461** [comment]
See https://github.com/nvim-telescope/telescope.nvim/pull/288 sadly was abandon. Someone needs to pick it up again

**Comment by milisims** [comment]
I made a quick and dirty change for anyone else looking for this. I just wrapped a loop around the processing that was already there.

Either apply [this patch](https://pastebin.com/3ZaSUHNt) or replace [these lines](https://github.com/nvim-telescope/telescope.nvim/blob/398a0d391aa2afcda1521a8e86b820ffb599b60b/lua/telescope/builtin/files.lua#L445-L457) with:

``` vim
  local tagfiles = opts.ctags_file or vim.fn.tagfiles()
  if type(tagfiles) == 'string' then tagfiles = { tagfiles } end

  if vim.tbl_isempty(tagfiles) then
    print('there are no tagfiles (opts.ctags_file or &tags)')
    return
  end

  local results = {}
  for _, ctags_file in ipairs(tagfiles) do
    local fd = assert(vim.loop.fs_open(vim.fn.expand(ctags_file, true), "r", 438))
    local stat = assert(vim.loop.fs_fstat(fd))
    local data = assert(vim.loop.fs_read(fd, stat.size, 0))
    assert(vim.loop.fs_close(fd))

    local fileresults = vim.split(data, '\n')
    for i=1,#fileresults do
      results[#results + 1] = fileresults[i]
    end
  end

  if vim.tbl_isempty(results) then
    print('there are no tags in tagfiles: ' .. table.concat(tagfiles, ', '))
    return
  end
```
