### ISSUE TITLE
Recent file opens as blank when PWD is not home directory

### ISSUE THREAD

**Issue by riddlew** [nvim-telescope/telescope.nvim#912]
### Description
If I have a file that is located in my home directory (say for example, C:\Users\username\projects\file.py), it will only open if my current directory is set to my home directory. If I cd to C:\Users\username, the file opens correctly. However, if I'm in a different directory such as C:\Users\username\Downloads, the file opens as blank. The tab's title also displays as "~projects\file.py". This issue only happens on my Windows machine and works fine on Linux.

**Expected Behavior**
File opens correctly.

**Actual Behavior**
Blank file opens.

### Details

<details><summary>Reproduce</summary>

1. Open file located in home directory (C:\Users\username\projects\file).
2. Change directory to a different file in home directory (C:\Users\username\Downloads).
3. Try to open recent file.
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1160-g0f7b6b2ef
- Operating system: Windows
- Telescope commit: 398a0d3

</details>

**Comment by l-kershaw** [comment]
I _**think**_ that this should have been fixed by nvim-lua/plenary.nvim#279

@riddlew can you confirm if this fixes your issue?

**Comment by riddlew** [comment]
> 

I just checked, and from what I can see it seems to have fixed the issue!
