### ISSUE TITLE
Add action.esc

### ISSUE THREAD

**Issue by mn-dimension** [nvim-telescope/telescope.nvim#915]
**Description**
Enable key mapping to allow esc into normal mode.
e.g. In insert  map `jj` and `kk` to `"\<esc>"`

**Describe the solution you'd like**
The below works but it might be better to have it as part of the available actions.
Introduce actions.esc implemented something like:

``` lua
local function esc(_)
	vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<esc>', true, true, true),'',true)
end
```

use like this

```
telescope.setup{
	defaults = {
		mappings = {
			i = {
			  ["jj"] =  esc,
			  ["kk"] =  esc,
                        }
                }
       }
}
```

**Comment by Conni2461** [comment]
Already possible. Something like this should work
```lua
telescope.setup{
  defaults = {
    mappings = {
      i = {
        ["jj"] = { "<esc>", type = "command" },
        ["kk"] = { "<esc>", type = "command" }
      }
    }
  }
}

**Comment by mn-dimension** [comment]
Cool.

--
The Continium

On 15 June 2021 at 18:56:50, Simon Hauser ***@***.******@***.***>) wrote:

Already possible. Something like this should work

telescope.setup{
  defaults = {
    mappings = {
      i = {
        ["jj"] = { "<esc>", type = "command" },
        ["kk"] = { "<esc>", type = "command" }
      }
    }
  }
}

**Comment by Conni2461** [comment]
Closing no reason to keep this open :)
