### ISSUE TITLE
Question: Sort by file modified/changed/accessed

### ISSUE THREAD

**Issue by thecontinium** [nvim-telescope/telescope.nvim#916]
Hi

Is there currently a way to sort by file attributes like modified time.

I amended the find_files find_command to sort by modified time

``` lua
find_command = {'rg', '--no-heading', '--with-filename', '--line-number', '--column', '--smart-case', '--sort=modified'},
```

but this has no effect as I think the files are sorted again by a telescope sorter before they are displayed.

**Comment by Conni2461** [comment]
There is `Telescope oldfiles` which does mru and frecency https://github.com/nvim-telescope/telescope-frecency.nvim which does smart mru

**Comment by thecontinium** [comment]
Cheers - I’ll take a look.

--
The Continium


On 18 June 2021 at 08:15:52, Simon Hauser ***@***.******@***.***>) wrote:

There is Telescope oldfiles which does mru and frecency https://github.com/nvim-telescope/telescope-frecency.nvim which does smart mru

**Comment by Conni2461** [comment]
Closing I guess. Stale for quite some time
