### ISSUE TITLE
live_grep not finding results that rg does

### ISSUE THREAD

**Issue by jemag** [nvim-telescope/telescope.nvim#917]
### Description
live_grep cannot find text in some specific situations, like within strings like "git::ssh://git@ssh.dev.azure.com/v3/AKS/TerraformModules//aks/?ref=v0.0.22". See "Reproduce" section for details

**Expected Behavior**
live_grep finds text

**Actual Behavior**
live_grep doesn't find it

### Details

<details><summary>Reproduce</summary>

1. Create file test.txt with following content
```
zing

  /* source         = "git::ssh://git@ssh.dev.azure.com/v3/AKS/TerraformModules//aks/?ref=v0.0.22" */
  source         = "/home/jemag/Projects/AKS/TerraformModules//aks/"
zong
```
2. In the directory containing test.txt. Test out following rg search
```
rg --color=never --no-heading --with-filename --line-number --column --smart-case terraformmodules
```
Results should be: 
![image](https://user-images.githubusercontent.com/7985687/122297838-fe972a00-cec9-11eb-9823-d6a6e9b7e1e9.png)
3. nvim -nu test.vim test.txt
2. use ":Telescope live_grep" and enter terraformmodules
Result should be 
![image](https://user-images.githubusercontent.com/7985687/122297994-300ff580-ceca-11eb-9256-b5abade62d5c.png)

3. Notice that 1 result is missing
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev+1415-g19ccda230
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/sbin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_F
LOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/jemag/Projects/github-reference/neovim/src/build/config -I/home/jemag/Projects/github-reference/neovim/src/src -I/home/jemag/Projects/github-reference/neovim/src/.deps/usr/include -I/usr/include -I/home/jemag/Projects/github-reference/neovim/src/build/src/nvi
m/auto -I/home/jemag/Projects/github-reference/neovim/src/build/include
Compiled by jemag

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/jemag/Projects/github-reference/neovim/build/share/nvim"

Run :checkhealth for more info
```
- Operating system: Arch wsl
- Telescope commit: 6ac5ee0854fe02d651cadf2fc97a2463ff92f322

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment]
Sorry to say that but works as expected on linux 
![image](https://user-images.githubusercontent.com/15233006/122345568-49f01d80-cf48-11eb-85fc-4266d1f27837.png)

**Comment by jemag** [comment]
It seems that loading nvim with 
`nvim -nu test.vim test.txt`
was still loading my telescope config.
It works properly with
`nvim --noplugin -u test.vim test.txt`

And within my config, it seems that the following line is the problem:
```
    file_ignore_patterns = { 'node_modules', '.git' },
```
I was under the impression that this would only ignore files matching that pattern, which wouldn't apply in this case for the text. Am I missing something?

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope.nvim/blob/6ac5ee0854fe02d651cadf2fc97a2463ff92f322/lua/telescope/pickers.lua#L1043

I wanna know which maintainers fault that is ... :rofl: We want something like this (I think)

https://github.com/nvim-telescope/telescope.nvim/blob/6ac5ee0854fe02d651cadf2fc97a2463ff92f322/lua/telescope/previewers/buffer_previewer.lua#L328

**Comment by Conni2461** [comment]
To explain it better. `entry.value` will be preferred which is okay for `find_files` but for `live_grep`/`grep_string`: `entry.value` is the whole rg line output.

**Comment by Conni2461** [comment]
File ignore patterns is fixed and this issue is no longer a thing. Closing feel free to reopen if I am wrong
