### ISSUE TITLE
find_files doesn't show dot file(files starting with a '.')

### ISSUE THREAD

**Issue by samrath2007** [nvim-telescope/telescope.nvim#918]
![image](https://user-images.githubusercontent.com/69572668/122337027-5af65a00-cf5b-11eb-9de1-dd15b132d7b8.png)
![image](https://user-images.githubusercontent.com/69572668/122337046-60ec3b00-cf5b-11eb-9cb8-2eb46ff5f37c.png)

**Comment by Conni2461** [comment]
Files starting with a dot are hidden. Most of the time you don't want to see them but you can with this
`Telescope find_files hidden=true`

**Comment by Conni2461** [comment]
I think i answer that question. Closing. Feel free to reopen if it doesn't work

**Comment by samrath2007** [comment]
> I think i answer that question. Closing. Feel free to reopen if it doesn't work

I forgot to close it, my bad

**Comment by kaykhan** [comment]
Has this changed recently? i never had this option but in the latest version (dot) files like .eslintrc.json do not show up.

**Comment by kaykhan** [comment]
Recently had to add the following: https://github.com/nvim-telescope/telescope.nvim/wiki/Configuration-Recipes#file-and-text-search-in-hidden-files-and-directories

```
telescope.setup({
	pickers = {
		find_files = {
			-- `hidden = true` will still show the inside of `.git/` as it's not `.gitignore`d.
			find_command = { "rg", "--files", "--hidden", "--glob", "!**/.git/*" },
		},
	},
})
```
