### ISSUE TITLE
Need to press <C-q> twice for it to work

### ISSUE THREAD

**Issue by svanharmelen** [nvim-telescope/telescope.nvim#919]
### Description
I remapped these:

```
local actions = require('telescope.actions')
require('telescope').setup{
  defaults = {
    mappings = {
      i = {
        ["<C-j>"]   = actions.move_selection_next,
        ["<C-k>"]   = actions.move_selection_previous,
        ["<C-q>"]   = actions.smart_send_to_qflist + actions.open_qflist,
        ["<ESC>"]   = actions.close,
      },
    },
  }
}
```

But when I press `<C-q>` nothing happens. If I press it again, it works as expected. If I instead map it to `<C-a>` it work the first time as well. I did try to search for anything else being mapped to `<C-q>` (using :verbose map <C-q>) but could not find anything...

I also tried to remove the `ESC` mapping so I could escape to normal mode and the press `<C-q>`, but in that case I also had to press it twice...

**Expected Behavior**
Trigger on the first invocation of `<C-q>`

**Actual Behavior**
Nothing happens the first time, only after pressing `<C-q>` again executes the action.

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :Telescope find_files
3. Press `<C-q>`
4. Nothing happens
5. Press `<C-q>` again, now the action works as expected

</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1398-gd09b8ad71
- Operating system: MacOS 11.4
- Telescope commit: 6ac5ee0

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

local actions = require('telescope.actions')
require('telescope').setup{
  defaults = {
    mappings = {
      i = {
        ["<C-j>"]   = actions.move_selection_next,
        ["<C-k>"]   = actions.move_selection_previous,
        ["<C-q>"]   = actions.smart_send_to_qflist + actions.open_qflist,
        ["<ESC>"]   = actions.close,
      }
    }
  }
}
EOF
```

**Comment by fdschmidt93** [comment]
Does this issue still persist with updated neovim and telescope?

I think this is a MacOS / terminal issue rather than a telescope issue. Please check that your terminal is receiving the adequate key codes (I'm afraid I don't know how to do that on Mac). Another thing is to try another terminal emulator (kitty works well for me as a suggestion).

I'm preemptively closing this as it is stale and extremely unlikely to be an immediate telescope problem. I'm happy to try and help; just ping me here if none of my suggestions work.

**Comment by svanharmelen** [comment]
Just tried Kitty and it indeed seems to work as expected using that. I'll have a closer look at my Alacritty config and/or see if switching to Kitty might be an option (I was actually already thinking a bit about that). Thanks!

**Comment by fdschmidt93** [comment]
Yeah I also switched at some point. I like ligatures (and underlining which I don't use looks cool). Further, Kitty is slightly faster (less input delay and rendering is also a bit faster actually, check the config for optimal settings) though setting the fonts is a bit of a funny business :sweat_smile: 

Glad we've been able to pin down the problem :)
