### ISSUE TITLE
(Status) Busy Summertime

### ISSUE THREAD

**Issue by tjdevries** [nvim-telescope/telescope.nvim#921]
Hi everyone :)

It's me, your telescope maintainer.

Just wanted to give everyone a heads up that I've been quite busy this summer. My wife and I have been trying to take some time off to spend time with our son (Neil, the future founder of NeilVim) since this is the first time we've been able to go anywhere with him :laughing: as well as various other personal things (trying to release nvim 0.5, new job, streaming, church, attempting to play basketball, etc.). 

I'll be out again next week, but I've got some big plans in the works for Telescope (when I can get around with it) in relative priority order:
- [x] Merge big update to layout configuration [PR](https://github.com/nvim-telescope/telescope.nvim/pull/823)
- [x] Write new job system for plenary.nvim using latest async updates (live grep speed up part 1) [PR](https://github.com/nvim-lua/plenary.nvim/pull/183)
- [x] Make live grep & other things more async-ish (live grep speed up part 2) (may have to make other architectural changes) [PR](https://github.com/nvim-telescope/telescope.nvim/pull/987)
- [ ] Multi-select actions [PR](https://github.com/nvim-telescope/telescope.nvim/pull/807)
- [x] Scrolling through results [Issue](https://github.com/nvim-telescope/telescope.nvim/issues/42)

Anyway, just wanted to say hey and thanks for using the project :)

- TJ

**Comment by rebuilt** [comment]
Thank you for the work you've put into it.  You rock!

**Comment by runiq** [comment]
Take all the time you need, guys. Here's to one great summer :)

**Comment by tjdevries** [comment]
Closing, no longer summertime.

Also got done most of the stuff on the list. I am currently spending most of my Open Source time on Lua Autocmds for neovim. After that is further along or I am tired of smashing my face against C code, I will try and do some more stuff here.

I have some plans for larger ideas that will hopefully ease the maintainence burden of the project.

With love from your friendly OSS maintainer,

TJ
