### ISSUE TITLE
No results showing

### ISSUE THREAD

**Issue by JaydenElliott** [nvim-telescope/telescope.nvim#923]
### Description
I followed the Plug install method, and when using :Telescope find_files I receive a blank results
and preview panel. When searching for files, they remain blank.
I am using the default telescope settings.

**Expected Behavior**
Files showing when searching

**Actual Behavior**
No files showing

### Details

1. Followed getting started steps
2. :Telescope find_files

nvim version: NVIM v0.5.0-dev+1405-g2f0e5e7e6

**Comment by tami5** [comment]
Odd, what's your OS? do you have either ripgrep, fd, or find  installed. Are you trying to find in a folder with dotfiles only?

**Comment by JaydenElliott** [comment]
@tami5, i'm using PopOs and I do have ripgrep and fd-find installed. I've tried across many different directories.

**Comment by tami5** [comment]
hmmm 🤔 , do you have all telescope dependencies installed? 
try :cd ~/ | Telescope fd<CR>

**Comment by JaydenElliott** [comment]
@tami5 I believe so. I tried that command and again the results and file preview are blank. 
The number of results in the "find files" section is showing, and if I click enter, a new file does get selected. Could it possibly be the text colour not being shown?

**Comment by Conni2461** [comment]
Does this happen with `nvim -nu minimalrc.vim` and the minimal rc from the bug template? Also please full `nvim --version` output.

**Comment by rbozan** [comment]
I actually have the same on Windows.

NVIM v0.5.0-dev+1421-ga72dfec85

**Comment by JaydenElliott** [comment]
I used the rc from the bug template and it still didn't work.

nvim --version output

```
NVIM v0.5.0-dev+1405-g2f0e5e7e6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az65-333

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info


```

**Comment by JaydenElliott** [comment]
I upgraded from an older nightly to the latest and that seemed to fix the problem.
