### ISSUE TITLE
Telescope file finder doesn't list particular file names

### ISSUE THREAD

**Issue by mortezadadgar** [nvim-telescope/telescope.nvim#924]
well it's so wierd that file names neo-git and neogit doesn't get listed in telescope
![image](https://user-images.githubusercontent.com/27911493/122579685-afc1cf80-d044-11eb-995f-076693f4d262.png)
![image](https://user-images.githubusercontent.com/27911493/122579497-80ab5e00-d044-11eb-9c4f-377322801283.png)

telescope [config](https://github.com/mortezadadgar/dotfiles/blob/master/nvim/.config/nvim/lua/telescope-nvim.lua) file

**Comment by Conni2461** [comment]
I don't think this is weird. You are ignoring `.git`. File ignores are a regex so, `.` can be any character, so you are ignoring any substr that has any character followed by `git`. Try ignoring `%.git`

**Comment by mortezadadgar** [comment]
> I don't think this is weird. You are ignoring `.git`. File ignores are a regex so, `.` can be any character, so you are ignoring any substr that has any character followed by `git`. Try ignoring `%.git`

Oh right I didn't know it's following regex patterns, closing now.
