### ISSUE TITLE
Autocompletion in Telescope writes to files when typing <Enter>.

### ISSUE THREAD

**Issue by vzytoi** [nvim-telescope/telescope.nvim#928]
### The problem

Hello, I use [TabNine](https://github.com/codota/tabnine-vim) for my autocompletion. This autocompletion is activated in the Telescope search bar and the first autocompletion result is executed when I click <Enter> on the file in question. For example, if the first autocompletion result when I write to Telescope is `dear` then when I click <Enter>, several operations will have been done: `de` will have deleted a word and `ar` will have inserted the letter "r". When I try to remove this change with u, it's as if it was never done and it remains even if I go back using [UndoTree](https://github.com/mbbill/undotree) to days ago.  According to #161, I tried this solution, which did not work ` autocmd! FileType TelescopePrompt set completeopt=menuone`.

### Plugins

I don't have very specific configurations, here are the **plugins** that are related to this problem:

- Plug 'nvim-lua/popup.nvim'
- Plug 'nvim-lua/plenary.nvim'
- Plug 'nvim-telescope/telescope.nvim'
- Plug 'nvim-telescope/telescope-fzy-native.nvim'
- Plug 'codota/tabnine-vim'

### Configuration

My telescope **configuration** file :

```
lua << EOF
local actions = require('telescope.actions')
require('telescope').setup {
  defaults = {
    file_sorter = require('telescope.sorters').get_fzy_sorter,
    prompt_prefix = '$ ',
    color_devicons = true,
    mappings = {
      n = {
        ["<c-c>"] = actions.close,
        ["<esc>"] = actions.close
        },
      i = {
        ["<c-j>"] = actions.move_selection_next,
        ["<c-k>"] = actions.move_selection_previous,
        ["<a-s-e>"] = actions.close,
        ["<a-s-s>"] = actions.close,
        ["<a-s-c>"] = actions.close
        }
      }
    },
  extensions = {
    fzu_native = {
      override_generic_sorter = false,
      override_file_sorter = true
      }
    },
  }

require('telescope').load_extension('fzy_native')
EOF
```

### Informations

**Version:** `NVIM v0.5.0-dev+1398-gd09b8ad71`
**OS:** `Windows 10 20H2 (KB5004476)`

**Comment by vzytoi** [comment]
I don't really understand ... Why is [YouCompleteMe](https://github.com/ycm-core/YouCompleteMe) related to TabNine?

**Comment by Conni2461** [comment]
Because tabNine is a youcompleteme fork https://github.com/codota/tabnine-vim#note . I linked you the tabnine doc page

**Comment by vzytoi** [comment]
Oh ok, anyway your solution was a good idea but didn't work. I should maybe try asking on their repo

**Comment by vzytoi** [comment]
@Conni2461, my problem had already been mentionned and solved [here](https://github.com/codota/tabnine-vim/pull/76/commits/b14d1ea163729664c1cf7f52a3194ebc53c35147). 
I just had to delete the 394th line of my `youcompleteme.vim`
Thank you.
