### ISSUE TITLE
How to select files to open in another window

### ISSUE THREAD

**Issue by sandangel** [nvim-telescope/telescope.nvim#929]
**Is your feature request related to a problem? Please describe.**
I usually use `telescope find_files` in defx/nvim-tree window to narrow down the file scope I need to search. 

the problem is telescope will open that file in `defx` window if I select it. 

I tried to add a pre/post hook to `action_set.select` to run `wincmd w` before opening that file but it doesn't work because it looks like telescope requires the origin window id
https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/actions/init.lua#L202

Is there any workaround for this issue? Can we change to telescope to get the current window id after the pre hook function is done?

**Comment by Conni2461** [comment]
We wanted to introduce something like this https://github.com/nvim-telescope/telescope.nvim/pull/745 some time ago
