### ISSUE TITLE
Change match mode when searching

### ISSUE THREAD

**Issue by kdurant** [nvim-telescope/telescope.nvim#930]
1.    'NameOnly' - fuzzy mode, match file name only when searching
2.    'FullPath' - fuzzy mode, match full path when searching
3.    'Fuzzy' - fuzzy mode, when lines in the result are not file path
4.    'Regex' - regex mode

**Comment by AgentCosmic** [comment]
+1 for this.

I've been using CtrlP with name only matching and it's **much** more accurate than Telescope. With Telescope I have to type much more, and often will not narrow down to what I want despite being very verbose.

**Comment by Conni2461** [comment]
https://github.com/nvim-telescope/telescope-fzf-native.nvim lets you switch between fuzzy, prefix, suffix and exact. Does this work for you?

**Comment by AgentCosmic** [comment]
I actually started using `get_fzy_sorter` which seems to work well enough. That plugin looks interesting, will check it out.

**Comment by Conni2461** [comment]
Closing as stale/wontfix. Also i think we have support for most of this.
