### ISSUE TITLE
Highlight matching words in previewers

### ISSUE THREAD

**Issue by liubog2008** [nvim-telescope/telescope.nvim#933]
Now only the line is highlighted.

**Comment by Conni2461** [comment]
We currently dont do anything with a column in any picker. But for the future we can. So if the the picker provides a column (and maybe col_width) we could make this possible but if not i think line highlighting is enough. Shouldn't be hard to implement we just need to make sure we arn't breaking builtins that do not provide it.

https://github.com/nvim-telescope/telescope.nvim/blob/6ac5ee0854fe02d651cadf2fc97a2463ff92f322/lua/telescope/previewers/buffer_previewer.lua#L299

We would need to change this to something like this:

```lua
if col and col_width then
  pcall(vim.api.nvim_buf_add_highlight, bufnr, ns_previewer, "TelescopePreviewLine", lnum - 1, col - 1, col + col_width + 1)
else
  pcall(vim.api.nvim_buf_add_highlight, bufnr, ns_previewer, "TelescopePreviewLine", lnum - 1, 0, -1)
end
```

or similar

**Comment by DasGandlaf** [comment]
Any news on this? I would prefer it this way actually. Or better yet, highlight the whole line with a background color, and highlight the colums with the text color.

**Comment by 416207298** [comment]
By the way, I would like to know how to change the color of matching word? 
![image](https://user-images.githubusercontent.com/19567041/226824457-fed3d25c-7d13-471b-9fcf-91a7a71deebe.png)

**Comment by 416207298** [comment]
> By the way, I would like to know how to change the color of matching word? ![image](https://user-images.githubusercontent.com/19567041/226824457-fed3d25c-7d13-471b-9fcf-91a7a71deebe.png)

Sorry to ask so beginner question, I found the hl group, which is `TelescopeMatching`.
