### ISSUE TITLE
Is there a way to do a file find on a specific directory?

### ISSUE THREAD

**Issue by Corey-Keller** [nvim-telescope/telescope.nvim#936]
For example, in my setup with FZF I have `<leader>fv` open a file finder specifically for the `stdpath('config')`

**Comment by clason** [comment]
Yes:
```lua
builtin.find_files{ cwd = vim.fn.stdpath('config') }
```

**Comment by clason** [comment]
(Usage questions are better asked in https://gitter.im/nvim-telescope/community)
