### ISSUE TITLE
Control + n not working in :Telescope registers

### ISSUE THREAD

**Issue by freezboltz** [nvim-telescope/telescope.nvim#937]
### Description

**Expected Behavior**

Should return list of register
**Actual Behavior**

provided a screenshot below
### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :Telescope registers
3. getting E5108 error
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1444-gc1120ad0e
- Operating system: manjaro latest
- Telescope commit: 6ac5ee0

</details>

<details><summary>Configuration</summary>
<p>

### Reproduce

- config details are provided below

- after that steps shown in provided gif

After selecting a register getting this error.
E5108: Error executing lua ...ed/telescope.nvim/lua/telescope/actions/init.lua:283: attempt to index local 'entry' (a nil value)

**Comment by l-kershaw** [comment]
I can't reproduce this on my machine.

Could you give more detail on your setup and steps that you can take to reproduce the error?
There are quite a few missing sections in the bug template.

**Comment by freezboltz** [comment]
I am using Plug  plugin manager
These are the plugins i am usiing
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-telescope/telescope-fzy-native.nvim'

Telescope settings
```lua
local actions = require('telescope.actions')
require('telescope').setup {
    defaults = {
        file_sorter = require('telescope.sorters').get_fzy_sorter,
        prompt_prefix = ' $ ',
        color_devicons = true,

        file_previewer   = require('telescope.previewers').vim_buffer_cat.new,
        grep_previewer   = require('telescope.previewers').vim_buffer_vimgrep.new,
        qflist_previewer = require('telescope.previewers').vim_buffer_qflist.new,

        mappings = {
            i = {
                ["<C-x>"] = false,
                ["<C-q>"] = actions.send_to_qflist,
            },
        }
    },
    extensions = {
        fzy_native = {
            override_generic_sorter = false,
            override_file_sorter = true,
        }
    }
}

require('telescope').load_extension('fzy_native')
```

my remap
nnoremap <Leader>reg :lua require('telescope.builtin').registers()<CR>

![neovim_reg_bug](https://user-images.githubusercontent.com/58996975/123503949-cfc04700-d673-11eb-9b08-80314e15a08d.png)
A screenshot of buffer is provided hope it will help @l-kershaw

**Comment by freezboltz** [comment]
![telescoperegisters](https://user-images.githubusercontent.com/58996975/123507901-deb1f400-d689-11eb-8a33-dcefae8c49a8.gif)
:Telescope registers

**Comment by freezboltz** [comment]
> I can't reproduce this on my machine.
> 
> Could you give more detail on your setup and steps that you can take to reproduce the error?
> There are quite a few missing sections in the bug template.

updated my bug template

**Comment by l-kershaw** [comment]
Thanks for more info @freezboltz
I still can't reproduce you issue, but while trying to I found other issues with `:Telescope registers` (see #940).

I'll have more of a look next week, and see if I can figure it out.

**Comment by freezboltz** [comment]
> Thanks for more info @freezboltz
> I still can't reproduce you issue, but while trying to I found other issues with `:Telescope registers` (see #940).
> 
> I'll have more of a look next week, and see if I can figure it out.

commit:  fe145b8

Fixed my `control + n` issue.
Thanks @l-kershaw for the fix.
![issue_937_940](https://user-images.githubusercontent.com/58996975/123534204-00b67f80-d739-11eb-8a1b-434bb2d3f536.gif)

**Comment by l-kershaw** [comment]
I don't really understand how this fixed your issue in the previous recording.
Glad its now working though 😅
