### ISSUE TITLE
Proximity sort and tiebreak==index

### ISSUE THREAD

**Issue by ten3roberts** [nvim-telescope/telescope.nvim#939]
**Is your feature request related to a problem? Please describe.**
When coding in a larger codebase many files in different directories usually have a similar or the same name. An example of this is `mod.rs` in rust.

**Describe the solution you'd like**
When using fzf.vim, you can pipe use `'fd | proximity-sort' .. fn.expand('%')`, along with `tiebreak==index` which will sort the files based on distance to the current file.

This means that typing `mod` in a rust project, will select the module file of the current file.

**Describe alternatives you've considered**
One solution I've tried is to change the find_files find_command, but that doesn't work as the order isn't preserved when the fzf sorter is run, because it prefers `length` on tiebreak, not `index`.

Another solution to this issue would be to be able to tiebreak `index`, instead of the default `length`

**Comment by dbalatero** [comment]
I'm also interested in a solution to this. I did this with fzf.vim to get `rg --files | proximity-sort` working:

https://github.com/dbalatero/dotfiles/blob/master/nvim/init.vim#L407-L418

and would love to port this solution to telescope.nvim.

**Comment by fdschmidt93** [comment]
> and would love to port this solution to telescope.nvim.

PR very welcome :) You can start from [here](https://github.com/nvim-telescope/telescope.nvim/pull/987#discussion_r686623272) and see also comments on this [PR](https://github.com/nvim-telescope/telescope.nvim/pull/1242).

**Comment by dbalatero** [comment]
Cool! I've actually found that telescope doesn't really perform well on my company's monorepo, so I'm back to fzf.vim which seems to be the only thing in the entire [Neovim, Emacs] ecosystem I've found that works for me so far. If the performance improves I'll probably come back here and want this feature again, so I can probably pick it up then. I'll keep any eye on telescope in the meantime. Thanks!

**Comment by TC72** [comment]
I've just added a pr for this #1401

**Comment by Conni2461** [comment]
#1401 was merged. Is this issue resolved ?

**Comment by fdschmidt93** [comment]
Pretty sure this can be done now. Closing. If there's a follow up, please open a new feature request. Thanks.

**Comment by dmvinson** [comment]
Hey, sorry to revive this thread, how could I use the new tiebreak function feature to implement proximity sort as a sorter?

**Comment by Nukesor** [comment]
Hello everybody.

I know this thread is closed, but it's still the very first thing that pops up when one searches for proximity search in telescope.
Since I wasn't really satisfied with the capabilities of tiebreak, I decided to dig into telescope a bit and came up with my own picker that uses `fd` and `proximity-search` under the hood.

It's a live picker that bypasses telescopes own sorters and filter to solely rely on fd for filtering and proximity-search for sorting.

I hope this helps anybody that wants the old  `fzf` functionality in telescope :)

```lua
-- Custom proximity search implementation
local conf = require("telescope.config").values
local finders = require "telescope.finders"
local make_entry = require "telescope.make_entry"
local pickers = require "telescope.pickers"
local sorters = require "telescope.sorters"

function starts_with(str, prefix)
    return string.sub(str, 1, string.len(prefix)) == prefix
end

local function get_relative_buffer_path()
    local full_path = vim.api.nvim_buf_get_name(0)
    -- In case one of the following conditions apply, use the cwd.
    -- - We aren't in a file buffer.
    -- - The filename is empty.
    -- - The path isn't absolut.e.
    if full_path == nil or
        full_path == '' or
        not starts_with(full_path, '/') then
        return '.'
    end

    -- Return the relative path of the buffer to the current cwd.
    -- That's what proxmity sort expects.
    local cwd = vim.fn.getcwd()
    local relative_path = string.gsub(full_path, cwd .. '/', '')
    -- Fallback to the cwd if:
    -- - The full_path equals the cwd.
    -- - We're in a neo-tree buffer
    if relative_path == '' or starts_with(full_path, 'neo-tree') then
        return '.'
    end
    return relative_path
end

-- A file picker based on the the proximity of files relative to the
-- file in the current buffer.
-- Requires the `proximity-sort` and `fd` binaries to be present.
local proximity_files = function(opts)
    local path = get_relative_buffer_path()
    -- print(string.format("Relative proximity path: '%s'", path))

    local live_fd = finders.new_job(
        function(prompt)
            if not prompt or prompt == "" then
                prompt = "."
            end

            local cmd = {
                "bash",
                "-c",
                string.format('fd --type f %s . | proximity-sort %s', prompt, path),
            }
            -- print("Cmd: ", vim.inspect(cmd))
            return cmd
        end,
        opts.entry_maker or make_entry.gen_from_file(opts),
        opts.max_results,
        opts.cwd
    )

    pickers
        .new(opts, {
            prompt_title = "Proximity Files",
            finder = live_fd,
            previewer = conf.file_previewer(opts),
            sorter = sorters.highlighter_only(opts),
            push_cursor_on_edit = true,
            __locations_input = true,
        })
        :find()
end

vim.keymap.set("n", "<C-p>", function() proximity_files({}) end)
```

**Comment by Nukesor** [comment]
Thinking about it, it might be a really nice idea to extract the `proximity-sort` functionality into a custom sorter.
That shouldn't be too problematic and lua might be fast enough for this to not feel sluggish.

Maybe somebody wants to give this a shot :smirk:. The algorithm seems rather simple.
https://github.com/jonhoo/proximity-sort/blob/main/src/main.rs#L55
