### ISSUE TITLE
Fade background when Telescope buffer is active

### ISSUE THREAD

**Issue by pmdaly** [nvim-telescope/telescope.nvim#942]
**Is your feature request related to a problem? Please describe**
No real problem, but a feature request.  Is it possible to fade or blur the background vim windows/panes when the Telescope buffer is active to allow better focus on the search experience?

**Additional context**
In a quick search I found the following

The idea is here but not implemented correctly, may be a good starting point.
```
hi ActiveWindow ctermbg=None ctermfg=None guibg=#21242b
hi InactiveWindow ctermbg=darkgray ctermfg=gray guibg=#282c34
set winhighlight=Normal:ActiveWindow,NormalNC:InactiveWindow
```

Another addon that fades inactive buffers.
https://github.com/TaDaa/vimade

I don't have a good example of blur 

@tjdevries referencing my comment in Discord

**Comment by l-kershaw** [comment]
I'm not sure how much value this adds to Telescope. Using Telescope alongside vimade seems to work quite well for blurring the background when Telescope is open.

What do you think including this in Telescope adds compared to using both Telescope and vimade?

**Comment by elianiva** [comment]
also, see https://github.com/sunjon/shade.nvim

**Comment by siduck76** [comment]
shade.nvim works flawlessly for this purpose. check : 


https://user-images.githubusercontent.com/59060246/125773706-d82e0019-89eb-4ecf-b21f-b14902c22591.mp4

**Comment by l-kershaw** [comment]
I think since other plugins implement this well, and there don't seem to be compatibility issues with Telescope, there isn't much benefit to implementing this functionality here.

Closing

**Comment by hinell** [comment]
Shading/fading inactive buffer isn't useful really.
