### ISSUE TITLE
Latest commit (#922) breaks Telescope and many of my other plugins

### ISSUE THREAD

**Issue by mroavi** [nvim-telescope/telescope.nvim#945]
### Description
After pulling the changes of the latest commit (feat: Consistent and sensible layout_config (#922)), many of my other plugins report the following error:
```vim
packer.nvim: Error running config for tmux-navigator: ...e/mroavi/.config/nvim/lua/mrv/plugins/tmux-navigator.lua:1: Vim:Deprecated window options. Please see ':help telescope.changelog'
packer.nvim: Error running config for delimitmate: /home/mroavi/.config/nvim/lua/mrv/plugins/delimitmate.lua:1: Vim:Deprecated window options. Please see ':help telescope.changelog'
packer.nvim: Error running config for vim-floaterm: /home/mroavi/.config/nvim/lua/mrv/plugins/floaterm.lua:1: Vim:Deprecated window options. Please see ':help telescope.changelog'
```

Telescope and the rest of my plugins were working fine before pulling the latest commit.

**Expected Behavior**
Telescope and all other plugins to work correctly.

**Actual Behavior**
Telescope does not work and neither do many of my other plugins. Removing Telescope gets rid of the messages in the other plugins.

### Details

Run `PackerSync`
Close nvim and reopen it.

- nvim --version: NVIM v0.5.0-dev+1459-g384f9870f
- Operating system:
        NAME="Manjaro Linux"
        ID=manjaro
        ID_LIKE=arch
        BUILD_ID=rolling
        PRETTY_NAME="Manjaro Linux"
        ANSI_COLOR="32;1;24;144;200"
        HOME_URL="https://manjaro.org/"
        DOCUMENTATION_URL="https://wiki.manjaro.org/"
        SUPPORT_URL="https://manjaro.org/"
        BUG_REPORT_URL="https://bugs.manjaro.org/"
        LOGO=manjarolinux
- nvim --version output:
    NVIM v0.5.0-dev+1459-g384f9870f
    Build type: RelWithDebInfo
    LuaJIT 2.1.0-beta3
    Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
    Compiled by runner@fv-az139-878

  Features: +acl +iconv +tui
  See ":help feature-compile"
  
     system vimrc file: "$VIM/sysinit.vim"
    fall-back for $VIM: "/share/nvim"

- Telescope commit: 5a53ec5 - (4 hours ago) feat: Consistent and sensible layout_config (#922)

If you need more info, I would be more than happy to provide it to you guys.

**Comment by clason** [comment]
Did you read the mentioned document and adapted your own config to the breaking changes?

**Comment by mroavi** [comment]
I did. I'm going to read it one more time.

**Comment by clason** [comment]
Yes, this is (intentionally) a breaking change that requires (minor) adaptation of user config.

**Comment by mroavi** [comment]
Commenting out `prompt_position = "bottom"` did the job. Thanks for your answer. Helped me pinpoint the problem with my config faster.
