### ISSUE TITLE
Option to remove devicon from the result

### ISSUE THREAD

**Issue by vinitkumar** [nvim-telescope/telescope.nvim#946]
### Description

I want to hide the icons from appearing in the telescope file buffers. Here is my config for telescope.

I am using neovim with Telescope. I want to hide the devicons but it doesn't seem to work for me.

<img width="467" alt="Screenshot 2021-07-01 at 9 55 47 PM" src="https://user-images.githubusercontent.com/537678/124158063-19b38d80-dab7-11eb-9ccb-374f446ff6b6.png">

**Expected Behavior**

The devicons should hide now.

**Actual Behavior**
The devicons are still visible.

### Details

<details><summary>Reproduce</summary>

- Open NVIM on an existing project
- Toggle telescope to run and search for any file
- Devicons are still visible
 
</details>

<details><summary>Environment</summary>

- nvim --version output:  NVIM v0.5.0-dev+1449-gbdf3df402 Build type: Release
- Operating system:  macOS 11.4
- Telescope commit: Latest stable

</details>

<details><summary>Configuration</summary>
<p>

```viml
lua <<EOF
-- https://github.com/nvim-telescope/telescope.nvim
local M = {}

M.setup = function()
  require("telescope").setup({
  defaults = {
    prompt_prefix = "❯ ",
    selection_caret = "❯ ",

    disable_devicons = true,
    winblend = 0,

    layout_strategy = "horizontal",
    layout_config = {
      width = 0.8,
      height = 0.85,
      preview_cutoff = 120,

      horizontal = {
        -- width_padding = 0.1,
        -- height_padding = 0.1,
        preview_width = 0.6,
      },

      vertical = {
        -- width_padding = 0.05,
        -- height_padding = 1,
        width = 0.9,
        height = 0.95,
        preview_height = 0.5,
      },

      flex = {
        horizontal = {
          preview_width = 0.9,
        },
      },
    },

    selection_strategy = "reset",
    prompt_position = "top",
    sorting_strategy = "descending",
    scroll_strategy = "cycle",
    color_devicons = false,
    },
  })

  require("telescope").load_extension("fzy_native")
end
EOF
```

**Comment by Conni2461** [comment]
You are not able to do this on `setup` level but you can either just uninstall https://github.com/kyazdani42/nvim-web-devicons and they should disappear if you don't want them, or `Telescope find_files disable_devicons=true` should work. The option should work for all  builtins that use devicons

**Comment by l-kershaw** [comment]
In addition to the above, it looks like you aren't actually calling `require('telescope').setup`, as it is called inside the function `M.setup`, which is itself not called.
You can also tell this by the fact that your `selection_caret` in your picture does not match that in your config.

From the look of the config provided here (and a quick glance at your nvim config [link](https://github.com/vinitkumar/nvim/blob/master/init.vim)) I would suggest removing the lines
```
local M = {}

M.setup = function()
```
at the beginning and the line
```
end
```
before the EOF.

This should allow the other options that you have set (e.g. `selection_caret`) to take effect.

**Comment by vinitkumar** [comment]
Thank you for time, will try this.

**Comment by vinitkumar** [comment]
> In addition to the above, it looks like you aren't actually calling `require('telescope').setup`, as it is called inside the function `M.setup`, which is itself not called.
> You can also tell this by the fact that your `selection_caret` in your picture does not match that in your config.
> 
> From the look of the config provided here (and a quick glance at your nvim config [link](https://github.com/vinitkumar/nvim/blob/master/init.vim)) I would suggest removing the lines
> 
> ```
> local M = {}
> 
> M.setup = function()
> ```
> 
> at the beginning and the line
> 
> ```
> end
> ```
> 
> before the EOF.
> 
> This should allow the other options that you have set (e.g. `selection_caret`) to take effect.

```lua << EOF
require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_prefix = "> ",
    selection_caret = "> ",
    entry_prefix = "  ",
    initial_mode = "insert",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_config = {
      horizontal = {
        mirror = false,
      },
      vertical = {
        mirror = false,
      },
    },
    file_sorter =  require'telescope.sorters'.get_fuzzy_file,
    file_ignore_patterns = {},
    generic_sorter =  require'telescope.sorters'.get_generic_fuzzy_sorter,
    shorten_path = true,
    winblend = 0,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
    color_devicons = false,
    disable_devicons = true,
    use_less = true,
    set_env = { ['COLORTERM'] = 'truecolor' }, -- default = nil,
    file_previewer = require'telescope.previewers'.vim_buffer_cat.new,
    grep_previewer = require'telescope.previewers'.vim_buffer_vimgrep.new,
    qflist_previewer = require'telescope.previewers'.vim_buffer_qflist.new,

    -- Developer configurations: Not meant for general override
    buffer_previewer_maker = require'telescope.previewers'.buffer_previewer_maker
  }
}

EOF```

Still doesn't work, not sure what I am doing wrong here.

**Comment by vinitkumar** [comment]
> Telescope find_files disable_devicons=true

This works for me. I don't need to add any config in my init.vim, right?

**Comment by l-kershaw** [comment]
If you are happy to use:

> Telescope find_files disable_devicons=true

every time, then you don't require any config relating to devicons.

If you want to have something more perminant, you could add:
```
pickers = {
  find_files = {
    disable_devicons = true
  },
},
```
in the following position
```
    -- Developer configurations: Not meant for general override
    buffer_previewer_maker = require'telescope.previewers'.buffer_previewer_maker
  },
--> HERE
}

EOF
```

This then means that whenever you call:
```
Telescope find_files
```
it will show the files with the devicons disabled.

**Comment by vinitkumar** [comment]
> If you are happy to use:
> 
> > Telescope find_files disable_devicons=true
> 
> every time, then you don't require any config relating to devicons.
> 
> If you want to have something more permanent, you could add:
> 
> ```
> pickers = {
>   find_files = {
>     disable_devicons = true
>   },
> },
> ```
> 
> in the following position
> 
> ```
>     -- Developer configurations: Not meant for general override
>     buffer_previewer_maker = require'telescope.previewers'.buffer_previewer_maker
>   },
> --> HERE
> }
> 
> EOF
> ```
> 
> This then means that whenever you call:
> 
> ```
> Telescope find_files
> ```
> 
> it will show the files with the devicons disabled.

Awesome. It just works. Thanks for taking the time to help out. Much appreciated. Will close this ticket now.

**Comment by l-kershaw** [comment]
No worries, happy to help 🙂
