### ISSUE TITLE
Prompt on top?

### ISSUE THREAD

**Issue by numToStr** [nvim-telescope/telescope.nvim#948]
**Is your feature request related to a problem? Please describe.**
Because of the recent changes in layout configuration, `prompt_position` is now gone. I was wondering is there any easy way to make the prompt appear on top as I would like to read everything from top to bottom.

I am also using `sorting_strategy = "ascending"`.

**Describe the solution you'd like**
Maybe another `layout_strategy` config.

**Additional context**
Before, my telescope looks like this.
![image](https://user-images.githubusercontent.com/24727447/124240316-4065d880-db38-11eb-9fc8-171801882096.png)

Now
![image](https://user-images.githubusercontent.com/24727447/124240626-8ae75500-db38-11eb-8958-19aba680f3dd.png)

**Comment by dhruvmanila** [comment]
`prompt_position` is moved to `layout_config.prompt_position`

```lua
layout_config = {
  prompt_position = "top",
}
```

**Comment by Conni2461** [comment]
Also see `:help telescope.changelog`

**Comment by numToStr** [comment]
> `prompt_position` is moved to `layout_config.prompt_position`
> 
> ```lua
> layout_config = {
>   prompt_position = "top",
> }
> ```

This seems to be the solution. Thanks!
