### ISSUE TITLE
Layout flex not working after layout_config update

### ISSUE THREAD

**Issue by gabrielbidula** [nvim-telescope/telescope.nvim#949]
Hi guys,

Before the update on the layout_config, I was able to have the layout_strategy set to flex which was adapting and displaying both prompt and preview on split windows ie: tmux vertical and horizontal split. I wonder if this feature still working, maybe I have to do some changes.

This is my setup before the update:

```
require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case',
      '--fixed-strings'
    },
    prompt_position = "top",
    sorting_strategy = "ascending",
    layout_strategy = "flex",
    winblend = 5,
    layout_defaults = {
      horizontal = {
        width_padding = 0.1,
        height_padding = 0.1,
        preview_width = 0.6,
      },
      vertical = {
        width_padding = 0.05,
        height_padding = 1,
        preview_height = 0.5,
      }
    },
  }
}
```

Unfortunately, I do not have any print of the previous behavior but this is how it was working.

<img width="1918" alt="Screenshot 2021-07-03 at 00 16 18" src="https://user-images.githubusercontent.com/1028654/124333443-8486c680-db94-11eb-8625-0214a4d7d845.png">

Thanks!

**Comment by l-kershaw** [comment]
The layout configuration PR changes some of the ways that users adjust the layout of Telescope pickers.

The key changes that affect your config seem to be:
- `layout_defaults` has been renamed to `layout_config`
- `width_padding` and `height_padding` have been deprecated in favour of passing tables like `{padding = 5}` to `width` and `height`
- `prompt_position` has been moved inside of `layout_config` (as it changes the layout configuration)

More details are available in the `:help telescope.changelog`

---

For your config, I think something like this would work:
```
require('telescope').setup({
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case',
      '--fixed-strings'
    },
    sorting_strategy = "ascending",
    layout_strategy = "flex",
    winblend = 5,
    layout_config = {
      prompt_position = "top",
      horizontal = {
        width = {padding = 0.1},
        height = {padding = 0.1},
        preview_width = 0.6,
      },
      vertical = {
        width = {padding = 0.05},
        height = {padding = 1},
        preview_height = 0.5,
      }
    },
  }
})
```

**Comment by gabrielbidula** [comment]
@l-kershaw Hi, thanks for the reply. The config you provided did not work, the preview does not show up on split/vertical. I will take a look at the documentation tho.

<img width="1918" alt="Screenshot 2021-07-03 at 14 41 54" src="https://user-images.githubusercontent.com/1028654/124354552-d9662380-dc0c-11eb-91d4-4fc999a4a690.png">

**Comment by Conni2461** [comment]
try to play around with the `preview_cutoff` option

**Comment by gabrielbidula** [comment]
Nice @Conni2461, seems to be working as expected now. I added` preview_cutoff = 40.`

<img width="1920" alt="Screenshot 2021-07-03 at 14 52 11" src="https://user-images.githubusercontent.com/1028654/124354835-580f9080-dc0e-11eb-91f0-7c3706177e03.png">

**Comment by Conni2461** [comment]
Its mentioned and explain in `:help telescope.defaults.layout_config` and `:help layout_strategies.horizontal`, etc. I think thats enough. We are working on reducing the documentation in the readme and make everything less confusing. The help file will be THE documentation for telescope in the future.

Glad it works again for you :) Closing for now. Feel free to reopen if have more issues :)

**Comment by gabrielbidula** [comment]
Makes sense, Thanks!
