### ISSUE TITLE
Builtin autocommands: cursor outside of buffer

### ISSUE THREAD

**Issue by ram02z** [nvim-telescope/telescope.nvim#957]
### Description

**Expected Behavior**

Open Telescope autocommands without an error

**Actual Behavior**

Telescope autocommands opens with the following error:
`Error executing vim.schedule lua callback: ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:746: Cursor position outside buffer`

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2.  `:Telescope autocommands`
3. Error flashes in command line
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.6.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-0Km7d0/neovim-0.5.0+ubuntu2+git202107031758-75f758b99-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-0Km7d0/neovim-0.5.0+ubuntu2+git202107031758-75f758b99-d569569c9/build/config -I/build/neovim-0Km7d0/neovim-0.5.0+ubuntu2+git202107031758-75f758b99-d569569c9/src -I/build/neovim-0Km7d0/neovim-0.5.0+ubuntu2+git202107031758-75f758b99-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-0Km7d0/neovim-0.5.0+ubuntu2+git202107031758-75f758b99-d569569c9/build/src/nvim/auto -I/build/neovim-0Km7d0/neovim-0.5.0+ubuntu2+git202107031758-75f758b99-d569569c9/build/include Compiled by buildd@lgw01-amd64-021  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

```
- Operating system: Ubuntu 20.04
- Telescope commit: 38907ce7d74f26d123bfbb8ecf55bc9616b5ece5

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua require('telescope').setup()
```

**Comment by clason** [comment]
(also happens to me on the latest versions of everything)

**Comment by Conni2461** [comment]
yep the `+1` at line 746 shouldn't be there. only `{selected_row, 0}` should be correct

**Comment by ram02z** [comment]
@Conni2461 I removed the `+1` locally and the error is gone. There is also a `+1` for `selected_row` on line 745, not sure if that is correct.

**Comment by akinsho** [comment]
Going to (annoyingly) verbally +1 this, rather than silently 👍🏿 , in the hope that the linked PR gets merged 🙏🏿

**Comment by Conni2461** [comment]
My bad i overlooked it :laughing: Thanks for bumping it

**Comment by akinsho** [comment]
Hmm so I'm actually still seeing this issue which I thought had been resolved primarily when I open a buffer in a new tab from telescope's buffer picker. Could there be a 1 based index type issue?

**Comment by Conni2461** [comment]
@akinsho this was probably introduced by https://github.com/nvim-telescope/telescope.nvim/commit/79dc995f820150d5de880c08e814af327ff7e965 

I dont think its a of by one issue here. I havent run into this issue (but i also have preview disabled for buffer)

Can you open a new issue with steps to reproduce it? That would be awesome. Thanks :)
