### ISSUE TITLE
Empty find_files result after updating to 38907ce

### ISSUE THREAD

**Issue by tommyalatalo** [nvim-telescope/telescope.nvim#958]
### Description
The `find_files` function has stopped working after doing a `:PlugUpdate` yesterday.

**Expected Behavior**
`:Telescope find_files` should display all files found recursively in the current folder.

**Actual Behavior**
`:Telescope find_files` does not show any files found, just a dialog with empty "Results" and "Preview" boxes.
An error is also displayed:

```
Error executing vim.schedule lua callback: ...ugged/telescope.nvim/lua/telescope/algos/linked_list.lua:77: attempt to index field '_tracked_node' (a nil value)
Error executing vim.schedule lua callback: ...lugged/telescope.nvim/lua/telescope/pickers/scroller.lua:59: Must never return a negative row: { result = -3, args = { -2 6 -3 } }
```

### Details
<details><summary>Reproduce</summary>

1. place `telescope.lua` in `.config/nvim/lua/username/telescope.lua`
2. add `lua require('username')*
3. start nvim in a folder with files
4. run `:Telescope find_files` -> no results

</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
❯ nvim --version
NVIM v0.5.0-dev+1423-ge2d3ad7bc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az139-869

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
- Operating system: Arch Linux
- Telescope commit: 38907ce

</details>

<details><summary>Configuration</summary>
<p>

```lua
local actions = require('telescope.actions')
require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_prefix = " ❯ ",
    selection_caret = "❯ ",
    entry_prefix = "  ",
    initial_mode = "insert",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",

    layout_config = {
      horizontal = {
        mirror = false,
      },
      vertical = {
        mirror = false,
      },
      preview_cutoff = 120,
      prompt_position = "bottom",
      height = 1,
      width = 0.75,
    },

    mappings = {
      i = {
        ["<esc>"] = actions.close
      },
    },


    file_sorter =  require('telescope.sorters').get_fzy_sorter,
    file_ignore_patterns = {"^.git[/]"},
    generic_sorter =  require('telescope.sorters').get_generic_fuzzy_sorter,
    shorten_path = true,
    winblend = 0,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰' },
    color_devicons = true,
    use_less = true,
    set_env = { ['COLORTERM'] = 'truecolor' }, -- default = nil,
    file_previewer = require('telescope.previewers').vim_buffer_cat.new,
    grep_previewer = require('telescope.previewers').vim_buffer_vimgrep.new,
    qflist_previewer = require('telescope.previewers').vim_buffer_qflist.new,

    -- Developer configurations: Not meant for general override
    buffer_previewer_maker = require('telescope.previewers').buffer_previewer_maker
  },
  extensions = {
    fzy_native = {
        override_generic_sorter = false,
        override_file_sorter = true,
    }
  }
}


require('telescope').load_extension('fzy_native')
T = {}
T.search_dotfiles = function()
	require('telescope.builtin').find_files({
		prompt_title = "< dotfiles >",
		cwd = "~/dotfiles/",
		hidden = "true",
	})
end

T.git_branches = function()
	require('telescope.builtin').git_branches({
      attach_mappings = function(prompt_bufnr, map)
        map('i','<c-d>', actions.git_delete_branch)
        map('n','<c-d>', actions.git_delete_branch)
        return true
      end
	})
end
return T
```

**Comment by Conni2461** [comment]
`height = 1,` seems to be the problem. Any reason why setting it to `1` in the first place?

**Comment by tommyalatalo** [comment]
> `height = 1,` seems to be the problem. Any reason why setting it to `1` in the first place?
> 
> Edit: just removing fixes your issue (for me)

I just copied over the value from the deprecated `results_height` I had from before. 
I think the value came from an example found somewhere.

**Comment by Conni2461** [comment]
`result_height` previously only had an effect on layout center. I think the previous readme said 1 but it didnt effected horizontal layout. Now it does so 1 is no longer a good value.

I didnt find any mention of 1 being a good value in the current documentation.

**Comment by tommyalatalo** [comment]
> `result_height` previously only had an effect on layout center. I think the previous readme said 1 but it didnt effected horizontal layout. Now it does so 1 is no longer a good value.
> 
> I didnt find any mention of 1 being a good value in the current documentation.

Yeah this is a value that I just carried over to the new `height` parameter which, as you say, behaves differently.
The difference in behavior was not mentioned in the `:help telescope.changelog-922` notes either, so I didn't catch it.

Where do you find the documentation for the current `height` parameter? I looked in the docs on github, but didn't find any mention of it specifically.

**Comment by Conni2461** [comment]
Yeah we forgot to mention it in changelog :grimacing: happens was a really big pr ;)

`height` is now more specific to the layout_strategy so you find help under `help telescope.layout`. For horizontal:  `help layout_strategies.horizontal()`

**Comment by tommyalatalo** [comment]
Thanks, I will close this issue, this discussion might be a good reference for someone else stumbling on the same thing though.
