### ISSUE TITLE
mapping <C-m> to keymaps() maps <CR>  to keymaps() too

### ISSUE THREAD

**Issue by shaeinst** [nvim-telescope/telescope.nvim#960]
### Description
so  i mapped ctrl+m to keymaps() as
`nnoremap <c-m> <cmd>lua require('telescope.builtin').keymaps() <CR>`
 but somehow it's also mapping **\<CR\>/Enter** to **keymaps()**. 
i tried with other keys, like **\<c-g\>** or **\<leader\>m**, they works fine.

**Expected Behavior**
it's \<C-m\> that must open keymaps() only, not \<CR\> 

**Actual Behavior**
when i press enter in normal mode, mapping window opens. problem gets solved when i map anything rather than \<C-m\>

- nvim --v0.5.0
- Arch Linux

**Comment by Conni2461** [comment]
hmm i dont see how this is a telescope issue.

I can reproduce this behavior when running neovim with `nvim -nu NORC` and doing `nnoremap <c-m> :echo "hello, world!"<cr>`. After that `nnoremap <cr>` shows that mapping.

I cannot reproduce this issue with `vim -nu NORC` (version 8.2.2891)

**Comment by shaeinst** [comment]
because this is a bug in neovim, i opened new issues there [#15021](https://github.com/neovim/neovim/issues/15021#issue-939467665).
