### ISSUE TITLE
Custom `path_display` using callback

### ISSUE THREAD

**Issue by DanielPower** [nvim-telescope/telescope.nvim#961]
**Is your feature request related to a problem? Please describe.**
There are currently several options available for `path_display`. They can be combined, but there doesn't appear to be an option to add a custom display.

For example, I would like to display paths using a similar style to what VS Code displays.

`file_name.js /src/path/file_name.js`

This ensures that if your window isn't large enough to see the full path, you at least get the most important part, the file name.

**Describe the solution you'd like**
Instead of `path_display` taking an array of pre-defined display styles, `path_display` could be a function, whose argument is the full path to the file, and which returns a formatted string that Telescope should display.

Additionally the callback could be passed a second argument, which is the width of the file list, so that the function can handle shortening appropriately.

Telescope could expose some default options, so that the current styles are possible without writing any additional code.

Example:
`path_display = require('telescope').path_formatters.shorten`.

Or they can be combined without much effort, to get the effect of `path_display = { absolute, shorten }`.

Example:
```
path_display = function(path, width)
  absolute = telescope.path_formatters.absolute(path, width)
  return telescope.path_formatters.shorten(absolute, width)
end
```

**Describe alternatives you've considered**
Provide an option for `path_display` that formats the path similarly to VS Code. However, I do feel that allowing it to be customized with a function is more powerful.

**Comment by Conni2461** [comment]
I think this is exactly the pr that tries to achieve what you want (re `path_display = { absolute, shorten }`) https://github.com/nvim-telescope/telescope.nvim/pull/839

tj wanted to do some work there so i haven't touched it

**Comment by Conni2461** [comment]
#839 is merged we could now talk about `path_display` being a function that returns a string.

**Comment by DanielPower** [comment]
> I think this is exactly the pr that tries to achieve what you want (re `path_display = { absolute, shorten }`) #839
> 
> tj wanted to do some work there so i haven't touched it

I personally don't want `path_display = { absolute, shorten }`. I was giving an example of how the proposal of a callback function could provide the same functionality that already exists. Referencing this wiki page which states that options can be combined: https://github.com/nvim-telescope/telescope.nvim/wiki/Path-Display-Configuration

So it would be a breaking change, but it would be relatively simple to update a config from the current usage of pre-defined string values, to equivalent callbacks.

What I would personally like to use would be something like this:

```lua
path_display = function(path)
  segments = split(path, '/') -- split implementation left out for simplicity
  filename = segments[#segments]
  return filename .. " " .. path
end
```

This would result in the `file_name.js /src/path/file_name.js` output that I would personally like to use.

**Comment by Conni2461** [comment]
So that wiki page wasn't valid before today, `path_display` was introduced today and the person that wrote it, wrote the wiki page before we merged it.

PRs are always welcome :) (i am just currently the only one who is really reviewing things, so things take a little only).

So i dont thing it will be a breaking change, we could make `opts.path_display` either a table or a function. 

So we have this util function which now handles all path related things:
https://github.com/nvim-telescope/telescope.nvim/blob/1dd6f8408b6e3334ddba695a7c4e0fd500f9bff6/lua/telescope/utils.lua#L285

And now we can check if `path_display` is of type function then do `return path_display(path)` and thats it. All thats missing is that either `path_display` can be passed via opts and if its not passed via opts then we could still have a `path_display` in config.

**Comment by Nazeehe** [comment]
I actually have that implemented in a local branch on my machine. The ability to specify a function that gets called to format the display. I think I saw the OP mention the idea in some thread and decided to go try it out. I haven't contributed anything to telescope before though, so I would need to get familiar with the process. 

It is pretty cool for sure. Nice to be able to fully control the path display formatting.

**Comment by Conni2461** [comment]
The process is simple. You fork the repo, make a new branch. Push the changes to this branch and open a PR. I (or another maintainer) will then review your submission a little bit later and provide some feedback. The last step will continue till we are all happy with the contribution, then we merge it :)

You might wanna give https://github.com/nvim-telescope/telescope.nvim/blob/master/CONTRIBUTING.md a quick read before submitting something. I'll can help you with where we would add the documentation, when the PR is submitted :)

**Comment by Nazeehe** [comment]
Sweet. Thanks for the quick info. I kicked off the process and have my changes in my fork now. I will finish it up (docs, etc) and send out a PR. 

Thanks!

**Comment by Nazeehe** [comment]
PR submitted. Looking forward to feedback. 

https://github.com/nvim-telescope/telescope.nvim/pull/1000

**Comment by Conni2461** [comment]
`path_display` can now be a function.

```lua
path_display = function(opts, path)
  local tail = require("telescope.utils").path_tail(path)
  return string.format("%s (%s)", tail, path)
 end
```
Thanks to @Nazeehe 

Closing for now
