### ISSUE TITLE
find_files with cwd doesn't open right files when already in dir

### ISSUE THREAD

**Issue by postylem** [nvim-telescope/telescope.nvim#962]
### Description

For the file picker `builtin.find_files`, when setting the `cwd` option to the actual current working directory, preview works fine, but the file does not open (instead it opens a nonexistent version of a file in the absolute root directory, rather than relative to the cwd)

Say I'm in a directory `~/dir` which contains a file `~/dir/example.txt`, and I opened neovim like this:

```zsh
cd ~/dir && nvim
```

Then, inside nvim, I want to run `:Telescope find_files cwd="~/dir/"` to browse files within that directory (of course I don't need to set cwd, but let's say this is a custom function that lets me access files in `dir` from anywhere, and this time I just happen to be there already.)

**Expected Behavior**

`:Telescope find_files cwd="~/dir/"` should open the telescope viewer and I should be able to find files there, and open them.  Like I should be able to open '~/dir/example.txt` by selecting it and pressing return.

**Actual Behavior**

Browsing works (I can browse `~/dir/`, and see a preview of `example.txt` in the Preview window). 
**However**, when I press enter, it opens a new buffer viewing  `/example.txt` (in the _absolute_ root directory), rather than `~/dir/example.txt` = `./example.txt` like it should.

If I run the exact same steps from any other directory (that is, for example, if I start out launching nvim like `cd ~ && nvim`), then I don't get this problem.  Browsing with `:Telescope find_files cwd="~/dir/"` works as before, and opening files works as it should.

**My temporary fix**:
If I use `:Telescope find_files cwd="~/dir"` (note, no final slash), then it works perfectly from any directory.
This is a perfectly usable fix, but the above behaviour is unexpected... I think I may have found a bug (or at least it should be mentioned somewhere that a final slash breaks something).

I imagine this should be pretty easy to fix, but it surprised me, and I'd also be intrigued to know why it's happening.

### Details

<details><summary>Reproduce</summary>

1. run `mkdir ~/dir && cd ~/dir && echo "Hi from example.txt" > example.txt && nvim`
2. `:Telescope find_files cwd="~/dir/"`
3. Select `example.txt` and press enter
4. Confirm that the buffer opened is an empty one viewing `/example.txt`, rather than `./example.txt`.
    - if not, then this fails to reproduce 
</details>

<details><summary>Environment</summary>

- nvim --version output:

```
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
```

- Operating system: macOS Big Sur
- Telescope commit: 1dd6f84

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua require('telescope').setup()
```

**Comment by nc1337** [comment]
@postylem Kindly update the telescope, as this has been fixed by using `plenary.path` instead of `telescope.path`.

**Comment by postylem** [comment]
indeed! commit df579bac425e4b6b69a0c8e694b154610cd5420b (https://github.com/nvim-telescope/telescope.nvim/pull/473) fixed this issue. great!
