### ISSUE TITLE
code action?

### ISSUE THREAD

**Issue by shaeinst** [nvim-telescope/telescope.nvim#963]
i am setting up telescope for flutter/dart environment. i want code action with telescope.
in simple, i want following with telescope
```
nnoremap <leader>ca <Cmd>lua vim.lsp.buf.code_action()<CR>
xnoremap <leader>ca <Cmd>lua vim.lsp.buf.range_code_action()<CR>
```
  how to do that?

please don't mind if it's not related to telescope

**Comment by Conni2461** [comment]
See https://github.com/nvim-telescope/telescope.nvim#neovim-lsp-pickers or `:help builtin.lsp_code_actions()` or `:help builtin.lsp_range_code_actions()`

**Comment by shaeinst** [comment]
thanks,
i got it with
```
nnoremap <silent><leader>ca <cmd>lua  require('telescope.builtin').lsp_code_actions( {layout_config={width=50, height=20} } ) <CR>
```

one more question, how to get rid of this extra padding?
![screenshoot](https://user-images.githubusercontent.com/41078534/125021198-e4e89d00-e099-11eb-9dfa-492d7e92db46.png)

and one more question, when i change height=10, it hides some options, is there any way to load all option and able scroll through it?

**Comment by Conni2461** [comment]
We do not have scrolling though all results right now see https://github.com/nvim-telescope/telescope.nvim/issues/42 you would need to filter.

Also we do not have right justify for the last column, so the current approach is, get the longest title and put the provider name after that title. This feature is currently also on the roadmap

PRs welcome :)

**Comment by shaeinst** [comment]
sorry, but How?
> Also we do not have right justify for the last column, so the current approach is, get the longest title and put the provider name after that title. This feature is currently also on the roadmap

**Comment by Conni2461** [comment]
what do you mean by How? We would need to implement a right justify in our displayer (handles displaying) and then we need to use this interface in the definition of `code_action`. There is nothing you can change in your config to make it work.

If you are interested i can help you implement this feature, but its not a trivial task

**Comment by shaeinst** [comment]
I appreciate it

> If you are interested i can help you implement this feature, but its not a trivial task

**Comment by Conni2461** [comment]
Closing. Code actions work. Right justify is a different issue.
