### ISSUE TITLE
git_status doesn't take `cwd` into account

### ISSUE THREAD

**Issue by sodiumjoe** [nvim-telescope/telescope.nvim#981]
### Description

When opening nvim in a directory other than the git root, selecting/opening a file from the built-in `git_status` picker tries to open the filename relative to git root, rather than relative to cwd.

**Expected Behavior**

It should open the correct file.

**Actual Behavior**

It tries to open the filename relative to git root.

### Details

<details><summary>Reproduce</summary>
With a file structure something like:

```
project/
  .git
  subdir/
    foo.txt
```
with foo.txt modified

```
$ cd project/subdir
$ nvim -nu test.vim
:Telescope git_status
```
select `subdir/foo.txt`

It tries to open `subdir/subdir/foo.txt`.
</details>

<details><summary>Environment</summary>

- nvim --version output:
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info

- Operating system: macos big sur 11.4
- Telescope commit: c5a6ed16e2022e2d19936e00a8a39a97cba39f11

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua require('telescope').setup()
```

**Comment by nc1337** [comment]
@sodiumjoe There is an option `use_git_root` which you can set `false` and your use case will work.

**Comment by sodiumjoe** [comment]
wow, that works great, thanks!
