### ISSUE TITLE
Is it possible for the builtin.lsp_definitions to default to a new tab?

### ISSUE THREAD

**Issue by knpwrs** [nvim-telescope/telescope.nvim#982]
When calling `builtin.lsp_definitions`, if there is only one result, the fuzzy picker is skipped and neovim navigates directly to the definition. Is there a way to make this single definition open in a new tab?

**Comment by l-kershaw** [comment]
There isn't currently an option for this, and I can't see a simple way of implementing it.
This is because the the function used to navigate to a single definition is `vim.lsp.util.jump_to_location` ([here](https://github.com/nvim-telescope/telescope.nvim/blob/999fad2ce514d869b736aa5d948d355fad89be8d/lua/telescope/builtin/lsp.lua#L68)), which doesn't have any options for this sort of thing.

If you can come up with a good way of implementing this, then I'd be happy to have a look at a PR 🙂

**Comment by knpwrs** [comment]
I'm not terribly familiar with vim scripting but the only thing that comes to mind is opening a tab to the same location (if required) and then running the command there. This works as a keybinding outside of telescope:

```vim
nnoremap gd <cmd>tab split \| lua vim.lsp.buf.definition()<cr>
```

**Comment by dhruvmanila** [comment]
You can write down your own ***LSP handler*** (_not telescope_) for this specific action. Something along the lines of:

```lua
vim.lsp.handlers["textDocument/definition"] = function(err, method, response)
  -- If there are any errors, report and exit
  if err then
    error(table.concat(err, "\n"))
  end

  -- If there are no definitions, print and exit
  if not response or vim.tbl_isempty(response) then
    vim.notify("LSP (" .. method .. ") No results found")
    return
  end

  -- Response: Location | Location[] | LocationLink[] | null
  -- https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_definition
  if vim.tbl_islist(response) then
    if vim.tbl_count(response) == 1 then
      -- there is only one definition,  open it in a new tab
    else
      -- there are more than one definitions, open the fuzzy finder
    end
  else
    -- there is only one definition,  open it in a new tab
  end
end
```

**Comment by knpwrs** [comment]
@dhruvmanila again, I'm not terribly familiar with how this all works, but doesn't that override all behavior? What if I wanted some actions for the current tab and others due a new tab? In CoC I had `gd` for go to definition and `gD` for the same in a new tab.

**Comment by zeertzjq** [comment]
I can think of an option `jump_type` whose possible values are:

- `"buffer"` (default): Jump directly
- `"tab"`: Jump in a new tab
- `"split"`: Jump in a split
- `"vsplit"` Jump in a vsplit
- `"never"`: Don't jump, show the picker instead.

**Comment by eliasdorneles** [comment]
For people arriving here from web search, this is what I'm using to obtain the behavior described by @knpwrs (`gd` for go to definition in current window and `gD` for the same in a new tab):

```
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gD :tab LspDefinition<cr>
```

**Comment by BenceBakos** [comment]
```
vim.api.nvim_buf_set_keymap(bufnr, "n", "gdt", "<cmd>tab split | lua vim.lsp.buf.definition()<CR>", opts)
```
from 

https://neovim.discourse.group/t/go-to-definition-in-new-tab/1552/4

worked for me.
