### ISSUE TITLE
Can't combine default and custom actions

### ISSUE THREAD

**Issue by TheBlob42** [nvim-telescope/telescope.nvim#983]
### Description
It seems not possible to combine any default actions (e.g. `select_default`) with a custom action using the `+` sign.

```lua
local actions = require('telescope.actions')
local transform_mod = require('telescope.actions.mt').transform_mod

local custom_actions = {}

function custom_actions.test1(prompt_bufnr)
    actions.close(prompt_bufnr)
end

function custom_actions.test2(prompt_bufnr)
    print("Test 2")
end

custom_actions = transform_mod(custom_actions)

require('telescope').setup {
    defaults = {
        mappings = {
            i = {
                ["<C-c>"] = custom_actions.test1,
                ["<CR>"] = actions.select_default + custom_actions.test2,
            }
        }
    }
}
```

Now call `Telescope find_files` and test both mappings. 
Pressing `C-c` will work fine and close the prompt buffer, but the `CR` mapping throws an error.

**Expected Behavior**
Should open the file and afterwards print "Test 2"

**Actual Behavior**
`E5108: Error executing lua ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:34: Key does not exist for 'telescope.actions': test2`

The same type of error occurs every time I want to combine a default action with a custom one.

### Details

<details><summary>Reproduce</summary>

1. Open Telescope e.g. `Telescope find_files`
2. With the above configuration press `CR`
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0
- Operating system: Pop_OS 21.04
- Telescope commit: 5692edd

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close

lua << EOF

local actions = require('telescope.actions')
local transform_mod = require('telescope.actions.mt').transform_mod

local custom_actions = {}

function custom_actions.test1(prompt_bufnr)
    actions.close(prompt_bufnr)
end

function custom_actions.test2(prompt_bufnr)
    print("Test 2")
end

custom_actions = transform_mod(custom_actions)

require('telescope').setup {
    defaults = {
        mappings = {
            i = {
                ["<C-c>"] = custom_actions.test1,
                ["<CR>"] = actions.select_default + custom_actions.test2,
            }
        }
    }
}

EOF
```

**Comment by Conni2461** [comment]
dup of https://github.com/nvim-telescope/telescope.nvim/issues/684 i explain there whats wrong. tj wants to fix it here https://github.com/nvim-telescope/telescope.nvim/pull/807

**Comment by TheBlob42** [comment]
@Conni2461 thank you for pointing this out,I have completely missed that already existing issue :see_no_evil: 

I will close this issue and subscribe to the already existing one instead :+1:
