### ISSUE TITLE
Can't find files using find command

### ISSUE THREAD

**Issue by afranioce** [nvim-telescope/telescope.nvim#984]
### Description

After the [commit](https://github.com/nvim-telescope/telescope.nvim/commit/999fad2ce514d869b736aa5d948d355fad89be8d#diff-cde19eefc57f14c96b7d86ee9758c1cc53c7021d1421e270b8a8c23bd261e306R177) is not possible find files 

**Expected Behavior**

Find files using `find` command after run the command `:Telescope find_files`

**Actual Behavior**

![image](https://user-images.githubusercontent.com/893768/125545023-0c8caaf7-37f6-43f2-a7d3-0d5692f057d6.png)

**Comment by esperz** [comment]
same issue.

**Comment by vmizener** [comment]
Issue is due assuming lua treats 0 as falsey in the [latest commit](https://github.com/nvim-telescope/telescope.nvim/blob/999fad2ce514d869b736aa5d948d355fad89be8d/lua/telescope/builtin/files.lua#L177).

**Comment by voodoojunk** [comment]
same issue

**Comment by Conni2461** [comment]
Yeah rather than `not vim.fn.has` it should be `0 == vim.fn.has`. Does someone want to provide a hotfix PR? i will merge :)

**Comment by Conni2461** [comment]
fixed by @l-kershaw https://github.com/nvim-telescope/telescope.nvim/commit/a4896e5ef39a8006a8251d48d4cf24aac81a4f94
