### ISSUE TITLE
[Question] Is it possible to display the file display history in the current directory?

### ISSUE THREAD

**Issue by nabezokodaikon** [nvim-telescope/telescope.nvim#990]
Is it possible to display the file display history in the current directory?
In `builtin.oldfiles`, the history is displayed not only in the current folder.

**Comment by l-kershaw** [comment]
Yes, this is possible (although it does not appear to be documented).
You can use the `cwd_only` option for `builtin.oldfiles`, for example:
```
:Telescope oldfiles cwd_only=v:true
```
or
```
:lua require('telescope.builtin').old_files({cwd_only=true})
```

**Comment by nabezokodaikon** [comment]
Thanks!
