### ISSUE TITLE
How do you disable folds inside pickers?

### ISSUE THREAD

**Issue by mystilleef** [nvim-telescope/telescope.nvim#991]
I have the following fold settings.

```
set foldclose=all
set foldopen=all
```

When I open pickers, navigating the result list in normal mode with j/k results in folds. Is this expected behavior, and is there a way to turn it off?

I've attached a video showing the issue.

https://user-images.githubusercontent.com/273399/125663225-fdbd8f06-9aef-40eb-9451-3938aaae03ff.mp4

**Comment by Conni2461** [comment]
We had a similar conversation over https://github.com/nvim-telescope/telescope.nvim/pull/978 we are probably introducing a `TelescopeResults` filetype so you can disable folds for that filetype (or we just disable folds for that filetype)

**Comment by Conni2461** [comment]
`TelescopeResults` is now a filetype so you can disable folds for it

**Comment by mystilleef** [comment]
For the benefit of new users, add the following to your `.vimrc`, or `init.vim` right after you initialized `Telescope`.

```vim
" disable folding in telescope's result window
autocmd! FileType TelescopeResults setlocal nofoldenable
```

It might help to also add this to the `docs` or `faq` for new users.

**Comment by Conni2461** [comment]
I am currently reworking documentation, so i'll add it :)

**Comment by arbitrary-dev** [comment]
Now also in Lua:
```
-- Disable folding in Telescope's result window.
vim.api.nvim_create_autocmd("FileType", { pattern = "TelescopeResults", command = [[setlocal nofoldenable]] })
```
