### ISSUE TITLE
sorter in :Telescope registers is not working as expected

### ISSUE THREAD

**Issue by freezboltz** [nvim-telescope/telescope.nvim#996]
### Description

Not able to sort through registers as expected

**Expected Behavior**

- After typing first letter the sorter should sort using in capital Alphabet present in between square bracket
- After pressing second letter the sorter should filter through register such as fuzzy finder

**Actual Behavior**

- In first case it works as expected
- In second case it is not fuzzy finding content but freeze in last selected item
- While typing letters all capital the last letter get sorted

#### step to reproduce issue
1. open nvim nightly
2. in command mode type Telescope registers
3. type all capital letter and see the behavior and compare with expected behavior
4. try to search for any register content the sorter will freeze in last selected item while searching
![reg_bug_sorter](https://user-images.githubusercontent.com/58996975/125788883-61d6f8c7-fdb0-4dfb-9553-9ca163b59ed4.gif)

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+5aaa1a1 
- Operating system: Manjaro latest
- Telescope commit: 37a3a68

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

local actions = require('telescope.actions')
require('telescope').setup {
    defaults = {
        file_sorter = require('telescope.sorters').get_fzy_sorter,
        prompt_prefix = ' $ ',
        color_devicons = true,

        file_previewer   = require('telescope.previewers').vim_buffer_cat.new,
        grep_previewer   = require('telescope.previewers').vim_buffer_vimgrep.new,
        qflist_previewer = require('telescope.previewers').vim_buffer_qflist.new,

        mappings = {
            i = {
                ["<C-x>"] = false,
                ["<C-q>"] = actions.send_to_qflist,
            },
        }
    },
    extensions = {
        fzy_native = {
            override_generic_sorter = false,
            override_file_sorter = true,
        }
    }
}

require('telescope').load_extension('fzy_native')

EOF
```

**Comment by l-kershaw** [comment]
The current way that `builtin.registers` works is the `ordinal` (thing that you filter against) is just the name of the register (the letter or symbol on the left in the square brackets). It also assumes that all the names for letters are capitalised. So this is working as I would expect in your recording (although I concede that the capitalisation is annoying sometimes).

---

In terms of implementing a sorter that switches between checking the _name_ of the register and the _contents_ of the register based on the length of the input prompt, I don't think that this is a simple change. It seems like this would require making the `ordinal` of the entry include both the name and content (which isn't too difficult), and then writing a custom sorter to separate the name and contents and then pass to appropriate sorters depending on the length of the prompt (which I would expect to be more involved, but I could be wrong).

If this is something you are interested in doing, then I would be happy to review a PR in this area 🙂

**Comment by freezboltz** [comment]
@l-kershaw Interest but I am new to lua so it is difficult for me to implement it.

**Comment by l-kershaw** [comment]
@freezboltz that's not a problem at all! I was new to lua two months ago when I first submitted a PR to telescope. Now I'm helping out with loads of stuff with telescope 🙂 

If you want to make a PR for this, I would be happy to help out with feedback and stuff. Even if it doesn't work properly yet, that's fine, just include WIP in the name and people will help guide with feedback 🙂

_if you still don't feel up to making a PR, that's fine. no pressure :)_

**Comment by tusqasi** [comment]
```luaM.registers = function()
    local get_levenshtein_sorter = function()
        return sorters.Sorter:new {
            scoring_function = function(_, prompt, line)
                return require "telescope.algos.string_distance"(prompt, line)
            end
        }
    end

    local make_entry_gen_from_registers = function(_)
        local displayer =
            entry_display.create {
            separator = " ",
            hl_chars = {["["] = "TelescopeBorder", ["]"] = "TelescopeBorder"},
            items = {
                {width = 3},
                {remaining = true}
            }
        }

        local make_display = function(entry)
            local content = entry.content
            return displayer {
                {"[" .. entry.value .. "]", "TelescopeResultsNumber"},
                type(content) == "string" and content:gsub("\n", "\\n") or content
            }
        end

        return function(entry)
            return {
                valid = true,
                value = entry,
                ordinal = vim.fn.getreg(entry),
                content = vim.fn.getreg(entry),
                display = make_display
            }
        end
    end
    local opts = {}
    local registers_table = {'"', "_", "#", "=", "_", "/", "*", "+", ":", ".", "%"}

    -- named
    for i = 0, 9 do
        table.insert(registers_table, tostring(i))
    end

    -- alphabetical
    for i = 65, 90 do
        table.insert(registers_table, string.char(i))
    end

    pickers.new(
        opts,
        {
            prompt_title = "Registers",
            finder = finders.new_table {
                results = registers_table,
                entry_maker = opts.entry_maker or make_entry_gen_from_registers(opts)
            },
            -- use levenshtein as n-gram doesn't support <2 char matches
            sorter = get_levenshtein_sorter(),
            attach_mappings = function(_, map)
                actions.select_default:replace(actions.paste_register)
                map("i", "<C-e>", actions.edit_register)

                return true
            end
        }
    ):find()
end
````

**Comment by tusqasi** [comment]
Changed the ordinal to the content of the register in `make_entry_gen_from_registers`.

**Comment by tusqasi** [comment]
Please check this commit, this makes using `:Telescope registers` not suck. (I think)

https://github.com/nvim-telescope/telescope.nvim/compare/master...tusqasi:telescope.nvim:register-sort-patch

**Comment by tusqasi** [comment]
@l-kershaw please check this out.

**Comment by tusqasi** [comment]
@freezboltz  try the register-sort-patch branch with
```lua
	use({
		-- "nvim-telescope/telescope.nvim",
		"tusqasi/telescope.nvim",
		branch = "register-sort-patch",
		requires = { "nvim-lua/plenary.nvim" },
	})
```

**Comment by tusqasi** [comment]
And @l-kershaw I opened the PR, what is next?

**Comment by tusqasi** [comment]
Would it make sense to sort by register name for single character input and then after 2 chars, sort by contents of the registers.

**Comment by Conni2461** [comment]
fixed in https://github.com/nvim-telescope/telescope.nvim/pull/2175
